### ISSUE TITLE
How could I set sorting param in python client

### ISSUE THREAD

**Issue by estherxyz** [kubernetes-client/python#1002]
Hi,

If use kubectl can add --sort-by param to get list after sorting by created time.
`kubectl get pods --sort-by=.metadata.creationTimestamp`
Is there any way can set sorting param in python client?
Or any param or setting could reach this?
k8s api return seems do not do sort?

Thanks.

**Comment by roycaihw** [comment]
Sort is a CLI feature in kubectl. kube-apiserver doesn't support sorting API result and the python client doesn't implement this CLI-level feature.
