### ISSUE TITLE
Cannot get Post Status "Terminated" 

### ISSUE THREAD

**Issue by bangi123** [kubernetes-client/python#1004]
**What happened (please include outputs or screenshots)**:
Code: 
kube_client = client.CoreV1Api()
kube_client.list_namespaced_pod(namespace="test")
while True:
    for pod in kube_client.get_pods_running().items:
            print(" {0} -> {2}".format(pod.status.phase, pod.status.pod_ip))

Pod Status is changing from Running to Pending, however, kubectl commmand Terminating, IS there a way to get Terminating pods. 

Output: 
Status : Running -> 10.96.3.129
Status:  Pending -> 10.96.3.129

**What you expected to happen**:
Output: 
Status : Running -> 10.96.3.129
Status: Terminating -> 10.96.3.129

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g., MacOS 10.13.6):
ubuntu 
- Python version (`python --version`)
Python 2.7.16
- Python client version (`pip list | grep kubernetes`)
kubernetes                              7.0.0

**Comment by roycaihw** [comment]
There is no `Terminating` pod phase according to https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase

My guess is that kubectl did some intelligent check of the deletion timestamp and printed `Terminating. You can run kubectl with `--v=8` to see what API response it actually received.

**Comment by bangi123** [comment]
@roycaihw: Thanks, Will close the ticket.

**Comment by megastallman** [comment]
```
            if pod.metadata.deletion_timestamp != None and pod.status.phase == 'Running':
                state = 'Terminating'
            else:
                state = str(pod.status.phase) 
```
This is actually the piece of out production code.

**Comment by svinther** [comment]
> 

It should include the Pending state as well: 

            if pod.metadata.deletion_timestamp != None and pod.status.phase in ('Pending, 'Running'):
                state = 'Terminating'
            else:
                state = str(pod.status.phase)

**Comment by alexis974** [comment]
From [PEP8](https://peps.python.org/pep-0008/#programming-recommendations):

> Comparisons to singletons like None should always be done with is or is not, never the equality operators.

Hence, a more pythonic way:

```Python
  if pod.metadata.deletion_timestamp is not None and pod.status.phase in ('Pending', 'Running'):
            state = 'Terminating'
        else:
            state = str(pod.status.phase) 
```
