### ISSUE TITLE
RoleBinding.rbac.authorization.k8s.io is invalid - Reason: Unprocessable Entity

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes-client/python#1012]
**What happened (please include outputs or screenshots)**:

I tried to create a RoleBinding, this is the body:
```
{'api_version': 'rbac.authorization.k8s.io/v1', 'kind': 'RoleBinding', 'metadata': {'name': 'oidc-foo-developers', 'namespace': 'foo-dev'}, 'subjects': [{'kind': 'Group', 'name': 'FOO-DEV', 'api_group': 'rbac.authorization.k8s.io'}], 'role_ref': {'kind': 'ClusterRole', 'name': 'oidc-developers', 'api_group': 'rbac.authorization.k8s.io'}}
```

If I try to use this payload I get this error:
```
(422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': '1db9791b-b123-4da9-8a57-cc81a6ad4379', 'Content-Type': 'application/json', 'Date': 'Thu, 21 Nov 2019 10:14:21 GMT', 'Content-Length': '631'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"RoleBinding.rbac.authorization.k8s.io \"oidc-foo-developers\" is invalid: [roleRef.kind: Unsupported value: \"\": supported values: \"Role\", \"ClusterRole\", roleRef.name: Required value]","reason":"Invalid","details":{"name":"oidc-foo-developers","group":"rbac.authorization.k8s.io","kind":"RoleBinding","causes":[{"reason":"FieldValueNotSupported","message":"Unsupported value: \"\": supported values: \"Role\", \"ClusterRole\"","field":"roleRef.kind"},{"reason":"FieldValueRequired","message":"Required value","field":"roleRef.name"}]},"code":422}
```

I tried to use 10.0.1, 9.0.1 and 8.0.2 of the library. 

**What you expected to happen**:

Rolebinding is created

**How to reproduce it (as minimally and precisely as possible)**:

As described above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): v1.14.3
- OS (e.g., MacOS 10.13.6): MacOS 10.15.1
- Python version (`python --version`) Python 3.7.5
- Python client version (`pip list | grep kubernetes`) 10.0.1

**Comment by tomplus** [comment]
It looks like it sends a malformed request. It's common in this library that the body is not a string/dict but a object. For example: [create_namespaced_role_binding](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/RbacAuthorizationV1Api.md#create_namespaced_role_binding) requires this structure [V1RoleBinding](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1RoleBinding.md) as a body.

Could you show which method do you use and how you executed it?

**Comment by pierluigilenoci** [comment]
I created the `body` manually as dict. Using objects as suggested works. I was misled by the fact that `__corev1api.create_namespace` accepts a dict.
