### ISSUE TITLE
WSClient._all grows uncontrolled and inefficiently

### ISSUE THREAD

**Issue by rawler** [kubernetes-client/python#1013]
**What happened (please include outputs or screenshots)**: When subscribing (line-by-line) to stdout of a POD, CPU increases until filling up the python-client CPU core, blocking everything else in the same process.

Cause is determined to be every line being added to WSClient._all, which grows increasingly slow since each iteration copies the existing data of WSClient._all. Commenting out "self._all += data" in ws_client.py, everything works as expected.

**What you expected to happen**: Client to progress with a steady consumption of CPU and memory.

**How to reproduce it (as minimally and precisely as possible)**:

    stream = stream.stream(self.api.connect_get_namespaced_pod_attach, name="pod_with_continuous_stdout", namespace="ns", stdout=True, _preload_content=False)
    while True:
        line = stream.readline_stdout()  # This will become increasingly expensive as WSClient._all grows
        print(line)

**Environment**:
- Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-18T14:56:51Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
- Ubuntu 19.10
- Python 3.7.5rc1
- Python client version: 10.0.1

**Comment by roycaihw** [comment]
I think we should add a method to flush the _all. Would you like to send a fix?

/help

**Comment by rawler** [comment]
I rather think the first thing to solve, is to use a more efficient method
of appending to _all, maybe using BytesIO.

Second, an opt-in flush method would almost certainly go unnoticed by
someone, until finding out the hard way, like i did. Maybe this should be
staged for next opportunity to break API, making collecting _all opt-in,
with the default being disabled?

Den tis 26 nov. 2019 19:44Kubernetes Prow Robot <notifications@github.com>
skrev:
