### ISSUE TITLE
ListThenWatch

### ISSUE THREAD

**Issue by epa095** [kubernetes-client/python#1016]
**What is the feature and why do you need it**:
I want to list the objects of some resource, and then watch for updates to it. 

As explained different places (e.g. https://github.com/kubernetes-client/python-base/pull/131#issuecomment-502737581
https://github.com/kubernetes-client/python/issues/819) one can *not* just use a ẁatch, but one has to first do a list, get the resourceVersion from the list-call itself, and then use that in the watch. I would be surprised if I am the only one who did not know this, and faulty tried to use the `watch` as a list+watch.

**Describe the solution you'd like to see**:
A list+watch functionality next to the `Watch`. 

This is related to #868, but seems like a smaller issue.

**Comment by yliaog** [comment]
i think the complete solution is an informer, so i would prefer to follow up on https://github.com/kubernetes-client/python/issues/868
