### ISSUE TITLE
Watch handles resourceVersion wrong

### ISSUE THREAD

**Issue by epa095** [kubernetes-client/python#1018]
Warning: I might have misunderstood something. Feel free to correct. 

As described several places (e.g. https://github.com/kubernetes-client/python-base/pull/131#issuecomment-502737581
https://github.com/kubernetes-client/python/issues/819) one can *not* just use a ẁatch on a "list-functon", but one has to first do a list, get the resourceVersion from the list-call itself, and then use that in the watch. 

The problem is that [watch](https://github.com/kubernetes-client/python-base/blob/a2d1024524de78b62e5f9aa72d34cb9ea9de2b97/watch/watch.py#L140) itself reapplies the provided function in an infinite loop, and if `func` is e.g. `list_namespace` (as in the example in the readme), then the correct course of action is to get the resourceVersion of *that call* and use it. But instead only the resourceVersions of the elements in the list is used.

**Comment by roycaihw** [comment]
I think we do extract the latest resource version from the apiserver response and use that: https://github.com/kubernetes-client/python-base/blob/a2d1024524de78b62e5f9aa72d34cb9ea9de2b97/watch/watch.py#L96

/close

**Comment by epa095** [comment]
> I think we do extract the latest resource version from the apiserver response and use that: https://github.com/kubernetes-client/python-base/blob/a2d1024524de78b62e5f9aa72d34cb9ea9de2b97/watch/watch.py#L96
> 
> /close

But that is the resource version for *each of the elements in the list*, not of the list itself. The resource_version exists in the response of [func](https://github.com/kubernetes-client/python-base/blob/a2d1024524de78b62e5f9aa72d34cb9ea9de2b97/watch/watch.py#L140) (at least if `func` is any of the functions `client.list_*_object`). So something like
```python
resp = func(*args, **kwargs)
resp.get("metadata", {}).get("resourceVersion", None)
```

But maybe the semantics is different because `watch` [is set to](https://github.com/kubernetes-client/python-base/blob/a2d1024524de78b62e5f9aa72d34cb9ea9de2b97/watch/watch.py#L133) `True` , and then K8s does not return a (interesting) resource_version on the list itself?

**Comment by roycaihw** [comment]
The semantics is different. The apiserver responds to watch requests with a stream of watch events. See https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes:

```
GET /api/v1/namespaces/test/pods?watch=1&resourceVersion=10245
---
200 OK
Transfer-Encoding: chunked
Content-Type: application/json
{
  "type": "ADDED",
  "object": {"kind": "Pod", "apiVersion": "v1", "metadata": {"resourceVersion": "10596", ...}, ...}
}
{
  "type": "MODIFIED",
  "object": {"kind": "Pod", "apiVersion": "v1", "metadata": {"resourceVersion": "11020", ...}, ...}
}
...
```

The python client extracts the resource version from each of the watch event. If you print the [`line`](https://github.com/kubernetes-client/python-base/blob/a2d1024524de78b62e5f9aa72d34cb9ea9de2b97/watch/watch.py#L142), you will see something like:

```
https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes
```
