### ISSUE TITLE
UNKNOWN_BASE_TYPE in documentation for patch_* methods

### ISSUE THREAD

**Issue by rihardsk** [kubernetes-client/python#1020]
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/AppsV1Api.md#patch_namespaced_deployment_scale and other `patch_*` methods.

**Description of the issue (please include outputs or screenshots if possible)**:
The type for the method's `body` parameter is `UNKNOWN_BASE_TYPE`. It's not clear to me what to pass to the method (i'm guessing `V1Scale` in this instance).

**Comment by kelajin** [comment]
It's not clear to me too

**Comment by yury-stepanov** [comment]
JFYI, I have tried to `V1Scale`, but it doesnt work apparently, so I just passing  `{"spec": {"replicas": 3}`. Seems to do the trick.

**Comment by roycaihw** [comment]
cc @tomplus 

/assign

**Comment by roycaihw** [comment]
There was no UNKNOWN_BASE_TYPE in 10.0 [client](https://github.com/kubernetes-client/python/blob/release-10.0/kubernetes/docs/AppsV1Api.md) (Kubernetes 1.14). This looks like a regression introduced by either openapi-generator or Kubernetes 1.15.

**Comment by tomplus** [comment]
It looks like openapi-generator insert it when the spec doesn't define the content-type:

https://github.com/OpenAPITools/openapi-generator/blob/c882338ef134e9c00a02fed2d2792b7eda36ea95/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L4981-L4987

In v10 we have NULL which is also incorrect:

https://github.com/kubernetes-client/python/blob/release-10.0/kubernetes/docs/AppsV1Api.md#patch_namespaced_deployment_scale

The content-type in `patch_` methods depends on the requester (ref: https://github.com/kubernetes-client/python/pull/959) and we have to agree that our auto-generated docs don't work well and need to be re-written (ref: https://github.com/kubernetes-client/python/issues/601).

**Comment by logicbomb421** [comment]
Running into this problem myself. Will the documentation be regenerated soon, or is there different documentation I can look at? Pretty new to interacting with the API directly, so not having documentation on what the body of a request should look like is somewhat tough.

**Comment by avbanks** [comment]
If anyone runs in to this issue a good way to find out what api object is needed is to edit the resource in question with kubectl edit  <resource> <name> -v 9

ex : if we wanted to patch the annotations in a pod run:

 kubectl edit pod vault-test -v 9 
then edit the annotation add test: test
now note the line "Request Body:  Request Body: {"metadata":{"annotations":{"test":test}}}"

This tells you what the body of the patch needs to be for the particular patch you're requesting (in the example case we're annotating metadata).

**Comment by pheonix991** [comment]
I can trigger this when trying to run this code.

```
from __future__ import print_function
import kubernetes
import os
from auth import EKSAuth # This is an in-house lib


KUBE_FILEPATH = '~/.kube/config'
REGION = os.environ.get('AWS_REGION', 'us-east-1')
HANGAR = os.environ.get('env_name')
CLUSTER_NAME = 'someapp-{0}-{1}'.format(SOMEVAR, REGION)
eks = EKSAuth(CLUSTER_NAME, REGION)
token = eks.get_token()
kubernetes.config.load_kube_config(KUBE_FILEPATH)
configuration = kubernetes.client.Configuration()
configuration.api_key['authorization'] = token

api_instance = kubernetes.client.CoreV1Api(
    kubernetes.client.ApiClient(configuration))

name = "ip-10-10-10-10.ec2.internal"
def main():
    body = {
        "Kind": "Node",
        "metadata": {
            name
        },
        'spec': {
            'unschedulable': True
        }
    }

    api_response = api_instance.patch_node(name, body)

    print(api_response)


if __name__ == '__main__':
    main()
```

Output:
```
Traceback (most recent call last):
  File "scratch2.py", line 40, in <module>
    main()
  File "scratch2.py", line 34, in main
    api_response = api_instance.patch_node(name, body)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 17587, in patch_node
    (data) = self.patch_node_with_http_info(name, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 17685, in patch_node_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 156, in __call_api
    body = self.sanitize_for_serialization(body)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 224, in sanitize_for_serialization
    for key, val in six.iteritems(obj_dict)}
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 224, in <dictcomp>
    for key, val in six.iteritems(obj_dict)}
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 220, in sanitize_for_serialization
    for attr, _ in six.iteritems(obj.openapi_types)
AttributeError: 'set' object has no attribute 'openapi_types'
```

Would be nice to have this fixed.

**Comment by hantmac** [comment]
Running into this problem, confusing too. 😭

**Comment by nrmitchi** [comment]
I ran into this as well last, but I think I've gotten it for the most part figured out.

The way that this is now displayed in the docs (`UNKNOWN_BASE_TYPE`) is implying that there is a given object type that should be there.

I _believe_ that the body of all of these request types is just meant to be an arbitrary `dict`, containing the same information that would be present by `patch`-ing a resource with `kubectl`: Ie,

```
kubectl patch deployment <name> -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"
```
