### ISSUE TITLE
Service certification file does not exists.

### ISSUE THREAD

**Issue by Deepakchawla** [kubernetes-client/python#1027]
`config.load_incluster_config()`
`v1 = client.CoreV1Api()`
`print("Listing pods with their IPs:")`
`ret = v1.list_pod_for_all_namespaces(watch=False)`
`for i in ret.items:`
      `     print("%s\t%s\t%s" %(i.status.pod_ip, i.metadata.namespace, i.metadata.name))`

getting this issue

> Service certification file does not exists.

**Comment by pigletfly** [comment]
have you created ServiceAccount resource?

**Comment by roycaihw** [comment]
`load_incluster_config` is used when you deploy your application within a pod and it loads the automatically mounted service account certs. Are you running your code inside a pod?

**Comment by roycaihw** [comment]
Closing the issue due to inactivity. Please reopen when you have more information for debugging

/close
