### ISSUE TITLE
Can't replicate `kubectl apply -f` functionality with Python client

### ISSUE THREAD

**Issue by Datamance** [kubernetes-client/python#1028]
**What happened (please include outputs or screenshots)**:
The kubectl CLI [uses a StrategicMergePatch type](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/apply/apply.go#L912) in the underlying API request for `apply`.

The Python client should be able to do the same by letting us pass a Content-Type of 'application/strategic-merge-patch+json' into the headers dict, but this odd little piece of generated code precludes us from doing so

https://github.com/kubernetes-client/python/blob/ccd3ce4fc27ed202864f9b3f971744a5ebf6ad7e/kubernetes/client/api/apps_v1_api.py#L3889

I would like to leverage the Python client as much as possible without resorting to `kubectl`. Is there a way to get around this for the time being?

Thanks in advance!

**Environment**:
- Kubernetes version (`kubectl version`):

- OS (e.g., MacOS 10.13.6):
10.15.1
- Python version (`python --version`)
3.8.0
- Python client version (`pip list | grep kubernetes`)
10.0.1

**Comment by Datamance** [comment]
OK, I see there appears to be [some activity on this precise issue now](https://github.com/kubernetes-client/python/pull/959). The Java client seemed to be having the same kind of issue in 2017, to boot. Codegen seems to be a bit unwieldy.

Still interested in any workarounds that stay in Python-land!

**Comment by roycaihw** [comment]
We patched the generated rest client to allow using strategic merge patch: https://github.com/kubernetes-client/python/blob/ccd3ce4fc27ed202864f9b3f971744a5ebf6ad7e/kubernetes/client/rest.py#L158-L161
That being said, `kubectl apply` is more than sending a strategic merge patch-- it has logic to do a three-way diff to compose the patch. A better way to do that is to use the new server-side apply feature https://github.com/kubernetes/enhancements/issues/555. We should support sending patch with `application/apply-patch` content type

**Comment by Datamance** [comment]
@roycaihw it looks like this feature is not generally available as of 1.17?

**Comment by roycaihw** [comment]
No it is not. From what I heard it was supported for a sub-portion of Kubernetes APIs in 1.15.

**Comment by Datamance** [comment]
@roycaihw given that this client doesn't implement the three-way diff logic found in the `kubectl` tool, and you don't yet support hooking into the server-side apply feature, if we want to emulate this behavior right now - do we have to shell out to `kubectl`? If so, when would you expect the server-side apply feature to be generally available, and how long after that would you be adding support in the Python client?

Related - is [this](https://github.com/kubernetes/apimachinery/blob/master/pkg/util/strategicpatch/patch.go#L2022) the logic that you're referring to? If so, I might try my hand at implementing it myself - especially if the only two requirements are 1) getting the patch body correct and 2) having the correct content-type.

**Comment by Datamance** [comment]
also @roycaihw doesn’t that rest client patch preclude me from doing anything other than a strategic merge patch? I’m on a mobile device so it’s a little hard to look at code right now but I’m unclear as to when `body` is going to be a list - perhaps this is only then for when I’m patching multiple resources? But then, what if I want to do a strategic merge patch to multiple resources? Or do another type of patch on a single resource?

**Comment by couaky** [comment]
Hi ! 
As I understand with the current patched generator, all PATCH requests will use `application/strategic-merge-patch+json` and there is no workaround to use other types of patch until the mentioned merge request will be done ?
Thanks.

**Comment by Datamance** [comment]
@roycaihw when approximately will this client be supporting the `application/apply-patch` content type?  Also I'm guessing that they'll support a `+json` prefix as well but just wanted to make 100% sure given that the [documentation](https://kubernetes.io/docs/reference/using-api/api-concepts/#api-endpoint) only mentions a `application/apply-patch+yaml`

**Comment by Datamance** [comment]
@roycaihw and @micw523 - it looks like the two of you are the major contributors to this repository. Are you able to answer to some of the questions above, or at least provide some sort of status update?

**Comment by micw523** [comment]
I'd be watching the status of PR #959. There are propositions of how to deal with it, but it might require upstream (generator) changes.

**Comment by kyprifog** [comment]
Is there a possible work around that doesn't get the three way merge capability.  I'm trying to replicate the functionality mentioned here:  https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#running-the-examples
but I dont really care if its a three way patch.  Would create custom object be sufficient?  https://github.com/kubernetes-client/python/blob/master/examples/custom_object.py
