### ISSUE TITLE
patch_namespaced_service when i just change port ==> error: duplicate value FieldValueDuplicate

### ISSUE THREAD

**Issue by black-sea** [kubernetes-client/python#1029]
**What happened (please include outputs or screenshots)**:
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 10 Dec 2019 01:51:51 GMT', 'Content-Length': '600'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Service \"nginxken\" is invalid: [spec.ports[0].name: Required value, spec.ports[1].name: Required value, spec.ports[1].nodePort: Duplicate value: 30080]","reason":"Invalid","details":{"name":"nginxken","kind":"Service","causes":[{"reason":"FieldValueRequired","message":"Required value","field":"spec.ports[0].name"},{"reason":"FieldValueRequired","message":"Required value","field":"spec.ports[1].name"},{"reason":"FieldValueDuplicate","message":"Duplicate value: 30080","field":"spec.ports[1].nodePort"}]},"code":422}

**What you expected to happen**:
change ok and port change
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"4838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"2749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"
- OS (e.g., MacOS 10.13.6):
centos7
- Python version (`python --version`)
python3.6
- Python client version (`pip list | grep kubernetes`)
kubernetes ==8.0.1

**Comment by roycaihw** [comment]
could you enable `Debug` in your client configuration and show us the patch sent to the apiserver? Also please share the code you're using and how the existing service object looks like.

**Comment by black-sea** [comment]
> could you enable `Debug` in your client configuration and show us the patch sent to the apiserver? Also please share the code you're using and how the existing service object looks like.

my code:
class K8SApi(object):
    def __init__(self, master_ip=None, token=None):
        self.token = token
        self.master_ip = master_ip
        aConfiguration = client.Configuration()
        aConfiguration.verify_ssl = False
        aConfiguration.host = self.master_ip
        aConfiguration.api_key = {
            "authorization": "Bearer " + self.token}
        aApiClient = client.ApiClient(aConfiguration)
        self.corev1_api = client.CoreV1Api(api_client=aApiClient)
        self.appsv1betaapi = client.ExtensionsV1beta1Api(api_client=aApiClient)

        def patch_svc(self):
        with open("./svc_test.yaml", "r") as f:
            body = f.read()
            body = yaml.load(body)
        # body["spec"]["ports"][0]["nodePort"] = 31181
        body["spec"]["ports"][0]["port"] = 8290
        api_instance = self.corev1_api.patch_namespaced_service(name="nginxkensvc", namespace="kentest", body=body)
        print(api_instance)
this is my code, It will report that error

**Comment by roycaihw** [comment]
I think this is a dup of https://github.com/kubernetes-client/python/issues/641#issuecomment-429473349

You can also use json patch to change the port: https://github.com/kubernetes-client/python/issues/641#issuecomment-468291235

/close
