### ISSUE TITLE
Should I  when  stop watch?

### ISSUE THREAD

**Issue by 52devops** [kubernetes-client/python#1030]
**What happened (please include outputs or screenshots)**:
I use websocket for client and server(django-chanels), when I use read_namespaced_pod_log
like  this code     
### watch    
       w = K8sStream.w.stream(self.c.k8s_core_api.read_namespaced_pod_log,
                               name=self.name,
                               namespace=self.namespace,
                               container=self.container,
                               previous=self.previous,
                               _preload_content=False,
                               tail_lines=500,
                               timestamps=True,
                               follow=True
                               )
        return (g for g in w)
### consumer:
class LogConsumer(WebsocketConsumer):
    def __init__(self, *args):
         self.stream = K8sStream(self.name, self.env, self.namespace, self.container,
                                    previous=int(self.previous)).pod_log()
    def connect(self):
            for s in self.stream:
                self.count += 1
                self.send(s)
### Issue
(Application instance <Task pending coro=<SessionMiddlewareInstance.__call__() running at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/channels/sessions.py:183> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/futures.py:348, <TaskWakeupMethWrapper object at 0x1126dd310>()]>> for connection <WebSocketProtocol client=['127.0.0.1', 59030] path=b'/podlog/saas-message-svc-d46c5c94d-48xsm/default/saas-message-svc/dev/0/'> took too long to shut down and was killed.
)

**Environment**:
- Kubernetes version (1.14):
- OS (e.g., MacOS 10.13.6):
- Python version (3.7.3)
- Python client version (1.10)

**Comment by palnabarun** [comment]
Hi,

What I am suspecting is the list comprehension `(g for g in w)` is blocking your return call in the loop. That is creating the timeout in your `django-channels` package.

Can you try using `yield` like this?

```
w = ...
for g in w:
  yield g
```

This would make the watch function non-blocking and you iterate over it and consume data in your consumer.

PS: I have limited knowledge of internal workings of `django-channels`.

**Comment by 52devops** [comment]
> Hi,
> 
> What I am suspecting is the list comprehension `(g for g in w)` is blocking your return call in the loop. That is creating the timeout in your `django-channels` package.
> 
> Can you try using `yield` like this?
> 
> ```
> w = ...
> for g in w:
>   yield g
> ```
> 
> This would make the watch function non-blocking and you iterate over it and consume data in your consumer.
> 
> PS: I have limited knowledge of internal workings of `django-channels`.

thanks

**Comment by palnabarun** [comment]
Closing this issue since the OP's question was resolved.

/close

**Comment by palnabarun** [comment]
Removing `kind/bug` since it is an unrelated issue.

/remove-kind bug
