### ISSUE TITLE
Streaming container logs works only for one hour

### ISSUE THREAD

**Issue by kvalev** [kubernetes-client/python#1040]
**What happened (please include outputs or screenshots)**:

I am trying to continuously stream the logs from a long-running container, but all the APIs that I tried return after exactly one hour, despite the container still running and writing to stdout.

Approach 1 using `urllib3` stream:
```
        for line in self._client.read_namespaced_pod_log(
            name=pod.name,
            namespace=pod.namespace,
            container=name,
            follow=True,
            _preload_content=False,
            _request_timeout=timedelta(hours=24),
        ).stream():
            print(line)
```

Increasing the request timeout did not influence anything.

Approach 2 using a watcher (which probably boils down to the same thing as approach 1):

```
        w = watch.Watch()
        for line in w.stream(
            self._client.read_namespaced_pod_log,
            name=pod.name,
            namespace=pod.namespace,
            container=name,
        ):
            print(line)
```

After exactly one hour from start reading the logs, the method just returns - there is no timeout or anything of the sorts.

**What you expected to happen**:

I expected to be able to stream all logs for as long as the container lives.

**How to reproduce it (as minimally and precisely as possible)**:

Using one of the two snippets above.

**Anything else we need to know?**:

I am not using a vanilla Kubernetes instance, but the version distributed with Openshift.

**Environment**:
- Kubernetes version (`kubectl version`): `v1.11.0+d4cacc0`
- OS (e.g., MacOS 10.13.6): `Mac OS 10.14.6`
- Python version (`python --version`): `Python 3.7.5`
- Python client version (`pip list | grep kubernetes`): `10.0.1`

**Comment by roycaihw** [comment]
I wonder if there is a server-side timeout. Could you try `kubectl logs -f` to see if the timeout happens to kubectl as well? You could also enable `-v=9` to see if kubectl does retry or not

**Comment by VassilisVassiliadis** [comment]
Hi @kvalev did you ever find a solution to your issue?

**Comment by kvalev** [comment]
@VassilisVassiliadis No, not really, we just handled the timeout on the client side.
