### ISSUE TITLE
Potential dependency conflicts between kubernetes and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [kubernetes-client/python#1042]
Hi, as shown in the following full dependency graph of  **_kubernetes_**, **_kubernetes_** requires **_urllib3 >=1.24.2_** ， while the installed version of **_requests _**(2.22.0) requires _**urllib3  <1.26,>=1.21.1**_.

According to Pip's _“first found wins”_ installation strategy, _**urllib3 1.25.7**_ is the actually installed version.  

Although the first found package version _** urllib3 1.25.7**_ just satisfies the later dependency constraint （_**urllib3  <1.26,>=1.21.1**_), it will lead to a build failure once developers release a newer version of urllib3.

### Dependency tree--------
```
kubernetes - 10.0.1
| +- certifi(install version:2019.9.11 version range:>=14.05.14)
| +- google-auth(install version:1.7.1 version range:>=1.0.1)
| | +- cachetools(install version:3.1.1 version range:>=2.0.0,<3.2)
| | +- pyasn1-modules(install version:0.2.7 version range:>=0.2.1)
| | +- rsa(install version:4.0 version range:<4.1,>=3.1.4)
| | | +- pyasn1(install version:0.4.8 version range:>=0.1.3)
| | +- setuptools(install version:42.0.1 version range:>=40.3.0)
| | +- six(install version:1.13.0 version range:>=1.9.0)
| +- python-dateutil(install version:2.8.1 version range:>=2.5.3)
| +- pyyaml(install version:5.2b1 version range:>=3.12)
| +- requests(install version:2.22.0 version range:*)
| | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.6 version range:<1.26,>=1.21.1)
| +- requests-oauthlib(install version:1.3.0 version range:*)
| +- setuptools(install version:42.0.1 version range:>=21.0.0)
| +- six(install version:1.13.0 version range:>=1.9.0)
| +- urllib3(install version:1.25.6 version range:>=1.24.2)
| +- websocket-client(install version:0.56.0 version range:>=0.32.0)
| | +- six(install version:1.13.0 version range:*) 
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependencies to be **_urllib3  >=1.24.2,<1.26_**.
2.	Ask your upstream project **_request _** to losse the version range of **_urllib3_** to be **_>=1.21.1_**.

@mbohlool Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by roycaihw** [comment]
I'm not familiar with pip dependency resolution, but if we add `<1.26` in our side to avoid accidental build failure, we should have clear notes/procedures about updating the requirements to the latest compatible version in each release, so that we don't get stuck with a old urllib3 version forever.

`requests` updates its requirements when it supports certain urllib3 versions https://github.com/psf/requests/commit/aeda65bbe57ac5edbcc2d80db85d010befb7d419. I imagine option 2 to be less likely to happen.

cc @yliaog

**Comment by roycaihw** [comment]
Closing in favor of https://github.com/kubernetes-client/python/issues/1171
