### ISSUE TITLE
Compatibility with python 2.7 is broken

### ISSUE THREAD

**Issue by siddiqskm** [kubernetes-client/python#1048]
Issue -
Installation of the package kubernetes with python 2.7 fails as listed below:
Collecting cachetools<5.0,>=2.0.0 (from google-auth>=1.0.1->kubernetes==9.0.0->-r requirements.txt (line 24))
  Downloading http://pypi.eng.hortonworks.com/api/package/cachetools/cachetools-4.0.0.tar.gz
cachetools requires Python '~= 3.5' but the running Python is 2.7.15

Expectation -
From the official home page - I see kuberenetes supports python 2.7 as well. So - I expect the installation to be successful on python 2.7

Steps to reproduce -
Just try installing kubernetes with python 2.7

Additional Information -
I see Google Auth no longer supports python 2.7 - With this latest development whats the latest on  kubernetes client for python 2.7?

**Comment by micw523** [comment]
You’ll need to configure your pip to fetch a lower version of compatible package of cachetools. This is not our problem.

On another note, Python 2 will reach end of life soon. Although we may keep supporting py2 a bit, you can see that many packages are starting to require Python 3.5 or higher.

/close

**Comment by palnabarun** [comment]
Xref: #1054
