### ISSUE TITLE
Install the kubernetes pcakage successfully but can't use it

### ISSUE THREAD

**Issue by nettyxiong** [kubernetes-client/python#1053]
```bash
git clone --recursive https://github.com/kubernetes-client/python.git
cd python
python setup.py install
```
```bash
python
>>> import kubernetes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/kubernetes/__init__.py", line 21, in <module>
    import kubernetes.dynamic
ImportError: No module named dynamic
>>> 
```

**Comment by palnabarun** [comment]
Hi @nettyxiong, we are dropping support for Python 2.7 from the client. Can you please try with Python 3 and see if the error still occurs?

**Comment by palnabarun** [comment]
I checked with Python 3.8.0 and the `ImportError` does not occur.

**Comment by palnabarun** [comment]
Xref: https://github.com/kubernetes-client/python/issues/1054

**Comment by micw523** [comment]
The dynamic client is enabled in #1035. Looks like there are import issues.
/assign

**Comment by palnabarun** [comment]
> The dynamic client is enabled in #1035. Looks like there are import issues.
> /assign

I tried it with Python 3.8.0 and the import is working. I couldn't test with Python 2.7 as I couldn't successfully install the client and its dependencies.

**Comment by micw523** [comment]
I cannot replicate this error with Python 2.7.17 on ubuntu 18.04.
Command:
```
pip install -e git+https://github.com/kubernetes-client/python.git@master#egg=kubernetes
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import kubernetes
>>> from kubernetes import dynamic
>>> dynamic
<module 'kubernetes.dynamic' from '/home/micw/py27/src/kubernetes/kubernetes/dynamic/__init__.py'>
>>> import kubernetes.dynamic
>>> 
```
