### ISSUE TITLE
How to delete the pod immediately?

### ISSUE THREAD

**Issue by nettyxiong** [kubernetes-client/python#1056]
I use the `delete_namespaced_pod` api to delete the pod, but always stuck in a long time, mabye in 1 minute.
I just want to delete the pod with `-f` flag. How can I do it?

**Comment by nettyxiong** [comment]
May I can set `grace_period_seconds=0` and `propagation_policy='Background',` to accelerate the delete operation?

**Comment by roycaihw** [comment]
cc @yliaog

**Comment by yliaog** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#background-cascading-deletion

It is correct to set 'Background'.
