### ISSUE TITLE
k8s python client error

### ISSUE THREAD

**Issue by beginend2012** [kubernetes-client/python#1057]
git clone --recursive https://github.com/kubernetes-client/python.git
  git branch -a
  git branch
  965  git checkout release-11.0

pip install kubernetes
.........
Installed /opt/deamon/.py3env/lib/python3.6/site-packages/kubernetes-11.0.0b2-py3.6.egg
Processing dependencies for kubernetes==11.0.0b2
Searching for urllib3==1.25.7
Best match: urllib3 1.25.7
Adding urllib3 1.25.7 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for requests-oauthlib==1.3.0
Best match: requests-oauthlib 1.3.0
Adding requests-oauthlib 1.3.0 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for requests==2.22.0
Best match: requests 2.22.0
Adding requests 2.22.0 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for websocket-client==0.57.0
Best match: websocket-client 0.57.0
Adding websocket-client 0.57.0 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for google-auth==1.10.1
Best match: google-auth 1.10.1
Adding google-auth 1.10.1 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for PyYAML==5.3
Best match: PyYAML 5.3
Adding PyYAML 5.3 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for setuptools==45.0.0
Best match: setuptools 45.0.0
Adding setuptools 45.0.0 to easy-install.pth file
Installing easy_install script to /opt/deamon/.py3env/bin
Installing easy_install-3.8 script to /opt/deamon/.py3env/bin

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for python-dateutil==2.8.1
Best match: python-dateutil 2.8.1
Adding python-dateutil 2.8.1 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for six==1.14.0
Best match: six 1.14.0
Adding six 1.14.0 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for certifi==2019.11.28
Best match: certifi 2019.11.28
Adding certifi 2019.11.28 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for oauthlib==3.1.0
Best match: oauthlib 3.1.0
Adding oauthlib 3.1.0 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /opt/deamon/.py3env/bin

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for idna==2.8
Best match: idna 2.8
Adding idna 2.8 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for rsa==4.0
Best match: rsa 4.0
Adding rsa 4.0 to easy-install.pth file
Installing pyrsa-decrypt script to /opt/deamon/.py3env/bin
Installing pyrsa-encrypt script to /opt/deamon/.py3env/bin
Installing pyrsa-keygen script to /opt/deamon/.py3env/bin
Installing pyrsa-priv2pub script to /opt/deamon/.py3env/bin
Installing pyrsa-sign script to /opt/deamon/.py3env/bin
Installing pyrsa-verify script to /opt/deamon/.py3env/bin

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for pyasn1-modules==0.2.8
Best match: pyasn1-modules 0.2.8
Adding pyasn1-modules 0.2.8 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for cachetools==4.0.0
Best match: cachetools 4.0.0
Adding cachetools 4.0.0 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Searching for pyasn1==0.4.8
Best match: pyasn1 0.4.8
Adding pyasn1 0.4.8 to easy-install.pth file

Using /opt/deamon/.py3env/lib/python3.6/site-packages
Finished processing dependencies for kubernetes==11.0.0b2
(.py3env) [root@wukui1 python]# echo $?
0

(.py3env) [root@wukui1 deamon]# python pod.py
Traceback (most recent call last):
  File "pod.py", line 4, in <module>
    config.load_kube_config()
  File "/opt/deamon/.py3env/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 645, in load_kube_config
    persist_config=persist_config)
  File "/opt/deamon/.py3env/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 613, in _get_kube_config_loader_for_yaml_file
    **kwargs)
  File "/opt/deamon/.py3env/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 153, in __init__
    self.set_active_context(active_context)
  File "/opt/deamon/.py3env/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 187, in set_active_context
    self._current_context['context']['cluster'])['cluster']
  File "/opt/deamon/.py3env/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 536, in get_with_name
    'Expected object with name %s in %s list' % (name, self.name))
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected object with name kubernetes in /root/.kube/config/clusters list

**Comment by beginend2012** [comment]
(.py3env) [root@wukui1 deamon]# kubectl get nodes -o wide
NAME           STATUS   ROLES    AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION          CONTAINER-RUNTIME
172.16.10.77   Ready    <none>   7d15h   v1.15.7   172.16.10.77   <none>        CentOS Linux 7 (Core)   3.10.0-693.el7.x86_64   docker://19.3.5
172.16.10.78   Ready    <none>   7d15h   v1.15.7   172.16.10.78   <none>        CentOS Linux 7 (Core)   3.10.0-693.el7.x86_64   docker://19.3.5

**Comment by beginend2012** [comment]
(.py3env) [root@wukui1 deamon]# cat pod.py
from kubernetes import client, config

# Configs can be set in Configuration class directly or using helper utility
config.load_kube_config()

v1 = client.CoreV1Api()
print("Listing pods with their IPs:")
ret = v1.list_pod_for_all_namespaces(watch=False)
for i in ret.items:
    print("%s\t%s\t%s" % (i.status.pod_ip, i.metadata.namespace, i.metadata.name))

**Comment by roycaihw** [comment]
Could you also provide your kubeconfig file?
