### ISSUE TITLE
Question: how to specify API server port?

### ISSUE THREAD

**Issue by qlyoung** [kubernetes-client/python#1061]
I wish to write a small application to create a few resources with the API. However, there is apparently no documentation on how to specify the port of the API server. Nothing in pydoc. I don't see anything in the repository. By default the client tries to connect on `localhost:80`, and the API server is not listening there in my cluster.

Error:
```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/persistentvolumes (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8000ff3128>: Failed to establish a new connection: [Errno 111] Con
nection refused',))
```

My API server is on 16443:
```
root@maltese:~# netstat -tulpn | grep apiserv
tcp6       0      0 :::16443      :::*       LISTEN      3772/kube-apiserver
```

Is there really no documentation for this extremely basic setting or am I blind?

**Comment by tomplus** [comment]
Have you seen this example: https://github.com/kubernetes-client/python#examples?

The simplest method is to read the configuration (address, certs etc.) from the `kubeconfig`, as `kubectl` does.

**Comment by qlyoung** [comment]
Yes, I read the readme. The linked example doesn't show how to specify a port.
I suppose reading `kubeconfig` works if you're running on the master node. But in any case I still am not clear on how to programmatically set the address and port of the API server.

I appreciate the response.

**Comment by qlyoung** [comment]
Ah, I think I see...you're supposed to just bring the `kubectl` binary with you anywhere you want to hit the API, and then use it to run a proxy server :slightly_frowning_face:. Well, thanks for the help.

**Comment by RottenLeaf24** [comment]
@qlyoung 
After my testing, I think there is something wrong with the api documentation.In the doc,they use the method of ```kubernetes.client.Configuration()``` to get authorization.But in the method the url has fixed.
![image](https://user-images.githubusercontent.com/41962159/76734072-1b135680-679d-11ea-9c86-c5a135cd878e.png)
We should modify the way of verification! if you see the example code like this:
```
from __future__ import print_function
import time
import kubernetes.client
from kubernetes.client.rest import ApiException
from pprint import pprint

# Configure API key authorization: BearerToken
configuration = kubernetes.client.Configuration()
configuration.api_key['authorization'] = 'YOUR_API_KEY'
# Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
# configuration.api_key_prefix['authorization'] = 'Bearer'

# create an instance of the API class
api_instance = kubernetes.client.AdmissionregistrationApi(kubernetes.client.ApiClient(configuration))

try:
    api_response = api_instance.get_api_group()
    pprint(api_response)
except ApiException as e:
    print("Exception when calling AdmissionregistrationApi->get_api_group: %s\n" % e)
```
You should change the code to the following:
```
from __future__ import print_function
import time
import kubernetes.client
from kubernetes.client.rest import ApiException
from pprint import pprint
from kubernetes import config
config.load_incluster_config()
api_instance = kubernetes.client.AdmissionregistrationApi()

try:
    api_response = api_instance.get_api_group()
    pprint(api_response)
except ApiException as e:
    print("Exception when calling AdmissionregistrationApi->get_api_group: %s\n" % e)
```
It will work be fine.
In addition,if you use the kube/config for verify,you need chang the ```config.load_incluster_config()``` to ```config.load_kube_config()```.
