### ISSUE TITLE
proxy SOCKS5 schema support 

### ISSUE THREAD

**Issue by llegolas** [kubernetes-client/python#1064]
**What is the feature and why do you need it**:
It would be nice if the client supports socks5 proxy to be on par with the kubectl which respects and uses properly env. proxy var of the sort of http_proxy=socks5://..... 

**Describe the solution you'd like to see**:
it would be sufficient if the code checks for the proxy schema in configuration.proxy and use urllib3.contrib.socks.SOCKProxyManager instead of urllib3.ProxyManager accordingly.

**Comment by llegolas** [comment]
Perhaps something like 
```
        # https pool manager
        if configuration.proxy:
            if configuration.proxy.split(':')[0].lower() == 'socks5':
                self.pool_manager = urllib3.contrib.socks.SOCKSProxyManager(
                    num_pools=pools_size,
                    maxsize=maxsize,
                    cert_reqs=cert_reqs,
                    ca_certs=ca_certs,
                    cert_file=configuration.cert_file,
                    key_file=configuration.key_file,
                    proxy_url=configuration.proxy,
                    **addition_pool_args
                )

```
vs.

```
        if configuration.proxy:
            self.pool_manager = urllib3.ProxyManager(
                num_pools=pools_size,
                maxsize=maxsize,
                cert_reqs=cert_reqs,
                ca_certs=ca_certs,
                cert_file=configuration.cert_file,
                key_file=configuration.key_file,
                proxy_url=configuration.proxy,
                **addition_pool_args
            )
        else:
```

in rest.py

**Comment by roycaihw** [comment]
The rest client is auto generated by [openapi-generator](https://github.com/OpenAPITools/openapi-generator/blob/67e3bf5271e1f2e70f6ab883ca9e38af57f710af/modules/openapi-generator/src/main/resources/python/rest.mustache#L78-L89). Would you mind file a feature request in that repo?

**Comment by tlianza** [comment]
I can't quite see in the code (in `kube_config.py`) how you'd pass a proxy server in such that it would ever get set. In other words, even with no changes to the openapi-generator, how could you ever get `if configuration.proxy:` to be set to true in the current k8s client?

**Comment by jlonganecker** [comment]
Can we now use the new version of open api generator. Looks like they merged in support for SOCKS5 proxies:

https://github.com/OpenAPITools/openapi-generator/commit/2ca958642bbdd8678f7f3bbb516cc274862053ff

**Comment by christophetd** [comment]
Confirming that this would be a great feature to have. If kubectl supports it then the K8s client should as well
