### ISSUE TITLE
job_crud.py

### ISSUE THREAD

**Issue by sushil11th** [kubernetes-client/python#1065]
Not able to create job with this example:

------Output log:

Job created. status='{'active': None,
 'completion_time': None,
 'conditions': None,
 'failed': None,
 'start_time': None,
 'succeeded': None}'
Job updated. status='{'active': None,
 'completion_time': None,
 'conditions': None,
 'failed': None,
 'start_time': None,
 'succeeded': None}'
Job deleted. status='{}'

**Comment by roycaihw** [comment]
I ran the example and it created the job successfully. 
```
$ python examples/job_crud.py
Job created. status='{'active': None,
 'completion_time': None,
 'conditions': None,
 'failed': None,
 'start_time': None,
 'succeeded': None}'
Job updated. status='{'active': None,
 'completion_time': None,
 'conditions': None,
 'failed': None,
 'start_time': None,
 'succeeded': None}'
Job deleted. status='{u'active': 1, u'startTime': u'2020-03-09T06:01:53Z'}'
```
Note that the example deletes the job at the end. If you remove [this line](https://github.com/kubernetes-client/python/blob/4bb1e7bf38381b45c17f63400b21ba2bbb553e8c/examples/job_crud.py#L93) and run the example you can see
```
$ kubectl get jobs
NAME   COMPLETIONS   DURATION   AGE
pi     1/1           7s         7s
```
/close
