### ISSUE TITLE
kubernetes/docs/V1Taint.md value field has contradictionary description

### ISSUE THREAD

**Issue by rhristov** [kubernetes-client/python#1068]
**Link to the issue (please include a link to the specific documentation or example)**:
kubernetes/docs/V1Taint.md

**Description of the issue (please include outputs or screenshots if possible)**:
The value field is described as "Required" in the description column, while it's described as [optional] in the Notes column

**Comment by roycaihw** [comment]
It's a documentation issue in Kubernetes OpenAPI spec, which has been fixed in Kubernetes 1.18 https://github.com/kubernetes/kubernetes/pull/88584. The fix will get included in this repo when we generate a client from Kubernetes 1.18.
