### ISSUE TITLE
10.0.1 missing from changelog

### ISSUE THREAD

**Issue by mac9416** [kubernetes-client/python#1075]
**Link to the issue (please include a link to the specific documentation or example)**:

https://github.com/kubernetes-client/python/blob/master/CHANGELOG.md

**Description of the issue (please include outputs or screenshots if possible)**:

I was about to bump a downstream project from 10.0.1 but wanted to see what changed.

10.0.1 doesn't have an entry in the changelog.

**Comment by roycaihw** [comment]
Fixed in #1090

/close
