### ISSUE TITLE
__deserialize_date return type dependent on runtime environment

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes-client/python#1081]
the __deserialize_date function behaves differently depending on which dependencies you have installed at runtime.
https://github.com/kubernetes-client/python/blob/master/kubernetes/client/api_client.py#L585

if dateutils is installed you get datetime objects for dates and if not you get strings.

This is very bad behaviour for a library as code will break depending on which other packages are currently installed.
The function should be changed to always return a single type regardless of current runtime environment.
One way to do that would be to make the dependency mandatory and throw an import error on library load or to remove the dependency by parsing the string with stdlib methods.

**Comment by roycaihw** [comment]
ref https://github.com/kubernetes-client/python/pull/1084#discussion_r381526844. The issue should be fixed when we upgrade the code-generator version in the 12.0.0a1 release
