### ISSUE TITLE
Unable to get kubeconfig file

### ISSUE THREAD

**Issue by keyurbitw** [kubernetes-client/python#1094]
**What happened (please include outputs or screenshots)**: I am trying to connect to my kubernetes cluster on eks. While running **config.load_kube_config(path)** it gives below error:
**ERROR:root:[Errno 2] No such file or directory**. At first I did not provide the path so its should take the config file from default location but I see the same error there as well. Even I am checking if the file exists or not. And I see that file exists and I am able print the content on config file. But while running it gives error.

**What you expected to happen**: It should connect to EKS cluster.

**How to reproduce it (as minimally and precisely as possible)**: Run the below script:
`from kubernetes import config, client
import os
import kubernetes
import yaml
from nose import loader

try:
    path = './config'
    with open(path) as file:
        data = yaml.load(file, Loader=yaml.FullLoader)
        print(data)
        
    if os.path.isfile(path):
        print "File Exists!!"    
    config.load_kube_config(path)
    k8sApi = client.CoreV1Api()     
    clusterNameSpaces = k8sApi.list_namespaced_persistent_volume_claim(namespace='mm', watch=False)
    print clusterNameSpaces

except Exception as e:
    print e`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): v1.15.5
- OS (e.g., MacOS 10.13.6): 10.15.3
- Python version (`python --version`) 2.7
- Python client version (`pip list | grep kubernetes`): 10.0.1

**Comment by palnabarun** [comment]
@keyurbitw -- I tried loading a kubeconfig from a location other than the default one and this is working fine. Are you still facing the issue?
