### ISSUE TITLE
 Trying to connect to a aks cluster and client.list_node() function does not work.

### ISSUE THREAD

**Issue by WilliamHoo** [kubernetes-client/python#1118]
**What happened (please include outputs or screenshots)**:

I created a aks cluster on azure, and then i tried to connect my aks cluster using python client.
it works perfectly with kubectl. i have saved my kubeconfig file in the default location. 

**What you expected to happen**:

client.list_node() showing my nodes information on aks. 

**How to reproduce it (as minimally and precisely as possible)**:
first, i used this to make sure kubeconfig is correctly saved. 

```
az aks get-credentials --resource-group $AKS_RESOURCE_GROUP_COMPUTE --name $AKS_CLUSTER_NAME --file ~/.kube/config-${RunId} --admin
export KUBECONFIG=$HOME/.kube/config-${RunId}
```

now, in python, i did:

```
config.load_kube_config()
v1 = client.CoreV1Api()
v1.list_node()
```

and it gave me error messages below:

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', port=443): Max retries exceeded with url: /api/v1/nodes (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2ab3786fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Anything else we need to know?**:
i was working behind a company proxy, and i tried to do this using/not using company proxy, both did not work. 

**Environment**:
- Kubernetes version (`kubectl version`):

Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g., MacOS 10.13.6):
windows 10 linux subsystem - 18.04

- Python version (`python --version`)
3.7.4

- Python client version (`pip list | grep kubernetes`)
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by WilliamHoo** [comment]
Thiis is a poxy issue. i successfully solved this issue by adding command:
```
client.Configuration._default.proxy = "your http proxy"
```
before i created my client.

**Comment by zffocussss** [comment]
hi @WilliamHoo .can you show your whole code?I want to how you authenticate with AKS cluster
