### ISSUE TITLE
how can i got the total count of pods in a very large namespace

### ISSUE THREAD

**Issue by yunfan** [kubernetes-client/python#1121]
i want to got the count number directly (like provided by api like `count_namespaced_job`/`count_namepsaced_pod`), i dont want to count it myself using apis like `list_namespaced_job`/`list_namespaced_pod` this is very useful when there were too many items in a namespace

**Comment by yliaog** [comment]
there is no direct api for the # of pods in a namespace, you have to do a list of the pods, then count it

**Comment by yunfan** [comment]
i think this policy is really ugly especially when you were using k8s managing too many containers and this is the target of k8s stack , right?
