### ISSUE TITLE
I called the interface to delete pod, job,Then the pod restarted again.

### ISSUE THREAD

**Issue by liudonggang** [kubernetes-client/python#1125]
**What happened (please include outputs or screenshots)**:
I called the interface to delete pod API, job API,Then the pod restarted again.My pod   restartPolicy: OnFailure

**Environment**:
- Kubernetes version 1.14.6 (`kubectl version 1.14.6`):
- Ubuntu 16.04
- Python version 3.6.9
- Python client version 10.0.1

**Comment by palnabarun** [comment]
Hi @liudonggang, can you please provide the code that you executed and the pod/job manifest?

**Comment by palnabarun** [comment]
@liudonggang -- Since there was no response, the issue is being closed.

Please feel free to reopen if you have any unresolved queries.

/close
