### ISSUE TITLE
Secret is not able to fetched using     image_pull_secrets

### ISSUE THREAD

**Issue by lucheeseng827** [kubernetes-client/python#1139]
**What happened (please include outputs or screenshots)**:
I was trying to call for secret so I can have my jobs pulling from dockerhub and then the secret was too big to parsed.

**What you expected to happen**:
I am suppose to get secret and have it added into my job so it can pull abut it does not have `dockersecret` inside
**How to reproduce it (as minimally and precisely as possible)**:

   ```
container = client.V1Container(
        name=NAME,
        image=IMAGE_NAME,
        command=["python", "app.py", "-p", project_id])

template = client.V1PodTemplateSpec(
        metadata=client.V1ObjectMeta(labels={"app": "appname"}),
        spec=client.V1PodSpec(restart_policy="Never", containers=[container], image_pull_secrets='dockersecret'))
```

###Error returned

```
 File "api-src/project/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'c09afe47-dd6e-49ca-89a5-073c6afc559d', 'Content-Type': 'application/json', 'Date': 'Thu, 09 Apr 2020 18:43:50 GMT', 'Content-Length': '511'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Job in version \"v1\" cannot be handled as a Job: v1.Job.Spec: v1.JobSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.ImagePullSecrets: []v1.LocalObjectReference: decode slice: expect [ or n, but found \", error found in #10 byte of ...|ecrets\": \"dockersecr|..., bigger context ...|1\", \"name\": \"prelabel-62\"}], \"imagePullSecrets\": \"dockersecret\", \"restartPolicy\": \"Never\"}}}}|...","reason":"BadRequest","code":400}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
1.15.10
- OS (e.g., MacOS 10.13.6):
10.15.3
- Python version (`python --version`)
3.7
- Python client version (`pip list | grep kubernetes`)
kubernetes==11.0.0

**Comment by palnabarun** [comment]
Hi @lucheeseng827, does this error occur even when you create the Job using `kubectl`?

**Comment by lucheeseng827** [comment]
it can  be create locally, if I pass with `dockersecret` it will manage to pull.

**Comment by palnabarun** [comment]
@lucheeseng827 `image_pull_secrets` is not a `string`. The type expected here is `	list[V1LocalObjectReference]`.

Reference: https://github.com/kubernetes-client/python/blob/v11.0.0/kubernetes/docs/V1PodSpec.md

**Comment by lucheeseng827** [comment]
@palnabarun any example of `list[V1LocalObjectReference]` you can give in python, the guide seemed to refer back to kubernetes documentations and I could not get a valid example.

**Comment by palnabarun** [comment]
So, here is what I tried, keeping other things the same as you mentioned.

```
template = client.V1Pod(metadata=client.V1ObjectMeta(name="test", labels={"app": "appname"}), spec=client.V1PodSpec(restart_policy="Never", containers=[container], image_pull_secrets=[client.V1LocalObjectReference(name='dockersecret')])) 
```

**Comment by nonai** [comment]
I  too  faced this issue, and  the correct  way  it worked for  me is:

`image_pull_secrets=[client.V1LocalObjectReference('the secret name')]`

**Comment by adamxy** [comment]
V1Deployment api Secret is not able to fetched using image_pull_secrets
