### ISSUE TITLE
list_pod_for_all_namespaces - RemoteDisconnected

### ISSUE THREAD

**Issue by edgrz** [kubernetes-client/python#1149]
I'm trying to make a GET request to list all the pods running on my cluster. I'm using a flask API which expose an endpoint which internally uses CoreV1Api to achieve that.

As it is needed every day, I've have a cronjob which creates a pod which makes a request to flask API endpoint. Usually everything works fine and I'm getting response. but sometimes I'm receiving the following exception after 60 seconds:

``` bash
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
````
It seems like there is a timeout somewhere.

On the client my request timeout is set to 90 seconds. 

On the server side where I'm using CoreApiV1, I'm not setting any value to *timeout_seconds* parameter.   From documentation, I understood that if not set, the call hasn't have time limit and remains open until having response. 

```
Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity.
````

 Does *timeout_seconds* has default value set to 60?

**Comment by roycaihw** [comment]
I don't think this client sets the default timeout_seconds. We need to check if the apiserver sets the default

**Comment by roycaihw** [comment]
I didn't find defaulting on [server side](https://github.com/kubernetes/kubernetes/blob/95bb85378ddd8a31d1a794540ec627640dbe8584/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go#L194-L199). @edgrz Have you tried setting _timeout_seconds_ to different values (30s, 120s) and seeing if the behavior changes?

**Comment by edgrz** [comment]
First of all, thanks for replying.
 From official k8s [documentation](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) I have come to the conclusion that apiserver has  by default 1m0s timeout:

> –request-timeout duration     Default: 1m0s
An  optional field indicating the duration a handler must keep a request  open before timing it out. This is the default request timeout for  requests but may be overridden by flags such as –min-request-timeout for  specific types of requests.

However, after some troubleshooting I realized that it was resources issue as it couldn't serve my call and so, the pod automatically rebooted the thread which was serving my requests.

We can close the issue. Thanks for support.
