### ISSUE TITLE
Copy From Pod

### ISSUE THREAD

**Issue by BobkovS** [kubernetes-client/python#1150]
Hello, is it possible to copy files from the pod using api?

I know that it can copy using kubectl like: kubectl cp -n "namespace" "pod_name": "filename" .

But i can't find declaration how to do it via API.

Thanks in advance for your reply.

**Comment by huzerun0306** [comment]
Have you solved this problem? I also want to use api to call functions similar to  kubectl cp ...

**Comment by rushant001** [comment]
it worked for me
https://github.com/kubernetes-client/python/pull/764/commits/e0d4cdc68520581c8173d088106985136f4a3caf
