### ISSUE TITLE
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool

### ISSUE THREAD

**Issue by jincheng-xiaosu** [kubernetes-client/python#1151]
My k8s cluster is installed quickly on the cloud server through kubeadm. I want to access my cluster through the public network address through the SDK of Python. The following error is reported：

`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='203.195.203.45', port=6443): Max retries exceeded with url: /api/v1/pods (Caused by SSLError(SSLCertVerificationError("hostname '203.195.203.45' doesn't match either of 'k8s-master', 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local', '10.1.0.1', '172.16.32.7'")))`

**Comment by DivyaNayaka** [comment]
The issue might be with your certs.

1. kubeadm alpha certs renew all
2. https://github.com/kubernetes/kubeadm/issues/581

**Comment by jincheng-xiaosu** [comment]
My cluster is just built and deployed with kubeadm tool. The certificate is self signed. I changed self.verify_ssl under configuration.py to false

c = client.Configuration()

c.verify_ssl = False

client.Configuration.set_default(c)

**Comment by palnabarun** [comment]
@jincheng-xiaosu -- the common names mentioned in the self-signed certificate don't match the server that you are pinging. I am guessing there are proxies/load balancers in between.

You can disable hostname matching by setting `configuration.assert_hostname = False` along with `configuration.verify_ssl = False`.

This should make it working with kubeadm clusters being proxied over.

**Comment by rjnshch** [comment]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='us-south.monitoring.cloud.im.com', port=443): Max retries exceeded with url: /api/v3/dashboards?light=True (Caused by ResponseError('too many 500 error responses'))

what can I do to fix this. error.

**Comment by palnabarun** [comment]
@rjnshch -- Is the error that you are describing related to Kubernetes or the Python Client?

**Comment by palnabarun** [comment]
@jincheng-xiaosu -- is your issue resolved? can this issue be closed?

**Comment by palnabarun** [comment]
/close

Please feel free to reopen if you face this issue again.

**Comment by vm250320** [comment]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013446F09D80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Process finished with exit code 1
 
Getting this error Help Me out
