### ISSUE TITLE
May I translate this project into Korean?

### ISSUE THREAD

**Issue by tina1296** [kubernetes-client/python#1152]
Hi :) I am Na Eun Kwon a university student in Kwangwoon University. I want to translate READ ME documentation for your project contribution and other Koreans who want to learn about kubernetes. 
So may I translate these infos into Korean?
If I could, plz tell me how I can share the translated results. 
Thank you

**Comment by roycaihw** [comment]
@tina1296 Thanks for the contribution! I think that's a good idea. I know we have translated documentation for upstream Kubernetes docs. 

For this repo, we have a [website](https://k8s-python.readthedocs.io/en/latest/index.html) publishing the documentation (background: https://github.com/kubernetes-client/python/pull/893), which could be an option for hosting the translated doc.

cc @kubernetes/kubernetes-blog @kubernetes/sig-docs-ko-owners SIG docs experts for suggestions on how to publish and maintain the translated doc.

**Comment by tina1296** [comment]
Thanks to your reply;) I have a question from your answer!! I can't understand what 'I know we have translated documentation for upstream Kubernetes docs' means... I want to know whether there is a Korean translated documentation such as README. I will wait for your reply. Thanks:)

**Comment by micw523** [comment]
He meant this: https://github.com/kubernetes/website

**Comment by roycaihw** [comment]
> this: https://github.com/kubernetes/website

Yes I was referring to the main Kubernetes documentation. As you can see from the source we have doc translated in multi languages. I'm not sure what service the `website` repo uses to host multi language docs. In the python repo we use sphinx documentation (https://github.com/kubernetes-client/python/pull/893), which seems to support hosting multi language docs https://www.sphinx-doc.org/en/master/usage/advanced/intl.html
