### ISSUE TITLE
Support for kubernetes 1.18.+

### ISSUE THREAD

**Issue by SockenSalat** [kubernetes-client/python#1153]
I have a probelm currently with a nagios plugin utilizing this client.

I'm not familar with python, but if I read the [compatibility table](https://github.com/kubernetes-client/python#compatibility) correctly and take [k8s Release notes](https://kubernetes.io/docs/setup/release/notes/#kube-apiserver-1) into account, I get the impression that the API changes mentioned are the reason for my problem.

So my question is: are there any plans to support k8s in version 1.18?

**Comment by roycaihw** [comment]
@SockenSalat We are actively working on releasing 1.16 client: https://github.com/kubernetes-client/python/pull/1141. Support for 1.18 is planned and will come after that

**Comment by SockenSalat** [comment]
@roycaihw Great to hear, thank you.

**Comment by arthurlogilab** [comment]
I'm not sure I understand why this is closed. Is it closed as in "wontfix" or is it closed as in "wontfix" till 1.16 and 1.17 are released ? 

Thanks for maintaining this project by the way.

**Comment by arthurlogilab** [comment]
We have 1.18.+ cluster we would like to keep talking to with this python client (used in checkmk supervision). Any chances of getting it to work by using the release-12.0 branch ? https://github.com/kubernetes-client/python/tree/release-12.0

**Comment by SockenSalat** [comment]
@arthurlogilab 
> I'm not sure I understand why this is closed.

I closed this Issue becaus it is stated that _Support for 1.18 is planned_.

**Comment by arthurlogilab** [comment]
@SockenSalat Thanks for your response. On a number of open source project I am used to subscribing to an issue I am interested in to get updates on the completion of such a task. In the case of this project how can I do that ? Should I subscribe to the releases ? (in the case where I follow an issue I can help out in the review or by testing an associated pull request). Thanks for your clarifications.

**Comment by SockenSalat** [comment]
@arthurlogilab I just subscribed the releases for getting notified when to take a look again
