### ISSUE TITLE
AppsV1Api().create_namespaced_deployment

### ISSUE THREAD

**Issue by ils-rohits** [kubernetes-client/python#1156]
AppsV1Api().create_namespaced_deployment 

Module not found in AppsV1Api create_namespaced_deployment 

I've searched and found it is in
 AppsV1beta2Api

But there is not an example associated with that for creating deployments.

**Comment by MoShitrit** [comment]
Hey @ils-rohits 
I have a PR open (#1155 ) to update the examples to use the V1 api versions.
Just FYI. 😄
