### ISSUE TITLE
list_namespaced_secret w/ watch=True does not report secret changes

### ISSUE THREAD

**Issue by bqian20** [kubernetes-client/python#1159]
I am trying to use the api:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_namespaced_secret, with the watch=true, as described in above link:
"Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion."
However, when I delete/recreate a secret under the namespace, the api call did not return. At the same time, kubectl -n dc-cert get secrets --watch command reported secret being deleted/recreated.

I troubleshot a bit, and dump data prior to the rest call at kubernetes/client/rest.py line 205 which sends the rest request:
method GET
url: https://192.168.100.1:6443/api/v1/namespaces/dc-cert/secrets
fields: [('watch', True)]
preload_content: True
headers: {'Content-Type': 'application/json', 'Accept': 'application/json', 'User-Agent': 'Swagger-Codegen/8.0.0/python'}
timeout: None
I can confirm that both ip and port in above url are correct.

My question is, should I expect the rest call is unblocked at the time when a change (add, update or remove) happens to a secret under the specified namespace? Or if I've done something wrong? Or this is indeed an issue fixed/to be fixed?
Thanks,

kubernetes version:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"archive", BuildDate:"2020-04-29T14:23:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
OS: centos 7
Python 2.7.5
python client: kubernetes-client 1.18

**Comment by roycaihw** [comment]
I tried replacing https://github.com/kubernetes-client/python/blob/d63282e8d3e8fc0650a6784d596e5a6899110b89/examples/pod_namespace_watch.py#L41 with 
```
for event in w.stream(v1.list_namespaced_secret, "default", timeout_seconds=10):
```
and I was able to observe secret changes. Could you share your code?

**Comment by bqian20** [comment]
That works, thanks.
