### ISSUE TITLE
Getting custom resources 

### ISSUE THREAD

**Issue by djamaile** [kubernetes-client/python#1162]
**What is the feature and why do you need it**:
Working with Istio I create new resources through the command line and not by code. The custom resource name is serviceentries. With kubectl you would do: 

> kubectl get serviceentries

Apparently it is not possible to get custom resources if they are not created by the python client itself. Don't if this is 100% sure, but I haven't seen a simple solution for this.  

**Describe the solution you'd like to see**:
Would be cool if we can do something like this: 

```python
api.list_custom_resources_for_all_namespaces(resource="serviceentries")
```

**Comment by MoShitrit** [comment]
@djamaile you should be able to get your custom resources using the python client like this:
```python
kubernetes.client.CustomObjectsApi().list_cluster_custom_object(group=<group>,
                                                                                                               version=<version>,
                                                                                                               plural=<plural>)
```

So for example if you have a custom resource named `my-resources.example.com` which serves version `v1alpha1`, you would run:
```python
kubernetes.client.CustomObjectsApi().list_cluster_custom_object(group="example.com",
                                                                                                               version="v1alpha1",
                                                                                                               plural="my-resources")
```

Give that a try and let us know if that worked 😄

**Comment by djamaile** [comment]
Oh it worked! I asked this question on stackoverflow and someone told my that it is not possible. Here is the question: https://stackoverflow.com/questions/61594447/python-kubernetes-client-equivalent-of-kubectl-get-custom-resource/61594809#61594809 

Maybe I worded it wrong? Either way you can give an answer there and i'll accept it or update the question with my own answer. Thanks!

**Comment by MoShitrit** [comment]
Thanks for pointing that out!
I'll share my answer there as well, feel free to mark it as the working solution 😄 
Glad to help!!
