### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by AndrewXWei** [kubernetes-client/python#1163]
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Pod.md
**Description of the issue (please include outputs or screenshots if possible)**:
In the items' description:
"List of pods. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md"
This "api-conventions.md" link can't be opened, please update it. 
Thank you!

**Comment by MoShitrit** [comment]
Looks like the docs were re-structured.
The new doc appears to be here - https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources


I'll have a PR to update it.

**Comment by MoShitrit** [comment]
PR created - #1164 
Thanks for raising the flag @AndrewXWei !

**Comment by AndrewXWei** [comment]
It's helpful! Thanks for your reply @MoShitrit
