### ISSUE TITLE
CRD's don't have dry_run option

### ISSUE THREAD

**Issue by sniranjan** [kubernetes-client/python#1165]
While working with CRDs (create/patch/delete), there is no **dry_run** option similar to the other native objects.
####  API Call for creating a custom object
`api_instance.create_namespaced_custom_object(group, version, namespace, plural, body, pretty=pretty)`
Reference - [create_namespaced_custom_object](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#create_namespaced_custom_object)

####  API Call for Deployment
`api_instance.create_namespaced_deployment(namespace, body, pretty=pretty, dry_run=dry_run, field_manager=field_manager)`

Is there any workaround to this?

**Comment by palnabarun** [comment]
Hi @sniranjan, the support for `dry-run` to CRD's has recently been added (https://github.com/kubernetes-client/gen/pull/154). Whenever the next client version is generated, it would get updated.

/assign

**Comment by LouisPlisso** [comment]
Hi @palnabarun , when can we expect the next version of the client? It's currently blocking us for the dry-run feature
Thanks

**Comment by palnabarun** [comment]
This has now been resolved with the latest client release.

/close
