### ISSUE TITLE
Is there a way to get all pods in a StatefulSet ?

### ISSUE THREAD

**Issue by EKwongChum** [kubernetes-client/python#1167]
**What is the feature and why do you need it**:
In some case, we need to get all pods in a specific StatefulSet and  edit their status.
But now , only throw label_selectors can I find those pods. 
**Describe the solution you'd like to see**:
Maybe some apis like 
```python
list_namespaced_statefulset_pod(watch=False,statefulname=mystatefulname,namespace=mynamespace)
```

**Comment by MoShitrit** [comment]
Hey @EKwongChum !
I don't think that's something that could be achieved through the python client (or any other client, afaik. Even `kubectl` doesn't have the ability to get something like that). The api is mostly built around label or field selectors, so your best bet would be to just pull them using a label selectors. In most cases, the pods would have some sort of a label, i.e. `app=foo` which would just allow to pull them based on that label.
Alternatively, if you don't have a label that you can use for your selector, you can implement a logic in your code to list all namespaced statefulset pods, iterate over them and based on `metadata.owner_references`, find the ones that are owned by the statefulSet you're looking for. It's not perfect, but it's as close as it can get you to what you seek.
