### ISSUE TITLE
How can i get the rollback_to info from the python api

### ISSUE THREAD

**Issue by Sunnykaby** [kubernetes-client/python#1169]
**What is the feature and why do you need it**:
Like the command :'kubectl rollout history deployments dep_name', I can get the revision list for this deployment, like something :
```
kubectl rollout history  deployment taudit
deployment.extensions/taudit
REVISION  CHANGE-CAUSE
1         <none>
2         <none>
3         <none>
4         <none>
```
I create the dep with :
```
k8s_apps_v1 = client.ExtensionsV1beta1Api()
        resp = k8s_apps_v1.create_namespaced_deployment
```
And I update the dep with:
```
k8s_apps_v1 = client.ExtensionsV1beta1Api()
        resp = k8s_apps_v1.replace_namespaced_deployment
```

And I use this Api to get the dep info:
```
k8s_apps_v1 = client.ExtensionsV1beta1Api()
    resp = k8s_apps_v1.list_namespaced_deployment(
```

But I get the rollback_to filed with value 'None'. As I show the info above, I have 4 revision for this dep actually. So, I not know how can i get the right info??? 

**Describe the solution you'd like to see**:

**Comment by Sunnykaby** [comment]
The doc [list_namespaced_deployment](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/ExtensionsV1beta1Api.md#list_namespaced_deployment) show that, the response struct 'ExtensionsV1beta1DeploymentList' has a filed named ’items[i].spec.rollback_to‘.

**Comment by roycaihw** [comment]
(This is a workloads API question, so sig-apps experts who worked on the API will know the answer better) I think it's expected. The `rollback_to` field in extension/v1beta1 deployment has been deprecated and doesn't store any meaningful information. `kubectl rollout history deployments` uses different logic to retrieve the revision list. 

I tested locally with 1.12 kubectl and 1.15 apiserver (Note that extensions/v1beta1 deployment is no longer served by latest apiserver. Please use apps/v1 deployment instead): 

```
$ kubectl rollout history deployment.v1beta1.extensions nginx-deployment -v=7 2>&1 >/dev/null | grep GET
I0608 16:44:26.897611   60388 round_trippers.go:383] GET https://35.193.245.136/apis/extensions/v1beta1/namespaces/default/deployments/nginx-deployment
I0608 16:44:27.070882   60388 round_trippers.go:383] GET https://35.193.245.136/apis/apps/v1/namespaces/default/deployments/nginx-deployment
I0608 16:44:27.119199   60388 round_trippers.go:383] GET https://35.193.245.136/apis/apps/v1/namespaces/default/replicasets?labelSelector=app%3Dnginx
```

What kubectl did was listing all replica sets that belong to the deployment, and retrieved the revisions and change-causes from the replica sets. 

You can also verify it with
```
$ kubectl get deployment.v1beta1.extensions nginx-deployment -oyaml | grep rollbackTo
$ kubectl get rs --selector=app=nginx -oyaml | grep 'kubernetes.io/change-cause'
      kubernetes.io/change-cause: kubectl set image deployment/nginx-deployment nginx=nginx:1.16.1
```

To achieve the same result using the python client, you will need to do the same as kubectl-- listing the replica sets with a label selector, and extract the revisions and change-causes from them.
