### ISSUE TITLE
Kubernetes Version Compatibility

### ISSUE THREAD

**Issue by doremi666** [kubernetes-client/python#1170]
From the screenshot below shows that the supported Kubernetes version is up until 1.15 and the latest version now is 1.18.
![image](https://user-images.githubusercontent.com/26452088/82643999-2ffbe280-9c43-11ea-8133-fe0eebf7d296.png)

May I know does this Python API Client library keep up-to-date with the Kubernetes version? Is there any drawback of using this API client library with Kubernetes version 1.18?

**Comment by roycaihw** [comment]
Yes this client is lagging behind. We are catching up and doing the 12.0.0 release https://github.com/kubernetes-client/python/issues/1052

**Comment by roycaihw** [comment]
A proposal about cutting the following releases is in https://github.com/kubernetes-client/python/issues/1242. 

/remove-lifecycle stale
