### ISSUE TITLE
Potential dependency conflicts between kubernetes and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [kubernetes-client/python#1171]
Hi, as shown in the following full dependency graph of  **_kubernetes_**, **_kubernetes_** requires _**urllib3**_ (>=1.24.2)， while the installed version of **_request _**(1.25.8) requires _**urllib3>=1.21.1,<1.26**_.

According to Pip's “first found wins” installation strategy, _**urllib3 1.25.8**_ is the actually installed version.  

Although the first found package version _**urllib3 1.25.8**_ just satisfies the later dependency constraint （_**urllib3>=1.21.1,<1.26**_), it will lead to a build failure once developers release a newer version of urllib3.

### Dependency tree--------
```
kubernetes  - 11.0.0
| +- certifi(install version:2020.4.5.1 version range:>=14.05.14)
| +- google-auth(install version:1.14.0 version range:>=1.0.1)
| | +- cachetools(install version:4.1.0 version range:>=2.0.0,<5.0)
| | +- pyasn1-modules(install version:0.2.8 version range:>=0.2.1)
| | +- rsa(install version:4.0 version range:>=3.1.4,<4.1)
| | | +- pyasn1(install version:0.4.8 version range:>=0.1.3)
| | +- setuptools(install version:46.1.3 version range:>=40.3.0)
| | +- six(install version:1.14.0 version range:>=1.9.0)
| +- python-dateutil(install version:2.8.1 version range:>=2.5.3)
| +- pyyaml(install version:5.3.1 version range:>=3.12)
| +- requests(install version:2.23.0 version range:*)
| | +- certifi(install version:2020.4.5.1 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:>=3.0.2,<4)
| | +- idna(install version:2.9 version range:>=2.5,<3)
| | +- urllib3(install version:1.25.8 version range:>=1.21.1,<1.26)
| +- requests-oauthlib(install version:1.3.0 version range:*)
| +- setuptools(install version:46.1.3 version range:>=21.0.0)
| +- six(install version:1.14.0 version range:>=1.9.0)
| +- urllib3(install version:1.25.8 version range:>=1.24.2)
| +- websocket-client(install version:0.57.0 version range:>=0.32.0)
| | +- six(install version:1.14.0 version range:*) 
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution
1.	Loosen the version range of **_urllib3_** to be **_<=1.25.8, >=1.24.2_**.
2.	Remove your direct dependency **_urllib3_**, and use the **_urllib3_** transitively introduced by **_requests_**.
3.	Ask your direct dependency requests to loosen the version range of **_urllib3_** to be **_ >=1.21.1_**.
@mbohlool Which solution do you prefer, 1 ,2 or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by roycaihw** [comment]
Some thoughts from the bi-weekly triage meeting today: 
- we can add a e2e test to make sure `pip install` works and fix the version range requirement whenever pip's "first found wins" breaks. One drawback is that there can be a window we fail to catch it given the other modules being released asynchronously.
- unifying the dependency tree is preferred if we can avoid depending on both modules without huge code changes
