### ISSUE TITLE
ApiextensionsV1Api missing

### ISSUE THREAD

**Issue by ClaudiuLSH** [kubernetes-client/python#1172]
**What happened (please include outputs or screenshots)**:
```
>>> client = kubernetes.client.ApiextensionsV1Api()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'kubernetes.client' has no attribute 'ApiextensionsV1Api'
>>> client = kubernetes.client.ApiextensionsV1beta1Api()
>>>
```
The file is missing:
```
# locate apiextensions_v1_api.py
# locate apiextensions_v1beta1_api.py
/usr/local/lib/python3.8/site-packages/kubernetes/client/api/apiextensions_v1beta1_api.py
```
 
**What you expected to happen**:
According to documentation there should be a `ApiextensionsV1Api`.

**How to reproduce it (as minimally and precisely as possible)**:
Try and use `ApiextensionsV1Api.get_api_resources()` or any other function.

**Environment**:
- Kubernetes version (`kubectl version`):  server `v1.17.5` and client `v1.18.2`
- OS (e.g., MacOS 10.13.6): Linux
- Python version (`python --version`): 3.8.3
- Python client version (`pip list | grep kubernetes`): 11.0.0

**Comment by MoShitrit** [comment]
Hey @ClaudiuPID 
What are you using the `extensions` API for?
Technically, this api group has been deprecated in 1.16, so whatever you need to pull from it probably lives under a different group right now.
You can read more about it [here](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)

**Comment by MoShitrit** [comment]
Yeah, looks like it's missing indeed.
I see it on `master` branch, but doesn't look like it exists on any of the release branches (checked 11.0 and 12.0).
Any idea about the reason, @roycaihw @palnabarun ?
If you have any pointers- I can take that issue and work on the fix.

**Comment by roycaihw** [comment]
ApiextensionsV1Api is introduced in Kubernetes 1.16. The 11.0.0 python client is generated against Kuberenetes 1.15 openapi spec so it doesn't have this API. The issue is we are in the middle of cutting a release ([12.0.0a1](https://github.com/kubernetes-client/python/issues/1052)), so the master branch contains a half-baked "snapshot" client, which contains documentation generated from 1.16 openapi. Once the new client is cut, the API will appear in pypi and in the release branch

**Comment by DavidSpek** [comment]
I am currently also facing this issue as I am trying to create volume snapshots. As per issue https://github.com/kubernetes-client/python/issues/1195, the suggested CustomObjects API doesn't seem the way to go and I believe `kubernetes.client.ApiextensionsV1Api` is needed as volume snapshots are CRDs and not custom objects. Is there a workaround for this issue? For reference I am using charmed kubernetes 1.19 and I tried client version 11.0 and 12.0 Beta1 and installing from master.

**Comment by roycaihw** [comment]
Closing as 12.0.0b1 has been released. 

/close
/remove-lifecycle stale

**Comment by javiermarcon** [comment]
keeps happening on django-cloud-deploy 0.3.4 which is the version installed by pip

**Comment by aaron-michaux** [comment]
I just ran across this issue,

```
> pip list | grep kubetest
kubetest           0.9.5

> pip list | grep kubernetes
kubernetes         29.0.0
```

**Comment by leonpros** [comment]
> I just ran across this issue,
> 
> ```
> > pip list | grep kubetest
> kubetest           0.9.5
> 
> > pip list | grep kubernetes
> kubernetes         29.0.0
> ```

having the same issue with the same versions + python 3.10.12
tried downgrading both kubetest and kubernetes, didn't work either
