### ISSUE TITLE
Add proxy support via environment variables

### ISSUE THREAD

**Issue by apyrgio** [kubernetes-client/python#1175]
**What is the feature and why do you need it**:

Most programs detect that they must use a proxy by checking the `http_proxy` / `https_proxy` environment variables. See for example this section of `requests` on proxying: https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

 This is not the case here though, as the user must explicitly override the `.proxy` argument of the `Configuration` class, in order to enable proxying.

https://github.com/kubernetes-client/python/blob/b6e4ae81a2afb49f668a142eb7d1c6e2571ef478/kubernetes/client/configuration.py#L99

**Describe the solution you'd like to see**:

The `Configuration` class should auto-detect the appropriate environment variables and pass them to `urllib3`, given that `urllib3` has chosen not to do it (https://github.com/urllib3/urllib3/issues/1785). If this proposal makes sense, I could open a PR.

**Comment by roycaihw** [comment]
The `Configuration` class is generated by openapi-generator: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/configuration.mustache. Could you file an issue in openapi-generator to propose adding the behavior?

**Comment by apyrgio** [comment]
Nice, thanks for pointing me to the template for this class.
So, I've opened an issue to OpenAPI (https://github.com/OpenAPITools/openapi-generator/issues/6786). You can close this issue if you want to, or keep it open to track the progress of the OpenAPI issue.

**Comment by apyrgio** [comment]
Closing this issue since this is something that should be resolved on the OpenAPI side (I haven't done so yet though).
