### ISSUE TITLE
unable to start pod interactive shell in python client

### ISSUE THREAD

**Issue by mohatb** [kubernetes-client/python#1176]
**What happened (please include outputs or screenshots)**:

I want to create a pod with the **python client SDK** (similar to kubectl run) that gives me results like the below:

    kubectl run --rm --image $IMAGE --overrides="$OVERRIDES" --generator=run-pod/v1 -ti "$POD"

I can see some examples which use exec https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py but this requires to create the pod first and run exec, but does not run **"Interactive Terminal"** as the -ti flags in kubectl run.

The code below works only with sending remote command but not with interactive terminal even if we run command=['/bin/bash'] which shows the output as below.

```
    try:    
        #resp = stream(api_instance.connect_post_namespaced_pod_exec, podname, namespace='default', stderr=True, stdin=True, stdout=True, tty=True)
        stream(api_instance.connect_get_namespaced_pod_exec, podname, namespace='default', stderr=True, stdin=False, stdout=True, tty=False)
    except ApiException as e:
        print("Exception when calling CoreV1Api->connect_get_namespaced_pod_exec: %s\n" % e)
    print(f"Pod created - cannot exec")
```

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/ewgSq.png

**What you expected to happen**:

Start an interactive bash terminal in the pod

**How to reproduce it (as minimally and precisely as possible)**:

Same as above

**Environment**:
- Kubernetes version (`kubectl version`):
Client Version: v1.17.4
Server Version: v1.16.7
- OS (e.g., MacOS 10.13.6):
Linux/WSL
- Python version (`python --version`)
3.6
- Python client version (`pip list | grep kubernetes`)
kubernetes (11.0.0)

**Comment by mohatb** [comment]
any help ?

**Comment by roycaihw** [comment]
This client supports reusing a connection and execute commands interactively. E.g. https://github.com/kubernetes-client/python/blob/b6e4ae81a2afb49f668a142eb7d1c6e2571ef478/kubernetes/e2e_test/test_client.py#L96-L115 and https://github.com/kubernetes-client/python/blob/b6e4ae81a2afb49f668a142eb7d1c6e2571ef478/examples/pod_exec.py#L82-L94

If the goal is to have a bash terminal experience, you could probably achieve it by wrapping the stream call with some module like https://docs.python.org/3/library/pty.html. 

[kubectl](https://github.com/kubernetes/kubernetes/blob/d01cc01ab4455d1c0db84d2cc79d963a1b15d292/staging/src/k8s.io/kubectl/pkg/cmd/exec/exec.go#L350-L376) has a [TTY implementation](https://github.com/kubernetes/kubernetes/blob/d01cc01ab4455d1c0db84d2cc79d963a1b15d292/staging/src/k8s.io/kubectl/pkg/util/term/term.go#L31-L53) that preserves the parent terminal state and does a few things.

**Comment by pawandeep-uber** [comment]
@roycaihw could you please provide a sample code to wrap the stream call for a bash-like experience during pod exec using python client?

**Comment by LucasVanHaaren** [comment]
Hello everyone,

I also want to get a full interactive tty experience using exec_command with pty library. 
But while reading docs I can't find how to achieves this, I don't see any stdin, stdout property that I can bind with pty.

Can someone has any hint about this ?

**Comment by Alexey-NM** [comment]
```python
import sys,os
sys.path.append(os.getcwd())
import lib.debug as debug
debug.init()
from threading import Thread
import shared.kube as kube
from kubernetes.stream import stream
import tty 
import termios

core_api = kube.get_client().get_core_api()


#open stream
resp = stream(core_api.connect_get_namespaced_pod_exec,
                          "nsctl-0",
                          "gs-cluster",
                          command="/bin/bash",
                          stderr=True,
                          stdin=True,
                          stdout=True,
                          tty=True, _preload_content=False)

#redirect input
def read():
    #resp.write_stdin("stty rows 45 cols 130\n")
    while resp.is_open():
        char = sys.stdin.read(1)
        resp.update()
        if resp.is_open():
            resp.write_stdin(char)

t = Thread(target=read, args=[])

#change tty mode to be able to work with escape characters
stdin_fd = sys.stdin.fileno()
old_settings = termios.tcgetattr(stdin_fd)
try:
    tty.setraw(stdin_fd)
    t.start()
    while resp.is_open():
        data = resp.read_stdout(10)
        if resp.is_open():
            if len(data or "")>0:
                sys.stdout.write(data)
                sys.stdout.flush()
finally:
    #reset tty 
    print("\033c")
    termios.tcsetattr(stdin_fd, termios.TCSADRAIN, old_settings)
    print("press enter") 
```

**Comment by roycaihw** [comment]
Would be great if we can have one [example](https://github.com/kubernetes-client/python/tree/master/examples) that does this.
