### ISSUE TITLE
exit code from connect_get_namespaced_pod_exec 

### ISSUE THREAD

**Issue by sunchill06** [kubernetes-client/python#1177]
Hi. @tomplus 

Even though the ws_client has defined a default timeout, (below), I can't seem to get a valid returncode if I don't call the resp.run_forever(timeout=5) the method specifically after the stream() method call.
_request_timeout = kwargs.get("_request_timeout", 60)

My code:
 resp = stream(v1.connect_get_namespaced_pod_exec, podName, namespace, command=exec_command, stderr=True, stdin=False, stdout=True, tty=False, _preload_content=preloadContent)
  resp.run_forever(timeout=5)

Without calling the run_forever method, I always get the returncode as None.

Any pointers?

**Comment by tomplus** [comment]
Hi @sunchill06 

It's correct. When you set _preload_content=False you will get WSClient instance and you have to read all returned data (stdout, sterr, exit code). You can use run_forever which tries to read everything (timeout is optional) or using something like this:

```
while resp.is_open():
    resp.update(timeout=None)
```
https://github.com/kubernetes-client/python-base/blob/49ec06096ebc4e092c1ebc2291bf18ccaac935af/stream/ws_client.py#L232

**Comment by sunchill06** [comment]
Thanks a lot, @tomplus for your inputs.

**Comment by sunchill06** [comment]
Hi @tomplus 

Is there any way to print the real-time command output and then a return code when the connection is closed?

Currently, I am using resp.read_stdout which buffers the output and prints everything at once at the end of the connection.

**Comment by sunchill06** [comment]
I actually tried readline_stdout, but it returns None.

**Comment by Akasurde** [comment]
@sunchill06 Try something like - https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/modules/k8s_exec.py#L168-L174

**Comment by sunchill06** [comment]
Thanks a lot @Akasurde , this helped a lot. 

I wrote something like this:

stdout = []
while resp.is_open():
     resp.update(timeout=1)
     if resp.peek_stdout():
             stdout.append(resp.read_stdout())
             print(''.join(stdout).strip())
print resp.returncode

This prints the command output in almost real-time. 
However, I also want to return the status (returncode) of the command to the calling function. But since I am printing the stdout, the calling function captures the stdout as return code. Any thoughts on this?

**Comment by Akasurde** [comment]
I would do 

```python
	...
    while resp.is_open():
        resp.update(timeout=1)
        if resp.peek_stdout():
            stdout.append(resp.read_stdout())
        if resp.peek_stderr():
            stderr.append(resp.read_stderr())
    err = resp.read_channel(3)
    err = yaml.safe_load(err)
    if err['status'] == 'Success':
        rc = 0
    else:
        rc = int(err['details']['causes'][0]['message'])
   return stdout, stderr, rc

```

**Comment by sunchill06** [comment]
@Akasurde, that is right, but my requirement is to print real-time logs of the command and then finally return the returncode.
