### ISSUE TITLE
Use Dynamic Client to Simplify create_from_yaml

### ISSUE THREAD

**Issue by micw523** [kubernetes-client/python#1182]
**What is the feature and why do you need it**:
The ```create_from_yaml``` function as currently stands, places an assumption on the structure of the function name and depends on the simplification methods depicted in the gen repo to work properly. Due to these restrictions, the utility will not be able to support custom objects, or potentially future APIs.

We already have the dynamic client, which should enable us to bypass the hack. The same method can be applied to delete too.

**Describe the solution you'd like to see**:
Use dynamic client to rework the creating portion of the ```create_from_yaml``` utility, and make sure all existing unit tests function properly.

I already started working on this.
/assign

**Comment by acesir** [comment]
This would be awesome. We heavily use create_from_yaml and ran into a lot of problems with CRDs. I am assuming this would help resolve a lot of that?
