### ISSUE TITLE
Don't support istio api

### ISSUE THREAD

**Issue by cmlfxz** [kubernetes-client/python#1183]
**What is the feature and why do you need it**:
 I need isito api to manage istio gateway,virtualservice ,destinationrule，thanks！
**Describe the solution you'd like to see**:

**Comment by MoShitrit** [comment]
Istio resources are custom resources from k8s perspective and can be managed using the `CustomResources` api.
You can see an example from an older closed issue #1162 
And [this](https://github.com/kubernetes-client/python/blob/b6e4ae81a2afb49f668a142eb7d1c6e2571ef478/kubernetes/docs/CustomObjectsApi.md) is the doc with all possible methods for the `CustomObjectsAPI`

**Comment by cmlfxz** [comment]
oh it work! really help! thanks
myclient = client.CustomObjectsApi()
obj=myclient.list_cluster_custom_object(group="networking.istio.io",version="v1alpha3",plural="virtualservices")

**Comment by MoShitrit** [comment]
Sure thing!
Glad to help :smile:
/close
