### ISSUE TITLE
Config Map watcher crashes because of utf-8 encoding (binary file as content)

### ISSUE THREAD

**Issue by simonstumpf** [kubernetes-client/python#1186]
**What happened (please include outputs or screenshots)**:
I'm trying to do a watch on all configmaps in the kubernetes cluster.
However at some point it crashes
`---> Running application from Python script (app.py) ...
Traceback (most recent call last):
  File "app.py", line 407, in <module>
    for stream in w.stream(api_instance.list_config_map_for_all_namespaces):
  File "/opt/app-root/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 144, in stream
    for line in iter_resp_lines(resp):
  File "/opt/app-root/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 48, in iter_resp_lines
    seg = seg.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 2047: unexpected end of data
`
I know that my code runs at other kubernetes clusters so one configmap seems to not be at the utf-8 format but I don't know which configmap it is.

**What you expected to happen**:
I would like that the configmap just gets skipped

**How to reproduce it (as minimally and precisely as possible)**:
My code:
v1 = client.CoreV1Api()
w = watch.Watch()
for event in w.stream(v1.list_config_map_for_all_namespaces, _request_timeout=60):
    if event['type'] == "ADDED":
        print("Event: %s %s %s" % (event['type'], event['object'].metadata.name, event['object'].metadata.namespace))

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): 1.11
- OS (e.g., MacOS 10.13.6): RHEL 7
- Python version (`python --version`): 3.6
- Python client version (`pip list | grep kubernetes`): 11.0.0

**Comment by simonstumpf** [comment]
So I just spent some more time into troubleshooting and I found out, that the iter_resp_lines function can't handle some binary content. (Its a pk12 file)

**Comment by roycaihw** [comment]
That sounds like a bug we should handle. @simonstumpf Would you like to send a fix, or provide some reproduction steps?

**Comment by simonstumpf** [comment]
I'm not as good in python that I could fix this issue im sorry :(
However I could reproduce this error when I put a non utf-8 valid File into a configmap.

**Comment by jan25** [comment]
Maybe this needs to be in python-base repo. Fix could be to add simple `catch:` block here https://github.com/kubernetes-client/python-base/blob/master/watch/watch.py#L139-L149.

Also i noticed `watch` is not handling `urllib3.exceptions.ReadTimeoutError` and crashes. Not sure if that is intended.

**Comment by ZeroSean** [comment]
I also occurred this problem, is the problem solved?
