### ISSUE TITLE
Rolling updates on created deployments from yaml files

### ISSUE THREAD

**Issue by DiptoChakrabarty** [kubernetes-client/python#1189]
**What is the feature and why do you need it**:
I have create deployment and service using the  create_from_yaml() method which uses a couple of kubernetes yml files , I need it because I am regularly updating the files and launching new deployments and services using the create_from_yaml() method.
However I do not know how to perform a rolling update on an already existing deployment which has been launched by the above method with the python client 

**Describe the solution you'd like to see**:
It would be great if we could have a way to update an individual deployment already created (not necessarily by the python client fully but by files as mentioned above )  by only specifying the changed image name and without having to specify all the details(metadata,labels etc) like in the create deployment notebook example. 

Or a method similar to create_from_yaml()  which could update a deployment or service when new image value is populated in the yaml file  , something like update_from_yaml()

**Comment by roycaihw** [comment]
> update an individual deployment already created (not necessarily by the python client fully but by files as mentioned above ) by only specifying the changed image name

I think the [server-side apply](https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply) feature satisfies the need. The upcoming 12.0.0 python client should have this feature.
