### ISSUE TITLE
ModuleNotFoundError: No module named 'kubernetes.config' when running api_discovery example

### ISSUE THREAD

**Issue by thesyntaxinator** [kubernetes-client/python#1190]
**What happened (please include outputs or screenshots)**:

When running python -m examples.api_discovery, I get 

ModuleNotFoundError: No module named 'kubernetes.config'

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g., MacOS 10.13.6):
MacOS 10.15.2
- Python version (`python --version`)
python 3.8.2
- Python client version (`pip list | grep kubernetes`)
11.0.0

**Comment by roycaihw** [comment]
I couldn't reproduce this issue: 

```
$ python
Python 3.8.2 (default, Jul 21 2020, 17:22:28)
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kubernetes
>>> print(kubernetes.__version__)
11.0.0
>>> import kubernetes.config
>>> print(kubernetes.config.__file__)
/Users/haoweic/.pyenv/versions/3.8.2/lib/python3.8/site-packages/kubernetes/config/__init__.py
```

Perhaps you were running python in a local kubernetes directory which missed the submodule, and python picked up the local module with higher priority: 
```
haoweic@haoweic-macbookpro2:~/Projects/k8s-p1/src/k8s.io/client-python$ rm -r kubernetes/base/
haoweic@haoweic-macbookpro2:~/Projects/k8s-p1/src/k8s.io/client-python$ python
Python 3.8.2 (default, Jul 21 2020, 17:22:28)
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import kubernetes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/haoweic/Projects/k8s-p1/src/k8s.io/client-python/kubernetes/__init__.py", line 20, in <module>
    import kubernetes.config
ModuleNotFoundError: No module named 'kubernetes.config'
```

If that's the case, please download the source code [with the submodule](https://github.com/kubernetes-client/python#installation)
```
git clone --recursive https://github.com/kubernetes-client/python.git
```
