### ISSUE TITLE
Response is not chunked

### ISSUE THREAD

**Issue by Alexis01** [kubernetes-client/python#1192]
I've tried to put an stream to list_namespaced_pod as per the docs, and this is what I've gotten for my troubles:

```
from kubernetes import config, watch
w = watch.Watch()
for event in w.stream(coreApi.list_namespaced_pod,
                              namespace = namespace,
                              label_selector = 'job-name={}'.format(jobName),
                              timeout_seconds = activeDeadlineSeconds + 60):
```
And the response is 200
```
 urllib3.connectionpool - _make_request - DEBUG - https://my.host:port "GET /console/catalog/api/v1/namespaces/my-name-space/pods?labelSelector=job-name%3Dtest&timeoutSeconds=90&watch=True HTTP/1.1" 200
```

Suddenly i got this error:

**ERROR - Exception: Response is not chunked. Header 'transfer-encoding: chunked' is missing.**

I dont know how to add "transfer-encodig" to this request.

**Environment**:
- OpenShift Master (3.11.200)
- Kubernetes Master (v1.11.0+d4cacc0)
- Kubernetes version (`kubectl version`):
- OS (Windows 10):
- Python version (3.8)
- Python client version (11.0.0)

Thanks,

Alexis

**Comment by MoShitrit** [comment]
@Alexis01 from looking at the code of `list_namespaced_pod()` I'm guessing that adding a `limit=N` kwarg to your call could help with solving that. You can see the description of that kwarg [here](https://github.com/kubernetes-client/python/blob/10671f94264265d4af491b7b327042cb3e0a07ad/kubernetes/docs/CoreV1Api.md#example-107):
> limit = 56 # int | limit is a maximum number of responses to return for a list call. If more items exist, the server will set the `continue` field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and kubernetes.clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, kubernetes.clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a kubernetes.client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned. (optional)

Can you try to add that arg to your code and see if that solves the issue?

Example:
```python
from kubernetes import config, watch
w = watch.Watch()
for event in w.stream(coreApi.list_namespaced_pod,
                              namespace = namespace,
                              label_selector = 'job-name={}'.format(jobName),
                              limit = 50,
                              timeout_seconds = activeDeadlineSeconds + 60):
```

**Comment by Alexis01** [comment]
@MoShitrit I´m going to try this param.

Thanks 4 ur help :-)

**Comment by Alexis01** [comment]
@MoShitrit 
I change my code to
```
stream_rsp = w.stream(func = coreApi.list_namespaced_pod, namespace = namespace,
                              label_selector = 'job-name={}'.format(jobName),
                              timeout_seconds = activeDeadlineSeconds + 60, limit = 50)
```
But i got the same error
```
 [1m  [37m 2020-06-25 09:17:35,213 - urllib3.connectionpool - _make_request - DEBUG - https://my.host:port "GET /console/catalog/api/v1/namespaces/my-namespace/pods?labelSelector=job-name%3Dtest&limit=50&timeoutSeconds=90&watch=True HTTP/1.1" 200 3026 
 Exception: Response is not chunked. Header 'transfer-encoding: chunked' is missing.
```
I read that **This field is not supported if watch is true.** and I dont know why there is **watch** param in the query.

**Comment by Alexis01** [comment]
I clear my dependencies and everything is ok, thank you @MoShitrit

**Comment by hubeihubei** [comment]
> I clear my dependencies and everything is ok, thank you @MoShitrit

@Alexis01 what does that “I clear my dependencies” means？I meet the same trouble.thank you
