### ISSUE TITLE
Not having a current context set causes 

### ISSUE THREAD

**Issue by 7AC** [kubernetes-client/python#1193]
When initializing kubectl you typically do something like:

```
for cluster in clusters
do
  kubectl config set-cluster $cluster
  kubectl config set-credentials ...
  kubectl config set-context ...
```

That creates a valid config with multiple clusters, but with `current-context` set to `""`. If you try to load that config with `config.load_kube_config()` the library assumes `""` is a context name and fails with the following:

```
  File "app/main.py", line 131, in get_versions
    config.load_kube_config()
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 739, in load_kube_config
    persist_config=persist_config)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 707, in _get_kube_config_loader_for_yaml_file
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 197, in __init__
    self.set_active_context(active_context)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 250, in set_active_context
    context_name)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 625, in get_with_name
    'Expected object with name %s in %s list' % (name, self.name))
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected object with name  in /kubeconfig/contexts list
```

Shouldn't the library assume `""` means the context is unset and avoid trying to look it up, or make the `context` argument to `config.load_kube_config()` mandatory?

**Comment by MoShitrit** [comment]
Yeah, we can probably throw a more specific error for that case.
I guess we can add an `if` block below [this line](https://github.com/kubernetes-client/python-base/blob/master/config/kube_config.py#L248), something like that:
```python
if context_name == "":
    raise ConfigException('Invalid kube-config file. Expected 'current-context' to be set, but it's empty')
```
I can take care of that.
/assign
/cc @roycaihw @palnabarun 
I see that `config/kube_config.py` is auto-generated and seems like the process is to edit it in `python-base` repo and then run `scripts/update_pycodestyle.sh`. Is that correct? Anything else I should be doing to get this done?

**Comment by 7AC** [comment]
But should `load_kube_config()` really fail with a valid config? I was thinking that the fact that `current-context` is not set should not impact it, in my case for example I just wanted to get a hold of a list of contexts and that's impossible if the configuration was provided to the app externally (via a kubernetes mount in my case).

**Comment by MoShitrit** [comment]
I think it should, because this method is used for authentication setup to the cluster and, assuming no context was provided to that method _and_ `current-context` isn't set in  `.kube/config` file, the client won't know which context to use.
Compare that to `kubectl` usage when `current-context` is set to `""`, and this is what you get:
```bash
$ kubectl get pods
error: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
So yeah, imo it should still fail with an error, but just display a more informative message about the reason for the failure.

**Comment by 7AC** [comment]
I’m not convinced that’s apples to apples though. Shouldn’t the config be still loadable, and then fail on an API call that requires a context to be set?

**Comment by 7AC** [comment]
The situation is the one I mentioned: I get a config passed to me and I want to get the list of contexts to do some initialization. When I'm done with that I can zoom into every context and do some work, but I don't know the list of contexts initially.

**Comment by roycaihw** [comment]
I think it's okay to skip `set_active_context` if `context_name` is not specified and `current-context` is empty. The Java client does [skip](https://github.com/kubernetes-client/java/blob/9dae95dac762cf979c2ace3334feb52f0232a5f8/util/src/main/java/io/kubernetes/client/util/KubeConfig.java#L111-L114), and client-go has some mechanism that is [similar](https://github.com/kubernetes/client-go/blob/d46605b64ea62aa25ab21343f8b674d50e828c89/tools/clientcmd/merged_client_builder.go#L34). 

The only concern I have is that we should make the error message clear for users who didn't intend to defer loading the config and accidentally made API calls without a context.

**Comment by vinayan3** [comment]
I am running into this issue just like @roycaihw  is hitting. I am not able to list the context because the `current-context` is blank. 

If `current-context` is blank then it should still be possible to get a listing of the contexts. `kubectl` supports this and doesn't blow up.

**Comment by weininghu1012** [comment]
I also encounter a similar problem:
` File "/Users/weininghu/.pyenv/virtualenvs/kafka-topic-manager/3.7.8/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 625, in get_with_name
    'Expected object with name %s in %s list' % (name, self.name))
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected object with name  in /Users/weininghu/.kube/config.shopify.cloudplatform/contexts list`

My ~/.kube/config is empty, how shall I properly set it?

**Comment by roycaihw** [comment]
The issue still exists. We should skip set_active_context so the behavior is consistent with kubectl (client-go) and client-java: https://github.com/kubernetes-client/python/issues/1193#issuecomment-662187563

/help

**Comment by MoShitrit** [comment]
I can take that one.
/assign

**Comment by gdlx** [comment]
@7AC Has this been fixed ?

**Comment by marafa-sugarcrm** [comment]
was this fixed? i am also getting the error message

**Comment by mwoodson** [comment]
I don't believe this was fixed.  Just closed.  It should be re-opened.  This current behavior is a real pain for the use cases described in this thread
