### ISSUE TITLE
VolumeSnapshot,VolumeSnapshotClass & VolumeSnapshotContent Support 

### ISSUE THREAD

**Issue by Jainbrt** [kubernetes-client/python#1195]
**What is the feature and why do you need it**:

Do we have plan to support VolumeSnapshot,VolumeSnapshotClass & VolumeSnapshotContent API?

**Describe the solution you'd like to see**:

**Comment by roycaihw** [comment]
It looks like those APIs are CRDs: https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/#the-volumesnapshotclass-resource

If that's the case, you could use the [CustomObject API](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md) to send requests to those APIs once they are installed. Example: https://github.com/kubernetes-client/python/blob/master/examples/custom_object.py

**Comment by DavidSpek** [comment]
I believe this page is more relevant in regards to VolumeSnapshot, VolumeSnapshotClass & VolumeSnapshotContent being CRDs.
https://kubernetes.io/docs/concepts/storage/volume-snapshots/#introduction

**Comment by DavidSpek** [comment]
For those searching for how to create a volume snapshot with the python client, here are 2 code snippets to create a snapshot from a CephFS PVC and to then create a PVC from said snapshot.

Create CephFS snapshot:
```
co_client = podutils._get_k8s_custom_objects_client()

my_resource = {
    "apiVersion": "snapshot.storage.k8s.io/v1beta1",
    "kind": "VolumeSnapshot",
    "metadata": {"name": "new-snapshot-dev-pvc"},
    "spec": {
        "volumeSnapshotClassName": "csi-cephfsplugin-snapclass",
        "source": {"persistentVolumeClaimName": "workspace-dev"}
    }
}
 # create the resource
co_client.create_namespaced_custom_object(
    group="snapshot.storage.k8s.io",
    version="v1beta1",
    namespace="admin",
    plural="volumesnapshots",
    body=my_resource,
)
print("Snapshot created")
```

Create CephFS PVC from above snapshot:
```
co_client = podutils._get_k8s_v1_client()

my_resource = {
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "metadata": {"name": "restore-pvc"},
    "spec": {
        "dataSource": {"name": "new-snapshot-dev-pvc", "kind": "VolumeSnapshot", "apiGroup": "snapshot.storage.k8s.io"},
        "accessModes": ["ReadWriteMany"],
        "resources": {
        "requests": {"storage": "10Gi"}
        } 
    }
}
 # create the resource
co_client.create_namespaced_persistent_volume_claim(
    namespace="admin",
    body=my_resource,
)
print("PVC created")
```

**Comment by HenryBeWell** [comment]
> For those searching for how to create a volume snapshot with the python client, here are 2 code snippets to create a snapshot from a CephFS PVC and to then create a PVC from said snapshot.
> 
> Create CephFS snapshot:
> 
> ```
> co_client = podutils._get_k8s_custom_objects_client()
> 
> my_resource = {
>     "apiVersion": "snapshot.storage.k8s.io/v1beta1",
>     "kind": "VolumeSnapshot",
>     "metadata": {"name": "new-snapshot-dev-pvc"},
>     "spec": {
>         "volumeSnapshotClassName": "csi-cephfsplugin-snapclass",
>         "source": {"persistentVolumeClaimName": "workspace-dev"}
>     }
> }
>  # create the resource
> co_client.create_namespaced_custom_object(
>     group="snapshot.storage.k8s.io",
>     version="v1beta1",
>     namespace="admin",
>     plural="volumesnapshots",
>     body=my_resource,
> )
> print("Snapshot created")
> ```
> 
> Create CephFS PVC from above snapshot:
> 
> ```
> co_client = podutils._get_k8s_v1_client()
> 
> my_resource = {
>     "apiVersion": "v1",
>     "kind": "PersistentVolumeClaim",
>     "metadata": {"name": "restore-pvc"},
>     "spec": {
>         "dataSource": {"name": "new-snapshot-dev-pvc", "kind": "VolumeSnapshot", "apiGroup": "snapshot.storage.k8s.io"},
>         "accessModes": ["ReadWriteMany"],
>         "resources": {
>         "requests": {"storage": "10Gi"}
>         } 
>     }
> }
>  # create the resource
> co_client.create_namespaced_persistent_volume_claim(
>     namespace="admin",
>     body=my_resource,
> )
> print("PVC created")
> ```
Hi~
can you tell me which your python's version is? 
when i use the CustomObjectsApi to create snapshotclass, it occurs error : kubernetes.client.exceptions.ApiException: (404)
