### ISSUE TITLE
how to pass patch type in patch_namespaced_deployment function in python kubernetes client?

### ISSUE THREAD

**Issue by vivekgrover1** [kubernetes-client/python#1202]
Is there any way to pass patch type in  patch_namespaced_deployment function in python kubernetes client,  I want to use MergePatchType for patching the deployment.

api_instance.patch_namespaced_deployment(name, namespace, body, pretty=pretty, dry_run=dry_run, field_manager=field_manager, force=force)

similiar way is there in go client (types.MergePatchType)

deploymentsClient.Patch(context.TODO(), name, types.MergePatchType, patch,metav1.PatchOptions{})

**Comment by roycaihw** [comment]
Currently it's not supported. The client supports auto-detecting JSON patch and strategic merge patch based on the body type https://github.com/kubernetes-client/python/blob/bc79976edfe01b028aef0b93bde54e002b113443/kubernetes/client/rest.py#L160-L163

Supporting patch type selection is discussed in https://github.com/kubernetes-client/python/pull/959

**Comment by cjbaar** [comment]
@roycaihw I am having a similar issue, and am not able use JSON patches at all with this library. The code you show relies on the content being set to 'application/json-patch+json' in the first place, which as far as I can tell from reviewing api.py files, it never does... so this never executes. Do you have any more info on how the "auto-select" of header type is supposed to work?

**Comment by gfrid** [comment]
this frustrating, had to use kubectl inside python to merge annotations

**Comment by EvanKuhn-Affirm** [comment]
Hitting the same problem, have to call out to kubectl from python. Disappointing.

**Comment by duxbuse** [comment]
Likewise for me. I'm trying to do a force patch and cant get it to.
