### ISSUE TITLE
fail to get the ipv6 address(pod_i_ps with V1PodIP type) from pod.status on the dual stack environment

### ISSUE THREAD

**Issue by Telzeng** [kubernetes-client/python#1203]
**What is the feature and why do you need it**:
Recently my project need get the ipv6 address(V1PodIP) from pod.status on the dual stack environment. but found latest Kubernetes does not include the code fix.
I observed that mater branch already included this fix c206745dcd491d64b63260c6b6f46e3a3a81b101.  I want to know when will this code plan to merge in official release 11.0.0+ ?

Doc: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1PodStatus.md
Code fix: https://github.com/kubernetes-client/python/commit/c206745dcd491d64b63260c6b6f46e3a3a81b101

**Describe the solution you'd like to see**: the fix can be merged to new release or minor version ASAP.

**Comment by Telzeng** [comment]
@palnabarun  thanks a lot.
My project expect one regular release. so i want to know when will deliver next release?

**Comment by palnabarun** [comment]
@Telzeng -- this should now be resolved with the latest client release. Please feel to reopen the issue if you feel otherwise.

/close
