### ISSUE TITLE
Error "Missing the required parameter `body`“ happens when calling `patch_namespaced_deployment_scale

### ISSUE THREAD

**Issue by ssquan** [kubernetes-client/python#1206]
**What happened (please include outputs or screenshots)**:
Exception happens when running code similar to the [example](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/AppsV1Api.md#example-30)
```
>>> body = None
>>> api_app.patch_namespaced_deployment_scale('presto-worker', 'bigdata', body)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/apps_v1_api.py", line 3936, in patch_namespaced_deployment_scale
    (data) = self.patch_namespaced_deployment_scale_with_http_info(name, namespace, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/apps_v1_api.py", line 3988, in patch_namespaced_deployment_scale_with_http_info
    raise ValueError("Missing the required parameter `body` when calling `patch_namespaced_deployment_scale`")  # noqa: E501
ValueError: Missing the required parameter `body` when calling `patch_namespaced_deployment_scale
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
Debian GNU/Linux 10
- Python version (`python --version`)
3.8.3
- Python client version (`pip list | grep kubernetes`)
11.0.0

**Comment by roycaihw** [comment]
The generated example is wrong. The `body` is a required parameter so it cannot be `None`. However, since Kubernetes supports different patch methods (JsonPatch, MergePatch, StrategicMergePatch), the payload of the `body` can be in different formats. In the generated code the type of `body` is `UNKNOWN_BASE_TYPE`. I think this is a limitation we get from OpenAPI v2 and openapi-generator.
