### ISSUE TITLE
how to get replicaset information

### ISSUE THREAD

**Issue by lvs071103** [kubernetes-client/python#1212]
```
    config.kube_config.load_kube_config(config_file=str(obj.config_file.file))
    v1 = client.CoreV1Api()
    if ns == 'all':
        rcs = v1.list_replication_controller_for_all_namespaces().items
    else:
        rcs = v1.list_namespaced_replication_controller(namespace=str(ns)).items
```
I found replication controller but I don't know how to get replicas
how to get it ?

**Comment by roycaihw** [comment]
replicaset and replicationcontroller are different APIs. You should use https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/AppsV1Api.md#list_replica_set_for_all_namespaces to get replicasets.

**Comment by lvs071103** [comment]
@roycaihw 
I want edit deployment by yaml, how to do it ?  For example：
![image](https://user-images.githubusercontent.com/5029708/92086199-70e7c380-edfc-11ea-91a7-2455a1e72034.png)
