### ISSUE TITLE
need support  load_kube_config_data()

### ISSUE THREAD

**Issue by onecer** [kubernetes-client/python#1213]
**What is the feature and why do you need it**:

I creating a simply k8s tools to mange that for my customers. They have diffrence cluster.

I want to store kubeconfig in mysql, manage mutilple k8s cluster.

from now just have two way too create a client.

- load_kube_config().  -- load kubeconfig fron file
- client.Configuration() -- use token

I think that kubeconfig is easy to config. Its friendly for my users.

here is my program process steps.

1. read kubeconfig from mysql
2. store it to disk /tmp/xxx.
3. load_kube_config(/tmp/xxx)

**Describe the solution you'd like to see**:

support set kubeconfig from strings. like load_kube_config_data(data='**kubeconfig data**')

**Comment by ConscriptMR** [comment]
well not from strings but from JSONs maybe would be more practical

**Comment by roycaihw** [comment]
Loading kubeconfig from dict support was added recently: https://github.com/kubernetes-client/python-base/pull/195. You can load JSON blob into dict and load kubeconfig from there
