### ISSUE TITLE
BatchV1_api.list_namespaced_job returns only partial data

### ISSUE THREAD

**Issue by liorschwimmer** [kubernetes-client/python#1214]
I'm using kubernetes==10.1.0
My code is in python 3.7 and something like that:

from kubernetes import client as kubernetes_client
BatchV1_api = kubernetes_client.BatchV1Api()
api_response = BatchV1_api.list_namespaced_job(namespace="default", watch = False, pretty='true', async_req=False )

The problem is I got about 1500 jobs in kubernetes and api_response returns only 20
The goal is to implement program which go throw all jobs and delete old ones by job name as parameter
Any idea why I'm getting only partial data from BatchV1_api.list_namespaced_job function?

**Comment by roycaihw** [comment]
I wonder if you're doing paging list. Could you enable the [debug logging](https://github.com/kubernetes-client/python/blob/b5603d8ee2bc0861e26426d7c4a9f09b6adee644/examples/deployment_crud.py#L91-L94) and verify if the response contains a continue token?
