### ISSUE TITLE
can i get or export deploy yaml files which can be used by kubectl apply -f ?

### ISSUE THREAD

**Issue by egoisz** [kubernetes-client/python#1215]
**Link to the issue (please include a link to the specific documentation or example)**:

**Description of the issue (please include outputs or screenshots if possible)**:
the response of read_namespaced_deployment_status(name, namespace=namespace).to_dict(), There are many fields whose names do not conform to k8s yaml file, I want to maintain a yaml file while updating deploy through the k8s python API

**Comment by plusices** [comment]
I am also confused about how to export the original yaml file of k8s resource, just like using the command kubectl get deployment test -o yaml. Does anyone solve this issue??

**Comment by roycaihw** [comment]
This is a duplicate of https://github.com/kubernetes-client/python/issues/1228. `to_dict()` should honor `attribute_map`. This is a bug that needs to be fixed in the upstream client generator.
