### ISSUE TITLE
SSLError(SSLError(0, 'Underlying socket connection gone (_ssl.c:1866)'),) when delete more than one deployment

### ISSUE THREAD

**Issue by 111qqz** [kubernetes-client/python#1219]
**What happened (please include outputs or screenshots)**:
I create two deployment objects via client.AppsV1Api(), when deleting them with delete_namespaced_deployment,I got following error.

```python
 api_response = self.k8s_apps_v1.create_namespaced_deployment(
            body=self.deployment, namespace="default")

 api_response = self.k8s_apps_v1.delete_namespaced_deployment(
            name=self.DEPLOYMENT_NAME,
            namespace="default",
            pretty=True,
            body=client.V1DeleteOptions(propagation_policy='Background',
                                        grace_period_seconds=0))
```

![1](https://user-images.githubusercontent.com/30498101/88902304-9e34d500-d284-11ea-9f7e-28fdfd68fee6.png)

**What you expected to happen**:
two deployments deleted without error 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): v1.17.0
- OS (e.g., MacOS 10.13.6): ubuntu 14.04 
- Python version (`python --version`)  python 3.5.6
- Python client version (`pip list | grep kubernetes`)  11.0.0

**Comment by roycaihw** [comment]
cc @yliaog

**Comment by yliaog** [comment]
do you hit any error if you try to delete them with kubectl?

**Comment by 111qqz** [comment]
> do you hit any error if you try to delete them with kubectl?

No, using kubectl to delete the deployment will exit without any error

**Comment by yliaog** [comment]
api_response = self.k8s_apps_v1.create_namespaced_deployment(
api_response = self.k8s_apps_v1.delete_namespaced_deployment(

so you're creating a deployment, then delete it? in the issue you mentioned the error occurred when deleting more than one deployment.

do you see the error when creating deployment? maybe try creating multiple deployment, and see if you hit the error?
