### ISSUE TITLE
setup fails of the repo

### ISSUE THREAD

**Issue by sunchill06** [kubernetes-client/python#1227]
**What happened (please include outputs or screenshots)**:
After cloning the repo, I ran python setup.py install, and getting below error:
error: pyasn1 0.1.9 is installed but pyasn1<0.5.0,>=0.4.6 is required by set(['pyasn1-modules'])

**What you expected to happen**:
Installation should run fine.

**How to reproduce it (as minimally and precisely as possible)**:
Just run python setup.py install after cloing the repo.

**Anything else we need to know?**:
Earlier I was getting below error, for this I upgraded setuptools.

error in kubernetes setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

**Environment**:
- Kubernetes version (`kubectl version`): 
- OS (e.g., MacOS 10.13.6): RHEL 7
- Python version (`python --version`) 2.7.5
- Python client version (`pip list | grep kubernetes`) 
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
kubernetes                       12.0.0-snapshot

**Comment by palnabarun** [comment]
@sunchill06 -- we are in the process of deprecating support for Python 2.7 in the Python client. We are wondering if there is a compelling reason to use Python 2.7 in your use case. Can you try using Python 3.5+ and see if the error still persists?

**Comment by sunchill06** [comment]
Thanks @palnabarun 

we have a legacy product and it won't be easy for us to migrate to 3.x* asap. I keep getting these issues while building package and recently I got the following:

```
Installed /usr/lib/python2.7/site-packages/oauthlib-3.1.0-py2.7.egg
Searching for rsa<5,>=3.1.4
**Reading https://pypi.org/simple/rsa/**
Downloading https://files.pythonhosted.org/packages/22/4e/772004168e23d2ac5987e189e3b4a4305169e45057d8776e9d36c1ef250f/rsa-4.7.tar.gz#sha256=69805d6b69f56eb05b62daea3a7dbd7aa44324ad1306445e05da8060232d00f4
Best match: rsa 4.7
Processing rsa-4.7.tar.gz
Writing /tmp/easy_install-6PBj7X/rsa-4.7/setup.cfg
Running rsa-4.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6PBj7X/rsa-4.7/egg-dist-tmp-6gkO5H
warning: no files found matching 'CHANGELOG.txt'
  File "build/bdist.linux-x86_64/egg/rsa/_compat.py", line 20
    def byte(num: int) -> bytes:
                ^
SyntaxError: invalid syntax
```

I was able to build the egg package with some workaround and installing it using easy_install, but its still going to pypi.

```
/usr/bin/easy_install -d /usr/lib/python2.7/site-packages/ requests cachetools==3.1.1 rsa==4.5 \
     /opt/temp/packages/kubernetes-12.0.0_snapshot-py2.7.egg
```

And as can be seen in the error above, its somehow going to pypi to fetch the dependencies etc, when I am supplying the local pythong egg package, why does it keep on going to pypi?
**Reading https://pypi.org/simple/rsa/**

Please help here.
