### ISSUE TITLE
Documentation not rendering in GitHub

### ISSUE THREAD

**Issue by jicowan** [kubernetes-client/python#1230]
**Link to the issue (please include a link to the specific documentation or example)**:
@palnabarun the documentation is not rendering in GitHub
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#create_namespaced_service
**Description of the issue (please include outputs or screenshots if possible)**:

**Comment by roycaihw** [comment]
duplicated: https://github.com/kubernetes-client/python/issues/1207#issuecomment-670253470
