### ISSUE TITLE
v1.list_pod_for_all_namespaces(watch=False) takes too long

### ISSUE THREAD

**Issue by zzmg** [kubernetes-client/python#1231]
**What happened (please include outputs or screenshots)**:

In our cluster, there are about 900 pods in total。use v1.list_pod_for_all_namespaces(watch=False)，takes about three seconds，use  api_instance.list_deployment_for_all_namespaces，takes about one seconds。in cluser，use kubectl get pods --all-namespaces，takes about one seconds

**What you expected to happen**:
Can the list pod interface be optimized ？？？
**How to reproduce it (as minimally and precisely as possible)**:
in your cluser，try it
**Anything else we need to know?**:
no more
**Environment**:
- Kubernetes version (`kubectl version`):
v1.10.5
- OS (e.g., MacOS 10.13.6):
ubuntu18.04
- Python version (`python --version`)
3.6
- Python client version (`pip list | grep kubernetes`)
kubernetes              11.0.0

**Comment by roycaihw** [comment]
I think the main difference is the encoding. The python client uses json and kubectl uses protobuf. Ref https://github.com/kubernetes-client/python/issues/166
