### ISSUE TITLE
support k8s 1.17 and 1.18 

### ISSUE THREAD

**Issue by nickvth** [kubernetes-client/python#1233]
1.15 is EOL and 1.16 will be EOL 10-2020

See: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md

**Comment by roycaihw** [comment]
/assign @palnabarun 

Nabarun is creating an umbrella issue to document the release process changes and track 1.16-1.19 releases

**Comment by palnabarun** [comment]
Tracking this as an umbrella in #1242.
