### ISSUE TITLE
Python to use Kubernetes API 

### ISSUE THREAD

**Issue by vardans6** [kubernetes-client/python#1238]
Need python to use kubernetes API to create kafka cluster and add monitoring for it, alerts whenever kafka master goes down.

Please help

**Comment by palnabarun** [comment]
Hi @vardans6, I think this question is more regarding how to deploy a particular software using Kubernetes. The questions of deploying Kafka can be answered better by the users of Kubernetes. You can check out the `#kubernetes-users` channel on the Kubernetes Slack.

Once Kafka is deployed, then you can go through the documentation of this client to talk to the Kubernetes API and create the required resources.

Let me know if that helps.
