### ISSUE TITLE
how to update configmap

### ISSUE THREAD

**Issue by 573009114** [kubernetes-client/python#1240]
excuse me . 
how to update configmap? similar to  kubectl apply -f configmap.yaml

**Comment by roycaihw** [comment]
You can use [patch_namespaced_config_map](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#patch_namespaced_config_map) or [replace_namespaced_config_map](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#replace_namespaced_config_map). See [example](https://github.com/kubernetes-client/python/blob/master/examples/job_crud.py#L59-L66) of patching other APIs.
