### ISSUE TITLE
Not all return codes are documented

### ISSUE THREAD

**Issue by soslan** [kubernetes-client/python#1245]
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/BatchV1Api.md#create_namespaced_job
**Description of the issue (please include outputs or screenshots if possible)**:
`create_namespaced_job` returns `409 Conflict` if the job being created already exists, but the docs doesn't mention the code. Aren't all possible response codes meant to be documented?

**Comment by roycaihw** [comment]
This is a openapi spec issue that needs to be fixed in the upstream https://github.com/kubernetes/kubernetes/issues/69014.
