### ISSUE TITLE
Unable to patch daemonset

### ISSUE THREAD

**Issue by jicowan** [kubernetes-client/python#1248]
**What happened (please include outputs or screenshots)**:
Trying to use the AppsV1Api to patch a namespaced daemonset.  I keep getting the error: 
```
AppsV1.patch_namespaced_daemonset(name='aws-node', namespace='kube-system', body=patch)
AttributeError: 'AppsV1Api' object has no attribute 'patch_namespaced_daemonset'
```
Other methods like list_namespaced_daemonsets work fine.  Here is the code I used to patch the daemonset: 
```
    print('Patching aws-node daemonset')
    if 'Clientset' in kwargs:
        api_client = kwargs['Clientset']
        AppsV1 = client.AppsV1Api(api_client)
    else:
        AppsV1 = client.AppsV1Api(api_client=config.new_client_from_config(context=Context))

    patch = {
        "spec": {
            "template": {
                "metadata": {
                    "annotations": {
                        "irsa": "enabled"
                    }
                }
            }
        }
    }
    try:
        AppsV1.patch_namespaced_daemonset(name='aws-node', namespace='kube-system', body=patch)
    except ApiException:
        print('An error occurred while patching the aws-node Daemonset')
        exit(1)
```
The Clientset is derived from this method: 
```
def create_clientset(ApiEndpoint: str, ClusterName: str, Certificate: str):
    token = get_token(ClusterName)
    configuration = client.Configuration()
    configuration.host = ApiEndpoint
    configuration.verify_ssl = False  # Should change this to true
    configuration.api_key = {'authorization': 'Bearer ' + token}
    api_client = client.ApiClient(configuration)
    return api_client
```
The context is coming from this method: 
```
def choose_context():
    try:
        config.load_kube_config()
    except Exception:
        print('Could not find kubeconfig in the default location.')
        return None
    contexts, active_context = config.list_kube_config_contexts()
    if not contexts:
        print("Cannot find any context in kube-config file.")
        exit(1)
    contexts = [context['name'] for context in contexts]
    active_index = contexts.index(active_context['name'])
    selected, first_index = pick(contexts,
                                 title="Pick the context to run this against (press SPACE to mark, ENTER to continue): ",
                                 default_index=active_index)
    return selected
```
**What you expected to happen**:
I expect the daemonset to get patched. 

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:
I don't think so. 

**Environment**:
- Kubernetes version (`kubectl version`): 1.16
- OS (e.g., MacOS 10.13.6): 10.15.6
- Python version (`python --version`)
3.8.5
- Python client version (`pip list | grep kubernetes`)
11.0.0

**Comment by jicowan** [comment]
I got this to work by using patch_namespaced_daemonset_with_http_info.  It appears there's something wrong with patch_namespaced_daemonset.

**Comment by roycaihw** [comment]
The method name is [patch_namespaced_daemon_set](https://github.com/kubernetes-client/python/blob/v11.0.0/kubernetes/docs/AppsV1Api.md#patch_namespaced_daemon_set). I noticed that you missed a `_` in your code. Was that a typo?

**Comment by jicowan** [comment]
No, not a typo.  I used what intellisense suggested when I typed . after the client.

**Comment by roycaihw** [comment]
Sounds like a problem with the autocomplete. Does using `patch_namespaced_daemon_set` fix the issue?

**Comment by jicowan** [comment]
Yes, it did, however I would suggest making the API calls consistent, e.g. patch_namespaced_daemon_set and patch_namespaced_daemonset_with_http_info.  Is there a particular reason 1 has a `_`  between daemon and set and one doesn't?
