### ISSUE TITLE
Help for create rolebinding

### ISSUE THREAD

**Issue by Kamerads** [kubernetes-client/python#1251]
Hi!
Help me please translate this command into kubernetes client python
kubectl create rolebinding team1 --namespace=test --clusterrole=edit --serviceaccount=users:test1

**Comment by MoShitrit** [comment]
```python
    def create_role_binding():
        import kubernetes
        rbac_api = kubernetes.client.RbacAuthorizationV1Api()
        metadata = kubernetes.client.V1ObjectMeta(name='team1')
        role_ref = kubernetes.client.V1RoleRef(api_group='rbac.authorization.k8s.io', kind='ClusterRole', name='edit')
        subject = kubernetes.client.V1Subject(kind='ServiceAccount', namespace='users', name='test1')
        role_binding = kubernetes.client.V1RoleBinding(metadata=metadata, role_ref=role_ref, subjects=[subject])
        resp = rbac_api.create_namespaced_role_binding(namespace='test', body=role_binding)
```

And here's the reference from the docs - https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1RoleBinding.md

**Comment by Kamerads** [comment]
Thank you very much! What if you need to specify multiple --serviceaccounts?
for example kubectl create rolebinding team1 --namespace=test --clusterrole=edit --serviceaccount=users:test1 --serviceaccount=test:default ?

**Comment by MoShitrit** [comment]
Sure thing!
So as you can see in the line before last, where we declare the `role_binding` object, `subjects` is in fact of type `list()`, so you can create as many subjects as you'd like and pass them into that list:

```python
subject1 = kubernetes.client.V1Subject(kind='ServiceAccount', namespace='users', name='test1')
subject2 = kubernetes.client.V1Subject(kind='ServiceAccount', namespace='test', name='default')
role_binding = kubernetes.client.V1RoleBinding(metadata=metadata, role_ref=role_ref, subjects=[subject1, subject2])
```

**Comment by Kamerads** [comment]
After you showed it became clear, thank you again

**Comment by MoShitrit** [comment]
Sure thing! Glad to help 😄
