### ISSUE TITLE
Support for kind: IngressClass in v1beta1

### ISSUE THREAD

**Issue by vepatel** [kubernetes-client/python#1255]
**What is the feature and why do you need it**:
[As per improvements to ingress api in 1.18](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#extended-configuration-with-ingress-classes) there should be python client support for `kind: IngressClass`

**Describe the solution you'd like to see**:
Create, delete and patch apis in `kubernetes.client.NetworkingV1beta1Api` or in `kubernetes.client.ExtensionsV1beta1Api`

**Comment by palnabarun** [comment]
Hi @vepatel :wave:, we are going to release the client based on Kubernetes 1.18 shortly. Issue #1242 tracks the release cadence.

**Comment by vepatel** [comment]
Thanks for the update @palnabarun
