### ISSUE TITLE
Disable Portforward Websocket logging

### ISSUE THREAD

**Issue by razilevin** [kubernetes-client/python#1261]
When using port-forward I see excessive logging which I cannot figure out how to disable.

```
send: b'POST /search-phrases-3448cbae-4514-4db8-aeb4-de3df35bc9c4/_doc HTTP/1.1\r\nHost: localhost:9200\r\nAccept-Encoding: identity\r\nContent-Length: 60\r\nconnection: keep-alive\r\ncontent-type: application/json\r\nuser-agent: elasticsearch-py/7.9.1 (Python 3.8.5)\r\nauthorization: Basic ***=\r\n\r\n'
send: b'{"keyword":"Bakery Banquet Towers","brand":[1020],"rank":52}'
reply: 'HTTP/1.1 201 Created\r\n'
header: Location: /search-phrases-3448cbae-4514-4db8-aeb4-de3df35bc9c4/_doc/kJgvuHQBIdhqAydPXo9A
header: content-type: application/json; charset=UTF-8
header: content-length: 219
```

**Environment**:
kubernetes 12.0.0-snapshot

**Comment by razilevin** [comment]
The root cause was urllib3 logging the request and response.

To fix I had to write the following code to suppress these logging statements.
`urllib3.connection.HTTPConnection.debuglevel = 0`

What led me to believe that this was caused by port forwarding was not seeing those logging statements when a direct
`kubectl port-forward...` was executed instead of the very cool urllib3 default socket factory function monkey patching as documented in the port-forward example.

**Comment by roycaihw** [comment]
The client configuration has a debug switch that sets the debuglevel: https://github.com/kubernetes-client/python/blob/master/kubernetes/client/configuration.py#L250-L270. Did you accidentally set it? I would be surprised if port-forward overrides the debuglevel.
