### ISSUE TITLE
Cannot find a clear example for Configuration and how to manage multiple configurations

### ISSUE THREAD

**Issue by maephisto666** [kubernetes-client/python#1263]
Let's take the following 2-3 snippets
- https://github.com/kubernetes-client/python#examples
- https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md#getting-started

It is clear to me that to set the configuration to communicate with the k8s cluster there are at least 2 ways:
- loading a `kubeconfig` file
- setting some parameters inside a `Configuration` object and create a corresponding `api_client`

Loading a `kubeconfig` file is super easy. It only seems to me that once I read the file, every time I instantiate a new API object such configuration will be reused. Now, if I want to write a program that connects to 2 clusters I don't understand how I can manage 2 configurations both read from different kubeconfig files for example. 

Beside that it would be nice to clearly define 2 `Configuration` objects and use them throughout the program whenever I need to connect to one cluster or to the other one. Now, creating a Configuration object seems not very simple and I could not find an appropriate section in the documentation which explains this. It is clear that I should generate a token and set a host. I can generate a token via the `awscli` (since my k8s cluster is hosted on AWS), but if I set the host then I get a SSL error saying that the certificate is not valid. By debugging I found out that the Configuration object created by the `config.load_kube_config()` function has the correct ca and other stuff (beside the token and the host).

Now my request, if possible, is to improve the documentation dedicating a section to how to manage the Configuration object, the gotchas and the connections to the `config.load_kube_config()` function.

**Comment by tomplus** [comment]
Hi @maephisto666 

There is an example which list pods from two different clusters: https://github.com/kubernetes-client/python/blob/master/examples/multiple_clusters.py maybe it helps.

**Comment by maephisto666** [comment]
> Hi @maephisto666
> 
> There is an example which list pods from two different clusters: https://github.com/kubernetes-client/python/blob/master/examples/multiple_clusters.py maybe it helps.

You are right @tomplus. There I can see the second option. Instead of calling the method `config.load_kube_config()` with no params, you can use either `config.new_client_from_config` or `config.load_kube_config` with one param to create the api_client object you can use later to create the `CoreV1Api`.
