### ISSUE TITLE
bug with list_namespaced_deployment

### ISSUE THREAD

**Issue by nachoparodi** [kubernetes-client/python#1264]
Hello friends, i have a problem with the client, i want to find a solution with your help. sorry my leguaje. Maybe I'm doing something wrong.

**What happened (please include outputs or screenshots)**:

i have a backend service that consume the kubernets api client, in the module CoreV1Api it's response ok, but in the AppsV1Api with the endpoint:  list_namespaced_deployment(namespace = ns, pretty = true) the response for 'items' is empty:

```
{
  "message": "{'api_version': 'apps/v1',\n 'items': [],\n 'kind': 'DeploymentList',\n 'metadata': {'_continue': None,\n              'remaining_item_count': None,\n              'resource_version': '324391948',\n              'self_link': '/apis/apps/v1/namespaces/<namespace>/deployments'}}"
}
```

Can't take the name for the components.

**What you expected to happen**:

i want to list the name of deployements in a namespace.

**How to reproduce it (as minimally and precisely as possible)**:

this is my function:

```
##instance api, is not the problem

api_client = kubernetes.client.ApiClient(configuration)
AppsV1instance = kubernetes.client.AppsV1Api(api_client)

@application.route('/<ns>/deployments', methods=['GET'])
def events(ns):
    deployments = AppsV1instance.list_namespaced_deployment(namespace = ns, pretty = true)

    return jsonify(message = str(deployments))

# this is to format the output, but for now i'snt work
#    data = [{
#        'deployment_name': i.metadata.name,
#        'deployment_namespace': i.metadata.namespace,
#        } for i in deployments.items]
#    return jsonify(message = str(data))
```

**Anything else we need to know?**:
i have all requierments installed.

**Environment**:

openshift api client 3.11 - client kubernets - python3.6.3 - flask

**Comment by roycaihw** [comment]
Could you use kubectl to double-check if there is any deployment in that namespace? Also could you enable [debug logging](https://github.com/kubernetes-client/python/blob/945aac9f1ece97b39c8598e769ada5a65355fdde/examples/deployment_crud.py#L91-L94) to see if the client-python request is for the same namespace?

**Comment by dimitrijevskiv** [comment]
@nachoparodi have you managed to find the root cause, I'm hitting on this as well.

**Comment by melinaurruchua** [comment]
Both, namespace and pretty, values must be strings. Pretty is not bool
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/AppsV1Api.md
