### ISSUE TITLE
Create Jupyter notebooks for common operations

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-client/python#127]
I started writing simple notebooks for interactive use of this client:

https://github.com/skippbox/notebooks

I am creating this issue to track a proposed GSoC project to expand on those notebooks:

https://github.com/cncf/soc

**Comment by ianubhav** [comment]
Hi Sebastien. Is this project still open?

**Comment by sebgoa** [comment]
@ianubhav yes this project is open. You will need to submit an application starting March 20th.
if you are interested by this, you can start using the python client for k8s and look at the notebooks project in https://github.com/skippbox/notebooks . Then maybe submit a few PRs...

**Comment by ianubhav** [comment]
Hi Sebastian,
I actually have a good understanding of Jupyter notebooks and Docker. Not so much for Kubernotes. I was unableto execute the command as I was getting this error "The connection to the server localhost:8080 was refused - did you specify the right host or port?". Are you using minikube or glocud for your environment

**Comment by ianubhav** [comment]
Hi @sebgoa 

While running this from python console, I was getting error. Can you help me resolve?

ret = v1.list_pod_for_all_namespaces(watch=False)

ApiException: (0)
Reason: SSLError
[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)

gives an SSL error

**Comment by ianubhav** [comment]
Hi @sebgoa ,
I setup the notebooks and kubernetes.
I was getting an error while running 
config.load_incluster_config()

The error is:
---------------------------------------------------------------------------
ConfigException                           Traceback (most recent call last)
<ipython-input-3-91ba88871994> in <module>()
----> 1 config.load_incluster_config()

/home/clab3-15/Desktop/anubhav-btp/kubernetes/lib/python3.4/site-packages/kubernetes/config/incluster_config.py in load_incluster_config()
     89     not running in a kubernetes environment."""
     90     InClusterConfigLoader(token_filename=SERVICE_TOKEN_FILENAME,
---> 91                           cert_filename=SERVICE_CERT_FILENAME).load_and_set()

/home/clab3-15/Desktop/anubhav-btp/kubernetes/lib/python3.4/site-packages/kubernetes/config/incluster_config.py in load_and_set(self)
     43 
     44     def load_and_set(self):
---> 45         self._load_config()
     46         self._set_config()
     47 

/home/clab3-15/Desktop/anubhav-btp/kubernetes/lib/python3.4/site-packages/kubernetes/config/incluster_config.py in _load_config(self)
     49         if (SERVICE_HOST_ENV_NAME not in self._environ or
     50                 SERVICE_PORT_ENV_NAME not in self._environ):
---> 51             raise ConfigException("Service host/port is not set.")
     52 
     53         if (not self._environ[SERVICE_HOST_ENV_NAME] or

ConfigException: Service host/port is not set.
---------------------------------------------------------------------------


Please help

**Comment by sebgoa** [comment]
Once the noteboooks for common operations are written:

* start pod
* create deployment
* create service
* rolling update

we can start working on:

https://github.com/kubernetes-incubator/client-python/issues/66

**Comment by djkonro** [comment]
@sebgoa, I have submitted a proposal for this project and I am looking forward to a review of my proposal. Thanks.

**Comment by stibi** [comment]
Hello, maybe I should create a new issue, I can do that later and now I'll ask here: I have some code done using client-python, we are running a WP hosting on Kubernetes  and client-python is used to deploy a WP site using AWS Lambda.

I can contribute a notebook for WP deployment on k8s…kind of "hello world" app in the docker world I'd say :) Does it sound helpful, or do you have something more basic to focus on now?

**Comment by sebgoa** [comment]
@stibi that would be great. The goal is to create a set of notebooks that people can walk through to do basic operations in k8s. The notebooks should not only contain the code, but also a bit of markdown to explain the steps.

In addition to the above, things like:

* create a daemonset, configmap, secret, ingress
* label pods and other resources (equivalent of `kubectl label`)
* annotate resources (equivalent of `kubectl annotate`)
* example of querying resources by labels

Then we can start doing things a bit more involved:

* watch and perform actions
* third party resources

**Comment by djkonro** [comment]
Pull Requests:
- Update create_deployment notebook:  https://github.com/kubernetes-incubator/client-python/pull/239
- Add introductory notebook: https://github.com/kubernetes-incubator/client-python/pull/272
- Remove code execution output from create_pod notebook: https://github.com/kubernetes-incubator/client-python/pull/261
- Add notebook on how to create a Service: https://github.com/kubernetes-incubator/client-python/pull/250
