### ISSUE TITLE
How can I get the correct API object for cert-manager Certificates?

### ISSUE THREAD

**Issue by bendavis78** [kubernetes-client/python#1272]
I would like to use the python client to apply `Certificate` resources under the `cert-manager.io/v1alpha2` API. Does the kubernetes python client support making calls for this?

**Comment by bendavis78** [comment]
Never mind - I found the `CustomObjectsApi` which appears to suit my needs.

**Comment by KeithTt** [comment]
Is there a API can Check certificate expiration?  Like the output of `kubeadm alpha certs check-expiration`.
