### ISSUE TITLE
Accessing pod attributes using jq syntax

### ISSUE THREAD

**Issue by nimrodishi** [kubernetes-client/python#1275]
Hi!
When using kubectl via the cli, I can do:
```
kubectl get pods -o json | jq -r .<some expression here>
```
Is there any way to do something similar here?
I have:
```
...
pods = client.list_namespaced_pod(namespace)
for pod in pods.items:
    pyjq.all(<a parameter script>, pod.to_dict())
```
since to_dict() doesn't convert values to str(values), it doesn't work, nor does `pyjq.all(<a parameter script>, pod.to_str())`
I now manually parse the <script> parameter, and then:
```
pod_as_dict = pod.to_dict()
for s in some_parse_function(script):
    pod_as_dict = pod_as_dict.get(s, None)
    if pod_as_dict is None:
        raise RuntimeError("..."
```

tl;dr
pyjq doesn't work with V1Pod class, need to manually break this down

Is there any official/good way of doing this?

**Comment by MoShitrit** [comment]
Hey @nimrodishi !
If I understand your question right, take a look at [preload_content](https://github.com/kubernetes-client/python/blob/bc79976edfe01b028aef0b93bde54e002b113443/kubernetes/client/rest.py#L122-L124).
It defaults to `True`, which parses the output of your request to a `V1Pod` object.
Instead, if you pass `preload_content=False` to your request, you get a `json` object back which you can interact with in a similar fashion.
Hope this helps!

**Comment by roycaihw** [comment]
Moshe is correct. Please use `_preload_content=False` if you want to get the raw data.
