### ISSUE TITLE
Load system certificates by default instead of Mozilla root certs

### ISSUE THREAD

**Issue by Smana** [kubernetes-client/python#1276]
Hi everyone!

We have our own pki and the ca certificate is loaded into the system.
However, using the kubernetes python doesn't support loading system certs.

I checked the urllib changes and it is supposed to work (https://github.com/urllib3/urllib3/pull/1608)

```
* Change ``HTTPSConnection`` to load system CA certificates
  when ``ca_certs``, ``ca_cert_dir``, and ``ssl_context`` are
  unspecified. (Pull #1608, Issue #1603)
```
 
Currently the default behaviour of the kubernetes python librairy is to use Mozilla's root certificates (https://github.com/kubernetes-client/python/blob/master/kubernetes/client/rest.py#L70)

Is there a reason for that ?

**Environment**:
- Kubernetes version: 1.15.9
- OS (e.g., MacOS 10.13.6): Ubuntu bionic
- Python version: 3.7.9
- Python client version: 7.0.0

**Comment by palnabarun** [comment]
This issue is similar to https://github.com/kubernetes-client/python/issues/1131

**Comment by roycaihw** [comment]
cc @palnabarun 

This file is generated by openapi-generator. Should this be an upstream generator issue?
