### ISSUE TITLE
Header key 'Authorization' or 'authorization'

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/python#128]
Throughout the client-python implementation, we consistently used 'authorization' as the header key. urllib3 is also using that, but in some libraries, capital "Authorization" is used. This issue is a placeholder for doing a research on this and make sure we are doing the right thing.

**Comment by SEJeff** [comment]
The correct http header is [Authorization](https://tools.ietf.org/html/rfc7235#section-4.2) with a capital `A`, however most python client libs use them case insensitive (see: requests, or django's test client as examples).

**Comment by mbohlool** [comment]
I agree, it should be capital `Authorization` with case insensitive checks. Will add help needed label so somebody look at this (It could be me if I find the time).

**Comment by saurav-malani** [comment]
Hi @mbohlool @SEJeff. If no one is working on this issue, then I would like to work on this issue.
