### ISSUE TITLE
use kubernetes client in pod

### ISSUE THREAD

**Issue by love-miao** [kubernetes-client/python#1293]
**Link to the issue (please include a link to the specific documentation or example)**:

**Description of the issue (please include outputs or screenshots if possible)**:
I want to use kubernetes client in pod, but I don't want to use the default serviceaccount of pod. I want to define a unified serviceaccount. How can I use this serviceaccount in kubernetes client, can I only get the token method manually first?

**Comment by MoShitrit** [comment]
Hey again @love-miao 😄 
Take a look at [this](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/) doc. It explains how to mount a serviceAccount into a pod.
You may also want to look at [this](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) doc to learn more about RBAC and how to implement it in Kubernetes if you're not familiar with it.
Hope this helps!

**Comment by roycaihw** [comment]
/assign @MoShitrit 
Thanks!

**Comment by brennerm** [comment]
Setting the service account in your Pod spec, like @MoShitrit described and using [this function](https://github.com/kubernetes-client/python-base/blob/master/config/incluster_config.py#L112) should do what you are looking for.
