### ISSUE TITLE
client call differs then calling via cli

### ISSUE THREAD

**Issue by nimrodishi** [kubernetes-client/python#1297]
**What happened (please include outputs or screenshots)**:
`
from kubernetes import client, config, configuration
...
config.load_kube_config(config_file="my-config", context="my-context")
client = client.CoreV1Api()
client.list_namespaced_pod("my-namespace")
`
raises an error:
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:anonymous\" cannot list resource \"pods\" in API group \"\" in the namespace \"default\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}\n

while running from the terminal:
`
kubectl get pods -n my-namespace --kubeconfig my-config --context my-context
`
is actually working

**What you expected to happen**:
expect this to work
**Environment**:
- Kubernetes version:
`
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
`
- OS: centos8
- Python version: 3.7.5+
- Python client version: 10

**Comment by yliaog** [comment]
it looks that it is not authenticated to the server during the api call: "message":"pods is forbidden: User "system:anonymous",

could you post your kubeconfig?
