### ISSUE TITLE
Unable to run a command inside windows container

### ISSUE THREAD

**Issue by PranayWankhede** [kubernetes-client/python#1312]
**What happened (please include outputs or screenshots)**:
Unable to execute commands inside windows containers
**What you expected to happen**:
output.txt created 
**How to reproduce it (as minimally and precisely as possible)**:
use the following piece of code
v1 = client.CoreV1Api()
    ret = v1.list_namespaced_pod("default")
    command = 'echo "hello world" > output.txt'
    command = shlex.split(command)
    #v1.delete_namespaced_pod()
    for pods in ret.items:
        print("%s\t%s\t%s" % (pods.status.pod_ip, pods.metadata.namespace, pods.metadata.name))
        for container in pods.status.container_statuses:
            if container.ready:
                try:
                    resp = stream(
                        v1.connect_get_namespaced_pod_exec,
                        name=pods.metadata.name,
                        namespace="default",
                        container=container.name,
                        command=command,
                        stderr=True,
                        stdin=False,
                        stdout=False,
                        tty=False,
                        _preload_content=False,
                    )
                    resp.close()
response is successful but after doing exec into the container there is no output.txt
**Anything else we need to know?**:
Windows Containers
Tried this command kubectl exec podname -- cmd.exe -c helloworldcontainer -- echo "hello world" > output.txt
using powershell and this is also not working.
**Environment**:
- Kubernetes version (1.17.11):
- Windows:
- Python version (`Python 3.8.6`)
- Python client version (`12.0.0`)

**Comment by PranayWankhede** [comment]
@palnabarun can you please help me with this? since i am using this library for hackathon project? there seems to be a particular issue with executing commands against windows container

**Comment by PranayWankhede** [comment]
tried even using kubectl :- kubectl exec helloworld-deployment-8494f859d5-fnkgt -c helloworldcontainer  cmd.exe -- echo "hello world" > output.txt but this also didnt work

**Comment by palnabarun** [comment]
@PranayWankhede -- Hi 👋🏽, this issue seems to me more relevant to the usage of `kubectl` and the container you are you trying to exec the command in. I think https://discuss.kubernetes.io/ may be the right forum to ask this question in. You would find a lot of Windows container users there.

**Comment by palnabarun** [comment]
/close

(due to non-responsiveness)

Please feel free to reopen if you face this issue again.
