### ISSUE TITLE
Run Powershell script inside windows container

### ISSUE THREAD

**Issue by PranayWankhede** [kubernetes-client/python#1313]
**What is the feature and why do you need it**:
I want to run a powershell script inside a pod containing windows container for doing load testing.
**Describe the solution you'd like to see**:
I would like to know if there is any command which i send using the below mentioned code to run the script :- 
resp = stream(
                        v1.connect_get_namespaced_pod_exec,
                        name=pods.metadata.name,
                        namespace="default",
                        container=container.name,
                        command=command,
                        stderr=True,
                        stdin=False,
                        stdout=False,
                        tty=False,
                        _preload_content=False,
                    )
                    resp.close()

**Comment by palnabarun** [comment]
Related to #1312 

/assign

**Comment by palnabarun** [comment]
/close

See https://github.com/kubernetes-client/python/issues/1312#issuecomment-731923549

Please feel free to reopen if you face this issue again.
