### ISSUE TITLE
git describe or git describe --tags do not give the correct version

### ISSUE THREAD

**Issue by DreamingRaven** [kubernetes-client/python#1315]
**Link to the issue (please include a link to the specific documentation or example)**:
The version of the codebase tags and releases are 12.0.1 (currently)
https://github.com/kubernetes-client/python/tags

**Description of the issue (please include outputs or screenshots if possible)**:
However there is not associated annotated tag or lightweight tag to match this for packaging:
```
> git clone ssh://git@github.com/kubernetes-client/python
  Cloning into 'python'...
  remote: Enumerating objects: 6, done.
  remote: Counting objects: 100% (6/6), done.
  remote: Compressing objects: 100% (6/6), done.
  remote: Total 61775 (delta 0), reused 2 (delta 0), pack-reused 61769
  Receiving objects: 100% (61775/61775), 16.52 MiB | 3.59 MiB/s, done.
  Resolving deltas: 100% (59651/59651), done.
> cd python
> ls
  CHANGELOG.md        CONTRIBUTING.md  doc/       kubernetes/  MANIFEST.in  README.md         scripts/           
  setup.cfg  test-requirements.txt
  code-of-conduct.md  devel/           examples/  LICENSE      OWNERS       requirements.txt  SECURITY_CONTACTS  
  setup.py   tox.ini
> git describe
  fatal: No annotated tags can describe '140af57f9c15d154f85be3fd0f22b34c6516db2a'.
  However, there were unannotated tags: try --tags.
> git describe --tags
  v0.0.0-travis-experiment2-93-g140af57f


> git for-each-ref refs/tags
  2ed00a993b58275937efe43dd323092f136644e6 commit	refs/tags/12.0.0a1
  f85a06aed9f3c0674590dd2d3e5364b4c3640bc2 commit	refs/tags/4.0.0b1
  a141eab05d163010cc225a3b347bad2ec90e5b42 commit	refs/tags/5.0.0b1
  39f833c20d53fa1d37e808d45661a4172824740b commit	refs/tags/6.0.0
  73afbbcbe3fd61e35de861b283f97ed035d1f6b2 commit	refs/tags/6.0.0b1
  f96f29b4f063eaaf0d6c863e27f266b8f3fd4d77 commit	refs/tags/v0.0.0-travis-experiment
  6b560a4f3140a4fc0e8dc2d169c0952d7352cffd commit	refs/tags/v0.0.0-travis-experiment2
```
Is this expected? that no annotated tags exist and that what lightweight tags exist the latest is v0.0.0-travis-experiment2 given by `git describe` and `git describe --tags` respectively. 

Would it be possible to create an annotated tag for the latest 12.0.1 release?

**Comment by palnabarun** [comment]
@DreamingRaven -- `git describe [--tags]` tries to find the most recent tag reachable from the current commit. If you are running this on `master`, it will not return the correct tag since the tags that we push are on release branches (`release-*`) such as `release-12.0`.

```
➜  python git:(master) ✗ git describe --tags 
v0.0.0-travis-experiment2-105-gb79ad683
➜  python git:(master) ✗ git checkout release-12.0
Switched to branch 'release-12.0'
➜  python git:(release-12.0) ✗ git describe --tags
v12.0.1
```

Depending on your packaging requirements, you should checkout the specific release branch and then run `git describe --tags`.

> Would it be possible to create an annotated tag for the latest 12.0.1 release?

We can annotated tags, but that will still be on the release branches.

**Comment by DreamingRaven** [comment]
@palnabarun 
Thanks for getting back to me on this.
I checked and indeed as you said the 12.0.1 branch has a tag for 12.0.1.

However is there any other way to pull the version number automatically, as this would require I know the version number (to swap to the correct branch) before trying to get the version number from that branch. I would be able to sort the release-* branches but there are other higher numbered releases included (all the way up to 19), so I would have to swap to each branch, try git describe --tags on every branch until I got a hit from highest to lowest numbered.

Is there no way to find the current version number associated with master, even if that be far ahead of releases, since I am making a VCS package anyway, and I would rather not use revisions if I absolutely can avoid it.

Also as a side note and out of curiosity why is this repository called python? Would it not be better to call it python-kubernetes-client?

Cheers and thanks again for spending the time to answer my questions

**Comment by roycaihw** [comment]
Could you get all the tags using `git tag`, and pick the latest stable release from the list?

**Comment by DreamingRaven** [comment]
Hey @roycaihw Yes that does work lets say by using the invocation:
```
git tag --sort=committerdate | tail -1
```
outputs:
```
v12.0.1
```
thus avoiding the need to know the latest version number thank you for reminding me about that.

However @roycaihw if you had to describe the version of the master branch what would it be? How far ahead is the master branch compared to this release/ is it more closely related to another release that is staging for instance, or is it indeed a staging version of a different release.

The reason I ask is if I create a VCS package with just the version number given by git tag the version will be based off of that release even if they are unrelated to the release, and little other information will be included. Would this be safe to do in the repositories current style of development (not condescending a genuine query would it be safe to do this)?

To give a more concrete example if we take the github git mirror, github.com/git/git the latest release as of today is v2.29.2 if you git clone it and run (sed is just for formatting and style):
```
git describe --long | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
```
outputs:
```
v2.29.2.r366.gb291b0a628
```
telling us the version master is associated to v2.29.2 the revision number into that version r366 and the short commit identifier gb291b0a628, so we know exactly what version we are installing if we were to create a VCS package, without ambiguity. This is of course removing the added complexity of commiterdate vs taggerdate in the sorting of the tags with the git tag approach.

I think for now I will have to go with revision number only to properly describe the version of any VCS package for this repository
```
printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
```
outputs (on master):
```
r809.140af57f
```
to get most of the information I need. If the master branch is always related to the latest release I can append this information to the version number to get all the information required. But I am not entirely certain how releases occur for this repository as it seems strange.
