### ISSUE TITLE
list_pod_for_all_namespaces method causing UnicodeDecodeError

### ISSUE THREAD

**Issue by kbfu** [kubernetes-client/python#1325]
**What happened (please include outputs or screenshots)**:
I got a response from Kubernetes which includes some Chineses characters from commit message(using three bytes per character), if the response content length is over 4096, the response will be split to at lease two parts. 
It happens when the Chinese character is on the end of first part response. UnicodeDecodeError will be thrown because of the incomplete bytes.
**What you expected to happen**:
Response should be joined without any error.
**How to reproduce it (as minimally and precisely as possible)**:
You need a huge response, and put some Chinese characters in it, and maybe you will see this error.
**Anything else we need to know?**:
After some dig in, I found this error was caused by the iter_resp_lines function in watch.py. Remove the decode block and change seg and prev variables to bytes type will do just fine.
```python
def iter_resp_lines(resp):
    prev = b""
    for seg in resp.read_chunked(decode_content=False):
        seg = prev + seg
        lines = seg.split(b"\n")
        if not seg.endswith(b"\n"):
            prev = lines[-1]
            lines = lines[:-1]
        else:
            prev = b""
        for line in lines:
            if line:
                yield line
```

And for non-watch type logic, update the code in line 182 to convert the line from bytes to str.

```python
yield line.decode('utf8')
```

**Environment**:
- Kubernetes version (`kubectl version`): 1.18.6
- OS (e.g., MacOS 10.13.6): 11.0.1
- Python version (`python --version`) 3.8.2
- Python client version (`pip list | grep kubernetes`) 12.0.1

**Comment by roycaihw** [comment]
Could you share the function calls you made using this client?

**Comment by roycaihw** [comment]
Discussed in the bi-weekly meeting this morning. Potentially we can do one of: 

- keep track of the last one or two bytes in `seg`, fallback and defer those bytes to the next `seg` when we fail to decode
- add a optional argument to disable decode
- read everything from `read_chunked` first, only decode at the end

cc @palnabarun 

I don't remember why we had the decode. Probably worth looking into the historic reason (other than parsing the `\n`)

**Comment by kbfu** [comment]
> Could you share the function calls you made using this client?

We are using this function in stream method to watch the pods from Kubernetes just like below
```python
for event in w.stream(v1.list_pod_for_all_namespaces, _request_timeout=0):

    metadata = event['object'].metadata
    annotations = metadata.annotations
    spec = event['object'].spec

    if annotations and 'field.cattle.io/ports' in annotations:
        ports_dict = json.loads(annotations['field.cattle.io/ports'])
        print(ports_dict)
    else:
        ports = False
```
So I updated the code from the package, make it decode the bytes after it received the entire bytes from chunked data, then everything works fine.
