### ISSUE TITLE
Getting error while connecting eks cluster from lambda

### ISSUE THREAD

**Issue by btrx-rkazi** [kubernetes-client/python#1326]
**What happened (please include outputs or screenshots)**:
Response:
{
  "errorMessage": "HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /apis/batch/v1/namespaces/default/jobs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31cdfee070>: Failed to establish a new connection: [Errno 111] Connection refused'))",
  "errorType": "MaxRetryError",
  "stackTrace": [
    "  File \"/var/task/main.py\", line 40, in handler\n    resp = k8s_apps_v1.create_namespaced_job(\n",
    "  File \"/opt/python/kubernetes/client/api/batch_v1_api.py\", line 66, in create_namespaced_job\n    return self.create_namespaced_job_with_http_info(namespace, body, **kwargs)  # noqa: E501\n",
    "  File \"/opt/python/kubernetes/client/api/batch_v1_api.py\", line 161, in create_namespaced_job_with_http_info\n    return self.api_client.call_api(\n",
    "  File \"/opt/python/kubernetes/client/api_client.py\", line 348, in call_api\n    return self.__call_api(resource_path, method,\n",
    "  File \"/opt/python/kubernetes/client/api_client.py\", line 180, in __call_api\n    response_data = self.request(\n",
    "  File \"/opt/python/kubernetes/client/api_client.py\", line 391, in request\n    return self.rest_client.POST(url,\n",
    "  File \"/opt/python/kubernetes/client/rest.py\", line 274, in POST\n    return self.request(\"POST\", url,\n",
    "  File \"/opt/python/kubernetes/client/rest.py\", line 167, in request\n    r = self.pool_manager.request(\n",
    "  File \"/opt/python/urllib3/request.py\", line 79, in request\n    return self.request_encode_body(\n",
    "  File \"/opt/python/urllib3/request.py\", line 171, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n",
    "  File \"/opt/python/urllib3/poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n",
    "  File \"/opt/python/urllib3/connectionpool.py\", line 754, in urlopen\n    return self.urlopen(\n",
    "  File \"/opt/python/urllib3/connectionpool.py\", line 754, in urlopen\n    return self.urlopen(\n",
    "  File \"/opt/python/urllib3/connectionpool.py\", line 754, in urlopen\n    return self.urlopen(\n",
    "  File \"/opt/python/urllib3/connectionpool.py\", line 726, in urlopen\n    retries = retries.increment(\n",
    "  File \"/opt/python/urllib3/util/retry.py\", line 446, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"
  ]
}

Request ID:
"67f890a4-0bfc-4b45-8f71-fc1d0905bb4d"

Function logs:
START RequestId: 67f890a4-0bfc-4b45-8f71-fc1d0905bb4d Version: $LATEST
configure
api call
[WARNING]	2020-11-20T16:58:15.172Z	67f890a4-0bfc-4b45-8f71-fc1d0905bb4d	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31cdfbbc10>: Failed to establish a new connection: [Errno 111] Connection refused')': /apis/batch/v1/namespaces/default/jobs
[WARNING]	2020-11-20T16:58:15.172Z	67f890a4-0bfc-4b45-8f71-fc1d0905bb4d	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31cdfbbd30>: Failed to establish a new connection: [Errno 111] Connection refused')': /apis/batch/v1/namespaces/default/jobs
[WARNING]	2020-11-20T16:58:15.173Z	67f890a4-0bfc-4b45-8f71-fc1d0905bb4d	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31cdfbbd60>: Failed to establish a new connection: [Errno 111] Connection refused')': /apis/batch/v1/namespaces/default/jobs
[ERROR] MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /apis/batch/v1/namespaces/default/jobs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31cdfee070>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/var/task/main.py", line 40, in handler
    resp = k8s_apps_v1.create_namespaced_job(
  File "/opt/python/kubernetes/client/api/batch_v1_api.py", line 66, in create_namespaced_job
    return self.create_namespaced_job_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/opt/python/kubernetes/client/api/batch_v1_api.py", line 161, in create_namespaced_job_with_http_info
    return self.api_client.call_api(
  File "/opt/python/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/python/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/opt/python/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/opt/python/kubernetes/client/rest.py", line 274, in POST
    return self.request("POST", url,
  File "/opt/python/kubernetes/client/rest.py", line 167, in request
    r = self.pool_manager.request(
  File "/opt/python/urllib3/request.py", line 79, in request
    return self.request_encode_body(
  File "/opt/python/urllib3/request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/opt/python/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/python/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/opt/python/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/opt/python/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))END RequestId: 67f890a4-0bfc-4b45-8f71-fc1d0905bb4d
REPORT RequestId: 67f890a4-0bfc-4b45-8f71-fc1d0905bb4d	Duration: 61.55 ms	Billed Duration: 100 ms	Memory Size: 1408 MB	Max Memory Used: 143 MB	Init Duration: 2650.19 ms
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Below is the code i am trying to run to execute a job on EKS cluster.
main.py
=====
import os.path
import yaml
import boto3
from kubernetes import client, config
from auth import EKSAuth
from os import path

# Configure your cluster name and region here
KUBE_FILEPATH = '/tmp/rconfig'
CLUSTER_NAME = 'pre-imputation'
REGION = 'us-east-1'

# We assume that when the Lambda container is reused, a kubeconfig file exists.
# If it does not exist, it creates the file.
with open("./rconfig", 'r') as c:
        job = yaml.safe_load(c)
with open(KUBE_FILEPATH, 'w') as outfile:
        yaml.dump(job, outfile, default_flow_style=False)

def handler(event, context):
#def handler():
    # Get Token
    eks = EKSAuth(CLUSTER_NAME)
    token = eks.get_token()
    # Configure
    print("configure")
    config.load_kube_config(KUBE_FILEPATH)
    configuration = client.Configuration()
    configuration.api_key['authorization'] = token
    configuration.api_key_prefix['authorization'] = 'Bearer'
    # API
    print("api call")
    api = client.ApiClient(configuration)
   # v1 = client.CoreV1Api(api)

    with open("./job.yaml",'r') as f:
        job = yaml.safe_load(f)
        k8s_apps_v1 = client.BatchV1Api(api)
        resp = k8s_apps_v1.create_namespaced_job(
            body=job,namespace="default")
        print("job created. name='%s'" % resp.metadata.name)

#handler()

Auth.py
=====
import base64
import boto3
import string
import random
import re
from botocore.signers import RequestSigner

class EKSAuth(object):

    METHOD = 'GET'
    EXPIRES = 60
    EKS_HEADER = 'x-k8s-aws-id'
    EKS_PREFIX = 'k8s-aws-v1.'
    STS_URL = 'sts.amazonaws.com'
    STS_ACTION = 'Action=GetCallerIdentity&Version=2011-06-15'

    def __init__(self, cluster_id, region='us-east-1'):
        self.cluster_id = cluster_id
        self.region = region

    def get_token(self):
        """
        Return bearer token
        """

        session = boto3.session.Session()

        # Get ServiceID required by class RequestSigner

        client = session.client('sts', region_name=self.region)
        service_id = client.meta.service_model.service_id

        signer = RequestSigner(
            service_id,
            session.region_name,
            'sts',
            'v4',
            session.get_credentials(),
            session.events,
            )

        params = {
            'method': 'GET',
            'url': 'https://sts.{}.amazonaws.com/?Action=GetCallerIdentity&Version=2011-06-15'.format(self.region),
            'body': {},
            'headers': {'x-k8s-aws-id': self.cluster_id},
            'context': {},
            }

        signed_url = signer.generate_presigned_url(params,
                region_name=session.region_name,
                expires_in=self.EXPIRES, operation_name='')

        base64_url = base64.urlsafe_b64encode(signed_url.encode('utf-8'
                )).decode('utf-8')

        return 'k8s-aws-v1.' + re.sub(r'=*', '', base64_url)

rconfig
======
Kind: config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <<removed data>>
    server: <<Removed data>>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
users:
- name: aws
  user:
    name: lambda

**Anything else we need to know?**:
I am running this using lambda. 
**Environment**:
- Kubernetes version (`kubectl version`): 1.18
- OS (e.g., MacOS 10.13.6): AmazonLinux2
- Python version (`python --version`) 3.8
- Python client version (`pip list | grep kubernetes`)12.0.1

**Comment by palnabarun** [comment]
Hi @btrx-rkazi -- can you please fill the other fields in the bug report? With just the stack trace, it is really difficult to infer what you are trying to achieve with the client.

**Comment by btrx-rkazi** [comment]
> Hi @btrx-rkazi -- can you please fill the other fields in the bug report? With just the stack trace, it is really difficult to infer what you are trying to achieve with the client.

I have done it. could you please check

**Comment by phracek** [comment]
Similar issue here: #1361

**Comment by thallesdaniell** [comment]
I had a constant 403 and 401 error using this authentication script. I looked for others and found this https://github.com/peak-ai/eks-token and it worked really well for me.
