### ISSUE TITLE
kubernetes/config/incluster_config.py", line 73, in _load_config raise ConfigException("Service token file does not exists.")

### ISSUE THREAD

**Issue by btrx-rkazi** [kubernetes-client/python#1331]
**What happened (please include outputs or screenshots)**:
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    handler()
  File "main.py", line 33, in handler
    config.load_incluster_config(KUBE_FILEPATH)
  File "/home/ec2-user/eks-lambda/lib/python3.8/site-packages/kubernetes/config/incluster_config.py", line 118, in load_incluster_config
    InClusterConfigLoader(
  File "/home/ec2-user/eks-lambda/lib/python3.8/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/home/ec2-user/eks-lambda/lib/python3.8/site-packages/kubernetes/config/incluster_config.py", line 73, in _load_config
    raise ConfigException("Service token file does not exists.")
kubernetes.config.config_exception.ConfigException: Service token file does not exists.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
main.py
=====
import os.path
import yaml
import boto3
from kubernetes import client, config
from auth import EKSAuth
from os import path

os.environ['KUBERNETES_SERVICE_HOST'] = 'kubernetes'
os.environ['KUBERNETES_SERVICE_PORT'] = '443'
#config.load_incluster_config()
#os.environ['KUBERNETES_SERVICE_HOST'] = os.environ.get('KUBERNETES_SERVICE_HOST')
#os.environ['KUBERNETES_SERVICE_PORT'] = os.environ.get('KUBERNETES_SERVICE_PORT')

Configure your cluster name and region here
KUBE_FILEPATH = '/tmp/config'
CLUSTER_NAME = 'pre-imputation'
REGION = 'us-east-1'

We assume that when the Lambda container is reused, a kubeconfig file exists.
If it does not exist, it creates the file.
with open("./config", 'r') as c:
job = yaml.safe_load(c)
with open(KUBE_FILEPATH, 'w') as outfile:
yaml.dump(job, outfile, default_flow_style=False)

#def handler(event, context):
def handler():
# Get Token
eks = EKSAuth(CLUSTER_NAME)
token = eks.get_token()
# Configure
print("configure")
config.load_incluster_config(KUBE_FILEPATH)

config.load_kube_config(KUBE_FILEPATH)
configuration = client.Configuration()
configuration.api_key['authorization'] = token
configuration.api_key_prefix['authorization'] = 'Bearer'
# API
print("api call")
api = client.ApiClient(configuration)
v1 = client.CoreV1Api(api)
with open("./job.yaml",'r') as f:
    job = yaml.safe_load(f)
    k8s_apps_v1 = client.BatchV1Api(api)
    resp = k8s_apps_v1.create_namespaced_job(
        body=job,namespace="default")
    print("job created. name='%s'" % resp.metadata.name)
handler()

Auth.py
====
import base64
import boto3
import string
import random
import re
from botocore.signers import RequestSigner

class EKSAuth(object):

METHOD = 'GET'
EXPIRES = 60
EKS_HEADER = 'x-k8s-aws-id'
EKS_PREFIX = 'k8s-aws-v1.'
STS_URL = 'sts.amazonaws.com'
STS_ACTION = 'Action=GetCallerIdentity&Version=2011-06-15'

def __init__(self, cluster_id, region='us-east-1'):
    self.cluster_id = cluster_id
    self.region = region

def get_token(self):
    """
    Return bearer token
    """

    session = boto3.session.Session()

    # Get ServiceID required by class RequestSigner

    client = session.client('sts', region_name=self.region)
    service_id = client.meta.service_model.service_id

    signer = RequestSigner(
        service_id,
        session.region_name,
        'sts',
        'v4',
        session.get_credentials(),
        session.events,
        )

    params = {
        'method': 'GET',
        'url': 'https://sts.{}.amazonaws.com/?Action=GetCallerIdentity&Version=2011-06-15'.format(self.region),
        'body': {},
        'headers': {'x-k8s-aws-id': self.cluster_id},
        'context': {},
        }

    signed_url = signer.generate_presigned_url(params,
            region_name=session.region_name,
            expires_in=self.EXPIRES, operation_name='')

    base64_url = base64.urlsafe_b64encode(signed_url.encode('utf-8'
            )).decode('utf-8')

    return 'k8s-aws-v1.' + re.sub(r'=*', '', base64_url)
rconfig
Kind: config
apiVersion: v1
clusters:

cluster:
certificate-authority-data: <>
server: <>
name: kubernetes
contexts:
context:
cluster: kubernetes
user: aws
name: aws
current-context: aws
users:
name: aws
user:
name: lambda
**Anything else we need to know?**:

**Environment**:
Kubernetes version (kubectl version): 1.18
OS (e.g., MacOS 10.13.6): AmazonLinux2
Python version (python --version) 3.8
Python client version (pip list | grep kubernetes)12.0.1

**Comment by roycaihw** [comment]
Is your application running inside a pod? The error means it cannot find the service token [file](https://github.com/kubernetes-client/python-base/blob/master/config/incluster_config.py#L24)

**Comment by renukamanavalan** [comment]
I have the same problem. Yes, I am trying to run the script inside container.

```
root@CO4AEAP000105BD:/# export KUBERNETES_SERVICE_HOST=localhost
root@CO4AEAP000105BD:/# export KUBERNETES_SERVICE_PORT=6443
root@CO4AEAP000105BD:/# python3
Python 3.9.1 (default, Feb  9 2021, 07:42:03) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kubernetes import client, config
>>> config.load_incluster_config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/incluster_config.py", line 118, in load_incluster_config
    InClusterConfigLoader(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/incluster_config.py", line 73, in _load_config
    raise ConfigException("Service token file does not exists.")
kubernetes.config.config_exception.ConfigException: Service token file does not exists.

```
How could I get around this ?

**Comment by renukamanavalan** [comment]
Resolved my problem

As I was running my pod inside the master
1) mounted /etc/kubernetes into the container 
2) export KUBECONFIG=/etc/kubernetes/admin.conf

Now I could use config.load_config itself.

```
root@CO4AEAP000105BD:/# python3
Python 3.9.1 (default, Feb  9 2021, 07:42:03) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kubernetes import client, config
>>> config.load_kube_config()
```
