### ISSUE TITLE
Documentation: Documentation required for Python api client

### ISSUE THREAD

**Issue by amitkrishna** [kubernetes-client/python#1334]
Documentation required  for easy api navigation .

**Comment by migueleliasweb** [comment]
Some markdowns, apparently, cannot be visualised in GitHub anymore due to their size.

<img width="1292" alt="Screen Shot 2020-12-10 at 10 59 09 am" src="https://user-images.githubusercontent.com/1608212/101703346-c0fab400-3ad6-11eb-8dba-4fdf2b69d896.png">

**Comment by amitkrishna** [comment]
Hey @migueleliasweb  can we put all apis in a gitbook so that it will be easier for anyone in the community to navigate through apis?
