### ISSUE TITLE
Problem with load_kube_config()

### ISSUE THREAD

**Issue by spestua** [kubernetes-client/python#1335]
Hi, everyone!

I have a very strange problem with using my _kubeconf_.
When I try to execute the example code from README, but at the stage `config.load_kube_config()` an error appears:

> ---------------------------------------------------------------------------
> Error                                     Traceback (most recent call last)
> <ipython-input-75-25891e2b5a6d> in <module>
>      63 
>      64 apply_oid_token_monkey_patch()
> ---> 65 config.load_kube_config()
>      66 
>      67 # v1 = client.CoreV1Api()
> 
> ~/miniconda3/lib/python3.8/site-packages/kubernetes/config/kube_config.py in load_kube_config(config_file, context, client_configuration, persist_config)
>     796     if client_configuration is None:
>     797         config = type.__call__(Configuration)
> --> 798         loader.load_and_set(config)
>     799         Configuration.set_default(config)
>     800     else:
> 
> ~/miniconda3/lib/python3.8/site-packages/kubernetes/config/kube_config.py in load_and_set(self, client_configuration)
>     574 
>     575     def load_and_set(self, client_configuration):
> --> 576         self._load_authentication()
>     577         self._load_cluster_info()
>     578         self._set_config(client_configuration)
> 
> ~/miniconda3/lib/python3.8/site-packages/kubernetes/config/kube_config.py in _load_authentication(self)
>     278         if not self._user:
>     279             return
> --> 280         if self._load_auth_provider_token():
>     281             return
>     282         if self._load_user_token():
> 
> ~/miniconda3/lib/python3.8/site-packages/kubernetes/config/kube_config.py in _load_auth_provider_token(self)
>     297             return self._load_azure_token(provider)
>     298         if provider['name'] == 'oidc':
> --> 299             return self._load_oid_token(provider)
>     300 
>     301     def _azure_is_expired(self, provider):
> 
> <ipython-input-75-25891e2b5a6d> in load_oid_token_trace(self, provider)
>      39         if PY3:
>      40             jwt_attributes = json.loads(
> ---> 41                 base64.b64decode(parts[1] + padding).decode('utf-8')
>      42             )
>      43         else:
> 
> ~/miniconda3/lib/python3.8/base64.py in b64decode(s, altchars, validate)
>      85     if validate and not re.fullmatch(b'[A-Za-z0-9+/]*={0,2}', s):
>      86         raise binascii.Error('Non-base64 digit found')
> ---> 87     return binascii.a2b_base64(s)
>      88 
>      89 
> Error: Incorrect padding 

I changed one line in source a little bit:
FROM
https://github.com/kubernetes-client/python-base/blob/2da2b981ca806b25487ad92d01a2164815c18517/config/kube_config.py#L391
TO
```base64.b64decode(parts[1].replace('-', '+') + padding).decode('utf-8') ```

And there were no more errors. Why? I can fix it in my configuration file, but it will break down here:
https://github.com/kubernetes-client/python-base/blob/2da2b981ca806b25487ad92d01a2164815c18517/config/kube_config.py#L374

You can see this problem in the following example:

```python
import base64

part = 'eyJhY3IiOiIxIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiLQnNCw0LvQutC-0LIiLCJncm91cHMiOltdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJrZW1hbGtvdiIsImZhbWlseV9uYW1lIjoi0JzQsNC70LrQvtCyIiwiZW1haWwiOiJrZW1hbGtvdkBiZWVsaW5lLnJ1In0'
padding = (4 - len(part) % 4) * '=' # padding = 1*'='
print(base64.b64decode(part+'=').decode('utf-8')) # > Error: Incorrect padding
print(base64.b64decode(part+'==').decode('utf-8')) # > UnicodeDecodeError
print(base64.b64decode(part.replace('-', '+')+'=').decode('utf-8')) # Work fine
print(base64.b64decode(part.replace('-', '+')+'==').decode('utf-8')) # Work fine
```

> Python version: 3.8.3
> Kubernetes-client version: 12.0.1
> MacOS 10.15.7

**Comment by JiffsMaverick** [comment]
I have this problem too. kubernetes-client/python-base#220 solved this problem, but it hasn't merged yet.

**Comment by JiffsMaverick** [comment]
This problem is still relevant. PR kubernetes-client/python-base#220 can solve this problem. Please, reopen.

**Comment by iicky** [comment]
I'm also having this issue - any merge for the PR yet?
