### ISSUE TITLE
Volume snapshot  client is missing

### ISSUE THREAD

**Issue by beniloew** [kubernetes-client/python#1339]
**What happened (please include outputs or screenshots)**:
When trying to create a volume snapshot, i get the following error:
Module 'kubernetes.client' has no attribute 'SnapshotStorageV1beta1Api' 

**What you expected to happen**:
Snapshot created

**How to reproduce it (as minimally and precisely as possible)**:
Create from yaml a generic volume snapshot. The yaml applied with kubectl created a snapshot

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):1.19.1
- OS (e.g., MacOS 10.13.6):ubuntu 18.04
- Python version (`python --version`) 3.8.5
- Python client version (`pip list | grep kubernetes`) 17.14.0a1

**Comment by roycaihw** [comment]
Based on https://kubernetes.io/docs/concepts/storage/volume-snapshots/#introduction, volume snapshot APIs are CRDs. You can use the dynamic client ([example](https://github.com/kubernetes-client/python-base/blob/master/dynamic/test_client.py)) to access them.
