### ISSUE TITLE
Is it safe to assume that passing the empty string as a namespace is equivalent to list_pod_for_all_namespaces?

### ISSUE THREAD

**Issue by hq6** [kubernetes-client/python#1349]
Consider the following two blocks of code:

Sample 1
```
        core_kube_client = client.CoreV1Api(api_client=api_client)
        podObjects = core_kube_client.list_namespaced_pod('')
```

Sample 2
```
        core_kube_client = client.CoreV1Api(api_client=api_client)
        podObjects = core_kube_client.list_pod_for_all_namespaces()
```

When I run these two pieces of code in a K8 setup without namespaces, they return identical results.

Is this behavior (empty string namespace == all namespaces) I can rely on, or should my code always branch on whether a context contains a namespace and use the two different calls for the case with namespace and without?

**Comment by yliaog** [comment]
it's better to explicitly use list_pod_for_all_namespaces for 'all namespaces' case, the meaning of empty namespace may change, it  may mean default namespace, for example.
