### ISSUE TITLE
Add since_time parameter to read_namespaced_pod_log

### ISSUE THREAD

**Issue by neelsomani** [kubernetes-client/python#1351]
**What happened (please include outputs or screenshots)**:

The docstring makes reference to both the `sinceSeconds` and `sinceTime` parameters which exist in the CLI, but I see that only the `since_seconds` kwarg is accepted by the Python client

**What you expected to happen**:

I expected the `since_time` kwarg to be accepted

**How to reproduce it (as minimally and precisely as possible)**:

Pass `since_time` attribute to the CoreV1Api method `read_namespaced_pod_log`

**Anything else we need to know?**:

n/a

**Environment**:
- Kubernetes version (`kubectl version`): v1.19.0
- OS (e.g., MacOS 10.13.6): Linux
- Python version (`python --version`) 3.6.10
- Python client version (`pip list | grep kubernetes`) 12.0.0

**Comment by neelsomani** [comment]
Would be happy to add this parameter myself, just not sure how - I saw the CoreV1Api code is generated so I figure I'm not supposed to edit that directly

**Comment by pigletfly** [comment]
actually, `it's supported already, read_namespaced_pod_log(self, name,namespace, **kwargs)`, just pass since_seconds in kwargs.

**Comment by neelsomani** [comment]
Yeah I'm currently using since_seconds, this issue is about since time though

**Comment by yliaog** [comment]
both since_time and since_seconds were added years ago, https://github.com/kubernetes/kubernetes/blame/c5cc25d1cb075f84756db9bffecd3fafe12c5fab/pkg/apis/core/types.go#L4427

**Comment by neelsomani** [comment]
Interesting, it didn't seem to work for me with the Python client but I ended up not needing this feature anyway. I'm fine with closing the issue.

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/blob/083290d996cd0707bfb9810eb17cc7d5652863b8/staging/src/k8s.io/api/core/v1/types_swagger_doc_generated.go#L1558

has both since_time and since_seconds

**Comment by neelsomani** [comment]
Yeah totally fine with closing it but just wondering, why is there no `since_time` parameter mentioned in the generated code here: https://raw.githubusercontent.com/kubernetes-client/python/master/kubernetes/client/api/core_v1_api.py

**Comment by yliaog** [comment]
https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json is the openapi spec used for generating python client in this repo. sinceseconds is present there, but sincetime is not.

**Comment by neelsomani** [comment]
I see now, so would this PR be sufficient? https://github.com/kubernetes/kubernetes/pull/98907
Do I need to do anything else?

**Comment by vdwees** [comment]
possibly a bug, since it is referenced in the description of since_seconds, but the field itself does not exist.
        {
          "description": "A relative time in seconds before the current time from which to show logs. If this value precedes the time a pod was started, only logs since the pod start will be returned. If this value is in the future, no logs will be returned. Only one of **sinceSeconds** or **sinceTime** may be specified.",
          "in": "query",
          "name": "**sinceSeconds**",
          "type": "integer",
          "uniqueItems": true
        }

**Comment by ZW007** [comment]
@yliaog @vdwees @neelsomani @pigletfly May I ask how to use this sinceSeconds? I could not understand what does it mean by `A relative time in seconds before the current time from which to show logs. If this value precedes the time a pod was started, only logs since the pod start will be returned. If this value is in the future, no logs will be returned` For example, i want to log from the beginning, (since_seconds = 0?), then make a stop (enable logs timestamp, record this timestamp),  then stream log from where I stopped. Any suggestion?
