### ISSUE TITLE
Can someone please let me know how to add multiple ranges for spec loadBalancerSourceRanges 

### ISSUE THREAD

**Issue by avinashsavaliya** [kubernetes-client/python#1352]

**Comment by roycaihw** [comment]
Since `load_balancer_source_ranges` is a `list[str]`. I think you can use: 
```
>>> from kubernetes import client
>>> spec=client.V1ServiceSpec(load_balancer_source_ranges=["a","b"])
>>> print(spec)
{'cluster_ip': None,
 'external_i_ps': None,
 'external_name': None,
 'external_traffic_policy': None,
 'health_check_node_port': None,
 'ip_family': None,
 'load_balancer_ip': None,
 'load_balancer_source_ranges': ['a', 'b'],
 'ports': None,
 'publish_not_ready_addresses': None,
 'selector': None,
 'session_affinity': None,
 'session_affinity_config': None,
 'topology_keys': None,
 'type': None}
```

/close

**Comment by avinashsavaliya** [comment]
> Since `load_balancer_source_ranges` is a `list[str]`. I think you can use:
> 
> ```
> >>> from kubernetes import client
> >>> spec=client.V1ServiceSpec(load_balancer_source_ranges=["a","b"])
> >>> print(spec)
> {'cluster_ip': None,
>  'external_i_ps': None,
>  'external_name': None,
>  'external_traffic_policy': None,
>  'health_check_node_port': None,
>  'ip_family': None,
>  'load_balancer_ip': None,
>  'load_balancer_source_ranges': ['a', 'b'],
>  'ports': None,
>  'publish_not_ready_addresses': None,
>  'selector': None,
>  'session_affinity': None,
>  'session_affinity_config': None,
>  'topology_keys': None,
>  'type': None}
> ```
> 
> /close

Thank you !
