### ISSUE TITLE
read_namespaced_pod_logs is breaking JSON output

### ISSUE THREAD

**Issue by fredleger** [kubernetes-client/python#1354]
**What happened (please include outputs or screenshots)**:

Try to get logs from a container logging in JSON (which is cool)
And later to rehydrate some props of this logs into a python object

Seems that Core.read_namespaced_pod_logs() is not handling quoting properly

Example:

NB: The test data is comming from https://jsonplaceholder.typicode.com/users/1
and the output can be easily reproduced in a container by running `wget -q -O - https://jsonplaceholder.typicode.com/users/1`

***WORKING***
```sh
$ wget -q -O - https://jsonplaceholder.typicode.com/users/1 | jq
{
  "id": 1,
  "name": "Leanne Graham",
  "username": "Bret",
  "email": "Sincere@april.biz",
  "address": {
    "street": "Kulas Light",
    "suite": "Apt. 556",
    "city": "Gwenborough",
    "zipcode": "92998-3874",
    "geo": {
      "lat": "-37.3159",
      "lng": "81.1496"
    }
  },
  "phone": "1-770-736-8031 x56442",
  "website": "hildegard.org",
  "company": {
    "name": "Romaguera-Crona",
    "catchPhrase": "Multi-layered client-server neural-net",
    "bs": "harness real-time e-markets"
  }
```

NB: Notice de " chars

***WITH KUBECTL - WORKING***

```sh
k logs hre-xxxxxxxx-2021-0115-xxxxxxxxx006-kq2j6 | jq                                                                              frederic@mistral
{
  "id": 1,
  "name": "Leanne Graham",
  "username": "Bret",
  "email": "Sincere@april.biz",
  "address": {
    "street": "Kulas Light",
    "suite": "Apt. 556",
    "city": "Gwenborough",
    "zipcode": "92998-3874",
    "geo": {
      "lat": "-37.3159",
      "lng": "81.1496"
    }
  },
  "phone": "1-770-736-8031 x56442",
  "website": "hildegard.org",
  "company": {
    "name": "Romaguera-Crona",
    "catchPhrase": "Multi-layered client-server neural-net",
    "bs": "harness real-time e-markets"
  }
}
```

***NOT WORKING***

```sh
python3 myscript.py

{"asctime": "2021-01-15 17:01:50,424", "levelname": "INFO", "processName": "MainProcess", "message": "Sucessfull pod was: hre-xxxxxxxx-2021-0115-xxxxxxxxx006-kq2j6"}
{"asctime": "2021-01-15 17:01:50,770", "levelname": "INFO", "processName": "MainProcess", "message": "Sucessfull pod output: {'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}"}
{"asctime": "2021-01-15 17:01:50,770", "levelname": "WARNING", "processName": "MainProcess", "message": "A <class 'json.decoder.JSONDecodeError'> exception occured when creating hre job: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)"}
```

NB: Note the ' chars instead

**What you expected to happen**:

I would not except any differences going through kubectl and python kubernetes/client

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): 
Client Version: v1.19.2
Server Version: v1.19.3+k3s2

- OS (e.g., MacOS 10.13.6): Macos Catalina
- Python version (`python --version`)
Python 3.8.7
- Python client version (`pip list | grep kubernetes`)
kubernetes         12.0.1

**Comment by fabianvf** [comment]
@fredleger I think this is just the way that python outputs dictionaries. It looks like the JSON output has been loaded into a Python `dict`, which is then output, and the `__repr__` for `dict` outputs single quotes. I don't think there's anything that this library should do to affect that. If you wanted to keep the initial formatting, you should output the raw json string you receive instead of the loaded Python `dict`

Example:
```python
> x = {"a": "1", "b": 2}
> repr(x)
"{'a': '1', 'b': 2}"
> str(x)
"{'a': '1', 'b': 2}"
> print(x)
{'a': '1', 'b': 2}
```

**Comment by fredleger** [comment]
Hi Fabian.

Didn't get that. Thanks for pointing that out.

/close

**Comment by pkit** [comment]
@fabianvf I'm not sure I follow:
How it's not a bug in this library?

I have a pod that runs `echo '{"a":1}'`
```
v1 = client.CoreV1Api()
logs = v1.read_namespaced_pod_log(name=pod_name, namespace=pod_namespace, pretty=False)
print(f"Pod log output: {logs} {type(logs)}")
```
The output:
```
Pod log output: {'a': 1} <class 'str'>
```
Looks like a critical bug to me.

Okay, running `echo 'aaa {"a":1}'` produces correct output: `aaa {"a":1}`
So it is a critical bug.

**Comment by pkit** [comment]
Okay, the proper workaround is:
```
v1 = client.CoreV1Api()
output = v1.read_namespaced_pod_log(name=pod_name, namespace=pod_namespace, _preload_content=False)
logs = output.data.decode("utf-8")
print(f"Pod log output: {logs} {type(logs)}")
```
Produces:
```
Pod log output: {"a": 1} 
<class 'str'>
```
