### ISSUE TITLE
when creating namespaced job getting 'property' object has no attribute 'openapi_types'

### ISSUE THREAD

**Issue by hezise** [kubernetes-client/python#1358]
**What happened (please include outputs or screenshots)**:
AttributeError("'property' object has no attribute 'openapi_types'")
**What you expected to happen**:
creating the job 
**How to reproduce it (as minimally and precisely as possible)**:
attaching my script
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): 1.16.9
- OS (e.g., MacOS 10.13.6): Ubuntu 18.0.4
- Python version (`python --version`) 3.7.8
- Python client version (`pip list | grep kubernetes`) 12.0.1

`
[create_job.txt](https://github.com/kubernetes-client/python/files/5835370/create_job.txt)
`

**Comment by yliaog** [comment]
https://github.com/kubernetes-client/python/blob/b79ad6837b2f5326c7dad488a64eed7c3987e856/kubernetes/client/models/v1_job.py#L30

has openapi_types

**Comment by hezise** [comment]
@yliaog  I didn't understand your comment :(
