### ISSUE TITLE
Documenation is 'too big' to view as markdown on github

### ISSUE THREAD

**Issue by bdirito** [kubernetes-client/python#1362]
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#patch_namespaced_service

**Description of the issue (please include outputs or screenshots if possible)**:
In trying to view the official documentation for the python kubernetes client for patching a namespaced service:
Start at the main github page:
https://github.com/kubernetes-client/python
  -> click the "Generated client's README file" link
https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md
  -> click the "patch_namespaced_service" link
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#patch_namespaced_service
  -> renders as 
```
View raw
(Sorry about that, but we can’t show files that are this big right now.)
```

**Comment by ZhuozhaoLi** [comment]
I also encountered this problem when I tried to search the docs for some APIs.

**Comment by yliaog** [comment]
that message is from github, unless github could increase the file size limit, the warning message would be shown.

you may still click on 'View raw' to see the file.

**Comment by ZhuozhaoLi** [comment]
The problem is that it does not provide a way to view any useful docs for some APIs, e.g., `read_namespaced_pod_status`. If you have one, please let me know.

**Comment by yliaog** [comment]
i usually 'git clone' to local disk, and do search
