### ISSUE TITLE
python package created from the repo doesn't have the dependencies

### ISSUE THREAD

**Issue by sunchill06** [kubernetes-client/python#1364]
**What happened (please include outputs or screenshots)**:
I ran the installer (python setup.py install) and inside the dist directory, an .egg file is created i.e. kubernetes-12.0.0_snapshot-py2.7.egg

Now I need to ship this to a docker image and use it inside the container. I am installing this egg file using easy_install.
however, easy_install goes to pypi to install all the dependencies of this package, like oauthlib, google.auth, requests etc.

I expected that all the dependencies should already be part of kubernetes-12.0.0_snapshot-py2.7.egg package.

**What you expected to happen**:
Is it possible to make sure that kubernetes-12.0.0_snapshot-py2.7.egg contains all the dependencies inside requirements.txt? so that it doesn't go to internet/pypi while installing it using easy_install.

**How to reproduce it (as minimally and precisely as possible)**:
Install kubernetes-12.0.0_snapshot-py2.7.egg using easy_install.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): v1.18.9
- OS (e.g., MacOS 10.13.6): SUSE Linux Enterprise Server 15 SP1
- Python version (`python --version`) 2.7
- Python client version (`pip list | grep kubernetes`)
You are using pip version 10.0.1, however version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by sunchill06** [comment]
@roycaihw @NeolithEra @palnabarun , Please assist here, its a blocker for me. Any guidance here would help a lot.

**Comment by NeolithEra** [comment]
> @roycaihw @NeolithEra @palnabarun , Please assist here, its a blocker for me. Any guidance here would help a lot.

requirements.txt usually don't contain all the dependencies that the project needs, it contains only the direct dependencies. however easy_install installs dependencies according to the requests.txt. It is possible not to  use the Internet while installing it using easy_install if you have install these direct dependencies in site-packages(or copy these folders to site-packages ).You can get more information from http://peak.telecommunity.com/DevCenter/PythonEggs

**Comment by sunchill06** [comment]
@NeolithEra , thanks for getting back to me.

when I install the kubernetes python client using `python setup.py install`, does all the dependencies mentioned inside requirements.txt come from the kubernetes python client repo itself or from the local env? 

My requirement is to install the kubernetes python client inside a container. Hence I first created an egg package for k8s python client (which obviously doesn't have the dependencies packed inside it). So I am trying to make a tar/archive of the k8s client with the code/dependencies packaged together which I can install (offline) in the container.

Any pointers here?
