### ISSUE TITLE
Question about cloud cluster

### ISSUE THREAD

**Issue by AronWaterAron** [kubernetes-client/python#1365]
May I know what if the cluster is in the cloud other than in local?
Such as azure, GKE.
How to make the call to those cloud providers to query the cluster information?

**Comment by yliaog** [comment]
please see https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#generate_kubeconfig_entry for GKE access

**Comment by brendandburns** [comment]
Here are the relevant instructions for generating an Azure Kubernetes Service (AKS) config:
https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_get_credentials
