### ISSUE TITLE
How would I go about listing services and their IPs?

### ISSUE THREAD

**Issue by HereticWilson** [kubernetes-client/python#1366]
https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#python-client

I'm trying to figure out how to do something similar to the example in the link, but listing services and their IPs, rather than pods and their IPs, and then print out said list of IPs.

**Comment by HereticWilson** [comment]
I believe I/ figured it out, if anyone wants to check this out:

`from kubernetes import client, config

config.load_kube_config()

v1 = client.CoreV1Api()
print("Listing services with their IPs:")
ret = v1.list_service_for_all_namespaces(watch=False)
for i in ret.items:
    print("%s\t%s\t%s" % (i.spec.cluster_ip, i.metadata.namespace, i.metadata.name))`

**Comment by nvtkaszpir** [comment]
```python

    kube_config = Configuration()

    try:
        k8s_config.load_incluster_config(client_configuration=kube_config)
    except k8s_config.ConfigException:
        try:
            k8s_config.load_kube_config(client_configuration=kube_config)
        except k8s_config.ConfigException:
            raise Exception("Could not configure kubernetes python client")

    client = api_client.ApiClient(configuration=kube_config)
    v1 = api_client.CoreV1Api(client)
    service_list = v1.list_namespaced_service(ns)
    for service in service_list.items:
        print("%s\t%s" % (service.metadata.name,
                              service.spec))
                              ```
