### ISSUE TITLE
Add support for immutable ConfigMaps

### ISSUE THREAD

**Issue by matthyx** [kubernetes-client/python#1368]
**What is the feature and why do you need it**:
Feature is in beta since 1.19 and it would be nice to allow using it:
https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable

**Describe the solution you'd like to see**:
Allow setting immutable in a ConfigMap (or Secret) declaration, instead of getting this kind of error:
TypeError: __init__() got an expected keyword argument 'immutable'

**Comment by roycaihw** [comment]
The python client is lagging behind Kubernetes releases. New releases are tracked in: https://github.com/kubernetes-client/python/issues/1242

**Comment by matthyx** [comment]
I see, do you need help from me?

**Comment by roycaihw** [comment]
I plan to sync with the current contributors on how we can unblock the releases. Will have more to share once we discuss the next steps.
