### ISSUE TITLE
modify SecurityContext of a conatiner/pod

### ISSUE THREAD

**Issue by thomasaab** [kubernetes-client/python#1371]
Hi, i want to inject some faults to kubernetes, the first thing i want to do is inject latency but for that i have to grant NET_ADMIN permissions, i wanted to know if i can configure that from the python api or does it have to be from the YAML.

**Comment by yliaog** [comment]
you can configure it in the python api directly, it does not need to be from YAML.

**Comment by thomasaab** [comment]
Thank you very much for your answer, but can I modify it when the pod is already created? If so, could you tell me about what function to investigate, please.

For now I solve it using nsenter with the container id, in case someone could find this useful.

**Comment by yliaog** [comment]
not sure if it can be modified post pod creation, pod is mostly immutable with only few exceptions.

**Comment by thomasaab** [comment]
OK thank you very much
