### ISSUE TITLE
PVC "Mounted By" attribute missing from read_namespaced_persistent_volume_claim_status()

### ISSUE THREAD

**Issue by sebastian-mora** [kubernetes-client/python#1372]
**What happened (please include outputs or screenshots)**:

I am trying to find which pod has mounted a PVC. Using `kubectl describe pvc` shows the attribute "Mounted By" but when using the method `read_namespaced_persistent_volume_claim_status` the attribute is missing from the object. I have also check the responses from the following methods `list_persistent_volume_claim_for_all_namespaces` and `read_namespaced_persistent_volume_claim_status_with_http_info`

**What you expected to happen**:
I expected  `read_namespaced_persistent_volume_claim_status` to contain the attribute "Mounted By" in the object. 

**How to reproduce it (as minimally and precisely as possible)**:
```python 

from kubernetes import client, config
config.load_kube_config()
v1Core = client.CoreV1Api()
print(v1Core.read_namespaced_persistent_volume_claim_status(name, namespace))
```

**Environment**:
- Kubernetes version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+e7db93d188d0d1", GitCommit:"e7db93d188d0d12f2fe5336d1b85cdb94cb909d3", GitTreeState:"clean", BuildDate:"2021-01-11T23:50:46Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g., MacOS 10.13.6):
Ubuntu Server 20
- Python version (`python --version`)
3.8
- Python client version (`pip list | grep kubernetes`)
12.0.1

**Comment by roycaihw** [comment]
Is this a feature supported in Kubernetes API server, or is this a feature request for a new API? If it's the latter, please file a feature request in the main Kubernetes repo.

**Comment by aslobodskoy-fiksu** [comment]
> ~Is this a feature supported in Kubernetes API server, or is this a feature request for a new API? If it's the latter, please file a feature request in the main Kubernetes repo.~
> 
> Sorry I didn't read close enough. Could you run `kubectl get pvc -oyaml` and see if the "Mounted By" information is there? If so, that's a missed feature in the python client; if not, likely kubectl implemented extra logic on top of the go client to get that information.

it is absent in json and yaml output

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.15", GitCommit:"58178e7f7aab455bc8de88d3bdd314b64141e7ee", GitTreeState:"clean", BuildDate:"2021-09-15T19:23:02Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by roycaihw** [comment]
Thanks @aslobodskoy-fiksu. Sounds like `kubectl` implemented extra logic to get the "Mounted By" attribute. If you run `kubectl` with `-v` you can see what APIs it calls to achieve this.

**Comment by aslobodskoy-fiksu** [comment]
@roycaihw So your advice is to make direct API calls instead of using kubectl?

**Comment by roycaihw** [comment]
If we want to achieve what kubectl does in a python program, we can use this library to make the same API calls as kubectl and perform the same logic.

**Comment by aslobodskoy-fiksu** [comment]
Maybe it is better API to return this information?

**Comment by roycaihw** [comment]
If we want an API to return this information, it should be a feature request to the main Kubernetes repo. This repo doesn't control what API the server serves.

**Comment by aslobodskoy-fiksu** [comment]
I understand that. Just posted here to discuss because find this thread :)

**Comment by dpfeif** [comment]
FYI & for anybody landing here as I did, I checked in v1.22.3 and the kubectl command calls the `/api/v1/namespaces/{namespace}/pods` and gets a list of all the pods (and the claims they use) in order to provide that information.
