### ISSUE TITLE
Add a support to delete kubernetes API objects from yaml

### ISSUE THREAD

**Issue by marukaz** [kubernetes-client/python#1373]
**What is the feature and why do you need it**:

There is already a util to [create kubernetes API objects from yaml](https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py) and it's very useful.
However, when I create an object from a yaml file, I sometimes want to delete the object created using that file, but there is no util for that.
I think it would be useful to have a util for delete that is paired with [create_from_yaml.py](https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/create_from_yaml.py), in other words, something like `kubectl delete -f`.

**Describe the solution you'd like to see**:

```
from kubernetes import utils, client

yaml_path = "path/to/yaml"
k8s_client = client.ApiClient()

utils.create_from_yaml(k8s_client, yaml_path)
utils.delete_with_yaml(k8s_client, yaml_path)
```

**Comment by adammrozik** [comment]
Hey! I was looking for similar functionality, but I guess if we do it, maybe we should generalize?
I see all that is happening inside the code is basically looking for a function called `create_namespaced_{0}`.

We could replace it with something like: `{action}_namespaced_{resource}` and have a function like:
```
utils.action_from_yaml(client, yaml_path, action='delete') # or 'patch', 'create' etc...
```

WDYT?

**Comment by roycaihw** [comment]
There is a PR already: https://github.com/kubernetes-client/python/pull/1197. It needs some rebase work to clean the changes up, but feel free to leave comments and suggestions there.

**Comment by roycaihw** [comment]
We don't have in-progress work for those functionalities. I imagine patching/replacing could be significantly more difficult than creating/deleting, since you may want to parse yaml into an object and calculate diff against the existing object. You may want to consider using https://github.com/kubernetes-client/python/pull/989 for that.
