### ISSUE TITLE
Add behaviour field to V2beta2HorizontalPodAutoscalerSpec

### ISSUE THREAD

**Issue by efotopoulou** [kubernetes-client/python#1374]
**What is the feature and why do you need it**:
I want to change the default stabilizationWindowSeconds for scale up and down at the hpa.
I need it because i want to programmaticaly change the [configurable scaling behavior of an hpa](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#default-behavior)

**Describe the solution you'd like to see**:
I would like to see an extra field named `behavior` at the [V2beta2HorizontalPodAutoscalerSpec class](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V2beta2HorizontalPodAutoscalerSpec.md).

**Comment by roycaihw** [comment]
Is this a feature supported in Kubernetes API server, or is this a feature request for a new API field? If it's the latter, please file a feature request in the main Kubernetes repo.
