### ISSUE TITLE
config.load_incluster_config fails when called from inside python3 container

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes-client/python#1376]
**What happened (please include outputs or screenshots)**:
Ref: sample code [here](https://github.com/kubernetes-client/python/blob/master/examples/in_cluster_config.py)

I ran python:latest docker image inside a master node with following settings to docker runtime

```
renuka@CO4AEAP000105BD:$ docker pull python
renuka@CO4AEAP000105BD:$ docker create --privileged -t -v /etc/kubernetes:/etc/kubernetes:rw -v /home/remanava/test_data:/test_data:rw --net=host --uts=host --name=python_test python:latest

renuka@CO4AEAP000105BD:$ docker exec -it python_test bash
root@CO4AEAP000105BD:/# pip install kubernetes

# As earlier it complained about missing host & port
root@CO4AEAP000105BD:/# export KUBERNETES_SERVICE_HOST=localhost
root@CO4AEAP000105BD:/# export KUBERNETES_SERVICE_PORT=6443
root@CO4AEAP000105BD:/# python3
Python 3.9.1 (default, Feb  9 2021, 07:42:03) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from kubernetes import client, config
>>> config.load_incluster_config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/incluster_config.py", line 118, in load_incluster_config
    InClusterConfigLoader(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/incluster_config.py", line 73, in _load_config
    raise ConfigException("Service token file does not exists.")
kubernetes.config.config_exception.ConfigException: Service token file does not exists.

```

**What you expected to happen**:
 config.load_incluster_config() loads just fine as given in example.

**How to reproduce it (as minimally and precisely as possible)**:
The steps given above are the least steps for repro.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): At host: v1.18.6
- OS (e.g., MacOS 10.13.6):   linux/ubuntu
- Python version (`python --version`): 3
- Python client version (`pip list | grep kubernetes`) - 12.0.1

**Comment by tomplus** [comment]
In-cluster means that your application has to be run by Kubernetes. It won't work if you start your application manually on K8s nodes.

**Comment by renukamanavalan** [comment]
Thanks Tom. Actually I was **running this in a container running in master node** which is running a kubernetes control plane. But I managed to resolve as below.

1) mount /etc/kubernetes into docker ( -v /etc/kubernetes:/etc/kubernetes:rw )
2) Inside the container
    2.1) export KUBECONFIG=/etc/kubernetes/admin.conf
    2.2) Use "config.load_config"
