### ISSUE TITLE
delete_namespaced_secret requires a body?

### ISSUE THREAD

**Issue by dannysauer** [kubernetes-client/python#1386]
**What happened (please include outputs or screenshots)**:
Attempting to delete a secret resulted in an error:
```
  File "./secretbench.py", line 35, in <module>
    api_response = v1.delete_namespaced_secret(secret_name, namespace)
TypeError: delete_namespaced_secret() missing 1 required positional argument: 'body'
```

**What you expected to happen**:
I expected the `delete_namespaced_secret` method to not require a body. :)

**How to reproduce it (as minimally and precisely as possible)**:
```python
#!/usr/bin/env python3

from base64 import b64encode, b64decode
from kubernetes import client, config

config.load_kube_config()
v1 = client.CoreV1Api()

namespace = "default"
secret_name = "secret-name"
# random string of letters between 8 an 16 chars in length, inclusive
body = client.V1Secret(
    metadata=client.V1ObjectMeta( name=secret_name ),
    data={ 'key': b64encode(b'hello').decode('ascii') },
    )
api_response = v1.create_namespaced_secret(namespace, body)
print( v1.read_namespaced_secret(secret_name, namespace) )
try:
    api_response = v1.delete_namespaced_secret(secret_name, namespace)
except client.rest.ApiException as e:
    print("Failed deleting without a body: %s\n" % e)
```

**Anything else we need to know?**:

Works fine with a default body. :shrug:
```python
    api_response = v1.delete_namespaced_secret(secret_name, namespace, body=client.V1Secret())
```

**Environment**:
- Kubernetes version (`kubectl version`):
  ```
   Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-08-04T12:00:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-08-04T12:00:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
   ```
- OS (e.g., MacOS 10.13.6):
   SUSE Linux Enterprise Server 15 SP2
- Python version (`python --version`)
   Python 3.6.10
- Python client version (`pip list | grep kubernetes`)
   kubernetes          8.0.1
   (installed from SUSE python3-kubernetes-8.0.1-bp152.4.19 RPM)

**Comment by tomplus** [comment]
This body argument is for passing [V1DeleteOptions](V1DeleteOptions).

Please take a look on this example:
https://github.com/kubernetes-client/python/blob/f17076f0e12bd894877825906864b42f25756f0c/examples/deployment_crud.py#L78

**Comment by dannysauer** [comment]
I agree that it has a use, but if it works as expected with the default V1Secret constructor, why not simply make that constructor the default for the argument and make the body argument optional?  As an end-user relatively new to the kube API (and thus also not super familiar with conventions across the API), it feels weird that "delete namespaced secret" requires providing more than a namespace and a secret. :D

**Comment by yliaog** [comment]
which version are you using?

please checkout a similar issue https://github.com/kubernetes-client/python/issues/798#issuecomment-477052554

**Comment by dannysauer** [comment]
> which version are you using?
> 
8.0.1 - which apparently is pretty old.  I'll get in touch with the maintainer at SUSE and see about getting that package updated.  There's a newer version available within the SUSE org; it just needs promoted across the other operating system releases.  There was a big shake-up in the container developer teams there, so this has probably fallen though the cracks for a while.

Thanks, @yliaog. Sounds like the behavior changed a while ago.  This evening I'll get a newer version installed, confirm that it works like I expect, and close this. :)

**Comment by dannysauer** [comment]
My bad; I forgot to close.

**Comment by pransukh** [comment]
Any idea how to do in nodejs client.
