### ISSUE TITLE
Is there an option to configure watch or listener on configmap resource

### ISSUE THREAD

**Issue by srinivasev** [kubernetes-client/python#1387]
We have config maps mounted in the container as volumes. Basically, these config maps are properties (key, value pairs) which are used by the application code. If there is any change in the config maps during runtime, the application/service requires the restart.

Is it possible to have some listener/watch configuration that invokes an action As part of the invocation, we are planning to introduce the kubectl rollout restart on the deployments.

**Comment by tomplus** [comment]
You can watch all type of objects in K8s. Please take a look at this example: https://github.com/kubernetes-client/python/blob/master/examples/pod_namespace_watch.py

**Comment by roycaihw** [comment]
cc @yliaog

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/issues/99770

**Comment by srinivasev** [comment]
Hi, Is there any update on this ?.

**Comment by Addyvan** [comment]
> You can watch all type of objects in K8s. Please take a look at this example: https://github.com/kubernetes-client/python/blob/master/examples/pod_namespace_watch.py

@tomplus This example doesn't make it clear as to how a user might go about doing this. 

I think they (and myself) wanted to know how to watch a specific configmap similar to: `v1.read_namespaced_config_map, name="name", namespace="ns")`

**Comment by yliaog** [comment]
currently there is no support for watching a specific configmap.
