### ISSUE TITLE
how to get namespaces ingressroutes through 

### ISSUE THREAD

**Issue by andy-kwo-any** [kubernetes-client/python#1388]
**Link to the issue (please include a link to the specific documentation or example)**:

I have the following command line below. It gives me the namespaces and ingressroutes names (see the Example below)

`kubectl --context mlf-eks-dev get --all-namespaces ingressroutes`

**Example**

```
NAMESPACE                       NAME                                                           AGE
aberdeentotalyes               aberdeentotalgeyes-yesgepi                                      98d
```

**Description of the issue (please include outputs or screenshots if possible)**:
I'm trying to replicate the results above with the python library client for Kubernetes.

I"m trying to replicate the kubetl command line above through my python code, using the python client for kubernetes but I miss on the option, on how to get the ingressroutes.

```
#My python code
from kubernetes import client, config

# Configs can be set in Configuration class directly or using helper utility
config.load_kube_config()

v1 = client.CoreV1Api()
print("Listing pods with their IPs:")
ret = v1.list_pod_for_all_namespaces(watch=False)
for i in ret.items:
    print("%s\t%s" % (i.metadata.namespace, i.metadata.name))
```

The results are below

```
wwwpaulolo   ci-job-backup-2kt6f
wwwpaulolo   wwwpaulolo-maowordpress-7dddccf44b-ftpbq
wwwvhugo        ci-job-backup-dz5hs
wwwvhugo        wwwvhua-maowordpress-5f7bdfdccd-v7kcx
```

I have the namespaces but not the ingressroutes, as I don't know how can I get it.

Question is what is the option to have the ingressroutes, please?

Any helps are more than welcomed.

Cheers

**Comment by tomplus** [comment]
I guess the context which you pass to kubectl may be important. Could you try to run: ```kubectl get --all-namespaces ingressroutes```?

**Comment by andy-kwo-any** [comment]
Hi @tomplus,

Thank you. The command you gave me, seems to be my initial command line without the `context`.

 Best regards,
 Andy

**Comment by roycaihw** [comment]
It looks like you were using the `list_pod_for_all_namespaces` function and you want a `list_ingressroute_for_all_namespaces` function. `ingressroute` is a CRD so it doesn't have a dedicated function for it. You can use the dynamic custom_object functions and pass in the `group, version, plural` of `ingressroute`: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#list_cluster_custom_object.

**Comment by Priyankasaggu11929** [comment]
cc @Priyankasaggu11929
