### ISSUE TITLE
persistent_volume_reclaim_policy key is not valid when using patch_persistent_volume

### ISSUE THREAD

**Issue by guykanyvision** [kubernetes-client/python#1389]
**What happened:**
I was trying to patch persistent_volume_reclaim_policy with patch_persistent_volume function:

`v1.patch_persistent_volume(name='pvc-e8e2ad15-8236-4da5-ab27-6b39c9fd763f', body={'spec': {'persistent_volume_reclaim_policy': 'Delete'}})`

But nothing changed and and the response was:
`'persistent_volume_reclaim_policy': 'Retain',`

After some debugging i understood that i should change the key to persistentVolumeReclaimPolicy and it worked:
`v1.patch_persistent_volume(name='pvc-e8e2ad15-8236-4da5-ab27-6b39c9fd763f', body={'spec': {'persistentVolumeReclaimPolicy': 'Delete'}})`

This is obviously not indicative, and i think the patch function should translate the key to it's right form

**Comment by roycaihw** [comment]
/assign @yliaog 
cc @roycaihw

**Comment by yliaog** [comment]
currently, this python client is automatically generated, it provides a thin-wrapper on the generated library.

I agree it would be ideal to either 1/ provides the auto translation or 2/ provides some validation to give out indicative errors when wrong key is used. 

However, neither could be easily done. Feel free to add if you have some good ideas about how to do it.
