### ISSUE TITLE
kind is None for each item when requesting for list object.

### ISSUE THREAD

**Issue by gksnjy** [kubernetes-client/python#1394]
Similar issue: https://github.com/kubernetes-client/python/issues/586

`kubectl get nodes -o yaml` returns a list object with each items too set with right `kind` and `apiVersion` but when we request for a node list object through python client it still returns `null`.

```
from kubernetes import client, config
config.load_kube_config()
v1 = client.CoreV1Api()
nodes = v1.list_node()
```
Apart from `kind` being set to `null`, the output of the above code significantly differs from `kubectl get nodes -o yaml`. The latter seems to ignore `null` values by default. So does command line tool does some processing to achieve this?

Client version:
```
pip list | grep kubernetes
kubernetes        12.0.1
```
kubernetes version: 1.16.3

**Comment by alanjcastonguay** [comment]
A request for a list of nodes made with kubectl 1.20.2 to api-server 1.19.3 doesn't contain `kind` or `apiVersion` fields in each Pod resource (inside `.items[]`) in the response body on the wire.

```
kubectl get nodes -v=10 -o yaml 2>&1 | grep 'Response Body' | sed 's/^.*Response Body: //' | jq '.items[] | del(.managedFields, .metadata.managedFields, .status)'
{
  "metadata": {
    "name": "docker-desktop",
    "selfLink": "/api/v1/nodes/docker-desktop",
    "uid": "0b3b0d94-6494-4400-b5ed-8b88c171a4a5",
    "resourceVersion": "110144",
    "creationTimestamp": "2021-03-15T16:44:04Z",
    "labels": {
      "beta.kubernetes.io/arch": "amd64",
      "beta.kubernetes.io/os": "linux",
      "kubernetes.io/arch": "amd64",
      "kubernetes.io/hostname": "docker-desktop",
      "kubernetes.io/os": "linux",
      "node-role.kubernetes.io/master": ""
    },
    "annotations": {
      "kubeadm.alpha.kubernetes.io/cri-socket": "/var/run/dockershim.sock",
      "node.alpha.kubernetes.io/ttl": "0",
      "volumes.kubernetes.io/controller-managed-attach-detach": "true"
    }
  },
  "spec": {}
}
```

```
kubectl get nodes -v=10 -o yaml 2>&1 | grep 'Response Body' | sed 's/^.*Response Body: //' | jq '.items[].kind'
null
```

I think the `kind`/`apiVersion` fields are added by kubectl for print in https://github.com/kubernetes/cli-runtime/blob/bc95ff91653e956ac06fbff1a242c3d96687602d/pkg/printers/typesetter.go#L41

**Comment by gksnjy** [comment]
Thanks for the explanation Alan! I'll see if I can contribute in this regard to set the appropriate `kind` and `apiVersion` values for each items when requesting for list objects. And may be omit `null` values too.
