### ISSUE TITLE
Need a function to get events for a pod

### ISSUE THREAD

**Issue by artiship** [kubernetes-client/python#1398]
**What is the feature and why do you need it**:

When creating a pod failed. I need to log out events of the pod for further troubleshooting. Such as finding out which node is associated with the pod. 

**Describe the solution you'd like to see**:

```
client.list_namespaced_pod_events(namespace, pod_name)
```

**Comment by Ashjoker24** [comment]
I am also need the same

**Comment by artiship** [comment]
I found that the `read_namespaced_pod` function can get the pod status which contains assigned node and error message

**Comment by yliaog** [comment]
you may call events api to list recent events, and find all the events that are related to the pod.

here is the events api:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/EventsV1beta1Api.md
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-events-k8s-io

**Comment by KeithTt** [comment]
> you may call events api to list recent events, and find all the events that are related to the pod.
> 
> here is the events api:
> https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/EventsV1beta1Api.md
> https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#event-v1-events-k8s-io

Is there an API to get the expiration time of the ssl certification?

**Comment by yliaog** [comment]
all k8s APIs are listed in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#-strong-api-overview-strong-

not sure if there is one  API to get the expiration time of the ssl certification

**Comment by KeithTt** [comment]
> all k8s APIs are listed in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#-strong-api-overview-strong-
> 
> not sure if there is one API to get the expiration time of the ssl certification

Unfortunately, I have not found this API...
