### ISSUE TITLE
Document client-side timeouts in watch

### ISSUE THREAD

**Issue by WouldYouKindly** [kubernetes-client/python#1402]
Hi!

From the watch example it is not clear that `timeout_seconds` is a server-side timeout, and that the client will hang indefinitely in case of a network failure. I found out about this from [this comment](https://github.com/kubernetes-client/python/issues/1148#issuecomment-626184613) after we experienced the issue in my team.

I suggest documenting this in [the watch example](https://github.com/kubernetes-client/python/blob/master/examples/pod_namespace_watch.py).

**Comment by roycaihw** [comment]
cc @roycaihw

**Comment by Priyankasaggu11929** [comment]
@roycaihw, can I work on updating the documentation around this? Taking reference information from this comment here https://github.com/kubernetes-client/python/issues/1148#issuecomment-626184613.

Thank you!

**Comment by WouldYouKindly** [comment]
Thank you both very much!
