### ISSUE TITLE
Does not load server address from kube config

### ISSUE THREAD

**Issue by konradjurk** [kubernetes-client/python#1407]
After `config.load_kube_config()` I can use `config.list_kube_config_contexts()` to list the contexts from my kube config but trying to execute any API fails with

```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/namespaces (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11128d160>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

The Kubernetes server does not run on localhost:80. The correct address is configured in the kubeconfig file and kubectl has no problems connecting to the server.

The only way to make your library work with my server is to run `sudo kubectl proxy --port=80` somewhere. I guess that is not the desired solution.

Can you please tell me how to correctly load the config file? Thanks!

**Comment by konradjurk** [comment]
💡Confused the order of these function calls.

Wrong
```
v1 = client.CoreV1Api()

config.load_kube_config()
```

Correct
```
config.load_kube_config()

v1 = client.CoreV1Api()
```

**Comment by Thelin90** [comment]
> 💡Confused the order of these function calls.
> 
> Wrong
> 
> ```
> v1 = client.CoreV1Api()
> 
> config.load_kube_config()
> ```
> 
> Correct
> 
> ```
> config.load_kube_config()
> 
> v1 = client.CoreV1Api()
> ```

Thank you! I was banging my head into oblivion on this....
