### ISSUE TITLE
Failure when running custom auth programs ("exec" in kubeconfig) is not indicated in exceptions

### ISSUE THREAD

**Issue by zbentley** [kubernetes-client/python#1409]
**What happened (please include outputs or screenshots)**:

When using an invalid `exec` field for my kubeconfig's auth, the Python kubernetes client emits exceptions that are not useful for diagnosing the issue (the error doesn't indicate that there was anything wrong running the auth program):

```
    core_v1_api.create_namespaced_config_map(namespace='kube-system', body=yaml.safe_load(self.outputs['config_map_aws_auth']))
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api/core_v1_api.py", line 6630, in create_namespaced_config_map
    return self.create_namespaced_config_map_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api/core_v1_api.py", line 6739, in create_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 397, in request
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 280, in POST
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/rest.py", line 233, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '1dabb4bf-e022-4f37-beb3-8af003da8c19', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 07 Apr 2021 18:42:01 GMT', 'Content-Length': '285'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:anonymous\" cannot create resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}
```

Above that stacktrace, the STDERR/STDOUT of the auth `exec` program are sent straight to the terminal that Python is hooked up to, which means that I can't see them when e.g. the `ApiException` above is caught and sent to my error reporting system. The only place those are visible are if I get the full STDOUT of my program that uses this library.

**What you expected to happen**:

Given an invalid `exec` auth program, I would expect this library to not even attempt to talk over the network. Instead, it should fail with some kind of exception that indicates a subprocess failure. The exception should include the exit code, STDERR, and ideally also some of the STDOUT of the auth program for use in debugging.

For example, given an auth program of `bash -c 'echo OUTPUT; echo FAILURE 1>&2; exit 127'`:

```
kubernetes.client.exceptions.AuthException: `unable to exec auth program for user '$username'. 
bash' exited with status 127.
STDERR: "FAILURE"
STDOUT: "OUTPUT"
```

The current behavior is also inconsistent: if the `exec` program is not found at all, an error similar to the above is raised, but if it's found and doesn't work there's no indication that that happened in the stacktrace.

**How to reproduce it (as minimally and precisely as possible)**:

Set up a kube config with a *deliberately invalid* `exec` setup for a user. For example:

```
apiVersion: v1
clusters:
- cluster:
    server: ...
    certificate-authority-data: ...
  name: kubernetes
contexts:
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: bash
      args:
        - '-c'
        - 'echo BAD OUT; echo BAD ERR 1>&2; exit 1'
```

Run the following snippet:
```
from kubernetes import client, config
config.load_kube_config(config_file="wherever you put the above kubeconfig example")
core_v1_api = client.CoreV1Api()
core_v1_api.create_namespaced_config_map(namespace='kube-system', body={})
```

You'll get an error like:
```
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ec7c7dac-ee27-405b-8305-d4b0c0fea26f', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 08 Apr 2021 15:58:49 GMT', 'Content-Length': '277'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:anonymous\" cannot create resource \"configmaps\" in API group \"\" in the namespace \"foo\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}
```

With no indication of the fact that the auth program failed.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:55:27Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g., MacOS 10.13.6): MacOS 10.14.6 and Ubuntu 18.04
- Python version (`python --version`) `3.6.10`
- Python client version (`pip list | grep kubernetes`) `kubernetes             12.0.1`

**Comment by roycaihw** [comment]
A similar issue was reported in https://kubernetes.slack.com/archives/C76GB48RK/p1621545987016400:

> my local development environment was misconfigured, aws CLI could not be reached from within target Python virtual environment

> Python client (suspiciously) complains about system:anonymous user being forbidden

**Comment by LucaSoato** [comment]
Is this still happening?

**Comment by zbentley** [comment]
I was able to reproduce, yes.
