### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-client/python#1413]
As documented in https://github.com/kubernetes-client/python/blob/master/CHANGELOG.md#v1700-snapshot. We should drop support for Python 2 from the next release (v18.0.0). This includes: 
- drop Python 2 from master branch
- make sure all the tests use Python 3
- drop Python 2 from v18 beta release.

**Comment by roycaihw** [comment]
This can be started after we cut a v17 GA release. We've released v17 beta this Monday. Given k8s v17 is pretty old, we will give v17 beta one week of soak time. The ETA for v17 GA is next Monday 05-10. 

To drop Python 2, most importantly we need to remove https://github.com/kubernetes-client/python/blob/b13b350dba25e279765b3a8d055e5485b5289e2d/setup.py#L75-L76
which controls the Python version the package runs in. 

Additionally, we should remove any places that use Python 2 in this repo, especially the tests:
https://github.com/kubernetes-client/python/blob/master/.travis.yml
https://github.com/kubernetes-client/python/blob/master/.github/workflows/test.yaml

**Comment by roycaihw** [comment]
This needs to happen after the v17 GA release because otherwise it will cause trouble pulling master into release-17.0, and accidentally drop Python 2 for v17.

**Comment by roycaihw** [comment]
the same needs to be done for python-base

**Comment by Priyankasaggu11929** [comment]
I’ll do the same for Python-base as well. Thank you for pointing.

**Comment by roycaihw** [comment]
I just realized that some of our tests (e.g. codestyle) only exist in Python 2. 

We need to make sure we have the same test in Python 3. @Priyankasaggu11929 would you mind taking a look at adding a Python 3 codestyle test? This doesn't have to be blocked by the v17 GA release. 

Sorry this is more complex than I thought. Let me know if you have any questions.

**Comment by Priyankasaggu11929** [comment]
Yes, I will have a look at this & try adding the required tests in python3.

Just to be sure `v17 GA release` is happening this week itself, right? 

And when you say this change doesn't have to be blocked by the GA release, that means we can go with `v17 GA release` without these changes for now?

**Comment by Priyankasaggu11929** [comment]
Understood now. Thank you for the clarification. :)
