### ISSUE TITLE
No API for creating ephemeral containers

### ISSUE THREAD

**Issue by aantn** [kubernetes-client/python#1417]
It seems like there is no API for creating ephemeral containers. The ephemeral container model is generated properly however no create_ephemeral_containers function seems to exist.

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/blob/5b46064cae41395cf775cb445ffdaae1261076c7/pkg/features/kube_features.go#L97

it was alpha since 1.16, and stayed at alpha till now. alpha features are disabled by default. once it moves to beta, there will be api for creating ephemeral containers.

**Comment by roycaihw** [comment]
Ephemeral container is a subresource of pod. There is no standalone API endpoint for ephemeral containers. You can use pod API to access ephemeral containers.

**Comment by roycaihw** [comment]
There was a bug in the upstream openapi spec that caused the API to be missing. It was fixed by https://github.com/kubernetes/kubernetes/pull/97276 in 1.21. 

The `/api/v1/namespaces/{namespace}/pods/{name}/ephemeralcontainers` API will be available when we generate the 1.21 client

**Comment by roycaihw** [comment]
It may be worth cherrypicking the fix kubernetes/kubernetes#97276 to older kubernetes minor releases, e.g. 1.19 and 1.20, so we can generating the API before 1.21. The cherrypick needs to be done in k/k.
