### ISSUE TITLE
Example of body format for patch_cluster_custom_object

### ISSUE THREAD

**Issue by SimplySeth** [kubernetes-client/python#1427]
Currently I'm struggling to use `patch_cluster_custom_object` , I though I could just feed it the JSON of the data in the body and it will patch it. 

I think there is some more information in `body` that needs to be included. 

Is there an example somewhere of what information needs to be in body so I can patch my custom resource?
Thanks.

**Comment by roycaihw** [comment]
cc @Yashks1994 @Priyankasaggu11929
