### ISSUE TITLE
Improve the custom_object.py to be more specific to usage of namespaced custom resource

### ISSUE THREAD

**Issue by Priyankasaggu11929** [kubernetes-client/python#1438]
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/tree/master/examples

**Description of the issue (please include outputs or screenshots if possible)**:

The [examples/custom_object.py](https://github.com/kubernetes-client/python/blob/master/examples/custom_object.py) example script can be improved by making it more specific to usage of  [kubernetes.client.CustomObjectsApi](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md) for a namespaced scope custom resource.

Following are the suggestion for improvement:
- rename the file to `namespaced_custom_object.py`
- include example usage of `patch_namespaced_custom_object` method

**Comment by Priyankasaggu11929** [comment]
cc @Yashks1994

**Comment by Yashks1994** [comment]
Opened a PR- https://github.com/kubernetes-client/python/pull/1439
