### ISSUE TITLE
Connection failed to AKS cluster intermittently 

### ISSUE THREAD

**Issue by neelam256** [kubernetes-client/python#1445]
**What happened (please include outputs or screenshots)**:

Get following type of errors intermittently 
1. urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='xxxxxxxxxxxxxxxxxxx', port=443): Read timed out. (read timeout=15)
2. urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
3. websocket._exceptions.WebSocketBadStatusException: Handshake status 200 OK

**What you expected to happen**:

Our process create bunch of kubernetes objects sometime it failed  due to different types of connection issues.
i have  connection timeout = 5 seconds and readtimeout  15 seconds
kubernetes python client 
version : 12.0.1
[Traceback.txt](https://github.com/kubernetes-client/python/files/6405795/Traceback.txt)
Attached error log file "Traceback.txt"

**How to reproduce it (as minimally and precisely as possible)**:

Might be connecting to AKS cluster and creating different types of kubernetes objects like ( namespace, STS, deployment , azureidentity, azureidentitybinding , network policy..etc)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):  ( AKS 
kubernetes version 1.18.14)
- OS (e.g., MacOS 10.13.6):  running in same cluster POD, 
- with following :  debian , version id 10 version_code_name: buster
- Python version (`python --version`)  python version 3.2.0

- Python client version (`pip list | grep kubernetes`) 12.0.1

**Comment by skamchiline** [comment]
Hello, I have similar issue:

It seems that 2 of these exceptions happened at the same time. In my case it happens in 100% cases.
```
...
Traceback (most recent call last):
98 | File "/usr/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 468, in websocket_call
99 | client = WSClient(configuration, url, headers, capture_all)
100 | File "/usr/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 62, in __init__
101 | self.sock = create_websocket(configuration, url, headers)
102 | File "/usr/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 452, in create_websocket
103 | websocket.connect(url, header=header)
104 | File "/usr/lib/python3.8/site-packages/websocket/_core.py", line 252, in connect
105 | self.handshake_response = handshake(self.sock, *addrs, **options)
106 | File "/usr/lib/python3.8/site-packages/websocket/_handshake.py", line 79, in handshake
107 | status, resp = _get_resp_headers(sock)
108 | File "/usr/lib/python3.8/site-packages/websocket/_handshake.py", line 164, in _get_resp_headers
109 | raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)
110 | websocket._exceptions.WebSocketBadStatusException: Handshake status 200 OK
111 |  
112 | During handling of the above exception, another exception occurred:
113 |  
114 | Traceback (most recent call last):
115 | File "/scripts/UpdateCluster.py", line 101, in <module>
116 | cluster.Deploy()
117 | File "/scripts/Cluster.py", line 325, in Deploy
118 | self.RollingUpdate(currentVersion=currentK8sVersion, versionSkew=2)
119 | File "/scripts/Cluster.py", line 263, in RollingUpdate
120 | nodesObj = self.kube.getNodesObj()
121 | File "/libs/kube.py", line 121, in getNodesObj
122 | return self.apiV1.list_node(label_selector=label)
123 | File "/usr/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 16414, in list_node
124 | return self.list_node_with_http_info(**kwargs)  # noqa: E501
125 | File "/usr/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 16517, in list_node_with_http_info
126 | return self.api_client.call_api(
127 | File "/usr/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
128 | return self.__call_api(resource_path, method,
129 | File "/usr/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
130 | response_data = self.request(
131 | File "/usr/lib/python3.8/site-packages/kubernetes/stream/ws_client.py", line 474, in websocket_call
132 | raise ApiException(status=0, reason=str(e))
133 | kubernetes.client.exceptions.ApiException: (0)
134 | Reason: Handshake status 200 OK
135
```

Versions:
kubeconfig        1.1.1
kubernetes        12.0.1
webencodings      0.5.1
websocket-client  0.58.0

python: Python 3.8.8

Interestingly - the previous version of the docker image with this code works fine. Nothing was changed in this part of the code between these images. All python lib versions are the same.
The code runs on alpine:3.12 based docker image. In regular MacOS environment I don't see this problem.

**Comment by skamchiline** [comment]
More information on this issue:

I found that in my case the problem happens only if before this call I have this code:
```
        with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
            results = list(executor.map(comm, self.podList))
```
the `comm` is a function which included this call:
```
        resp = stream(self.apiV1.connect_get_namespaced_pod_exec,
                      podname,
                      namespace,
                      command=command,
                      container=container,
                      stderr=True, stdin=False,
                      stdout=True, tty=False)
```
where `stream` is `from kubernetes.stream import stream`

So it could be that `stream` somehow works incorrectly with sockets, so consequent call to get_nodes_obj raises an exception?

**Comment by neelam256** [comment]
I am running this microservice on same cluster, that means I am creating k8s objects in same cluster where this microservice is running. 
That is making https connection to kubeapi server , I observed all these connection issues.
Is there any way I can avoid this (http/https) connection  and create k8s objects in same cluster.

**Comment by neelam256** [comment]
connection_pool_maxsize is cpu_count*5 , and cpu_count is 4 in my system , should i increase the pool size , any ideas ?
**in my case, - sending a lot of requests to one host (kubernetes master)**

**Comment by 15m43lk4155y** [comment]
I am having the same type of connection errors with an AKS cluster as well, has any solution been found for this?
