### ISSUE TITLE
method to get the details of a deployment pod

### ISSUE THREAD

**Issue by felixsiju** [kubernetes-client/python#1473]
**What is the feature and why do you need it**:

A method to get the details of a pod including the status which will help to proceed with the check status .

**Describe the solution you'd like to see**:

**Comment by Priyankasaggu11929** [comment]
@felixsiju, thanks for raising the issue. 

Could you please provide more details on the feature with the help of some examples.

**Comment by felixsiju** [comment]
Eg 
creating a pod using create_namespaced_deployment method
Now need to use the list_namespaced_pod method and itrate to get the details of the pod deployed and the staus whtehr its success or failure

Its good to have a direct get method to get the details directly by passing the pod name

**Comment by felixsiju** [comment]
@ Priyankasaggu11929 , Explained an eg above
Thanks

**Comment by felixsiju** [comment]
closing this as this already exists. 
read_namespaced_deployment
