### ISSUE TITLE
Leaderelection package lost resourcelock sub package

### ISSUE THREAD

**Issue by Arvintian** [kubernetes-client/python#1475]
I install the package version 17.17.0 from pypi `pip install kubernetes==17.17.0`, follow the [example.py](https://github.com/kubernetes-client/python-base/blob/master/leaderelection/example.py) try to enable leaderelection, but i can't find the resourcelock sub package in my local.

```
/lib/python3.7/site-packages/kubernetes/leaderelection
$ ls -al
total 52
drwxrwxr-x  3 xxx xxx 4096 May 21 18:32 .
drwxrwxr-x 10 xxx xxx 4096 May 21 18:32 ..
-rw-rw-r--  1 xxx xxx 2176 May 21 18:32 electionconfig.py
-rw-rw-r--  1 xxx xxx 1838 May 21 18:32 example.py
-rw-rw-r--  1 xxx xxx  587 May 21 18:32 __init__.py
-rw-rw-r--  1 xxx xxx 8377 May 21 18:32 leaderelection.py
-rw-rw-r--  1 xxx xxx  911 May 21 18:32 leaderelectionrecord.py
-rw-rw-r--  1 xxx xxx 9900 May 21 18:32 leaderelection_test.py
drwxrwxr-x  2 xxx xxx 4096 May 21 18:32 __pycache__
```

**Comment by tyrken** [comment]
Just hit the same issue trying to follow the same example - it does not seem to be in the downloaded package.  Does it need adding as was done for https://github.com/kubernetes-client/python/pull/1411/commits/dadc47b282af834a500c00ad2c052d69b5ff67b8 ?

**Comment by Arvintian** [comment]
I copy the resourcelock code to my project directory resolve this issue, @tyrken maybe it is work for you.

**Comment by tyrken** [comment]
Thanks @Arvintian - yeah I did the same.

I'm not sure but think the intention was that `resourcelock` should have been in the shipping package, so could you re-open this so we get the maintainers to look at it?

**Comment by tdihp** [comment]
Spot the same symptom, will attempt to PR on this.

**Comment by tyrken** [comment]
Probably fixed by https://github.com/kubernetes-client/python-base/pull/267 and https://github.com/kubernetes-client/python/pull/1631
