### ISSUE TITLE
[Question] Use all api servers

### ISSUE THREAD

**Issue by ltagliamonte-dd** [kubernetes-client/python#1476]
I wrote a job for extracting some info about cluster costs.
The job goes over all the nodes and all the pods and performs few math.
Atm using python without a client side informer cache, the job is a pretty heavy hitter on the api servers, although i've noticed that the k8s lib uses a single API server for the whole duration, this is what i mean:
<img width="820" alt="Screen Shot 2021-05-25 at 10 23 51 AM" src="https://user-images.githubusercontent.com/51684360/119541508-56b39400-bd43-11eb-8c0b-4cb666f138f7.png">

By using the in cluster config the library will use the service IP attached to the api servers.

The service IP is a virtual IP that is translated by iptables in the real api IP and should be also load balanced as well.

I believe that the iptables load balancing is not working because the library opens a persistent connection to the api servers and uses that connection for the whole duration, i didn't have time yet to look at the code, but i was wondering if there is a client config that i can tune so make the lib re-create connections to api server more often so i can use more equally the api servers in my cluster.

**Comment by edmeister** [comment]
`kube-api-server` does leader election, so only 1 of them will serve your requests. The other ones are standing by in case they need to take over.

**Comment by ltagliamonte-dd** [comment]
I've looked at the code and a quick and dirty fix is to close the connection pool, every N requests:
<img width="1672" alt="Screen Shot 2021-05-26 at 11 07 06 AM" src="https://user-images.githubusercontent.com/51684360/119710948-d14be480-be13-11eb-8379-11f1d71dbfbb.png">
```
# the kubernetes client creates a long running connection pool that ends up sending all requests
# to a single api server, to balance the reqs among all the available api servers we can close the pool.
# This is not great in terms of TCP perfs but definitely better than create a CPU spike on single api server
core_api.api_client.rest_client.pool_manager.clear()
```
