### ISSUE TITLE
Need to perform ibmcloud ks cluster config --cluster <cluster> using Python kubernetes package

### ISSUE THREAD

**Issue by mabdullah1994** [kubernetes-client/python#1482]
Hi. Is there a way to configure the Kubernetes cluster using python Kubernetes package? I need to perform the following:

`ibmcloud ks cluster config --cluster <cluster>`

**Comment by palnabarun** [comment]
@mabdullah1994 -- Can you please explain what that command does?

Although do note that this project is a client in Python to talk to the Kubernetes API Server. We don't support features outside out of expectations from an official client.

/kind support

**Comment by mabdullah1994** [comment]
Thanks for the response @palnabarun 

This command basically downloads the kube config from the kube cluster hosted on ibm cloud. The configurations are downloaded in the `~/.kube/config` file and then I am able to perform typical kubectl commands such as 

`kubectl get pods`

I need this to be done programmatically, and not using CLI commands. Please advise. Thanks

**Comment by palnabarun** [comment]
Hi @mabdullah1994 -- this seems to be out of the scope of the Kubernetes Python client as it is very much vendor-specific.

I feel that this question should be asked in the appropriate IBM cloud forums. They would be more suited to answer this question.

**Comment by mabdullah1994** [comment]
Hi @palnabarun. I think I agree with what you've said. This is vendor-specific and should not be discussed here. Thanks for the support. Closing the issue now.
