### ISSUE TITLE
Make google-auth an optional dependency

### ISSUE THREAD

**Issue by hmonteiro** [kubernetes-client/python#1486]
From what I can gather, `google-auth` is only required when using the google cloud platform.

Since it's of use only to a subset of the users, I propose that that dependency gets moved from the general requirements to the `extras` part of the `setup.py` file. Users that require this feature would install the package using, for example, a "gcp" extras flag (e.g. `pip install kubernetes[gcp]`).

In corporate environments, where compliance regulations require tracking and justifying all packages installed, this would reduce the maintenance burden by removing a whole section of the dependency tree when it's not needed.

**Comment by palnabarun** [comment]
Thanks for filing this issue. This is a good ask.

I will have a look at this.

/assign

**Comment by hmonteiro** [comment]
Thanks for having a look at this
