### ISSUE TITLE
current context can't be "null"

### ISSUE THREAD

**Issue by Klaven** [kubernetes-client/python#1500]
**What happened (please include outputs or screenshots)**:

I want to start this off by saying it's probably a super unimportant edge case. Second I want to say i'm not a python developer so maybe this is expected/desired results though it seems like a un-sanitized strings issue.

If you name your context "null" like this:
```yaml
- context:
    cluster: null
    user: null
  name: null
current-context: null
```
The command line complains that the context must be set, even though it is set. Kubectl and go client-go handle this just fine.

**What you expected to happen**:

I expect it to use the context `null`

**How to reproduce it (as minimally and precisely as possible)**:

create a cluster called `null` with a context `null`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): 1.20
- OS (e.g., MacOS 10.13.6): Ubuntu 20.04
- Python version (`python --version`): 3.7.3
- Python client version (`pip list | grep kubernetes`): 17.17.0

Here is a screen shot of it happening :)

![Screenshot from 2021-06-26 23-42-07](https://user-images.githubusercontent.com/11365642/123554828-ef2ca200-d74f-11eb-8fd2-35fa4f42f1a0.png)

**Comment by Klaven** [comment]
Also, that cluster no longer exists in any way and was for demo purposes. just wanted to give the full output. I know sensitive info is in it, but it's info that no longer exists.

**Comment by roycaihw** [comment]
I think Python treats `null` specially. That's why it behaves different from kubectl and client-go (Golang).

Does changing the value to `"null"` help?

**Comment by Klaven** [comment]
I will check later today when I have the time. I was wondering if it was something along these lines (I apologize, I don't use python much!) If that is the case then we can close this as it's more of a "feature" of python then anything else.
