### ISSUE TITLE
V1ResourceQuotaSpec with "requests.nvidia.com/gpu:" fails

### ISSUE THREAD

**Issue by cesarandreslopez** [kubernetes-client/python#1505]
**What happened (please include outputs or screenshots)**:

When trying to set up the quota at namespace level in the python client API:

```
    resource_quota = client.V1ResourceQuota(
        spec=client.V1ResourceQuotaSpec(
            hard={"requests.cpu": "2", "requests.memory": "2000M", "limits.cpu": "2", "limits.memory": "2000M",
                  "requests.storage": "80Gi", "services.nodeports": "0","requests.nvidia.com/gpu:": "1"}))
    resource_quota.metadata = client.V1ObjectMeta(namespace=namespace,
                                                  name="user-quota")
    status = v1.create_namespaced_resource_quota(namespace, resource_quota)
```

The API will complain about the "/" character in requests.nvidia.com/gpu

```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"ResourceQuota \"user-quota\" is invalid: spec.hard[requests.nvidia.com/gpu:]: Invalid value: \"requests.nvidia.com/gpu:\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')","reason":"Invalid","details":{"name":"user-quota","kind":"ResourceQuota","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"requests.nvidia.com/gpu:\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')","field":"spec.hard[requests.nvidia.com/gpu:]"}]},"code":422}
```

**What you expected to happen**:

I should be able to enforce GPU quotas.

**How to reproduce it (as minimally and precisely as possible)**:

Add "requests.nvidia.com/gpu:": "1" in V1ResourceQuotaSpec

**Environment**:
- Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g., MacOS 10.13.6):
Ubuntu 20.04
- Python version 
3.8
- Python client version 
pip install kubernetes==17.17.0

**Comment by yliaog** [comment]
it looks that "requests.nvidia.com/gpu:" is being used, instead of "requests.nvidia.com/gpu". note the extra ':', which should be removed.

**Comment by cesarandreslopez** [comment]
You are absolutely right. Thanks
