### ISSUE TITLE
Treatment for SealedSecret 

### ISSUE THREAD

**Issue by rkhudov** [kubernetes-client/python#1507]
**What happened (please include outputs or screenshots)**:
I am trying to use utils library (from kubernetes import utils) and method utils.create_from_dict(...) using my .yaml file
The content of this file is:
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
....
But it gives me an error
module 'kubernetes.client' has no attribute 'BitnamiComV1alpha1Api'
and also there is no kind of SealedSecret in the kubernetes-client,

**What you expected to happen**:
I am expecting, that kubernetes.client treat SealedSecret kind of .yaml file and know services that is using for sealing, for example (bitnami).

**How to reproduce it (as minimally and precisely as possible)**:
Check the first section

**Environment**:
- Kubernetes version: Client version v1.19.7; Server version v1.19.9.
- OS: Linux
- Python version: 3.8
- Python client version: 17.17.0

**Comment by roycaihw** [comment]
It looks like SealedSecret is a custom resource, therefore there is no typed client generated for it. You can use the custom object client or the dynamic client to access it. For example: 
- https://github.com/kubernetes-client/python/blob/master/examples/namespaced_custom_object.py
- https://github.com/kubernetes-client/python/blob/master/examples/cluster_scoped_custom_object.py
- https://github.com/kubernetes-client/python/tree/master/examples/dynamic-client
