### ISSUE TITLE
kubernetes python library for fetching the node allocatable memory

### ISSUE THREAD

**Issue by Srinidhi2301** [kubernetes-client/python#1508]
I need to get the allocatable memory for the node using the python client API. 
    c = client.Configuration()
    c.debug = True
    config.load_kube_config() 

    core_v1 = client.CoreV1Api()
    app_v1 = client.AppsV1Api()

    node = core_v1.list_node()
    print(node.status.capacity)
    print(node.status.allocatable)

could anyoneplease suggest me the right way of get the node's remaining memory

**Comment by roycaihw** [comment]
`node = core_v1.list_node` returns a node list object. To access the allocatable memory of individual nodes, you need to iterate through the [items](https://github.com/kubernetes-client/python/blob/05e8f5798aa40be42cc13cfc115c753ca66d089b/kubernetes/client/models/v1_node_list.py#L37) of the node list, and then access `.status.allocatable`
