### ISSUE TITLE
extensions/v1beta1 for ingress deprecated but new api not found in models

### ISSUE THREAD

**Issue by frederiksf** [kubernetes-client/python#1509]
The kubernetes documentation tells me the following ;

_The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress will no longer be served in v1.22.

Migrate manifests and API clients to use the networking.k8s.io/v1 API version, available since v1.19._

I have the models but i was not able to find the new models based on networking.k8s.io/v1. This is something not yet made and will come in the future or do i miss something? Methods i used;
```BASH
body = client.ExtensionsV1beta1Ingress(
            api_version="extensions/v1beta1",
            kind="Ingress",
            metadata=client.V1ObjectMeta(name="blabla-tenant-ingress",
                                         annotations=annotations),
            spec=client.ExtensionsV1beta1IngressSpec(
                rules=rules
            ))
```

**Comment by yliaog** [comment]
you're right, 1.19 has networking.k8s.io/v1, but python client library latest release is 1.18. the release for 1.19 will likely start next week. so check in a few weeks for the 1.19 release.

**Comment by yliaog** [comment]
it is due to lack of contributors, help is welcome!

**Comment by bateau84** [comment]
Any progress on this yet?

**Comment by roycaihw** [comment]
[v19.15.0a1](https://github.com/kubernetes-client/python/releases/tag/v19.15.0a1) has been released. Please give it a try and file any issue you find. I plan to release a beta version in the next week or two.

**Comment by OvervCW** [comment]
> it is due to lack of contributors, help is welcome!

What kind of work is involved besides rerunning a generator on the latest OpenAPI spec?

**Comment by yliaog** [comment]
please see https://github.com/kubernetes-client/python/blob/master/devel/release.md for the release process.
