### ISSUE TITLE
Loading config fails in docker without aws cli

### ISSUE THREAD

**Issue by kemega** [kubernetes-client/python#1516]
**What happened (please include outputs or screenshots)**:
I'm trying to dockerize a python app that calls my `AWS EKS` cluster using `kubernetes-client`. The app works fine locally but I faced an issue when I tried dockerizing it.
Running `config.load_kube_config()` throws `ERROR:root:[Errno 2] No such file or directory: 'aws'`, only when using docker.
 I added my `.kube` folder to the /root user inside the container. Also I ran the container with environment variables:
```
AWS_ACCESS_KEY_ID=<my_key>
AWS_SECRET_ACCESS_KEY=<my_secret>
```
Note: The user with the above credentials is an admin user (has administrative role in `aws iam`), also this is the user that created the `EKS` cluster.

While trying to fix this I installed `aws cli` in the container, that is when the config is successfully loaded. I also have the `aws cli` installed locally (that would explain why loading configs didn't work only in docker)

I've looked for any `aws cli` reference in the docs with no luck. Does kubernete-client use `aws cli` somehow? And do I really have to install `aws cli` to use `kubernetes-client` with `AWS EKS`?

**What you expected to happen**:
The kubernetes client should be able to load config in default location within a container.

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a folder for the app and copy `.kube` folder there. 
2) Create a python `script.py`:
```py
#!/usr/bin/env python3

from kubernetes import config
config.load_kube_config()
```
3) Create a docker file:
```
FROM python:3.9
RUN mkdir /code
WORKDIR /code
ADD . /code
RUN pip install kubernetes
ADD docker-entrypoint.sh /
ENTRYPOINT [ "/docker-entrypoint.sh" ]
```
4) Create a `docker-entrypoint.sh`:
```
#!/bin/bash
cp -r /code/.kube /root
cd /code
python3 script.py
```
5) Build image:
`docker build -t k8:1 .`
6) Run image with env file:
`docker run --env-file docker.env k8:1`  (the docker.env file contains the credentials mentioned above)

**Anything else we need to know?**:
Without installing the `aws cli` I get `ERROR:root:[Errno 2] No such file or directory: 'aws'`, however if I install the `aws cli` by adding this to the `dockerfile`
```
# Install aws cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip -o awscliv2.zip
RUN ./aws/install
```
I don't get the error anymore.
**Environment**:
- Kubernetes version (`kubectl version`): v1.18.9
- OS (e.g., MacOS 10.13.6): Debian GNU/Linux 10 (buster)
- Python version (`python --version`): v3.9
- Python client version (`pip list | grep kubernetes`): v17.17.0

**Comment by palnabarun** [comment]
@kemega -- The Kubernetes Client doesn't depend on AWS CLI, however, in order to speak to EKS clusters you would need the AWS CLI. There can be two solutions here:
1. Install AWS CLI in the container since you are using your local kube config.
2. Create a service account for the workload and mount that to the pod that you are creating.

Method 2 is the community suggested one as you would have granular controls of what the pod can do in the Kubernetes API server.

**Comment by kemega** [comment]
@palnabarun Thanks for the explanation.

**Comment by palnabarun** [comment]
Closing the issue for now. Please feel free to reopen in case you have any further doubts. :)

/close
