### ISSUE TITLE
cli.list_namespaced_pod(namespace) got wrong pod 

### ISSUE THREAD

**Issue by stark-ydq** [kubernetes-client/python#1524]
**What happened (please include outputs or screenshots)**:
when I use  patch_one_workload_by_type(cls_id, kind, namespaces, workload_id, body) to update image version of my pod ,
and then use cli.list_namespaced_pod(namespace)  to checkout pod ,I find that I usually got wrong version of my pod's container image unless I fresh the kubectl on terminal use "kubectl get pod -n xxxxxx"
**What you expected to happen**:
get right version of my pod's container image
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.3-tke.11", GitCommit:"43d7ff3fae76c311692393308feeca4ceb740ebc", GitTreeState:"clean", BuildDate:"2020-10-12T03:37:10Z", GoVersion:"go1.12.14", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g., MacOS 10.13.6): MacOs10.15.7
- Python version (`python --version`) 3.8
- Python client version (`pip list | grep kubernetes`):12.0.0

**Comment by palnabarun** [comment]
@stark-ydq -- can you please mention how we can reproduce the issue that you are facing?

**Comment by roycaihw** [comment]
/assign @palnabarun 
Thank you!
