### ISSUE TITLE
kube_config.py leaking file descriptors when running load_kube_config

### ISSUE THREAD

**Issue by AWSmith0216** [kubernetes-client/python#1531]
**What happened (please include outputs or screenshots)**:
I work in an environment where we have several hundred Kubernetes clusters. One process we use connects to each cluster to retrieve some metadata. After connecting to 200 or so, I started hitting the OS open files limit. Using psutil I could see that there were several files under /tmp that were being left open after every invocation of 'load_kube_config'.

**What you expected to happen**:
Not to leak file descriptors

**How to reproduce it (as minimally and precisely as possible)**:
I was unable to reproduce it with a single cluster, so don't have easy reproduction steps

**Anything else we need to know?**:
The problem seems to be the following function: https://github.com/kubernetes-client/python-base/blob/master/config/kube_config.py#L73

```
def _create_temp_file_with_content(content, temp_file_path=None):
    if len(_temp_files) == 0:
        atexit.register(_cleanup_temp_files)
    # Because we may change context several times, try to remember files we
    # created and reuse them at a small memory cost.
    content_key = str(content)
    if content_key in _temp_files:
        return _temp_files[content_key]
    if temp_file_path and not os.path.isdir(temp_file_path):
        os.makedirs(name=temp_file_path)
    _, name = tempfile.mkstemp(dir=temp_file_path)
    _temp_files[content_key] = name
    with open(name, 'wb') as fd:
        fd.write(content.encode() if isinstance(content, str) else content)
    return name
```

The 'tempfile.mkstemp' returns an open file descriptor, but it's never used or closed. I was able to monkey patch the function to be the following and the leaking file descriptors stopped:

```
def _create_temp_file_with_content(content):
    if len(_temp_files) == 0:
        atexit.register(_cleanup_temp_files)
    # Because we may change context several times, try to remember files we
    # created and reuse them at a small memory cost.
    content_key = str(content)
    if content_key in _temp_files:
        return _temp_files[content_key]
    fd, name = tempfile.mkstemp()  # Close the fd -- it was leaving files open
    os.close(fd)
    _temp_files[content_key] = name
    with open(name, 'wb') as fd:
        fd.write(content.encode() if isinstance(content, str) else content)
    return name
```

**Environment**:
- Kubernetes version (`kubectl version`): 1.19.8
- OS (e.g., MacOS 10.13.6): RHEL 7.6
- Python version (`python --version`) 3.7.3
- Python client version (`pip list | grep kubernetes`) 9.0.0

**Comment by roycaihw** [comment]
> After connecting to 200 or so

Are you using the [ENV_KUBECONFIG_PATH_SEPARATOR](https://github.com/kubernetes-client/python-base/blob/dd15ac62636c9ccf1493a02a0bdd5e3a8678c413/config/kube_config.py#L705-L706) to load multiple kubeconfig files (e.g. `load_kube_config(config_file="fileA;fileB;fileC")`)? I wonder if it can be reproduced by copying 200 kubeconfig files (same content, different file names) and load them all at once

**Comment by AWSmith0216** [comment]
I'm not using that to load multiple files. I did try reproducing it by taking a single kubeconfig, copying it a couple hundred times, and loading it in a loop. For some reason that did not reproduce the problem, but I didn't dig into it to determine why.

**Comment by roycaihw** [comment]
Perhaps the the leak was short-circuited when using the same kubeconfig file multiple times: https://github.com/kubernetes-client/python-base/blob/dd15ac62636c9ccf1493a02a0bdd5e3a8678c413/config/kube_config.py#L69-L70

The proposed fix looks good to me. @AWSmith0216 Would you mind opening a PR?
