### ISSUE TITLE
The NetworkingV1beta1IngressSpec tls attribute says it takes a list of NetworkingV1beta1IngressTLS but that class doesn't exist

### ISSUE THREAD

**Issue by drodriguezIE** [kubernetes-client/python#1533]
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/NetworkingV1beta1IngressSpec.md
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/NetworkingV1beta1IngressTLS.md

**Description of the issue (please include outputs or screenshots if possible)**:
I'm trying to implement an ingress using TLS, but although the documentation says it accepts a list of `NetworkingV1beta1IngressTLS` objects, that class can't be imported because it doesn't exist or at least it hasn't been implemented.
![image](https://user-images.githubusercontent.com/54848250/130339047-73ea87ff-73a7-4dd4-9afe-23b65d0f028f.png)
![image](https://user-images.githubusercontent.com/54848250/130339053-84ad8162-7d02-4acd-a078-694c9dd886a2.png)

**Comment by drodriguezIE** [comment]
![image](https://user-images.githubusercontent.com/54848250/130340109-c3bbfbb9-e682-443f-96df-35ce803d74a6.png)

**Comment by roycaihw** [comment]
The NetworkingV1beta1IngressTLS class exists in https://github.com/kubernetes-client/python/blob/v18.20.0/kubernetes/client/models/networking_v1beta1_ingress_tls.py#L21. Could you try if that works?

**Comment by drodriguezIE** [comment]
> The NetworkingV1beta1IngressTLS class exists in https://github.com/kubernetes-client/python/blob/v18.20.0/kubernetes/client/models/networking_v1beta1_ingress_tls.py#L21. Could you try if that works?

It did, thanks a lot, although as a workaround I was doing something like this:

```py
bashCommand = f"kubectl create -f ./test-ssl.yml"
process = subprocess.Popen(shlex.split(bashCommand), stdout=subprocess.PIPE)
print(process.communicate())
```
