### ISSUE TITLE
understanding port forward implementation

### ISSUE THREAD

**Issue by PetruGarstea** [kubernetes-client/python#1534]
Hi,

Giving the port forward object

```
from kubernetes.stream import stream, portforward


    pf = portforward(
         k8s_client_v1.connect_get_namespaced_pod_portforward,
         pod_name,
         name_space,
         ports=port
    )
    
    pf.socket(port)
```

```pf``` is a socket object from ```AF_UNIX``` family.

I need a better understating whether another ```AF_INET``` family socket has to be instantiated in oder to achieve the same functionality as ```kubectl``` client has, ex: ```kubectl port-forward $pod_name $port```

I appreciate in advance if someone could share any snippets of this type of implementation.

At this moment creating port forward object was inspired from [here][1] 

  [1]: https://github.com/kubernetes-client/python/blob/master/examples/pod_portforward.py#L176

**Comment by yliaog** [comment]
Please check out the following tests.

https://github.com/kubernetes-client/python/blob/f07176153e062b3eb94fe9461c25e7a4d0656d4c/kubernetes/e2e_test/test_client.py#L221

https://github.com/kubernetes-client/python/blob/f07176153e062b3eb94fe9461c25e7a4d0656d4c/kubernetes/e2e_test/test_client.py#L360

**Comment by PetruGarstea** [comment]
@yliaog 
thanks for sharing.

After I created **pf** object it doesnt have **sendall()** method

```
sock5432 = pf.socket(5432)
sock5432.sendall(b'Test port 5432 forwarding...')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
BrokenPipeError: [Errno 32] Broken pipe
```

---
python - v3.9
k8s - v18.20.0
