### ISSUE TITLE
watch.stream() find pod deleted event but not container occationally.

### ISSUE THREAD

**Issue by JuHyung-Son** [kubernetes-client/python#1540]
**What happened (please include outputs or screenshots)**:

k8s watch sometimes behave unexpectedly.

I deleted a pod and below is watch response. `event['type']` and `event['object'].status.container_statuses`.
I expect there should be state: {'terminated': {finished_at: something}} , but watch could not catch it and sometimes catch it.
I think it didn't catch something between event type `MODIFIED` and `DELETED` when pod is terminating. So it was not able to fill `state: {'terminated': {}}`

And when I add `termination_grace_period_seconds` option in `PodSpec`, it works as I expected.
Also something weird is `state.waiting.message` is `ContainerCreating` even it is `DELETED` event.

Does watch not guarantee catching all status??

```
MODIFIED
[{'container_id': None,
 'image': 'docker/base:cuda11.1-cudnn8-ubuntu18.04',
 'image_id': '',
 'last_state': {'running': None,
                'terminated': {'container_id': None,
                               'exit_code': 137,
                               'finished_at': None,
                               'message': 'The container could not be located '
                                          'when the pod was deleted.  The '
                                          'container used to be Running',
                               'reason': 'ContainerStatusUnknown',
                               'signal': None,
                               'started_at': None},
                'waiting': None},
 'name': 'name',
 'ready': False,
 'restart_count': 0,
 'started': False,
 'state': {'running': None,
           'terminated': None,
           'waiting': {'message': None, 'reason': 'ContainerCreating'}}}]
DELETED
[{'container_id': None,
 'image': 'docker/base:cuda11.1-cudnn8-ubuntu18.04',
 'image_id': '',
 'last_state': {'running': None,
                'terminated': {'container_id': None,
                               'exit_code': 137,
                               'finished_at': None,
                               'message': 'The container could not be located '
                                          'when the pod was deleted.  The '
                                          'container used to be Running',
                               'reason': 'ContainerStatusUnknown',
                               'signal': None,
                               'started_at': None},
                'waiting': None},
 'name': 'name',
 'ready': False,
 'restart_count': 0,
 'started': False,
 'state': {'running': None,
           'terminated': None,
           'waiting': {'message': None, 'reason': 'ContainerCreating'}}}]
```

**What you expected to happen**:

`watch` catches `container_statuses.state.terminated` like `{finished_at: datetime...}`

**Environment**:
- Kubernetes version (`kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g., MacOS 10.13.6): MacOS
- Python version (`python --version`): 3.8.11
- Python client version (`pip list | grep kubernetes`): 17.17.0

**Comment by roycaihw** [comment]
Does kubectl or client-go return the expected events?
