### ISSUE TITLE
read_namespaced_pod_log() gets stuck after some time

### ISSUE THREAD

**Issue by EvgeniiTitov** [kubernetes-client/python#1546]
Hi!

I have an Azure k8s cluster where I run workflows with Kubeflow. One of the steps in my pipeline manually creates a pod (kubectl apply ...) and then starts reading logs generated by the container running in the created pod and printing them to the stdout so that they appear in the  Kubeflow dashboard.  The way I do it is as follows:
```python3
def get_logs(self):
    response = self.v1.read_namespaced_pod_log(
        name=self.launcher_pod,
        namespace=self.train_job_namespace,
        follow=True,
        _preload_content=False,
        pretty="true"
    )
    response_gen = response.stream(2 ** 6)
    for line in response_gen:
        try:
            decoded_line = line.decode("utf-8")
        except UnicodeDecodeError:
            print(line)
            continue
        print(decoded_line, end="", flush=True)
    print("INFO:: Logs reading thread has finished")
```

**What I expect to happen** - all logs that appear inside the container running in the pod to be successfully extracted and printed to the stdout of the corresponding Kubeflow step (which in turn runs in another pod inside the same cluster).
**What happens** - I get logs for some time but then they get stuck. If I SSH into the container running in the pod whose logs I want to read I can see the logs but I don't get them using the read_namespaced_pod_log() method running in a different pod.

**Anything else we need to know?**:
I've tried many different variations of the read_namespaced_pod_log's and stream's parameters but nothing seems to help - it works for a while (the time that passes before it stops printing logs seems to vary as well) and then it gets stuck. 

**Environment**:
- Kubernetes version (`kubectl version`): 1.20.7
- OS (e.g., MacOS 10.13.6): Alpine Linux v3.14 (3.14.2)
- Python version (`python --version`) 3.9.6
- Python client version (`pip list | grep kubernetes`) 17.17.0

Thank you in advance!

Regards,
Evgenii

**Comment by roycaihw** [comment]
You need to use the watch client to stream the log. Please try this example: https://github.com/kubernetes-client/python-base/pull/93/files#diff-caaa4c6a05b0eef75a61b3c5942aeff261ce4344e51b934efd57227a91586874R83-R91

We should have an example for read_namespaced_pod_log under https://github.com/kubernetes-client/python/tree/master/examples

/kind documentation

**Comment by EvgeniiTitov** [comment]
Hi @roycaihw,

Yes, I did try to use the Watch() object to stream the logs at the beginning but I had the same issues - logs get stuck after some time.

Regards,
Evgenii

**Comment by roycaihw** [comment]
Could you share the code you use to stream the logs with Watch()? And how long do you usually see the stream works before it gets stuck?

**Comment by EvgeniiTitov** [comment]
Sure @roycaihw , this is the approach that uses Watch()

```python
def get_logs(self):
    w = watch.Watch()

    for line in w.stream(self.v1.read_namespaced_pod_log,
                      name=self.launcher_pod,
                      namespace=self.train_job_namespace,
                      timestamps=True):

        print(line, end="\n")
        if "INFO:: Training completed." in line:
            break
```

As you can see we rely on reading logs from the pod (self.launcher_pod) in which we're trying our models to signal when training has completed (we are aware it is not the best approach and working on it). If logs never arrive (get stuck), we never see the "INFO:: Training completed." message, as a result our pipeline step hangs indefinitely.

Funny enough, it happens at different times, sometimes I see more logs, sometimes less. Once in a while, it even works as expected.

**Comment by naor2013** [comment]
@roycaihw any news about this? We also have this issue.

**Comment by brendandburns** [comment]
You probably need to watch repeatedly. The network connection to stream the logs may become interrupted, and I don't think that the `Watch` code handles that.
