### ISSUE TITLE
how to close hostname check

### ISSUE THREAD

**Issue by ycwdaaaa** [kubernetes-client/python#1548]
I tried to close the hostname check like this:

c = Configuration()
c.verify_ssl = False
c.assert_hostname = False
client.Configuration.set_default(c)

but it throw an error TypeError: __init__() got an unexpected keyword argument 'assert_hostname'

**Comment by roycaihw** [comment]
I tried to reproduce with a v20.13.0 client and couldn't get the error. What client version did you use, and could you try using the latest version? Also I noticed that `c = Configuration()` should be `c = client.Configuration()`.

Let me know if you still hit this issue.

/close
