### ISSUE TITLE
Can these interfaces provide the same capabilities as "kubectl apply -k"？

### ISSUE THREAD

**Issue by ChenhanXmu** [kubernetes-client/python#1555]
**What is the feature and why do you need it**:
Production requirements

**Describe the solution you'd like to see**:
I want to achieve the same ability as "kubectl apply -k" through the interface, what should I do?

**Comment by roycaihw** [comment]
IIUC kubectl achieves it by compiling kustomize as a part of kubectl. This Python client doesn't provide the capability. 

/close

**Comment by coderanger** [comment]
This is incorrect, any client library can use the Server Side Apply APIs now.

**Comment by imageschool** [comment]
> This is incorrect, any client library can use the Server Side Apply APIs now.

how do you use it in the current python client library?

**Comment by coderanger** [comment]
> > This is incorrect, any client library can use the Server Side Apply APIs now.
> 
> how do you use it in the current python client library?

Use the `patch` client method for the type with a content type header set to `application/apply-patch+yaml`. You must set a field manager (optional for other patch types and update) and you will usually want to set force=true.

**Comment by imageschool** [comment]
@coderanger Thanks for the reply!

It seems like there is no such content-type written in the doc
(https://github.com/kubernetes-client/python/blob/release-8.0/kubernetes/docs/AppsV1Api.md#patch_namespaced_deployment)

but, i was able to find it in the code (`patch_namespaced_deployment_scale_with_http_info()` in `apps_v1_api.py`)

How can I actually specify content type '`application/apply-patch+yaml`' when calling `patch_namespaced_deployment()` from `client.AppsV1Api()` ?

![image](https://user-images.githubusercontent.com/29969006/146705405-50d82bfe-b715-4f2a-941f-a6db781c125e.png)

**Comment by coderanger** [comment]
That you'll have to take up with the Python client library team.

**Comment by imageschool** [comment]
> That you'll have to take up with the Python client library team.

So is it correct that it is do-able but hasn't been implemented in the client library?

**Comment by coderanger** [comment]
There is nothing specific to implement client-side, it's a kube-apiserver call. That's why it's called "server side apply".

**Comment by imageschool** [comment]
> There is nothing specific to implement client-side, it's a kube-apiserver call. That's why it's called "server side apply".

Sorry that I am quite new at this, so to clarify, is the below true ?

- At first, it is available through kubectl command (client-side)
- It is not available on the python client library (client-side)
- It is available in kube-apiserver (server-side)

**Comment by imageschool** [comment]
> There is nothing specific to implement client-side, it's a kube-apiserver call. That's why it's called "server side apply".

Right, thanks.

**Comment by roycaihw** [comment]
Oh I thought the feature request was about kustomize integration:
```
$ kubectl apply --help
  -k, --kustomize='': Process a kustomization directory.
```

If it's about server-side apply, I agree we should support it: https://github.com/kubernetes-client/python/issues/1430

**Comment by coderanger** [comment]
I got sent here by a help request on Slack from someone assuming you meant apply was not supported, beyond that I defer to y'all :)

**Comment by roycaihw** [comment]
Thanks for the clarification @coderanger!
