### ISSUE TITLE
Github frequently refuses to render CoreV1Api documentation

### ISSUE THREAD

**Issue by partcyborg** [kubernetes-client/python#1557]
Right now all attempts to view the `CoreV1Api` documentation result in this:

![kubernetes-client-docs](https://user-images.githubusercontent.com/41255671/135179935-8edeca53-8d94-44d5-909e-8ef25ec2a833.png)

As the error message states, the reason for this is that the markdown file is too large.  Unfortunately, this makes it difficult enough to be effectively impossible to read the documentation, as you can no longer use the tag links to find what you are looking for.

**Comment by roycaihw** [comment]
This seems to be a general issue that happens to all the generated clients, e.g. the [Java client](https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/CoreV1Api.md).

It would be great if we can split the file into smaller pieces, or find a site that can host files this large. And it would be great if we can involve folks from other repos to solve it for everyone. 

/help

**Comment by roycaihw** [comment]
Thanks for the detailed thoughts!

> 1. We can split bigger MDs into 2 or more files as you suggest

I can imagine automating the split, change of links, etc. But it only solves one bad UX and it's not quite maintainable long term. I would accept a PR though :(

> maybe one file per API group?

CoreV1 is one gigantic & legacy API group. If Kubernetes removes some deprecated APIs / splits it up (which may be slowly happening over the years) that works for us. 

> 3. Use GitHub Wikis - I’ve checked and the biggest MD can be rendered, take a look: https://github.com/tomplus/kubernetes_asyncio/wiki/CoreV1Api It’s possible to prepare GitHub actions to create such wiki pages.

The Wiki page sometimes worked for me and sometimes didn't. I really like it though. Regardless of the rendering issue, I think it helps if we have a centralized place for installation, examples, API doc, contribution, etc. 

> 4. Use Python specific solutions like https://readthedocs.org/. It bases on Sphinx, which we already have configured (docs/ in the root directory).

Yes we have https://kubernetes.readthedocs.io/en/latest/ published from [here](https://github.com/kubernetes-client/python/tree/master/doc), but it seems we never published the API docs to it?

**Comment by michaelkaye** [comment]
/remove-lifecycle stale

Checked today that CoreV1API documentation as linked from [here](https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md) to [here](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#connect_delete_namespaced_pod_proxy) still not readable due to raw file size.

**Comment by michaelkaye** [comment]
/remove-lifecycle stale

Checked today that CoreV1API documentation as linked from [here](https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md) to [here](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#connect_delete_namespaced_pod_proxy) still not readable due to raw file size.

If python client should not have documentation, please comment that that is expected behavior and close issue.

If python client should have documentation, please could someone make the robot not auto-close as stale.

**Comment by Rishit-dagli** [comment]
@roycaihw @michaelkaye

I faced the same issue today and came across this issue. Following that, I have got a GitHub action running for my repository to do this and later today I will make a PR to do this in this repository.

@roycaihw 
> The Wiki page sometimes worked for me and sometimes didn't. I really like it though. Regardless of the rendering issue, I think it helps if we have a centralized place for installation, examples, API doc, contribution, etc.

/assign

**Comment by boldandbusted** [comment]
Howdy. So, I still get the issue in GitHub. I looked at this repo's Wiki, and it seems to be empty. So, I think this issue still is present?

**Comment by Rishit-dagli** [comment]
@boldandbusted the action runs only when a commit is made to the docs, since we didn't want to run it on every single commit

**Comment by boldandbusted** [comment]
> @boldandbusted the action runs only when a commit is made to the docs, since we didn't want to run it on every single commit
> 

Thanks for your reply. The Wiki tab on this repp is actually empty when I look at it. So, has it ever been run? Or is there some permissions issue whereby I cant see the resulting product? Cheers.

**Comment by Rishit-dagli** [comment]
If you see the actions tab it has actually never been run

**Comment by boldandbusted** [comment]
Is there a new issue covering this? :)
