### ISSUE TITLE
portforward does not work on Windows (Reason: module 'socket' has no attribute 'AF_UNIX')

### ISSUE THREAD

**Issue by datacart** [kubernetes-client/python#1558]
I am working on getting port forwarding working, but it does not work on python installed on Windows.

When following the example like in https://github.com/kubernetes-client/python/blob/master/examples/pod_portforward.py, you are presented with this error:

```
kubernetes.client.exceptions.ApiException: (0)
Reason: module 'socket' has no attribute 'AF_UNIX'
```
I tracked this down to kubernetes.stream.ws_client._Port.__init__

The socketpair is being explicatly created with socket.AF_UNIX, which will never work on Windows. The comment tries to explain why the socketpair needs to be AF_UNIX, but I dont really follow the logic.

I removed all the explicate arguments, and it seems to all work (although I did not try on a linux or Mac system.)

**Comment by aagten** [comment]
@datacart are you working on this? Otherwise I might change that line.

**Comment by datacart** [comment]
@aagten If you want me to submit a PR, I can certainly do that, but since I have not contributed to this project as of yet, it might be simpler if you do it.

**Comment by Omega-Centauri-21** [comment]
Did you check if the firewall is blocking it? Maybe same ports are being assigned or the router must have DMZ enabled
