### ISSUE TITLE
Can't push down label selectors to list namespaced pods query

### ISSUE THREAD

**Issue by westernspion** [kubernetes-client/python#1559]
**What happened (please include outputs or screenshots)**:
I can't use the label selector in CoreV1Api.list_namespaced_pod. Neither match_labels or match_expressions in the V1labelSelector work. I keep getting this unable to parse requirement error.
I don't see any reason this shouldn't work 

```
selectors = client.V1LabelSelector(match_expressions=match_labels={'app':'superapp'})
#{'match_expressions': None, 'match_labels': {'app', 'superapp'}}
v1.list_namespaced_pod(namespace='my-namespace', watch=False, label_selector=selectors)

```

```
ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '31f354f6-6baf-43f8-b0c7-5edc9fc18d06', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Fri, 01 Oct 2021 13:29:25 GMT', 'Content-Length': '423'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"unable to parse requirement: invalid label key \"{'matchLabels':\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')","reason":"BadRequest","code":400}
```

**What you expected to happen**:
That I can push down label selectors to the list namespaced pods query

**How to reproduce it (as minimally and precisely as possible)**:
See code above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
-Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- OS - Docker image - tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim
- Python version 3.8.8
- Python client version  18.20.0

**Comment by westernspion** [comment]
It should be fairly straightforward to test the API call with curl, or with a python requests snippet. If I have time I'll test it inspect it. The error is definitely coming from the Kubernetes API - so it's something not-agreeable with what the python client is doing.

**Comment by dmitrybabanovforreal** [comment]
Just for those coming here for the same question, as I did: you can avoid this error by passing a string to `label_selector` instead of a `V1LabelSelector` object.

Like this: `await v1core.list_service_for_all_namespaces(label_selector='helm.sh/chart=postgresql-12.1.3')`
