### ISSUE TITLE
Deleting a nodeSelector via a patch update doesn't work

### ISSUE THREAD

**Issue by ryanpeach** [kubernetes-client/python#1570]
**What happened (please include outputs or screenshots)**:

Nothing (it doesn't actually do anything).

**What you expected to happen**:

The removal of the nodeSelector "kubeversion"

**How to reproduce it (as minimally and precisely as possible)**:

```python
from kubernetes import client
def remove_kubeversion_nodeselector(deployment_name: str, namespace: str) -> None:
    api = client.AppsV1Api()
    body = api.read_namespaced_deployment(deployment_name, namespace)
    if body.spec.template.spec.node_selector is None:
        return

    if 'kubeversion' in body.spec.template.spec.node_selector:
        del body.spec.template.spec.node_selector["kubeversion"]
        
    api.patch_namespaced_deployment(
        name=deployment_name,
        namespace=namespace,
        body=body,
        pretty="true",
    )
```

**Environment**:
- Kubernetes version (`kubectl version`): 1.18
- OS (e.g., MacOS 10.13.6): MacOS latest
- Python version (`python --version`) 3.9.7
- Python client version (`pip list | grep kubernetes`) 18.20.0

**Comment by lexisworkingout** [comment]
Hi, have you solved this problem yet? I also can't change spec.nodeSelector using patch_namespaced_node api.
