### ISSUE TITLE
Update OpenAPI Generator to v5.3.0

### ISSUE THREAD

**Issue by palnabarun** [kubernetes-client/python#1589]
**What is the feature and why do you need it**:

OpenAPI Generator has got some improvements that we should pull in. Doing that will resolve issues like #859, #1131.

**Risks**

There have a lot!! of changes since v4.3.0. We would need to go through most of those changes through the release notes and see if anything can break the client.

**Describe the solution you'd like to see**:

Update OpenAPI Generator to v5.3.0 in https://github.com/kubernetes-client/gen/blob/a3aef4de7a1d5dab72021aa282fffd8bc8a022ca/openapi/python.sh#L48

**Comment by roycaihw** [comment]
/help

@itaru2622 Are you willing to drive the upgrade? 

cc @roycaihw

**Comment by itaru2622** [comment]
@roycaihw You made me so suprised. Unfortunately I don't have much time now, so it is hard to drive this issue solving. but I think I can help you.

**Comment by idsvandermolen** [comment]
One of the interesting things I think was introduced in OpenAPI Generator 5 was improved validation of types, for example the enum type of `protocol` in `ContainerPort` (https://github.com/kubernetes-client/python/blob/master/kubernetes/client/models/v1_container_port.py#L169) currently isn't validated to have a correct value. When generated with version 5 afaict it will be validated to contain one of the correct enumeration values (`SCTP`,`TCP`,`UDP`).
If kubernetes-client/python get's this kind of validation, it will catch issues early (shift left) and when used to generate manifests, there's no more need for `kubeval` or `kubeconform` for validation.

**Comment by itaru2622** [comment]
@idsvandermolen yes, there are some improvement in openapi-generator.

to get benefit of those improvements on validation, it needs to update openapi defenition which is managed by server side at https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json

it may take  to be adjusted.

**Comment by rosscdh** [comment]
So it sounds like we just have to manually patch the python k client in the mean time?
https://github.com/kubernetes-client/python/issues/740
