### ISSUE TITLE
Target_Port parameter type reference is a broken link

### ISSUE THREAD

**Issue by rezuma** [kubernetes-client/python#1603]
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1ServicePort.md

**Description of the issue (please include outputs or screenshots if possible)**:
The documentation of the V1ServicePort defines target_port type as object. The link on the word object links is broken so the audience cant understand what that object is
This is the link https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/.md on the object word

Thanks

**Comment by roycaihw** [comment]
`target_port` is an [IntOrString](https://github.com/kubernetes/kubernetes/blob/d3bd8a3aab79a61aaf5281dd302941cff440462b/staging/src/k8s.io/api/core/v1/types.go#L4446).

Fundamentally this is a shortcoming of Kubernetes using OpenAPI v2, which cannot properly express the schema of an "int or string" type, nor let us generate the correct client-side validation. People had put workarounds for the client-side validation (https://github.com/kubernetes-client/gen/pull/26, https://github.com/kubernetes-client/gen/pull/30), but the documentation became somewhat broken (also see [Java example](https://github.com/kubernetes-client/java/blob/738dc9560636b4e18db5026f58a6c397331f0b05/kubernetes/docs/V1ServicePort.md))

A short-term fix for the Python client can be appending the [documentation of IntOrString](https://github.com/kubernetes/kubernetes/blob/d3bd8a3aab79a61aaf5281dd302941cff440462b/staging/src/k8s.io/apimachinery/pkg/util/intstr/intstr.go#L31-L34) to [v["description"]](https://github.com/kubernetes-client/gen/blob/ca817f53d452ddcbc0febf4138ee478984876157/openapi/preprocess_spec.py#L414-L415). Other suggestions are welcome.

/help

**Comment by roycaihw** [comment]
@jefftree I wonder if you know any effort to change the schema of IntOrString when [Kubernetes goes OpenAPI v3](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2896-openapi-v3/README.md). Currently it looks like this:
```
"io.k8s.apimachinery.pkg.util.intstr.IntOrString": {                                                                                
  "description": "IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.",
  "format": "int-or-string",
  "type": "string"                                                                                                                  
},
```

**Comment by Jefftree** [comment]
OpenAPI V3 should be able to use the new [oneOf](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) annotation and correctly indicate the type as oneOf {int, string}. 

Thanks for bringing this up, I was actually unaware of this struct and originally thought all IntOrString operations went through the x-int-or-string extension. Will add it to the agenda for OpenAPI :)

**Comment by Aayush987** [comment]
Hi i am new to kubernetes but i want to try to fix this issue .Can somebody explain what to do here?

**Comment by Jefftree** [comment]
Hi, just want to give a quick update around OpenAPI V3. OpenAPI v3 is now beta in kubernetes and will be enabled by default. The spec is split by group/version and the discovery endpoint can be found at `/openapi/v3`. 

We also have generated files committed to the k/k repo split by group version. IntOrString is properly defined in OpenAPI V3 (https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/v3/apis__apps__v1_openapi.json#L6034-L6046), let me know if I can provide any help with integration.

**Comment by Mohdcode** [comment]
Hello! I want to know if anyone working on this issue.

**Comment by Mohdcode** [comment]
could you tell me the issue as it's my first time on an open source project? as I couldn't understand the upper conversation cuz it's little cryptic to me.

**Comment by Ashutosh-20** [comment]
I want to start contributing in this project. And I am a total beginner. So it would be great if u could suggest some resources to start with.
