### ISSUE TITLE
WSClient.update(): select function returns empty reader although there's still data missing to be received

### ISSUE THREAD

**Issue by rogerhil** [kubernetes-client/python#1604]
**What happened (please include outputs or screenshots)**:
This issue is intermittent and it happens especially when there is a lot of data returned as the output from a command execution. I've been stuck with this issue for months and I kind of ignored it for a while until now, when the past few weeks, I've been trying to really find a way to fix it myself, but I unfortunately can't.

To summarize, see below the pdb breakpoint when/where the issue happens. The breakpoint pdb.set_trace() is actually set in my code in the loop that reads the stdout channel. I've also put a print inside the `websocket._abnf.frame_buffer.recv_frame()` method to show the payload's length, payload[-50:], and header:

<img width="1159" alt="Screenshot 2021-10-26 at 22 34 11" src="https://user-images.githubusercontent.com/611173/138965519-aa8fdf8e-e433-4873-b243-d969c92cc7bd.png">

As seen above, I expect to see that last piece of the payload to be returned, but the loop keeps on forever trying to peek further data. This method `WSClient.peek_stdout()` calls `WSClient.update()` that never reads anything as the select never returns any potential readers (lines 8-10):

>       1     def update(self, timeout=0):
>       2        """Update channel buffers with at most one complete frame of input."""
>       3        if not self.is_open():
>       4           return
>       5        if not self.sock.connected:
>       6            self._connected = False
>       7            return
>       8        r, _, _ = select.select((self.sock.sock, ), (), (), timeout)
>       9        if r:
>      10            op_code, frame = self.sock.recv_data_frame(True)
>      11            if op_code == ABNF.OPCODE_CLOSE:
>      12                self._connected = False
>      13                return
>      14            elif op_code == ABNF.OPCODE_BINARY or op_code == ABNF.OPCODE_TEXT:
>      15                data = frame.data

**What you expected to happen**:
I expect to get the full output from the command that is executed via `WSClient.write_stdin()` method.

**How to reproduce it (as minimally and precisely as possible)**:
The issue is intermittent, and it happens more frequently when a lot of output is returned from a command execution, for instance, when we try to run "`cat file`", where the file has over 5MB. It can happen even with a very small output size, just less often though.
Also, it will occur even more frequently if I run a command like `cat file; echo STATUS_CODE=$?`. The output of the second echo command gets "kind of lost". It can still be read, but the select() function tells that there's nothing to read :(.

I wrote this tiny KubeExecSession and KubeShell that can be used to reproduce the issue, see the usage below:

```
with KubeExecSession('pod_name', 'container_name', 'namespace') as kube_shell:
    status, out, err = kube_shell.run('cat /tmp/file_over_5mb.log')
```

The KubeExecSession context manager will keep the connection opened in the container, thus we can execute as many commands as we want in the context manager block. The kube_shell object returned by KubeExecSession is another object that can execute any command and return the command status code, stdout and stderr.

The full code is shown down below. Please note that I kept the `pdb.set_trace()` in case the issue happens when the loop keeps on and on over 50000 iterations. Please bear in mind that the issue is intermittent and you might have to try several times until the pdb traceback is caught. Also, try different file sizes, or different commands to see.
**Code below:**

```
import re

from kubernetes import config, client
from kubernetes.stream import stream
from kubernetes.config import ConfigException


STATUS_CODE_KEY = '__WSCLIENT_STATUS_CODE__'
STATUS_CODE_REGEX = re.compile(r'^%s=(\d+)$' % STATUS_CODE_KEY)


class KubeExecSession:

    def __init__(self, pod, container, namespace):
        self.pod = pod
        self.container = container
        self.namespace = namespace
        self.ws_client = None

    def __enter__(self):
        try:
            config.load_incluster_config()
        except ConfigException:
            config.load_kube_config()
        api = client.CoreV1Api()
        self.ws_client = stream(api.connect_get_namespaced_pod_exec, self.pod,
                                self.namespace, container=self.container,
                                stdout=True, stderr=True, stdin=True,
                                command=["/bin/bash"], tty=False,
                                _preload_content=False)
        return KubeShell(self.ws_client)

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.ws_client.close()


class KubeShell:

    def __init__(self, ws_client):
        self.ws_client = ws_client

    def run(self, cmd):
        self.ws_client.write_stdin('%s\n SC=$?; printf "\n%s=$SC\n"\n' %
                                   (cmd, STATUS_CODE_KEY))
        self.ws_client.update(timeout=1)
        out = ''
        err = ''
        status = -1
        status_got = False
        threshold_count_for_debug = 0
        while self.ws_client.is_open():
            threshold_count_for_debug += 1
            if threshold_count_for_debug > 50000:
                # in case it gets stuck, we can debug to see what's going on
                import pdb; pdb.set_trace()
                threshold_count_for_debug = 0

            if self.ws_client.peek_stdout():
                output = self.ws_client.read_stdout(timeout=3600)
                lines = output.split('\n')
                for line in lines:
                    if line:
                        match = STATUS_CODE_REGEX.search(line.strip())
                        if match:
                            status = int(match.group(1))
                            status_got = True
                            break
                    out += "%s\n" % line
                if status_got:
                    break
            if self.ws_client.peek_stderr():
                err = self.ws_client.read_stderr(timeout=3600)
        return status, out, err


def main():
    with KubeExecSession('pod', 'container', 'namespace') as kube_shell:
        status, out, err = kube_shell.run('cat /tmp/file_over_5mb.log')


if __name__ == '__main__':
    main()

```

**Anything else we need to know?**:
Again, the issue is intermittent, it happens more frequently when 2 commands are executed in sequence, like separate by ";" or using &&. Also, when the output is a big one and/or there are pauses in the output display until the command execution finishes.

If I put a "sleep 0.1" in between the commands (real command; **sleep 0.1**; echo STATUS_CODE=$?), the issue happens less often. I used this approach in the code for a while to alleviate the problem. But now I want to definitely fix this as things are going bad in production now.

Another thing: I'd love to know if there's another way of getting the return code from a command execution. Currently, I'm getting it via "`$?`". In my specific case, I need to keep the connection open, and for this reason, I use _preload_content as False and I will never get the return code as part of the json response (when _preload_content=True). I need to somehow get this return code myself. If there's another suggestion, I will be very grateful.

**Environment**:
- Kubernetes version (`kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"9e5f344f6cdbf2eaa7e450d5acd8fd0b7f669bf9", GitTreeState:"clean", BuildDate:"2021-05-19T04:34:27Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS: Ubuntu 20.04.3 LTS or MacOS BigSur 11.3.1 or Suse Linux.
- Python version (`python --version`): 3.8.7
- Python client version (`pip list | grep kubernetes`): 11.0.0

**Comment by roycaihw** [comment]
Thanks for the detailed report!

/assign @rogerhil 
cc @yliaog

**Comment by btruong66** [comment]
@rogerhil  Hello, it seems like a PR wasn't created for your solution. Just curious on if your solution continued to work?
