### ISSUE TITLE
Dynamic Provisioning not creating EFS access point with given privileges

### ISSUE THREAD

**Issue by swarnaswaminathan** [kubernetes-client/python#1611]
I wanted to dynamically provision EFS storage using the EFS CSI driver.
Steps followed:
1. Manually created an EFS storage from the AWS console.
 2. Manually created a storage class with below yaml.
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: efs-sc-range-test
      provisioner: efs.csi.aws.com
      parameters:
        provisioningMode: efs-ap
        fileSystemId: fs-5xxxxxxc
        directoryPerms: "700"
        uid: "0"
        gid: "0"
        basePath: "/dynamic_provisioning"

3. Created a PVC using the yaml passed as the body to the below method.
       from kubernetes import client, config, watch
       coreapi = client.CoreV1Api()
       dep = yaml.safe_load(file)
       coreapi.create_namespaced_persistent_volume_claim(
                namespace=namespace, body=dep, **kwargs)
                
       The yaml file for PVC is as below:
       
       `apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: efs-claim-range-test
          namespace: xxxxxx
        spec:
          accessModes:
            - ReadWriteMany
          storageClassName: efs-sc-range-test
          resources:
            requests:
              storage: 5Gi
        ---
        apiVersion: v1
        kind: Pod
        metadata:
          name: efs-app
          namespace: xxxxxxx
        spec:
          containers:
            - name: app
              image: centos
              command: ["/bin/sh"]
              args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
              volumeMounts:
                - name: persistent-storage
                  mountPath: /data
          volumes:
            - name: persistent-storage
              persistentVolumeClaim:
                claimName: efs-claim-range-test`

Dynamic provisioning creates a persistent volume claim (PVC) and uses the PVC to dynamically provision a persistent volume (PV). On Creating a PVC, kubernetes requests EFS to create an Access Point in a file system which will be used to mount the PV.

So, the below storage class was created:
---------------SC-------------------------
Name:            efs-sc-range-test
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"efs-sc-range-test"},"parameters":{"basePath":"/dynamic_provisioning","directoryPerms":"700","fileSystemId":"fs-57c96c2c","gid":"0","provisioningMode":"efs-ap","uid":"0"},"provisioner":"efs.csi.aws.com"}

Provisioner:           efs.csi.aws.com
Parameters:            basePath=/dynamic_provisioning,directoryPerms=700,fileSystemId=fs-57c96c2c,gid=0,provisioningMode=efs-ap,uid=0
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>

And the below PVC, PV and access point got created by the dynamic provisioning:

---------------PVC-------------------------
Name:          efs-claim-range-test
Namespace:     swarna-ns
StorageClass:  efs-sc-range-test
Status:        Bound
Volume:        pvc-7aa999f3-104e-45aa-90eb-7b4914551877
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: efs.csi.aws.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       efs-app
Events:

---------------PV-------------------------
Name:            pvc-7aa999f3-104e-45aa-90eb-7b4914551877
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: efs.csi.aws.com
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    efs-sc-range-test
Status:          Bound
Claim:           swarna-ns/efs-claim-range-test
Reclaim Policy:  Delete
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        5Gi
Node Affinity:   <none>
Message:
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            efs.csi.aws.com
    FSType:
    VolumeHandle:      fs-57c96c2c::fsap-033ae282addde997f
    ReadOnly:          false
    VolumeAttributes:      storage.kubernetes.io/csiProvisionerIdentity=1635395013246-8081-efs.csi.aws.com
Events:                <none>

---------------FSAP-------------------------
![image](https://user-images.githubusercontent.com/93309275/139203505-ad4e2e40-3798-41db-9798-84f3fd5b33de.png)

The access point created have:
User ID as 50000
Group ID as 50000

**I expected User ID and Group ID to be set as "0", instead it was set to 50000.

 What needs to be done so that the user id and group id gets set to 0.**

**Environment**:
- Kubernetes version (`kubectl version`):
   Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g., MacOS 10.13.6):
   Ubuntu 20.04.2 LTS
- Python version (`python --version`)
  Python 3.8.10 
- Python client version (`pip list | grep kubernetes`)
   kubernetes         12.0.1

**Comment by yliaog** [comment]
i don't think it is python client specific issue. I think you will get the same if you use kubectl.

For the specific question below, 
**I expected User ID and Group ID to be set as "0", instead it was set to 50000.

What needs to be done so that the user id and group id gets set to 0.**

you may check out the 
https://serverfault.com/questions/906083/how-to-mount-volume-with-specific-uid-in-kubernetes-pod, https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#access-control
hopefully it helps.

**Comment by swarnaswaminathan** [comment]
> i don't think it is python client specific issue. I think you will get the same if you use kubectl.
> 
> For the specific question below, **I expected User ID and Group ID to be set as "0", instead it was set to 50000.
> 
> What needs to be done so that the user id and group id gets set to 0.**
> 
> you may check out the https://serverfault.com/questions/906083/how-to-mount-volume-with-specific-uid-in-kubernetes-pod, https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#access-control hopefully it helps.

Thanks for the response.
Yes this feature to use uid and gid is yet to be released. Checked on the aws-efs-csi-driver github.
