### ISSUE TITLE
GCP auth-provider does not respect the token-key and expiry-key parameter

### ISSUE THREAD

**Issue by Mariappan** [kubernetes-client/python#1612]
**What happened (please include outputs or screenshots)**:

Python client crashes in the following path

```
  File "/app/helm.py", line 70, in health_check
    config.load_kube_config()
  File "/usr/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 819, in load_kube_config
    loader.load_and_set(config)
  File "/usr/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 589, in load_and_set
    self._load_authentication()
  File "/usr/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 287, in _load_authentication
    if self._load_auth_provider_token():
  File "/usr/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 302, in _load_auth_provider_token
    return self._load_gcp_token(provider)
  File "/usr/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 359, in _load_gcp_token
    self._refresh_gcp_token()
  File "/usr/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 368, in _refresh_gcp_token
    credentials = self._get_google_credentials()
  File "/usr/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 240, in _refresh_credentials
    return _refresh_credentials_with_cmd_path()
  File "/usr/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 233, in _refresh_credentials_with_cmd_path
    return commandTokenSource.token()
  File "/usr/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 181, in token
    token=data['credential']['access_token'],
```

We are using an external program [`vault-k8s-helper`](https://github.com/basisai/vault-k8s-helper) to load the gcp access-token and expiry from vault gcp provider.
vault-k8s-helper returns the following json
```
{
  "token_expiry": "DATE",
  "token": "TOKEN"
}
```

and our kube-config file with gcp auth-provider and external command is as follows,
```
- name: gcp-user
  user:
    auth-provider:
      config:
        cmd-args: gke --vault-token=XXX --vault-address=https://vault.app.ai
          --vault-ca-cert=/kube/vault.pem gcp-span-staging-workload/static-account/deployment/token
        cmd-path: /usr/bin/vault-k8s-helper
        expiry-key: '{.token_expiry}'
        token-key: '{.token}'
      name: gcp
```

**What you expected to happen**:
Kubectl and other go clients are able to load the above kube config and refresh token properly using `expiry-key` and `token-key` 's jsonpath
Similar to other client, python client should also be able to load config successfully and refresh tokens using custom json-path in `expiry-key` and `token-key`.

**How to reproduce it (as minimally and precisely as possible)**:
Can be repro minimally using the following helper program and gcp auth-provider config:

```bash
[maari@dev testpythonclient]$ cat /usr/local/bin/vault-helper
#!/usr/bin/sh
gcloud config config-helper --format=json | jq '{token: .credential.access_token, token_expiry: .credential.token_expiry}'
```

kube_config:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXXXXXXXXXX
    server: https://XXXXXXXXXXX
  name: canary-dev-cluster
contexts:
- context:
    cluster: canary-dev-cluster
    user: canary-dev-user
  name: canary-dev
current-context: canary-dev
kind: Config
preferences: {}
users:
- name: gcp-user
  user:
    auth-provider:
      config:
        cmd-path: /usr/local/bin/vault-helper
        expiry-key: '{.token_expiry}'
        token-key: '{.token}'
      name: gcp
```

Fails:
KUBECONFIG=${PWD}/kube_config python -c 'from kubernetes import config; config.load_kube_config()'

Succeeds:
KUBECONFIG=${PWD}/kube_config kubectl get pods

**Anything else we need to know?**:

Root-cause:
The token path and expiry path is hard-coded, and tokenKey/expiryKey is not used while parsing the cmd output data:
https://github.com/kubernetes-client/python-base/blob/master/config/kube_config.py#L182

**Proposal:**
There are two ways we can fix this:
* Use a json-path library like  `https://github.com/h2non/jsonpath-ng` to parse the JSON path properly in token-key and expiry-key
* Write a minimal logic to parse simple json paths like: `.credential.access-token`  which might be enough for most situations like
```python
data = json.loads(data_str)

for i in tokenKey.strip("{.}").split("."):
    data = data[i]
```

I could take a stab at it if the above proposal looks fine.

**Environment**:
- Kubernetes version (`kubectl version`): 
 ```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"2021-10-28T06:55:39Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.301", GitCommit:"17ad7bd6afa01033d7bd3f02ce5de56f940a915d", GitTreeState:"clean", BuildDate:"2021-08-24T05:18:54Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g., MacOS 10.13.6): Linux 5.14.14-arch1-1
- Python version (`python --version`): 3.9.7
- Python client version (`pip list | grep kubernetes`): `18.20.0`

**Comment by roycaihw** [comment]
Thanks for the detailed report. 

> The token path and expiry path is hard-coded, and tokenKey/expiryKey is not used while parsing the cmd

I didn't expect different auth plugins to write data to different paths. Do kubectl/client-go have a complete list of all paths that need to be supported?
