### ISSUE TITLE
Pod Log: Get logs on specific date

### ISSUE THREAD

**Issue by zhb1207** [kubernetes-client/python#1613]
How could I get logs on a specific day using read_namespaced_pod_log, for example, get the logs on 2021.11.1. From the doc, using 'since_seconds' gets logs from a timestamp in the past, and using 'tail_lines' gets contents from the end of logs, but it seems there is not a parameter used to get logs within a time RANGE. In this case, do I have to process the logs by myself?

**Comment by roycaihw** [comment]
cc @yliaog

**Comment by yliaog** [comment]
that's correct, it has to be processed on your side.
