### ISSUE TITLE
client 20.y.z symlink is available but broken

### ISSUE THREAD

**Issue by pdp10** [kubernetes-client/python#1614]
**Link to the issue (please include a link to the specific documentation or example)**:

- See: https://github.com/kubernetes-client/python 

**Description of the issue (please include outputs or screenshots if possible)**:

Regarding the entry: 
`client 20.y.z: Kubernetes 1.19 or below (+-), Kubernetes 1.20 (✓), Kubernetes 1.21 or above (+-)`
The provided symlink to `https://pypi.org/project/kubernetes/20.11.0/` does not work.

**Comment by yliaog** [comment]
the link should be: https://pypi.org/project/kubernetes/20.11.0a1/

**Comment by pdp10** [comment]
Thanks your swift reply.
