### ISSUE TITLE
How to cover the V1Job object to standard Job Yaml File ?

### ISSUE THREAD

**Issue by Guanyan1996** [kubernetes-client/python#1615]
**What is the feature and why do you need it**:
Hi , I want to dump the V1Job object to yaml file  to debug the error in local data. Then I can use kubectl apply -f xxx.yaml for debug.
**Describe the solution you'd like to see**:
I don't find the way can cover the object to yaml . plz

**Comment by roycaihw** [comment]
You can use the `sanitize_for_serialization` method, e.g. https://github.com/kubernetes-client/python/issues/1380#issuecomment-781458859, https://github.com/kubernetes-client/python/issues/1117#issuecomment-939957007

/close

**Comment by Guanyan1996** [comment]
thx very much  . @roycaihw
