### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed when try to connect to aks

### ISSUE THREAD

**Issue by roquesao** [kubernetes-client/python#1622]
**What happened (please include outputs or screenshots)**:
when trying to list all the secrets from all namespaces  I'm getting the error:

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed 

**What you expected to happen**:
list all the secrets
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

if I try to use the requests library hitting to endpoint cluster I don't have the ssl error 

**Environment**:
- Kubernetes version (`kubectl version`): 1.20.9
- OS (e.g., MacOS 10.13.6): ubuntu 18.0.4
- Python version (`python --version`) 3.6.9
- Python client version (`pip list | grep kubernetes`): 19.15.0

**Comment by roycaihw** [comment]
Not sure if it's an issue with AKS. You can try skipping the SSL verification. Here is an example: https://github.com/kubernetes-client/python/issues/36#issuecomment-569071516
