### ISSUE TITLE
V1NodeCondition

### ISSUE THREAD

**Issue by liyinxin** [kubernetes-client/python#1625]
Dear community:
   I want to know the V1NodeCondition.type is the real-time status of the node ? I test the type with these:
`zailushang@zailushang-inspiron-3670:~/CloudEdgeProjectMANO/NFs$ cat cloudCore.py`
`#!/usr/bin/env python`
`# coding=utf-8`
`from kubernetes import client,config`
`# configs can be set in Configuration class directly or using helper utility`
`config.load_kube_config()`
`v1 = client.CoreV1Api()`
`res = v1.read_node_status("ubuntu")`
`NodeConditions = res.status.conditions`
`for condition in NodeConditions:`
   ` print(condition.type)`
`zailushang@zailushang-inspiron-3670:~/CloudEdgeProjectMANO/NFs$ python cloudCore.py `
`NetworkUnavailable`
`MemoryPressure`
`DiskPressure`
`PIDPressure`
`Ready`

I want to know if there has an api which can read nodes status in real-time ?
**Environment**:
- Kubernetes version (`kubectl version`):1.22.3
- OS (e.g., MacOS 10.13.6):ubuntu 18.04
- Python version (`python --version`):3.6.9
- Python client version (`pip list | grep kubernetes`):20.11.0a1

**Comment by liyinxin** [comment]
I have solve it. Thanks

**Comment by roycaihw** [comment]
Hi @liyinxin, glad that you found the solution :) It would be great if you could also share what the solution was here. 

/close

**Comment by liyinxin** [comment]
the condition.type are five types: 
NetworkUnavailable
MemoryPressure
DiskPressure
PIDPressure
Ready
so it's no error, if you want to know the status of nodes, you can use the condition.status .

**Comment by roycaihw** [comment]
Thanks @liyinxin!
