### ISSUE TITLE
async creation of custom resources (CR) using the CRD is failing

### ISSUE THREAD

**Issue by venukarnati92** [kubernetes-client/python#1626]
Async creation of custom resources (CR) using the CRD is failing for dynamic Client create call.

Synchronous Implementation with this example is working fine https://github.com/kubernetes-client/python/blob/master/examples/dynamic-client/namespaced_custom_resource.py

Now to make creation process as async update line number 192 on the above example to the following

`ingressroute_api.create(body=ingressroute_manifest_first, namespace=namespace_first, async_req=True)`

Error Message

`(ansible) 21-11-16 2:45:14 venu.karnati@ABOUTPIANOORIGIN:~/Desktop/gitProject/python/examples/dynamic-client$ python namespaced_custom_resource.py Traceback (most recent call last): File "namespaced_custom_resource.py", line 250, in <module> main() File "namespaced_custom_resource.py", line 192, in main ingressroute_api.create(body=ingressroute_manifest_first, namespace=namespace_first, async_req=True) File "/Users/venu.karnati/.pyenv/versions/ansible/lib/python3.6/site-packages/kubernetes/dynamic/client.py", line 119, in create return self.request('post', path, body=body, **kwargs) File "/Users/venu.karnati/.pyenv/versions/ansible/lib/python3.6/site-packages/kubernetes/dynamic/client.py", line 62, in inner return serializer(self, json.loads(resp.data.decode('utf8'))) AttributeError: 'ApplyResult' object has no attribute 'data'`

**Environment**:
- Kubernetes version 1.21.2
- MacOS 11.6):
- Python 3.6.8
- kubernetes          18.20.0

**Comment by roycaihw** [comment]
cc @fabianvf @roycaihw

**Comment by roycaihw** [comment]
In our typed clients, the syntax for using async_req is:
```
  thread = api.method(body, async_req=True)
  result = thread.get()
```
For example, the [CRD client](https://github.com/kubernetes-client/python/blob/549482d8842a47c8b51122422e879e7cc497bf88/kubernetes/client/api/apiextensions_v1_api.py#L43-L46).

Could you try if the same works with the dynamic client?

**Comment by venukarnati92** [comment]
@roycaihw 
On further debugging I was able to find that when you make an asynchronous call response doesn't have data attribute.I can see request is launched but client.py is unable to get the response details.Looks we need to have separate logic for response parsing when the call is asynchronous .

@roycaihw The above suggestion will still fail because the error is happening when we make a create call itself.

`"/Users/venu.karnati/.pyenv/versions/ansible/lib/python3.6/site-packages/kubernetes/dynamic/client.py", line 62, in inner return serializer(self, json.loads(resp.data.decode('utf8'))) AttributeError: 'ApplyResult' object has no attribute 'data'`

**Comment by venukarnati92** [comment]
I have raised a PR for the fix https://github.com/kubernetes-client/python-base/pull/269

**Comment by roycaihw** [comment]
Fixed by https://github.com/kubernetes-client/python/pull/1697
/close
