### ISSUE TITLE
How does Python get the token of serviceaccount through API

### ISSUE THREAD

**Issue by asskss** [kubernetes-client/python#1630]
**How does Python get the token of serviceaccount through API**

**Comment by roycaihw** [comment]
Could you clarify your question a bit more? Are you asking how does a Python application running in a pod in cluster get the token, or if you want to get the token from outside of the cluster? [Service account tokens](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#service-account-tokens) are embedded in secrets, so you can access them through secret API

**Comment by asskss** [comment]
@roycaihw 
Obtain the token from outside the cluster, such as calling client.RbacAuthorizationV1Api() through python script, the result returns the token of the serviceaccount account of the corresponding namespace.

**Comment by asskss** [comment]
@roycaihw 
I found it, thank you very much.

**Comment by roycaihw** [comment]
Glad to hear that! Yeah from outside the cluster I think you can use the service account API to find what secret is used by the service account, and then use the secret API to get the token. 

/close
