### ISSUE TITLE
AttributeError: 'NetworkingV1Api' object has no attribute 'create_namespaced_ingress'

### ISSUE THREAD

**Issue by XS170202106505** [kubernetes-client/python#1632]
AttributeError: 'NetworkingV1Api' object has no attribute 'create_namespaced_ingress'

def main():

    with open(path.join(path.dirname(__file__), "/data/k8s-client/ingress.yaml")) as f:
        dep = yaml.safe_load(f)
        k8s_apps_v1 = client.NetworkingV1Api()
        resp = k8s_apps_v1.create_namespaced_ingress(
            body=dep, namespace="fortest")
        print("Ingress created. status='%s'" % resp.metadata.name)
main()

**Comment by XS170202106505** [comment]
@roycaihw

**Comment by XS170202106505** [comment]
@roycaihw please! 3q!

**Comment by roycaihw** [comment]
@XS170202106505 What client version did you use? I tested the 20.13.0 client and didn't get the error. Here is the code I used: https://github.com/kubernetes-client/python/pull/1638

**Comment by muzaffersenkal** [comment]
Here is the source code. I think you are using the old version.

https://github.com/kubernetes-client/python/blob/24e6e8f00adaa942986fda02b53a6d932214536e/kubernetes/client/api/networking_v1_api.py#L168-L173

**Comment by roycaihw** [comment]
Thanks for the confirmation @muzaffersenkal! @XS170202106505 Please let us know if you have more questions. 

/close
