### ISSUE TITLE
pip install kubernetes report "ImportError: No module named pathlib"

### ISSUE THREAD

**Issue by ldrmcml** [kubernetes-client/python#1633]
I think there may be some problems with python2.7? I search stackoverflow, someone advice me to use python3, but I just can't upgrade to python3.

**What happened (please include outputs or screenshots)**:
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/6141752/143679666-4d67ad9e-d8d4-4a59-b051-b9d540a8f80a.png">

**What you expected to happen**:
pip install kubernetes successfully

**How to reproduce it (as minimally and precisely as possible)**:
pip install kubernetes

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g., MacOS 10.13.6):
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Python version (`python --version`)
Python 2.7.12

- Python client version (`pip list | grep kubernetes`)
$ pip list | grep kubernetes
You are using pip version 8.1.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by roycaihw** [comment]
Python 2.7 is no longer supported. Please try the latest Python client version ([v20.13.0](https://github.com/kubernetes-client/python/releases/tag/v20.13.0)) with Python 3. 

/close
