### ISSUE TITLE
Kubernetes python client taking up a lot of memory when using from a pod

### ISSUE THREAD

**Issue by vamshi-aruru** [kubernetes-client/python#1648]
**What happened (please include outputs or screenshots)**:
We have an API server on a kuberentes cluster hosted on aws. We recently added code to edit kuberentes deployment objects and cronjob objects and also monitor deployment health. Ever since we started using the client, our api pods memory usage has increased by more than 400 MB. Before the change, the pod was using about 400 MB of memory, now it uses around 800 MB

```
NAME                                             CPU(cores)   MEMORY(bytes)
api-7c9bd57697-57m22                         19m          803Mi
api-7c9bd57697-57r9w                         28m          774Mi
api-7c9bd57697-5cwkn                         24m          765Mi
api-7c9bd57697-5gh88                         27m          793Mi
api-7c9bd57697-b8gbt                         25m          783Mi
api-7c9bd57697-n2fl5                         30m          799Mi
```
Our API is build using fastapi  is similar to this
```
from kubernetes import client, config

@router.patch(
    path="/{service_name}/refresh/?",
    operation_id="refresh_service",
    responses={
        status.HTTP_200_OK: {
            "model": ServiceInDB
        }
    },
    summary="Refreshes a service",
    description=""
)
def refresh_service(service_name: StrictStr):
    """
    Refreshes a service
    """
   config.load_incluster_config()
   app_client = client.AppsV1Api()
   deployment = app_client.read_namespaced_deployment(service_name, "default")
   service = transform_deployment_object(deployment) # transform_deployment_object is an internal helper function
   return service
```
This API is not used frequently at all (about once every day), but ever since we have added this, the memory usage has increased a lot. 

**What you expected to happen**:
For the memory usage to not increase 

**How to reproduce it (as minimally and precisely as possible)**:
Simply install and use kuberentes python client in a long running pod and monitor memory usage.

**Anything else we need to know?**:
I have tried wrapping the kuberentes python client in a custom singleton so that only one instance of client is active at any time, but that hasn't helped either.

**Environment**:
- Kubernetes version (`kubectl version`):  
```Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g., MacOS 10.13.6): python:3.8-slim
- Python version (`python --version`): Python 3.8.12
- Python client version (`pip list | grep kubernetes`):  20.13.0

**Comment by roycaihw** [comment]
IIUC, you have a pod working as both an API server and an operator:
- it serves a `/{service_name}/refresh/?` API
- when it receives an API call for `{service_name}`, it reads the corresponding deployment and does some `transform_deployment_object`
- > edit kuberentes deployment objects and cronjob objects and also monitor deployment health

It's hard to tell where the memory usage comes from without more profiling. Could you provide more data points? Also do you see the memory usage to be static, or continuously increasing (any sign of leak)?

Without knowing more details, some suggestions off the top of my head:
- avoid re-loading incluster kubeconfig
- avoid re-constructing the apps v1 client
- if you use watch to monitor deployments, check if you need to tear down resources after you finished watching

**Comment by ashokat258** [comment]
Is issue still happening on this version?
