### ISSUE TITLE
Add property metadata to generated models

### ISSUE THREAD

**Issue by felixhuettner** [kubernetes-client/python#1658]
Hello everyone,

**What is the feature and why do you need it**:
I want determine in advance if a ssa-patch would cause any actual change for a given k8s resource.
In order to do this reliably for lists i need the information about `x-kubernetes-patch-strategy` and `x-kubernetes-patch-merge-key` from the openapi spec.

To make this easier it would be great if the models of this library would already provide this information for all fields.

**Describe the solution you'd like to see**:
This could work as follows (lets take `env` from a container as an example):

The class `V1Container` from https://github.com/kubernetes-client/python/blob/master/kubernetes/client/models/v1_container.py would be extended to contain the following information:

```python
[...]
class V1Container(object):
[...]
  openapi_metadata = {
    "env": {
        "x-kubernetes-patch-merge-key": "name",
        "x-kubernetes-patch-strategy": "merge"
    },
    [...]
  }
[...]
```

This would allow me to directly access the information from the respective object.

As these classes are auto-generated i am not sure if here is even the correct location to raise this feature request or if this is something that needs to be handled on the OpenAPI-Generator side.

Thank you

**Comment by madkinsz** [comment]
This would be really helpful for me as well! We're merging multiple configs (i.e. a default one and a user provided one) and it's not always feasible to create the resource _then_ patch it.

**Comment by madkinsz** [comment]
Can a maintainer determine if this is open for contribution and suggest the best way to add such metadata?
