### ISSUE TITLE
Facing connection refused error when trying to access python kubernetes client

### ISSUE THREAD

**Issue by Ramya1507** [kubernetes-client/python#1663]
**What happened (please include outputs or screenshots)**:
I am new to the kubernetes python- client and  trying to get the configmap details using python-client . I am running this in kubernetes cluster and  facing the **below** **warning** even though configmap is present in the cluster, can anyone help me on this

**WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f675f0943c8>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/**

code:
````
from kubernetes import client ,config
try:
   config.load_incluster_config()
except:
   config.load_kube_config()

v1 = client.CoreV1Api()
namespace = "default"
name = "example"
try:
   configmap = v1.read_namespaced_config_map(name,namespace)
   logging.info(configmap)
except:
   logging.info("no configmap with the given details")

````

**Comment by yliaog** [comment]
what does the kube config look like? does it work if you try using kubectl?

**Comment by yliaog** [comment]
i noticed that, before the upgrade: 
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 10.43.0.1:443

and after the upgrade:
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:80

do you know why is the connection changed from 10.43.0.1:443 to localhost:80 ?

**Comment by heresie** [comment]
Seems related to https://github.com/kubernetes-client/python/issues/1530
