### ISSUE TITLE
How to do pagination?

### ISSUE THREAD

**Issue by alkmim** [kubernetes-client/python#1668]
**Link to the issue (please include a link to the specific documentation or example)**:
No related documentation as far as I know. See description.

**Description of the issue (please include outputs or screenshots if possible)**:
I need to call 'list_pod_for_all_namespaces' method, but in my case I have too many pods. In this case it is not viable to retrieve everything in a single request. How can I do a pagination of the result like what is suggested here: https://github.com/kubernetes-client/python/issues/1225#issuecomment-675782379 ?

Thanks in advance

**Comment by yliaog** [comment]
it is the regular request with the extra 'limit' and 'continue' parameter. please see https://containerjournal.com/topics/container-management/introduction-to-using-the-kubernetes-rest-api/

**Comment by alkmim** [comment]
Thanks @yliaog ! This is exactly what I need! It would be nice if this was also in the kubernetes client docs or at least a reference to it.

**Comment by yliaog** [comment]
agreed. it'll be great if you could open a PR to add doc or reference for it.

**Comment by JPFrancoia** [comment]
For future people landing on this issue, here is a snippet to implement the pagination:

```python
    all_pods = []
    _continue = ""
    while True:
        print("Fetching all pods with pagination")
        if not _continue:
            ret = v1.list_pod_for_all_namespaces(watch=False, limit=200)
        else:
            ret = v1.list_pod_for_all_namespaces(watch=False, limit=200, _continue=_continue)

        all_pods += ret.items

        _continue = ret._metadata._continue

        if _continue is None:
            break

        print(f"{ret._metadata.remaining_item_count} pods left to fetch")

    print(f"Found {len(all_pods)} pods")
```
