### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable, but only on one namespace

### ISSUE THREAD

**Issue by joeldeteves** [kubernetes-client/python#1673]
**What happened (please include outputs or screenshots)**:

I apolgize if this is something obvious, but I am far from a Python / coding expert. I am trying to pull `Kind` from `pod.metadata.owner_references`:

```
def list_pods(ns):
    v1 = client.CoreV1Api()
    pods = v1.list_namespaced_pod(ns).items

    pod_list = []

    for pod in pods:

        name = pod.metadata.name
        kind = pod.metadata.owner_references[0].kind

        pod_list.append({'name':name, 'kind':kind})

    return pod_list
```
The code works on all pods / namespaces except for one I recently created. For some reason, *only this one instance* returns the following:

```
Traceback (most recent call last):
  File "/test.py", line 23, in <module>
    list_pods('my-namespace')
  File "/test.py", line 17, in list_pods
    kind = pod.metadata.owner_references[0].kind
TypeError: 'NoneType' object is not subscriptable
```

The rest of my namespaces / pods all work fine.

**What you expected to happen**:
The script should return the `Kind` field from `pod.metadata.owner_references`

**How to reproduce it (as minimally and precisely as possible)**:
Not sure, because it works on every namespace except for this one

**Anything else we need to know?**:

**Environment**: Docker (Alpine + Python image) / Ubuntu (tried both)
- Kubernetes version (`kubectl version`): 1.21
- OS (e.g., MacOS 10.13.6): WSL2 (Ubuntu on Windows 10), Docker
- Python version (`python --version`) 3.8.10
- Python client version (`pip list | grep kubernetes`) 12.0.1

---

UPDATE: To further complicate matters, when I run ```print(type(pod.metadata.owner_references))```, it does indeed show that the owner_references, and *only* the owner_references, and *only on this one namespace*, are indeed set to 'NoneType':

```
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'NoneType'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
```

Am I losing my marbles?

Thank you,

**Comment by showjason** [comment]
Hi @joeldeteves，maybe this pod is created independently, I mean this pod
does not be controlled by workload like deploy, sts, ds or rs. If so, `pod.metadata.owner_references` will be `noneType`

**Comment by joeldeteves** [comment]
@showjason thank you, however it is a Deployment. However I think you have touched on the problem - I had no idea there were certain conditions that could cause this to happen. Do you know of anything else that might trigger it to be listed as a `NoneType`?

**Comment by showjason** [comment]
@joeldeteves can you execute kubectl to get the yaml template of this pod? Then check if there is parameter `ownerReferences` in the template

**Comment by joeldeteves** [comment]
> 

Hi @showjason yes the `ownerReferences` are there, and I can also reference them as follows:

```
pod = client.CoreV1Api().list_namespaced_pod('my-namespace').items[0]
print(pod.metadata.owner_references[0].kind)
```

Obviously this is not ideal since I need to list all pods and check for their their `Kind`.

It is indeed a headscratcher that I ony have the problem with this one namespace, and only when referencing the `Kind` inside of my *for* loop.

**Comment by joeldeteves** [comment]
Hi there @showjason I just figured it out thanks to what you pointed out earlier.

My apologies for making the issue more complicated than it needed to be - it turns out, I am looping thru a list of pods and one of the pods in the list (not the specific one I was looking to extract the data from) is in fact a pod with no deployment type. In other words, you were 100% correct - I just missed it because I was looking at the wrong pod.

This solves my issue because now I can exclude pods that aren't part of a deployment.

Thank you so much for your help!
