### ISSUE TITLE
watch custom resources

### ISSUE THREAD

**Issue by coopstah13** [kubernetes-client/python#1679]
**What is the feature and why do you need it**:
I am creating custom resources and want to open a watch to wait for a status on the resources.

**Describe the solution you'd like to see**:
I would like to be able to pass `client.CustomObjectsApi().get_namespaced_custom_object` to the stream method of Watch. Instead I get the error `Got an unexpected keyword argument 'watch' to method get_namespaced_custom_object`. This seems easier to add than the full informer model with #868 - an informer would be kind of heavy for what I'm trying to accomplish.

**Comment by yannickperrenet** [comment]
I'd also like to have this behavior, but it seems like currently the 
`GET /apis/{group}/{version}/namespaces/{namespace}/{plural}/{name}` endpoint does not support the `follow` or `watch` query argument.

Any update on this? @roycaihw :smiley:

**Comment by tombokombo** [comment]
Works like a charm with watch api
```python
from kubernetes import client, config, watch
config.load_incluster_config()

wa = watch.Watch()
# list_namespaced_custom_object() has 4 required positional arguments: 'group', 'version', 'namespace', and 'plural'
# crontabs CR from here https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
for ev in wa.stream(co.list_namespaced_custom_object,'stable.example.com','v1','default','crontabs'):
    print(ev)
```
