### ISSUE TITLE
which api can implement“the bindings subresource of pods”

### ISSUE THREAD

**Issue by BigFishLi** [kubernetes-client/python#1680]
**Link to the issue (please include a link to the specific documentation or example)**:

https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Binding.md

**Description of the issue (please include outputs or screenshots if possible)**:
V1Binding
Binding ties one object to another; for example, a pod is bound to a node by a scheduler. Deprecated in 1.7, please use the bindings subresource of pods instead。

But which api should I use to "bindings subresource of pods"？

**Comment by showjason** [comment]
Hi@BigFishLi, I think "bindings subresource of pods" means the subresource like "nodeAffinity", "podAffinity", "nodeSelector" etc.
