### ISSUE TITLE
Get cpu and memory usage through in cluster config

### ISSUE THREAD

**Issue by zhilongwang** [kubernetes-client/python#1688]
**What is the feature and why do you need it**:
In my current project, I need to monitor some client pods in a server pod, which creates the these pods. The in_cluster_config.py in example/ folder can help me to create and delete pods. However, I did not find any APIs that can help me to monitor the memory and CPU usage just like which can be achieved through "kubectl top pods". I wonder is there python API that can help me to achieve this purpose? Thanks.

**Describe the solution you'd like to see**:
 Could you told me if there already exists some API that can help to achieve his purpose? If not, I hope to see a new API will be implemented soon.

**Comment by yliaog** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/

the cpu/memory is available in the metrics api (the one that kubectl top uses). please use this python client to access the metrics api to retrieve the cpu/memory info.
