### ISSUE TITLE
Support for RESTConfigFromKubeConfig to get kubeconfig from byte[]

### ISSUE THREAD

**Issue by zijianjoy** [kubernetes-client/python#1699]
**What is the feature and why do you need it**:

In golang, there is an API RESTConfigFromKubeConfig which you can convert byte[] to a restconfig, which can be used to create a Kubernetes client: https://pkg.go.dev/k8s.io/client-go/tools/clientcmd#RESTConfigFromKubeConfig. Do we have similar support in Python?

**Describe the solution you'd like to see**:

I am trying to reach a different cluster using the secret stored in the current cluster. But I am not sure how to convert a byte[] to kubeconfig.

**Comment by roycaihw** [comment]
Yes. We have a method to create client from dict. You will need to convert your byte array to a dict (something like base64.b64decode -> yaml.safe_load), then call [new_client_from_config_dict](https://github.com/kubernetes-client/python/blob/d5fffcae05ebdf2ce88a807e1f6ec68159794a4a/kubernetes/base/config/kube_config.py#L870-L885)
