### ISSUE TITLE
How to list nodes in k8s python client with multiple  labels?

### ISSUE THREAD

**Issue by nileshsalpe** [kubernetes-client/python#1710]
**Link to the issue (please include a link to the specific documentation or example)**:

Documentation list for list_node 

https://k8s-python.readthedocs.io/en/stable/kubernetes.client.apis.html
or 
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_node

**Description of the issue (please include outputs or screenshots if possible)**:

I want to list nodes with multiple labels and values with `AND` condition.

Example :
I want to list nodes with filter node with  two labels say label_1 ='x' and label_2='y' 

Question:
How to create `label_selector` for multiple labels?
is it string literal, regex  or function expression as string ?  is label_selector is like  ` label_1 =x,label_2='y' ` ? Please provide example.

**Comment by nileshsalpe** [comment]
As per my experimentation , following works. I expect it should be documented properly 

```
label_selector  = label_1 =x, label_2='y' 
```

**Comment by yliaog** [comment]
@nileshsalpe
do you mind to create a PR for an example to document it?

**Comment by Shivansh2407** [comment]
@yliaog can I proceed with this issue, if no one's currently working on this?

**Comment by yliaog** [comment]
sure, thanks.

**Comment by hsuram189** [comment]
Did the below get added in the documentation?

> As per my experimentation, following works. I expect it should be documented properly
> 
> ```
> label_selector  = 'label_1 =x,label_2=y'
> ```
> 
> ```
> v1_k8s_client.list_node(label_selector='label_1 =x, label_2=y')
> ```
