### ISSUE TITLE
Does Patching a Deployment trigger the Deployment be restarted

### ISSUE THREAD

**Issue by obautista** [kubernetes-client/python#1719]
I am using AppsV1Api.patch_namespaced_deployment to add an Annotation.  This is working.  My thought is doing this would trigger the Deployment be restarted.  The restart is not happening.  Is that expected behavior?  Is there a restart Deployment API?

I am using kubernetes==21.7.0

**Comment by showjason** [comment]
Hi @obautista , perhaps you can try [this example](https://github.com/kubernetes-client/python/blob/master/examples/deployment_crud.py)

**Comment by obautista** [comment]
Hi @showjason.  Thanks for the response.  Existing code below.  It looks like I am setup as such.  Annotation is added/updated, so deployment is in fact patched, but it isnt restarted.  Am I misunderstanding something?

`def __update_deployment(self, existing_deployment):
        try:
            self.__get_kubernetes_config()
            api = client.AppsV1Api()
            current_utc = datetime.datetime.utcnow().isoformat() + 'Z'
            annotation_key = 'deployment.kubernetes.io/restartedAt'
            existing_deployment.metadata.annotations[annotation_key] = current_utc
            response = api.patch_namespaced_deployment(self.deployment_name, self.namespace, existing_deployment)
            logging.debug(f'Updated Kubernetes Template Annotation: {response.metadata.annotations[annotation_key]}')
        except Exception as e:
            logging.error(f'Error updating Kubernetes Deployment: {e}')
            raise e`

**Comment by obautista** [comment]
@showjason - thank you.  Example reference was helpful.  It is working now.
