### ISSUE TITLE
Calling NetworkingV1Api().list_namespaced_ingress(namespace=namespace) raises 404 error instead of empty list

### ISSUE THREAD

**Issue by ckkz-it** [kubernetes-client/python#1723]
**What happened (please include outputs or screenshots)**:
The call to method `list_namespaced_ingress()` of `NetworkingV1Api` is raising 404 error.
![image](https://user-images.githubusercontent.com/39866850/155359540-23110c86-d301-4342-8096-7026df5c56b2.png)

**What you expected to happen**:
It should return an empty list, as other `list` methods do (e.g. `list_namespaced_config_map`, `list_namespaced_deployment`, `list_namespaced_horizontal_pod_autoscaler`, etc)

**How to reproduce it (as minimally and precisely as possible)**:
Call `NetworkingV1Api().list_namespaced_ingress(namespace=...)` for a namespace that doesn't have ingresses. In my case, it was the `default` namespace.

**Anything else we need to know?**:
Running inside GitHub Actions.

**Environment**:
- Kubernetes version (`kubectl version`): -
- OS (e.g., MacOS 10.13.6): Ubuntu 20.04
- Python version (`python --version`): 3.10.2
- Python client version (`pip list | grep kubernetes`): 21.7.0

**Comment by showjason** [comment]
Hi @ckkz-it , please try this script and it's working in my cluster.
```
from kubernetes import client, config


def main():

    config.load_kube_config()
    net_api = client.NetworkingV1Api()
    print(net_api.list_namespaced_ingress("default"))


if __name__ == "__main__":
    main()
```

**Comment by ckkz-it** [comment]
Hi @showjason, thanks for the answer.

Looks like this occurs sometimes even if we have ingresses in the default namespace, but I don't have exact steps for reproducing the issue. I'll try to update once we will have more info.

**Comment by roycaihw** [comment]
cc @roycaihw

**Comment by roycaihw** [comment]
Thanks @showjason @ckkz-it. Yes please let us know when you have more info.

**Comment by zxl00** [comment]
i  try this script  but this error

 kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Thu, 07 Apr 2022 03:04:39 GMT', 'Content-Length': '174'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}

**Comment by zhoushijie977816193** [comment]
**kubernetes 版本和 kubernetes-client 版本不匹配，换成匹配的版本可以解决问题。**

[client 9.y.z](https://pypi.org/project/kubernetes/9.0.1/): Kubernetes 1.12 or below (+-), Kubernetes 1.13 (✓), Kubernetes 1.14 or above (+-)
[client 10.y.z](https://pypi.org/project/kubernetes/10.1.0/): Kubernetes 1.13 or below (+-), Kubernetes 1.14 (✓), Kubernetes 1.14 or above (+-)
[client 11.y.z](https://pypi.org/project/kubernetes/11.0.0/): Kubernetes 1.14 or below (+-), Kubernetes 1.15 (✓), Kubernetes 1.16 or above (+-)
[client 12.y.z](https://pypi.org/project/kubernetes/12.0.1/): Kubernetes 1.15 or below (+-), Kubernetes 1.16 (✓), Kubernetes 1.17 or above (+-)
[client 17.y.z](https://pypi.org/project/kubernetes/17.17.0/): Kubernetes 1.16 or below (+-), Kubernetes 1.17 (✓), Kubernetes 1.18 or above (+-)
[client 18.y.z](https://pypi.org/project/kubernetes/18.20.0/): Kubernetes 1.17 or below (+-), Kubernetes 1.18 (✓), Kubernetes 1.19 or above (+-)
[client 19.y.z](https://pypi.org/project/kubernetes/19.15.0/): Kubernetes 1.18 or below (+-), Kubernetes 1.19 (✓), Kubernetes 1.20 or above (+-)
[client 20.y.z](https://pypi.org/project/kubernetes/20.13.0/): Kubernetes 1.19 or below (+-), Kubernetes 1.20 (✓), Kubernetes 1.21 or above (+-)
[client 21.y.z](https://pypi.org/project/kubernetes/21.7.0/): Kubernetes 1.20 or below (+-), Kubernetes 1.21 (✓), Kubernetes 1.22 or above (+-)
[client 22.y.z](https://pypi.org/project/kubernetes/22.6.0/): Kubernetes 1.21 or below (+-), Kubernetes 1.22 (✓), Kubernetes 1.23 or above (+-)
[client 23.y.z](https://pypi.org/project/kubernetes/23.6.0/): Kubernetes 1.22 or below (+-), Kubernetes 1.23 (✓), Kubernetes 1.24 or above (+-)
