### ISSUE TITLE
issue while creating config map using tube python client

### ISSUE THREAD

**Issue by deep1512** [kubernetes-client/python#1724]
**Link to the issue (please include a link to the specific documentation or example)**:  https://github.com/kubernetes-client/python/blob/master/examples/dynamic-client/configmap.py

**Description of the issue (please include outputs or screenshots if possible)**:

I am trying to create config map and getting issue.

def create_config_map():
    config.load_kube_config()
    v1 = client.CoreV1Api()
    configmap_name = "test"
    configmap_manifest = {
        "kind": "ConfigMap",
        "apiVersion": "v1",
        "metadata": {
            "name": configmap_name,
            "namespace": "Default"
        },
        "data": {
            "turbo.config": {
                "communicationConfig": {
                    "serverMeta": {
                        "version": "8.2",
                        "turboServer": ""
                    },
                    "restAPIConfig": {
                        "opsManagerUserName": "",
                        "opsManagerPassword": ""
                    }
                },
                "targetConfig": {
                    "targetName": " "
                },
                "HANodeConfig": {
                    "nodeRoles": ["master"]
                }
            }
        }
    }
    configmap = v1.create_namespaced_config_map(
        body=configmap_manifest, namespace="Default")

    print("\n[INFO] configmap 'test'  created\n")

create_config_map()

Getting error below.

python3 kube_python_client.py
Traceback (most recent call last):
  File "monitoring-agent-st2/kube_python_client.py", line 113, in <module>
    create_config_map()
  File "monitoring-agent-st2/kube_python_client.py", line 78, in create_config_map
    api = client.resources.get(api_version="v1", kind="ConfigMap")
AttributeError: module 'kubernetes.client' has no attribute 'resources'

python3 kube_python_client.py
Traceback (most recent call last):
  File "monitoring-agent-st2/kube_python_client.py", line 113, in <module>
    create_config_map()
  File "monitoring-agent-st2/kube_python_client.py", line 78, in create_config_map
    api = client(api_version="v1", kind="ConfigMap")
TypeError: 'module' object is not callable

python3 kube_python_client.py
Traceback (most recent call last):
monitoring-agent-st2/kube_python_client.py", line 113, in <module>
    create_config_map()
  kube_python_client.py", line 108, in create_config_map
    configmap = v1.create(body=configmap_manifest, namespace="Default")
AttributeError: 'CoreV1Api' object has no attribute 'create'

deepakupadhyay@Deepaks-MacBook-Pro monitoring-agent-st2 % python3 kube_python_client.py
Traceback (most recent call last):
  File "monitoring-agent-st2/kube_python_client.py", line 114, in <module>
    create_config_map()
  File "monitoring-agent-st2/kube_python_client.py", line 108, in create_config_map
    configmap = v1.create_namespaced_config_map(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 6630, in create_namespaced_config_map
    return self.create_namespaced_config_map_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 6725, in create_namespaced_config_map_with_http_info
    return self.api_client.call_api(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kubernetes/client/rest.py", line 275, in POST
    return self.request("POST", url,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/kubernetes/client/rest.py", line 234, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': 'a5e1b885-3309-4846-9a9c-83bfc85a72e7', 'X-Kubernetes-Pf-Prioritylevel-Uid': '5273023a-bdc1-4ca9-8cf9-a5866c5f39da', 'Date': 'Fri, 25 Feb 2022 06:17:59 GMT', 'Content-Length': '434'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"ConfigMap in version \"v1\" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects \" or n, but found {, error found in #10 byte of ...|config\": {\"communica|..., bigger context ...| \"namespace\": \"Default\"}, \"data\": {\"turbo.config\": {\"communicationConfig\": {\"serverMeta\": {\"version\": |...","reason":"BadRequest","code":400}

**Comment by showjason** [comment]
Hi @deep1512 , the format of `configmap_manifest` in your code is wrong, please refer to [this doc](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) to recreate the configmap manifest

**Comment by deep1512** [comment]
@showjason Actually, that is format from official document of product and working fine when applying using kubectl appy command.  I tried another one but that is skipping creation. Can you please provide your input here. 

def create_configmap_object():
    # Configureate ConfigMap metadata
    metadata = client.V1ObjectMeta(
        namespace="Default",
    )
    # Get File Content
    with open('test.yml', 'r') as f:
        file_content = f.read()
    # Instantiate the configmap object
    configmap = client.V1ConfigMap(
        api_version="v1",
        kind="ConfigMap",
        data=file_content,
        metadata=metadata
    )

    return configmap

    print("\n[INFO] configmap 'test-config' created\n")


create_configmap_object()

**Comment by roycaihw** [comment]
/assign @showjason 
Thank you!

**Comment by showjason** [comment]
@deep1512 I think you misunderstand this example :https://github.com/kubernetes-client/python/blob/master/examples/dynamic-client/configmap.py.
In this example, you can see the `data` in `configmap_manifest` is a map(one key and one value which is a type of string ), rather than a nested map like the `configmap_manifest` in your code. 
In addition, I guess the nested map for configmap is not supported by kubernetes(my kubernetes version is 1.19 and 1.21), because I try to run the `configmap_manifest` you posted by kubectl, I get this error `error: error validating "origin.json": error validating data: ValidationError(ConfigMap.data.turbo.config): invalid type for io.k8s.api.core.v1.ConfigMap.data: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false`

You can try this yaml file, it's working in my cluster:
`kind: ConfigMap
apiVersion: v1
metadata:
  name: test-cm
  namespace: default
data:
  turbo.config: |
    communicationConfig:
      serverMeta:
        version: 8.2
        turboServer: ''
      restAPIConfig:
        opsManagerUserName: ''
        opsManagerPassword: ''
    targetConfig:
      targetName: ' '
    HANodeConfig:
      nodeRoles:
        - master`

**Comment by deep1512** [comment]
@showjason thank you for reply. Can you please me proper format of above response. I am new programming and didn't understand how I can use it.

**Comment by showjason** [comment]
> @showjason thank you for reply. Can you please me proper format of above response. I am new programming and didn't understand how I can use it.

test.yml:
```
  turbo.config: |
    communicationConfig:
      serverMeta:
        version: 8.2
        turboServer: ''
      restAPIConfig:
        opsManagerUserName: ''
        opsManagerPassword: ''
    targetConfig:
      targetName: ' '
    HANodeConfig:
      nodeRoles:
        - master
```

Please try this script:
```
from kubernetes import client, config
import yaml

def create_configmap_object():
    # Configureate ConfigMap metadata
    metadata = client.V1ObjectMeta(
        namespace="default",
        name = "cm-test"
    )
    # Get File Content
    with open('test.yml', 'r') as f:
        file_content = yaml.safe_load(stream=f)
    # Instantiate the configmap object
    configmap = client.V1ConfigMap(
        api_version="v1",
        kind="ConfigMap",
        data=file_content,
        metadata=metadata
    )

    return configmap

print("\n[INFO] configmap 'test-config' created\n")
cm_obj = create_configmap_object()
config.load_kube_config()
v1 = client.CoreV1Api()
v1.create_namespaced_config_map(body=cm_obj, namespace="default")
```

**Comment by deep1512** [comment]
Hello @showjason <https://github.com/showjason>

Thank you. I tried an example and it did work but I want to check how I can
call this in the main function. Right now cm_obj calling function and
creating the object but i am want to call it in the main function if logic
so it will not create object all the time. Like below. Please help.

def main():

if nsfound == False:
cm_obj = create_configmap_object()
main()

**Comment by deep1512** [comment]
full code what i think should work in this way.

```
from kubernetes import client, config
import yaml

def create_configmap_object():
    # Configureate ConfigMap metadata
    metadata = client.V1ObjectMeta(
        namespace="default",
        name = "cm-test"
    )
    # Get File Content
    with open('test.yml', 'r') as f:
        file_content = yaml.safe_load(stream=f)
    # Instantiate the configmap object
    configmap = client.V1ConfigMap(
        api_version="v1",
        kind="ConfigMap",
        data=file_content,
        metadata=metadata
    )

    return configmap

print("\n[INFO] configmap 'test-config' created\n")
cm_obj = create_configmap_object()
config.load_kube_config()
v1 = client.CoreV1Api()
v1.create_namespaced_config_map(body=cm_obj, namespace="default")

def main():
    if nsfound == False:
        cm_obj = create_configmap_object()
main()
```

**Comment by deep1512** [comment]
Closing issue for now. Thank you for all support.
