### ISSUE TITLE
Why can't I add probes to the service

### ISSUE THREAD

**Issue by Dignn** [kubernetes-client/python#1727]
But I think when my probe mode is HTTP, it always prompts me to report an error
I use the v1httpgetaction object. I want to fill in the port. I am prompted to fill in the object type in the source code and documents, but I can't find the object type.
Always remind me:Invalid value for `port`, must not be `None`
I hope you can help me, thank you.

**Comment by showjason** [comment]
Hi @Dignn，can you post your code and kubernetes/python-client version here?

**Comment by roycaihw** [comment]
/assign @showjason 
Thank you!

**Comment by Dignn** [comment]
> Hi @Dignn，can you post your code and kubernetes/python-client version here?
It has been solved now. Thank you for your help.
