### ISSUE TITLE
Missing an example in how to run a "apply -f"

### ISSUE THREAD

**Issue by mazzespazze** [kubernetes-client/python#1737]
**Link to the issue (please include a link to the specific documentation or example)**:
Most of the resources https://github.com/kubernetes-client, https://github.com/kubernetes-client/python/tree/master/examples are lacking one of the most needed examples: how to perform a `kubectl apply -f file.yaml`

**Description of the issue (please include outputs or screenshots if possible)**:
Currently it seems the API has examples for how to create and delete resources, and most of its examples are around connectivity. An example on the apply -f should be given, especially since these closed tickets should have not been closed at all as no solution was given: 
https://github.com/kubernetes-client/python/issues/1215
https://github.com/kubernetes-client/python/issues/1168

**Comment by mazinesy** [comment]
Adding [server side apply doc](https://kubernetes.io/docs/reference/using-api/server-side-apply/)

**Comment by RonMallory** [comment]
I have submitted a PR adding additional examples for using utils.create_from_directory and utils.create_from_yaml.

I believe this is some of the functionality that you are looking for an examples of.

It will not be the full functionality of kubectl apply -f but it gives you a better example than what was previously up there.

**Comment by roycaihw** [comment]
Thanks @RonMallory 
/close

**Comment by sm-moore** [comment]
I was looking at the examples in the PR Ron mentioned above https://github.com/kubernetes-client/python/pull/1752 and don't see any example of kubectl apply, only kubectl create. It appears to me this library doesn't actually support the apply operation. Is that true?
