### ISSUE TITLE
Move kubernetes/test/test_api_client.py to a different place

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-client/python#1742]
[kubernetes/test/test_api_client.py](https://github.com/kubernetes-client/python/blob/6c90fe3182adc0f3e1a351a0993d3159322b2c80/kubernetes/test/test_api_client.py) doesn't play well with the [release process](https://github.com/kubernetes-client/python/blob/6c90fe3182adc0f3e1a351a0993d3159322b2c80/scripts/release.sh#L206).

/assign

**Comment by Shivansh2407** [comment]
Hey @roycaihw, where would you suggest moving this file to? I would like to work on this. Thanks!
