### ISSUE TITLE
CoreV1Api.md not viewable in GitHug -- too big

### ISSUE THREAD

**Issue by ottokruse** [kubernetes-client/python#1758]
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md

Shows:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/6275520/159245456-18d1afeb-b615-4f39-9f3a-c38ad731aa35.png">

Which is unfortunate because now I have to open an external MD viewer. Is this something you folks can fix, e.g. by splitting out?

**Comment by roycaihw** [comment]
This is a Github issue. There is not much we can do.
/close
