### ISSUE TITLE
How to get Allocated resources of node. Like kubectl describe node ***

### ISSUE THREAD

**Issue by Rudy-Han** [kubernetes-client/python#1759]
Hi all, I can get Allocated resources info by kubectl describe node [node_name]. 
But read_node and read_node_status didn't give me those info I need.

**Comment by showjason** [comment]
Hi Rudy-Han, the function `read_node` or `read_node_status` only sends a request to kube-apiserver,  then kube-apiserver gets the data from etcd and responses the request with the collected data. However, `Allocated resources` is not recorded in etcd, it is computed by `kubectl describe`. `kubectl describe` collects the total `Allocated resources` of every pod running in the specified node. You can refer to source code [here](https://github.com/kubernetes/kubernetes/blob/56f45c5c811ba23934915b1a1330d87c58bddf07/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L4065)

**Comment by roycaihw** [comment]
/assign @showjason 
You could also check what API kubectl calls using `-v` flag.
