### ISSUE TITLE
ValueError: Invalid value for `spec`, must not be `None` when use client.V1SelfSubjectRulesReview()

### ISSUE THREAD

**Issue by zhangguanzhang** [kubernetes-client/python#1762]
**What happened (please include outputs or screenshots)**:

```
$ cat t2

from kubernetes import client, config

if __name__ == "__main__":
    body = client.V1SelfSubjectRulesReview()
    print(body)
$ python t2
Traceback (most recent call last):
  File "t2", line 5, in <module>
    body = client.V1SelfSubjectRulesReview()
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/models/v1_self_subject_rules_review.py", line 70, in __init__
    self.spec = spec
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/models/v1_self_subject_rules_review.py", line 160, in spec
    raise ValueError("Invalid value for `spec`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `spec`, must not be `None`

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 10.13.6):
- Python version (`python --version`) Python 3.7.8
- Python client version (`pip list | grep kubernetes`) kubernetes         23.3.0

**Comment by roycaihw** [comment]
The error message suggests that the field is required and should not be none. @zhangguanzhang Is there any reason that you believe it should be optional? 

Could you enable [debug logging](https://github.com/kubernetes-client/python/blob/51c481692ab0d9c71b9dd96342bfa93b721b029d/examples/deployment_crud.py#L153-L155) to print the request and response, and share the log with us?
