### ISSUE TITLE
Support pod execute api for dynamic client

### ISSUE THREAD

**Issue by dingyiyi0226** [kubernetes-client/python#1764]
**What is the feature and why do you need it**:
I want to use dynamic client for executing commands in pods (api: `connect_get_namespaced_pod_exec`).  
Similar to this [example](https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py) but using the dynamic client.

**Describe the solution you'd like to see**:
Add new functions for dynamics clients for discovering this api.

**Comment by fabianvf** [comment]
We investigated doing this a while ago but decided against it, as the API is totally specific to pods and AFAIK there are no plans to implement it on other resources. We didn't see any advantage to using a dynamic client vs the typed client in this case. Is there a reason using the pod exec API in the typed client isn't working for you?

**Comment by dingyiyi0226** [comment]
The typed client is working. I requested for this feature  is because I use dynamic client in my project and i don't want to create a new client only for this API.

I think we can close this issue.
