### ISSUE TITLE
Random 401 with BoundServiceAccountToken

### ISSUE THREAD

**Issue by waldner** [kubernetes-client/python#1768]
**What happened**:

With the new bound service account token feature (ie the token in `/run/secrets/kubernetes.io/serviceaccount/token` is periodically rotated), it looks like sometimes the library is not able to pick up the new values of the token.

**How to reproduce it (as minimally and precisely as possible)**:

Have the following code running in a pod with a projected volume created by the feature gate (secret `somesecret` must exist in namespace `mynamespace`, which in this case was the same ns the pod was running under, so for maximum reproducibility I suggest running in a non-default namespace):

```
# loop.py
from kubernetes import client, config
import sys, random, time, datetime

while True:
    config.load_incluster_config()
    v1 = client.CoreV1Api()
    msg = "ok"
    try:
        resp = v1.read_namespaced_secret("somesecret", "somenamespace")
    except Exception as e:
        msg = "Exception: %s" % e

    print("[%s]: %s" % (datetime.datetime.now(), msg), file=sys.stderr)
    time.sleep(random.randint(20, 300))
``` 

Leave it running for a while and after some time (might be _many_ hours) we get (sample):

```
...
[2022-03-31 14:33:38.147379]: ok
[2022-03-31 14:36:36.257633]: ok
[2022-03-31 14:38:28.367270]: ok
[2022-03-31 14:42:46.523703]: Exception: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': '226e3c4b-b29f-4c63-9065-f9e609de0213', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Thu, 31 Mar 2022 14:42:46 GMT', 'Content-Length': '129'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}\n'

[2022-03-31 14:46:53.663473]: Exception: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'a7b17fac-66f9-4aaf-80c3-51b587496099', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Thu, 31 Mar 2022 14:46:53 GMT', 'Content-Length': '129'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}\n'


...snip about 42 minutes of repeated exceptions...


[2022-03-31 15:24:44.495199]: ok
[2022-03-31 15:29:14.607463]: ok
[2022-03-31 15:33:20.739682]: ok
...
```

**Anything else we need to know?**:

Here's a simple Dockerfile to build an image to run the above code:

```
FROM python:3.9
ARG VERSION=22.6.0
RUN pip3 install --upgrade setuptools
COPY loop.py /
RUN pip3 install kubernetes==${VERSION}
CMD [ "python3", "/loop.py" ]
```

deploy it in k8s and check the logs.

Here's the projected volume created by the feature gate:

```
    - name: kube-api-access-74mc9
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
```

**Environment**:
- Kubernetes version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.1-1820+4dd1b5a1afc832-dirty", GitCommit:"4dd1b5a1afc832ea28e8c58af4a8d67b30f1278f", GitTreeState:"dirty", BuildDate:"2021-11-23T11:10:51Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g., MacOS 10.13.6):

OKD 4.9 cluster

- Python version (`python --version`)
```
$ python --version
Python 3.9.12
```

- Python client version (`pip list | grep kubernetes`)

Seen with 21.7.0, 22.6.0 and 23.3.0

**Comment by yliaog** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection

The kubelet will request and store the token on behalf of the pod, make the token available to the pod at a configurable file path, and refresh the token as it approaches expiration. The kubelet proactively rotates the token if it is older than 80% of its total TTL, or if the token is older than 24 hours.

The application is responsible for reloading the token when it rotates. Periodic reloading (e.g. once every 5 minutes) is sufficient for most use cases.

==============================================================
https://github.com/kubernetes-client/python/blob/1271465acdb80bf174c50564a384fd6898635ea6/kubernetes/base/config/incluster_config.py#L47

the library will refresh the token every 1 minutes. could you check if token used when call v1.read_namespaced_secret(...) is the same as the token mounted into the pod.

**Comment by waldner** [comment]
After a cluster upgrade to okd 4.10, this has now been running for more than two days without issues, so I'm going to assume that the problem was elsewhere. Closing the bug, thanks.
