### ISSUE TITLE
CoreV1APi.create_namespaced_pod() always sets "image_pull_policy" to "NotIfPresent"

### ISSUE THREAD

**Issue by spleeeen** [kubernetes-client/python#1770]
**What happened**:
Function works as intended and sets every other value of large nested pod definition (the body arg). However, as seen in the V1Pod return value, it sets the all container.image_pull_policy values to "NotIfPresent" in the pod.spec.containers array.  `kubectl applying`ing the generated yaml with this value changed to 'Always' succeeds in persisting it. Problem only occurs when using the python client.

### Relevant Code
_call to create_namespaced_pod()_
<img width="595" alt="image" src="https://user-images.githubusercontent.com/40253103/162068167-4890d376-cb93-48a7-a64e-38fa96a669bc.png">
_definition of pod body_
<img width="906" alt="image" src="https://user-images.githubusercontent.com/40253103/162068555-dd659293-c23c-4ae1-83e8-78b120a18d4c.png">

### Excerpt of print statement
<img width="715" alt="image" src="https://user-images.githubusercontent.com/40253103/162069320-18efec37-14e1-4be7-aed2-f14803cc21f2.png">

**What you expected to happen**:
image pull policy to be set to 'Always'

**How to reproduce it (as minimally and precisely as possible)**:
see code

**Environment**:

Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

Python 3.8.9

kubernetes==21.7.0

**Comment by showjason** [comment]
Hi @spleeeen , please refer to this [example](https://github.com/kubernetes-client/python/blob/release-21.0/examples/deployment_crud.py), it is similar to your case.
The attributes of pod belong to different models, they must be converted to model object, then unmarshal the model object into Go struct.

**Comment by spleeeen** [comment]
```
def pod_object(asset_name):
    env_var = client.V1EnvVar(name='CONTAINER_NAME', value=asset_name)
    limits = {'cpu': cpu_limit, 'memory': memory_limit}
    requests = {'cpu': cpu_request, 'memory': memory_request}
    resources = client.V1ResourceRequirements(limits=limits, requests=requests)
    container = client.V1Container(name=f'{asset_name}-archivist', 
                                    image=f'ntr.nwie.net/eds/anomaly-engine-archivist:{image_tag}',
                                    image_pull_policy='Always',
                                    resources=resources,
                                    env=[env_var])
    spec = client.V1PodSpec(containers=[container])
    metadata = client.V1ObjectMeta(name=f'{asset_name}-archivist', labels={'archivist': asset_name})
    return client.V1Pod(metadata=metadata, spec=spec)
```
<img width="735" alt="image" src="https://user-images.githubusercontent.com/40253103/162309964-8866160e-b555-47cd-85a8-631975be0b9b.png">

After changing the code to use the client's objects it still exhibits the same behavior. Everything from the pod name to the resources and environment variables are set as specified with the exception of image_pull_policy, which is set to 'IfNotPresent' within the pod despite how it is declared.

I have read the the default for this image_pull_policy value is 'IfNotPresent' when the image tag is anything but 'latest,' in which case it defaults to 'Always.' Is this supposed default behavior somehow overwriting my declared value?

**Comment by spleeeen** [comment]
Not sure how but it worked after switching the image tag it was using to create the pod's container? Thanks

**Comment by roycaihw** [comment]
/assign @showjason 
Thank you!

/close
