### ISSUE TITLE
ExecPlugins are broken when using KubeConfigs loaded from dict

### ISSUE THREAD

**Issue by jeid64** [kubernetes-client/python#1774]
**What happened (please include outputs or screenshots)**:

We use https://github.com/kubernetes-client/python/blob/master/kubernetes/base/config/kube_config.py#L820 to load Kubeconfigs from memory in Python, these Kubeconfigs have a configuration to use an Exec plugin to get an auth token (specifically we are trying to auth with an EKS cluster.)

https://github.com/kubernetes-client/python-base/pull/275/files#diff-a994e720c2c925ca342b251f2d057ab3a730a1bdc166e5766249a30bdf170a47R73 this PR to python-base attempts to pass the cwd of the config file to the exec plugin, however the cwd of a config file loaded from a dict is empty string (https://github.com/kubernetes-client/python/blob/master/kubernetes/base/config/kube_config.py#L542). When empty string is passed to subprocess.Popen, subprocess.Popen errors with "ERROR:root:[Errno 2] No such file or directory: ''" and does not run the auth plugin. 

Commenting out https://github.com/kubernetes-client/python-base/pull/275/files#diff-a994e720c2c925ca342b251f2d057ab3a730a1bdc166e5766249a30bdf170a47R73 fixed our auth issues completely, but the longterm fix is probably checking if the base_path is empty string and if so, pass None as the cwd to Popen. 

The issue means that anyone using EKS with load_kube_config_from_dict has been broken since this PR was merged. 

**What you expected to happen**:
Run the ExecProvider and return a token
**How to reproduce it (as minimally and precisely as possible)**:
Use load_kube_config_from_dict with an Authentication configuration using "command" for the user

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 10.13.6):
Linux
- Python version (`python --version`)
3.8.10
- Python client version (`pip list | grep kubernetes`)
23.3.0

**Comment by jeid64** [comment]
@aschleck

**Comment by nikitron** [comment]
The problem is empty `self.cwd` when called `subprocess.Popen` in file `kubernetes/config/exec_provider.py` (line 69)
```python
        process = subprocess.Popen(
            self.args,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=self.cwd,
            env=self.env,
            universal_newlines=True)
```
This variable is set to None in class `KubeConfigLoader` (file `kubernetes/config/kube_config.py` line 201)
```python
        elif isinstance(config_dict, ConfigNode):
            self._config = config_dict
        else:
            self._config = ConfigNode('kube-config', config_dict)   <---- problem here
```
As you can see in last line when a config is created by dict - 3rd argument is not provided.

So I propose to use a temp directory in `ConfigNode('kube-config', config_dict, 'some_temp_dir')`

**Work around** is to save token to file and use `kubernetes.config.new_client_from_config_dict(token_file_path)`

**Comment by nwbhatia** [comment]
does anyone know the last python client version where this was working correctly?
