### ISSUE TITLE
Document debug logging

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-client/python#1775]
Document how to use [debug logging](https://github.com/kubernetes-client/python/blob/51c481692ab0d9c71b9dd96342bfa93b721b029d/examples/deployment_crud.py#L153-L155) to show request and response, in a dev doc.

**Comment by kriswuollett** [comment]
If possible, it would be great if there was an example that used `load_incluster_config` as I'm assuming that is what would be likely used if trying to implement an operator. I tried using some code like the following but it seems to break the configuration loaded earlier:

```python
config = Configuration()
config.debug = True
kubernetes.config.load_incluster_config(client_configuration=config)
```

**Comment by roycaihw** [comment]
Could you try if this works
```
kubernetes.config.load_incluster_config()
c = client.Configuration()
c.debug = True
apps_v1 = client.AppsV1Api(api_client=client.ApiClient(configuration=c))
```
IIRC we had a feature request of "load_kube_config falls back to load_incluster_config if the out-of-cluster kubeconfig is not found". If that's implemented, the flow should be the same for both out-of-cluster kubeconfig and in-cluster kubeconfig

**Comment by kriswuollett** [comment]
Will try to find a chance to try your suggestion later in the week when I finish the stack of changes built upon this -- was able to figure out issue without debugging at the moment.

**Comment by rogue-gamer-ryt** [comment]
Hey @roycaihw,

I want to start contributing to this project, since this is a documentation change I think this would be a good candidate for my first contribution.

So firstly can I pick this up? and secondly, is this the correct [file](https://github.com/kubernetes-client/python/blob/master/examples/README.md) which needs to be updated?
