### ISSUE TITLE
Add `api_client` parameter to `Watch`

### ISSUE THREAD

**Issue by kriswuollett** [kubernetes-client/python#1776]
**What is the feature and why do you need it**:

I'm manually configuring a proxied `api_client` like the following with the command `kubectl proxy --port=8080`:

```python
config = Configuration()
config.host = f"{host}:{port}"
api_client = ApiClient(configuration=config)
```

I currently can create an instance of an API like:

```python
custom_objects = CustomObjectsApi(api_client=api_client)
```

But I cannot do the the same with `Watch` because its `api_client` is a private variable initialized with `client.ApiClient()`:https://github.com/kubernetes-client/python/blob/51c481692ab0d9c71b9dd96342bfa93b721b029d/kubernetes/base/watch/watch.py#L71-L77

Is there a limitation why it seems to be using the global default configured `client`?

I particularly need to make sure I'm using my specific `Configuration`, but this would also apply to watching resources across multiple Kubernetes clusters simultaneously.

**Describe the solution you'd like to see**:

Add an `api_client` parameter to the `Watch` constructor with default value of `client.ApiClient()`.

**Comment by roycaihw** [comment]
Haven't checked the watch implementation for a while. When using a watch you also need to specify a list method which comes with its own client ([example](https://github.com/kubernetes-client/python/blob/51c481692ab0d9c71b9dd96342bfa93b721b029d/examples/watch/pod_namespace_watch.py#L37-L40)). I wonder what's the difference between the two clients.

**Comment by roycaihw** [comment]
Looks like it's only used for [deserialize](https://github.com/kubernetes-client/python/blob/51c481692ab0d9c71b9dd96342bfa93b721b029d/kubernetes/base/watch/watch.py#L105), which is static in most cases. I think that's why it doesn't need to be expose as a parameter. WDYT?
