### ISSUE TITLE
Download directory from Pod

### ISSUE THREAD

**Issue by geek-bit** [kubernetes-client/python#1780]
I have been able to download a file from Pod to local using the Python Kube client. The code is available [here](https://stackoverflow.com/questions/59703610/copy-file-from-pod-to-host-by-using-kubernetes-python-client).
However, I don't see any example to download directory from pod to local in the official [examples](https://github.com/kubernetes-client/python/tree/master/examples). 
As a workaround, I am creating a tar file of the directory in the pod. Then I am downloading the tar of the directory as a file to local and extract it. 

`directory -> tar -> download tar -> extract tar at local -> delete tar in pod -> delete tar in local  
`

However, this approach involves clean-up of the temporary tar in the pod as well as local and is not very clean. 
Is there any better way to download the whole directory from pod to local?

**Comment by yliaog** [comment]
one way is to use GCS bucket, and gsutil. it does not need to use python kube client though.

**Comment by geek-bit** [comment]
We don't have the Kube cluster hosted on GCP. Isn't there any elegant way of downloading the directory from Pod to local using Python client?
@roycaihw, @yliaog any suggestions?

**Comment by geek-bit** [comment]
Any update on this please?
