### ISSUE TITLE
Docs - edit on github link is broken

### ISSUE THREAD

**Issue by epicfaace** [kubernetes-client/python#1786]
The link here (https://kubernetes.readthedocs.io/en/latest/README.html#) on the top right is broken.

**Comment by yliaog** [comment]
i followed the link: https://kubernetes.readthedocs.io/en/latest/README.html#, it shows the doc just fine. what is broken?

**Comment by epicfaace** [comment]
Click on the "Edit on github" link and it links to https://github.com/kubernetes-client/python/blob/master/doc/source/README.md, which is not found.

![image](https://user-images.githubusercontent.com/1689183/166265769-c2c7fa58-7948-4867-9a31-bd844d4b6d6a.png)

**Comment by yliaog** [comment]
i see. could you change the link to point to https://github.com/kubernetes-client/python/README.md?

**Comment by epicfaace** [comment]
I see there's a PR here? https://github.com/kubernetes-client/python/pull/1788 but it seems to be adding much more than what is needed...

**Comment by Shivansh2407** [comment]
Instead of pointing it to the readme, it would be a better option to add a readme file to the source dir, as the `make html` command builds up the things and uses `source-dir = doc/source`, because of which the pages are generated from here.
Let me know your thoughts on this.

**Comment by epicfaace** [comment]
Got it, but where did you get the content for that readme file from?

**Comment by Shivansh2407** [comment]
Oh, so this one's the same that is present on the root dir (https://github.com/kubernetes-client/python/blob/master/README.md)

**Comment by yliaog** [comment]
sounds good to me. approved the PR

**Comment by Shivansh2407** [comment]
Cool. My First PR to the Kubernetes Python client! Will try to add more value to the repo and the py client in the upcoming PRs. Thanks @yliaog and @epicfaace 👍
