### ISSUE TITLE
Is the Kubernetes version 1.23.6 compatible with the current client?

### ISSUE THREAD

**Issue by Alexander123312** [kubernetes-client/python#1791]
Is the Kubernetes version 1.23.6 compatible with the current client because I have problems with it and with the K8S version 1.20 it works without problems. I can't explain in more detail what the problems behind it are because I only use the API in connection with CheckMK.

**Comment by roycaihw** [comment]
We need more information to tell what the problem is. On the other hand we just had a new release for Kubernetes 1.23: https://github.com/kubernetes-client/python/releases/tag/v23.6.0. Could you try if that helps?
