### ISSUE TITLE
read_node_status returns unexpected keyword argument 'watch' error

### ISSUE THREAD

**Issue by obrienrobert** [kubernetes-client/python#1793]
**What happened (please include outputs or screenshots)**:
`read_node_status` returns the following error:

```
Traceback (most recent call last):
  File "/home/robrien/repos/krkn/node_status.py", line 13, in <module>
    for e in w.stream(v1.read_node_status, name=node):
  File "/home/robrien/.local/lib/python3.10/site-packages/kubernetes/watch/watch.py", line 163, in stream
    resp = func(*args, **kwargs)
  File "/home/robrien/.local/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 25433, in read_node_status
    return self.read_node_status_with_http_info(name, **kwargs)  # noqa: E501
  File "/home/robrien/.local/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 25478, in read_node_status_with_http_info
    raise ApiTypeError(
kubernetes.client.exceptions.ApiTypeError: Got an unexpected keyword argument 'watch' to method read_node_status
```
Code (simplifed):
```
from kubernetes import client, config, watch

config.load_kube_config()

w = watch.Watch()
v1 = client.CoreV1Api()

for e in w.stream(v1.read_node_status, name="node-name"):
    print(e['object'])
```

**What you expected to happen**:
The status of the requested node is returned using the watch.

**How to reproduce it (as minimally and precisely as possible)**:
Run the code above in a script against a cluster

**Anything else we need to know?**:
My target cluster is an Openshift CRC cluster (but all other functions work without error)

**Environment**:
- Kubernetes version (`Kubernetes Version: v1.23.3+e419edf`):
- OS (Fedora 35):
- Python version (`Python 3.10.4`)
- Python client version (`kubernetes==18.20.0`)

**Comment by obrienrobert** [comment]
Looks like it's only working with `list` functions, and not read. Maybe this is expected behaviour?

**Comment by roycaihw** [comment]
Yes. Watch is implemented as [part of the list API](https://github.com/kubernetes/kubernetes/blob/b53be1d66ef1c7f79410d619864d3788e084dd49/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L335-L338), so you need to use a list method to do the watch.

cc @yliaog 
/close
