### ISSUE TITLE
Release 1.24 clients

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-client/python#1797]
Kubernetes 1.24 is [released](https://github.com/kubernetes/kubernetes/tree/v1.24.0). We should generate corresponding clients.

**Comment by mk46** [comment]
Hi @roycaihw, I want to work on this. I have seen https://github.com/kubernetes-client/python/pull/1794 and https://github.com/kubernetes-client/python/pull/1709.
`./scripts/update-client.sh` may be used for generating client changes.
Could you please guide me on how to generate API changes?  
Thanks !!

**Comment by roycaihw** [comment]
/assign @yliaog 
Yu has already started on this. 

@mk46 Thanks for being interested to contributing. Maybe we can try the 1.25 release?

**Comment by yliaog** [comment]
1.24 GA has been released.
