### ISSUE TITLE
Hey I need to write the client for kubectl plugin, is there any doc that how can I do it through this python client?

### ISSUE THREAD

**Issue by mukhtar-inamdar** [kubernetes-client/python#1823]
**Hey I need to write the client for kubectl plugin, is there any doc that how can I do it through this python client?**:

**Comment by Akasurde** [comment]
@mukhtar-inamdar Thanks for reporting this issue. Could you please refer https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/ ? Thanks.

**Comment by roycaihw** [comment]
This seems like a duplicate of #1822
/close
