### ISSUE TITLE
line 342     if async:        SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Tarandeepsingh436** [kubernetes-client/python#1834]
**What happened (please include outputs or screenshots)**:
traceback (most recent call last):
  File "/Users/apple/Projects/python/Twiiter/twitter_get_user_timeline.py", line 3, in <module>
    from tweepy import Cursor
  File "/Users/apple/opt/anaconda3/lib/python3.9/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/Users/apple/opt/anaconda3/lib/python3.9/site-packages/tweepy/streaming.py", line 342
    if async:
       ^
SyntaxError: invalid syntax

**What you expected to happen**:
I am expecting here to get a .jsonl file. I am working on
Mining Twitter Data with Python: Collecting data

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 12.4):
- Python version 3.9
- Python client version (`pip list | grep kubernetes`)

**Comment by Akasurde** [comment]
@Tarandeepsingh436 Thanks for reporting this issue. It seems that this issue is related to `tweepy` and this repo manages `Kubernetes-client` for Python. I would request you to migrate the issue to the respective repository.
Thanks,

**Comment by roycaihw** [comment]
Thanks @Akasurde for looking into the issue!
