### ISSUE TITLE
Invalid markdown format in kubernetse/docs/V1EnvVar.md

### ISSUE THREAD

**Issue by PyoJunCode** [kubernetes-client/python#1836]
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1EnvVar.md

**Description of the issue (please include outputs or screenshots if possible)**:

In table, format of description is broken due to `$` mark and `\&quot;`

## Properties
Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**name** | **str** | Name of the environment variable. Must be a C_IDENTIFIER. | 
**value** | **str** | Variable references $(VAR_NAME) are expanded using the previously defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. &quot;$$(VAR_NAME)\&quot; will produce the string literal \&quot;$(VAR_NAME)\&quot;. Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to \&quot;\&quot;. | [optional] 
**value_from** | [**V1EnvVarSource**](V1EnvVarSource.md) |  | [optional]

**Comment by YidaHu** [comment]
Let me change that.
