### ISSUE TITLE
[Starter Project] Implement `kubectl drain` command

### ISSUE THREAD

**Issue by TracyBin** [kubernetes-client/python#188]
`kunectl drain` is a client side functionality that can be ported to this client from: https://github.com/kubernetes/kubernetes/blob/ca89308227abdf4f2c895118528c354c32aa3046/pkg/kubectl/cmd/drain.go#L239

This is a great starter project as the sequence of commands in the `kubectl` code are calling simple APIs. The best place for it is a new `util` package in `/kubernetes`.

Original post:

> hi,I have achieved schedule and unschedule using  patch_node function.But which function can drain node in preparation for maintenance?

**Comment by mbohlool** [comment]
You may find your answer here: https://kubernetes.io/docs/api-reference/v1.6/

**Comment by pokoli** [comment]
I think we have nothing to do with this issue, do we? Can we close it?

**Comment by huseyinyilmaz** [comment]
It would be great if somebody would confirm this.
It seems to me like kubectl cordon and kubectl drain functions is not implemented in api level. They are client functionality.
drain implemented here:

https://github.com/kubernetes/kubernetes/blob/ca89308227abdf4f2c895118528c354c32aa3046/pkg/kubectl/cmd/drain.go#L239

Seems like drain makes node unshedulable=true and delete all pods.

In short, this client does not have drain functionality. If I can find another client that has I will post it here.

**Comment by mbohlool** [comment]
It look like it is a client side functionality. I am not sure if they plan to move it to server but looking at the code, it should not be hard to convert that code to python using this client. Would you mind creating a feature request with this information and mark it as help needed so somebody look at it? This is a great starter project for anybody wants to start developing in this repo.

**Comment by huseyinyilmaz** [comment]
@mbohlool  I will need that functionality soon and it seemed simple enough to implement it on top of this library. If it is not implemented when I do it, I can contribute it to the library. I have a question about it though. I thought this library was completely autogenerated from swagger source. So, if I were to add a functionality like this how would I attach my functionality to auto generated code. Can you direct me to an example in codebase? I could not find any examples.

**Comment by mbohlool** [comment]
All files in the kubernetes/base (that some of them are sym-linked back in) are manually coded. You can add a utility package or something like that is the [base repo](https://github.com/kubernetes-client/python-base/tree/master) and update the submodule here to use them. examples are config/* and watch/* files. [This document](https://github.com/kubernetes-client/community/blob/master/design-docs/clients-library-structure.md) explains the structure of our clients in more detail.
