### ISSUE TITLE
Not possible to close watch stream immediately

### ISSUE THREAD

**Issue by Lirt** [kubernetes-client/python#1881]
Hello Kubernetes Python Community,

I would like to ask for a help about what is the intended way to close the watch stream immediately. 

Consider my simple reproducible example python3 code where I want to close the stream by sending signal:
```python3
#!/usr/bin/env python3

import signal
from kubernetes import client, config, watch

watcher_cm = watch.Watch()


def cleanup(sig, frame):
    print("Cleaning up watcher streams")
    watcher_cm.stop()
    print("Cleanup Finished")


def main():
    config.load_kube_config()
    signal.signal(signal.SIGINT, cleanup)
    signal.signal(signal.SIGTERM, cleanup)

    v1 = client.CoreV1Api()
    event: client.CoreV1Event

    try:
        for event in watcher_cm.stream(
                func=v1.list_namespaced_config_map,
                namespace="kube-system",
                label_selector="app=kube-proxy"):
            print('Registered new ConfigMap event')
    except Exception as e:
        print(e)


main()
```

1. I run the script;
1. It registers one ConfigMap;
1. Ten I hit Ctrl+C;
1. I expect that the watch stream will try to end as soon as possible, but it is hanging. Probably it waits for one more `next()` event before it closes?;
1. While the script is hanging, in the second terminal I execute `kubectl label cm kube-proxy foo=bar` to create new event;
1. The script finishes now;

```bash
$ python3 test.py
Registered new ConfigMap event
^CCleaning up watcher streams
Cleanup Finished
# Here the script is hanging...
# But when I do `kubectl label cm kube-proxy foo=bar` in the second terminal, it registers one more event and closes the watch stream.
Registered new ConfigMap event
```

The question is how do I exit the watch stream without waiting for one more event?

**Environment**:
- Kubernetes version (`kubectl version`): v1.23.9
- OS (e.g., MacOS 10.13.6): Fedora 35
- Python version (`python --version`): 3.10.4
- Python client version (`pip list | grep kubernetes`): kubernetes 24.2.0

Thank you very much for any help.

**Comment by sharmadhiraj86** [comment]
I would like to contribute in solving this issue. So please assign me this issue as I want to work on this and solve this asap. @Lirt

**Comment by Lirt** [comment]
Hi @sharmadhiraj86,

I cannot assign anyone as I am not maintainer of the project. Maybe @fabianvf or someone else from OWNERS file could help here?

But I'd say if you open a PR it will probably be automatically assigned to someone from owners.

**Comment by sharmadhiraj86** [comment]
@fabianvf @lavalamp @roycaihw @SEJeff

**Comment by SEJeff** [comment]
Instead of tagging every single contributor (which is very annoying), just do the work and open a pull request please.

**Comment by sharmadhiraj86** [comment]
> Instead of tagging every single contributor (which is very annoying), just do the work and open a pull request please.

But before that, I need this task assigned to me officially as I have to show this as a proof.

**Comment by SEJeff** [comment]
No you don’t. I’m one of the authors of this lib.

**Comment by iciclespider** [comment]
Try coding your `cleanup` method like this:
```python
def cleanup(sig, frame):
    print("Cleaning up watcher streams")
    raise Exception('Exit the watcher event loop')
```
From [socket.recv](https://docs.python.org/3/library/socket.html#socket.socket.recv):

Changed in version 3.5: If the system call is interrupted and the signal handler does not raise an exception, the method now retries the system call instead of raising an [InterruptedError](https://docs.python.org/3/library/exceptions.html#InterruptedError) exception (see [PEP 475](https://www.python.org/dev/peps/pep-0475) for the rationale).

**Comment by Lirt** [comment]
Hi @iciclespider, 

Thank you for your advice and useful links. It works now :pray:!

From my side this solves the issue. If you would like I can add an example to better clarify how to interrupt the watch stream correctly. If not feel free to close the issue.

**Comment by qifenggang** [comment]
when i use thread , stream also not exit immediately ,
