### ISSUE TITLE
I am trying to deploy kong rate limit plugin. Is there any documents explain which class to use to ?

### ISSUE THREAD

**Issue by anilkvp** [kubernetes-client/python#1885]
I am trying to deploy Kong route with ingress with rate limit. I am able to deploy Kong route using V1Ingress, but I didn't find any information on create and deploy a plugin for example 'KongPlugin'.

**Comment by roycaihw** [comment]
I think this is a question for the Kong project, e.g. how to deploy the KongPlugin to Kubernetes using kubectl. If there is documentation on how to do it using kubectl, you can see what APIs it uses and do the same using this Python client.

**Comment by anilkvp** [comment]
I am able to add ingress to namespace using python-client, but couldn't find anything for kind 'KongPlugin'

**Comment by roycaihw** [comment]
I'm not familiar with KongPlugin. I suspect it's a custom resource. You may try using the [dynamic client](https://github.com/kubernetes-client/python/tree/master/examples/dynamic-client)
