### ISSUE TITLE
Does the library support "kubectl top pod" api?

### ISSUE THREAD

**Issue by fred214** [kubernetes-client/python#1890]
Hi,
I want to using python library to get "top" info of pod, but I cannot find any example or document, does the library support it?

**Comment by yliaog** [comment]
the library provides the API to list pods, you may need to implement the 'top' feature using the API.

**Comment by rclemsmith** [comment]
Hello @yliaog , I have started working on this Top featiure for python client. Also i am newbie to opensource contributions. I tried hitting the request path "apis/metrics.k8s.io/v1beta1/nodes" using the ApiClient.call_api method. I am getting the 200 Response, but the data is None

`(None, 200, HTTPHeaderDict({'Audit-Id': 'f47867fc-0eb9-4310-84e6-90d9d88a7d7f', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Sun, 09 Oct 2022 15:57:29 GMT', 'X-Kubernetes-Pf-Flowschema-Uid': 'c0c9f6a5-5908-4c19-94cb-3210e8e8add8', 'X-Kubernetes-Pf-Prioritylevel-Uid': '341e3230-0c8c-4d9e-966a-755d61b6867b', 'Transfer-Encoding': 'chunked'}))`

Can you help resolve this issue ?

**Comment by yliaog** [comment]
could you try getting the data using kubectl ?

**Comment by madclement** [comment]
Yes, I am getting the expected result using kubectl

<img width="592" alt="image" src="https://user-images.githubusercontent.com/93644717/194790610-f6fa3e4e-f9f4-4728-8267-c65ea3ebcb65.png">

I am also able to get the data when I call the api directly like this

`curl http://localhost/apis/metrics.k8s.io/v1beta1/nodes/ip-20-0-53-61.ec2.internal --header "Authorization: Bearer eyJhbGciOiJSUz...........`


The problem occurs only when I use the ApiClient ( call_api method) class from the client package.

**Comment by rclemsmith** [comment]
Yes, I am getting the expected result using kubectl

<img width="592" alt="image" src="https://user-images.githubusercontent.com/93644717/194790610-f6fa3e4e-f9f4-4728-8267-c65ea3ebcb65.png">

I am also able to get the data when I call the api directly like this

`curl http://localhost/apis/metrics.k8s.io/v1beta1/nodes/ip-20-0-53-61.ec2.internal --header "Authorization: Bearer eyJhbGciOiJSUz...........`


The problem occurs only when I use the ApiClient ( call_api method) class from the client package.

**Comment by yliaog** [comment]
could you try some examples in this repo, below is a quick one, call from the dynamic client.

https://github.com/kubernetes-client/python/blob/38ba743227524798d6cd58baddb3a6454207451f/kubernetes/base/dynamic/client.py#L270

also try call APIs other than apis/metrics.k8s.io/v1beta1/nodes

it's likely there is some config issue with your calling the API.

**Comment by rclemsmith** [comment]
Thanks a lot @yliaog . I was able to get it working by adding the _preload_content parameter as False. I will complete the feature as soon as possible and share the Pull Request.
