### ISSUE TITLE
how to use 'create_namespaced_deployment_rollback'

### ISSUE THREAD

**Issue by wuchenyanghaoshuai** [kubernetes-client/python#1892]
Hi,

i want to use python library client.create_namespaced_deployment_rollback,
but my kubernetes version v1.23.0  this attribute not found 
i know this attribute before in client.ExtensionsV1beta1Api()
now wehere is the create_namespaced_deployment_rollback in ?

Please help me,
Thanks

**Comment by yliaog** [comment]
ExtensionsV1beta1Api is no longer supported in newer k8s versions. apps/v1 deployment does not have create_namespaced_deployment_rollback anymore.
