### ISSUE TITLE
load_kube_config() got an unexpected key word argument 'kube_config_path'

### ISSUE THREAD

**Issue by yabea** [kubernetes-client/python#1893]
When using load_config() and "kube_config_path" in kwargs:
https://github.com/kubernetes-client/python/blob/16935036252be0fdf164f8ce624bd71eb8d35e89/kubernetes/base/config/__init__.py#L24
load_config(kube_config_path="/")

Received this error:
load_kube_config() got an unexpected key word argument 'kube_config_path'.

because:
![image](https://user-images.githubusercontent.com/15773461/191698473-6a3e5563-a3f0-49db-982e-92b1ae597fba.png)

![image](https://user-images.githubusercontent.com/15773461/191698578-6c35a9fa-109d-40a8-acda-87debc9bb24d.png)

**Comment by yliaog** [comment]
it seems that you have identified the root cause. please send a PR for the fix.

**Comment by pmareke** [comment]
Hi @yliaog I'd to give it a try.

I'm not sure if the error is in the [if](https://github.com/kubernetes-client/python/blob/16935036252be0fdf164f8ce624bd71eb8d35e89/kubernetes/base/config/__init__.py#L36) of tbe base config or in the name of the parameters in the load_kube_config [method](https://github.com/kubernetes-client/python/blob/16935036252be0fdf164f8ce624bd71eb8d35e89/kubernetes/base/config/kube_config.py#L790) ?

Thanks!

**Comment by yabea** [comment]
Fixed.

https://github.com/kubernetes-client/python/pull/1906/commits/4d5070f4eacd6084c9b320e8fdf37244967f9eff

**Comment by pmareke** [comment]
> Fixed.
> 
> [4d5070f](https://github.com/kubernetes-client/python/commit/4d5070f4eacd6084c9b320e8fdf37244967f9eff)

I was waiting for their response, thanks.
