### ISSUE TITLE
How to convert dynamic client response to JSON

### ISSUE THREAD

**Issue by denduluri** [kubernetes-client/python#1901]
I am trying to convert the output of Dynamic client which is of type ResourceField https://github.com/kubernetes-client/python/blob/master/kubernetes/base/dynamic/resource.py . I want it to try to convert JSON for further parsing but I am not having luck in doing so. Is there any way to convert it to JSON?

**Comment by pmareke** [comment]
Hi @denduluri did you try to use the `json.dumps(your_resource.to_dict)`?
