### ISSUE TITLE
A Question regarding metadata.ownerReferences

### ISSUE THREAD

**Issue by zhanshen8D** [kubernetes-client/python#1905]
Hi,
This is like a question because I am not sure if it's a bug.
We use the kubernetes client to patch a rolebinding with patch_namespaced_role_binding(). It's successful to patch the annotations and labels.
We also need to remove the metadata.ownerreferences but it doesn't succeed. The patch_namespaced_role_binding returns without error but the ownerreferences of the related rolebinding is not removed.
BTW, we are able to remove the ownerreference with kubectl in the same environment:
# ./kubectl patch rolebinding "rolebindingName" --type='json' -p='[{"op":"remove", "path":"/metadata/ownerReferences"}]' -n "namespace"

So what could be the problem? And what should I do to make it?
Thanks.

**Environment**:
- Kubernetes version (`kubectl version`): 1.22
- OS (e.g., MacOS 10.13.6): SUSE linux 5.3.18-57-default
- Python version (`python --version`):  Python 3.6.15
- Python client version (`pip list | grep kubernetes`): 21.7.0

**Comment by zhanshen8D** [comment]
It seems I can make it with replace_namespaced_role_binding().
So patch_namespaced_role_binding() is not supposed to do it, right?

**Comment by roycaihw** [comment]
kubectl was doing a json patch. We suspect the python client is doing strategic merge patch by default. You may need to specify using json patch with this client. 

you can verify what patch was being sent by using
- `-v=9` with kubectl
- debug logging with this python client
