### ISSUE TITLE
Extract information from a kubeconfig?

### ISSUE THREAD

**Issue by boldandbusted** [kubernetes-client/python#1907]
Howdy. I'd like to find documentation (or tips here) on how to do the equivalent of the following kubectl command:

```
kubectl config view --raw --minify --flatten --output='jsonpath={.clusters[].cluster.certificate-authority-data}'
```

and assign the output here to a variable. Is this possible with this library, and if so, where can I find an example, please? Thanks. :)

**Comment by pmareke** [comment]
Hi @boldandbusted reading the config files I think you can read your config (once it's loaded) directly from the `config` object

https://github.com/kubernetes-client/python/blob/74952467e78b651742b7b5bf03594bf41eb8b158/kubernetes/base/config/kube_config.py#L662

Maybe this link helps you!

**Comment by roycaihw** [comment]
/assign @pmareke 
Thank you!

/close
