### ISSUE TITLE
1.25 Release

### ISSUE THREAD

**Issue by yliaog** [kubernetes-client/python#1908]
k8s 1.25 has been released, it's time to release the corresponding python client

**Comment by jmrodri** [comment]
Any movement on this issue?

**Comment by yliaog** [comment]
yes, please see the release notes.

**Comment by jmrodri** [comment]
OH! I clicked the latest release and assumed it wasn't done yet. Sorry for not checking the list of releases.

**Comment by juliantaylor** [comment]
imo it would be good to still have the fix for https://github.com/kubernetes-client/python/issues/1921 in the release (assuming the fix is as simple as proposed), it is a pretty severe performance issue

**Comment by yliaog** [comment]
https://github.com/kubernetes-client/python/releases/tag/v25.3.0 is released.
