### ISSUE TITLE
list_csi_node() error

### ISSUE THREAD

**Issue by adikatzen** [kubernetes-client/python#1909]
I'm trying to get a list of all csi nodes client.StorageV1Api().list_csi_node() function and get the following error
ValueError: Invalid value for `drivers`, must not be `None`
I saw that there is already an issue regarding the same problem (#1778)  but it was closed and I couldn't find the answer..

**Comment by ramvikrams** [comment]
> I'm trying to get a list of all csi nodes client.StorageV1Api().list_csi_node() function and get the following error ValueError: Invalid value for `drivers`, must not be `None` I saw that there is already an issue regarding the same problem (#1778) but it was closed and I couldn't find the answer..

because of inactivity the issue was closed by the bot

**Comment by roycaihw** [comment]
hi, I think we still need to verify the question https://github.com/kubernetes-client/python/issues/1778#issuecomment-1108812973. Could you try that?

**Comment by ramvikrams** [comment]
> hi, I think we still need to verify the question [#1778 (comment)](https://github.com/kubernetes-client/python/issues/1778#issuecomment-1108812973). Could you try that?

yes sir
