### ISSUE TITLE
leader election mistakenly set "threading.daemon = True"

### ISSUE THREAD

**Issue by AngelJisoo** [kubernetes-client/python#1914]
**What happened (please include outputs or screenshots)**:
When applying leader election to my service on kubernetes, I found that when leader pod lost leadership, it didn't turn to Completed status. Therefore, the pod was still serving and there would be more than 1 pod are serving.
I found the following bug in https://github.com/kubernetes-client/python/blob/master/kubernetes/base/leaderelection/leaderelection.py
![image](https://user-images.githubusercontent.com/68831154/195047730-dded1343-aa9a-4f5f-9a9e-84a59015895e.png)
I wonder if "threading.daemon = True" is valid here because i have never seen any example setting daemon like this. 
Have a look on the following test about threading.daemon. It might prove that "threading.daemon = True" is invalid in python threading.
![image](https://user-images.githubusercontent.com/68831154/195047333-583d848f-0f43-4b3e-b719-dab9419f9d78.png)
If daemon here was mistakenly set and service thread was not a daemon thread, it might be the cause why leader pod didn't complete and restart even if leader had lost leadership.

**Anything else we need to know?**:
I suggest we should use the official method to set daemon:
`threading.Thread(target=self.election_config.onstarted_leading, daemon=True).start()`

It seems the above is the exact problem but maybe I still need more comments and ideas.
Thanks.

**Comment by nitishmalang** [comment]
please assign me

**Comment by roycaihw** [comment]
/assign @nitishmalang 
Thank you!
