### ISSUE TITLE
how can the V1Pod.spec.termination_grace_period_seconds be decreased on termination via API

### ISSUE THREAD

**Issue by daniel-balosh** [kubernetes-client/python#1928]
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1PodSpec.md

https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1DeleteOptions.md

**Description of the issue (please include outputs or screenshots if possible)**:
how can the V1Pod.spec.termination_grace_period_seconds be decreased on termination via API?
Using official python client would be great.
But also plain http would be nice.

In the docs here it says,
`May be decreased in delete request`
but not on what actual function it is found.
I could not find a function that receive `termination_grace_period_seconds`, only `grace_period_seconds`
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1PodSpec.md

I tried without success:

- patch_namespaced_pod - got can't update this property after create
- delete_namespaced_pod - with Foreground policy and grace_period_seconds the actual termination grace stays the same
- delete_namespaced_job  - with Foreground policy and grace_period_seconds the actual termination grace stays the same

Notice that the pod "looks" deleted, but the actual process still runs on the node until the original termination_grace_period_seconds is finished.

Thanks for the help!

**Comment by roycaihw** [comment]
Could you file an issue in the upstream kubernetes repo to see if this is actually allowed? If we can get an example of how to do it in client-go, we can achieve the same using this python client.

**Comment by roycaihw** [comment]
I think filing an issue in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) may give the issue more visibility. I think we need to understand how to use this API (the API documentation is confusing). Knowing how to do it in client-go or kubectl can help.
