### ISSUE TITLE
Can't import name `models`

### ISSUE THREAD

**Issue by s1113950** [kubernetes-client/python#194]
In our codebase we've got a kubernetes import, but due to what looks like a name collision it can't be imported. I've posted the relevant traceback below.

```
import kubernetes
  File ".venv/local/lib/python2.7/site-packages/kubernetes/__init__.py", line 15, in <module>
    import kubernetes.client
  File ".venv/local/lib/python2.7/site-packages/kubernetes/client/__init__.py", line 347, in <module>
    from .apis.apis_api import ApisApi
  File ".venv/local/lib/python2.7/site-packages/kubernetes/client/apis/__init__.py", line 4, in <module>
    from .apis_api import ApisApi
  File ".venv/local/lib/python2.7/site-packages/kubernetes/client/apis/apis_api.py", line 24, in <module>
    from ..api_client import ApiClient
  File ".venv/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 23, in <module>
    from . import models
ImportError: cannot import name models
```

We're using kubernetes version 2.0.0.a1

**Comment by mbohlool** [comment]
Can you share more information about your setup? Other packages, python version etc. I can't reproduce this.

**Comment by s1113950** [comment]
👍 python version is 2.7.6, in our own packages we have `from package_name.models...`
Below is a `pip freeze`, excluding our private packages:
```
alabaster==0.7.10
alembic==0.8.5
amqp==1.4.9
anyjson==0.3.3
astroid==1.5.2
Babel==2.4.0
backports.functools-lru-cache==1.3
backports.ssl-match-hostname==3.5.0.1
billiard==3.3.0.23
boto==2.46.1
boto3==1.3.1
botocore==1.4.93
celery==3.1.19
certifi==2017.4.17
chardet==3.0.2
click==6.7
coverage==4.3.4
decorator==4.0.11
docutils==0.13.1
enum34==1.1.6
eventlet==0.18.2
flake8==2.3.0
Flask==0.12
Flask-Login==0.2.11
flask-swagger==0.2.11
Flask-Testing==0.4.2
Flask-WTF==0.11
funcsigs==1.0.2
futures==3.1.1                                                                                                                      
gitdb==0.6.4
GitPython==1.0.1
greenlet==0.4.12
httplib2==0.10.3
httpretty==0.8.10
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.2
kombu==3.0.37
kubernetes==2.0.0a1
lazy-object-proxy==1.2.2
logilab-common==1.4.0
Mako==1.0.6
MarkupSafe==1.0
mccabe==0.6.1
mock==1.3.0
moto==0.4.24
MySQL-python==1.2.3
nauth==1.0
ndg-httpsclient==0.4.0
numpy==1.10.4
oauth2client==4.0.0
oauthlib==0.1.3
passlib==1.6.5
pbr==3.0.0
pep8==1.7.0
py==1.4.33
pyasn1==0.2.3
pyasn1-modules==0.0.8
pyflakes==0.8.1
Pygments==2.2.0
PyJWT==1.4.1
pylint==1.4.1
pyOpenSSL==0.13
pytest==3.0.3
pytest-cov==2.4.0
python-dateutil==2.2
python-editor==1.0.3
python-magic==0.4.10
pytz==2017.2
PyYAML==3.11
requests==0.12.1
rsa==3.4.2
simplejson==3.8.0
singledispatch==3.4.0.3
six==1.10.0
smmap==0.9.0
snowballstemmer==1.2.1
Sphinx==1.3.1
sphinx-rtd-theme==0.1.9
SQLAlchemy==1.0.14
urllib3==1.20
validators==0.11.0
websocket-client==0.40.0
Werkzeug==0.12.1
wrapt==1.10.10
WTForms==2.1
xmltodict==0.10.2

**Comment by cwyl02** [comment]
I got to reproduce the same ImportError:

`>>> import kubernetes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/kubernetes/__init__.py", line 19, in <module>
    import kubernetes.client
  File "/Library/Python/2.7/site-packages/kubernetes/client/__init__.py", line 540, in <module>
    from .apis.admissionregistration_api import AdmissionregistrationApi
  File "/Library/Python/2.7/site-packages/kubernetes/client/apis/__init__.py", line 4, in <module>
    from .admissionregistration_api import AdmissionregistrationApi
  File "/Library/Python/2.7/site-packages/kubernetes/client/apis/admissionregistration_api.py", line 23, in <module>
    from ..api_client import ApiClient
  File "/Library/Python/2.7/site-packages/kubernetes/client/api_client.py", line 27, in <module>
    from . import models
ImportError: cannot import name models`


I am using kubernetes 6.0.0. I am on OSX 10.13.6, python 2.7.10, pip 18.

And here is my `pip freeze` output

`altgraph==0.10.2
asn1crypto==0.24.0
awscli==1.15.55
bcrypt==3.1.4
bdist-mpkg==0.5.0
bonjour-py==0.3
boto==2.48.0
boto3==1.7.54
botocore==1.10.54
cachetools==2.1.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
colorama==0.3.9
cryptography==2.2.2
docutils==0.14
ecdsa==0.13
enum34==1.1.6
Fabric==1.12.0
fabric2==2.1.3
futures==3.2.0
google-auth==1.5.0
idna==2.7
invoke==1.0.0
ipaddress==1.0.22
jmespath==0.9.3
kubernetes==6.0.0
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
oauthlib==2.1.0
paramiko==1.18.5
py2app==0.7.3
pyasn1==0.4.3
pyasn1-modules==0.2.2
pycparser==2.18
pycrypto==2.6.1
PyNaCl==1.2.1
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==2.7.3
pytz==2013.7
PyYAML==3.12
requests==2.19.1
requests-oauthlib==1.0.0
rsa==3.4.2
s3transfer==0.1.13
scipy==0.13.0b1
six==1.11.0
urllib3==1.23
websocket-client==0.48.0
xattr==0.6.4
zope.interface==4.1.1`
