### ISSUE TITLE
Getting some kubernetes resources from the python client impossible

### ISSUE THREAD

**Issue by trent-abc** [kubernetes-client/python#1940]
I'm just getting started in the python client, I'm trying to list some kubernetes resources. I tried all the list & read api from https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md but none of them gave me the resource I'm looking for.  We happen to be using knative in our deployment but the task is simple, get a kubernetes resource and print the result.  Here's my kubectl command, that I'm trying to convert into the python client:

```
kubectl get DomainMapping --all-namespaces -o json
```
Within the json I find the information I'm looking for, but how is it none of the CoreV1Api can simply get a resource, am I looking in the wrong api doc?

**Comment by showjason** [comment]
Hi, since `DomainMapping` is  a CRD, please use the dynamic client, or custom object API. Perhaps, you can reference #1894, get helpful information.

**Comment by trent-abc** [comment]
Thanks for that reference, got it working!  In my case I didn't know the name of the resource, it's what I'm trying to query so the tricky part was including name='' in the dynamic query

```
import kubernetes

kubernetes.config.load_kube_config()
DYNAMIC_CLIENT = kubernetes.dynamic.DynamicClient(
    kubernetes.client.api_client.ApiClient()
)

def get_simple_item(dynamic_client: kubernetes.dynamic.DynamicClient, kind, verbose: bool=False):
    api_version = "serving.knative.dev/v1alpha1"
    namespace = "my-namespace"
    crd_api = dynamic_client.resources.get(api_version=api_version, kind=kind)
    print(crd_api.get(namespace=namespace, name=''))

get_simple_item(DYNAMIC_CLIENT, "DomainMapping", verbose=True)
```
