### ISSUE TITLE
V1beta1PodSecurityPolicy removed in 25.3.0, so cannot support earlier k8s versions with client

### ISSUE THREAD

**Issue by rvlane4** [kubernetes-client/python#1941]
**What happened (please include outputs or screenshots)**:
The kubernetes client removed the V1beta1PodSecurityPolicy class, which I understand since it was removed in kubernetes 1.25.
Howevrer, it would be nice for these removed classes which are supported in earlier versions of kubernetes to be archived and still available.  I have an operator using the client and want to support earlier versions of kubernetes with my newest operator, but can no longer support deploying in istio w/o CNI with a version built from 25.3.0 since I can no longer create a PSP resource.

**What you expected to happen**:
Would like archive access to deprecated classes if possible.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):  1.24
- OS (e.g., MacOS 10.13.6): centos7/rocky8
- Python version (`python --version`): 3.6.8
- Python client version (`pip list | grep kubernetes`): 25.3.0

**Comment by yliaog** [comment]
could you still use 24.x.y client for your use case? the python client is generated from upstream k8s, it's in sync with the upstream.

**Comment by rvlane4** [comment]
Yeah, I understand that you are following upstream, but we try to keep our Kubernetes client up-to-date, but we also have to support installations on previous versions of Kubernetes.  Maintaining backward compatibility is important for this reason.  I expect I could create the PodSecurityPolicy a raw custom object to get around this.

Thanks,

Rick Lane
