### ISSUE TITLE
certifi version in requirements doesn't correspond to certifi versioning pattern

### ISSUE THREAD

**Issue by inc0** [kubernetes-client/python#1942]
**What happened (please include outputs or screenshots)**:

Currently, in our requirements, there is `certifi>=14.05.14 # MPL`, meanwhile, [PyPI certifi release history](https://pypi.org/project/certifi/#history) shows that they follow pattern based on year and month of release. This causes pip error 
```
pkg_resources.DistributionNotFound: The 'certifi>=14.05.14' distribution was not found and is required by kubernetes
```

**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure why it started to appear in my environment today, or how it worked before. This may be due to some conflicts on my environment, but regardless, our requirements version should fit release version pattern.

**Comment by yliaog** [comment]
could you send a pr to fix it? thanks.

**Comment by ramvikrams** [comment]
> could you send a pr to fix it? thanks.

could you please for what could be a fix for this
