### ISSUE TITLE
'str' object has no attribute 'path' error when attepting to load_kube_config or load_kube_config_from_dict 

### ISSUE THREAD

**Issue by ryanf351** [kubernetes-client/python#1945]
**What happened (please include outputs or screenshots)**:
Error Statement
  "errorMessage": "'str' object has no attribute 'path'",
  "errorType": "AttributeError",
  "stackTrace": [
    "  File \"/var/task/index.py\", line 61, in lambda_handler\n    config.load_kube_config_from_dict(kube_content)\n",
    "  File \"/opt/python/kubernetes/config/kube_config.py\", line 848, in load_kube_config_from_dict\n    loader.load_and_set(config)\n",
    "  File \"/opt/python/kubernetes/config/kube_config.py\", line 584, in load_and_set\n    self._load_authentication()\n",
    "  File \"/opt/python/kubernetes/config/kube_config.py\", line 290, in _load_authentication\n    if self._load_user_token():\n",
    "  File \"/opt/python/kubernetes/config/kube_config.py\", line 520, in _load_user_token\n    base_path = self._get_base_path(self._user.path)\n"
  ]

config.load_kube_config_from_dict(kube_content)

**Anything else we need to know?**:
Attempting to use API within AWS lambda
Have create a kubeconfig file from dist
    kube_content = dict()
    
    kube_content['apiVersion'] = 'v1'
    kube_content['clusters'] = [
        {
        'cluster':
            {
            'server': endpoint,
            'certificate-authority-data': certificate
            },
        'name':'kubernetes'
                
        }]

    kube_content['contexts'] = [
        {
        'context':
            {
            'cluster':'kubernetes',
            'user':'aws'
            },
        'name':'aws'
        }]

    kube_content['current-context'] = 'aws'
    kube_content['Kind'] = 'config'
    kube_content['users'] = [
    {
    'name':'aws',
    'user':'ambda'
    }]

Whether writing it to file
with open("/tmp/kubeconfig", 'w') as outfile:
    yaml.dump(kube_content, outfile, default_flow_style=False)

or using the kube_content directly 

**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 10.13.6): AWS Lambda
- Python version (`python --version`): 3.8
- Python client version (`pip list | grep kubernetes`) Both v24.2.0 & v25.3.0 though older version v6 works but does not have AppsV1Api

**Comment by bentastic27** [comment]
I wonder if this is somehow unique to Lambda, this works for me on MacM1, Python 3.10, kubernetes 25.3.0.

```
from kubernetes import config, client
import yaml

with open("/Users/ben/.kube/config") as file:
  kubeconfig = yaml.safe_load(file)

config.load_kube_config_from_dict(config_dict=kubeconfig)
v1 = client.CoreV1Api()

print(v1.list_namespace())
```

**Comment by roycaihw** [comment]
/assign @bentastic27 
Thank you for verifying this!

**Comment by Sayanc2000** [comment]
@bentastic27 
This issue is not present when you are trying with the default location i.e: "/Users/ben/.kube/config".
But if you try any other path the issue appears.
If you write it in a python script and then make the config file in the same folder as done by @ryanf351 and then use a path such as this: 
`f"{os.getcwd()}/config"`
OR EVEN
`f"{os.getcwd()}/.kube/config"`

The initial issue appears:
`AttributeError: 'str' object has no attribute 'path'`

Please let us know how to fix this issue.

**Comment by bentastic27** [comment]
@Sayanc2000 I wasn't using the kubeconfig from issue opener in the example of my initial comment. I copied it to where I was running that python script and ran it like this and it still worked:

```
from kubernetes import config

import os, yaml
with open(f"{os.getcwd()}/config") as file:
  kubeconfig = yaml.safe_load(file)

config.load_kube_config_from_dict(config_dict=kubeconfig)
```

@ryanf351 It actually appears that this may an issue with the structure of your kube_content dict. The user in this case isn't supposed to be a string. It's supposed to be a dict, like this for example:

```
kube_content['users'] = [
  {
  'name':'aws',
  "user": {
    "client-certificate-data": "base-64-encoded-certificate",
    "client-key-data": "base-64-encoded-certificate-key"
    }
  }
]
```

So there is missing validation to be sure that the user field is structured correctly, but in either case it was formatted incorrectly.
