### ISSUE TITLE
feature request: auth-provider oidc

### ISSUE THREAD

**Issue by vasu1124** [kubernetes-client/python#195]
I just injected an additional case in `kube_config.py` in function `_load_gcp_token()`
```       
if self._user['auth-provider']['name'] == 'oidc':
  self.token = "Bearer %s" % self._user['auth-provider']['config']['id-token']
  return self.token
```
Works for me, but does not cover the refresh of the token and other features of oidc.

Would be nice to also get proper support for oidc (and not only gcp)

Thanks!

**Comment by lichen2013** [comment]
This issue is the same as https://github.com/kubernetes-client/python/issues/368

**Comment by benley** [comment]
It appears this may be addressed via https://github.com/kubernetes-client/python-base/pull/48; should this issue be closed?
