### ISSUE TITLE
Cannot create roles by create_namespaced_role function

### ISSUE THREAD

**Issue by gun082544** [kubernetes-client/python#1954]
**What happened (please include outputs or screenshots)**:
Ans: I cannot run create_namespced_role function and its return error

> HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Role in version \"v1\" cannot be handled as a Role: json: cannot unmarshal object into Go struct field Role.rules of type []v1.PolicyRule","reason":"BadRequest","code":400}

This is my code.
<img width="886" alt="Screenshot 2565-11-22 at 19 11 22" src="https://user-images.githubusercontent.com/56395331/203311504-63a5aaae-6a72-444a-a0ff-81e6726101ea.png">

**Environment**:
- Python 3.9
- Kubernetes 25.3.0
- Kubernetes node v1.23.13-eks-fb459a0

Thank you.

**Comment by bentastic27** [comment]
@gun082544 I was curious about this. The [spec](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Role.md) calls for a list of rules. So changinging to this works (note the `[]`):

```
client.V1Role(metadata=client.V1ObjectMeta(name="some-test"),
                       rules=[client.V1PolicyRule(api_groups=['*'], resources=['secret'], verbs=['get'])])
```

**Comment by gun082544** [comment]
@bentastic27  It works! Thank you.
