### ISSUE TITLE
Issue with DynamicClient

### ISSUE THREAD

**Issue by Jsalz2000** [kubernetes-client/python#1959]
**What happened (please include outputs or screenshots)**:
```
Traceback (most recent call last):
  File "kubernetes_test.py", line 24, in <module>
    client
  File "/anaconda3/envs/python3612/lib/python3.6/site-packages/kubernetes/dynamic/client.py", line 84, in __init__
    self.__discoverer = discoverer(self, cache_file)
  File "/anaconda3/envs/python3612/lib/python3.6/site-packages/kubernetes/dynamic/discovery.py", line 224, in __init__
    Discoverer.__init__(self, client, cache_file)
  File "/anaconda3/envs/python3612/lib/python3.6/site-packages/kubernetes/dynamic/discovery.py", line 48, in __init__
    default_cachefile_name = 'osrcp-{0}.json'.format(hashlib.md5(default_cache_id, usedforsecurity=False).hexdigest())
TypeError: openssl_md5() takes no keyword arguments
```

**What you expected to happen**:
Was trying to create the dynamic client so I can apply a deployment to the cluster

**How to reproduce it (as minimally and precisely as possible)**:
```
from kubernetes import client, config, utils, dynamic
config.load_kube_config()
api = dynamic.DynamicClient(
    client = client.ApiClient()
)
```

**Anything else we need to know?**:
I am trying to use DynamicClient in order to use an API extension from an operator (for ex prometheus operator). If I am not mistaken, using a DynamicClient is the only way to do this? Just trying to define the dynamic client will give me the above error.

**Environment**:
- Kubernetes version (`kubectl version`): v1.25.2
- OS (e.g., MacOS 10.13.6): RHEL 7.9
- Python version (`python --version`) 3.6.12
- Python client version (`pip list | grep kubernetes`) kubernetes==25.3.0

EDIT: 
It seems the kwarg usedforsecurity is not supported on my env. 

https://github.com/pynbody/pynbody/issues/581

https://stackoverflow.com/questions/54717862/how-do-i-know-if-the-usedforsecurity-flag-is-supported-by-hashlib-md5

**Comment by karinakanjaria** [comment]
Similar issue with me:
```
File "/opt/conda/lib/python3.8/site-packages/openshift/dynamic/client.py", line 40, in __init__
    K8sDynamicClient.__init__(self, client, cache_file=cache_file, discoverer=discoverer)
  File "/opt/conda/lib/python3.8/site-packages/kubernetes/dynamic/client.py", line 84, in __init__
    self.__discoverer = discoverer(self, cache_file)
  File "/opt/conda/lib/python3.8/site-packages/kubernetes/dynamic/discovery.py", line 224, in __init__
    Discoverer.__init__(self, client, cache_file)
  File "/opt/conda/lib/python3.8/site-packages/kubernetes/dynamic/discovery.py", line 48, in __init__
    default_cachefile_name = 'osrcp-{0}.json'.format(hashlib.md5(default_cache_id, usedforsecurity=False).hexdigest())
TypeError: openssl_md5() takes at most 1 argument (2 given)
```

**Comment by rhkngw** [comment]
had the same issue, just worked around it by removing the usedforsecurity=False.  site-packages/kubernetes/dynamic/discovery.py 
hashlib.md5(default_cache_id, usedforsecurity=False).hesdigest())

**Comment by karinakanjaria** [comment]
Thank you @rhkngw ! I'm using the kubernetes-client to deploy an application on openshift so it's not a local change for me. Any options there? I could technically write a script to edit that within the container on openshift but that wouldn't be best practice.

**Comment by adrianimboden** [comment]
This got already fixed on master: https://github.com/kubernetes-client/python/commit/1ac54eff7b7427a4470f642a7e827fe0cd5e5472
