### ISSUE TITLE
Inconsistent timeout of WSClient.update

### ISSUE THREAD

**Issue by t-yrka** [kubernetes-client/python#1963]
**What happened (please include outputs or screenshots)**:

https://github.com/kubernetes-client/python/blob/master/kubernetes/base/stream/ws_client.py#L182-L189
The timeout behavior of the `update` method is inconsistent.
Function `select.select` interprets timeout as floating-point seconds where the polling object (`poll` method) uses milliseconds.

**What you expected to happen**:

The timeout unit is the same in all cases.

**How to reproduce it (as minimally and precisely as possible)**:

Exec `update` with `select` and `poll`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 10.13.6):
- Python version (`python --version`) `3.10.8`
- Python client version (`pip list | grep kubernetes`) `25.3.0`

**Comment by roycaihw** [comment]
@t-yrka would you like to send a PR? Thanks
