### ISSUE TITLE
missing attribute from list_volume_attachment

### ISSUE THREAD

**Issue by Rawad84** [kubernetes-client/python#1964]
#!/usr/bin/python3
# Script name: usage_info.py
from __future__ import print_function
import time
import kubernetes.client
from kubernetes.client.rest import ApiException
from pprint import pprint
from kubernetes import client, config

config.load_kube_config()

api_instance = kubernetes.client.StorageV1Api()
api_response = api_instance.list_volume_attachment()
pprint(api_response)

the expected behavior is to list all the volumes attachments in the cluster, but I keep getting 
AttributeError: 'StorageV1Api' object has no attribute 'list_volume_attachment'

**Comment by roycaihw** [comment]
The method exists in the latest API: https://github.com/kubernetes-client/python/blob/1ad6e80f29369651e17a6ba767ddccc99f46600b/kubernetes/docs/StorageV1Api.md#list_volume_attachment. Could you check which version you're using?
