### ISSUE TITLE
Client not able to reach Cluster API behind a proxy if using multiple client function

### ISSUE THREAD

**Issue by FlorianJDF** [kubernetes-client/python#1967]
Hello all,

**What happened (please include outputs or screenshots)**:
I need to access multiple k8s clusters at once, all behind a proxy.
To be able to reach many k8s clusters at once, I use the function _new_client_from_config_dict_.

Unfortunatly this do no allow to have an HTTP(S) PROXY set.

This [#333](https://github.com/kubernetes-client/python/issues/333) solution do not work because the _new_client_from_config_dict_ is not using the _default object in _kube_client.Configuration_

**What you expected to happen**:
Been able to set a proxy variable or inject a client configuration when using the function _new_client_from_config_dict_

**How to reproduce it (as minimally and precisely as possible)**:
```python
# This is working
config.load_kube_config()
client.Configuration._default.proxy = "MY_HTTP_PROXY"
client.CoreV1Api().list_namespace()
```

```python
# Impossible to set a proxy with a new client from config
my_client = config.new_client_from_config_dict(kubeconfig2)
my_client.configuration.proxy = "MY_HTTP_PROXY"
client.CoreV1Api(api_client=my_client).list_namespace()
# >> Proxy error
```

**Environment**:
- Kubernetes version (`kubectl version`):
- > 1.23.8
- OS (e.g., MacOS 10.13.6):
- > MacOS 13.0.1
- Python version (`python --version`)
- > 3.9.13
- Python client version (`pip list | grep kubernetes`)
- > 25.3.0

Thanks,

**Comment by hilmeeen** [comment]
I got the same issue with new_client_from_config() 

```
# Impossible to set a proxy with a new client from config
my_api_client=config.new_client_from_config(my_kubeconfig_file)
my_api_client.configuration.proxy="MY_HTTP_PROXY"
eks_client = dynamic.DynamicClient(my_api_client)
api_deployment = eks_client.resources.get(api_version="apps/v1", kind="Deployment")
api.get(namespace='MY_NAMESPACE',name='MY_DEPLOYMENT')
# >> Proxy error
```

**Comment by FlorianJDF** [comment]
@hilmeeen you can use this fix if you want: https://github.com/kubernetes-client/python/pull/1968
Just waiting for my PR to be reviewed

**Comment by mkemmerz** [comment]
Any update on this?

**Comment by kwibus** [comment]
you could try this solution.
```python
config.load_kube_config()
k8s_config = client.Configuration().get_default_copy()
k8s_config .proxy = "MY_HTTP_PROXY"
client.Configuration().set_default(k8s_config) 
client.CoreV1Api().list_namespace()
```
