### ISSUE TITLE
Add __all__ or redundant alias to top level kubernetes

### ISSUE THREAD

**Issue by smackesey** [kubernetes-client/python#1970]
**What is the feature and why do you need it**:

Currently pyright/pylance (popular Python language server/type-checker) give an error for e.g. this:

```
import kubernetes
kubernetes.config  # error!

# ... "config" is not a known member of module (reportGeneralTypeIssues)
```

The reason for this is the lack of `__all__` and/or rendundant aliasing in `kubernetes/__init__.py`-- effectively `kubernetes` has no public interface recognized by pyright/pylance.

**Describe the solution you'd like to see**:

This is easily fixable by defining `__all__` or with redundant aliasing:

```python
import kubernetes.client as client
import kubernetes.config as config
import kubernetes.dynamic as dynamic
import kubernetes.watch as watch
import kubernetes.stream as stream
import kubernetes.utils as utils
import kubernetes.leaderelection as leaderelection
```

**Comment by roycaihw** [comment]
@smackesey would you like to send a PR? Thanks
