### ISSUE TITLE
need support for python 3.11

### ISSUE THREAD

**Issue by zffocussss** [kubernetes-client/python#1977]
**What is the feature and why do you need it**:
as python 3.11.0 is released officially. when will be kubernetes-client upgraded as well?

**Describe the solution you'd like to see**:
I hope this package can work under python 3.11.0

**Comment by jumbosushi** [comment]
@roycaihw @yliaog Can we close this & include 3.11 in [setuptools classifers](https://github.com/kubernetes-client/python/blob/master/setup.py#L69)?

**Comment by yliaog** [comment]
sure, please send a PR for [setuptools classifers](https://github.com/kubernetes-client/python/blob/master/setup.py#L69)
