### ISSUE TITLE
request timeout doesnt work 

### ISSUE THREAD

**Issue by arnoldyahad** [kubernetes-client/python#1978]
When using request timeout:
```
    api = eks_client.resources.get(api_version="keda.sh/v1alpha1", kind="ScaledObject",_request_timeout=30)
```
or:
```
        eks_client.patch(resource=resource_class, namespace=namespace, name=deployment, body=body, content_type="application/merge-patch+json",_request_timeout=30)
```
it doesnt work:
```
AttributeError: 'DynamicClient' object has no attribute '_request_timeout'
```

i am using the dynamic client:
```
    eks_client = dynamic.DynamicClient(
        api_client.ApiClient(configuration=config.load_kube_config())
    )
```

as i read here:
https://github.com/kubernetes-client/python/blob/release-25.0/kubernetes/client/api_client.py#L336
and here:
https://github.com/kubernetes-client/python/blob/master/examples/watch/timeout-settings.md

it should be possible to set timeouts for requests, am i missing something here? are there any examples of how to use the timeout properly or is it a bug?

**Environment**:
- Kubernetes version (`kubectl version`):
```
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.23.13-eks-fb459a0
```
- OS (e.g., MacOS 10.13.6):
```
12.5.1 (21G83)
```
- Python version (`python --version`)
```
 python --version
Python 3.9.15
```
- Python client version (`pip list | grep kubernetes`)
```
pip list | grep kubernetes
kubernetes               25.3.0
```

**Comment by Ithrael** [comment]
The _requests_time of the api client is used when requesting,  look  [L283](https://github.com/kubernetes-client/python/blob/38ba743227524798d6cd58baddb3a6454207451f/kubernetes/base/dynamic/client.py#L283).

So you can refer to this  [L37](https://github.com/kubernetes-client/python/blob/def8b28f0a65208ccc84be99c2a4d1f14f930270/examples/dynamic-client/node.py#L37) , increase _request_time here

`node = api.get(name=item.metadata.name, _request_time=3)`

**Comment by venukarnati92** [comment]
I will look at the dynamic client Implementation and will raise a PR if needed.

**Comment by venukarnati92** [comment]
I did tested the dynamic client and there is no issue with `_request_timeout` parameter .As @Ithrael mentioned `_requests_time` client side param to be used when requesting.

**Comment by venukarnati92** [comment]
Example Code Snippet:

`
from kubernetes import config, dynamic
from kubernetes.client import api_client


def main():
    # Creating a dynamic client
    client = dynamic.DynamicClient(
        api_client.ApiClient(configuration=config.load_kube_config())
    )

    # fetching the node api
    api = client.resources.get(api_version="v1", kind="Node")
    # api = client.resources.get(api_version="v1", kind="Node")
    # Listing cluster nodes

    print("%s\t\t%s\t\t%s" % ("NAME", "STATUS", "VERSION"))
    for item in api.get().items:
        node = api.get(name=item.metadata.name, _request_time=30)
        print(
            "%s\t%s\t\t%s\n"
            % (
                node.metadata.name,
                node.status.conditions[3]["type"],
                node.status.nodeInfo.kubeProxyVersion,
            )
        )


if __name__ == "__main__":
    main()
`

**Comment by Jean-PhilippeD** [comment]
In my case, I need to set a timeout on query which discover cluster/api version when creating the DynamicClient:

```
c = dynamic.DynamicClient(
        api_client.ApiClient(configuration=config.load_kube_config())
)

```
Line 145 in dynamic/discovery.py
```
self._cache['version'] = {
       'kubernetes': self.client.request('get', '/version', serializer=just_json)
}
```

How can I set a timeout at the first discover ?

**Comment by Jean-PhilippeD** [comment]
Ok I found a solution, using DynamicClient I can not set a timeout.
But I can discover if API is available by testing : 

```
from kubernetes import client
apiClient = client.ApiClient(conf)
coreApi = client.CoreApi(apiClient)
try:
  res = coreApi.get_api_versions(_request_timeout=2).versions
except urllib3.exceptions.MaxRetryError:
 # timeout error
```

**Comment by prabhatkgupta** [comment]
Make sure you are making sure older connections are terminated
