### ISSUE TITLE
Delete namedspace job - force option

### ISSUE THREAD

**Issue by mans2singh** [kubernetes-client/python#1982]
Hi:

I am trying to delete a job immediately and found [delete_namedspace_job method](https://github.com/kubernetes-client/python/blob/master/kubernetes/client/api/batch_v1_api.py#L850) with the `grace_period_seconds` option.   However it still takes some time (sometimes upto 3+ minutes) for the job to be killed even though I set the value of `grace_period_seconds` to `0`.

The kubectl delete help has the following option:

`      --grace-period=-1: Period of time in seconds given to the resource to terminate gracefully. Ignored if negative.
Set to 1 for immediate shutdown. Can only be set to 0 when --force is true (force deletion).`

However I could not find the `--force` option in the python client api.  

Questions:
1. Is the `0` the right value for `grace_period_seconds` option ?
2. Is there a `--force` option in the python client ?
3. Is there any reason the kubernetes is still taking 3+ minutes to kill the job ?

Thanks

**Comment by roycaihw** [comment]
could you run `kubectl --force` with `-v=9`? It should show you what API / flag kubectl uses. Then you should be able to use the same API and flag in this client to achieve the force deletion
