### ISSUE TITLE
Update ADAL dependency to MSAL

### ISSUE THREAD

**Issue by localden** [kubernetes-client/python#1983]
Hi folks - I am a PM on the Microsoft Identity SDK team. I've noticed that the project [takes a dependency on ADAL](https://github.com/kubernetes-client/python/blob/master/setup.py#L31). This library will hit end-of-support by June of this year (2023) - the recommended path forward here is to update this to MSAL (there is [a Python release](https://github.com/AzureAD/microsoft-authentication-library-for-python)).

What's the best path to make the change? This will affect the Azure token acquisition mechanism.

**Comment by brendandburns** [comment]
Kubernetes is deprecating in-tree authorization providers in favor of `exec` credentials, and Azure is moving to `kubelogin`  https://github.com/Azure/kubelogin

I'm not sure this work is worth the effort, instead it probably makes more sense to just rip out the native Azure code in favor of the `exec` approach, which is the default for AKS going forward from `1.23.x` anyway.

@roycaihw wdyt?

**Comment by yliaog** [comment]
that sounds right to me.

**Comment by brendandburns** [comment]
Ok, I will send a PR to remove this code from the client.
