### ISSUE TITLE
add type hinting by upgrading to OpenAPI Generator v6.2.0 or later

### ISSUE THREAD

**Issue by jmhodges-color** [kubernetes-client/python#1984]
**What is the feature and why do you need it**:

It'd be nice to have type hinting baked into this client. 

**Describe the solution you'd like to see**:

Type hinting can now be created with [openapi-generator v6.2.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v6.2.0) and more recent versions.

Currently, in the `kubernetest-client/gen` repo, the [default version of openapi-generator](https://github.com/kubernetes-client/gen/blob/39ed53daebe6f53854a96e1b01d81dc816b44ba2/openapi/python.sh#L48) used is v4.3.0. I'm sure there have been some significant changes between those versions.

(There's an [old, less specific ticket](https://github.com/kubernetes-client/python/issues/225) around maybe adding type hinting, but I figured this one with a tighter focus would be useful)

**Comment by roycaihw** [comment]
we have a PR upgrading the generator, but it's hitting some backwards compatibility issue: https://github.com/kubernetes-client/python/pull/1887

**Comment by benglewis** [comment]
I am happy to contribute this change if the team are willing to consider external PRs for this

**Comment by roycaihw** [comment]
@benglewis Yes PRs are welcome!
