### ISSUE TITLE
Using no_proxy attribute does not work as expected

### ISSUE THREAD

**Issue by jandbg** [kubernetes-client/python#1995]
Hi all! First I would like to said thanks for the this k8s client library, I think it´s a great tool! We use it a lot in our projects.
We are facing the following issue. We have a pod (lets said pod A) where we´re running a program based on: 
https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py

The goal of the pogram is to execute a command in another pod, lets said pod B. 

In the pod A we have defined an HTTPS_PROXY environment variable, and we would like to bypass this HTTPS_PROXY, so we set the atributte no_proxy on the kubernetes.client.Configuration class. We are not very sure how to use this attribute, we set no_proxy attribute with the pod B´s IP address but we still get  the "Error 407 Proxy authentication". So I guess we couldn´t bypass the proxy.

The question is, how I should proceed to execute the command in the pod B and bypass the HTTPS_PROXY? How I must setup the no_proxy attribute? I mean, I guess is a IPs string comma separated, I´m right? Something like this "100.67.5.3.170,100.65.2.169"

Thank you very much in advance, best regards!

**Environment**:
-  Kubernetes Version: v1.23.12+8a6bfe4
- PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
  NAME="Debian GNU/Linux"
  VERSION_ID="11"
  VERSION="11 (bullseye)"
  VERSION_CODENAME=bullseye
  ID=debian
- Python 3.8.16
- Python client version (`pip list | grep kubernetes`): kubernetes  24.2.0

**Comment by roycaihw** [comment]
this PR could be related https://github.com/kubernetes-client/python/pull/1968

**Comment by rheemskerk** [comment]
Did you try NO_PROXY instead of no_proxy?

**Comment by jandbg** [comment]
Hi all, I hope you´re doing well!

It seems neither no_proxy nor NO_PROXY is working, indeed if I type anything it won´t work too and no exception arises.
The only workaround I found was to set empty the HTTPS_PROXY environment variable before

***@***.***


***@***.***

Thank you and regards
Alejandro

From: rheemskerk ***@***.***>
Sent: Wednesday, May 10, 2023 20:35
To: kubernetes-client/python ***@***.***>
Cc: Alejandro Bailo ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]: Re: [kubernetes-client/python] Using no_proxy attribute does not work as expected (Issue #1995)


Did you try NO_PROXY instead of no_proxy?

**Comment by jandbg** [comment]
Finally we set the environment variable with os.environ before the call Configuration().get_default_copy(), because neither no_proxy nor NO_PROXY work as expected.
We really appreciate you efforts with this library. Thanks!

**Comment by gurujonnala** [comment]
> 

Dear @jandbg we ran in to the same problem as you did. We aren't able to bypass the proxy when executing a command from within the POD using the connect_get_namespaced_pod_exec method. We use API Key and Username, but not kubeconfig. We have set os.environ['NO_PROXY'] and ['no_proxy'] both, but without any avail. Could you let me know what worked for you in this case? Thanks..
