### ISSUE TITLE
CoreAPI Readme is too big for github

### ISSUE THREAD

**Issue by byungheon-jeong** [kubernetes-client/python#2000]
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md
![image](https://user-images.githubusercontent.com/45370147/215156884-7137aa78-a7a3-4282-b1c5-db417c64952e.png)

**Description of the issue (please include outputs or screenshots if possible)**:
The generated md file is > 1 MB, which prevents github from offering a preview. The raw md is hard to read

**Comment by yliaog** [comment]
this is known issue with github. we are limited by that. you may download the raw to work around it.
