### ISSUE TITLE
Pod annotations with a prefix seem to be forbidden

### ISSUE THREAD

**Issue by aschmied** [kubernetes-client/python#2001]
**What happened (please include outputs or screenshots)**:

I attempted to create a pod with the following annotation:

```
annotations={"prometheus.io/scrape:": "true"}
```

It was rejected with the following message:

```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"canary-pod-<redacted-id>\" is invalid: metadata.annotations: Invalid value: \"prometheus.io/scrape:\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')","reason":"Invalid","details":{"name":"canary-pod-<redacted-id>kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"prometheus.io/scrape:\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')","field":"metadata.annotations"}]},"code":422}
```

**What you expected to happen**:

The `/` is rejected by the regex, however kubernetes allows `/` as a separator between the annotation prefix and name ([ref](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set)). I expected it to be allowed. 

**Anything else we need to know?**:

Maybe this is a docs issue. The [docs I found for annotations](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1ObjectMeta.md) are not specific.

**Environment**:
- Kubernetes version (`kubectl version`): 1.23
- OS (e.g., MacOS 10.13.6): Linux
- Python version (`python --version`) Unsure. This error is coming from MWAA via KubernetesPodOperator
- Python client version (`pip list | grep kubernetes`): 11.0.0

**Comment by roycaihw** [comment]
this seems to be a server side rejection. We are not sure if this is an issue to this client. Can you achieve what you were trying to do with `kubectl`?

**Comment by aschmied** [comment]
I took a crack at getting a better repro for this and I couldn't. I can create an annotation name with "/" using both kubectl and the python client. It's just when I try to add it to the Airflow KubePodOperator that I see the problem. From [this](https://github.com/kubernetes/kubernetes/issues/54464) related issue it seems more likely that the annotation name is not getting quoted properly somewhere along the line.

Sorry for the confusion and thank you for responding.
