### ISSUE TITLE
EKS kubernetes.config.config_exception.ConfigException: Service host/port is not set. 

### ISSUE THREAD

**Issue by ashish-aesthisia** [kubernetes-client/python#2002]
**What happened (please include outputs or screenshots)**:
Error while trying to access the kubernetes functions from within the cluster. 

main.py
![Screenshot 2023-01-30 at 9 16 13 PM](https://user-images.githubusercontent.com/108272701/215524732-bc03c86f-dac2-4391-b071-43b8e70d5b56.png)

requirement.txt
![Screenshot 2023-01-30 at 9 14 54 PM](https://user-images.githubusercontent.com/108272701/215524863-23c9fabe-1448-47ff-9428-f4bd0edfd4d8.png)

Error
![Screenshot 2023-01-30 at 9 14 13 PM](https://user-images.githubusercontent.com/108272701/215525047-2481eaa0-095c-45fa-81f5-9bfc14212bcb.png)

**What you expected to happen**:
List all the pods

**How to reproduce it (as minimally and precisely as possible)**:
Python: 3.10-alpine(Dockerimage)
Kubernetes: 1.24
Hosted on: EKS

Tried all the available documentation. I do have KUBERNETES_SERVICE_HOST & KUBERNETES_PORT in env as well inside pod.yaml.

Any help would be appreciated. 
Thanks

**Comment by venukarnati92** [comment]
@ashish-aesthisia The issue is the way you are loading the config.Please change the  code from `config.load_incluster_config()` to `config.load_config()`

You need to use config.load_incluster_config() when you are running inside the cluster.

**Comment by ashish-aesthisia** [comment]
Hey @venukarnati92, I have tried both, I am running this code within the EKS cluster, hosted on the python container. config.load_config() also doesn't work here, because kubeconfig is not available inside the pod.

**Comment by venukarnati92** [comment]
@ashish-aesthisia Where you able to run other api calls like create secret or read secret from your cluster .This test is to rule out that you are able to load the kubeconfig within the cluster.

A quick test can be from your terminal run the following steps
` $ python3
Python 3.7.10 (default, Apr 13 2022, 13:56:42) 
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from kubernetes import config
>>> config.load_config()
>>> 
`

**Comment by ashish-aesthisia** [comment]
load_config() doesn't work but config.load_incluster_config() from within the container 
<img width="652" alt="Screenshot 2023-02-07 at 11 29 42 AM" src="https://user-images.githubusercontent.com/108272701/217161253-ba97e262-37e5-4140-a1e4-a716756c579b.png">

**Comment by venukarnati92** [comment]
@ashish-aesthisia In the screenshot shared above I see you were able to list the pods using config.load_incluster_config().So, what is the issue you are facing now?

**Comment by ashish-aesthisia** [comment]
I think it's working now, Thanks.
