### ISSUE TITLE
Create ThirdParty Resource Like ChaosMesh

### ISSUE THREAD

**Issue by Jim0530** [kubernetes-client/python#2006]
**Link to the issue (please include a link to the specific documentation or example)**:
I want to create Custom kind (ex:PodChaos) what api should I use to create custom kind???
**Description of the issue (please include outputs or screenshots if possible)**:
In CLI kubectl apply -f example.yaml , and it will automate create for me, What should I use?

**Comment by roycaihw** [comment]
You can use the custom object API client or the dynamic client. Here are some examples:
- https://github.com/kubernetes-client/python/tree/master/examples/dynamic-client
- https://github.com/kubernetes-client/python/blob/master/examples/cluster_scoped_custom_object.py
- https://github.com/kubernetes-client/python/blob/master/examples/namespaced_custom_object.py

/close
