### ISSUE TITLE
oauthlib (Python lib in requirements.txt) needs upgrade

### ISSUE THREAD

**Issue by It4lik** [kubernetes-client/python#2009]
**What happened (please include outputs or screenshots)**:

Trying to deploy kubernetes module on an updated Rocky 9 remote machine result in the following error : 

```
Failed to import the required Python library (kubernetes) on master's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
```

This error is present despite having `kubernetes` Python library previously installed on the remote machine.

If we login on the target machine, fire a Python3 interpreter, and try to manually `import kubernetes`, we got the following error :

```
ImportError: cannot import name 'SIGNATURE_RSA' from 'oauthlib.oauth1'
```

**What you expected to happen**:

It should just work ?

**Anything else we need to know?**:

The bug resides in the `kubernetes` module dependencies.
Your current `requirements.txt` contains  `requests-oauthlib # ISC`.
Going on `requests-oauthlib` repo, we can see that their `requirements.txt` contains the following : `oauthlib[signedtoken]==3.1.1` (available here https://github.com/requests/requests-oauthlib/blob/master/requirements.txt).
Upgrading `oauthlib` Python library to `>=3.2.0` solves the problem.

**Environment**:
```bash
$ pip list | grep kubernetes
kubernetes          25.3.0
```

**Comment by roycaihw** [comment]
Thanks for reporting @It4lik. Would you like to create a PR?

**Comment by danielpodwysocki** [comment]
I ran into this as well - submitted an MR here: https://github.com/kubernetes-client/python/pull/2016
