### ISSUE TITLE
Problem with tests - Invalid version: '26.0.0-snapshot'

### ISSUE THREAD

**Issue by tomplus** [kubernetes-client/python#2014]
**What happened (please include outputs or screenshots)**:

The latest version of setuptools refuses to install the library because the "master" version is not compliant with PEP 440. You can see it in this log: https://github.com/kubernetes-client/python/actions/runs/4217586381/jobs/7321474234

I suggest using ''26.0.0+snapshot" instead of "26.0.0-snapshot". What do you think?
I'll prepare PR if you agree. Thanks.

Related issue: https://github.com/pypa/setuptools/issues/3772

**What you expected to happen**:

All tests pass.

**How to reproduce it (as minimally and precisely as possible)**:

`tox -e py`

```
.......
   File "/home/runner/work/python/python/.tox/.pkg/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 219, in finalize_options
    parsed_version = parse_version(self.egg_version)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/python/python/.tox/.pkg/lib/python3.11/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '26.0.0-snapshot'
Backend: run command get_requires_for_build_editable with args {'config_settings': None}
running egg_info
Backend: Wrote response {'code': 1, 'exc_type': 'InvalidVersion', 'exc_msg': "Invalid version: '26.0.0-snapshot'"} to /tmp/pep517_get_requires_for_build_editable-p92ljork.json
.pkg: _exit> python /opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  py: FAIL code 1 (12.62 seconds)
  evaluation failed :( (13.14 seconds)
```

**Anything else we need to know?**:

(n/a)

**Environment**:

(n/a)

**Comment by yliaog** [comment]
[tomplus](https://github.com/tomplus) Thanks for raising the issue. i'm looking forward to your PR to have the issue fixed.

**Comment by tomplus** [comment]
@yliaog Pull request is ready https://github.com/kubernetes-client/python/pull/2018. Thanks.
