### ISSUE TITLE
copy tar.gz file from pod

### ISSUE THREAD

**Issue by sona201** [kubernetes-client/python#2015]
> Hi @ltamaster， 

i want to copy foo.tar.gz from pod, when i doing like this
```
    # Calling exec interactively

    src_path = pod/to/foo.tar.gz
    target_path = local/to/foo.tar.gz
    _exec_copy_command = ['/bin/sh', '-c', 'cat {src_path}'.format(src_path=src_path)]
    with open(target_path, 'a') as tar_file:
        resp = stream(self.api_instance.connect_get_namespaced_pod_exec,
                      pod_name,
                      namespace,
                      command=_exec_copy_command,
                      container=container,
                      stderr=True, stdin=True,
                      stdout=True, tty=False,
                      _preload_content=False)

        while resp.is_open():
            resp.update(timeout=1)
            if resp.peek_stdout():
                out = resp.read_stdout()
                # print("STDOUT: %s" % len(out))
                tar_file.write(out)
            if resp.peek_stderr():
                # print('STDERR: {0}'.format(resp.read_stderr()))
                logger.error(f'STDERR: {resp.read_stderr()}')
        resp.close()
```

however，Compare the MD5 of the two files, inconsistent

is there anything wrong？

_Originally posted by @sona201 in https://github.com/kubernetes-client/python/issues/476#issuecomment-1440312647_

**Comment by sona201** [comment]
i try someway to soulve this problem, but it doesnot work.
if there any to copy a tar.gz file from pod. 
should i try tar zxf tar.gz file ,then copy from pod?

**Comment by zffocussss** [comment]
have a look at how [**kubectl cp**](https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/cp/cp.go) work. hope it can help you.

**Comment by sona201** [comment]
> have a look at how [**kubectl cp**](https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/cp/cp.go) work. hope it can help you.

thanks. when i used kubectl cp command, maybe the file I copied is too large to cause "unexpected EOF", and the retry parameter needs to be configured
