### ISSUE TITLE
Add --copy-to parameter for ephemeral containers (V1EphemeralContainer)

### ISSUE THREAD

**Issue by jsboak** [kubernetes-client/python#2019]
**What is the feature and why do you need it**:

The `kubectl debug` command, which enables adding an Ephemeral Container to an existing pod, has the optional `--copy-to` flag that allows users to copy the original pod to a new pod (with the ephemeral container attached), and this allows for the extra `--share-processes` flag which furthers the PID, IPC, etc namespace sharing of the containers within the pod.
Details for this are described [here](https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#copying-a-pod-while-adding-a-new-container).

**Describe the solution you'd like to see**:

It would be great if the `patch_namespaced_pod_ephemeralcontainers` included a parameter that allows for this functionality.  Today, this method includes the `target_container_name` parameter, which allows the ephemeral container to share the PID,IPC namespace with a specific container in the running pod.  It would be nice if similarly, there were (for example) a `copy_to` string parameter where I would then specify the name of my "cloned" pod, and a boolean `share-processes` parameter that determines whether the containers in the cloned pod share their PID,IPC namespaces.

**Comment by roycaihw** [comment]
the `patch_namespaced_pod_ephemeralcontainers` API is generated from the upstream openapi spec. It cannot be changed unless we change the upstream spec. The `kubectl debug --copy-to` CLI may be using multiple APIs in combination to achieve the functionality. You can check what APIs the CLI calls by running the CLI with more verbosity `-v=9`
