### ISSUE TITLE
What is kubernetes dir

### ISSUE THREAD

**Issue by sergei-sh** [kubernetes-client/python#2020]
**Link to the issue (please include a link to the specific documentation or example)**:
[https://github.com/kubernetes-client/python/tree/master/kubernetes](https://github.com/kubernetes-client/python/tree/master/kubernetes)

What is the relation of this api and the root project ? Which one I should use?

**Comment by roycaihw** [comment]
the kubernetes dir contains the core (APIs, models, config loader) of this library. You can check https://github.com/kubernetes-client/python/tree/master/examples for examples on how to use this library
