### ISSUE TITLE
ResourceInstance has apiVersion but no api_version. 

### ISSUE THREAD

**Issue by nohhyun** [kubernetes-client/python#2027]
**What happened (please include outputs or screenshots)**:
For all objects in the lib, apiVersion can be accessed via `api_version` except for when you use DynamicClient which will return a ResourceInstance that requires apiVersion to be accessed via `apiVersion`. 

Following code:
```
    dclient = DynamicClient(client)
    resource = dclient.resources.get(
        api_version='v1',
        kind='Namespace',
    )
    ns = dclient.get(resource, 'default')
    print(ns.api_version, ns.kind)
    print(ns.apiVersion, ns.kind)

    core_client = CoreV1Api(client)
    ns = core_client.read_namespace('default')
    print(ns.api_version, ns.kind)
    print(ns.apiVersion, ns.kind)
```
results in:
```
None Namespace // I expected this to be v1 Namespace
v1 Namespace // Perhaps this should error out as well?
v1 Namespace
Traceback (most recent call last):
  File "/Users/nohhyun/src/sdmain/jedi/lib/kupr/k8s/helper.py", line 210, in <module>
    print(ns.apiVersion, ns.kind)
AttributeError: 'V1Namespace' object has no attribute 'apiVersion'
```

**What you expected to happen**:
Access apiVersion of ResourceInstance using `api_version` and not `apiVersion`. 

**How to reproduce it (as minimally and precisely as possible)**:
Above code should do it.

**Anything else we need to know?**:
I believe I can create a fix for this but wanted to check if this is indeed a bug. 

**Environment**:
- Kubernetes version (`kubectl version`): 1.24
- OS (e.g., MacOS 10.13.6): MacOS 10.13.6
- Python version (`python --version`) 3.10
- Python client version (`pip list | grep kubernetes`) 26.1.0

**Comment by nohhyun** [comment]
If this is indeed a bug, for backwards compatibility, I am thinking we can support both `api_version` and `apiVersion` in the fix?

**Comment by fabianvf** [comment]
@nohhyun I don't have any issue with including both, the ResourceInstance is a pretty dumb wrapper at the moment so I'm in favor of improving the usability generally, and bringing it in line with rest of the project

**Comment by nohhyun** [comment]
@fabianvf Thanks for the response - let me create a small diff and see if that works.
