### ISSUE TITLE
Could I use apply in DynamicClient ?

### ISSUE THREAD

**Issue by hermitgreen** [kubernetes-client/python#2030]
**What is the feature and why do you need it**:

Can 'DynamicClient' support 'apply'？

**Describe the solution you'd like to see**:

While I try https://github.com/kubernetes-client/python/blob/master/examples/dynamic-client/service.py example，I replace .create to .apply and except this can create if not exist or patch（like kubectl apply）, but I got

```shell
AttributeError: 'DynamicClient' object has no attribute 'apply
```

how could I use apply?

my code

```python
from kubernetes import config, dynamic
from kubernetes.client import api_client


def main():
    client = dynamic.DynamicClient(
        api_client.ApiClient(configuration=config.load_kube_config())
    )
    api = client.resources.get(api_version="v1", kind="Service")
    name = "frontend-service"
    service_manifest = {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {"labels": {"name": name}, "name": name, "resourceversion": "v1"},
        "spec": {
            "ports": [
                {"name": "port", "port": 80, "protocol": "TCP", "targetPort": 80}
            ],
            "selector": {"name": name},
        },
    }
    service = api.apply(body=service_manifest, namespace="default")


if __name__ == "__main__":
    main()
```

**Comment by yabea** [comment]
Can't use apply in DynamicClient: 
https://github.com/kubernetes-client/python/blob/56eea103a761c2310af76c63d4ed9cdd7171aeed/kubernetes/base/dynamic/client.py#L72

You can get() first, if the get succeeds excute patch(), else execute create().
