### ISSUE TITLE
Will you consider using pre-commit?

### ISSUE THREAD

**Issue by yabea** [kubernetes-client/python#2032]
**What is the feature and why do you need it**:
Add some plugins in pre-commit can check the code very well and fix some problems.
when i used pre-commit for this project, i found some  problems, such as:
![image](https://user-images.githubusercontent.com/15773461/227452955-33ae0f20-1a88-4c5b-bd33-ede9b0baf4f5.png)

**Describe the solution you'd like to see**:
Add .pre-commit-config.yaml

**Comment by roycaihw** [comment]
I think we have [some linter](https://github.com/kubernetes-client/python/blob/84f5fea2a3e4b161917aa597bf5e5a1d95e24f5a/.github/workflows/test.yaml#L27) used, but it would be certainly great to have some additional pre-commit checks
