### ISSUE TITLE
watch.Watch() - .stream() - v1_apps.list_namespaced_stateful_set

### ISSUE THREAD

**Issue by PawlowskiAdrian** [kubernetes-client/python#2036]
**What happened (please include outputs or screenshots)**:

Listening for stateful set does not provide all information about how many pods are not ready

**What you expected to happen**:

listening for deployment events provide `unavailable_replicas` field.
Listening for that field in stateful sets can result in Attribute Error

**How to reproduce it (as minimally and precisely as possible)**:

listen for events in list_namespaced_stateful_set: for event in w.stream(list_namespaced_stateful_set, namespace=namespace, timeout_seconds=600)

retrieve status and parse it to some function: event["object"].status

try to get data ex.: if event_status.unavailable_replicas is None

=> 
there is no field unavailable_replicas  in event_status

**Anything else we need to know?**:

example outputs of data:

```
STATEFUL SET, REPLICA COUNT 2
#     {'available_replicas': 0,
#  'collision_count': 0,
#  'conditions': None,
#  'current_replicas': 1,
#  'current_revision': 'mongo1-7458d9854f',
#  'observed_generation': 1,
#  'ready_replicas': None,
#  'replicas': 1,
#  'update_revision': 'mongo1-7458d9854f',
#  'updated_replicas': 1}

DEPLOYMENT, REPLICA COUNT 1
# {'available_replicas': None,
#  'collision_count': None,
#  'conditions': [{'last_transition_time': datetime.datetime(2023, 3, 29, 13, 11, 1, tzinfo=tzlocal()),
#                  'last_update_time': datetime.datetime(2023, 3, 29, 13, 11, 1, tzinfo=tzlocal()),
#                  'message': 'Deployment does not have minimum availability.',
#                  'reason': 'MinimumReplicasUnavailable',
#                  'status': 'False',
#                  'type': 'Available'},
#                 {'last_transition_time': datetime.datetime(2023, 3, 29, 13, 11, 1, tzinfo=tzlocal()),
#                  'last_update_time': datetime.datetime(2023, 3, 29, 13, 11, 1, tzinfo=tzlocal()),
#                  'message': 'ReplicaSet "app1-c798567d5" is progressing.',
#                  'reason': 'ReplicaSetUpdated',
#                  'status': 'True',
#                  'type': 'Progressing'}],
#  'observed_generation': 1,
#  'ready_replicas': None,
#  'replicas': 1,
#  'unavailable_replicas': 1,
#  'updated_replicas': 1}
```

**Environment**:
- Kubernetes version (`kubectl version`): 1.25.6
- OS (e.g., MacOS 10.13.6):  Ubuntu 20.04.5 LTS
- Python version (`python --version`) 3.10
- Python client version (`pip list | grep kubernetes`) 25.3.0

**Comment by roycaihw** [comment]
Please refer to the API doc. [StatefulSetStatus](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1StatefulSetStatus.md) doesn't have the `unavailable_replicas` field. I think this is expected behavior.

/close
