### ISSUE TITLE
load_config does not really support "kube_config_path"

### ISSUE THREAD

**Issue by Cornel-Craveta** [kubernetes-client/python#2038]
If you try to call `kubernetes.config.load_config` with an argument `kube_config_path` -- which apparently should be possible, according to the first line of the method:

```
def load_config(**kwargs):
...
    if "kube_config_path" in kwargs.keys()...
       load_kube_config(**kwargs)
```

then the call would fail, because the method `load_kube_config` (on the next line) does not accept an argument `kube_config_path`.

```
def load_kube_config(config_file=None, context=None,
                     client_configuration=None,
                     persist_config=True,
                     temp_file_path=None):
```

See:

https://github.com/kubernetes-client/python/blob/master/kubernetes/base/config/__init__.py#L36
https://github.com/kubernetes-client/python/blob/master/kubernetes/base/config/kube_config.py#L793

**Comment by tomplus** [comment]
It's known issue, will be fixed by https://github.com/kubernetes-client/python/pull/1966

**Comment by roycaihw** [comment]
Thank you @tomplus for pointing that out!
