### ISSUE TITLE
Can you share an example of how to update existing ingress using patch_namespaced_ingress? I'm not able to find a way to add content-type header with Python sdk. Below i sth ecode I have written and it keeps returning 409 status code to me.

### ISSUE THREAD

**Issue by neha587** [kubernetes-client/python#2042]
**Link to the issue (please include a link to the specific documentation or example)**:

**Description of the issue (please include outputs or screenshots if possible)**:
![image](https://user-images.githubusercontent.com/88154146/231248021-39d19ba8-0b97-475b-8ff2-ac3bf41e851b.png)

**Comment by roycaihw** [comment]
Please take a look at this [example](https://github.com/kubernetes-client/python/blob/ca4bfe509327961521ecd837b36e8ea0e91eb751/examples/cronjob_crud.py#L41)
