### ISSUE TITLE
Cannot list namespaced ResourceQuota

### ISSUE THREAD

**Issue by devopstales** [kubernetes-client/python#2051]
**What happened (please include outputs or screenshots)**:

I get the fallowing error: 

```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/v1/namespaces/network-testing/resourcequotas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f47fb90>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**What you expected to happen**:

Get back the ResourceQuota object list.

**How to reproduce it (as minimally and precisely as possible)**:

```
    try:
        lrs = k8s_client.CoreV1Api().list_namespaced_resource_quota(ns_name)
        pprint(lrs)
    except ApiException as e:
        print("Exception when calling CoreV1Api->list_namespaced_resource_quota: %s\n" % e)
```

**Anything else we need to know?**:
I tried python mosul version 20.13.0 too.

**Environment**:
- Kubernetes version (`kubectl version`): 1.20
- OS (e.g., MacOS 10.13.6): MacOS 13.3.1
- Python version (`python --version`) Python 3.11.2
- Python client version (`pip list | grep kubernetes`) 26.1.0

**Comment by paldib** [comment]
I get tha same on Linux Ubuntu 20.04 wit Python 3.11 using K3S v1.26.4 and Docker desktop kubernetes v1.25.4

**Comment by devopstales** [comment]
It was my fault I didn't load the local config correctly.
