### ISSUE TITLE
Website Documentation Link Broken

### ISSUE THREAD

**Issue by jdholtz** [kubernetes-client/python#2060]
**Link to the issue (please include a link to the specific documentation or example)**:
https://kubernetes.readthedocs.io/en/latest/README.html#documentation

**Description of the issue (please include outputs or screenshots if possible)**:
The link leading to the "[Generated client’s README file](https://github.com/kubernetes-client/python/blob/master/kubernetes/README)" does not have the `.md` ending, causing the link to lead to a 404. I'm not sure if this is the correct place to report this issue, but the "Edit on GitHub" button led me to this repository (which also led me to a 404). This possibly might just be because the website hasn't been regenerated in a while, but I have never used this method of documentation so I can't say for sure.

Fixing the documentation on the website can help new users of this library significantly by pointing them to the correct information.

**Comment by kumiDa** [comment]
I verified that the building html pages with latest version of the code at 469ef552 resulted in the complete URL (https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md) being hyperlinked over the text "Generated client’s README file" unlike the hosted site where the broken link of (https://github.com/kubernetes-client/python/blob/master/kubernetes/README) is linked to that text.

This only leads me to conclude that the current version of the code is not hosted in the readTheDocs site like @jdholtz suggested.
@roycaihw, @yliaog can you please guide me on how to correct this?

**Comment by tomplus** [comment]
This PR https://github.com/kubernetes-client/python/pull/2026 should fix it.
