### ISSUE TITLE
Sphinx automodule is not working in ReadTheDocs

### ISSUE THREAD

**Issue by rgaiacs** [kubernetes-client/python#2079]
https://github.com/kubernetes-client/python/blob/master/doc/source/kubernetes.client.api.core_v1_api.rst is render at https://kubernetes.readthedocs.io/en/latest/kubernetes.client.api.core_v1_api.html and user finds

![Screenshot 2023-06-27 at 09-31-33 kubernetes client api core_v1_api module — kubernetes-python-client documentation](https://github.com/kubernetes-client/python/assets/1506457/e0034062-9c4e-4c7d-ab5d-065af97ab788)

The module documentation is missing completely.

Openapi Generator produces some documentation (e.g. https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md) but GitHub is not rendering the file because it is too large.

**Comment by tomplus** [comment]
It works well locally:

```
# if you have all dependencies installed:
cd doc
make html
cd build/html
python -m http.server
```

but for some reason Read The Docs can't build it :/ @roycaihw could you check their logs?
