### ISSUE TITLE
Dynamic client is unable to resolve when there are multiple entries in DNS

### ISSUE THREAD

**Issue by Surasmi** [kubernetes-client/python#2080]
**What happened (please include outputs or screenshots)**: 
![image](https://github.com/kubernetes-client/python/assets/136793553/1859f746-2823-439b-98dc-165d1116b95d)

**What you expected to happen**:
When two DNS are provided, dynamic client should properly route to one of them.  It is not happening and dns resolution is failing

**How to reproduce it (as minimally and precisely as possible)**:
Configure the kubernetes client and add two DNS in the setup
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): 
- OS (e.g., MacOS 10.13.6): Ubuntu and RHEL
- Python version (`python --version`)   3.6
- Python client version (`pip list | grep kubernetes`) v25.3.0

**Comment by roycaihw** [comment]
@Surasmi Do the typed clients also have this issue? Or is it specific to the dynamic client?
