### ISSUE TITLE
connect_get_namespaced_pod_exec returns "Upgrade request required"

### ISSUE THREAD

**Issue by saikrishnaa97** [kubernetes-client/python#2083]
While trying to run commands using connect_get_namespaced_pod_exec method, the following exception is being returned.

kubernetes.client.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '3c3be21c-a1ff-4374-8467-0f21d6508353', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 04 Jul 2023 08:56:54 GMT', 'Content-Length': '139'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}

**Anything else we need to know?**: 
I added the following rule in the role for the pod from which I am trying to run the exec method.
`- apiGroups:`
  `  - ""`
  `  resources:`
  `  - pods/exec`
  `  verbs:`
  `  - '*'`

**Environment**:
- Kubernetes version : 1.24.6
- OS : Oraclelinux 8
- Python version : Python 3.9.13
- Python client version : 24.2.0

**Comment by DamianFekete** [comment]
Use the websockets `stream`, see an example here https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py#L86

Make sure that you notice the difference:
```
resp = stream(api_instance.connect_get_namespaced_pod_exec(... )) # NOT OK
resp = stream(api_instance.connect_get_namespaced_pod_exec, ...)  # OK, a comma and not a `(` after exec
```

**Comment by saikrishnaa97** [comment]
Thank you @DamianFekete. This was exactly the mistake I made. I was calling the connect_get_namespaced_pod_exec method inside the stream, instead of passing it as a parameter. This solved my issue.
