### ISSUE TITLE
How to log client requests also

### ISSUE THREAD

**Issue by vedujoshi** [kubernetes-client/python#209]
I have enabled logging to console as shown below

kslogger = logging.getLogger('kubernetes') 
console_h= logging.StreamHandler() 
kslogger.addHandler(console_h) 
kslogger.setLevel(logging.DEBUG) 

When I run list_namespaced_pod(), I see only the response body being logged on the console.

`response body: {"kind":"PodList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/default/pods","resourceVersion":"718033"},"items":[]}
`

I would like to also view the full request url and the body. How do i get the same?

**Comment by dims** [comment]
@vedujoshi try http://urllib3.readthedocs.io/en/latest/user-guide.html#logging

**Comment by mbohlool** [comment]
Look here: https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/client/configuration.py#L64

**Comment by vedujoshi** [comment]
@mbohlool @dims 
I had tried urllib3 debug logging earlier, but it only shows the url, but not the request body.
For ex...while creating a deployment : 

2017-05-04 10:22:50,414 DEBUG https://10.204.217.194:6443 "POST /apis/apps/v1beta1/namespaces/default/deployments HTTP/1.1" 201 1002
response body: {"kind":"Deployment","apiVersion":"apps/v1beta1","metadata":{"name":"test-deployment","namespace":"default","selfLink":"/apis/apps/v1beta1/namespaces/default/deployments/test-deployment","uid":"8685b59c-3085-11e7-9c09-525400010001","resourceVersion":"758517","generation":1,"creationTimestamp":"2017-05-04T04:52:50Z","labels":{"app":"nginx"}},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"name":"ctest-container-50726557","image":"nginx:1.7.9","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":"25%","maxSurge":"25%"}},"revisionHistoryLimit":2,"progressDeadlineSeconds":600},"status":{}}
`

If i set HTTPConnection debuglevel, i can see the full body, but would have preferred without all those HTTP headers...

send: 'POST /apis/apps/v1beta1/namespaces/default/deployments HTTP/1.1\r\nHost: 10.204.217.194:6443\r\nAccept-Encoding: identity\r\nContent-Length: 223\r\nContent-Type: application/json\r\nAccept: application/json\r\nUser-Agent: Swagger-Codegen/1.0.0-snapshot/python\r\n\r\n{"spec": {"template": {"spec": {"containers": [{"image": "nginx:1.7.9", "name": "ctest-container-48376028", "ports": []}]}, "metadata": {"labels": {"app": "nginx"}}}, "replicas": 3}, "metadata": {"name": "test-deployment"}}'
reply: 'HTTP/1.1 201 Created\r\n'
header: Content-Type: application/json
header: Date: Thu, 04 May 2017 04:59:56 GMT
header: Content-Length: 1002
2017-05-04 10:29:56,343 DEBUG https://10.204.217.194:6443 "POST /apis/apps/v1beta1/namespaces/default/deployments HTTP/1.1" 201 1002
response body: {"kind":"Deployment","apiVersion":"apps/v1beta1","metadata":{"name":"test-deployment","namespace":"default","selfLink":"/apis/apps/v1beta1/namespaces/default/deployments/test-deployment","uid":"846a457c-3086-11e7-9c09-525400010001","resourceVersion":"759211","generation":1,"creationTimestamp":"2017-05-04T04:59:56Z","labels":{"app":"nginx"}},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"name":"ctest-container-48376028","image":"nginx:1.7.9","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":"25%","maxSurge":"25%"}},"revisionHistoryLimit":2,"progressDeadlineSeconds":600},"status":{}}

**Comment by mbohlool** [comment]
I think configuration.debug and log is the way to go. We can't control what is getting logged but you can create a log stream and filter out what you don't need. Does that work for you?

**Comment by vedujoshi** [comment]
Yeah..that seems like i need to do that.
It would have been nice if the kubernetes python client itself would log the request as well ..similar to kubectl verbose out below: 

I0504 15:39:41.488207   27929 request.go:991] Request Body: {"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"name":"busy-deployment","namespace":"default"},"spec":{"replicas":2,"template":{"metadata":{"labels":{"app":"busybox"}},"spec":{"containers":[{"command":["sleep","3600"],"image":"busybox","name":"busybox"}]}}}}
I0504 15:39:41.488287   27929 round_trippers.go:398] curl -k -v -XPOST  -H "Accept: application/json" -H "Content-Type: application/json" -H "User-Agent: kubectl/v1.6.2 (linux/amd64) kubernetes/477efc3" http://localhost:8080/apis/apps/v1beta1/namespaces/default/deployments
I0504 15:39:41.492799   27929 round_trippers.go:417] POST http://localhost:8080/apis/apps/v1beta1/namespaces/default/deployments 201 Created in 4 milliseconds
I0504 15:39:41.492871   27929 round_trippers.go:423] Response Headers:
I0504 15:39:41.492881   27929 round_trippers.go:426]     Content-Type: application/json
I0504 15:39:41.492888   27929 round_trippers.go:426]     Date: Thu, 04 May 2017 19:39:41 GMT
I0504 15:39:41.492895   27929 round_trippers.go:426]     Content-Length: 1008
I0504 15:39:41.492981   27929 request.go:991] Response Body: {"kind":"Deployment","apiVersion":"apps/v1beta1","metadata":{"name":"busy-deployment","namespace":"default","selfLink":"/apis/apps/v1beta1/namespaces/default/deployments/busy-deployment","uid":"6ad0ec7e-3101-11e7-9c09-525400010001","resourceVersion":"829138","generation":1,"creationTimestamp":"2017-05-04T19:39:41Z","labels":{"app":"busybox"}},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"busybox"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"busybox"}},"spec":{"containers":[{"name":"busybox","image":"busybox","command":["sleep","3600"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":"25%","maxSurge":"25%"}},"revisionHistoryLimit":2,"progressDeadlineSeconds":600},"status":{}}
