### ISSUE TITLE
connect_get_namespaced_pod_exec Upgrade request required

### ISSUE THREAD

**Issue by joedborg** [kubernetes-client/python#2092]
**What happened (please include outputs or screenshots)**:

Code:

```
from kubernetes import client, config
from kubernetes.stream import stream

config.load_incluster_config()
api = client.CoreV1Api()
data_stream = stream(
    api.connect_get_namespaced_pod_exec(
        "hello-world",
        "default",
        container="hello-world",
        command=["sh", "-c", "echo 'hello world'"],
        stderr=False,
        stdin=False,
        stdout=True,
        tty=False,
    )
)
```

Output:
```
│   File "loop.py", line 157, in main                                                                                                                                                             │
│     api.connect_get_namespaced_pod_exec(                                                                                                                                                                 │
│   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 994, in connect_get_namespaced_pod_exec                                                                                │
│     return self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)  # noqa: E501                                                                                                            │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                          │
│   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 1101, in connect_get_namespaced_pod_exec_with_http_info                                                                │
│     return self.api_client.call_api(                                                                                                                                                                               │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                               │
│   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 348, in call_api                                                                                                            │
│     return self.__call_api(resource_path, method,                                                                                                                                                                  │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                  │
│   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 180, in __call_api                                                                                                          │
│     response_data = self.request(                                                                                                                                                                                  │
│                     ^^^^^^^^^^^^^                                                                                                                                                                                  │
│   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 373, in request                                                                                                             │
│     return self.rest_client.GET(url,                                                                                                                                                                               │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                               │
│   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 240, in GET                                                                                                                       │
│     return self.request("GET", url,                                                                                                                                                                                │
│            ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                │
│   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 234, in request                                                                                                                   │
│     raise ApiException(http_resp=r)                                                                                                                                                                                │
│ kubernetes.client.exceptions.ApiException: (400)                                                                                                                                                                   │
│ Reason: Bad Request                                                                                                                                                                                                │
│ HTTP response headers: HTTPHeaderDict({'Audit-Id': 'b1613686-b4c3-4b8b-8ef4-56763470bb8b', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 26 Jul 2023 21:00:14 GMT', 'Con │
│ HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}
```

**What you expected to happen**:

Because `stream()` wrapped the function, expected not to get the "Upgrade request required" error.

**How to reproduce it (as minimally and precisely as possible)**:

See code snipped above.

**Environment**:
- Kubernetes version (`kubectl version`):
```
v1.27.3-eks-a5565ad
```
- OS (e.g., MacOS 10.13.6):
```
Debian GNU/Linux 12 (bookworm)
```
- Python version (`python --version`)
```
Python 3.11.4
```
- Python client version (`pip list | grep kubernetes`)
```
kubernetes         23.6.0
````

**Comment by ai-naymul** [comment]
Hey @joedborg,
Did you try this code:
`api.connect_get_namespaced_pod_exec(
    "hello-world",
    "default",
    container="hello-world",
    command=["sh", "-c", "echo 'hello world'"],
    stderr=False,
    stdin=False,
    stdout=True,
    tty=False,
    upgrade=True,  # Add this line
)`
Let me know!! :)

**Comment by roycaihw** [comment]
/assign @ai-naymul 

Maybe also worth checking our [examples](https://github.com/kubernetes-client/python/tree/master/examples).

**Comment by ai-naymul** [comment]
> **What happened (please include outputs or screenshots)**:
> 
> Code:
> 
> ```
> from kubernetes import client, config
> from kubernetes.stream import stream
> 
> config.load_incluster_config()
> api = client.CoreV1Api()
> data_stream = stream(
>     api.connect_get_namespaced_pod_exec(
>         "hello-world",
>         "default",
>         container="hello-world",
>         command=["sh", "-c", "echo 'hello world'"],
>         stderr=False,
>         stdin=False,
>         stdout=True,
>         tty=False,
>     )
> )
> ```
> 
> Output:
> 
> ```
> │   File "loop.py", line 157, in main                                                                                                                                                             │
> │     api.connect_get_namespaced_pod_exec(                                                                                                                                                                 │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 994, in connect_get_namespaced_pod_exec                                                                                │
> │     return self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)  # noqa: E501                                                                                                            │
> │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                          │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 1101, in connect_get_namespaced_pod_exec_with_http_info                                                                │
> │     return self.api_client.call_api(                                                                                                                                                                               │
> │            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                               │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 348, in call_api                                                                                                            │
> │     return self.__call_api(resource_path, method,                                                                                                                                                                  │
> │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                  │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 180, in __call_api                                                                                                          │
> │     response_data = self.request(                                                                                                                                                                                  │
> │                     ^^^^^^^^^^^^^                                                                                                                                                                                  │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 373, in request                                                                                                             │
> │     return self.rest_client.GET(url,                                                                                                                                                                               │
> │            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                               │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 240, in GET                                                                                                                       │
> │     return self.request("GET", url,                                                                                                                                                                                │
> │            ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 234, in request                                                                                                                   │
> │     raise ApiException(http_resp=r)                                                                                                                                                                                │
> │ kubernetes.client.exceptions.ApiException: (400)                                                                                                                                                                   │
> │ Reason: Bad Request                                                                                                                                                                                                │
> │ HTTP response headers: HTTPHeaderDict({'Audit-Id': 'b1613686-b4c3-4b8b-8ef4-56763470bb8b', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 26 Jul 2023 21:00:14 GMT', 'Con │
> │ HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}
> ```
> 
> **What you expected to happen**:
> 
> Because `stream()` wrapped the function, expected not to get the "Upgrade request required" error.
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> See code snipped above.
> 
> **Environment**:
> 
> * Kubernetes version (`kubectl version`):
> 
> ```
> v1.27.3-eks-a5565ad
> ```
> 
> * OS (e.g., MacOS 10.13.6):
> 
> ```
> Debian GNU/Linux 12 (bookworm)
> ```
> 
> * Python version (`python --version`)
> 
> ```
> Python 3.11.4
> ```
> 
> * Python client version (`pip list | grep kubernetes`)
> 
> ```
> kubernetes         23.6.0
> ```

@joedborg 
replace the line `config.load_incluster_config()` with the following line `config.load_kube_config()`

Let me know if this work :)

**Comment by silvia20177** [comment]
> , upgrade=True

It can't work


api = get_coreV1Api(token)
name = "redis-redis-0"
namespace = "default"
exec_commands = ["ls"]
response = api.connect_get_namespaced_pod_exec(name=name, namespace=namespace, container="redis",  command=exec_commands, stderr=False, stdin=False, stdout=True, tty=False, upgrade=True)

/usr/lib/python2.7/site-packages/google/auth/crypt/_cryptography_rsa.py:22: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  import cryptography.exceptions
Traceback (most recent call last):
  File "zjj.py", line 52, in <module>
    response = api.connect_get_namespaced_pod_exec(name=name, namespace=namespace, container="redis",  command=exec_commands, stderr=False, stdin=False, stdout=True, tty=False, upgrade=True)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api/core_v1_api.py", line 994, in connect_get_namespaced_pod_exec
    return self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api/core_v1_api.py", line 1053, in connect_get_namespaced_pod_exec_with_http_info
    " to method connect_get_namespaced_pod_exec" % key
kubernetes.client.exceptions.ApiTypeError: Got an unexpected keyword argument 'upgrade' to method connect_get_namespaced_pod_exec

**Comment by silvia20177** [comment]
> **What happened (please include outputs or screenshots)**:
> 
> Code:
> 
> ```
> from kubernetes import client, config
> from kubernetes.stream import stream
> 
> config.load_incluster_config()
> api = client.CoreV1Api()
> data_stream = stream(
>     api.connect_get_namespaced_pod_exec(
>         "hello-world",
>         "default",
>         container="hello-world",
>         command=["sh", "-c", "echo 'hello world'"],
>         stderr=False,
>         stdin=False,
>         stdout=True,
>         tty=False,
>     )
> )
> ```
> 
> Output:
> 
> ```
> │   File "loop.py", line 157, in main                                                                                                                                                             │
> │     api.connect_get_namespaced_pod_exec(                                                                                                                                                                 │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 994, in connect_get_namespaced_pod_exec                                                                                │
> │     return self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)  # noqa: E501                                                                                                            │
> │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                          │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 1101, in connect_get_namespaced_pod_exec_with_http_info                                                                │
> │     return self.api_client.call_api(                                                                                                                                                                               │
> │            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                               │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 348, in call_api                                                                                                            │
> │     return self.__call_api(resource_path, method,                                                                                                                                                                  │
> │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                  │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 180, in __call_api                                                                                                          │
> │     response_data = self.request(                                                                                                                                                                                  │
> │                     ^^^^^^^^^^^^^                                                                                                                                                                                  │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 373, in request                                                                                                             │
> │     return self.rest_client.GET(url,                                                                                                                                                                               │
> │            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                               │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 240, in GET                                                                                                                       │
> │     return self.request("GET", url,                                                                                                                                                                                │
> │            ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                │
> │   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 234, in request                                                                                                                   │
> │     raise ApiException(http_resp=r)                                                                                                                                                                                │
> │ kubernetes.client.exceptions.ApiException: (400)                                                                                                                                                                   │
> │ Reason: Bad Request                                                                                                                                                                                                │
> │ HTTP response headers: HTTPHeaderDict({'Audit-Id': 'b1613686-b4c3-4b8b-8ef4-56763470bb8b', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 26 Jul 2023 21:00:14 GMT', 'Con │
> │ HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}
> ```
> 
> **What you expected to happen**:
> 
> Because `stream()` wrapped the function, expected not to get the "Upgrade request required" error.
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> See code snipped above.
> 
> **Environment**:
> 
> * Kubernetes version (`kubectl version`):
> 
> ```
> v1.27.3-eks-a5565ad
> ```
> 
> * OS (e.g., MacOS 10.13.6):
> 
> ```
> Debian GNU/Linux 12 (bookworm)
> ```
> 
> * Python version (`python --version`)
> 
> ```
> Python 3.11.4
> ```
> 
> * Python client version (`pip list | grep kubernetes`)
> 
> ```
> kubernetes         23.6.0
> ```

Have you solved it?

**Comment by silvia20177** [comment]
您好！您的邮件已收到。谢谢！张静静。

**Comment by silvia20177** [comment]
您好！您的邮件已收到。谢谢！张静静。
