### ISSUE TITLE
Append ConfigMap data

### ISSUE THREAD

**Issue by curiousEnough** [kubernetes-client/python#2108]
**What is the feature and why do you need it**:
I have created a config map via create_namespaced_config_map. I am attempting to patch it by appending existing data. Tried like this

cm = client.V1ConfigMap()
        cm.metadata = client.V1ObjectMeta(name=name)
        cm.data = cm_data
        existingCM = v1.read_namespaced_config_map("test-cm", "test-ns")
        print(existingCM)
        
        # print(existingCM)
        
         
        if existingCM == False:
            print(self.v1.read_namespaced_config_map(test-cm", "test-ns"))
            self.v1.create_namespaced_config_map(namespace=namespace, body=cm)
            print(f"Created ConfigMap {name} in namespace {namespace}") 

        else:
            # print(existingCM)
            print(existingCM.update(cm.data))
            v1.patch_namespaced_config_map(name=name, namespace=namespace, body=cm)
            print(f"Updated ConfigMap {name} in namespace {namespace}") 

This wouldn't work. Is there an example that I can follow?

**Describe the solution you'd like to see**:
Example to achieve successful data append

**Comment by roycaihw** [comment]
Could you elaborate what you're trying to achieve? Could you show what's the `kubectl` equivalent of the python program?
