### ISSUE TITLE
Watch Jobs

### ISSUE THREAD

**Issue by agardnerIT** [kubernetes-client/python#2109]
Hi,

Is it possible to:

1) "watch jobs"
2) Get the duration

For example, I want to watch jobs and when react when `sj5` finishes and get the `6s` field. I know I can grab `status.startTime` and `status.completionTime` and calculate that myself.

```
% kubectl get jobs
NAME   COMPLETIONS   DURATION 
sj5    1/1           6s
sj6    1/1           7s
```

**Comment by agardnerIT** [comment]
For others:

```
from kubernetes import client, config, watch

config.load_kube_config()

w = watch.Watch()

v1 = client.BatchV1Api()
for event in w.stream(v1.list_job_for_all_namespaces):
  ...
```

**Comment by aemonge** [comment]
That `for` loop is blocking, is there a way to set it none-blocking ?
