### ISSUE TITLE
Feedback on comparison with kr8s

### ISSUE THREAD

**Issue by jacobtomlinson** [kubernetes-client/python#2117]
Hey there 👋. I'm the author of [`kr8s`](https://docs.kr8s.org/en/latest/), another Python library for Kubernetes.

The goal of `kr8s` is to be a batteries-included kubectl-inspired Python library that has a very shallow learning curve and reduces boilerplate. I built it to solve some specific challenges we were having in [`dask-kubernetes`](https://kubernetes.dask.org/en/latest/) with using the official `kubernetes` library (and especially `kubernetes_asyncio`).

We are at the point in development where `dask-kubernetes` has been fully migrated over to it and the API is getting pretty stable, so I decided to take a step back and assess how well we are doing in terms of hitting our design goals. In doing so I wrote up [a blog post comparing the `kr8s` API with other Python Kubernetes libraries](https://jacobtomlinson.dev/posts/2023/comparison-of-kr8s-vs-other-python-libraries-for-kubernetes/) including `kubernetes`.

The comparison is intended to check how well `kr8s` is meeting it's goals and to discuss the tradeoffs we make to achieve those goals compared with libraries, rather than trying to show which is "better".

I wanted to stop by here and open an issue to ask for feedback on the `kubernetes` description and examples I've included in the post. I want to make sure I'm highlighting the strengths of `kubernetes` accurately so that if folks do use the post to choose between the libraries they can make an informed decision based on their own requirements.

If you do have any feedback feel free to reply here, send me an email to jacob@tomlinson.email or [open a PR directly on the blog post](https://github.com/jacobtomlinson/website/blob/master/content/posts/2023/2023-09-04-python-kubernetes-library-comparison/index.md).

Thank you!

**Comment by jacobtomlinson** [comment]
@sanmai-NL in `kr8s` we use `httpx` for making all HTTP requests to the Kubernetes API. According to the [`httpx` documentation](https://www.python-httpx.org/environment_variables/#http_proxy-https_proxy-all_proxy), it supports the `HTTP_PROXY`, `HTTPS_PROXY`, `ALL_PROXY` out of the box. 

But we don't do anything to enable setting this in code. If that would be valuable to you then please open an issue on the `kr8s` repo.

**Comment by sanmai-NL** [comment]
Setting this in code, you an you don't provide an API to configure proxying? But for us, using the environment variables is sufficient.

**Comment by jacobtomlinson** [comment]
> you mean you don't provide an API to configure proxying

Not currently. If there is demand for this we can definitely expose it though.
