### ISSUE TITLE
UnicodeDecodeError with method read_namespaced_pod_log()

### ISSUE THREAD

**Issue by berqavos** [kubernetes-client/python#2118]
**What happened (please include outputs or screenshots)**:
While using the following `pod_logs = v1.read_namespaced_pod_log(name=pod_name, namespace=namespace)`. I receive the error: 
```
File "/opt/app/batch/python_virt/venv_app/lib64/python3.11/site-packages/kubernetes/client/rest.py", line 229, in request
    r.data = r.data.decode('utf8')
             ^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 3793: invalid continuation byte
```

**What you expected to happen**:
The pod logs are displayed correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Use pods where the output is not utf-8. In my case it's latin-1.

**Anything else we need to know?**:
There are legacy applications where the output has to be in a special charset. Therefore, it would be great when the method `read_namespaced_pod_log` from the `kubernetes.client.CoreV1Api()` could have a parameter charset, where the developer can choose a desired charset. For example:
`pod_logs = v1.read_namespaced_pod_log(name=pod_name, namespace=namespace, charset='latin1')`

As stated above at the moment the charset utf-8 is hardcoded in:
https://github.com/kubernetes-client/python/blob/68d5a1479e7d735ea454021bc54e453c9b31baf7/kubernetes/client/rest.py#L232

It worked as soon as I changed `r.data = r.data.decode('utf8')` to `r.data = r.data.decode('latin1')`

**Environment**:
- Kubernetes version: 1.26
- OS: Fedora 38
- Python version: 3.11.4
- Python client version: 26.1.0

**Comment by yliaog** [comment]
https://github.com/kubernetes-client/python/pull/2100

seems to be similar issue

**Comment by TheLord45** [comment]
I had the same problem and applying the above solution worked. So I modified the code a little bit and added a function to allow setting the character set for the client. I attached the _diff_ here.
[kubernetes.txt](https://github.com/kubernetes-client/python/files/12618102/kubernetes.txt)
