### ISSUE TITLE
Port-forward and usage with other Python libraries

### ISSUE THREAD

**Issue by thesalmonidae** [kubernetes-client/python#2130]
https://github.com/kubernetes-client/python/blob/a6d44ff625b5e8d8ad380a70245d40fa3d5472b2/examples/pod_portforward.py#L32

Please, how this works if one would like to create a portforward, and then use another library such as Kafka client or Redis client to communicate through the port forward by using TCP connection?

They do try to create their own sockets, when they try to connect. For instance redis library is using socket.socket(), how one can "monkey patch that"?

**Comment by roycaihw** [comment]
/cc @iciclespider 

Could you take a look? Thanks

**Comment by iciclespider** [comment]
If the library ultimately calls the python `socket.create_connection` method, then that can be monkey patched as this example shows: https://github.com/kubernetes-client/python/blob/master/examples/pod_portforward.py#L124-L187

If the library is doing it's own `socket.socket` call to create the connection, then a creative solution will be needed on a library by library basis, likely involving either forking the project, are figuring out an appropriate place to monkey patch that library.
