### ISSUE TITLE
patch_namespaced_deployment_scale returns None instead of 0 when scaling a deployment to 0 replicas

### ISSUE THREAD

**Issue by dandres-stratio** [kubernetes-client/python#2132]
**What happened (please include outputs or screenshots)**:
After scaling down a deployment to 0 replicas using **patch_namespaced_deployment_scale**, the resulting V1ScaleSpec replicas is None instead of 0.

e.g. With this piece of code:
`scale = _app_client.patch_namespaced_deployment_scale(<deployment-name>, <namespace>, body={'spec': {'replicas': 0}})`

The resulting V1Scale.spec.replicas is supposed to return an Integer, but returns None instead.

**What you expected to happen**:
V1Scale.spec.replicas should return an integer, even if the number of replicas is 0.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a deployment with N number of replicas
- Scale that deployment to 0 replicas using patch_namespaced_deployment_scale as shown above
- Capture the output of V1Scale.spec.replicas

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`): v1.27.4
- OS (e.g., MacOS 10.13.6): ubuntu:22.04
- Python version (`python --version`): 3.10.12
- Python client version (`pip list | grep kubernetes`): 28.1.0 (Also reproducible with 27.2.0)

**Comment by yliaog** [comment]
patch_namespaced_deployment_scale is generated by open api generator, so the any fix needs to be at the generator.

for the particular question raised in this issue, what issue does returning None instead of 0 cause?

**Comment by dandres-stratio** [comment]
Hello @yliaog. Given the documentation for V1ScaleSpec https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1ScaleSpec.md **replicas** is supposed to be an integer.

While 0 is an integer and None is not, I assumed this was a bug. Of course I can addapt my code to this, but I think the current behaviour is not as straight forward as it should be, neither it matches the documentation.
