### ISSUE TITLE
Make google-auth an optional dependency

### ISSUE THREAD

**Issue by dblackdblack** [kubernetes-client/python#2134]
This is a dupe of https://github.com/kubernetes-client/python/issues/1486 which was closed but which was never tackled.  Feel free to re-open that one and close this one

**What is the feature and why do you need it**:

From what I can gather, google-auth is only required when using the google cloud platform.

Since it's of use only to a subset of the users, I propose that that dependency gets moved from the general requirements to the extras part of the setup.py file. Users that require this feature would install the package using, for example, a "gcp" extras flag (e.g. pip install kubernetes[gcp]).

In corporate environments, where compliance regulations require tracking and justifying all packages installed, this would reduce the maintenance burden by removing a whole section of the dependency tree when it's not needed.

**Describe the solution you'd like to see**:

Only install `google-auth` if it's needed by having e.g. a `kubernetes[gcp]` variant of the kubernetes package.

**Comment by roycaihw** [comment]
@dblackdblack Would you like to send a PR? Thanks
