### ISSUE TITLE
Port Forward - Different Ports local port and remote port

### ISSUE THREAD

**Issue by razilevin** [kubernetes-client/python#2138]
I would like to be able to spin up multiple port forwards at the same time if possible. E.g. Using the kubectl CLI command form of `kubectl --context <some-context> port-forward -n <some-namespace> <some-pod> <local-port>:<remote-port>`

```shell
kubectl --context cluster-1 port-forward -n n1 pod 9200:9200 &
kubectl --context cluster-2 port-forward -n n1 pod 9100:9200 &
```

Currently I do not see a way of doing this AFAIK.

I get an error that the PORTS must be the same when creating the port forwarded socket.

```python
 pf = portforward(
    dispatch["k8s"].connect_get_namespaced_pod_portforward,
    "...",
    "...",
    _request_timeout=60,
    ports="some-remote-port",
)
return pf.socket(some-local-port)
```

Am I missing something?

**Comment by roycaihw** [comment]
@iciclespider Could you take a look? Thanks

**Comment by iciclespider** [comment]
The forwarded ports are not open on the network interfaces. This is instead providing a means for the python code to access the remote pod ports. Here is a snippet that uses the python client port forwarding to access two ports:
```python
pf = portforward(
    dispatch["k8s"].connect_get_namespaced_pod_portforward,
    "...",
    "...",
    _request_timeout=60,
    ports="80,443",
)
http_port = pf.socket(80)
https_port = pf.socket(443)
```

**Comment by iciclespider** [comment]
If this is essentially what you are trying to recreate:
```bash
kubectl --context cluster-1 port-forward -n n1 pod 9200:9200 &
kubectl --context cluster-2 port-forward -n n1 pod 9100:9200 &
```
This is roughly how it will be accomplished:
```python
cluster_1_pf = portforward(
    dispatch["cluster-1"].connect_get_namespaced_pod_portforward,
    "...",
    "...",
    _request_timeout=60,
    ports="9200",
)
cluster_2_pf = portforward(
    dispatch["cluster-2"].connect_get_namespaced_pod_portforward,
    "...",
    "...",
    _request_timeout=60,
    ports="9200",
)
cluster_1_port = cluster_1_pf.socket(9200)
cluster_2_port = cluster_2_pf.socket(9200)
```
