### ISSUE TITLE
kubectl get pods --show-labels equivalent in python client

### ISSUE THREAD

**Issue by dirrao** [kubernetes-client/python#2140]
Right now we are using the list_pod_for_all_namespaces function to get the list of pods (V1PodList). However, we are interested in pod labels alone. So, It is not optimized for our use case. We are looking for a Python client function that returns the pod labels instead of whole whole PodSpec similar to kubectl get pods --show-labels. The intention of this request is to use table format and return the labels. So, this will avoid whole pod spec data transfer and improve the latency.

**Comment by dirrao** [comment]
I am able to achieve the same using dynamic client.

**Comment by roycaihw** [comment]
Could you share more detail on how you achieved this? I wonder if you use a server-side filtering to avoid returning the pod spec.

**Comment by roycaihw** [comment]
cc @yliaog
