### ISSUE TITLE
when I use "connect_get_namespaced_pod_exec" or "connect_post_namespaced_pod_exec" I got 400

### ISSUE THREAD

**Issue by silvia20177** [kubernetes-client/python#2144]
**What happened (please include outputs or screenshots)**:

**What you expected to happen**:
I could exec my command in the pod

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):v1.16.15
- OS (e.g., MacOS 10.13.6):
- Python version (`python --version`):Python 2.7.5
- Python client version (`pip list | grep kubernetes`):kubernetes          18.20.0

<img width="1068" alt="image" src="https://github.com/kubernetes-client/python/assets/33800642/9c9f52c4-0135-472a-a730-1ff671a6db00">

<img width="1425" alt="image" src="https://github.com/kubernetes-client/python/assets/33800642/7bef75e3-0aaf-4d1c-b397-d854ec49c490">

**Comment by roycaihw** [comment]
@silvia20177 Could you check the example https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py and see if it resolves you question?

**Comment by silvia20177** [comment]
您好！您的邮件已收到。谢谢！张静静。
