### ISSUE TITLE
Watch Method stops detecting change in events

### ISSUE THREAD

**Issue by samskan** [kubernetes-client/python#2145]
After sometime watch method is not detecting any change in secret/configmaps.

- Kubernetes version (`kubectl version`): 
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.5

No timeout set for watch
 w = watch.Watch()
 for event in w.stream(v1.list_secret_for_all_namespaces):
      print(event['type'], event['object'].kind, event['object'].metadata.name)

I dont see any events in the print  line

**Comment by Ananya2001-an** [comment]
Hey @samskan can u give more info on the issue... I am able to get the event updates for secrets

**Comment by vivekdixit2510** [comment]
The watch method fails to detect changes despite pod termination, persisting in an unresponsive state.
            w = watch.Watch()
            for event in w.stream(
                    kube_client.list_namespaced_pod,
                    namespace=environ.get('NAMESPACE')):
                pod = event['object']

**Comment by vivekdixit2510** [comment]
I need to watch a server process for 6 hours and delete it after. If it ends early , I should note it as successful. But sometimes, I don't receive notifications after it ends. This happens inconsistently.

**Comment by vivekdixit2510** [comment]
Any update on this Bug?
