### ISSUE TITLE
Consider Cut a new release?

### ISSUE THREAD

**Issue by shuoli84** [kubernetes-client/python#2152]
Hi, I just met a dependency problem, and it is fixed by pr #2131. Consider cut a new release? Thanks ~

**Comment by shuoli84** [comment]
BTW, can use the git version, put following line in requirements.txt
```
kubernetes @ git+https://github.com/kubernetes-client/python.git@36cfbe68a509d9b9d33395b22b6fa94d7d46c30f
```

**Comment by bagerard** [comment]
urllib3 < 2 is impacted by a few vulnerabilities so it would really be nice to get a new minor release of kubernetes with #2131 included :pray: . RIght now we are forced to trick pip in our installation in order to force a version of urllib3>2

**Comment by namoshizun** [comment]
+1 ! We are using poetry and it is very tricky to force it install kubernetes lib.

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/releases/tag/v1.29.0 is cut, we can release a new version 1.29.

**Comment by yliaog** [comment]
https://github.com/kubernetes-client/python/releases/tag/v29.0.0a1
