### ISSUE TITLE
How to delete a custom object and wait until it is cleaned up with `propagation_policy`

### ISSUE THREAD

**Issue by TrafalgarZZZ** [kubernetes-client/python#2161]
**What is the feature and why do you need it**:
I'm trying to use Kubernetes python sdk to delete a CR with `custom_api.delete_namespaced_custom_object`. My CR has a finalizer and a controller will clean some dependant resources when a `deletionTimeStamp` is added on the CR. When the resources are cleaned up, the finalizer will be removed and the CR will then be cleaned up. My question is that how can I make the `custom_api.delete_namespaced_custom_object` fucntion return after my CR is cleaned up.

I've tried adding `propagation_policy='Foreground' and 'Background'` as a parameter to the function but it does not work: It deletes the CR, returns immediately but doesn't wait for it to be cleaned up.
```
kwargs = {
  "propagation_policy": "Foreground",  # or "Background"
  "grace_period_seconds: 120
}

self.custom_api.delete_namespaced_custom_object(
                "example.com",
                "v1alpha1",
                "default",
                "mycrds",
               "demo-cr",
               **kwargs
            )
```

Is it possible to implement this feature using `propagation_policy` or any other similar techniques?

**Describe the solution you'd like to see**:
```
self.custom_api.delete_namespaced_custom_object(..., propagation_policy="Foreground")
```
Such code may block until the CR is really deleted.

**Comment by roycaihw** [comment]
Your usage of `Foreground` policy is correct. 

However, `delete_namespaced_custom_object` does not block on object deletion. You need to write your own code to wait for the object to be non-existing. kubectl achieves it by sending multiple API calls to the server. You can try running kubectl with `-v=9` to see what APIs kubectl uses to wait for the deletion to finish. 

Ref: https://kubernetes.io/docs/concepts/architecture/garbage-collection/#cascading-deletion
