### ISSUE TITLE
not able to update/patch the configmap 

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes-client/python#2168]
**What happened (please include outputs or screenshots)**:
I have a configmap as show below
```
Name:         test-configmap
Namespace:    default
Labels:       <none>
Annotations:  <none>
Data
====
test.json:
----
[
   {
      "targets": [
         "127.0.0.1:12321"
      ],
      "labels": {
          "job": "test",
          "element_name": "new-service-a",
          "__test_path__": "/path/x/test"
      }
   }
]
```
I want to replace above information completely (context in test.json)
so I'm using python kubernetes client as show below

 ```
config.load_kube_config()
kube_client = client.CoreV1Api()

data = json.dumps(testsinfo,indent=4) // testsinfo is a list , which as multiple entry(dict) as show in configmap
data1 = {'test.json': data} //NOTE: here data.. (is a json string (with mutiple entry))

resp = kube_client.patch_namespaced_config_map("test-configmap", namespace, data1, pretty='true')
```
it is not updating the configmaps.

**What you expected to happen**:
the data should be replaced with new data.

**How to reproduce it (as minimally and precisely as possible)**:
mentioned in above steps

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
-`Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
`
- OS (e.g., MacOS 10.13.6):
ubuntu 18.04.5
- Python version (`python --version`)
Python 3.6.9
- Python client version (`pip list | grep kubernetes`)
`kubernetes (26.1.0)`

**Comment by roycaihw** [comment]
Could you check the [our examples](https://github.com/kubernetes-client/python/tree/master/examples) and look for patch and update examples?
