### ISSUE TITLE
Regenerate supported client versions for kubernetes-client/gen#259 and kubernetes-client/gen#260

### ISSUE THREAD

**Issue by arcivanov** [kubernetes-client/python#2174]
The update would provide CustomObjectApi with field_validation capability delivered in kubernetes-client/gen#259 and kubernetes-client/gen#260

**Comment by arcivanov** [comment]
@yliaog

**Comment by arcivanov** [comment]
Nope. 29.0.0 does not include those patches.

**Comment by roycaihw** [comment]
Oh I thought the PR [included the change](https://github.com/kubernetes-client/python/pull/2176/files#diff-666eacd060c8111fca12aa57465a90159785af46d1c751fa2b9e0baffa6e8ad7). <-- Could you double-check? We may have missed something, in that case we can re-generate the client.

**Comment by arcivanov** [comment]
Yeah you're right, it's in 29 already. Thanks!

**Comment by roycaihw** [comment]
No problem! Thanks for confirming!

/close
