### ISSUE TITLE
Way to get only current logs, without follow and  line by line

### ISSUE THREAD

**Issue by m350** [kubernetes-client/python#2179]
**Link to the issue (please include a link to the specific documentation or example)**:
In https://github.com/kubernetes-client/python/issues/199#issuecomment-614084830
we see example of getting logs until interrupt.
**Description of the issue (please include outputs or screenshots if possible)**:
We don't have straight way to get only part of logs line by line.

I found how we can use current code to achieve this 

```
import kubernetes

configuration= kubernetes.config.load_kube_config()
with kubernetes.client.ApiClient(configuration) as api_client:
Corev1Api = kubernetes.client.CoreV1Api(api_client)
resp = Corev1Api.read_namespaced_pod_log( name=pod_name, namespace=namespace_name , _preload_content=False)
  for line in kubernetes.watch.watch.iter_resp_lines(resp):
    print(line)
```

**Comment by roycaihw** [comment]
Could you elaborate what's the ask here?

**Comment by m350** [comment]
> Could you elaborate what's the ask here?

There is no question asked.
I found the way of using python module for Kubernetes to get data line by line. 
I suggest to add this info to docs.
I found that it may be helpful.
