### ISSUE TITLE
api by yaml

### ISSUE THREAD

**Issue by zfrhv** [kubernetes-client/python#2181]
I was wondering why not to do something like [this](https://github.com/zfrhv/hnc-ui/blob/main/image/k8s.js).  
I wrote it in js but its similar in python.

the input is a yaml/json object, and then its automatically transferred into api url with all the versions and whats needed.
the usage will be so easy, and its more kubernetes native!

for example creating a deployment will be:
```python
config.load_kube_config()
with open(path.join(path.dirname(__file__), "deployment.yaml")) as f:
    dep = yaml.safe_load(f)
    resp = client.create(dep)
```
its similar to `kubectl create -f deployment.yaml`, so easy to understand and use.

**Comment by kwibus** [comment]
`create_from_yaml` from  [kubernetes.utils.create_from_yaml.py](https://github.com/kubernetes-client/python/blob/df43d155d9252ab980bf5454e4b9574c5d5c7348/kubernetes/utils/create_from_yaml.py#L97) might do what you want

**Comment by zfrhv** [comment]
nnnice
thank you!
