### ISSUE TITLE
read proxy-url from kubeconf

### ISSUE THREAD

**Issue by kwibus** [kubernetes-client/python#2183]
**What is the feature and why do you need it**:

kubeconfig support the cluster option [proxy-url](https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#Cluster).
I think it would be useful if function like  `load_kube_config`  would use that to set `kubernetes.client.configuration.proxy`

**Describe the solution you'd like to see**:
the changes that are need to implemented are minimal. already started with merge request #2182

**Comment by richardnpaul** [comment]
Just came across this as I was trying to use the rubusta krr plugin to k9s and I use a proxy->vpn configuration to access the clusters which are locked down to certain IP addresses.  I've had to work back through the python code to this dependency to figure out that proxy-url wasn't supported to then find that there are multiple people trying to get this use case working recently.

**Comment by tianshihan818** [comment]
I tried to set the proxy as this:

```python
from kubernetes import client, config

config.load_kube_config(DEFAULT_KUBECONFIG)
configuration = client.Configuration()
configuration.proxy = DEFAULT_PROXY
c = client.ApiClient(configuration=configuration)
```

And it works for the CoreV1Api methods:
```python
client.CoreV1Api(c).list_namespaced_pod(...)
```

But doesn't work for:
```python
dynamic.DynamicClient(c).resources.get(...)
```

Would you share any ideas? Thanks!

**Comment by kwibus** [comment]
@richardnpaul  merge request does now include unittest. 
Did not have time until now to add them. 
But i agree its better to add them

**Comment by kwibus** [comment]
@tianshihan818 don`t know if this is best location to ask questions, But might be able to help you.

``` python
from kubernetes import client, config

config.load_kube_config(DEFAULT_KUBECONFIG)  # this sets Configuration._default

#  this creates a new empty Configuration not using Configuration._default
# configuration = client.Configuration()  
#  use this instead
configuration =  client.Configuration().get_default_copy()

configuration.proxy = DEFAULT_PROXY
c = client.ApiClient(configuration=configuration)

# are you sure this worked before?
client.CoreV1Api(c).list_namespaced_pod(...)

# I assume this will work now
dynamic.DynamicClient(c).resources.get(...) 
```
I am also new to this project, so i can be wrong. 
But i hope this helps,

**Comment by jcox10** [comment]
I would really like to see this move forward also, it's very unintuitive to have to set this manually in the code.
