### ISSUE TITLE
Port forward a service

### ISSUE THREAD

**Issue by AlbertoSoutullo** [kubernetes-client/python#2195]
I would like to know if there is a way to get a service, and create a port forward to my local machine. I saw that his can be done pretty easily with external libraries, but I would like to stick with only one K8s library. 

My idea is to forward whatever Thanos pod is available through it's service to my local machine, and then make queries to download some metrics to analyze them locally.

Looking at the documentation and other issues, like [pod_porforward.py](https://github.com/kubernetes-client/python/blob/master/examples/pod_portforward.py) or #2138, but those couldn't really help me, since they are specific to pods, and I would like to do it through a service.

Is there a way to do this? Or I am not completely understanding the documentation?

Regards.

**Comment by iciclespider** [comment]
@AlbertoSoutullo, use the kubernetes apis to obtain the service and then search for a pod that matches the port you are trying to attach to. This is exactly what the kubectl cli does behind the scenes. The example you linked to does exactly that here: https://github.com/kubernetes-client/python/blob/master/examples/pod_portforward.py#L143-L171

**Comment by AlbertoSoutullo** [comment]
@iciclespider That makes perfect sense now that I think about it. Thank you very much! I will try this and if I find any problem I will reopen this.

**Comment by iciclespider** [comment]
@matthewfischl The port forwarding ability of the does exactly what your step 2 is doing. Here is an example of doing exactly what your step 2 is doing but just in the python code: https://github.com/kubernetes-client/python/blob/master/examples/pod_portforward.py
