### ISSUE TITLE
add verify-* scripts

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/python#22]
Kubernetes has a number of hack/verify-*.sh scripts that some of them may be useful here. For example, to prevent #15 we could adopt kubernetes's hack/verify-boilerplate.sh. This is the issue to track efforts on finding relevant verify scripts and add them to client-python.

**Comment by SEJeff** [comment]
Would these be git pre-commit hooks or part of the linting in the tests?

**Comment by mbohlool** [comment]
It is something in between I guess. k8s verify scripts will be run as a github's PR check and they should pass before a PR can be merge into master. I hoped with this task, we could achieve the same for client-python.

**Comment by dims** [comment]
let's add the verify-boilerplate script to the python-base and run it from travis
