### ISSUE TITLE
kubernetes.client.Configuration.set_default is not working as expected

### ISSUE THREAD

**Issue by DARSHAN-THE-CODER** [kubernetes-client/python#2202]
**What happened (please include outputs or screenshots)**:
    configuraa = client.Configuration()
    configuraa.retries = 1
    client.Configuration.set_default(configuraa)
   Here, I am trying to override retries value from 3 to 1.
  This is from the source code ->
<img width="620" alt="Screenshot 2024-03-01 at 12 30 58 AM" src="https://github.com/kubernetes-client/python/assets/79416723/f86360a6-3c4e-465e-a1cc-14f9d7417cc0">

 But I found that , you are not receiving that parameter here ->
<img width="620" alt="Screenshot 2024-03-01 at 12 32 19 AM" src="https://github.com/kubernetes-client/python/assets/79416723/9bb6416e-9843-40a8-8bc7-0db96696af7e">

**What you expected to happen**:
  Expected behaviour -> User should be able to override max retry times incase cluster is not reachable
**How to reproduce it (as minimally and precisely as possible)**:
 Try to reach any cluster which doesnt exist properly from the above code
**Anything else we need to know?**:
 After a long time, this error is printed , Which takes literally a lot of time ! and get this error message 
<img width="1668" alt="Screenshot 2024-03-01 at 12 46 08 AM" src="https://github.com/kubernetes-client/python/assets/79416723/9a2ab51d-6a33-4c01-ac6d-82a89612b99b">

**Environment**:
- Kubernetes version (`kubectl version`) : Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14") , Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.9-gke.1092000" 
- OS (e.g., MacOS 10.13.6): linux/amd64
- Python version (`python --version`) : Python 3.6.8
- Python client version (`pip list | grep kubernetes`):        kubernetes                    26.1.0

**Comment by showjason** [comment]
Hi, here [rest.py](https://github.com/kubernetes-client/python/blob/851dc2a0b10d1bc07826c6ade489d1bd2ef431c3/kubernetes/client/rest.py#L77) is the right code receiving the parameter `retries`.

**Comment by showjason** [comment]
> > Hi, here [rest.py](https://github.com/kubernetes-client/python/blob/851dc2a0b10d1bc07826c6ade489d1bd2ef431c3/kubernetes/client/rest.py#L77) is the right code receiving the parameter `retries`.
> 
> It is not working, as in even retries is not getting applied

please try the following code:
```
from kubernetes import client, config

conf = client.Configuration()
conf.retries = 3
config.load_kube_config(client_configuration=conf)
client.Configuration.set_default(conf)

v1 = client.CoreV1Api()

resp = v1.read_namespaced_pod("<pod_name>", "<namespace>")
print(resp)
```
