### ISSUE TITLE
Deprecation warning datetime.datetime.utcnow().

### ISSUE THREAD

**Issue by aguzmans** [kubernetes-client/python#2213]
We are using using this library for some e2e testing and receive a few deprecation warnings about this line

https://github.com/kubernetes-client/python/blame/851dc2a0b10d1bc07826c6ade489d1bd2ef431c3/kubernetes/base/config/kube_config.py#L83

The warning looks like this:
```
(...)
/my/paht/kubernetes/config/kube_config.py:83: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

python version: `python3.12`
using venv and installed the library with pip via requirements.txt file.
```
(...)
kubernetes==29
(...)
```

**Comment by roycaihw** [comment]
/help

Is there a new method that can be used to replace this method? If so, would you like to send a PR?

**Comment by aguzmans** [comment]
> /help
> 
> Is there a new method that can be used to replace this method? If so, would you like to send a PR?

I think my knowledge of the project is too limited, I am more of an incidental user. the fix should not be hard, but it might take me very long to get anything meaningful moving.

**Comment by roycaihw** [comment]
> > /help
> > Is there a new method that can be used to replace this method? If so, would you like to send a PR?
> 
> I think my knowledge of the project is too limited, I am more of an incidental user. the fix should not be hard, but it might take me very long to get anything meaningful moving.

No problem! Thank you @aguzmans for reporting the issue. And @showjason thank you for opening the PR!
