### ISSUE TITLE
K8s Python interface issue

### ISSUE THREAD

**Issue by Jicming** [kubernetes-client/python#2222]
When I was experimenting with the Python client, I found a configuration that I didn't know what to fill in as follows：

configuration.api_key['authorization'] = 'YOUR_API_KEY'

**Comment by roycaihw** [comment]
Please take a look at the [examples](https://github.com/kubernetes-client/python/tree/master/examples) on how to use this client

**Comment by Jicming** [comment]
下面这个例子中 configuration.api_key['authorization'] = 'YOUR_API_KEY' 这块填啥呢？
-----------------------------------
from __future__ import print_function
import time
import kubernetes.client
from kubernetes.client.rest import ApiException
from pprint import pprint

configuration = kubernetes.client.Configuration()
# Configure API key authorization: BearerToken
configuration.api_key['authorization'] = 'YOUR_API_KEY'
# Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
# configuration.api_key_prefix['authorization'] = 'Bearer'

# Defining host is optional and default to http://localhost
configuration.host = "http://localhost"

# Defining host is optional and default to http://localhost
configuration.host = "http://localhost"
# Enter a context with an instance of the API kubernetes.client
with kubernetes.client.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = kubernetes.client.WellKnownApi(api_client)
    
    try:
        api_response = api_instance.get_service_account_issuer_open_id_configuration()
        pprint(api_response)
    except ApiException as e:
        print("Exception when calling WellKnownApi->get_service_account_issuer_open_id_configuration: %s\n" % e)
