### ISSUE TITLE
Request timeout in APIs

### ISSUE THREAD

**Issue by piyush5566** [kubernetes-client/python#2227]
**What is the feature and why do you need it**:
When using CoreV1Api, there is no parameter to specify request timeout for API requests, like we have for watch API.
Due to it, sometimes requests take too long or hang indefinitely.

**Describe the solution you'd like to see**:
There should be a parameter _request_timeout for each Kube Apiserver call. There should also be support to set it when creating client object, such that the request timeout will be applied to all API requests to be sent with that client.

**Comment by roycaihw** [comment]
cc @yliaog

**Comment by piyush5566** [comment]
> please take a look at examples/watch/timeout-settings.md in this repo

Thanks for your reply.
I am aware that watch API has parameter "_request_timeout".
But, my doubt is if this parameter  is also supported for normal CoreV1Api calls like list_namespaced_service(), list_namespaced_pod(), etc. i.e. without usage of watch APIs.

**Comment by cesarqdt** [comment]
+1 here, sometimes a pod using a function from the CoreV1Api hangs indefinitely and can't be killed.

**Comment by yliaog** [comment]
https://github.com/search?q=repo%3Akubernetes-client%2Fpython%20_request_timeout&type=code

**Comment by cfloressuazo** [comment]
Perfect! Yes, I didn't realize this existed. Can this issue be closed?

**Comment by yliaog** [comment]
Sure.

/close

**Comment by piyush5566** [comment]
Thanks for the resolution. Please add this parameter in API docs as well.
https://github.com/kubernetes-client/python/tree/master/kubernetes%2Fdocs

**Comment by hterik** [comment]
> There should also be support to set it when creating client object, such that the request timeout will be applied to all API requests to be sent with that client.

This part of the issue is not resolved yet. See https://github.com/kubernetes-client/python/issues/1961 related to client-global timeout applied on all calls.
