### ISSUE TITLE
Version 30.0?

### ISSUE THREAD

**Issue by arcivanov** [kubernetes-client/python#2229]
**What is the feature and why do you need it**:

Kubernetes 1.30.0 has been released.

**Describe the solution you'd like to see**:

Starting the 30.0 release train.

**Comment by arcivanov** [comment]
@yliaog

**Comment by yliaog** [comment]
sure, I can start the 1.30 release

**Comment by arcivanov** [comment]
Thank you!

**Comment by yliaog** [comment]
1.30.1 has been released.
