### ISSUE TITLE
How to get access to the slack channel?

### ISSUE THREAD

**Issue by matthewfischl** [kubernetes-client/python#2232]
How do we get access to the slack channel mentioned in the readme?  

https://kubernetes.slack.com/messages/C76GB48RK/

Is this channel still active? 

Thanks!!

**Comment by roycaihw** [comment]
The channel is active. Maybe check https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md for access?

**Comment by harshit240205** [comment]
Yes ! it's working.
https://kubernetes.slack.com/messages/C76GB48RK/
