### ISSUE TITLE
Support new Kubernetes Sidecar Containers

### ISSUE THREAD

**Issue by taleinat** [kubernetes-client/python#2247]
**What is the feature and why do you need it**: [Kubernetes Sidecar Containers](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/) are useful and I'd like to be able to use them via the Python client.

**Describe the solution you'd like to see**:  Sidecar containers are defined by creating an Init Container with restartPolicy set to "Always". However, the V1Container class currently does not have a "restart_policy" attribute. I'm not very familiar with the implementation of this client, but this would seem like a straightforward thing to add support for.

**Comment by tomplus** [comment]
Which version of the library do you use?

It's already implemented (+v28)
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Container.md

**Comment by taleinat** [comment]
You're right!

I'm using version 29.x and it is indeed there now that I took another look. I was sure I had checked this thoroughly before creating this issue... my apologies for the noise.
