### ISSUE TITLE
When I call the query deployment interface, it returns 403 forbidden.

### ISSUE THREAD

**Issue by Heaven25333** [kubernetes-client/python#2248]
**What happened (
![图片](https://github.com/kubernetes-client/python/assets/126088761/16910ebe-a62a-48bf-a267-b690b365b98f)
)**:

**Anything else we need to know?**:I have two versions of k8s here, one is version 1.24 and the other is version 1.26. When I call the API to query the deployment information, the 1.24 version can work normally, but the 1.26 version will return 403. Please help me check

**Environment**:
- Kubernetes version (`1.26`):
- OS (MacOS):
- Python version (3.9)
- Python client version (`29.0.0`)

**Comment by gaiusgdcruz** [comment]
@Heaven25333 I think this is due to the lack of RBAC permissions for the user, grant the required role/permissions to the user and this error will be resolved.
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#kubectl-create-rolebinding
