### ISSUE TITLE
Azure error being logged as debug message

### ISSUE THREAD

**Issue by MJLongstreth-tiq** [kubernetes-client/python#2257]
https://github.com/kubernetes-client/python/blob/7a278c794a101989cc19fe8eef1e9799235d9805/kubernetes/client/rest.py#L226-L235

Ran into an issue here, where the rest call is returning a 200 code, but with an error message:

RawError: {"code":"SnapshotsLimitReached, "message": "The incremental snapshot count was exceeded the limit for disk **REDACTED**. Please delete an incremental snapshot before creating another one."}

Would be great if this could check the response for an error and log the error at error level, as opposed to debug

**Comment by roycaihw** [comment]
IIUC the log is written only when the debug logging is enabled, which seems working as intended to me. 

Are you suggesting that we add additional error level logging, which will be written even when debug logging is disabled?
