### ISSUE TITLE
Use a threadpool for async requests

### ISSUE THREAD

**Issue by yuvipanda** [kubernetes-client/python#226]
Currently, a new thread is created for each HTTP request. Would be nicer to have the option of using a ThreadPool with a ThreadPoolExecutor instead.

We can already wrap this ourselves when using, but would be nice to do this in the library itself so async usage is cleaner

**Comment by dims** [comment]
@yuvipanda : we are using urllib3.PoolManager, please see https://github.com/kubernetes-client/python-base/blob/7c8e59b58d9a769f1ca3f818aa91c8a6538b51b1/rest.py#L110

**Comment by yuvipanda** [comment]
Aaah, whoops! Didn't notice that - it was doing Thread() last time I looked (was a while ago!). Thanks :)

**Comment by yuvipanda** [comment]
I'm actually curious about https://github.com/kubernetes-incubator/client-python/blob/f399ece006d43970a9d25052798782db1407fd05/kubernetes/client/api_client.py#L331 - which starts an entirely new thread for each request still. This is a thread pool, unrelated to the urllib3 connection pool...

**Comment by yuvipanda** [comment]
Note: I've started using a threadpool for this in my applications and performance is much better!

**Comment by mbohlool** [comment]
That is a good idea. Would I suggest you contribute it back to `swagger-codegen`. Their templates should be straightforward to edit with your changes. When you did, we can import the changes here.
