### ISSUE TITLE
py dependency seems unneeded

### ISSUE THREAD

**Issue by jelly** [kubernetes-client/python#2286]
The tests have a dependency on [py](https://github.com/kubernetes-client/python/blob/master/test-requirements.txt#L6), but I can't see anything in the code import this and the tests run successfully without it.

Also note that the `py` package is in maintenance mode and should not be required anymore by new projects.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 10.13.6):
- Python version (`python --version`) 3.12
- Python client version (`pip list | grep kubernetes`) 28.1

**Comment by roycaihw** [comment]
Thanks for reporting this! I agree if the tests are not depending on `py` then we don't need this. Would you mind creating a PR to verify if the tests continue to pass?
