### ISSUE TITLE
There is no way to determine the exit code for an exec command

### ISSUE THREAD

**Issue by rubenvw-ngdata** [kubernetes-client/python#2300]
**What is the feature and why do you need it**:

Would be handy to identify the exit code for a command being executed. This holds information about whether the command has succeeded.

**Describe the solution you'd like to see**:
GET /api/v1/namespaces/{namespace}/pods/{name}/exec to return an object that holds exit code, stdin, stdout and stderr separately

**Comment by ofrzeta** [comment]
Hi, does this example not do what you want? https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py You can either exec with _preload_content=False or continuously read from the stream response.

**Comment by rubenvw-ngdata** [comment]
Yes, that helped, thx for your suggestion.
