### ISSUE TITLE
[Feature Request] Implement a Config Loader

### ISSUE THREAD

**Issue by codevulture** [kubernetes-client/python#237]
Current Implementation Of Client loads configuration from yaml File:

Following function loads yaml and do the processing.
> https://github.com/kubernetes-client/python-base/blob/7c8e59b58d9a769f1ca3f818aa91c8a6538b51b1/config/kube_config.py#L309

`_get_kube_config_loader_for_yaml_file`

There are many cases and projects where Configurations are present in different options like ini file which needs to be loaded where creating a ConfigurationObject and assigning parameters is one way.It could save a lot of code if generic handler for loading could be implemented in Client-python as well.

>  If this looks feasible  i can also volunteer to work on the same

**Comment by codevulture** [comment]
Thanks, I will be posting the structure to discuss shortly.

**Comment by codevulture** [comment]
Please find a draft version for implementation detail:


- An Example is worth a thousand words:
Sample file of a project using kubernetes having a section to declare parameters in it's local conf:
`Project.conf`
>.
>.
>[kubernetes]
> api_root/base_url=127.0.0.1(url)
> ssl_client_crt_file=file path
> ssl_ca_crt_file=file path
> ssl_verify_server_crt=file path
> token_file=file_path

- Assumption:
Configuration File have to follow convention of parameters name in order to be loaded.

- Proposal:
So instead of Making a [Configuration Object](https://github.com/kubernetes-client/python-base/blob/8704ce39c241f3f184d01833dcbaf1d1fb14a2dc/configuration.py#L36) and assigning each parameter to configuration Object.
We can have a INI type of file loader similar to implementation of yaml loader for projects:
Like: [Yaml Config Loader](https://github.com/kubernetes-client/python-base/blob/8704ce39c241f3f184d01833dcbaf1d1fb14a2dc/config/kube_config.py#L316)

**Comment by mbohlool** [comment]
Thanks for providing the example. The part I am not clear on yet is if we save much code by generalizing config. Also the example is an ini file, what about the new code structure? What do you want to generalize?

**Comment by codevulture** [comment]
@mbohlool : 

>The part I am not clear on yet is if we save much code by generalizing config.

- If this was a case of single project there might not be a need to load params from ini, but taking the case of various projects doing the same thing might need some consideration. [Sample]( https://review.openstack.org/475893)

>Also the example is an ini file, what about the new code structure? What do you want to generalize?

- Code Structure would look something like:

```
def load_kube_config(config_file=None, context=None,
                     client_configuration=configuration):
    if config_file is None:
        config_file = os.path.expanduser(KUBE_CONFIG_DEFAULT_LOCATION)
    if config_file.endswith('.conf'): #Something like checking file, but this is just an assumption
        _get_kube_config_loader_for_ini_file(config_file,   active_context=context,client_configuration=client_configuration
        ).load_and_set()
    else:
        _get_kube_config_loader_for_yaml_file(config_file, active_context=context, client_configuration=client_configuration).load_and_set()
```
and similar to _get_kube_config_loader_for_yaml_file: 
```
def _get_kube_config_loader_for_ini_file(filename, **kwargs):
    with open(filename) as f:
        return KubeConfigLoader(
            config_dict=load(f)  # find a way to load config,
            config_base_path=os.path.abspath(os.path.dirname(filename)),
**kwargs)
```

OR 

maybe use a generic loader like:
```
def load_kube_config(config_file=None, context=None,
                     client_configuration=configuration):
    if config_file is None:
        config_file = os.path.expanduser(KUBE_CONFIG_DEFAULT_LOCATION)
    _get_kube_config_loader(config_file,   active_context=context,client_configuration=client_configuration
        ).load_and_set()
```
and implement loader based on file type (maybe ending with conf, or passing additional param to check whether file needs to be loaded in specific type.
and 
```
def _get_kube_config_loader(filename, **kwargs):
    with open(filename) as f:
        return KubeConfigLoader(
            config_dict=load(f)  # find a way to load config as per type if passed as kwargs,
            config_base_path=os.path.abspath(os.path.dirname(filename)),
**kwargs)
```

I do not have an exact model at the moment but it would be good to hear from you about your thought on this. This may or may not be needed but it would be good to have.
