### ISSUE TITLE
[Examples] Incorrect Module Reference

### ISSUE THREAD

**Issue by codevulture** [kubernetes-client/python#252]
[client-python/examples/create_thirdparty_resource.md](https://github.com/kubernetes-incubator/client-python/blob/dab09e0e92ee025a2ff9a43d406b20c234525ac9/examples/create_thirdparty_resource.md#L10)
Shows:
`from kubernetes.rest import ApiException`
should be
` from kubernetes.client.rest import ApiException`
Kindly check.

**Comment by mbohlool** [comment]
Yes, all examples need to be updated. We should update example's template (and probably documentation templates) to match our client structure.

**Comment by yjww** [comment]
Could I be assigned this? 

I would go through and fix the module imports for all the examples.

Could you please elaborate on what else needs to be changed about the template for the examples and the documentation? I could try to see what I can do.

**Comment by mbohlool** [comment]
Great, Fixing imports (and adding a config.load_kube_config) would be a great start. Just look at one of the examples in examples/ folder and make examples template look close to those. Now to fix templates, you need to copy them somewhere. We are moving toward using kubernetes-client/gen repo for all generations: https://github.com/kubernetes-incubator/client-python/pull/284

I have a PR in that repo to move templates from swagger-codegen to gen repo for java client: https://github.com/kubernetes-client/gen/pull/16

you can follow the same pattern, copy templates and start changing them. Make sure you document the branch/sha key from which you copied templates. Don't do everything in one PR, send a PR for moving templates (and all changes necessary for them to work) first to make sure we are on the right path and then start sending PRs to fix example(s) template. Let me know if you had any questions.

**Comment by yjww** [comment]
Thanks for the pointers. Ok will do. I'll send the PR example by example as I finish them.

**Comment by mbohlool** [comment]
You should be able to edit one template and generate all examples at once.

**Comment by wyjw** [comment]
I'm swamped with work unexpectedly and unfortunately. If anyone else wants to take this, go for it. Sorry.
