### ISSUE TITLE
connect_get_namespaced_pod_exec() how to pass curl command?

### ISSUE THREAD

**Issue by abhi-paul** [kubernetes-client/python#253]
@mbohlool how to pass curl command as argument of `connect_get_namespaced_pod_exec()`, i am able run 'ls' command but not curl command, i fell doing mistake with single or double quotes while passing curl command, trying following curl command
exec_cmd = "curl localhost:9200/_cat/master?v&pretty"

**Comment by mbohlool** [comment]
What do you get when you pass this `exec_cmd`?  Does your container has curl command? (confirm it with kubectl). Would be helpful if you share the code.

**Comment by abhi-paul** [comment]
@mbohlool  thanks for the reply, `exec_cmd = ['/bin/curl', 'localhost:<port>/_cat/indices?pretty']` with this now I am able to execute, but when pass with another argument like `exec_cmd = ['/bin/curl', 'localhost:9200/_cat/indices?pretty', '2>/dev/null']` but with this command it's throwing error ```
curl: (6) Could not resolve host: 2>; Unknown error
command terminated with non-zero exit code: Error executing in Docker Container: 6
```
yes, i am able to execute both the command using kubectl successfully, and curl command i am able to run inside container.

**Comment by mbohlool** [comment]
Instead of last argument just tell exec to not return stderr by param
`stderr=false`

**Comment by abhi-paul** [comment]
@mbohlool 
```
name = "podname"
namespace = "namespace"
exec_cmd = ['/bin/curl', 'localhost:<port>/_cat/indices?pretty', '2>/dev/null']
res=self.core_api_instance.connect_post_namespaced_pod_exec(name,
                                                        namespace,
                                                        command=exec_cmd,
                                                        stderr=False, stdin=False,
                                                        stdout=False, tty=False)
```

I wants to suppress the metering output that I am getting from curl command and due to this I am passing this third argument (2>/dev/null) and just only grab the response, stderr i already set to false. Below is the metering part.

```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1012  100  1012    0     0  19705      0 --:--:-- --:--:-- --:--:-- 19843
```

**Comment by Ark-kun** [comment]
@abhi-paul use `curl -sS ` to silence it.

It won't help you though since the `api.connect_get_namespaced_pod_exec()` is now completely broken.
