### ISSUE TITLE
Load in cluster config by default

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/python#255]
Currently we have two method in config module to load config. One from kube config and the other from in-cluster configs. Either add in-cluster config load to load kube config or add a new method (maybe call it `load_config` or `load` for short) that tries in-cluster first and then kube-config.

**Comment by codevulture** [comment]
@mbohlool : Looks good to me, Just a small questions: Would the differentiation be done on the basis of whether config file is present or not?

**Comment by mbohlool** [comment]
That is a good question. I think it should be on success of loading config not existance of the files only. If loading in-cluster config raised an exception, we can try kube-config. However, I don't have strong opinion on this.

**Comment by pokoli** [comment]
I think we should create a new function, which will try first in-cluster and the kube-config and document this order. 

For people that do not want to rely on default settings they can use the current existing functions. 

@mbohlool I imagine you plan to update all the examples to use this new load method, don't you?

**Comment by jkinkead** [comment]
I'd love to see this as part of the API. I implemented a version of this already; I'm happy to put this into a PR if you like:

```python
# Prereqs:
# - import os
# - 'config' is the instance of  kubernetes.client.Configuration being initialized.

# Code:
# Load credentials from the environment.
base_creds_path = '/var/run/secrets/kubernetes.io/serviceaccount'
with open(os.path.join(base_creds_path, 'token')) as token_file:
    config.api_key['authorization'] = 'Bearer {}'.format(token_file.read())
config.ssl_ca_cert = os.path.join(base_creds_path, 'ca.crt')
# Load the "kubernetes" service items.
service_host = os.environ['KUBERNETES_SERVICE_HOST']
service_port = os.environ['KUBERNETES_SERVICE_PORT']
config.host = 'https://{}:{}'.format(service_host, service_port)
```

**Comment by mbohlool** [comment]
@jkinkead We already have an in cluster config loader. The goal of this issue is to merge the experience of load in-cluster config and kube config (we have both separately).

@pokoli Yes, I will work on examples soon.

**Comment by jkinkead** [comment]
Awesome. Where is the in-cluster loader? I'd love to not have to reimplement this.

**Comment by mbohlool** [comment]
```python
from kubernetes import config
config.load_incluster_config()
...
```
Somebody should add an example for this in examples/ folder.

**Comment by jonastl** [comment]
Would be nice since this is just accidental complexity for the normal case, and for all _our_ kube python projects.

People don't develop and run initial tests in a pod. Running the code however in prod, or doing SIT happens mostly in pods for us, so we're forced to use the try-except _boilerplate_.
