### ISSUE TITLE
Add contribution 101

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/python#266]
Add a contribution document explain the structure of the repo and best practices to start developing. Topics includes (but not limited to):

- What is generated, semi-generated, and manual
- What is base repo and how it is related to this repo
- How to update generated client
- What should be fixed in preprocessing script and what should be an upstream fix
- What should be commit and how many commits my PR should have

**Comment by ebbeelsborg** [comment]
Perhaps also some guidelines on how and when one should write different types of tests (unit, integration, e2e...)?

**Comment by mbohlool** [comment]
That is a good idea. I can start something and then we can all contribute to it.

**Comment by roycaihw** [comment]
> What is generated, semi-generated, and manual
What is base repo and how it is related to this repo

The original design was https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md

Also it would be great if we have document around how to run tests in this repo. Ref: https://github.com/kubernetes-client/python-base/pull/126#issuecomment-491335985

**Comment by scottilee** [comment]
@micw523 any update on this and https://github.com/kubernetes-client/python/issues/910?

**Comment by micw523** [comment]
Thanks for the ping - it will be done - I just returned from a conference and regained my desktop.
