### ISSUE TITLE
How to get pod status and Service NodePort using Python?

### ISSUE THREAD

**Issue by sd2302** [kubernetes-client/python#295]
Help request. Stackoverflow was not useful
1. How can I get a pod status using your Python-API?

2. How can I get a specific service NodePort using your Python-API when I pass a namespace, serviceName ?

**Comment by mbohlool** [comment]
Generally I spin up a local minikube and install `kubernetes` python package and use interactive python interpreter to look at the output and find what I need. For the first one, it is part of a short video I had at pycon: https://youtu.be/84Vbzmq3iWs?t=3m43s
