### ISSUE TITLE
Support multi-watch

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/python#30]
@mml suggested that a multi-watcher would be a nice addition to the Watch Class. I could be a simple multi-threading class that uses existing Watch operations or we can think of something more elegant.

**Comment by thxCode** [comment]
@mbohlool ,  is there any process in this issue?

**Comment by mbohlool** [comment]
The issue needs community support. I have limited time and will assign it to myself when I got a chance to work on this.

**Comment by drdivano** [comment]
Is there a particular reason the kubernetes client uses requests HTTP library?
For instance, in urllib3 it would be possible to use non-blocking I/O to poll multiple watches.

**Comment by dgvigil** [comment]
This is still a valid feature request for the community. Commenting to keep it alive.

**Comment by sebastian-philipp** [comment]
AFAICS, this is not trivial. `kubernetes.client.api_client.ApiClient#__call_api` is blocking.To this make any sense, a solution needs to use fewer threads than the number of watchers.

Then we need an event loop or something similar. Maybe https://github.com/urllib3/urllib3/issues/1323 ? 
Therefore we cannot use `kubernetes.client.api_client.ApiClient#call_api` as it is. 

Hm.

**Comment by sebastian-philipp** [comment]
Possibly?
