### ISSUE TITLE
Document how to use this with `kubectl proxy`

### ISSUE THREAD

**Issue by yuvipanda** [kubernetes-client/python#303]
I've been profiling an application that talks heavily to the k8s API. A big performance bottleneck is doing TLS in python. It'd be great if instead I can run a kubectl proxy as a sidecar, and direct requests to there. That way, the go proxy deals with TLS (and is much faster)!

I'm not entirely sure how to construct a Configuration object that'll work for this tho. kubectl proxy by default provides an unauthenticated http port..

**Comment by mbohlool** [comment]
This should work:

```python
from kubernetes.client import configuration
configuration.host = "127.0.0.1:8001"

# no need to call config.load_kube_config()
```

If you want a client with this config but don't want to change global config:
```python
from kubernetes import client
from kubernetes.client import Configuration, ApiClient
myconfig=Configuration()
myconfig.host = "127.0.0.1:8001"
myapiclient = ApiClient(config=myconfig)
v1 = client.CoreV1Api(api_client=myapiclient)

# no need to call config.load_kube_config()
```

Note: 127.0.0.1:8001 is what `kubectl proxy` normally listen to proxy calls to main cluster. The port however can change based on availability. use what `kubectl proxy` reports.

**Comment by yuvipanda** [comment]
Thank you, this is useful. Is the singleton Configuration object still recommended or should I switch to using this instead in all my code?

**Comment by mbohlool** [comment]
It is completely depends on your application. Singleton is for ease of use when you only talk to one cluster. If you want to connect to multiple clusters concurrently then you need to follow the second example.
