### ISSUE TITLE
ResourceWarning: unclosed SSLSocket

### ISSUE THREAD

**Issue by abhi-paul** [kubernetes-client/python#309]
while calling `self.core_api_instance.list_namespaced_pod` method getting following warning message:
```
/usr/lib64/python3.5/json/decoder.py:355: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<lan-ip>', 40169), raddr=('<remote-ip>', 6443)>
  obj, end = self.scan_once(s, idx)
```
**Note**:I am using **unittest package in python** then only above warning message is coming. Any idea reason behind it?

**Comment by kanwar-saad** [comment]
I am also seeing this in unittest and python3.6. Any workaround for this.

**Comment by mugdha-adhav** [comment]
warnings.simplefilter("ignore", ResourceWarning)

**Comment by mturde** [comment]
Hello 


```
import requests
import warnings
warnings.filterwarnings("ignore", category=ResourceWarning, message="unclosed.*<ssl.SSLSocket.*>")

```
OR

`warnings.simplefilter("ignore", ResourceWarning)`

This code are definitely worked

**Comment by dguyhasnoname** [comment]
thanks to @mturde. It worked for me: https://github.com/dguyhasnoname/k8s-cluster-checker/blob/master/objects/test.py

**Comment by tdesikan** [comment]
While ignoring the `ResourceWarning` is one approach, a better one might be to explicitly close all the underlying connection pools that the `kubernetes` client uses.

Adding a `__del__` function and calling `rest_client.pool_manager.clear()` seems to do the trick.

```python   
def __init__(self):
  self._api = client.CoreV1Api()

def __del__(self):
  self._api.api_client.rest_client.pool_manager.clear()
  self._api.api_client.close()
```

**Comment by yliaog** [comment]
/reopen
for further discussion and PR is welcome
