### ISSUE TITLE
kubefed commands 

### ISSUE THREAD

**Issue by strigazi** [kubernetes-client/python#313]
Does it make sense to add the kubefed commands in this client?

Would it make more sense to have a separate package? Similarly to kubectl and kubefed

Thoughts?

cc @clenimar

**Comment by mbohlool** [comment]
According to our client structure proposal, it should be a new repo. The generator repo should do 99% of the job by providing OpenAPI spec of kubefed. @nikhiljindal do you have any opinion on this?

**Comment by nikhiljindal** [comment]
cc @sig-federation-misc

kubefed, in my view, is closer to kubeadm then it is to kubectl.
Kubefed commands cant be autogenerated using the OpenAPI spec of `federation-apiserver`.

**Comment by strigazi** [comment]
So what we do?

Has this item been discussed in a meeting?

**Comment by mbohlool** [comment]
I don't think it is discussed. @nikhiljindal can you elaborate on why we can't auto-generated a python client from OpenAPI spec of federation-apiserver?

**Comment by nikhiljindal** [comment]
We can auto-generate a python client from OpenAPI spec of federation-apiserver, but thats not kubefed.

same way we cant generate kubeadm or kops using OpenAPI spec of kube-apiserver.

What is the motivation here? Is there a user asking for this?
