### ISSUE TITLE
Issue with configuration client

### ISSUE THREAD

**Issue by arnouthoebreckx** [kubernetes-client/python#316]
I got an issue writing a webhook.
It works with google cloud engine and it pulls clusternames through the API.
The chatbot will then ask for a cluster to select.

Now I use the googleapiclient to pull the kube-config from the cluster. 
`"gcloud container clusters get-credentials {0} --zone {1} --project {2}".format(clustername, zone,projectname)`
This works and the server even replies that the config has been added. Now I can create a set deployment etc from here on. 

But if I select a different server after this, my google command will still add the kube-config but it looks like the Kubernetes python client caches the old one and it will keep adding the deployments to the old server.
```
config.load_kube_config()
with open(path.join(path.dirname(__file__), "sampledata/nginx-deployment.yaml")) as f:
       dep = yaml.load(f)
        k8s_beta = client.ExtensionsV1beta1Api()
        resp = k8s_beta.create_namespaced_deployment(body=dep, namespace="default")
        speech = "Deployment created with name " + str(resp.metadata.name) + " in namespace " \
                 + str(resp.metadata.namespace)
```
This piece of code is called everytime I ask the bot to create a deployment. 

Has anyone had a similar issue before?

**Comment by mbohlool** [comment]
config.load_kube_config() will load config to a default `configuration` object. It is only helpful for one time use before you actually create your API client (here in your example `client`). Either recreate the `client` to pick up the configuration or explicitly get `Configuration` object and pass it to your client. While both are identical in practice, I would prefer the later as it is clear why you are re-creating the client.

**Comment by arnouthoebreckx** [comment]
@mbohlool How would you go about recreating the client or the configuration object? I'm pretty new to working with these concepts. Shouldn't the client technically be recreated everytime that specific function in my webhook is called?

**Comment by mbohlool** [comment]
I see that you actually created api client after load config. That part should be fine.

> But if I select a different server after this, my google command will still add the kube-config

Can you make sure that in this part, the command add your new server's config as the default one? look for `current` in the kube-config file after you get config for a new cluster. Make sure the current config is changed to the new one. load_kube_config will load the current/active cluster from you config file.

**Comment by Dimss** [comment]
I've faced with the same problem. 
I've loaded different kubeconfig files, to get a total count of PODs on two different K8S clusters, but the Python API Client was always return count of PODs from the same cluster. 
```
import kubernetes.client
from kubernetes import config
class KubeClient(object):
    def __init__(self, conf=None):
        self.conf = conf
        self.set_kube_configs()
        self.core_api = kubernetes.client.CoreV1Api()

    def set_kube_configs(self):
        if self.conf:
            kubeconfig = "/path/to/kubeconfig/config1"
        else:
            kubeconfig = "/path/to/kubeconfig/config2"
        config.load_kube_config(kubeconfig)

    def fetch_pods(self):
        resp = self.core_api.list_pod_for_all_namespaces()
        print(len(resp.items))

for i in range(0, 100):
    k = KubeClient()
    k.fetch_pods()
    k = KubeClient(True)
    k.fetch_pods()
```
I've upgraded my Python API client to https://github.com/kubernetes-incubator/client-python/releases/tag/v4.0.0a1 and it's solved the problem.
Looks like in previous versions of Python API client, the configuration object was implemented as a single tone, and probably this is why the configuration wasn't actually updated. 
https://github.com/kubernetes-incubator/client-python/blob/master/CHANGELOG.md
