### ISSUE TITLE
watch.stream works only once

### ISSUE THREAD

**Issue by tomplus** [kubernetes-client/python#326]
If you use `Watch.stop()` to stop `stream()` it will stop all next `stream()`. Private attribute `_stop` is not reseted.

```
watch = watch.Watch()

# first
for e in watch.stream(v1.list_namespace):
    print(e)
    watch.stop()  # stop after first item

# next call
for e in watch.stream(v1.list_namespace):
    print(e)

# It should print all namespaces and wait for changes
```

**Comment by mbohlool** [comment]
resolved in #28. Thanks.

**Comment by mbohlool** [comment]
Closed this soon. This repo's submodule `base` need to be updated.

**Comment by pokoli** [comment]
Corrrect issue reference is kubernetes-client/python-base#28

**Comment by sinistersnare** [comment]
This can be closed now, since that MR is merged?
