### ISSUE TITLE
None equality comparison raises error

### ISSUE THREAD

**Issue by ntfrnzn** [kubernetes-client/python#329]
the generated code and its built-in __eq__ comparison raises an error, for example, 

```
import kubernetes
j = kubernetes.client.models.V1Job()
j == None
```

```
AttributeErrorTraceback (most recent call last)
<ipython-input-87-70fc4dcff2b7> in <module>()
      1 import kubernetes
      2 j = kubernetes.client.models.V1Job()
----> 3 j == None

/usr/lib/python2.7/site-packages/kubernetes/client/models/v1_job.pyc in __eq__(self, other)
    170         Returns true if both objects are equal
    171         """
--> 172         return self.__dict__ == other.__dict__
    173 
    174     def __ne__(self, other):

AttributeError: 'NoneType' object has no attribute '__dict__'
```

I don't know if this is an artifact of the swagger implementation, or whether it's something that can be controlled in the project.  I think being able to compare objects to None is a reasonable thing to do and you shouldn't have to resort to 

```
        if type(job) == type(None):  # wow. client library overrides equality comparison, badly.  Throws with a direct None comparison
```

**Comment by mbohlool** [comment]
I think it is a reasonable thing to do too. This is not controlled by this project. If somebody (hint hint) sends a PR to swagger-codegen to fix it, I can update the client here to pick it up. It seems to be a straightforward fix.

**Comment by dims** [comment]
@mbohlool @ntfrnzn looks like this got fixed https://github.com/swagger-api/swagger-codegen/commit/3236ade09dc659c4d63981573d82d043270da2ef

**Comment by mbohlool** [comment]
Nice, we need to pick it up. I have a plan to move all of our small fixes back to swagger-codegen and then update client using latest code in master of swagger-codegen.

**Comment by iamneha** [comment]
I would like to work on this issue. Please assign me
