### ISSUE TITLE
clients are not working if k8s cluster require proxy to access

### ISSUE THREAD

**Issue by geekyabhi** [kubernetes-client/python#333]
I am trying to reach k8s cluster hosted in aws. Using kubectl command I'm able to list all the nodes present in the cluster since proxy is set in the environment, but using kubernetes-incubator python client I am unable to do so, not really know where to set proxy.

code snippet
from kubernetes import client,config
from kubernetes.client import configuration

config.load_kube_config('/root/.kube/config.devenv')
print  configuration.host
v1=client.CoreV1Api()

v1.list_node()

ERROR
https://abhishek-api.dev.devops.net
2017-08-27 03:28:40,499 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdccc9d7210>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /api/v1/nodes

**Comment by IamPrvn** [comment]
try this: 
`from kubernetes.client import Configuration
conf = Configuration()
conf.http_proxy_url="<your proxy>"
config.load_kube_config(client_configuration=conf)
v1 = client.CoreV1Api()`

**Comment by montyz** [comment]
@jueast08 the following worked for me though is a bit of a hack. The trick was that I had to `load_config` to cause `Configuration._default` to be created, and then modify that directly with the proxy_url before creating the `CoreV1Api` object. Perhaps there is a better way to do this via constructors but I couldn't figure it out. Any suggestions welcome.

```
import os
from kubernetes import client, config

kube_config = os.getenv('KUBE_CONFIG')
context = os.getenv('CONTEXT')

proxy_url = os.getenv('HTTP_PROXY', None)
config.load_kube_config(config_file=kube_config,
                        context=context)
if proxy_url:
    logging.warning("Setting proxy: {}".format(proxy_url))
    client.Configuration._default.proxy = proxy_url

kubernetes_client = client.CoreV1Api()
```
