### ISSUE TITLE
kubectl set image ?

### ISSUE THREAD

**Issue by FingerLiu** [kubernetes-client/python#347]
Just want to update image of deployment simple as `kubectl set image`
Try patch_deployment but it seems that it has a few issues, And just can not get it work well.

Is there a simple api like `kubectl set image`  or will there be more docs of how to format the
body of patch_deployment to satisfy the server ?

**Comment by FingerLiu** [comment]
Update:
After some test, this format works for me to update a image of an existing container:
``` python
from kubernetes import client, config
from kubernetes.client.rest import ApiException
from pprint import pprint
config.load_kube_config()
client.configuration.debug = True
api_instance = client.AppsV1beta1Api()
body = {"spec":{"template":{"spec":{"containers":[{"name":"image","image":"gcr.io/xxx/image:tag"}]}}}}
api_response = api_instance.patch_namespaced_deployment('image', 'default', body,pretty=True)
pprint.pprint(api_response)

```

**Comment by mbohlool** [comment]
Would be nice if you can add that as an example (you just need to clean it up a little and make it similar to other examples).

**Comment by FingerLiu** [comment]
Make a PR https://github.com/kubernetes-incubator/client-python/pull/352, please review it.
