### ISSUE TITLE
Load k8s resources from a manifest file and operate on those resources.

### ISSUE THREAD

**Issue by swarupdonepudi** [kubernetes-client/python#349]
This will make it easy for users of the client library to replicate kubectl create -f <manifest.yml> functionality in python modules. [Java client](https://github.com/fabric8io/kubernetes-client/blob/2f3e6de212f848774775bac6108b2f4d57c41f2b/kubernetes-examples/src/main/java/io/fabric8/openshift/examples/LoadExample.java#L48) offers this functionality with client.load("manifest.yml) function.

**Comment by SmilentRhino** [comment]
1. Official [java client](https://github.com/kubernetes-client/java) and python client are generated by swagger code-gen, [kubernetes-client/gen](https://github.com/kubernetes-client/gen), the structure of two java client libraries are quite different.

1. But if you just want the create function, you can do the function mapping, find the write function name by parsing the manifest.yaml and swagger.json.
Here is a sample:
https://github.com/SmilentRhino/kubenetes_ops_scripts/blob/master/kube_create_draft.py
The code is ugly, and can't use directly, just to provide some thoughts.

1. IMHO, golang is the only right way for managing kubernetes now. There is not equial of `kubectl apply` now in other library. 
`kubectl apply` can act as a diff tool, which is quite import for managing kubernetes as code.

1. You might be interested in [helm](https://github.com/kubernetes/helm) and [ksonnet)(https://github.com/ksonnet)

**Comment by swarupdonepudi** [comment]
I am closing this issue since it has already been merged. Thanks @micw523
