### ISSUE TITLE
No Api calls/methods available to create "Deployment", "Daemonsets" descriptors

### ISSUE THREAD

**Issue by mageshmcc** [kubernetes-client/python#351]
Not able to find api methods to create Deployment/Daemonsets Descriptors
eg: create_namespaced_deployment()
      create_namespaced_daoemonset()

**Comment by rajakshay** [comment]
Try these:
https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/docs/AppsV1beta1Api.md#create_namespaced_deployment

https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/docs/AppsV1beta2Api.md#create_namespaced_daemon_set
