### ISSUE TITLE
Impersonation support

### ISSUE THREAD

**Issue by kincl** [kubernetes-client/python#362]
Does the Python client support User Impersonation[1]? I have been able to achieve it by setting the default headers with `header_name` and `header_value` on `kubernetes.client.ApiClient` but that doesn't seem like the best way to do this.

[1] https://kubernetes.io/docs/admin/authentication/#user-impersonation

**Comment by sniranjan** [comment]
@kincl  Were you able to find a way to do this?

**Comment by kincl** [comment]
@sniranjan yes but only through the mechanism I mentioned in my initial message:

```python
from kubernetes import client as kclient
kclient.ApiClient(header_name='Impersonate-User', header_value='impersonated-user-name')
```

Not ideal, but it did meet my needs.

**Comment by antdking** [comment]
For when using other headers (or conditional impersonation), you can use:
```py
import kubernetes as k8s
client = k8s.client.APIClient()
client.set_default_header("Impersonate-User", impersonate_user)
```

This works for ServiceAccount impersonation too: `impersonate_user="system:serviceaccount:ns:my-sa"`

**Comment by rohitagarwal003** [comment]
@yliaog It seems like the python client doesn't support the [official kubeconfig](https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#AuthInfo) fields: `as`, `as-uid`, `as-groups`, `as-user-extra`. Is that expected? Can we fix that?

**Comment by yliaog** [comment]
i think it is just not implemented, if someone can help work on it, that would be great.
