### ISSUE TITLE
pypi kubernetes kubernetes-3.0.0.tar.gz does not contain `requirements.txt`

### ISSUE THREAD

**Issue by mouradmourafiq** [kubernetes-client/python#373]
Adding 'kubernetes==3.0.0' to install_requires in setup file will break `python setup.py install` command because of the missing `requirements.txt` file.

**Comment by jrozansk** [comment]
That's right. Same issue occurred for me. Any plans for updating packages in pypi repositories?

**Comment by foxish** [comment]
+1, I was also hit by this. 
cc/ @mbohlool

**Comment by dims** [comment]
@mouradmourafiq @jrozansk @foxish - should be fixed already via https://github.com/kubernetes-incubator/client-python/pull/369

**Comment by mouradmourafiq** [comment]
I guess we can close this one, already fixed in following versions.
