### ISSUE TITLE
add client requirements to a vendor folder or zip file

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/python#374]
Many of the troubles people have with this client is around the dependencies. There are nice ideas around like [this one](https://vilimpoc.org/blog/2012/11/23/bundling-up-distributable-python-package-libraries-using-pip-and-zip/) that make all of those go away. Starting this thread to discuss supporting something like that for this client to make it self sufficient to run on any platform.

My idea is for the first try to have all dependencies packaged in a file called `vendor.zip` and release it with the package (or make it downloadable through the release page). Then add a parameter to `load_kube_config` and `load_incluster_config` methods to accept the path to this file and use them instead of system packages.

This approach generally works with pure python packages that I believe it is the case for our client. Any thoughts?

**Comment by dims** [comment]
How about we have a small script that checks the versions of packages we need and tells the user to update stuff if needed?

**Comment by mbohlool** [comment]
That is definitely useful too but it may not fix all of the problems. Our requirements are lose to let people run the client on different configuration. e.g. any urllib3 > 1.19.1 were ok until we figured out 1.21 does not work for us. Having vendor folder or file will make sure that we tested the client with those exact versions.

**Comment by dims** [comment]
@mbohlool we can definitely package the dependencies and make it available as a zip. I am hesitating to add hooks in the code to use the zip directly. it's not normal in python community to do that.

**Comment by mbohlool** [comment]
Hmm. It is easy to do it manually like this:

```python
if not ('kubernetes_vendor.zip' in sys.path):
    sys.path.insert(0, 'kubernetes_vendor.zip')
```

What is the concern of adding an optional parameter? By default we won't load that file. I guess we can do it better in our library by adding some checks before adding the path to sys to make sure we are doing it right.

**Comment by dims** [comment]
@mbohlool i've not seen this pattern in any popular libraries. Do you have a precedent we can go by? (not a blog post, but a reasonably popular library)

**Comment by mbohlool** [comment]
I did not do a through research on this though the idea is very similar to virtualenv and we can pitch it to the users of the client as an alpha feature to see if it helps them fix dependencies problem.

I've seen people package their application with all dependencies in a zip file though to make it a self sufficient runnable application. This is close to that except this is a library and do not have python executables with it.

**Comment by dims** [comment]
Right, so let's help them with a script and a zip. If we still see large number of issues then we can consider the code change.

**Comment by mbohlool** [comment]
@dims sure. that looks like a reasonable start and hopefully end :)

**Comment by tomplus** [comment]
Dependencies in Python are a real pain in the neck and it would be nice if we could provide some solution for developers who have a conflict with their own dependencies. The idea with zip files will work but in my opinion it should stay as an option. Traditional behavior is good because is traditional and predictable ;)

I am also thinking about testing the library with every combination of version of dependent libraries. It looks crazy but we can write some script to automate it. It’ll allow us to detect breaking changes in external libraries as fast as possible.

**Comment by dims** [comment]
@tomplus @mbohlool - On the note of "every combination", in OpenStack we have 2 pieces of data that is available to end users

1. The "requirements.txt" which can possibly have ranges
2. The actual list of packages that is tested in the CI system. (Install using requirements.txt and do a `pip freeze` to print out the exact versions used).

So i would recommend running some jobs here in client-python
1.  a job that runs the minimum versions (that adhere to the lowest in requirements.txt)
2.  a job that runs the maximum versions (if upper bound is not specified in requirements, then latest from pypi)
3. a job that just does "pip install" just like a end user would (and publish the exact list that got pulled from pypi)

That should cover majority of the cases and avoid explosion of combinations especially when we add more libraries in the future. And it provides a contract that and end user can expect from us to help with figuring out what they will need in their own environment.

How does that sound?

**Comment by tomplus** [comment]
@dims it sounds good, we can also create a optional solution with vendor.zip for developers who have to use other versions in their project.
