### ISSUE TITLE
ImportError: No module named 'kubernetes' python 3.5.0

### ISSUE THREAD

**Issue by Sathiyarajan** [kubernetes-client/python#379]
Python 3.5.3 and ubuntu 17.04 I am getting the above error after installing with pip install kubernetes.

**Comment by tomplus** [comment]
I can't confirm it. Are you sure that you install library for python3 ? Ubuntu can have both version of Python. Could you paste output from command `pip3 freeze` ?

**Comment by DanielClaudeBaeriswyl** [comment]
I have the same issue. Here my pip3 freez
absl-py==0.2.0
aiohttp==3.1.3
alabaster==0.7.10
anaconda-client==1.6.9
anaconda-navigator==1.7.0
anaconda-project==0.8.2
asn1crypto==0.24.0
astor==0.6.2
astroid==1.6.1
astropy==2.0.3
async-timeout==2.0.1
attrs==17.4.0
Babel==2.5.3
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==1.5.0
bokeh==0.12.13
boto==2.48.0
Bottleneck==1.2.1
cachetools==2.1.0
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
click==6.7
cloudpickle==0.5.2
clyent==1.2.2
cmocean==1.1
colorama==0.3.9
colour==0.1.5
conda==4.4.10
conda-build==3.4.1
conda-verify==2.0.0
contextlib2==0.5.5
cryptography==2.1.4
cvxopt==1.2.0
cycler==0.10.0
Cython==0.27.3
cytoolz==0.9.0
dask==0.17.2
datashape==0.5.4
decorator==4.2.1
dill==0.2.7.1
distributed==1.20.2
docutils==0.14
entrypoints==0.2.3
et-xmlfile==1.0.1
Events==0.3
Faker==0.8.15
fastcache==1.0.2
filelock==2.0.13
Flask==0.12.2
Flask-BasicAuth==0.2.0
Flask-Cors==3.0.3
gast==0.2.0
gevent==1.2.2
glob2==0.6
gmpy2==2.0.8
google-auth==1.5.0
greenlet==0.4.12
grpcio==1.11.0
gunicorn==19.8.1
h5py==2.7.1
heapdict==1.0.0
html5lib==0.9999999
idna==2.6
idna-ssl==1.0.1
imageio==2.2.0
imagesize==0.7.1
ipaddress==1.0.22
ipykernel==4.8.0
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.1
isort==4.2.15
itsdangerous==0.24
jdcal==1.3
jedi==0.11.1
Jinja2==2.10
joblib==0.11
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.31.5
jupyterlab-launcher==0.10.2
kubernetes==6.0.0
lazy-object-proxy==1.3.1
llvmlite==0.21.0
locket==0.2.0
lxml==4.1.1
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.1.2
mccabe==0.6.1
mistune==0.8.3
mpmath==1.0.0
msgpack-python==0.5.1
multidict==4.2.0
multipledispatch==0.4.9
multiprocess==0.70.5
navigator-updater==0.1.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
nltk==3.2.5
nose==1.3.7
notebook==5.4.0
ntplib==0.3.3
numba==0.36.2
numexpr==2.6.4
numpy==1.14.0
numpydoc==0.7.0
oauthlib==2.1.0
odo==0.5.1
olefile==0.45.1
openpyxl==2.4.10
packaging==16.8
pandas==0.21.0
pandocfilters==1.4.2
parso==0.1.1
partd==0.3.8
path.py==10.5
pathlib2==2.3.0
pathos==0.2.1
patsy==0.5.0
pep8==1.7.1
pexpect==4.3.1
pickleshare==0.7.4
Pillow==5.0.0
pkginfo==1.4.1
plotly==2.6.0
pluggy==0.6.0
ply==3.10
pox==0.2.3
ppft==1.6.4.7.1
prompt-toolkit==1.0.15
protobuf==3.5.2.post1
psutil==5.4.3
psycopg2==2.7.4
ptyprocess==0.5.2
py==1.5.2
pyasn1==0.4.3
pyasn1-modules==0.2.2
pycodestyle==2.3.1
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.1
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.8.2
pyodbc==4.0.22
pyOpenSSL==17.5.0
pyparsing==2.2.0
PySocks==1.6.7
pytest==3.3.2
python-dateutil==2.6.1
pytz==2017.3
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==16.0.3
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
randopt==0.1.7
requests==2.18.4
requests-cache==0.4.13
requests-oauthlib==1.0.0
rope==0.10.7
rsa==3.4.2
ruamel-yaml==0.15.35
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.8.1
Send2Trash==1.4.2
simplegeneric==0.8.1
simplejson==3.14.0
singledispatch==3.4.0.3
six==1.11.0
slackclient==1.2.1
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.9
Sphinx==1.6.6
sphinxcontrib-websupport==1.0.1
spyder==3.2.6
SQLAlchemy==1.2.1
statsmodels==0.8.0
sympy==1.1.1
tables==3.4.2
tblib==1.3.2
tensorboard==1.8.0
tensorflow==1.8.0
termcolor==1.1.0
terminado==0.8.1
terminaltables==3.1.0
testpath==0.3.1
text-unidecode==1.2
tflearn==0.3.2
toolz==0.9.0
tornado==4.5.3
tqdm==4.23.2
traitlets==4.3.2
typing==3.6.2
unicodecsv==0.14.1
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.47.0
Werkzeug==0.14.1
widgetsnbextension==3.1.0
wrapt==1.10.11
xlrd==1.1.0
XlsxWriter==1.0.2
xlwt==1.3.0
yarl==1.2.3
zict==0.1.3

**Comment by tomplus** [comment]
Please paste output from commands

* ```python3 --version```
* ```pip3 --version```
* ```python3 -v -mkubernetes```

I try to recreate the issue but some of packages don't exist, for instance:

```
No matching distribution found for anaconda-client==1.6.9 (from -r req (line 4))
No matching distribution found for conda==4.4.10 (from -r req (line 33))
No matching distribution found for clyent==1.2.2 (from -r req (line 29))
No matching distribution found for datashape==0.5.4 (from -r req (line 43))
...
```
I skipped missed packages and install rest of them but still it works for me - I can import `kubernetes` without any problems. IMO it looks like a problem with pip3 or your system. Do you try to upgrade pip3 and reinstall the package ?

**Comment by DanielClaudeBaeriswyl** [comment]
it worked in jupyter notebook. but not in the python console of pycharm !

**Comment by tomplus** [comment]
I don't use pycharm but there is a lot of questions about packages in StackOverflow, eg. https://stackoverflow.com/questions/26069254/importerror-no-module-named-bottle-pycharm Maybe it'll be helpful for you.

**Comment by Sathiyarajan** [comment]
@tomplus if it worked for you I can close it?

**Comment by micw523** [comment]
@tomplus
The two people who replied use Anaconda, a common scientific python package.
Given that, I also use Anaconda and have no problem... One thing is that if you’re using an IDE make sure you’re selecting the right interpreter and (potentially) virtual environment.

If it’s working for you @Sathiyarajan then please close it.

**Comment by tomplus** [comment]
@Sathiyarajan yes, sure, can be closed. Thanks.
