### ISSUE TITLE
Scheduling containers with GPU resources

### ISSUE THREAD

**Issue by dgunjal** [kubernetes-client/python#382]
Hello,
The alpha support for GPU scheduling is available with kubernetes v1.8 and client library is seems to provide support for the same in 3.0 release onward.

While looking the code I could not see how the 3.0 version enables an application to use the available GPUs. May be I am missing something but I will request if someone can provide information on how the library can be used to utilize the GPU services if NVIDIA GPU cards are available.

**Comment by mbohlool** [comment]
1.8 is supported in 4.0 client.

**Comment by dgunjal** [comment]
Thanks for the reply. We have downloaded the 4.0 client as well and tried to find out the support for GPU but we are not able find the GPU support. Are we missing something or could you please point us towards where to look for the GPU specific work in 4.0 client. Your help is really appreciated.

**Comment by mbohlool** [comment]
I am not personally familiar with GPU support of kubernetes. I can help you if you tell me how you do it otherwise (using kubectl for example). Knowing kubectl command, we should be able to do it here too. If you don't know that, the right channel to ask this question is kubernetes-users channel.
