### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused host='localhost', port=8080

### ISSUE THREAD

**Issue by Sathiyarajan** [kubernetes-client/python#385]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/pods?watch=False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faa0ec9df90>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by mbohlool** [comment]
need more information please. a simple code to reproduce and your system configuration.
