### ISSUE TITLE
Find API call to create object from yaml config

### ISSUE THREAD

**Issue by tom-bowles** [kubernetes-client/python#387]
I have a yaml file containing configs that I would like to apply as `kubectl apply -f my_file.yml` would. It is possible to pass configs loaded from yaml unmodified to API calls as discussed in https://github.com/kubernetes-incubator/client-python/issues/63 and illustrated in the `create_deployment.py` example. However, if you have a collection of objects you have to figure out which call to make on which API version to apply each item of config, while the `apiVersion` and `kind` keys in the config, which carry this information, get ignored.

Is there any way to find the right API version object and function given the `apiVersion` and `kind` values other than to have a mapping in my own code? If not, would it be possible to add such a thing, and maybe generic `create` and `delete` calls that read those attributes from the body, thus behaving similarly to kubectl?

**Comment by nielsole** [comment]
As this is the most requested feature in this repo by far I thought I nudge it to the top of the issues.
(https://github.com/kubernetes-client/python/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)
Does someone have a plan on how to implement this? 
pykube handles this by having a mapping: https://github.com/kelproject/pykube/blob/master/pykube/objects.py
I guess kubectl also has this mapping internally? or does it create a list of possible objects and their endpoints each time by querying the server?

**Comment by nakulpathak3** [comment]
Was just searching through the issues for this - there is a related issue https://github.com/kubernetes-client/python/issues/504 and a PR up for this https://github.com/kubernetes-client/python/pull/655. Would be awesome to get it reviewed and in soon.

**Comment by confiq** [comment]
Hi, 
This issue got stale, unfortunately, this client does not support standard `kubectl apply/replace -f -`.
I only assume it does not have it because it will bring more bugs than ever and it will be really hard to debug...

**Comment by nielsole** [comment]
Still the scond-most requested feature: 
/remove-lifecycle rotten

**Comment by yliaog** [comment]
"kubectl apply -f" is currently implemented on the client side, it has many subtle issues. It would be a significant effort to support that in python. That said, there is server side apply feature in main k/k repo that goes to beta in 1.16. It would be better to wait and use that feature directly in python.

**Comment by confiq** [comment]
is there a link for it?

**Comment by yliaog** [comment]
https://github.com/kubernetes/kubernetes/issues/73723
