### ISSUE TITLE
trouble with lib vs application logging

### ISSUE THREAD

**Issue by gardlt** [kubernetes-client/python#391]
I am currently when I enable logging for my application the `config/rest.py` is picking up my application debug and start outputting more logging than I was expecting.
commented out this: 

https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/client/rest.py#L219

and it suppressed the lib logging. 

Is there a way to sure this only enabled if wanted? or could we delete this logger completely?

**Comment by dims** [comment]
I believe you can use stand python logging mechanisms to control the log level of different packages (example `xyz` below)

```
logging.getLogger('xyz').setLevel(logging.INFO)
```

take a peek at "python set logging level" in your fav search engine for more info.

Thanks,
Dims
