### ISSUE TITLE
APIServer Example

### ISSUE THREAD

**Issue by mattmoor** [kubernetes-client/python#393]
Is there an example of writing an APIServer using the Python library?

**Comment by tomplus** [comment]
Hi @mattmoor it's the library to write a client only.

**Comment by mattmoor** [comment]
Ack.  I'm not sure a better forum exists, if so please redirect.

There is an issue here on examples for CRDs and Custom Controllers in Python, and writing an `APIServer` to participate in the API Aggregation layer is arguably a graduation of that.

**Comment by yliaog** [comment]
https://github.com/kubernetes/sample-apiserver, it is in Go though.

**Comment by mattmoor** [comment]
Yes, I'm aware of that thanks.

To my point, [~25% of the lines](https://github.com/kubernetes/sample-apiserver/blob/master/Godeps/Godeps.json#L1114-L1532) in the `Godeps.json` for that are references to `client-go`, so it ends up being a really interesting non-trivial example of talking to the K8s API from Go.  The same for Python would be fantastic.
