### ISSUE TITLE
"Connection pool is full" is reported and client-python stop watching

### ISSUE THREAD

**Issue by sswv** [kubernetes-client/python#402]
Hello, I am using Kubernetes client-python's "watch" API to watch the changes of pod status. My program works well for hours. However, a "Connection pool is full" warning (as follows) will be reported randomly after hours. Then the watcher cannot observe new event from Kubernetes. I guess this issue is related to the use of urllib3. It is a bug? or something I need to pay attention to when using the watch API? Thanks!

`2017-11-23 05:51:03,416 WARNING Connection pool is full, discarding connection: 192.168.48.187`

**Comment by yliaog** [comment]
as discussed in https://github.com/kubernetes-incubator/client-python/issues/290 and fixed in https://github.com/kubernetes-client/python-base/pull/18
