### ISSUE TITLE
Add resource_version assertion behavior when patching

### ISSUE THREAD

**Issue by joeblackwaslike** [kubernetes-client/python#419]
I'm trying to mimic `kubectl annotate` behavior when --resource-version is passed.  In this situation, the `resource_version` supplied is tested by the api server and must match before setting the annotation.  This kind of behavior is fundamentally important for doing any atomic operations. An example would be setting an annotation on an endpoint object for leader election.

As a contrived, more thorough example:

the following call to add an annotation: `test=true` to an endpoint
```
PATCH https://[api-server]/api/v1/namespaces/default/endpoints/[endpoint-name]
{"metadata":{"annotations":{"test":"true"},"resourceVersion":"1"}}
```
Should return
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Operation cannot be fulfilled on endpoints \"couchdb\": the object has been modified; please apply your changes to the latest version and try again",
  "reason": "Conflict",
  "details": {
    "name": "couchdb",
    "kind": "endpoints"
  },
  "code": 409
}
```

When I pass an extra kwarg 'resource_version' to `patch_namespaced_endpoints` that is invalid, the request is still accepted.  I would expect the request to not be accepted and optimally, an exception to be raised.

I'm slightly unfamiliar with working with swagger clients but I am getting better. if someone can guide me in the correct direction, I can hopefully scratch my own itch and submit a pull request.

**Comment by tomplus** [comment]
Hi @joeblackwaslike Try to add `resource_version` to your metadata dict (it has such field https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/docs/V1ObjectMeta.md) instead of kwargs.

**Comment by joeblackwaslike** [comment]
@tomplus I tried adding resource_version to the metadata dictionary that and it too is completely ignored, ie the operation succeeds regardless of value or presence.

**Comment by tomplus** [comment]
@joeblackwaslike, try to use camelCase notation (this dict is sent directly to K8s).

It works for me, it raises exception due to version:

```
    v1 = client.CoreV1Api()
    patch = {'metadata': {'resourceVersion': '1', 
             'annotations': {'my-label: 'test')}}}
    res = v1.patch_namespace('my-namespace', patch)
```

**Comment by joeblackwaslike** [comment]
@tomplus Ah! this works! Thank you very much, turns out I do have to use camel case.
