### ISSUE TITLE
template is optional for AppsV1beta1DeploymentSpec but raises ValueError

### ISSUE THREAD

**Issue by brejoc** [kubernetes-client/python#420]
During the switch to version 4.0.0 of the lib I've noticed, that one of the tests failed: 

```
         File "/home/brejoc/repos/suse/salt/sandbox/lib/python2.7/site-packages/kubernetes/client/models/apps_v1beta1_deployment_spec.py", line 296, in template
           raise ValueError("Invalid value for `template`, must not be `None`")
       ValueError: Invalid value for `template`, must not be `None`
```
But in `__init__` the `template` is treated as an optional parameter:

```
def __init__(self, min_ready_seconds=None, paused=None, progress_deadline_seconds=None, replicas=None, revision_history_limit=None, rollback_to=None, selector=None, strategy=None, template=None)
```

Later on the `template.setter` for `template` is throwing that `ValueError`. Was that design on purpose?

**Comment by tomplus** [comment]
This library is generated by the swagger-codegen and the latest version of this generator respects mandatory parameters in this way...

**Comment by brejoc** [comment]
Okay, thanks for the explanation. I don't think I like what swagger is doing here, but that's the way it is.
