### ISSUE TITLE
Req: Example for deployment rollback

### ISSUE THREAD

**Issue by gangadhars** [kubernetes-client/python#427]
Hi,

When I tried to rollback to last revision, getting below error:
```
Traceback (most recent call last):
  File "deployment_examples.py", line 111, in <module>
    main()
  File "deployment_examples.py", line 105, in main
    rollback_deployment(extensions_v1beta1)
  File "deployment_examples.py", line 86, in rollback_deployment
    body=body)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 273, in create_namespaced_deployment_rollback
    (data) = self.create_namespaced_deployment_rollback_with_http_info(name, namespace, body, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 364, in create_namespaced_deployment_rollback_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 163, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 236, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 622, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/models/extensions_v1beta1_deployment_rollback.py", line 65, in __init__
    self.name = name
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/models/extensions_v1beta1_deployment_rollback.py", line 137, in name
    raise ValueError("Invalid value for `name`, must not be `None`")
ValueError: Invalid value for `name`, must not be `None`
```
Below is snippet that generating error:
```python
def rollback_deployment(api_instance, revision=0):
    rollback_to = client.AppsV1beta1RollbackConfig(revision)
    body = client.AppsV1beta1DeploymentRollback(
        name=DEPLOYMENT_NAME,
        rollback_to=rollback_to)
    api_response = api_instance.create_namespaced_deployment_rollback(
        name=DEPLOYMENT_NAME,
        namespace="default",
        body=body)
    print("Deployment rolled back. status='%s'" % str(api_response.status))
```

You can find the complete code at https://pastebin.com/yNkA85ub

Could you please provide the example for rollback of a deployment?

**Comment by cristifalcas** [comment]
I think that the new deployment needs another name

**Comment by gangadhars** [comment]
Sorry! @cristifalcas . Pasted the wrong exception. Now updated with correct exception.

**Comment by roycaihw** [comment]
It's a problem in k8s openapi spec. This client is generated based on the openapi spec in every k8s release. A PR is in progress here https://github.com/kubernetes/kubernetes/pull/56591. Closing

**Comment by prasad1991** [comment]
w = watch.Watch()
print w
for event in w.stream(v1.list_namespaced_pod,"default"):
    if event['object'].status.phase == "Pending" and event['object'].spec.scheduler_name == scheduler_name:
       # print event['object']
        r1 = event['object'].metadata.name
        #print event['object'].namespace
        print r1
        pod = client.V1Pod()
        pod.api_version="v1"
        pod.kind="Pod"
        pod.metadata=client.V1ObjectMeta(name=r1)
        container= client.V1Container()
        print container

        print client
        container.name="redis"
        container.image= "redis"
        container.priorityClassName="high-priority"
        spec=client.V1PodSpec()
        spec.containers=[container]
        pod.spec=spec
        print pod
        try:
             v1.create_namespaced_pod(name=event['object'].metadata.name,namespace="default",body=pod,_preload_content=False)
        except ValueError:
             print('pass it')

+++++++++++++++++++++++++++++++++++++++getting error +++++++++++++++++++++++++++++
w = watch.Watch()
print w
for event in w.stream(v1.list_namespaced_pod,"default"):
    if event['object'].status.phase == "Pending" and event['object'].spec.scheduler_name == scheduler_name:
       # print event['object']
        r1 = event['object'].metadata.name
        #print event['object'].namespace
        print r1
        pod = client.V1Pod()
        pod.api_version="v1"
        pod.kind="Pod"
        pod.metadata=client.V1ObjectMeta(name=r1)
        container= client.V1Container()
        print container

        print client
        container.name="redis"
        container.image= "redis"
        container.priorityClassName="high-priority"
        spec=client.V1PodSpec()
        spec.containers=[container]
        pod.spec=spec
        print pod
        try:
             v1.create_namespaced_pod(name=event['object'].metadata.name,namespace="default",body=pod,_preload_content=False)
        except ValueError:
             print('pass it')

**Comment by prasad1991** [comment]
w = watch.Watch()
print w
for event in w.stream(v1.list_namespaced_pod,"default"):
    if event['object'].status.phase == "Pending" and event['object'].spec.scheduler_name == scheduler_name:
       # print event['object']
        r1 = event['object'].metadata.name
        #print event['object'].namespace
        print r1
        pod = client.V1Pod()
        pod.api_version="v1"
        pod.kind="Pod"
        pod.metadata=client.V1ObjectMeta(name=r1)
        container= client.V1Container()
        print container

        print client
        container.name="redis"
        container.image= "redis"
        container.priorityClassName="high-priority"
        spec=client.V1PodSpec()
        spec.containers=[container]
        pod.spec=spec
        print pod
        try:
             v1.create_namespaced_pod(name=event['object'].metadata.name,namespace="default",body=pod,_preload_content=False)
        except ValueError:
             print('pass it')
 i am getting error 
Traceback (most recent call last):
  File "custome.py", line 151, in <module>
    container= client.V1Container()
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/models/v1_container.py", line 123, in __init__
    self.name = name
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/models/v1_container.py", line 350, in name
    raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `name`, must not be `None`

**Comment by roycaihw** [comment]
@prasad1991 At a glance the error is unrelated to this issue. Please file a separate issue
