### ISSUE TITLE
when listing objects, the returned list has kind:None for all items

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes-client/python#429]
Cluster version is 1.6.7

Example:

    ret = v1b1e.list_deployment_for_all_namespaces()
    for i in ret.items:
        print("kind: %s" % (i.kind)

Returns:

    kind: None

This is the same for v3 and v4. Also, object type doesn't matter (daemonset, replicationcontroller, statefulset, deployment)

**Comment by tomplus** [comment]
Interesting observation :) The attribute `kind` is not returned by K8s here, you will get it only when you ask about one object (read_namespaced_deployment).

Workaround - let's use type function: `print("type: %s" % type(i))`, it returns:
```
type: <class 'kubernetes.client.models.extensions_v1beta1_deployment.ExtensionsV1beta1Deployment'>
```

**Comment by StevenACoffman** [comment]
Really? Doing this makes me grumpy:
```python
def kube_type_lookup(kube_type):
    if "deployment" in str(type(kube_type)).lower():
        return "Deployment"
    elif "pod" in str(type(kube_type)).lower():
        return "Pod"
    elif "job" in str(type(kube_type)).lower():
        return "Job"
    else:
        return "Unknown"
```
Is this a fixable thing?
