### ISSUE TITLE
Support for v1 alpha AdmissionReview

### ISSUE THREAD

**Issue by gdmello** [kubernetes-client/python#431]
There doesn't seem to be any support for processing [AdmissionRequests](https://kubernetes.io/docs/admin/extensible-admission-controllers/#write-a-webhook-admission-controller) for Dynamic Admission Controllers. Is the reasoning that the client does not invoke the apiserver, thus no machinery needed to construct the request/process the response?

It would be cleaner to process AdmissionRequests via the client, instead of the rather clunky approach of something like `request.json["spec"]["object"]["Spec"]["Containers"]`.

**Comment by ioandr** [comment]
Hi @gdmello any update on this? 

Just bumped into the exact same issue when using the Python client to create a validation webhook for custom resources on Kubernetes.

**Comment by gdmello** [comment]
@ioandr: None, there was no response to this issue. JSON parsing is the only approach atm afair.
