### ISSUE TITLE
Leader Election

### ISSUE THREAD

**Issue by rmb938** [kubernetes-client/python#434]
It would be nice to have a built in way to do leader election similar to the tooling in client-go.

https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/leaderelection.go

**Comment by roycaihw** [comment]
The Java client also supports leader election with a similar implementation. It would be great for the Python client to also support leader election.

**Comment by Invictus17** [comment]
Can someone describe a bit more about this issue or direct me to a resource that could help.

**Comment by Invictus17** [comment]
@roycaihw I'd like to work on this issue.

**Comment by roycaihw** [comment]
/assign @Invictus17

please go for it!

**Comment by dims** [comment]
Looks like the java one is here https://github.com/kubernetes-client/java/commits/master/extended/src/main/java/io/kubernetes/client/extended/leaderelection

**Comment by Invictus17** [comment]
Hi folks,
Sharing a document stating my proposal and a description for this specific task. I'd be happy to address any feedback!
https://docs.google.com/document/d/1KJAcdMv4NZBqyz_WrLfDEVTFnqvlXdrIopHwkcMfWlw/edit?usp=sharing

**Comment by Invictus17** [comment]
@rmb938 @dims It'd be great to have your opinions on the PR!

**Comment by dims** [comment]
@Invictus17 you have @roycaihw reviewing it ... he's the best!

**Comment by Invictus17** [comment]
> @Invictus17 you have @roycaihw reviewing it ... he's the best!

True that :)

**Comment by guettli** [comment]
BTW, leader election seems to be implemented: [python/kubernetes/base/leaderelection at master · kubernetes-client/python](https://github.com/kubernetes-client/python/tree/master/kubernetes/base/leaderelection)
