### ISSUE TITLE
Kubernetes load_config failure while executing from within the POD

### ISSUE THREAD

**Issue by vrock28** [kubernetes-client/python#436]
Here is the code:
===================
from kubernetes import config
import kubernetes.client
from kubernetes.client.rest import ApiException

config.load_incluster_config()
api_instance = kubernetes.client.CoreV1Api()
...
.........

Error:
======
config.load_incluster_config()\n  File "local/lib/python2.7/site-packages/kubernetes/config/incluster_config.py", 
line 93, in load_incluster_config\n    cert_filename=SERVICE_CERT_FILENAME).load_and_set()\n  
File "local/lib/python2.7/site-packages/kubernetes/config/incluster_config.py", 
line 45, in load_and_set\n    
self._load_config()\n  
File "local/lib/python2.7/site-packages/kubernetes/config/incluster_config.py", 
line 51, in _load_config\n    
raise ConfigException("Service host/port is not set.")\n
ConfigException: Service host/port is not set.'

# python --version
Python 2.7.6

python Kubernetes client version 4.0.0 is installed

When i try to execute the statements directly inside the POD,
i see that neither the host or port info is missing 
in the environment.

 python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>>
>>>
>>> print os.environ["KUBERNETES_SERVICE_HOST"]
10.3.0.1
>>> print os.environ["KUBERNETES_SERVICE_PORT"]
443
>>>
[1]+  Stopped                 python

**Comment by kevin-bates** [comment]
@vrock28 - not sure if this is applicable, but I ran into this issue yesterday.  I have a pod (service) that spawns other pods (jobs), then monitors/controls them via the python api.  The monitoring calls were working, but the job-creation calls were producing this error. 
 
The issue was because I use a sub-process (via `Popen()`) from which the jobs are created, yet didn't "flow" the service host and port envs to the sub-process.  Once those two values were propagated, `load_incluster_config()` could complete and the jobs were appropriately created.

**Comment by vrock28** [comment]
@kevin-bates - Thanks for the pointer. My POD runs a Flask application and i am not sure if it actually spawns a sub-process in some way. Nonetheless, how did you manage to prppogate the values to the sub-process ?

**Comment by kevin-bates** [comment]
@vrock28 - `Popen()` takes a `**kwargs`, one of which is an `env` dictionary.  As a result, I could do the following:
```
    # Transfer internal env vars since the launcher starts fresh
    kw['env']['KUBERNETES_SERVICE_HOST'] = os.environ.get('KUBERNETES_SERVICE_HOST')
    kw['env']['KUBERNETES_SERVICE_PORT'] = os.environ.get('KUBERNETES_SERVICE_PORT')
```

**Comment by LinxiFan** [comment]
@vrock28 @kevin-bates I'm experiencing exactly the same error with the same code. I'm running the python client outside any pods or subprocesses, so env variable propagation is likely not the cause.

**Comment by LinxiFan** [comment]
Are you able to resolve this problem? @vrock28

**Comment by vrock28** [comment]
@LinxiFan - No i am still not able to resolve this error. I just hacked a bit to get around the issue to hard code the HOST and PORT

**Comment by LinxiFan** [comment]
@vrock28 I'm using python 3.6, btw, so it's not your python's problem.

**Comment by LinxiFan** [comment]
@vrock28 even after I hardcode the HOST and PORT, I'm still getting "Service token not found" error. Something in the env is seriously wrong ...

**Comment by vrock28** [comment]
@LinxiFan - I just edited the incluster_config.py and removed the code which checks for the env variables.

**Comment by vrock28** [comment]
@LinxiFan - May be trying with earlier rlse of kubernetes ( < 4.0.0) would help ?

**Comment by LinxiFan** [comment]
@vrock28 I'm giving up. For my use case, I can simply use `subprocess` module to call `kubectl` directly and process the stdout. The API is poorly documented and not worth the trouble.
