### ISSUE TITLE
python kubeconfig loading doesn't match kubectl config loading...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/python#445]
I had a .kube/config file with duplicate clusters with the same name (but different information) in the config file, the three different entries each pointed to different clusters, two were dead, but one was alive (I had be repeatedly creating and deleting clusters)

`kubectl` command line happened to chose the working one and worked correctly.

python client library chose the first one in the file (which wasn't working) and failed.

This lead to a very confused experience until I figured out what was going on.

It will be difficult to emulate the `kubectl` parsing exactly, but we should detect duplicate entries and throw an exception.  (and I would argue that `kubectl` probably should too)

This actually probably applies to all client libraries in different languages.

@mbohlool

**Comment by brendandburns** [comment]
We need a spec for this or we risk getting on a treadmill...

--brendan

________________________________

**Comment by roycaihw** [comment]
@brendandburns Totally agree. Just curious if `kubectl` in your test was picking the last one or behaving differently. I will open a PR to add the duplication detection.
