### ISSUE TITLE
kubernetes/client/apis/custom_objects_api.py is missing an update (PATCH) method

### ISSUE THREAD

**Issue by tommyvn** [kubernetes-client/python#453]
Short of monkey-patching `kubernetes.client.CustomObjectsApi` there appears to be no way to PATCH a Custom Resource.

I'd expect to see something similar to other APIs in the library, like https://github.com/kubernetes-client/python/blob/eeaf4f8c3426f099e2d6ebf82300f5286d473b4d/kubernetes/client/apis/apiextensions_v1beta1_api.py#L595-L700 does for deployments, but there are no methods in the custom objects API that enable a partial PATCH to the Kubernetes API :( #

**Comment by craigtracey** [comment]
I am encountering this as well. Not sure how this can be, as this code should have been auto-generated by swagger and PATCH is in the API specification.

**Comment by roycaihw** [comment]
`CustomObjectsApi` is generated from [spec in gen repo](https://github.com/kubernetes-client/gen/blob/39b6e38699ff6c258708b8ebb0ed5aa842c2a5f2/openapi/custom_objects_spec.json). PR is welcome :)

**Comment by craigtracey** [comment]
@roycaihw yes, I noticed this after I posted this comment.  I have changes that I am testing now.

**Comment by craigtracey** [comment]
I have opened https://github.com/kubernetes-client/gen/pull/53 to address this issue.

**Comment by roycaihw** [comment]
kubernetes-client/gen#53 is merged. Closing this one
