### ISSUE TITLE
Unable to initialize V1beta1PodDisruptionBudgetStatus with returned Object PDB from K8S

### ISSUE THREAD

**Issue by azman0101** [kubernetes-client/python#460]
I'm running kubernetes 1.6.7 which create that kind of PDB response:
```json
    {
      "metadata": {
        "name": "myapp",
        "namespace": "mynamespace",
        "generation": 1,
        "creationTimestamp": "2018-02-14T10:04:15Z"
      },
      "spec": {
        "minAvailable": "100%",
        "selector": {
          "matchLabels": {
            "app": "pyapp",
            "release": "pyrelease"
          }
        }
      },
      "status": {
        "observedGeneration": 1,
        "disruptedPods": null,
        "disruptionsAllowed": 0,
        "currentHealthy": 0,
        "desiredHealthy": 0,
        "expectedPods": 0
      }
    },
```
Then, I encounter an error while using the documentation sample:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/PolicyV1beta1Api.md#list_pod_disruption_budget_for_all_namespaces

In fact, [V1beta1PodDisruptionBudgetStatus](https://github.com/kubernetes-client/python/blob/b176bad56897384cad38f44a6a8189504895c359/kubernetes/client/models/v1beta1_pod_disruption_budget_status.py#L143) instance initialization can't have a null/None value.

**Comment by mbohlool** [comment]
dup of #376
