### ISSUE TITLE
V1beta1PodDisruptionBudget deserialization should not throw exception on V1beta1PodDisruptionBudgetStatus

### ISSUE THREAD

**Issue by edolinina** [kubernetes-client/python#466]
create_namespaced_pod_disruption_budget, patch_namespaced_pod_disruption_budget and list_namespaced_pod_disruption_budget throws ValueError("Invalid value for `disrupted_pods`, must not be `None`") because it tries to deserialize V1beta1PodDisruptionBudgetStatus model where disruptedPods is mandatory field.. 
However for V1beta1PodDisruptionBudget object status is optional and not relevant for an example for just created object. Also in V1beta1PodDisruptionBudgetStatus "disruptedPods: null" is valid value

**Comment by DaveTaddei-CR** [comment]
There is a workaround for this issue (only tested with raw JSON as the configuration body).  Calling `create_namespaced_pod_disruption_budget` with the additional parameter `aync=True` correctly created the PodDisruptionBudget.

**Comment by soloman817** [comment]
got the same issue...

**Comment by rvadim** [comment]
Can we fix this during waiting of fixes in Kuberentes? I can't create proper logic of recreating PDB due to unable to get it.

**Comment by mydockergit** [comment]
Any idea when this issue will be solved ?

**Comment by wlodekb** [comment]
workaround from https://github.com/kubernetes-client/python/issues/466#issuecomment-379434054 works also with all objects created from python client needed for `create_namespaced_pod_disruption_budget`
