### ISSUE TITLE
How to watch a single pod for updates

### ISSUE THREAD

**Issue by andrewshilliday** [kubernetes-client/python#467]
I'm having trouble figuring out how, in the python client, to create a watch that monitors a single pod for status updates.  I would have thought that the following code would have worked:

`watch.Watch(api.read_namespaced_pod, namespace='ns', name='name')`

But the above code returns the error

`Got an unexpected keyword argument 'watch' to method read_namespaced_pod`

Is there some other call I should be making, or is 'watch' functionality only supported for lists?

Thanks.

**Comment by andrewshilliday** [comment]
Update: I did manage to get this working using the list_namespaced_pod with field_selector="metadata.name=[name]", but that seems like a hacky work-around. I'm still curious as to how to directly monitor a single pod.

**Comment by ceridwen** [comment]
That *is* the official way to watch a single resource: https://github.com/kubernetes/kubernetes/issues/14289

**Comment by andrewshilliday** [comment]
But there is an endpoint for watching an individual node (e.g. api/v1/watch/pods/my-pod). Does the python not have a means to access the watch endpoints?

**Comment by ceridwen** [comment]
Those endpoints are deprecated, as I understand it.

**Comment by andrewshilliday** [comment]
Ok.  Thanks!
