### ISSUE TITLE
accessing cluster without kube confg

### ISSUE THREAD

**Issue by EvgenyKhaliper** [kubernetes-client/python#472]
Hi, it is possible to access the cluster without kube config file ? If yes, can you please guide me cause i feel lost.

I have kube config file which works perfectly with the client but i need to pass this file along with request as base64 so other microservices in my system will use it to access k8s cluster. Seems like wrong way to do it.

So i've read the token using:
`kubectl -n kube-system describe secret default-token-XXXXX`

What i've done so far is and it fails due to certificates.

        configuration = Configuration()
        configuration.host = "https://address.of.cluster.com"
        configuration.api_key['authorization'] = "token "

        self.core_api = CoreV1Api(ApiClient(configuration=configuration))

thanks

**Comment by wanghonglei5181** [comment]
i have the same problerm

**Comment by craynic** [comment]
It seems that it's also my case. I want to provide the certificates as strings, not file paths.

**Comment by tomplus** [comment]
It may be helpful - https://github.com/kubernetes-client/python/pull/446 and releated issue https://github.com/kubernetes-client/python/issues/430

BTW, @craynic certificates have to be files, urllib3 requires files (https://urllib3.readthedocs.io/en/latest/advanced-usage.html#custom-ssl-certificates-and-client-certificates). Kubernetes Python client creates temporary files with certs even if them are read from kubeconfig.

**Comment by roycaihw** [comment]
Seems @tomplus has solved the issue. Closing
