### ISSUE TITLE
metrics-server endpoint

### ISSUE THREAD

**Issue by P6rguVyrst** [kubernetes-client/python#474]
Couldn't get an email contact so I'll ask here.
Is querying Kubernetes metrics-server supported in the client?
For example endpoint like this: /apis/metrics.k8s.io/v1beta1/namespaces/{namespace}/pods/{name}

**Comment by P6rguVyrst** [comment]
Anwsered in [528](https://github.com/kubernetes-client/python/issues/528) 

api_client = ApiClient()
response = api_client.call_api('/apis/metrics.k8s.io/v1beta1/pods/', 'GET', preaload_content=False)
print(response.text)  # raw HTTPResponse

https://github.com/kubernetes-client/python/blob/master/kubernetes/client/api_client.py#L278

**Comment by darkdragn** [comment]
In case someone else finds this, another viable alternative is:

```python
from kubernetes.config import load_kube_config                     
from kubernetes.client import CustomObjectsApi                                 
load_kube_config()
cust = CustomObjectsApi()
cust.list_cluster_custom_object('metrics.k8s.io', 'v1beta1', 'nodes')
cust.list_cluster_custom_object('metrics.k8s.io', 'v1beta1', 'pods')
```
