### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by a24ibrah** [kubernetes-client/python#479]
I tried to install python client for kubernetes on my windows machine, but I keep getting the following: "error: supposed package directory 'kubernetes\config' exists, but is not a directory"

I tried with different versions but I keep getting the same message?!

**Comment by aogier** [comment]
Hi, have you tried cloning with --recursive ? Seems you're missing the needed base submodule

**Comment by a24ibrah** [comment]
Thanks aogier. I did try to clone with --recursive. However, I did not know why it does not copy the base submodule. I did copy them manually and it worked.

**Comment by micw523** [comment]
This repo is structured in such a way that symbolic links well. You'll need to manually copy the folder when you clone recursively on Windows - that's a current restriction on the repo.
