### ISSUE TITLE
Documentation mismatch for V1Taint

### ISSUE THREAD

**Issue by stanchanpsu** [kubernetes-client/python#481]
In this documentation: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Taint.md

`value` is both described as `Required.` and is noted as `[optional]`

**Comment by roycaihw** [comment]
The documentation is generated from kubernetes openapi spec, which is generated based on the Go type in main k8s repo: https://github.com/kubernetes/kubernetes/blob/863d1f5f7286e6930423a4038e9adca4233578f8/staging/src/k8s.io/api/core/v1/types.go#L2715-L2717

A `Taint` with empty `value` doesn't make a lot of sense to me (maybe used for matching `Toleration` with `Exists` operation only?) https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/ And it also breaks our [api convention](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#optional-vs-required), as string does not have `nil` value.

PR/issue is welcome in main k8s repo.
