### ISSUE TITLE
v1beta1/create_namespaced_deployment_rollback

### ISSUE THREAD

**Issue by aogier** [kubernetes-client/python#491]
Hello, I'm getting some issues trying to rolling back a deployment because api-client response. 

If I try to run an the [examples' deployment script](https://gist.github.com/aogier/4ddf93864582f6e9abc32a0aad186ee2) I'm getting this error during rollback:

```
Traceback (most recent call last):
  File "examples/notebooks/create_deployment.py", line 140, in <module>
    extension.create_namespaced_deployment_rollback(name="nginx-deployment", namespace="default", body=rollback)
  File "/home/oggei/dev/k8s-py/kubernetes/client/apis/extensions_v1beta1_api.py", line 273, in create_namespaced_deployment_rollback
    (data) = self.create_namespaced_deployment_rollback_with_http_info(name, namespace, body, **kwargs)
  File "/home/oggei/dev/k8s-py/kubernetes/client/apis/extensions_v1beta1_api.py", line 364, in create_namespaced_deployment_rollback_with_http_info
    collection_formats=collection_formats)
  File "/home/oggei/dev/k8s-py/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/home/oggei/dev/k8s-py/kubernetes/client/api_client.py", line 163, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/oggei/dev/k8s-py/kubernetes/client/api_client.py", line 236, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/oggei/dev/k8s-py/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/oggei/dev/k8s-py/kubernetes/client/api_client.py", line 622, in __deserialize_model
    instance = klass(**kwargs)
  File "/home/oggei/dev/k8s-py/kubernetes/client/models/extensions_v1beta1_deployment_rollback.py", line 65, in __init__
    self.name = name
  File "/home/oggei/dev/k8s-py/kubernetes/client/models/extensions_v1beta1_deployment_rollback.py", line 137, in name
    raise ValueError("Invalid value for `name`, must not be `None`")
ValueError: Invalid value for `name`, must not be `None`
```

Tracing api calls, this is what is posted during rollback:
```json
{
    "apiVersion": "extensions/v1beta1",
    "kind": "DeploymentRollback",
    "name": "nginx-deployment",
    "rollbackTo": {
        "revision": 0
    }
}
```
Response, a positive `201 Created`, is:
```json
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Success",
    "message": "rollback request for deployment \"nginx-deployment\" succeeded",
    "code": 200
}
```

I don't think this could be related to `rollbackTo` [deprecation in v1beta1](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rollback-to), cause if I rollback via `kubectl rollout undo` as [documented here](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-to-a-previous-revision) I still get a similar chat (altough no `revision` in $.rollbackTo).

```json
{
    "kind": "DeploymentRollback",
    "apiVersion": "extensions/v1beta1",
    "name": "nginx-deployment",
    "rollbackTo": {}
}
```

```json
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Success",
    "message": "rollback request for deployment \"nginx-deployment\" succeeded",
    "code": 200
}
```

I think the culprit is on swagger machinery but I don't know if it could be safe to work on this, or what else.

Any ideas ? Thank you, ciao !

**Comment by tomplus** [comment]
Duplicated https://github.com/kubernetes-client/python/issues/376

**Comment by aogier** [comment]
Hi @tomplus, in this case we have `name` that isn't a list, so maybe the problem originate somewhere else. BTW suggested monkey patch will not work

**Comment by tomplus** [comment]
Sorry, you are right. I've deleted my previous comment to remove the link from the attached issue.

 It looks like bug in official API specification. Take a look - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#rollback `RollbackConfig` should be returned but you get `Status`. 

IMO you can create an issue here: https://github.com/kubernetes/kubernetes/

**Comment by aogier** [comment]
Hi, thank you for that great pointer I didn't noticed before !  
I'll definitely produce a better trace of what's going on and then submit a k8s issue. For now I'll also leave this one open.

Thank you, regards !

**Comment by roycaihw** [comment]
k8s PR tracked here: https://github.com/kubernetes/kubernetes/pull/56591. Closing

**Comment by zq-david-wang** [comment]
The fix does not seem shipped into pip package, I have to use _preload_content=False to prevent client from parsing the response.
`create_namespaced_deployment_rollback(name, namespace, body=body, _preload_content=False)`

**Comment by nmohoric** [comment]
Yeah I'm still running into this as well, thanks for the tip to at least get around it for now @zq-david-wang

**Comment by roycaihw** [comment]
The k8s openapi fix was merged after 1.11 and didn't get cherrypicked. Currently the latest python client (v7) is generated from k8s 1.11, so it still doesn't include the fix. We will release v8 after k8s 1.12 is released, and the client will include the fix.

**Comment by roycaihw** [comment]
Actually I realized that the previous fix was wrong https://github.com/kubernetes/kubernetes/pull/63837#issuecomment-422997776. I had another fix https://github.com/kubernetes/kubernetes/pull/68864 and plan to cherrypick it to 1.12.1 (talked with 1.12 patch release manager-- 1.12.1 release will be roughly two weeks after 1.12.0 being cut). 

@yliaog I plan to do an alpha release align with 1.12.0 and a beta release align with 1.12.1, assuming that we don't have more API change after beta release. WDYT?

**Comment by yliaog** [comment]
that sounds good to me.

**Comment by Lawouach** [comment]
Hello,

I'm running into this issue as well with:

Python kubernetes==9.0.0
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

Was there a fix for this one?

Cheers,

**Comment by Lawouach** [comment]
Oh, that was my bad. I was misusing the API! :(
