### ISSUE TITLE
OIDC auth refresh flow differs from kubectl behavior

### ISSUE THREAD

**Issue by nurus** [kubernetes-client/python#493]
I've been testing OIDC for authentication using the work done in https://github.com/kubernetes-client/python-base/pull/48 and came across an issue refreshing credentials because I do not specify `idp-certificate-authority-data` in my kubeconfig. This issue has already been brought up: https://github.com/kubernetes-client/python/issues/368#issuecomment-337778192. As `kubectl` does not require this key I don't think the python client should either.

Another potential issue is the lack of support for the `idp-certificate-authority` key which allows you to load CA certificates from a file. I was attempting to use this to get around the issue mentioned above by loading a trusted root CA bundle. I could convert the entire file to base64 and add it as a value for `idp-certificate-authority-data` but this results in an unwieldy kubeconfig file.

**Comment by mvle** [comment]
I also ran into this problem when my kubeconfig does not have `idp-certificate-authority-data` field. This is not needed for `kubectl` and I don't think it should be forced on users w/o this requirement. It can be unsafe. 
I created patch to skip over the certificate check when `idp-certificate-authority-data` is not specified.

Ping @yliaog

**Comment by yliaog** [comment]
i think the patch looks good. idp-certificate-authority-data does not need to be required. could you send a PR?

**Comment by mvle** [comment]
ping @yliaog. PR is there, any reason for the hold up?

**Comment by yliaog** [comment]
sorry for late response, i did not get notification about it until you pinged explicitly. the PR looks good.
