### ISSUE TITLE
The default usage of client with multi-contexts if not thread-safe

### ISSUE THREAD

**Issue by piglei** [kubernetes-client/python#496]
Currently, If kubeconfig file has multiple contexts defined, we will be able to choose from those context. but if several threads are using different contexts, There will be a race condition because all threads are sharing one single `client.configuration` object.

```python
client.load_kube_config(context="default')    # thread1
client.load_kube_config(context="context2') # thread2
client.load_kube_config(context="context3') # thread3
```

In above code, some threads might calling API using the wrong context.

So, should we use thread.local instead of the global variable `configuration` to avoid this race condition?

**Comment by vasilgramov** [comment]
+1

**Comment by vasilgramov** [comment]
There is a method from `kubernetes.config.new_client_from_config`
