### ISSUE TITLE
trying to understand the Watch behavior

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-client/python#502]
I am struggling with the behavior of Watch. If we use a watch for CRD It seems that setting the resource_version is not honored and the stream starts back at the beginning. So I tried to go back to the base Watch() method and list namespaces with the following snippet.

```
while True:

    print "initializing stream"
    stream = watch.Watch().stream(v1.list_namespace,resource_version=resource_version)
 
    for event in stream:
        t = event["type"]
        obj = event["object"]
    
        print t
        print obj  

        # Configure where to resume streaming.
        metadata = obj.metadata

        if metadata.resource_version is not None:
            resource_version = metadata.resource_version
            print resource_version
```

The result is as expected. but I put a timeout in the Stream method, then I start receiving a lot of events of type ERROR with Object of kind Status.

Why do I see ERROR events ?

**Comment by sebgoa** [comment]
the reason I started playing with a timeout was to stop the stream intentionally and check that the new stream would start back at the correct resource version.

**Comment by sebgoa** [comment]
Looks like when you define a timeout in the `stream()` function then you start getting ERROR WatchEvent objects due to:

```
{'raw_object': {u'status': u'Failure', u'kind': u'Status', u'code': 410, u'apiVersion': u'v1', u'reason': u'Gone', u'message': u'too old resource version: 2428 (88826)', u'metadata': {}}, u'object': {'api_version': 'v1',
 'kind': 'Status',
```

The resource version is too old.

**Comment by sebgoa** [comment]
ok got it. So the `list` method returns a `NamespaceList` which has a resource version, so you need to get that resourceVersion and resume there.

```
from kubernetes import client, config, watch

config.load_kube_config()

crds = client.CustomObjectsApi()
v1 = client.CoreV1Api()
        
resource_version = ""

while True:

    stream = watch.Watch().stream(v1.list_namespace,resource_version=resource_version, timeout_seconds=5)
    resource_version = v1.list_namespace().metadata.resource_version
    
    for event in stream:
        t = event["type"]
        obj = event["object"]
```

the timeout forces the stream to close which triggers a reconnect at the correct resource version and you don't start from the beginning of times.

**Comment by KeithTt** [comment]
The doc of the `watch` method in the source code have explained this, but I wonder why it should stop when it is too old?

Can not it block to run without stop? If the program stop, it need to deal with it manually? It is a little strange...
