### ISSUE TITLE
Authentication fails to GCP: The OAuth client was not found

### ISSUE THREAD

**Issue by Satak** [kubernetes-client/python#506]
How the authentication should work against GCP Kubernetes (GKE)? There is no proper documentation and authentication is not mentioned nearly anywhere. For example how to handle multiple GCP projects and clusters? How to authenticate automatically to GKE?

I have installed latest Kubernetes Python client and GCP SDK. Without first running the `kubectl get pods` command authentication doesn't work with this client.

`config.load_kube_config()` command gives error:

`google.auth.exceptions.RefreshError: ('invalid_client: The OAuth client was not found.', '{\n  "error" : "invalid_client",\n  "error_description" : "The OAuth client was not found."\n}')`

**Comment by charly37** [comment]
https://github.com/kubernetes-client/python/pull/446

**Comment by charly37** [comment]
also this "config.load_kube_config()" will only works if you run your python script on a node where kube client is installed (if you can do a kubectl get pod and it works).
