### ISSUE TITLE
Exception RuntimeError: RuntimeError('cannot join current thread',) in ..... ignored

### ISSUE THREAD

**Issue by git-shine** [kubernetes-client/python#512]
===== ERROR：
Exception RuntimeError: RuntimeError('cannot join current thread',) in <bound method ApiClient.__del__ of <kubernetes.client.api_client.ApiClient object at 0x39cf8d0>> ignored

=================script=====================
#!/usr/bin/python
#coding=utf-8
from kubernetes import client, config
import urllib3
from pprint import pprint
#disable warnings
urllib3.disable_warnings()

def kube_get_dep_list():
    configuration = client.Configuration()
    configuration.host = "https://192.168.0.33:6443"
    configuration.verify_ssl = False
    client.Configuration.set_default(configuration)
    print("Listing deployment:")
    k8s_beta = client.ExtensionsV1beta1Api()
    resp = k8s_beta.list_deployment_for_all_namespaces(async=True)
    pprint(resp.get())

kube_get_dep_list()

**Comment by git-shine** [comment]
help........how to deal with？

**Comment by tomplus** [comment]
Do you need use async version of calls ? I guess that theres is a problem iwith not closing threadpool, https://github.com/kubernetes-client/python/issues/411

**Comment by git-shine** [comment]
thx, it work well now without async=True ~
