### ISSUE TITLE
Port exec-based client auth provider to Python client

### ISSUE THREAD

**Issue by dbenhur** [kubernetes-client/python#514]
With 1.10, this exec-based client auth credential provider alpha feature was introduced  [kubernetes/features#541](https://github.com/kubernetes/features/issues/541) for client-go.  Exec-based auth plugin should be supported by this Python client in addition to client-go. Umbrella issue: [kubernetes#62185](https://github.com/kubernetes/kubernetes/issues/62185)

/kind feature
/sig api-machinery

**Comment by roycaihw** [comment]
Link to the credential plugin feature: https://kubernetes.io/docs/admin/authentication#client-go-credential-plugins
Design proposal: https://github.com/ericchiang/community/blob/2bfa7e1e624a5c87cbd1d07566e617563e2280fd/contributors/design-proposals/auth/kubectl-exec-plugins.md

The feature is in alpha state which means the API may change and support may be dropped in future. Python client auth is happening in kubeconfig loader class in python base repo: https://github.com/kubernetes-client/python-base/tree/master/config. 

cc @Lawouach

**Comment by jasonkriss** [comment]
With AWS EKS going GA, this seems to be a pretty important feature. @dbenhur any chance you guys are already working on this? It's currently blocking us from moving to EKS.

**Comment by palnabarun** [comment]
Hi, Can the client communicate with EKS clusters at this point of time?

**Comment by naumvd95** [comment]
Subscribe and hope , that this feature will be implemented asap) ill try to investigate it by myself and do my best in help-offer

**Comment by fillbit** [comment]
Hi,

I am looking for this feature as well. Is anyone working on it? I'm willing to do work on it if not.

Phil

**Comment by dovreshef** [comment]
Hi

I've implemented it here: https://github.com/kubernetes-client/python-base/pull/75.

**Comment by willthames** [comment]
A release that includes https://github.com/kubernetes-client/python/pull/619 should fix this

**Comment by jw-maynard** [comment]
Any plans for a release that includes this fix?

**Comment by roycaihw** [comment]
@jw-maynard We usually align the python client release with main kubernetes release. The python client v8 release procedure will start after kubernetes 1.12.0 is cut.

**Comment by jw-maynard** [comment]
@roycaihw Cool, this is currently a blocker to getting our tooling working with EKS.  I was hoping to you guys could do something like a 7.0.1 release that adds this feature since it's v1beta1 in 1.11. If not, do you know the rough time frame for 1.12 and then getting a release of the client from that? Thanks!

**Comment by alexandraj777** [comment]
@roycaihw I'd be interested in learning how I can get notified about releases of this client! 

@jw-maynard I don't know if this is helpful, but we've written a python package that uses EKS, and our current solution is to have a wrapper class that calls `kubectl` from subprocess. Every subprocess call looks something like:
```python
subprocess.Popen(
  pargs=['kubectl', ...],
  env=dict(KUBECONFIG=<config_file_path>, PATH=<path_to_kubectl>),
  ...
)
```
It's not the prettiest, but it works for now. We're planning to swap out the subprocess code for the python client once EKS is supported 😄

**Comment by roycaihw** [comment]
@jw-maynard Currently the planned date for 1.12.0 cut is [Sep. 27th](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.12). Ideally I'd like to do an 8.0.0a1 release on Sep. 28th.

@alexandraj777 We send announcements about python client releases to kubernetes-dev mailing list. You could join the google group via https://groups.google.com/forum/#!forum/kubernetes-dev

**Comment by jw-maynard** [comment]
@roycaihw Awesome! I think we can just wait for that.

@alexandraj777 Thanks! Trying to avoid wrapping kubectl if we can but if push comes to shove this will definitely help.

**Comment by jw-maynard** [comment]
@roycaihw Hey, just wondering if you guys were hoping to get an 8.0.0a1 build out sometime this week? Thanks!

**Comment by roycaihw** [comment]
Hi folks, the 8.0.0a1 release has been uploaded to pypi https://pypi.org/project/kubernetes/8.0.0a1/. I will create a github release page and send a notification to kubernetes-dev mailing list shortly. Thanks for your patience, and please give it a try and file any issue to let us know :)

**Comment by Lawouach** [comment]
You folks rock!

**Comment by nakulpathak3** [comment]
Hi I'm using the 8.0.0a1 issue and I'm doing 
```
api_client = config.new_client_from_config(kube_config_yaml_file)
v1_core = client.CoreV1Api(api_client)
```
and this seems to pass almost always but every now and then I get an Exception from the python client 
```
ERROR:root:exec: process returned 1. could not get token: AccessDenied: Access denied
	status code: 403, request id: 296d0777-de24-12b8-b352-c942b2ac475e
```
which seems to be getting triggered here in the [exec_provider](https://github.com/kubernetes-client/python-base/blob/master/config/exec_provider.py#L77) in python-base. 

I'm using EKS with `aws-iam-authenticator` on my machine.
