### ISSUE TITLE
Error while running exec command from pod

### ISSUE THREAD

**Issue by paNjii** [kubernetes-client/python#516]
Hi all,

I am trying to execute a command in a pod, using the k8s API from another pod.
I am using the following snippet for this
```
response = stream(self.core_v1.connect_post_namespaced_pod_exec(cilium_pod_name,
                                                                container="test",
                                                                namespace="kube-system",
                                                                command=exec_command,
                                                                stderr=True, stdin=False,
                                                                stdout=True, tty=False,
                                                                _preload_content=True
                                                                ))
``` 
I use the post variant, but I experience the issue with get as well.
I load my kube config using `config.load_incluster_config()` and use the following as client `client.CoreV1Api()` with these as imports
```
from kubernetes.stream import stream
from kubernetes import config, client
```

I use the following requirements.txt 
```
kubernetes==6.0.0
certifi>=14.05.14 # MPL
six>=1.9.0  # MIT
python-dateutil>=2.5.3  # BSD
setuptools>=21.0.0  # PSF/ZPL
urllib3>=1.19.1,!=1.21  # MIT
pyyaml>=3.12  # MIT
google-auth>=1.0.1  # Apache-2.0
ipaddress>=1.0.17;python_version=="2.7" # PSF
websocket-client>=0.32.0,!=0.40.0,!=0.41.*,!=0.42.* # LGPLv2+
requests # Apache-2.0
requests-oauthlib # ISC
```

I run into the following issue, which I have seen reported in different issues but I have not been able to get a working solution from them.
```
 Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Tue, 17 Apr 2018 16:46:41 GMT', 'Content-Length': '139'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400} 
```

For some additional context, I am using minikube `v0.26.0` in combination with kubernetes `1.10`
Anyone have any ideas on how to fix this?

**Comment by acoccimiglio** [comment]
I'm experiencing a similar issue. Same error message, but with `connect_get_namespaced_pod_portforward_with_http_info`.

**Comment by mpw07458** [comment]
Have similar issue similar error

Python : get error "Upgrade request required" for exec command using exec with connect_get_namespaced_pod_exec

when I create the pod with python api I can use kubectl and run the following commands successfully at linux command line:

kubectl exec secret-pod --namespace=production cat data/busybox/username
and
kubectl exec secret-pod --namespace=production cat data/busybox/password

The following python code fails with "Upgrade request required"

def _get_user_token(self):
try:
user = self.core_api_instance.connect_get_namespaced_pod_exec(name="secret-pod",
namespace="production",
command=["cat /data/busybox/username"],
stderr=True, stdin=False,
stdout=True, tty=False)
pprint(user)
except ApiException as e:
print("Exception when calling CoreV1Api->get_namespaced_pod_exec: %s\n" % e)

    exec_cmd = ['cat /data/busybox/password']
    try:
        passwd = self.core_api_instance.connect_get_namespaced_pod_exec(name="secret-pod",
                                                                        namespace='production',
                                                                        command=["cat /data/busybox/password"],
                                                                        stderr=True, stdin=False,
                                                                        stdout=True, tty=False)
        pprint(passwd)
    except ApiException as e:
        print("Exception when calling CoreV1Api->get_namespaced_pod_exec: %s\n" % e)

    return {'user': user, 'password': passwd}

**Comment by mpw07458** [comment]
I upgraded kubernetes python package from 4.0.0 to 6.0.0 and websocket-client to 0.47.0 and it did not fix this

**Comment by mpw07458** [comment]
I also used stream(elf.core_api_instance.connect_get_namespaced_pod_exec(name="secret-pod",
                                                                    namespace='production',
                                                                    command=["cat /data/busybox/password"],
                                                                    stderr=True, stdin=False,
                                                                    stdout=True, tty=False)))
This did not resolve the issue

**Comment by NickScottKortical** [comment]
I'm seeing the same issue, has anyone been able to find a workaround?

**Comment by akaihola** [comment]
I have this in a script and it seems to work:
```python
resp = stream(core_v1.connect_get_namespaced_pod_exec,
              name, namespace,
              command=['kill', '1'],
              stderr=True, stdin=False, stdout=True, tty=False)
assert resp == ''
```

This is with Minikube 0.30.0 and kubectl 1.10.8.
