### ISSUE TITLE
PatchCustomResourceObject - Support JSON Patch

### ISSUE THREAD

**Issue by davissp14** [kubernetes-client/python#517]
**Problem**
`PatchCustomResourceObject` only supports the `application/merge-patch+json` request header.
 
https://github.com/kubernetes-client/python/blob/369366a813964e3d72e91d402c5f471275e7a3e5/kubernetes/client/apis/custom_objects_api.py#L1160-L1162

Is there any reason why the other request headers are not supported for this endpoint?  

We have a solid need for `application/json-patch+json`.

**Comment by davidxia** [comment]
@ellieayla thanks for that solution. Bumping this in case anyone knows why the library doesn't support json patches or if there's any plans to do so or appetite for a PR to add it?
