### ISSUE TITLE
403 forbidden when  i ran in_cluster_config.py in the pod

### ISSUE THREAD

**Issue by wangshuaizs** [kubernetes-client/python#519]
Hi,

 I want to run examples/ folder in a pod, but error message said 

> root@gpu-pod:/data# python in_cluster_config.py
Listing pods with their IPs:
Traceback (most recent call last):
  File "in_cluster_config.py", line 32, in <module>
    main()
  File "in_cluster_config.py", line 25, in main
    ret = v1.list_pod_for_all_namespaces(watch=False)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/core_v1_api.py", line 13589, in list_pod_for_all_namespaces
    (data) = self.list_pod_for_all_namespaces_with_http_info(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/core_v1_api.py", line 13686, in list_pod_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 23 Apr 2018 10:48:16 GMT', 'Content-Length': '243', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:citicai:default\" cannot list pods at the cluster scope","reason":"Forbidden","details":{"kind":"pods"},"code":403}

I think this was maybe caused by service accounts. I used default service account for this pod. How can I generate a service account that can be used for the in_cluster_config.py file? Or are there another way to run this file in a pod?
tks!

**Comment by tomplus** [comment]
@wangshuaizs likely RBAC is not configured for your service account. As I can see you want to use `v1.list_pod_for_all_namespaces` so you need to create objects: ClusterRole, ClusterRoleBinding. More information: https://kubernetes.io/docs/admin/authorization/rbac/

**Comment by wangshuaizs** [comment]
@tomplus Thank you! It has been solved!

**Comment by 1032231418** [comment]
@wangshuaizs  I have the same problem as you. I'll ask you how to solve it.

**Comment by wangshuaizs** [comment]
@1032231418 

As tomplus said, RBAC is not configured for the current service account. A service account with higher privilege should be used for ```v1.list_pod_for_all_namespaces```. And here is my blog for solving this problem: https://blog.csdn.net/u013431916/article/details/80057369

**Comment by 1032231418** [comment]
@wangshuaizs  Thank you, but you can't create namespace now, through the interface.

**Comment by 1032231418** [comment]
@wangshuaizs Pods-list is OK.

**Comment by 1032231418** [comment]
@wangshuaizs  The following configuration is OK.



kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io

**Comment by jabir366** [comment]
I also have the same issue
I am getting the following error when i run the program
https://github.com/kubernetes-client/python/blob/master/examples/remote_cluster.py with the token of an admin-user serviceAccount

` Listing pods with their IPs:
/home/jabir/.local/lib/python2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "prog1.py", line 38, in <module>
    main()
  File "prog1.py", line 31, in main
    ret = v1.list_pod_for_all_namespaces(watch=False)
  File "/home/jabir/.local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13812, in list_pod_for_all_namespaces
    (data) = self.list_pod_for_all_namespaces_with_http_info(**kwargs)
  File "/home/jabir/.local/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13909, in list_pod_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/home/jabir/.local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/home/jabir/.local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/home/jabir/.local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/home/jabir/.local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/home/jabir/.local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Fri, 16 Nov 2018 12:00:58 GMT', 'Content-Length': '290', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"v1 \"pods\" is forbidden: User \"system:serviceaccount:default:default\" cannot get resource \"v1\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"name":"pods","kind":"v1"},"code":403}
`
when i curl into my apiserver i am getting a success

` curl https://192.168.3.143:6443/api --header "Authorization: Bearer $TOKEN" --insecure 
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "192.168.3.143:6443"
    }
  ]
} `

i already have a serviceaccount which is in kube-system namespace with the following defenition

` apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace:   kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system

`

i just tried to change the namespace into 'default' and did `kubectl apply -f `
and tried to run my program again .but it didnt work
do we have any provisoion to specify the namespace from our pyhton program

**Comment by prashanth-vadde** [comment]
We are trying to deploy Jupyterhub Application on Fabric environment. Fabric is based on the Red Hat OpenShift product.However, Fabric has multiple layers of security features are implemented as per our Client standards. We are also facing the similar problem where the Service account default is not able to launch our Jupyter notebook successfully. 

We have understood ClusterRoleBinding and ClusterRole are needed for service account like default. But, here in our Fabric UAT region,we have controlled environment due to security limitations. 

--> Jupyterhub-kubespawner is internally directing to kubernetes. So, this error is coming. 

We were asked to come up with a solution at our Jupyterhub Application level itself without compromising client security standards. Our application is listing all the pods and our service account "default" does not have the necessary RBAC. 

We would like to know the answers for these questions below. 

1.What else this Jupyterhub applications does  apart from listing pods? If so, please provide the list as well. 

2. Is there any other way to deploy Jupyterhub application (without kubernetes or kubespawner)?

Please suggest us, how to proceed in this situation.

**Comment by fsalazarh** [comment]
This works to grant access to default ServiceAccount to list pods:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pods-list
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list","create","delete"]
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: couchdb
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
```
