### ISSUE TITLE
Support for client-go credential plugins authentification scheme?

### ISSUE THREAD

**Issue by Lawouach** [kubernetes-client/python#522]
Hey all,

Kubernetes 1.10 has introduced an alpha feature to support a greater variety of authentification mechanisms https://kubernetes.io/docs/admin/authentication/#client-go-credential-plugins

Is there planning to support this from the Python client by any chance?

Thanks,

PS: Duplicate from https://github.com/kubernetes-client/python-base/issues/63 as it was not clear where to create issues for this project. Feel free to close the inappropriate one.

**Comment by roycaihw** [comment]
dup of https://github.com/kubernetes-client/python/issues/514
