### ISSUE TITLE
OIDC + Python3 + Incorrect padding during base64decode

### ISSUE THREAD

**Issue by nabadger** [kubernetes-client/python#525]
Using 3.6.5

```
  File "/usr/lib/python3.6/site-packages/kubernetes-6.0.0_snapshot-py3.6.egg/kubernetes/config/kube_config.py", line 474, in load_kube_config
  File "/usr/lib/python3.6/site-packages/kubernetes-6.0.0_snapshot-py3.6.egg/kubernetes/config/kube_config.py", line 355, in load_and_set
  File "/usr/lib/python3.6/site-packages/kubernetes-6.0.0_snapshot-py3.6.egg/kubernetes/config/kube_config.py", line 185, in _load_authentication
  File "/usr/lib/python3.6/site-packages/kubernetes-6.0.0_snapshot-py3.6.egg/kubernetes/config/kube_config.py", line 237, in _load_oid_token
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

When attempting to decode the token, I run into this issue in `_load_oid_token` 

```python
  if PY3:
    jwt_attributes = json.loads(
      base64.b64decode(parts[1]).decode('utf-8')
    )

```

The non py3 block appends "=="  to the token part before decoding it. If i use that, it works fine.

**Comment by richerve** [comment]
Same on 3.5.5 and 3.6.6.

This is the reference to the PR to fix this: https://github.com/kubernetes-client/python-base/pull/70

**Comment by markuszoeller** [comment]
Same on Python 3.4

**Comment by zybjcdl** [comment]
@bpicolo Could you please help to fix the issue? We need to run python 3.6.5 with this client.

**Comment by cparedes** [comment]
Ran into the same issue with Python 3.7 with the latest version of this client (8.0.0 at this time of writing)

**Comment by rocktavious** [comment]
Same on python 3.7.2 + kubernetes 9.0.0

**Comment by joshbranham** [comment]
Anyone know why no fix for this has been merged?

**Comment by nabadger** [comment]
@yliaog - would you (or any owner) be able to provide a comment on this? Just wondering what your thoughts are on this issue as it's been around for a while and probably affecting quite a large user base.

**Comment by yliaog** [comment]
it looks @micw523 is reviewing the fix PR kubernetes-client/python-base#70, @micw523 do you have any further comment on the PR?

**Comment by micw523** [comment]
Hi @yliaog, kubernetes-client/python#70 seems to have been abandoned and the fork does not exist any more. kubernetes-client/python#79 is active and seems like the author just pushed some new commits.

However, due to the new version of minikube, we need to have #797 merged first to unblock the PRs. We can’t have the CI to pass unless we get that one through.

**Comment by switchboardOp** [comment]
https://github.com/kubernetes-client/python/pull/797 has merged and it looks like kubernetes-client/python-base#79 passed CI...

**Comment by TechnoTaff** [comment]
Can I bump this? My existing code is Python 3.6 and I can't port it back to 2.x due to other libraries. The PR works for me, can we get it pushed into PyPi plz? Thank you.

**Comment by AlexShemeshWix** [comment]
Any updates?

**Comment by r0fls** [comment]
Is there a workaround? :thinking:

**Comment by r0fls** [comment]
Is there any workaround? :thinking:

**Comment by roycaihw** [comment]
fixed in https://github.com/kubernetes-client/python-base/pull/79
