### ISSUE TITLE
How to get pod monitoring information from SDK?

### ISSUE THREAD

**Issue by yokiy0828** [kubernetes-client/python#528]
How to get pod monitoring information from SDK?

**Comment by tomplus** [comment]
What kind of information do you need?

**Comment by yokiy0828** [comment]
Pod's CPU, memory, hard disk usage and more.

**Comment by tomplus** [comment]
There are not such things in standard API. Please take a look at projects: [heapster](https://github.com/kubernetes/heapster) (deprecated),  [metric-server](https://github.com/kubernetes-incubator/metrics-server), [cAdvisor](https://github.com/google/cadvisor) and [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics).

**Comment by P6rguVyrst** [comment]
Does the Python API support raw queries to the Kubernetes API? If I have the metric-server installed and want to make a raw query to Kubernetes API like: get --raw /apis/metrics.k8s.io/v1beta1/pods/

Issue: metrics-server endpoint #474

**Comment by tomplus** [comment]
@P6rguVyrst yes, it should be possible. Try to use something like this:

```
api_client = ApiClient()
response = api_client.call_api('/apis/metrics.k8s.io/v1beta1/pods/', 'GET', preaload_content=False)
print(response.text)  # raw HTTPResponse
```

https://github.com/kubernetes-client/python/blob/master/kubernetes/client/api_client.py#L278

**Comment by mward29** [comment]
minikube version: v0.28.2

Any chance I'm doing something wrong?

metrics_url = '/apis/metrics.k8s.io/v1beta1/namespaces/kube-system/pods/kube-controller-manager-minikube'
api_client.call_api(metrics_url, 'GET', _preload_content=True)
returns None

when I make the same call via curl, it returns the expected data.
curl --cacert <redacted> --key <redacted> --cert <redacted> https://192.168.99.100:8443/apis/metrics.k8s.io/v1beta1/namespaces/kube-system/pods/kube-controller-manager-minikube

**Comment by mward29** [comment]
FYI,

I found: .request instead of .call_api
api_client.request('GET', metrics_url, headers=None, _preload_content=True)

This Works!

**Comment by Shinzu** [comment]
@mward29 how did you include config parameters here, like the ones from `config.load_incluster_config()` ?

**Comment by mward29** [comment]
yes. config.load_kube_config()

**Comment by Shinzu** [comment]
@mward29 i think go get  .call_api  to work you have to define at least  response_type , but i did not find any suitable type in https://github.com/kubernetes-client/python/tree/master/kubernetes/client/models

**Comment by Shinzu** [comment]
with 
```
ret= api_client.call_api('/apis/metrics.k8s.io/v1beta1/namespaces/default/pods', 'GET', auth_settings = ['BearerToken'], response_type='json', _preload_content=False)
print(ret)
```
i get 
```
(<urllib3.response.HTTPResponse object at 0x7f1166713710>, 200, HTTPHeaderDict({'Content-Length': '446', 'Content-Type': 'application/json', 'Date': 'Fri, 10 Aug 2018 06:39:06 GMT'}))
```

**Comment by Shinzu** [comment]
i do it now this way:

```
ret_metrics = api_client.call_api('/apis/metrics.k8s.io/v1beta1/namespaces/' + namespace.metadata.name + '/pods', 'GET', auth_settings = ['BearerToken'], response_type='json', _preload_content=False) 
response = ret_metrics[0].data.decode('utf-8')
```

**Comment by mward29** [comment]
Nice Shinzu
