### ISSUE TITLE
default behavior of kube_config.load_kube_config() doesn't respect KUBECONFIG env var

### ISSUE THREAD

**Issue by impulsemk** [kubernetes-client/python#533]
For setups where you have multiple kube config files, kubectl respects the KUBECONFIG env variable which allows for appending multiple kube config file locations.

I believe that https://github.com/kubernetes-client/python/blob/ce8e08226d6454e475a59d60d1ea13fed9cf6eea/kubernetes/config/kube_config.py#L292 should look at the environment's KUBECONFIG if it exists and load in all kube configs from there. If it doesn't exist, then use KUBE_CONFIG_DEFAULT_LOCATION.

**Comment by tomplus** [comment]
This feature has to be added to python-base repo, ref issue: https://github.com/kubernetes-client/python-base/issues/62
