### ISSUE TITLE
how to use replace_persistent_volume api

### ISSUE THREAD

**Issue by chenyanter** [kubernetes-client/python#535]
`code:`
`  def replaceVolume(self, old_vol=None):`
`    api_response = None`
`    try:`
`      if old_vol:`
`        if old_vol.spec.nfs and (old_vol.spec.nfs != self.body.spec.nfs):`
`          old_vol.spec.nfs.path = self.body.spec.nfs.path`
`          old_vol.spec.nfs.read_only = self.body.spec.nfs.read_only`
`          old_vol.spec.nfs.server = self.body.spec.nfs.server`
`      api_response = self.core_v1_api_instance.replace_persistent_volume(`
`        old_vol.metadata.name,`
`        old_vol,`
`        pretty=self.pretty)`
`    except ApiException as e:`
`      logger.info("Exception when calling CoreV1Api->replace_persistent_volume: %s\n" % e)`

old pvc
---------------------------------------------------------------------------------------------------
{'api_version': 'v1',
 'kind': 'PersistentVolume',
 'metadata': {'annotations': {'pv.kubernetes.io/bound-by-controller': 'yes',
                              'volume.beta.kubernetes.io/mount-options': 'nfsvers=4'},
              'cluster_name': None,
              'creation_timestamp': None,
              'deletion_grace_period_seconds': 0,
              'deletion_timestamp': None,
              'finalizers': ['kubernetes.io/pv-protection',
                             'foregroundDeletion'],
              'generate_name': None,
              'generation': None,
              'initializers': None,
              'labels': {'name': 'name-app-nfs-pv',
                         'volume': 'name-app-nfs-pv'},
              'name': 'name-app-nfs-pv',
              'namespace': None,
              'owner_references': None,
              'resource_version': None,
              'self_link': '/api/v1/persistentvolumes/name-app-nfs-pv',
              'uid': None},
 'spec': {'access_modes': ['ReadWriteMany'],
          'aws_elastic_block_store': None,
          'azure_disk': None,
          'azure_file': None,
          'capacity': {'storage': '800Gi'},
          'cephfs': None,
          'cinder': None,
          'claim_ref': {'api_version': 'v1',
                        'field_path': None,
                        'kind': 'PersistentVolumeClaim',
                        'name': 'name-app-nfs-pvc',
                        'namespace': 'mynp',
                        'resource_version': '2857986',
                        'uid': 'ed3ba98c-4a2b-11e8-9e13-00163e02b3ab'},
          'fc': None,
          'flex_volume': None,
          'flocker': None,
          'gce_persistent_disk': None,
          'glusterfs': None,
          'host_path': None,
          'iscsi': None,
          'local': None,
          'nfs': {'path': '/hdd01/contentdatafile',
                  'read_only': None,
                  'server': '192.168.10.10'},
          'persistent_volume_reclaim_policy': 'Retain',
          'photon_persistent_disk': None,
          'portworx_volume': None,
          'quobyte': None,
          'rbd': None,
          'scale_io': None,
          'storage_class_name': 'slow',
          'storageos': None,
          'vsphere_volume': None},
 'status': {'message': None, 'phase': None, 'reason': None}}
---------------------------------------------------------------------------------------------------
new_pvc
---------------------------------------------------------------------------------------------------
{'api_version': 'v1',
 'kind': 'PersistentVolume',
 'metadata': {'annotations': {'pv.kubernetes.io/bound-by-controller': 'yes',
                              'volume.beta.kubernetes.io/mount-options': 'nfsvers=4'},
              'cluster_name': None,
              'creation_timestamp': None,
              'deletion_grace_period_seconds': 0,
              'deletion_timestamp': None,
              'finalizers': ['kubernetes.io/pv-protection',
                             'foregroundDeletion'],
              'generate_name': None,
              'generation': None,
              'initializers': None,
              'labels': {'name': 'name-app-nfs-pv',
                         'volume': 'name-app-nfs-pv'},
              'name': 'name-app-nfs-pv',
              'namespace': None,
              'owner_references': None,
              'resource_version': None,
              'self_link': '/api/v1/persistentvolumes/name-app-nfs-pv',
              'uid': None},
 'spec': {'access_modes': ['ReadWriteMany'],
          'aws_elastic_block_store': None,
          'azure_disk': None,
          'azure_file': None,
          'capacity': {'storage': '600Gi'},
          'cephfs': None,
          'cinder': None,
          'claim_ref': {'api_version': 'v1',
                        'field_path': None,
                        'kind': 'PersistentVolumeClaim',
                        'name': 'name-app-nfs-pvc',
                        'namespace': 'mynp',
                        'resource_version': '2857986',
                        'uid': 'ed3ba98c-4a2b-11e8-9e13-00163e02b3ab'},
          'fc': None,
          'flex_volume': None,
          'flocker': None,
          'gce_persistent_disk': None,
          'glusterfs': None,
          'host_path': None,
          'iscsi': None,
          'local': None,
           'nfs': {'path': '/hdd02/contentdatafile',
                  'read_only': None,
                  'server': '172.168.10.10'},
          'persistent_volume_reclaim_policy': 'Retain',
          'photon_persistent_disk': None,
          'portworx_volume': None,
          'quobyte': None,
          'rbd': None,
          'scale_io': None,
          'storage_class_name': 'slow',
          'storageos': None,
          'vsphere_volume': None},
 'status': {'message': None, 'phase': None, 'reason': None}}
---------------------------------------------------------------------------------------------------
then i get this error

 Tue, 22 May 2018 22:15:48 volume.py[line:71] INFO Exception when calling CoreV1Api->replace_persistent_volume: (422)
 Reason: Unprocessable Entity
 HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Tue, 22 May 2018 14:15:48 GMT', 'Content-Length': '566'})
 HTTP response body: {
   "kind": "Status",
   "apiVersion": "v1",
   "metadata": {
     
   },
   "status": "Failure",
   "message": "PersistentVolume \"name-app-nfs-pv\" is invalid: spec.persistentvolumesource: Forbidden: is immutable after creation",
   "reason": "Invalid",
   "details": {
     "name": "name-app-nfs-pv",
     "kind": "PersistentVolume",
     "causes": [
       {
         "reason": "FieldValueForbidden",
         "message": "Forbidden: is immutable after creation",
         "field": "spec.persistentvolumesource"
       }
     ]
   },
   "code": 422
 }

**Comment by xuyanwei** [comment]
function 'replac_namespaced_pod' had the some problem.

(422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json', 'Date': 'Thu, 24 May 2018 09:14:05 GMT'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":
