### ISSUE TITLE
How to use the Python Kubernetes client in a way resilient to GKE Kubernetes Master disruptions?

### ISSUE THREAD

**Issue by kevincvlam** [kubernetes-client/python#536]
Hi,

We sometimes use Python Scripts to spin up and monitor Kubernetes Pods running on Google Kubernetes Engine using the 'Official Python client library for kubernetes' [1]. We also enable auto-scaling on several of our nodepools. 

According to [2], 'Master VM is automatically scaled, upgraded, backed up and secured'. The post also seems to indicate that some automatic scaling of the control plane/Master VM occurs when the node count increases from 0-5 to 6+ and potentially at other times when more nodes are added.

It seems like the control plane can go down at times like this, when many nodes have been brought up. In and around when this happens, our Python Scripts that monitor pods via the control plane often crash, seemingly unable to find the KubeApi/Control Plane endpoint triggering some of the following exceptions: ApiException, urllib3.exceptions.NewConnectionError, urllib3.exceptions.MaxRetryError. What's the best way to handle this situation? Are there any properties of the autoscaling events that might be helpful?

To clarify what we're doing with the Python client is that we are in a loop reading the status of the pod of interest via read_namespaced_pod ([3]) every few minutes, and catching exceptions similar to the provided example at [3] (in addition we've tried also catching exceptions for the underlying urllib calls). We have also added retrying with exponential back-off but things are unable to recover and fail after a specified max number of retries, even if that number is high (eg. keep retrying for >5 minutes). 

One thing we haven't tried is recreating kubernetes.client.CoreV1Api object on each retry, would that make much of difference? 

[1] https://github.com/kubernetes-client/python

[2] https://cloudplatform.googleblog.com/2017/11/Cutting-Cluster-Management-Fees-on-Google-Kubernetes-Engine.html

[3] https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#read_namespaced_pod

**Comment by pcasteran** [comment]
Hello,

We are experiencing the exact same issue in almost the same context.
We have a Python application using the Kubernetes client to create Job objects and polling for their status every few seconds. The application is sometimes unable to connect to the K8s control plane and the call to `read_namespaced_job_status()` fails with exception `MaxRetryError`.
I checked the last logs and it happened also when the cluster autoscaler added a node to the cluster to a total of 6 nodes.
I don't know if it's useful but the Python application itself runs in the K8s cluster and uses in-cluster config (`config.load_incluster_config()`) to connect to the control plane.

The application logs contains lots of error lines indicating 3 retries per call to `read_namespaced_job_status()` in a time span of about 4-5 ms which is too short for the control plane to be available again. After a little digging, I found that those retries are from the **urllib3** package which is used by the kubernetes client. Unfortunately, the kubernetes client does not currently allow to configure the retrying parameters (delay, exponential backoff, ...). Maybe some corresponding properties could be added to the `kubernetes.client.Configuration` class...

Did you find a way to work around this issue?
