### ISSUE TITLE
Getting API_KEY

### ISSUE THREAD

**Issue by VinayVanama** [kubernetes-client/python#538]
Hi I have installed kubernetes and accessing it through kubectl on my EC2 instances. I'm trying it with Python API now to create a pod, namespace etc., but I wanted to know how to generate or how to get my API_KEY.

**Comment by atotala** [comment]
Hi Team,
I am also stuck here.Please help out.

**Comment by tomplus** [comment]
What kind of API_KEY do you need? This library can read credentials (token, certs, passwords) from kubeconfig like kubectl does. Try to run [examples/example1.py](https://github.com/kubernetes-client/python/blob/master/examples/example1.py) which should works like `kubect get pods --all-namespaces`.
