### ISSUE TITLE
Unused threads and thread pools in kubernetes.watch.Watch._api_client

### ISSUE THREAD

**Issue by bgagnon** [kubernetes-client/python#545]
**TL;DR** every Watch object consumes 16 threads for no apparent reason

`kubernetes.watch.Watch` creates an APIClient in its constructor:

```python
    def __init__(self, return_type=None):
        self._raw_return_type = return_type
        self._stop = False
        self._api_client = client.ApiClient()
        self.resource_version = 0
```

Which is only used for `deserialize` purposes, not for making calls:

```python
            js['object'] = self._api_client.deserialize(obj, return_type)
```

The problem is that `ApiClient` is a rather expensive object that creates a new `ThreadPool` and `RESTClientObject` every time:

```python
    def __init__(self, configuration=None, header_name=None, header_value=None, cookie=None):
        if configuration is None:
            configuration = Configuration()
        self.configuration = configuration

        self.pool = ThreadPool()
        self.rest_client = RESTClientObject(configuration)
```

The `RESTClientObject` is default-constructed (no `configuration`), which implies:

```python
        self.connection_pool_maxsize = multiprocessing.cpu_count() * 5
```

and

```python
class RESTClientObject(object):

    def __init__(self, configuration, pools_size=4, maxsize=None):
```

**Comment by bgagnon** [comment]
Workaround that kills some threads right after the Watch object is constructed:

```python
watch = kubernetes.watch.Watch()
watch._api_client.pool.close()
watch._api_client.rest_client.pool_manager.clear()
```

**Comment by minrk** [comment]
This is a bug in the upstream swagger-codegen project fixed by https://github.com/swagger-api/swagger-codegen/pull/8061 . Once that is merged, re-rendering with the updated swagger-codegen should fix it.

**Comment by bidyut1990** [comment]
Is there any update to this? I am also trying to use many watches simultaneously and its hogging a lot of memory. Any advise to make a client(capable of setting up watches and digesting the events) really scalable in the most efficient manner.

**Comment by tomplus** [comment]
@bidyut1990 which version do you use? It should be fixed in v9.0.0. 

If you need to handle many watches in your application you may be interested asynchronous fork of this library [kubernetes-asyncio](https://github.com/tomplus/kubernetes_asyncio).

**Comment by bidyut1990** [comment]
@tomplus - I am using 9.0.0 only but i did not realize it's been fixed. Anyways, i ll also take a look at the async based package.

**Comment by yliaog** [comment]
@bidyut1990 could you please verify if the fix works?
