### ISSUE TITLE
Unclear parameters for list_namespaced_secret

### ISSUE THREAD

**Issue by max-l-weaver** [kubernetes-client/python#548]
I am currently using the Kubernetes library to push a secret to a namespace, and I want to check if the secret is present before attempting to push.

Looking at the docs, one would assume you'd put a field_selector or label_selector parameter to filter the results by a particular secret name, but nothing I've tried works. The documentation just says you need to provide a string, but does not indicate what the string should refer to.

Can someone explain how the label_selector for example is supposed to work? I would be nice if I had a secret named "foo_secret" and could put in the label_selector "foo_secret" and for it to return only results for that secret.

I've had a look at the Kubernetes REST api docs but they are pretty much exactly the same as the Python client ones.

**Comment by tomplus** [comment]
Hi @max-l-weaver 

Each object in K8s can have a set of labels and you can list objects using the label_selector. It has nothing to do with your secret name (the name is not a label).

In your case it'll be better to use the command `read_namespaced_secret`. It requires name of namespace and name of your secret. It'll raise an exception if the secret doesn't exist or just return the  object.

**Comment by max-l-weaver** [comment]
Thanks @tomplus, this seems like an elegant solution.
