### ISSUE TITLE
Connection Refused when using client behind coporate proxy to connect to AWS Cluster

### ISSUE THREAD

**Issue by jueast08** [kubernetes-client/python#549]
So I've been using the client for about a week, and I have to say I love it and what it can do. However, I've noticed that when using the client at work I receive the following errors despite the fact that all kubectl commands work : 

`2018-06-18 11:20:15,250 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff4dc6f69d0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/status
2018-06-18 11:20:15,254 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff4dc6f6910>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/status
2018-06-18 11:20:15,258 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff4dc6f6a90>: Failed to establish a new connection: [Errno 111] Connection refused',)': /api/v1/namespaces/default/status
HTTPSConnectionPool(host='<ip_address>', port=443): Max retries exceeded with url: /api/v1/namespaces/default/status (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff4dc6f6a10>: Failed to establish a new connection: [Errno 111] Connection refused',))`

I've tried using the default config.load_kube_config() function. I've also tried to set the proxy using : 
`conf = client.Configuration()
 conf.http_proxy_url = <proxy>
config.load_kube_config(client_configuration=conf)
`
The latter command fixes the host as 'localhost' rather than the IP of my AWS cluster

**Comment by tomplus** [comment]
Can you show us your kubeconfig file `~/.kube/config` (with removed certs/passwords/ips if it's neccessary) ? It's interesting that kubectl works and this library try to connect but the connection is refused.

**Comment by jueast08** [comment]
Weirdly enough, I went into the source code of the ApiClient to see if I could kick start the thing and gain more info about what the problem may be. 

I was able to make the client work behind my proxy by doing the following in the __init__ function of the api_client.py module:

`    
def __init__(self, configuration=None, header_name=None, header_value=None, cookie=None):
        if configuration is None:
            configuration = Configuration()
        configuration.proxy = <proxy_url> # <---- I added my proxy url here to see if there would be a change in the result
        self.configuration = configuration
...
`
Setting the proxy via the specified methods or launching my code in an environment with the correctly proxy variables set had no effect, where as this "fixed" the problem immediately

**Comment by jueast08** [comment]
Ok. So I ended up doing the following (this time without editing the sources)

`config.load_kube_config()` 
`conf = client.Configuration()`
`conf.proxy = <my_proxy>` 
`client.Configuration.set_default(conf)`

Not sure if it was indicated in the docs to do a load_kube_config() and use that to solve the proxy issue, but I could not see anything of the kind

**Comment by abushoeb** [comment]
Check this https://github.com/kubernetes-client/python/issues/333#issuecomment-397979195

**Comment by Omegastick** [comment]
> Ok. So I ended up doing the following (this time without editing the sources)
> 
> `config.load_kube_config()`
> `conf = client.Configuration()`
> `conf.proxy = <my_proxy>`
> `client.Configuration.set_default(conf)`
> 
> Not sure if it was indicated in the docs to do a load_kube_config() and use that to solve the proxy issue, but I could not see anything of the kind

This doesn't work for me. Only changing the ApiClient source as described in the previous comment does.
