### ISSUE TITLE
error in kubernetes setup command: 'install_requires' must be a string or list of strings

### ISSUE THREAD

**Issue by alexxa** [kubernetes-client/python#551]
Following installation instructions in Readme:

```
git clone --recursive https://github.com/kubernetes-client/python.git
cd python
python setup.py install
```
returns
```
error in kubernetes setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```

**Comment by tomplus** [comment]
Hi @alexxa, which version of setuptools do you use (`easy_install --version`) ? I use virtualenv with setuptools 39.2.0 and it works without any problems.

**Comment by alexxa** [comment]
@tomplus Hello Tomasz, right, the error appears on CentOS 7.5 which goes with setuptools 0.9.8. I have installed 39.2.0, and it works fine then. Do you think adding "Requirements" note in Readme will be beneficial?

**Comment by abushoeb** [comment]
@alexxa if you still have the issue then simply install it using pip.

`sudo pip install kubernetes`

**Comment by alexxa** [comment]
@abushoeb pip installation works fine. The issue is not about that, but installation from the source. And there is no "Requirements" or "Tested on" notes in Readme, and I ask if it can be useful to add it there.

**Comment by nettyxiong** [comment]
`pip install setuptools --upgrade` can solve this error. It's worth to try

**Comment by EKwongChum** [comment]
```shell
python -m pip install --upgrade pip setuptools wheel
```
This command works for me!

**Comment by edperry** [comment]
I just ran in to this issue too. really annoying that you don't have setuptool > version number not required

```
pip install setuptools --upgrade

```
Fixed my issue on centos7
