### ISSUE TITLE
Error: Initialization of V2beta1HorizontalPodAutoscalerStatus

### ISSUE THREAD

**Issue by keigohtr** [kubernetes-client/python#553]
When we use ```create_namespaced_horizontal_pod_autoscaler``` of ```AutoscalingV2beta1Api```, the response always throws an exception since it doesn't set ```conditions``` in ```V2beta1HorizontalPodAutoscalerStatus``` .

Likewise, the response of ```read_namespaced_horizontal_pod_autoscaler``` throws an exception since it doesn't set ```current_metrics``` .

I will create a PR for this.

### Situaltion
- Kubernetes 1.9 via Rancher 1.6.16
- Python 3.6.3
- python kubernetes 5.0.0

**Comment by ackintosh** [comment]
https://github.com/kubernetes-client/python/pull/554
It might be realized by fixing the API definition:

https://github.com/kubernetes-client/python/blob/71b5abce5a4e2d747c0bb26d4eaa17eeb08f8ac5/scripts/swagger.json#L68656

```json
      "required": [
        "currentReplicas",
        "desiredReplicas",
        "currentMetrics",
        "conditions"
      ],
```

Removing "currentMetrics" and "conditions" in the swagger.json ( or its original data if the json is auto-generated file) will result as same as

**Comment by ackintosh** [comment]
Similar fix: https://github.com/kubernetes/kubernetes/pull/64996/files#diff-9ce7ea8441086bf1902b4f936f4601d0

**Comment by keigohtr** [comment]
Thank you for your information. Yes we can fix this issue by hands.
I am not sure but I think this Kubernetes swagger spec is automatically generated from a code. So I believe we need to fix the original Kubernetes code for this.

**Comment by flmu** [comment]
I am facing the same issue. Are there any plans to permanently fix this problem?

Btw, the same setting can be deployed with kubectl

**Comment by zq-david-wang** [comment]
I have the same issue, and sometimes "list_namespaced_horizontal_pod_autoscaler" would raise ValueError("Invalid value for `conditions`, must not be `None`") when the hpa has not condition set yet.

And I am using 9.0.0

For create_namespaced_horizontal_pod_autoscaler, add '_preload_content=False' can help

**Comment by Anurag2408** [comment]
I am also facing the same issue. When is plan to fix is permanently?

**Comment by nollimahere** [comment]
for those of us trying to communicate with the GKE api (and thus don't have access to the api definition to modify it our own local k8s installations), adding an annotation in the metadata is enough to get past this issue.

resource_hpa['metadata']['annotations'] = { "autoscaling.alpha.kubernetes.io/conditions": "[ {\"type\":\"ScalingLimited\",\"status\":\"True\",\"reason\":\"TooFewReplicas\",\"message\":\"who needs m     essages\"}]" }
