### ISSUE TITLE
V1List was not found in client.models

### ISSUE THREAD

**Issue by tapvirvirk** [kubernetes-client/python#557]
With below manifest, ansible is givig V1list not found error

apiVersion: v1
kind: List
items:
- kind: Namespace
  apiVersion: v1
  metadata:
    name: rule-service

Can you please suggest withi apiversion needs to be used with Kind list?

Thanks
Tapvir

**Comment by tomplus** [comment]
hi @tapvirvirk, could you give us steps to reproduce it ?
