### ISSUE TITLE
Using stream to execute commands is never finish

### ISSUE THREAD

**Issue by ronny35** [kubernetes-client/python#559]
kubectl version
client : v1.11.0
server v1.11.0

result = stream(api.connect_get_namespaced_pod_exec, "pod", "default", command=command, stderr=True, stdout=True, stdin=False, tty=False)

stream function is never finished

**Comment by dkoshkin** [comment]
We had a similar issue when the API server is exposed with a proxy, you can set a timeout `_request_timeout`.

**Comment by shaozi** [comment]
Is there a way to get notification when exec has been done?

**Comment by dlopezrodriguez** [comment]
I did this funtion, is good for many commands like __> command = "apt-get install \n".
I'm trying other way to stop others command types. For now this way is ok for me.

`def executeCommand(self,command):
        print("COMANDO ::: %s"%command)
        print("Executing command...\n")
        exec_command = ['/bin/sh']
        self.resp = stream(self.api.connect_get_namespaced_pod_exec, self.namePod, 'default',
            command=exec_command,
            stderr=True, stdin=True,
            stdout=True, tty=False,
            _preload_content=False)
        count = 0
        count2 = 2
        responseCommandFull=""
        self.resp.write_stdin(command)
        while self.resp.is_open():
                print("WHILEEEE ::: %s"%self.resp.is_open())
                self.resp.update(timeout=1)
                if self.resp.peek_stdout():
                    count = count+1
                    responseCom = self.resp.read_stdout()
                    print("STDIN :: %s"%responseCom)
                    #if len(responseCom)!= 1:
                    responseCommandFull="%s\n%s"%(responseCommandFull,responseCom)
                if self.resp.peek_stderr():
                    count = count+1
                    responseCom = self.resp.read_stderr()
                    print("STDERR :: %s"%responseCom)
                    responseCommandFull="%s\n%s"%(responseCommandFull,responseCom)
                 else:
                    if count2 == count:
                            print("Executing command sucessfully.")
                            break
                    count2 = count
        self.resp.close()
        print responseCommandFull
`

**Comment by dlopezrodriguez** [comment]
I did this funtion, is good for many commands like __> command = "apt-get install \n".
I'm trying other way to stop others command types. For now this way is ok for me.

```
def executeCommand(self,command):
        print("COMANDO ::: %s"%command)
        print("Executing command...\n")
        exec_command = ['/bin/sh']
        self.resp = stream(self.api.connect_get_namespaced_pod_exec, self.namePod, 'default',
            command=exec_command,
            stderr=True, stdin=True,
            stdout=True, tty=False,
            _preload_content=False)
        count = 0
        count2 = 2
        responseCommandFull=""
        self.resp.write_stdin(command)
        while self.resp.is_open():
            print("WHILEEEE ::: %s"%self.resp.is_open())
            self.resp.update(timeout=1)
            if self.resp.peek_stdout():
                count = count+1
                responseCom = self.resp.read_stdout()
                print("STDIN :: %s"%responseCom)
                #if len(responseCom)!= 1:
                responseCommandFull="%s\n%s"%(responseCommandFull,responseCom)
            if self.resp.peek_stderr():
                count = count+1
                responseCom = self.resp.read_stderr()
                print("STDERR :: %s"%responseCom)
                responseCommandFull="%s\n%s"%(responseCommandFull,responseCom)
             else:
                if count2 == count:
                        print("Executing command sucessfully.")
                        break
                count2 = count
        self.resp.close()
        print responseCommandFull
```
