### ISSUE TITLE
how to use patch_node to delete a annotation

### ISSUE THREAD

**Issue by liuzhi1986** [kubernetes-client/python#560]
I can use patch_node to add a annotation, but delete one is not useful.
the code like this:
```pthyon
name = "samenode"
node_o = api_instance_corev1.read_node(name)

annotations_d = node_o.metadata.annotations
annotations_d['test'] = "test-annotation"
api_instance_corev1.patch_node(name, node_o)
```
It add an annotation to the node successful.
```pthyon
name = "samenode"
node_o = api_instance_corev1.read_node(name)

annotations_d = node_o.metadata.annotations
annotations_d.pop['test']
api_instance_corev1.patch_node(name, node_o)
```
When I try to delete the label , it did not  work.

**Comment by tomplus** [comment]
We have an example to update labels which shows how to delete item:

https://github.com/kubernetes-client/python/blob/master/examples/manage_node_labels.py

In your case, k8s uses json-merge-path and if you want to delete item you will need to set this annotation as `None`.

```
annotations_d = node_o.metadata.annotations
annotations_d['test'] = None
api_instance_corev1.patch_node(name, node_o)
```

Or you can use list of operations as json-patch format which will look something like this:

```
   [
     { "op": "remove", "path": "/metadata/annotations/test" }
   ]
```

More information: https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/

**Comment by liuzhi1986** [comment]
@tomplus  Thank you for your help.
