### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by baeriswyld** [kubernetes-client/python#561]
Kubernetes newbie question.

using the create_deployment.py example using my yaml i get this (yaml works with kubectl create -f )

HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod in version \"v1\" cannot be handled as a Deployment: converting (v1.Pod).v1.PodSpec to (extensions.Deployment).extensions.DeploymentSpec: Replicas not present in src","reason":"BadRequest","code":400}

python script:
`from os import path
import pprint

import yaml

from kubernetes import client, config

import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]='key.json'

def main():
    # Configs can be set in Configuration class directly or using helper
    # utility. If no argument provided, the config will be loaded from
    # default location.
    config.load_kube_config()

    with open(path.join(path.dirname(__file__), "trading-bot_4.yaml")) as f:
        dep = yaml.load(f)
        print(dep)
        k8s_beta = client.ExtensionsV1beta1Api()
        resp = k8s_beta.create_namespaced_deployment(
            body=dep, namespace="default")
        print("Deployment created. status='%s'" % str(resp.status))

if __name__ == '__main__':
    main()`

**Comment by roycaihw** [comment]
As the error message suggested, the apiserver received your deployment object but it cannot interpret as an extension/v1beta1 Deployment object. In your case `k8s_beta = client.ExtensionsV1beta1Api()` POSTs the object to `/apis/extensions/v1beta1/namespaces/default/deployments` endpoint. I believe `kubectl create` does extra steps to figure out the `group/version kind` of the object to be created, and sends it to proper endpoint. 

You could check the endpoint that `kubectl` POSTs to by running `kubectl create -f trading-bot_4.yaml --v=8`. And for example if `/apis/apps/v1beta1` is the proper endpoint, then you should use `k8s_beta = client.AppsV1beta1Api()` as your client.
