### ISSUE TITLE
Unit tests leaking thread pools

### ISSUE THREAD

**Issue by amoralej** [kubernetes-client/python#566]
Unit tests in kubernetes python client don't terminate the pools in tearDown. This makes them to fail when running in specific environments with lower limits as 32bit systems, with errors like:

error: can't start new thread

I've tested it adding pools termination in unit tests and it worked fine, however i understand unit tests are generated automatically with swagger, so i'm not sure what's the right way to propose patches here.

**Comment by zhusichuang** [comment]
I have the same issue.
`api = core_v1_api.CoreV1Api()
resp = stream(api.connect_get_namespaced_pod_exec, name, 'default',
              command=exec_command,
              stderr=True, stdin=False,
              stdout=True, tty=False)
api = None`
The first line code will produce about 59 threads, but after I call the exec api and make the api variable be None ,the 59 threads still be alive in my process.

**Comment by amoralej** [comment]
I think the right fix is add api _client pools terminate in tearDown for each test.

**Comment by roycaihw** [comment]
This is a known issue. Please see https://github.com/kubernetes-client/python/issues/411. @amoralej The tests are generated using swagger-codegen: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/api_test.mustache, please feel free to patch the upstream generator.
