### ISSUE TITLE
question in disabling logs 

### ISSUE THREAD

**Issue by selvakumarnms** [kubernetes-client/python#570]
Hi ,
I am seeing python k8s client is flooding log of logs each time when I request
client/rest.py:237

Logs:
{"@timestamp":"2018-07-12T17:13:17+0000","context":"/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py:237","level":"DEBUG","msg":"[pid: 1, thread: Thread-62] response body: {\"kind\":\"ReplicationController\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"elb-controller\",\"namespace\":\"kube-system\",\"selfLink\":\"/api/v1/namespaces/kube-system/replicationcontrollers/elb-controller/status\",\"uid\":\"809c41ae-85ee-11e8-b017-fa163e194c33\",\"resourceVersion\":\"3948422\",\"generation\":1,\"creat

How to disable this? it is really annoying.

**Comment by roycaihw** [comment]
It seems that you're using [release-3.0](https://github.com/kubernetes-client/python/tree/release-3.0) of this client which contains [this debugging line](https://github.com/kubernetes-client/python-base/blob/168c5e761fc8a60a332e38342fda04350d64fe33/rest.py#L236-L237). 

Please consider upgrade to our new releases https://github.com/kubernetes-client/python/releases. Also see the compatibility matrix for more info https://github.com/kubernetes-client/python#compatibility.

**Comment by selvakumarnms** [comment]
even I have used latest tagged version 7.0.0 still I see the logs are getting printed.

https://github.com/kubernetes-client/python/blob/release-7.0/kubernetes/client/rest.py#L219

**Comment by roycaihw** [comment]
I didn't see we setting log level for the rest client module. We do have level setting for [loggers in configuration module](https://github.com/kubernetes-client/python/blob/release-7.0/kubernetes/client/configuration.py#L152-L173).

IIUC the log level for https://github.com/kubernetes-client/python/blob/release-7.0/kubernetes/client/rest.py#L33 is by default `logging.WARNING`, which shouldn't contain the DEBUG logs.

**Comment by StepanKuksenko** [comment]
also faced with this issue, 
you can configure kubernetes module logger log level directly, example:

```python
import logging
import logging.config

logging_config = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(asctime)s [%(levelname)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'root': {
            'handlers': ['console'],
            'level': log_level,
            'propagate': False,
        },
        'kubernetes': {
            'handlers': ['console'],
            'level': "INFO",
            'propagate': False,
        },
    },
}

logging.config.dictConfig(logging_config)
```

**Comment by zhangguanzhang** [comment]
some other way:
```
logging.getLogger('kubernetes').setLevel(logging.INFO)
```
