### ISSUE TITLE
rollout status deployment : wait for a deployment rollout

### ISSUE THREAD

**Issue by Smana** [kubernetes-client/python#571]
Hey guys,

I would like to know how would it be possible to wait for a deployment rollout and get the output similar to what does the command : 

```
kubectl rollout status deployment foo
```

Sorry but didn't find the answer in the documentation, 
Thanks for your help

**Comment by tomplus** [comment]
Maybe it would help: [read_namespaced_deployment_status](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/ExtensionsV1beta1Api.md#read_namespaced_deployment_status)

**Comment by Smana** [comment]
@tomplus thank you for your answer.
Actually, I could definitely write something with that but I was just wondering if there's a complete example somewhere. A waiting loop that prints the status until the rollout is finished.
Anyway, I'll close this issue in a few days if no one  has an example

**Comment by kamilglod** [comment]
@Smana Following code from https://github.com/kubernetes/kubernetes/blob/74bcefc8b2bf88a2f5816336999b524cc48cf6c0/pkg/controller/deployment/util/deployment_util.go#L745 you can check deployment status like so:
```python3
def _wait_for_deployment_complete(deployment_name, timeout=60):
    api = _get_kube_api(client.ExtensionsV1beta1Api)
    start = time.time()
    while time.time() - start < timeout:
        time.sleep(2)
        response = api.read_namespaced_deployment_status(deployment_name, K8S_API_NAMESPACE)
        s = response.status
        if (s.updated_replicas == response.spec.replicas and
                s.replicas == response.spec.replicas and
                s.available_replicas == response.spec.replicas and
                s.observed_generation >= response.metadata.generation):
            return True
        else:
            print(f'[updated_replicas:{s.updated_replicas},replicas:{s.replicas}'
                  ',available_replicas:{s.available_replicas},observed_generation:{s.observed_generation}] waiting...')

    raise RuntimeError(f'Waiting timeout for deployment {deployment_name}')
```

**Comment by Smana** [comment]
Awesome! Thank you @kamilglod

**Comment by PrajwalShenoy** [comment]
You can find more docs [here](https://github.com/kubernetes-client/python/blob/b313b5e74f7cf222ccc39d8c5bf8a07502bd6db3/kubernetes/docs/AppsV1Api.md)
This is my implementation
```
from kubernetes import client, config
from kubeconfig import KubeConfig
import time

conf = KubeConfig()
namespace = conf.view()['contexts'][0]['context']['namespace']
config.load_kube_config()
v1=client.AppsV1Api()
dep = v1.read_namespaced_deployment_status(deployment_name, namespace)
while dep.status.updated_replicas != dep.spec.replicas:
    time.sleep(10)
```
