### ISSUE TITLE
order of params for a function should not be important. CustomObjectsApi().get_namespaced_custom_object()

### ISSUE THREAD

**Issue by mward29** [kubernetes-client/python#575]
I've run into this a few times now with respect to the CustomObjectsApi. Have not run into it with others but I've not explicitly tested it either. While I'm posting this to the python client, I've not done enough testing to determine where the problem is. (minikube, python client, k8s api)
This two function this effects I've found so far.

**get_namespaced_custom_object**
**create_namespaced_custom_object**

**Expected Behavior**
JSON response
{'apiVersion': 'alpha.metacenter.io/v1',
 'kind': 'Charge',
 'metadata': {'clusterName': '',
              'creationTimestamp': '2018-07-17T04:16:37Z',
              'generation': 1,
              'name': 'tester',
              'namespace': 'default',
              'resourceVersion': '1176',
              'selfLink': '/apis/alpha.metacenter.io/v1/namespaces/default/charges/tester',
              'uid': '32f96be9-8978-11e8-b03f-080027a6927e'},
 'spec': {'avgCpu': '',
          'avgMem': '',
          'creationTimestamp': '',
          'deletionTimestamp': '',
          'disk': '',
          'monthYear': '',
          'podChargesFinal': '',
          'podChargesFinalSeconds': '',
          'podChargesRunning': '',
          'podChargesRunningSeconds': '',
          'status': ''}}

**Actual Behavior**
Exception when calling CustomObjectsApi->get_namespaced_custom_object: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 17 Jul 2018 14:08:41 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found

**Steps to Reproduce the Problem**
run the function with params out of order

**WORKS if the params are ordered accordingly :**
get_namespaced_custom_object(group, version, namespace, plural, name)
create_namespaced_custom_object(group, version, namespace, plural, body)

Specifications
**Version:** 
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Platform: **minikube**

**Comment by roycaihw** [comment]
I wasn't able to reproduce the problem. Could you show more detail on how to reproduce it?

You can enable the logger debug level to check the http request sent to apiserver.

```
cfg = client.configuration.Configuration()
cfg.debug = True
c = client.CustomObjectsApi(client.api_client.ApiClient(cfg))
c.get_namespaced_custom_object(version="v1alpha1", group="samplecontroller.k8s.io", name="example-foo", namespace="default", plural="foos")
```

```
2018-07-24 13:04:06,559 DEBUG https://localhost:6443 "GET /apis/samplecontroller.k8s.io/v1alpha1/namespaces/default/foos/example-foo HTTP/1.1" 200 388
{u'kind': u'Foo', u'spec': {u'deploymentName': u'example-foo', u'replicas': 1}, u'apiVersion': u'samplecontroller.k8s.io/v1alpha1', u'metadata': {u'name': u'example-foo', u'generation': 1, u'namespace': u'default', u'resourceVersion': u'4028', u'creationTimestamp': u'2018-07-24T19:35:27Z', u'selfLink': u'/apis/samplecontroller.k8s.io/v1alpha1/namespaces/default/foos/example-foo', u'uid': u'b7766613-8f78-11e8-87d9-705a0f4b4210'}}
```
