### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by zhusichuang** [kubernetes-client/python#576]
```
api = core_v1_api.CoreV1Api()
resp = stream(api.connect_get_namespaced_pod_exec, name, 'default',
              command=exec_command,
              stderr=True, stdin=False,
              stdout=True, tty=False)
api = None
```
The python GC can't collect the variable 'api',and `api.api_client.pool.close()`won't be called.This will make my process have many threads until it crashes.
![image](https://user-images.githubusercontent.com/24446530/42875085-5455919a-8ab5-11e8-8a5a-c78cacf849d7.png)

**Comment by roycaihw** [comment]
Dup of https://github.com/kubernetes-client/python/issues/411
