### ISSUE TITLE
Add Python 3.7 support to Travis CI testing

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-client/python#584]
Python 3.7 is released and we need to add it to our ci 

- [ ] Currently workaround exists but 3.7 isn't officially supported by travis ci: https://github.com/travis-ci/travis-ci/issues/9815

**Comment by sellers** [comment]
see #558

**Comment by Lawouach** [comment]
Hey folks,

Just a friendly ping to know the status of this one. Following #558, a fix was merged but I'm a little confused about what needs to be addressed still? Also, as this a breaking change (we have moved to Python 3.7 and currently can't use the kube client with it), is there a potential ETA by any chance? :)

Thanks :)

**Comment by roycaihw** [comment]
This issue is about testing this client in Travis CI with Python 3.7. The client itself already resolved the reserved keyword conflict since 7.0.0a1 release: https://github.com/kubernetes-client/python/blob/master/CHANGELOG.md#v700a1
