### ISSUE TITLE
RoleBinding and Role 'kind' is 'None'

### ISSUE THREAD

**Issue by mydockergit** [kubernetes-client/python#586]
Why the 'kind' field in all the objects: RoleBinding, Role, ClusterRoleBinding, Cluster is `None` ?

**Reproduce:**  
```
from kubernetes import client, config
config.load_kube_config()
v1 = client.RbacAuthorizationV1Api()
roles = v1.list_role_for_all_namespaces()
roles.items[0].kind
```

**Comment by roycaihw** [comment]
`/apis/rbac.authorization.k8s.io/v1/roles/` returns a `RoleList` object ("kind": "RoleList", "apiVersion": "rbac.authorization.k8s.io/v1") and when apiserver omits the type meta (`kind` and `apiVersion`) for `items` when responding a list object (did a quick search but didn't find the reason behind).

Usually what happens is: 

```
GET host:port/api/v1/XXX

{
    "kind": "XXXList",
    "apiVersion": "v1",
    "metadata": {
        "selfLink": "/api/v1/XXX",
        "resourceVersion": "###"
    },
    "items": [
      {
        "metadata": ...
        "spec": ...
        "status": ...
      },
      {
        "metadata": ...
        "spec": ...
        "status": ...
      },
      {
        "metadata": ...
        "spec": ...
        "status": ...
      }
    ]
}
```

Therefore the `roles.items[0].kind` is `None`

**Comment by mydockergit** [comment]
I think that when there is a request for `v1.list_role_for_all_namespaces()` (just one example), the items are Roles and therefore their `kind` should be assigned with kind `Role`

**Comment by roycaihw** [comment]
I feel it's feasible to infer items' `Kind` when deserializing the list object in this client (also see https://github.com/kubernetes-client/python/issues/429), but it would benefit all clients in other languages if apiserver properly sets the items' `Kind` when responding a list request. Please feel free to file an issue in upstream kubernetes about this.
