### ISSUE TITLE
Replicate kubectl create -f in python client

### ISSUE THREAD

**Issue by simeonkorchev** [kubernetes-client/python#591]
Hello,
I am trying to deploy Issuer and Certificate in a particular namespace with Kubernetes Python client. However, I can not figure out how to get this done. Is it implemented such a functionality which simulates the behavior of "kubectl create -f file" command? If not, has the implementation of this functionality  been planned already?
Regards

**Comment by qubusp** [comment]
Same issue here, https://github.com/kubernetes-client/python/issues/514

**Comment by tomplus** [comment]
Something like `kubectl create -f file` you can find in this example: https://github.com/kubernetes-client/python/blob/master/examples/create_deployment.py

**Comment by roycaihw** [comment]
@tomplus complained this well. Closing
