### ISSUE TITLE
Is there way to make this run in a Dockerfile?

### ISSUE THREAD

**Issue by DjKniteX** [kubernetes-client/python#592]
I'm trying to run this as a Dockerfile on minikube and the test code runs fine when i run python app.py in the terminal and it shows up the pod information but I wanna run it from a docker image

this is what my dockerfile looks like

FROM python:3
ADD . /
RUN pip install kubernetes
CMD [ "python", "./app.py" ]
i keep getting an errcrashloop or an image never pull, also when i run "docker run name"

i get this

`docker run pythonathome1
Traceback (most recent call last):
  File "./app.py", line 4, in <module>
    config.load_kube_config()
  File "/kubernetes/config/kube_config.py", line 480, in load_kube_config
    config_persister=config_persister)
  File "/kubernetes/config/kube_config.py", line 437, in _get_kube_config_loader_for_yaml_file
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.kube/config'
`

Any ideas?

**Comment by tomplus** [comment]
You can't use `load_kube_config()` from a pod, use `load_incluster_confg()` instead.

Example: https://github.com/kubernetes-client/python/blob/master/examples/in_cluster_config.py#L21

Ref: https://github.com/kubernetes-client/python/issues/255

**Comment by nxaysanasy** [comment]
I changed that line to what you suggested and I'm getting a crashloopbackoff when im trying to kubectl run the local docker image.

Does the dockerfile look right?

**Comment by DjKniteX** [comment]
I changed that line to what you suggested and I'm getting a crashloopbackoff when im trying to kubectl run the local docker image.

Does the dockerfile look right?

@tomplus

**Comment by tomplus** [comment]
Yes, Dockerfile is correct. crashloopbackoff means that your application exits and k8s tries to start it again. Please check what your application logs.

**Comment by DjKniteX** [comment]
this is what im getting when using the code you referenced

`Listing pods with their IPs:
Traceback (most recent call last):
  File "./app.py", line 16, in <module>
    main()
  File "./app.py", line 9, in main
    ret = v1.list_pod_for_all_namespaces(watch=False)
  File "/kubernetes/client/apis/core_v1_api.py", line 13608, in list_pod_for_all_namespaces
    (data) = self.list_pod_for_all_namespaces_with_http_info(**kwargs)
  File "/kubernetes/client/apis/core_v1_api.py", line 13705, in list_pod_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 14 Aug 2018 17:24:07 GMT', 'Content-Length': '243'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:default:default\" cannot list pods at the cluster scope","reason":"Forbidden","details":{"kind":"pods"},"code":403}
`

**Comment by tomplus** [comment]
It's better, you get the response from API Server :)

This error `pods is forbidden: User \"system:serviceaccount:default:default\" cannot list pods at the cluster scope` means that you need configure ClusterRole/Binding to allow to do this action. More information: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by DjKniteX** [comment]
Just so I'm reading this right, I have to make a yaml file now?

**Comment by tomplus** [comment]
Yes, by applying yaml manifests. Pods cannot query api server by default. You, as an administrator, can create role/binding to add required permissions.

**Comment by tomplus** [comment]
Hi @DjKniteX how is going, does your application work?

To answer your questions - for security reason - by default pod can't get information about a cluster.

**Comment by DjKniteX** [comment]
@tomplus not yet, haven't gotten a chance to touch it yet but I will tomorrow. so from just the general looks of it, can I just copy the example code from the authorization and in the docker-compose make it run the local docker image?

**Comment by tomplus** [comment]
If you want to use the docker-compose you won't need to create RBAC manifests - it's k8s configuration. A script started by docker-compose works as stand-alone script with its kubeconfig file.

**Comment by DjKniteX** [comment]
@tomplus oh okay, so how would I write this? Just make a separate yml file and package it when I docker build it?

i call it auth.yml stick the example code in it. docker build . kubectl run it, and it should run this time?

**Comment by DjKniteX** [comment]
Okay, I'm getting a crashlooperror again and when i try to python app.py I get this error now

`Traceback (most recent call last):
  File "app.py", line 5, in <module>
    config.load_incluster_config()
  File "/home/nikkix/Documents/work/python/kubernetes/config/incluster_config.py", line 93, in load_incluster_config
    cert_filename=SERVICE_CERT_FILENAME).load_and_set()
  File "/home/nikkix/Documents/work/python/kubernetes/config/incluster_config.py", line 45, in load_and_set
    self._load_config()
  File "/home/nikkix/Documents/work/python/kubernetes/config/incluster_config.py", line 51, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set`

**Comment by DjKniteX** [comment]
@tomplus im getting the same error as the one above, im trying to run this in minikube, when i did describe pod this is what i get

`kubectl describe pod hello-python-95dc7b4c-nlkpz
Name:           hello-python-95dc7b4c-nlkpz
Namespace:      default
Node:           minikube/10.0.2.15
Start Time:     Mon, 20 Aug 2018 15:48:48 -0700
Labels:         pod-template-hash=51873607
                run=hello-python
Annotations:    <none>
Status:         Running
IP:             172.17.0.4
Controlled By:  ReplicaSet/hello-python-95dc7b4c
Containers:
  hello-python:
    Container ID:   docker://b8d37a4277bf32d31d8470d61b40fdfd90477c28c241657c3e54f269ce245250
    Image:          hello-python123:v1
    Image ID:       docker://sha256:c815c79585f19c8e106bb52222249d34e48ceaad751d82df38e2160e364c0be8
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 20 Aug 2018 15:52:13 -0700
      Finished:     Mon, 20 Aug 2018 15:52:15 -0700
    Ready:          False
    Restart Count:  5
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-nxxtc (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-nxxtc:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-nxxtc
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age              From               Message
  ----     ------                 ----             ----               -------
  Normal   Scheduled              4m               default-scheduler  Successfully assigned hello-python-95dc7b4c-nlkpz to minikube
  Normal   SuccessfulMountVolume  4m               kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-nxxtc"
  Normal   Pulled                 2m (x5 over 4m)  kubelet, minikube  Container image "hello-python123:v1" already present on machine
  Normal   Created                2m (x5 over 4m)  kubelet, minikube  Created container
  Normal   Started                2m (x5 over 4m)  kubelet, minikube  Started container
  Warning  BackOff                1m (x9 over 3m)  kubelet, minikube  Back-off restarting failed container
`

**Comment by DjKniteX** [comment]
im trying to run this in minikube as well
