### ISSUE TITLE
Error parsing KUBECONFIG url

### ISSUE THREAD

**Issue by cpwr** [kubernetes-client/python#599]
I have `KUBECONFIG` path like that: 

> /home/username/.kube/config:/home/username/Downloads/config-azure-dev.txt

The way config file name parsed is not correct for such cases:
`config_file = os.path.expanduser(KUBE_CONFIG_DEFAULT_LOCATION)`
and it causes an error:

> $ python test.py 
> Traceback (most recent call last):
>   File "test.py", line 4, in <module>
>     config.load_kube_config()
>   File "/home/username/workspace/kubernetes/env/lib/python3.5/site-packages/kubernetes/config/kube_config.py", line 470, in load_kube_config
>     config_persister=config_persister)
>   File "/home/username/workspace/kubernetes/env/lib/python3.5/site-packages/kubernetes/config/kube_config.py", line 427, in _get_kube_config_loader_for_yaml_file
>     with open(filename) as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/username/.kube/config:/home/username/Downloads/config-azure-dev.txt'

Maybe user should get a warning instead?
```
if len(KUBE_CONFIG_DEFAULT_LOCATION.split(':')) > 1:
    raise ValueError('Your setup has more than one path. Please, provide the config file location '
                     'explicitly')
```
or use the default path like so:
```config_file = os.path.expanduser(KUBE_CONFIG_DEFAULT_LOCATION.split(':')[0])```

**Comment by tomplus** [comment]
This feature has to be added to python-base repo, ref issue: https://github.com/kubernetes-client/python-base/issues/62

**Comment by ignertic** [comment]
I'm interested in tackling this issue

**Comment by ignertic** [comment]
i cloned the repository by i can't seem to find the _/kubernetes/config_ folder

**Comment by ignertic** [comment]
Check out [#96](https://github.com/kubernetes-client/python-base/pull/96)

**Comment by yliaog** [comment]
this is fixed by https://github.com/kubernetes-client/python-base/pull/94
/close
