### ISSUE TITLE
Deleting a job requires a body, which conflicts with query parameters

### ISSUE THREAD

**Issue by pvanderlinden** [kubernetes-client/python#600]
Deleting a job requires a body, which conflicts with query parameters.

Example:
```
api.delete_namespaced_job(job_name, namespace, {}, propagation_policy='Foreground'))
```
This will get the `propagation_policy` query parameter to be ignored by the kubernetes api. Passing in None will give an error (Body required), passing `''` will cause a parse error on the kubernetes api server (not valid json).
For more information, see: https://github.com/kubernetes/kubernetes/issues/67394

Luckily there is a workaround, by not using a query parameter, but the above method should work without a body:
```
api.delete_namespaced_job(job_name namespace, {
    'apiVersion': 'v1',
    'kind': 'DeleteOptions',
    'propagationPolicy': 'Foreground',
})
```

**Comment by iamneha** [comment]
@roycaihw can you please assign me this issue

**Comment by roycaihw** [comment]
@iamneha Sure thing :) 

Due to kubernetes org policy, I think we can only assign issue/PR to org members (you can apply for membership in https://github.com/kubernetes/org)-- but it's still great to reply under the issue to let others know that you'll be working on it

/assign @iamneha

**Comment by saurav-malani** [comment]
Hello @iamneha are you still working on this issue?
