### ISSUE TITLE
Kubes ops communicating via websockets and API hanging

### ISSUE THREAD

**Issue by bonneaud** [kubernetes-client/python#602]
Hi,

**This is a Bug Report**
- [ ] Feature Request
- [x] Bug Report

**Problem:**
We're using Kubernetes clusters with pods running Airflow. We then have other pods running tasks that send commands to Airflow. To do that, these ops use websockets (kubernetes.stream) and Kubernetes' core_v1_api to get the information about the pod running Airflow. We run commands in one pod, from another pod, by using connect_get_namespaced_pod_exec [1] via the Kubernetes Python API, which, if we understand correctly, is a wrapper for 'kubectl exec'. Our code looks like:
stream(self.api.connect_get_namespaced_pod_exec,
            self.web_pod_name,
            self.namespace,
            command=['airflow'] + cmd,
            container='web',
            stdin='True',
            stdout='True')

Most of the times, our tasks are able to send commands and get their outputs back from Airflow's pods. Once in a while though, the tasks seem to hang forever on the stream call. When the task hangs, it is accessible via Kubes and shown as running, it simply is silent. We don't see any error.

[1] https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#connect_get_namespaced_pod_exec

**Proposed Solution:**
We don't have a solution right now, except to delete the pod via Kube and re-create it.

**Environment**:
- Kubernetes version (use `kubectl version`): 1  (1.9.7-gke.5)
- Cloud provider or hardware configuration: Google Cloud / GKE cluster
- OS (e.g. from /etc/os-release): Linux

**Comment by abeltre1** [comment]
@bonneaud  I have the same issue, have you found a solution to it? 
alternatively, we can use os.system(<command>) as a hack.

**Comment by PaulFurtado** [comment]
@bonneaud I may have tracked down the issue you're hitting, I filed an issue here: https://github.com/kubernetes-client/python-base/issues/106

**Comment by arzarif** [comment]
@PaulFurtado - are you hitting this specifically when using CRI-O? The OP's description of this bug matches my own exactly - intermittent, indefinite hangs when invoking connect_get_namespaced_pod_exec. In my case, however, I'm using just Docker. It doesn't look like the OP specified which runtime they were using.

**Comment by PaulFurtado** [comment]
@arzarif the issue I filed is relevant to every runtime, however, for the commands I tested, something about the framing of the data causes it to be very reproducible when cri-o is the runtime.

**Comment by arzarif** [comment]
@PaulFurtado Interesting. Thanks for the heads up. This seems to be a pretty serious issue; it appears that Rundeck's remote pod execution feature is broken because of this. I tried to bypass Rundeck altogether and hit the same problem in my own client before stumbling on this issue.

**Comment by PaulFurtado** [comment]
Yeah, I agree that this is a serious issue for anyone using the exec API from python. Unfortunately, I'm not a maintainer and none of them have commented on that issue, but maybe I should just open a PR to get the ball rolling. On my end, I work around this by monkey-patching the python client, you could do the same if you need an immediate solution.

**Comment by TomasTomecek** [comment]
Having the same issue: https://github.com/packit-service/sandcastle/issues/23

**Comment by TomasTomecek** [comment]
After being stuck on this for far too long, I was able to solve this by passing `_request_timeout=30.0` to stream(), can anyone verify?

**Comment by SudheerBondada** [comment]
@PaulFurtado @arzarif This issue seems to be occurring with https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_namespaced_pod as well. (k8 python client version: 8.0.1). Adding a timeout does not help either, the API call neither returns anything nor throws an error. Looks like no one is assigned to this issue from the dev team yet.

**Comment by EricCat** [comment]
@TomasTomecek `_request_timeout` not work for me. the kubernetes package default is `_request_timeout = kwargs.get("_request_timeout", 60)`

**Comment by michalmisiewicz** [comment]
I'm facing the same issue with `create_namespaced_pod`
