### ISSUE TITLE
Missing `metadata.json` in wheels since 6.0.0

### ISSUE THREAD

**Issue by kevingessner** [kubernetes-client/python#604]
The published wheels on Pypi for kubernetes-client seem to be missing an important file: `metadata.json` in the `dist-info` directory.  The wheel for version 6.0.0b1 (from https://pypi.org/project/kubernetes/6.0.0b1/#files) contains `kubernetes-6.0.0b1.dist-info/metadata.json` but the wheels for 6.0.0 and 7.x don't have any `metadata.json`.  That file being absent breaks some consumers of the wheel as a dependency (Bazel's rules_python, in my case) which use `metadata.json` to resolve dependencies.

Can you please restore that file to the published wheels?  Thanks!

**Comment by roycaihw** [comment]
I think `metadata.json` is dropped by upstream bdist_wheel (which we use in our release process): https://github.com/pypa/wheel/issues/195. Please read workaround mentioned in that issue for parsing METADATA.
