### ISSUE TITLE
GCP Token not getting refreshed => 404 Error

### ISSUE THREAD

**Issue by hannes-brt** [kubernetes-client/python#612]
I am using Snakemake (https://bitbucket.org/snakemake/snakemake), a system for running scientific and Bioinformatics computing pipelines, which offers a Kubernetes backend.

Currently, long-running jobs on GKE always eventually fail with a 404 error (https://bitbucket.org/snakemake/snakemake/issues/932/long-running-jobs-on-kubernetes-fail). We believe that the problem is in the Kubernetes client, as we determined that although `_refresh_gcp_token` is being called when the token is expired, the next API call still fails with a 404 error.

**Comment by hannes-brt** [comment]
Any leads on what might be happening here?

**Comment by flylo** [comment]
@hannes-brt is this at all related to your issue?

https://github.com/kubernetes-client/python/issues/492
