### ISSUE TITLE
create namespace

### ISSUE THREAD

**Issue by 1032231418** [kubernetes-client/python#613]
Hi,
Namespace, how to create, there is no example, do you have any namespace documentation?

**Comment by tomplus** [comment]
Hi. 
The documentation is generated from the official specification and it's not very easy to use. I usually start with official API doc https://kubernetes.io/docs/reference/ and then I browse this auto-generated https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md

**Comment by reymont** [comment]
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#create_namespace

**Comment by mitar** [comment]
```
    kubernetes_client.create_namespace(client.V1Namespace(metadata=client.V1ObjectMeta(name=namespace)))
```

**Comment by roycaihw** [comment]
Thanks for explaining! @tomplus @reymont @mitar 

@1032231418 I also suggest the [kubernetes-client slack channel](https://kubernetes.slack.com/messages/C76GB48RK/) would be a good place to ask question like this one :) I will add a section to mention it in README
