### ISSUE TITLE
The python client do not provide create_persistent_volume_claim function

### ISSUE THREAD

**Issue by reymont** [kubernetes-client/python#614]
In https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#create_persistent_volume, I find the create_persistent_volume. But where is the `create_persistent_volume_claim`?

**Comment by tomplus** [comment]
hi @reymont you are looking for `create_namespaced_persistent_volume_claim`. PVs are global object unlike to PVCs which exist in namespaces.

**Comment by reymont** [comment]
thanks @tomplus .
