### ISSUE TITLE
periodically reload InClusterConfig token

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/python#616]
This feature is being implemented for client-go in the main repo and needs to be implemented here too: https://github.com/kubernetes/kubernetes/pull/67359

**Comment by saurav-malani** [comment]
@GeekTheGreat are you still working on this? If not, then I would like to take it up.

**Comment by GeekTheGreat** [comment]
Hello @saurav-malani,  I'm working on it.

**Comment by mourya007** [comment]
@marie-yau hey, Are you still working on it ?

**Comment by isunitha98selvan** [comment]
I would like to work on this issue.

**Comment by saurav-malani** [comment]
Hello @isunitha98selvan! I haven't seen any activity on this issue, for the past 4 weeks. Are you still working on this?

**Comment by marie-yau** [comment]
Hello everyone, you can work on it. It is too difficult for me to fix.

**Comment by LTMenezes** [comment]
Can I work on this issue? @mbohlool

**Comment by mikedanese** [comment]
@LTMenezes please do.

**Comment by schedutron** [comment]
@LTMenezes are you still working on this? I'd like to give a shot.

**Comment by LTMenezes** [comment]
Sorry for the delay @schedutron, I am not, you can go ahead.

**Comment by zshihang** [comment]
this can be closed. @mikedanese

**Comment by mikedanese** [comment]
@zshihang Thanks!
