### ISSUE TITLE
patch_namespaced_secret: add usage doc

### ISSUE THREAD

**Issue by kevinburke** [kubernetes-client/python#618]
Currently the body of the docstring for `patch_namespaced_secret` uses `body = NULL`, which is unhelpful in explaining how to use it.

I have these questions:

- How does `body` relate (if at all) to the `jsonpatch` spec?
- If I call `patch_namespaced_secret` with one key in the `data` object will all of the other keys get clobbered?
- How do I delete a key in `secret.data` ?

**Comment by roycaihw** [comment]
The documentation under https://github.com/kubernetes-client/python/tree/master/kubernetes/docs are auto-generated from openapi spec, which (sadly) aren't very helpful for questions like this one. We usually add [examples](https://github.com/kubernetes-client/python/tree/master/examples) to document complex/detailed usages that code generator can't explain well. 

To the question about `patch_namespaced_secret`, please refer to sections on patching a map in [strategic-merge-patch](https://github.com/kubernetes/community/blob/master/contributors/devel/strategic-merge-patch.md). Also please refer to how this client uses strategic merge patch as default https://github.com/kubernetes-client/python/issues/641#issuecomment-429473349

**Comment by totycro** [comment]
This issue is actually still open despite being closed here. The documentation link posted above also has been deleted by now:
https://github.com/kubernetes/community/blob/master/contributors/devel/strategic-merge-patch.md

I'm not sure what the original link said, but this might be the current version:
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#notes-on-the-strategic-merge-patch

**Comment by Gabrielmadrid73** [comment]
@kevinburke I had this same problem, looking for a example. I solved it creating body this way:

```
body = {
    "apiVersion": "v1",
    "kind": "Secret",
    "data": { "abc" : "123" },
    "metadata": {"annotations": {"xxx": "xxx", "yyy": "yyy"}, "name": "secretnamehere", "namespace": "namespacehere"},
    "type": "typeofsecrethere"
}
```

I hope help someone!

**Comment by rgouveia-redhat** [comment]
Hi,

I spent hours reading docs, source code, and googling. I finally ended with this elegant solution. I am just sharing in the hope it can be of use to other.

On the command line the command is:

~~~
$ oc patch secret -p='{"metadata": {"annotations": {"auth.openshift.io/certificate-not-after": null}}}' -n openshift-kube-apiserver external-loadbalancer-serving-certkey
secret/external-loadbalancer-serving-certkey patched
~~~

The patch code that works for me is:

~~~
        patch = {"metadata": {"annotations": {"auth.openshift.io/certificate-not-after": ""}}}
        res = v1api.patch_namespaced_secret(secret_name, namespace, body=patch)
~~~
