### ISSUE TITLE
config.load_kube_config fails with Exception TypeError: "'NoneType' object is not callable"

### ISSUE THREAD

**Issue by Jainbrt** [kubernetes-client/python#625]
Hi Team, 
I have tried simple code to load kube config but it is failing saying "'NoneType' object is not callable" .

[root@node1 ~]# cat list.py
import os
from kubernetes import client, config
config.load_kube_config()

[root@node1 ~]# python list.py
Exception TypeError: "'NoneType' object is not callable" in <function _removeHandlerRef at 0x7fc213b85c80> ignored

**Comment by 1032231418** [comment]
@Jainbrt  config.load_kube_config("/root/.kube/config")

**Comment by 1032231418** [comment]
@Jainbrt You need to put the configuration file here.

**Comment by Jainbrt** [comment]
Thanks for your response. Still the same Exception error. 

Snippet:
-------------

[root@node1 ~]# cat list.py
import os
from kubernetes import client, config
config.load_kube_config("/root/.kube/config")

[root@node1 ~]# python list.py
Exception TypeError: "'NoneType' object is not callable" in <function _removeHandlerRef at 0x7f70def6ec80> ignored

[root@node1 ~]# ls -ltr "/root/.kube/config"
-rw------- 1 root root 5454 Sep 11 14:34 /root/.kube/config
[root@node1 ~]#

**Comment by cliffburdick** [comment]
I'm seeing the same error. I have the config in the place suggested above.

**Comment by gangadhars** [comment]
I'm also getting the same problem.

How to reproduce:

```
>>> import kubernetes
>>> exit()
Exception TypeError: "'NoneType' object is not callable" in <function _removeHandlerRef at 0x7f3b0bccd938> ignored
```
Environment
```
Client version:  8.0.0a1

kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

OS: Ubuntu 16.04.5 LTS
```
