### ISSUE TITLE
[help] How to access api server via python client in pod

### ISSUE THREAD

**Issue by sevensees** [kubernetes-client/python#626]
Hi,

I need to run the python client in the pod to access api server. When the python client runs in the pod, it raise an error that 

> No such file or directory: '/root/.kube/config'

It seems that the python client tries to read config file. Is there any approach to configure the client in the pod?

thanks a lot.

**Comment by tomplus** [comment]
You have to use a different method to configure client. Here is an example: https://github.com/kubernetes-client/python/blob/master/examples/in_cluster_config.py#L55

**Comment by sevensees** [comment]
@tomplus Thanks a lot.
