### ISSUE TITLE
Library appears to globally override urllib logging, adds additional handler each time new_client is called

### ISSUE THREAD

**Issue by jakewins** [kubernetes-client/python#629]
The following code reproduces my issue:

```
import logging
from kubernetes import config
from urllib3.connectionpool import log as urlliblog


class FooMatter(logging.Formatter):
    """
    Custom formatter that prepends "foo" to every log message
    """
    def format(self, record):
        msg = super().format(record)
        return f"Foo: {msg}"

# Configure logging for my application
handler = logging.StreamHandler()
handler.setFormatter(FooMatter())

root = logging.getLogger()
root.addHandler(handler)
root.setLevel(logging.INFO)


kubeconfig = "/path/to/.kube/config"
context = "cluster-context"

# Call new_client a few times..
config.new_client_from_config(kubeconfig, context)
config.new_client_from_config(kubeconfig, context)
config.new_client_from_config(kubeconfig, context)

urlliblog.warning("Hello from urllib")
```

I expect this code to log a single line, via the global custom handler:

    Foo: Hello from urllib

However, it appears each call to `new_client_from_config` modifies the application logging configuration, appending an additional log handler to the urllib logger, so the actual output is:

    2018-09-24 16:08:19,496 WARNING Hello from urllib
    2018-09-24 16:08:19,496 WARNING Hello from urllib
    2018-09-24 16:08:19,496 WARNING Hello from urllib
    Foo: Hello from urllib

This leads to large amounts of unwanted logging as urllib3 logs warnings about connection problems.

Since the kubernetes python client is a library, I would expect it to not make any modifications to logging output at all - setting up log handlers is up to the application - and particularly not modify standard library loggers.

**Comment by jakewins** [comment]
The issue seems to revolve around this: https://github.com/kubernetes-client/python/blob/master/kubernetes/client/configuration.py#L136

I'd be happy to contribute a patch, but I'm not sure what direction to go with it; as mentioned above, it seems wrong that library code should be attaching log handlers at all - but I assume the above code is there for a reason. Maybe just a patch with an option to disable that code?

**Comment by jakewins** [comment]
As an aside, this works as a, albeit brittle, workaround: 

```
client = config.new_client_from_config(..)
for logger in client.configuration.logger.values():
    logger.removeHandler(client.configuration.logger_stream_handler)
```

**Comment by BobbieSueDevRecruiter** [comment]
Unsubscribe immediately
