### ISSUE TITLE
Missing model AppsV1beta2Deployment

### ISSUE THREAD

**Issue by woqer** [kubernetes-client/python#632]
Trying to install the dashboard from https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

I'm getting several missing models for different api version:
```
AppsV1beta2Deployment
Rbac.authorization.k8s.io_v1Role
Rbac.authorization.k8s.io_v1RoleBinding
```

Client versions:
```
kubernetes: 7.0.0-snapshot
openshift: 0.7.9
```
Server version:
```
Kubernetes: 1.10
```

I'm assuming the client should support it since it has been available since Kubernetes Server 1.8 https://github.com/kubernetes/dashboard/commit/054916b8fbadebd32dc16d32108fdd3c9ccbf400#diff-c94c495c3bae442684adf5dad7519941R79

**Comment by woqer** [comment]
Just saw a new relase coming but it seems that `AppsV1beta2Deployment` is still missing... any thoughts? https://github.com/kubernetes-client/python/pull/631

**Comment by roycaihw** [comment]
This is an intended behavior. `AppsV1beta2Deployment` model is defined in [v1beta2_deployment.py](https://github.com/kubernetes-client/python/blob/release-8.0/kubernetes/client/models/v1beta2_deployment.py). The `apps_v1beta2_api` takes and returns `V1beta2Deployment` [object](https://github.com/kubernetes-client/python/blob/release-8.0/kubernetes/client/apis/apps_v1beta2_api.py#L262-L266). 

The `Apps` prefix was removed intentionally during [client generation](https://github.com/kubernetes-client/gen/blob/master/openapi/preprocess_spec.py#L197-L205):

> This function tries to remove parts of the package name but will make sure there is no conflicting model 
names.

The `remove_model_prefixes` method tries to keep only two rightmost segments from the definition name , e.g. keeping `v1beta2.Deployment` from `io.k8s.api.apps.v1beta2.Deployment`. 

When a conflict exists (e.g. `io.k8s.api.extensions.v1beta1.Deployment` and `io.k8s.api.apps.v1beta1.Deployment`), the method keeps [adding one more segment](https://github.com/kubernetes-client/gen/blob/master/openapi/preprocess_spec.py#L229-L234) until the conflict is resolved: keeping `extensions.v1beta1.Deployment` and `apps.v1beta1.Deployment`.

**Comment by woqer** [comment]
Thank you @roycaihw for such a detailed response, really appreciate it! Thought it was an issue with the client, but seems to be Ansible :'(
