### ISSUE TITLE
DeprecationWarning from kube_config.py

### ISSUE THREAD

**Issue by rbtcollins** [kubernetes-client/python#634]
Most folk won't see these as they default hidden in widely used Python versions.

```
17:24:57 ./.tox/venv/lib/python3.5/site-packages/kubernetes/config/kube_config.py:102: DeprecationWarning: decodestring() is a deprecated alias, use decodebytes()
17:24:57    base64.decodestring(self._data.encode()))
```

Using `base64.standard_b64decode` will avoid this.

**Comment by roycaihw** [comment]
@rbtcollins Thanks for reporting this!

**Comment by roycaihw** [comment]
Fixed by https://github.com/kubernetes-client/python-base/pull/90.
