### ISSUE TITLE
load_kube_config does not support colon delimited KUBECONFIG files in env

### ISSUE THREAD

**Issue by matohavo** [kubernetes-client/python#636]
https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable

**Comment by tomplus** [comment]
This feature has to be added to python-base repo, ref issue: https://github.com/kubernetes-client/python-base/issues/62

**Comment by kshitija08** [comment]
@matohavo @brendandburns @roycaihw Hey , I would like to take up this issue.

**Comment by tomplus** [comment]
@kshitija08 I'm already working on it, see the link above.

**Comment by kshitija08** [comment]
@tomplus Sorry, my mistake. Please carry on with your work. :)

**Comment by tomplus** [comment]
@kshitija08 if you need this feature you can use my branch to test. I hope it'll be reviewed and merged soon.

**Comment by sebhoss** [comment]
@yliaog do you remember why this was closed? This features does not seem to be working with the current version (29.0.0) and a KUBECONFIG that looks like this: `/var/home/seb/.config/kube/clusters/kube.example.com.yaml:/var/home/seb/.config/kube/contexts/kube.example.com.yaml:/var/home/seb/.config/kube/users/kube.example.com.yaml`
