### ISSUE TITLE
Issues with connect_get_namespaced_pod_exec

### ISSUE THREAD

**Issue by kaniket1234** [kubernetes-client/python#638]
I am new to kubernetes world and trying to automate few scenarios.
The basic test case which i am trying is to connect to a pod and execute a list directory command.
Here is my code:
```
from kubernetes import config
from kubernetes.client import Configuration
from kubernetes.client.apis import core_v1_api
config.load_kube_config()
c = Configuration()
c.assert_hostname = False
api = core_v1_api.CoreV1Api()
exec_command = [
    '/bin/sh',
    '-c',
    'ls']
resp = api.connect_get_namespaced_pod_exec('mytestpod','default',command=exec_command, stderr=True, stdin=False, stdout=True, tty=False)
print("Response: " + resp)
```
I was getting "hostname is invalid" error while executing this program. While debugging, I found that the url constructed for websocket is malformed:
```
wss:/api-*****/api/v1/namespaces/default/pods/mytestpod/exec?stderr=True&stdin=False&stdout=True&tty=False&command=%2Fbin%2Fsh&&command=-c&&command=ls&
```

Note: there is only one slash (/) after wss: and that causes a problem. There is one line in ws_client.py file which does below operation:
`# patch extra /
    url = url.replace('//api', '/api')`
If i comment out this line then the test works fine. Do we have any workaround for this?

**Comment by roycaihw** [comment]
@kaniket1234 It looks like you're using 2.0 release of this client, which has the `url.replace` function call (I couldn't find the code in later releases).

2.0 release is not supported anymore (please refer to "Maintenance status" in https://github.com/kubernetes-client/python/blob/master/README.md). Could you try update your client to latest stable version [v7.0.0](https://github.com/kubernetes-client/python/releases) to see if it solves your problem? Thanks
