### ISSUE TITLE
How to create a configmap with a file?

### ISSUE THREAD

**Issue by linuxvip** [kubernetes-client/python#642]
I want to do the following using kubernetes-client python
```bash
# kubectl create configmap --from-file=/tmp/test.conf 
```
> **I want to pass in a configuration file, not a key-value pair**
In the example I don't find it. 

my code
```python
from kubernetes import client, config
from kubernetes.client.rest import ApiException
from pprint import pprint


def create_configmap_object():
    # Configureate ConfigMap metadata
    metadata = client.V1ObjectMeta(
        name="chummy-configmap",
        namespace="default",
    )
    # Instantiate the configmap object
    configmap = client.V1ConfigMap(
        api_version="v1",
        kind="ConfigMap",
        # How do I modify here ?
        data=dict(env="test",host="xx.xx.xxx.xx"),
        metadata=metadata
    )
    return configmap

def create_configmap(api_instance, configmap):
    try:
        api_response = api_instance.create_namespaced_config_map(
            namespace="default",
            body=configmap,
            pretty = 'pretty_example',
        )
        pprint(api_response)

    except ApiException as e:
        print("Exception when calling CoreV1Api->create_namespaced_config_map: %s\n" % e)

def main():
    config.load_kube_config()
    configuration = client.Configuration()
    api_instance = client.CoreV1Api(client.ApiClient(configuration))

    configmap = create_configmap_object()
    create_configmap(api_instance, configmap)

if __name__ == '__main__':
    main()
```
> **I want to pass in a configuration file, not a key-value pair**
my  configuration file :  /tmp/test.conf

How do I change my code？ Thanks！
Thanks！Thanks！Thanks！Thanks！

**Comment by JonathanRRogers** [comment]
I'm not sure opening an issue is the best way to request help. That said, it's not obvious to me where a better place would be. If you want to do something with the contents of a file in Python, the most straightforward approach is to use the built-in open() function and call .read() on the resulting file object. The following code would give you the contents of your file in the variable "contents," after which you could pass it to V1ConfigMap().
`with open('/tmp/test.conf') as f:
    contents = f.read()
`

**Comment by linuxvip** [comment]
Thanks a lot ! @JonathanRRogers .
Modified code:
```python
 .......
.......
def create_configmap_object():
    # Configureate ConfigMap metadata
    metadata = client.V1ObjectMeta(
        annotations=dict(app="test", person="chummy"),
        deletion_grace_period_seconds=30,
        labels=dict(app="test", person="chummy"),
        name=CONFIGMAP_NAME,
        namespace="default",
    )
    # Get File Content
    with open('/tmp/test.txt', 'r') as f:
        file_content=f.read()
    # Instantiate the configmap object
    configmap = client.V1ConfigMap(
        api_version="v1",
        kind="ConfigMap",
        data=dict(test=file_content),
        metadata=metadata
    )

    return configmap
......
```

**Comment by roycaihw** [comment]
@linuxvip The examples folder has an [example](https://github.com/kubernetes-client/python/blob/5b2e27c81b9d14acb71966461e883d5964e9776b/examples/create_deployment.py#L28-L29) that uses yaml file as input object for deployment creation. Also PR is welcome to help make our documentation better :)

I'd also suggest asking this kind of support question at the [kubernetes-client](https://kubernetes.slack.com/messages/C76GB48RK/) slack channel. 

@JonathanRRogers Thanks for explaining! Closing
