### ISSUE TITLE
Making the dependency adal optinal

### ISSUE THREAD

**Issue by atolj** [kubernetes-client/python#645]
Hi folks, 

I'm currently using the version 'kubernetes==8.0.0a1' and encountered that the ADAL dependency was added. This makes it more difficult to package a container image as it pulls additional dependencies and the image size increases. The following tweet illustrates it perfectly. 

https://twitter.com/try_except_/status/1029843228613402627 

It would be nice if the dependency is only added under extra_require. 

It has also the effect that, when I'm building an alpine image I have to install additional packages like [ build-base, libffi-dev, openssl-dev] or in another case [gcc build-base linux-headers python3-dev ca-certificates python3-dev libffi-dev libressl-dev], which bloats the container further.

I'm currently not sure where the dependency is used.

**Comment by roycaihw** [comment]
/assign @roycaihw 
cc @mbohlool @yliaog

**Comment by iamneha** [comment]
#668
