### ISSUE TITLE
kubectl  describe pods

### ISSUE THREAD

**Issue by 1032231418** [kubernetes-client/python#651]
hi:

Is there such an interface kubectl describe xxx?

**Comment by tomplus** [comment]
Describe what? :) Kubectl can do a lot of nice thing and it depends on a object. This library has methods which can be used to build such views but in several calls...

**Comment by 1032231418** [comment]
OK, understand.

**Comment by tomplus** [comment]
I've just noticed that you asked about `describe pod`. In this case [read_namespaced_pod](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#read_namespaced_pod) should be enough. Btw, you can check what kubectl does by adding a switch `-v9`.
