### ISSUE TITLE
make connection retry configurable via client configuration

### ISSUE THREAD

**Issue by zq-david-wang** [kubernetes-client/python#652]
If a cluster is down, the client would make a default 3 retry for each api call, which sometimes is unnecessary.  Adding a field to client configuration indicating how many retries should be used would help deal with this situation. 

I used following code and it works
```


`diff --git a/kubernetes/client/rest.py b/kubernetes/client/rest.py
index 4cdc83bb..173af930 100644
--- a/kubernetes/client/rest.py
+++ b/kubernetes/client/rest.py
@@ -79,6 +79,8 @@ class RESTClientObject(object):
         addition_pool_args = {}
         if configuration.assert_hostname is not None:
             addition_pool_args['assert_hostname'] = configuration.assert_hostname
+        if hasattr(configuration, "retries") and configuration.retries is not None:
+            addition_pool_args['retries'] = configuration.retries
 

```

**Comment by eddieparker** [comment]
/remove-lifecycle stale

This would be a nice feature to have - having a higher retry value in certain critical situations would be nice.

**Comment by roycaihw** [comment]
fixed in https://github.com/kubernetes-client/python/pull/780

/close
