### ISSUE TITLE
Bad Reqest Error when kind:Deployment and apiVersion:'apps/v1'

### ISSUE THREAD

**Issue by nik9839** [kubernetes-client/python#654]
kubernetes.client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Thu, 18 Oct 2018 22:21:22 GMT', 'Content-Length': '213'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the API version in the data (apps/v1) does not match the expected API version (extensions/v1beta1)","reason":"BadRequest","code":400}

**Comment by tomplus** [comment]
Which version of the library and Kubernetes do you use? Please compare these values with a [compatibility-matrix](https://github.com/kubernetes-client/python#compatibility-matrix).
