### ISSUE TITLE
[PROPOSAL] Add convenience function

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-client/python#66]
The client is very low level, it would be great to add a few convenience functions ala `kubectl` like:

* `kubectl run `
* `kubectl expose`

Right now starting a simple Pod is a bit "complex" and requires digging through the docs quite a bit to find the correct classes to instantiate. For example:

```
pod=client.V1Pod()
pod.metadata=client.V1ObjectMeta(name="busy box")

spec=client.V1PodSpec()

container=client.V1Container()
container.image="busybox"
container.args=["sleep", "3600"]
container.name="busybox"

spec.containers = [container]
pod.spec = spec

v1.create_namespaced_pod(namespace="default",body=pod)
```

It would be nice to have something like:

```
def run_pod(namespace, image):
    ....
    return v1.create_namespaced_pod(namespace=namespace, body)
```

**Comment by mbohlool** [comment]
These helper methods are definitely useful and I won't have objection adding them. However the approach is not scalable. I would also suggest we go the route of fluent interface that makes things like this easier like this:

```python
v1.create_namespaced_pod(
    client.V1Pod()
        .metadata_name("busy box")
        .container_image(0, "busybox")
        .container_args(0, ["sleep", "3600"])
        .container_name(0, "busy_box"))
```

This is not solid yet, just a quick thought. I will write a proposal for it.

**Comment by mbohlool** [comment]
I've had more thoughts on fluent interface, something like this look much better:

```python
 client.V1Pod()
     .edit_metadata()
          .name("busy box")
          .done()
     .add_container()
         .image("busybox")
         .args(["sleep", "3600"])
         .name("busy_box")
         .done()
    .create()
```

**Comment by sebgoa** [comment]
`add_metadata()` maybe, it is not really an _edit_ method.

**Comment by mbohlool** [comment]
Maybe, the difference is container is an array, metadata is not.

**Comment by djkonro** [comment]
@mbohlool, I just want to let you know that I have started working on this, so any notes you have in   mind would be welcomed.

**Comment by mbohlool** [comment]
Would be nice if you can share any design before implementation. I added "x-kubernetes-group-version-kind" and "x-kubernetes-action" in Kubernetes 1.7 spec and I was planning to use that to generate a set of kubernetes friendly object with actions on them based on the generated objects. Not a real design, but I was thinking to do have something like:

```python
from kubernetes import objects
...
pod = objects.V1Pod()   # objects are all in form of GroupVersionKind
or
pod = objects.for_gvk("", "v1", "pod")
# edit pod
pod.create()
```

**Comment by djkonro** [comment]
@mbohlool Sorry for the delayed response on [issue66](https://github.com/kubernetes-incubator/client-python/issues/66), I was traveling to Denver for GopherCon 2017 and I am still in Denver for the Conference but I would just like to make some progress on the issue by the time I return to Cameroon.

Initialy I was hoping to create helper classes for the resources, which would inherite the exiting classes and then implement helper functions for the fluent interface. Below is a sample for what I had in mind.

`class PodHelper(V1Pod):`

    `def edit_metadata(self, name=""):`
       ` #Create metadata object and set name`
        `return self`

    `def add_container(self, image="", args=[], name="")`
        `#Create container with provided details`
        `return self`
        
    `def create(self)`
        `#created pod`
        
We can then create a pod with

`client.PodHelper()`
    `.edit_metadata(name="")`
    `.add_container(image="", args=[], name="")`
    `.create()`
