### ISSUE TITLE
impossible to use client Configuration objects with different authorization

### ISSUE THREAD

**Issue by oliaboo** [kubernetes-client/python#663]
When trying to create few Configuration objects with different authorization tokens faced the following issue:
```
In [1]: import kubernetes.client                                                                                                            

In [2]: config1 = kubernetes.client.Configuration()                                                                                         

In [3]: config2 = kubernetes.client.Configuration()                                                                                         

In [4]: config1.api_key                                                                                                                     
Out[4]: {}

In [5]: config2.api_key                                                                                                                     
Out[5]: {}

In [6]: config1.api_key['authorization'] = 'zzzz'                                                                                           

In [7]: config2.api_key                                                                                                                     
Out[7]: {'authorization': 'zzzz'}

In [8]: id(config1.api_key)                                                                                                                 
Out[8]: 140012587374472

In [9]: id(config2.api_key)                                                                                                                 
Out[9]: 140012587374472
```
[TypeWithDefault](https://github.com/kubernetes-client/python/blob/39f833c20d53fa1d37e808d45661a4172824740b/kubernetes/client/configuration.py#L27-L38) metaclass makes Configuration work as a singleton.

**Comment by tomplus** [comment]
Yes, it's intentional. You can create new object using `config1 = type.__call__(Configuration)`.

**Comment by maratkomarov** [comment]
@tomplus What is the reason for this? It's not documented anywhere that `Configuration` is a singleton. Instead, i see [Configuration is not a singleton object anymore. Please use Configuraion.set_default to change default configuration](https://github.com/kubernetes-client/python/blob/3fb2be14e18d84edef094bbd908b6bb3e39aafe6/CHANGELOG.md#v400a1) in the changelog.

The suggested factory for `Configuration` doesn't look good. It uses the magic method `__call__`, that is for making objects callable, and not for be called directly by some client code. Why not having something like `kubernetes.client.new_config()` for the factory?

**Comment by tomplus** [comment]
Yes, it looks complicated. It's not a singleton but a metaclass construction. A feature - 'default configuration' makes it works as a singleton. This library wraps it and it'd better to use `config.new_client_from_config` like in this example: https://github.com/kubernetes-client/python/blob/master/examples/multiple_clusters.py but I'm not sure if it's a @oliaboo's case...

**Comment by maratkomarov** [comment]
@tomplus Thank you for the example. I think we're ready to close this issue.

**Comment by oliaboo** [comment]
@tomplus, thank you for the explanation! Closing the issue
