### ISSUE TITLE
what can I get 'kubectl describe node xxx '  by api?

### ISSUE THREAD

**Issue by HarveyJie** [kubernetes-client/python#670]
I want to get the node's resource  used look that by api,

` kubectl describe nodes 10.0.0.2`
```
Non-terminated Pods:         (14 in total)
  Namespace                  Name                                                   CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                                   ------------  ----------  ---------------  -------------
  k8s                        admin-sso-web-cloud-f55fc9bc-8ttzn                     500m (3%)     1 (6%)      256Mi (0%)       1Gi (3%)
  k8s                        application-center-cloud-6779cbf659-ljf86              1 (6%)        2 (12%)     512Mi (1%)       4Gi (12%)
  k8s                        csp-cloud-64c9646967-2x7l6                             1 (6%)        2 (12%)     512Mi (1%)       4Gi (12%)
  k8s                        h5-csms-cloud-795f4dd84d-9cf4r                         500m (3%)     1 (6%)      256Mi (0%)       1Gi (3%)
  k8s                        h5-lease-app-bdb65d757-85xgc                           1 (6%)        1 (6%)      1Gi (3%)         1Gi (3%)
  k8s                        h5-staff-cloud-59bc954cbb-76qwc                        500m (3%)     1 (6%)      256Mi (0%)       1Gi (3%)
  k8s                        jrocket2-bkofficer-cloud-66fb478458-4vbcn              1 (6%)        2 (12%)     512Mi (1%)       4Gi (12%)
  k8s                        marketing-management-h5-cloud-79cf9b475-l86sz          500m (3%)     1 (6%)      256Mi (0%)       1Gi (3%)
  k8s                        micro-back-investment-cloud-6d788b54c9-nf2kl           500m (3%)     1 (6%)      256Mi (0%)       1Gi (3%)
  k8s                        micro-finance-back-stage-cloud-85f5bcf846-d7z8v        1 (6%)        2 (12%)     512Mi (1%)       4Gi (12%)
  k8s                        micro-finance-back-stage-web-cloud-7df58c4f45-srsh8    500m (3%)     1 (6%)      256Mi (0%)       1Gi (3%)
  k8s                        partner-service-cloud-7db665d448-z8dz5                 1 (6%)        2 (12%)     512Mi (1%)       4Gi (12%)
  k8s                        price-engine-cloud-79cd7489c4-pkf7r                    1 (6%)        2 (12%)     512Mi (1%)       4Gi (12%)
  k8s                        user-center-cloud-c8878d84c-8wxrg                      1 (6%)        2 (12%)     512Mi (1%)       4Gi (12%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource  Requests   Limits
  --------  --------   ------
  cpu       11 (68%)   21 (131%)
  memory    6Gi (19%)  35Gi (111%)
Events:     <none>
```

**Comment by micw523** [comment]
Possible duplicate of #651

**Comment by tomplus** [comment]
You will need to get information about node ([read_node](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#read_node)) and get list of pods on this node ([list_namespaced_pod](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_namespaced_pod)). 

If you want to check what kubectl does you can increase log level by adding a switch `-v9`.

**Comment by amelbakry** [comment]
> You will need to get information about node ([read_node](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#read_node)) and get list of pods on this node ([list_namespaced_pod](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_namespaced_pod)).
> 
> If you want to check what kubectl does you can increase log level by adding a switch `-v9`.

But this will consume huge time, as you are looping for every node in the cluster and for every node looping for all pods inside it and containers inside pods to get resources and limits
while this is in mili seconds when using kubectl get node

**Comment by roycaihw** [comment]
> this will consume huge time

below is what kubectl does. You could use field selector to filter pods for one node. kubectl is faster in deserializing apiserver responses using protobuf

```
kubectl describe node 127.0.0.1 --v=9
GET https://localhost:6443/api/v1/nodes/127.0.0.1
GET https://localhost:6443/api/v1/pods?fieldSelector=spec.nodeName%3D127.0.0.1%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded
GET https://localhost:6443/api/v1/events?fieldSelector=involvedObject.uid%3D127.0.0.1%2CinvolvedObject.name%3D127.0.0.1%2CinvolvedObject.namespace%3D%2CinvolvedObject.kind%3DNode
```

**Comment by hacktmz** [comment]
res_pods = v1.list_pod_for_all_namespaces(pretty=True)
for i in res_pods.items:
    for j in i.spec.containers:
        if j.resources.requests or j.resources.limits:
            print(i.spec.node_name, j.name, j.resources)

**Comment by chiefzor** [comment]
v1 = client.CoreV1Api()

def convert_cpu(cpu_item):
    """
    Convert cpu
    @param cpu_item: [string]
    return cpu in mili cores (int)
    """
    try:
        if cpu_item.endswith("m"):
            return int(cpu_item.replace("m", ""))
        elif cpu_item.endswith("n"):
            return int(cpu_item.replace("n", "")) / (10**6)
        else:
            return int(cpu_item)*1024
    except Exception as ex:
        raise Exception("Unable to convert cpu_item", ex)

def convert_memory(memory_item):
    """
    Convert memory
    @param memory_item: [string]
    return memory in Mb (int)
    """
    try:
        if memory_item.endswith("Ki"):
            return int(memory_item.replace("Ki", ""))/1024
        elif memory_item.endswith("Mi"):
            return int(memory_item.replace("Mi", ""))
        elif memory_item.endswith("M"):
            return int(memory_item.replace("M", ""))
        elif memory_item.endswith("Gi"):
            return int(memory_item.replace("Gi", ""))*1024
        else:
            return int(memory_item)
    except Exception as ex:
        raise Exception("Unable to convert cpu_item", ex)


def calculate_nodes_resources():
    nodes_dict = {}
    res_pods = v1.list_pod_for_all_namespaces(pretty=True)
    for container in res_pods.items:
        for container_spec in container.spec.containers:
            if container_spec.resources.requests:
                container_cpu = container_spec.resources.requests.get('cpu') or 0
                container_mem = container_spec.resources.requests.get('memory') or 0
                if nodes_dict.get(container.spec.node_name):
                    if container_cpu:
                        new_cpu_requests = nodes_dict[container.spec.node_name].get('cpu_requests') or 0
                        nodes_dict[container.spec.node_name]['cpu_requests'] = \
                            new_cpu_requests + convert_cpu(container_cpu)
                    if container_mem:
                        new_mem_requests = nodes_dict[container.spec.node_name].get('mem_requests') or 0
                        nodes_dict[container.spec.node_name]['mem_requests'] = \
                            new_mem_requests + convert_memory(container_mem)
                else:
                    nodes_dict[container.spec.node_name] = {
                        'cpu_requests': 0,
                        'mem_requests': 0
                    }

                    if container_cpu:
                        nodes_dict[container.spec.node_name].update({
                            'cpu_requests': convert_cpu(container_cpu)
                        })
                    if container_mem:
                        nodes_dict[container.spec.node_name].update({
                            'mem_requests': convert_memory(container_mem)
                        })
    return nodes_dict
