### ISSUE TITLE
Setup.py will fail on Windows

### ISSUE THREAD

**Issue by micw523** [kubernetes-client/python#676]
This issue references #479, as it is a restriction on the current repo.
This repo uses symbolic link when managing the submodules, so that the folders in /kubernetes/base can be referenced in /kubernetes.
Windows does not have symbolic link, so Windows developers will have to manually copy the folders over after doing a --recursive clone.
This should be a simple enough fix in case someone wants to take a crack at it.

**Comment by jenetiks** [comment]
I'd like to take a stab at this but I have a few questions first. 
1. Would you be looking for a specific python version (2 vs 3) and more specifically, a subversion?
2. base/config and config/ are always in the same location?
3. run python setup.py install script from a specific directory?

**Comment by micw523** [comment]
@jenetiks
1. We should just look for python in the environment - although, we do support Python 2.7. The file setup.py though will be configured to handle this. Personally I don’t expect any developer to clone this repository with Python 2.6 or lower, but that might be up to debate.

2. When we clone submodule with git the folders in the /kubernetes/base is supposed to be symbolically linked in the /kubernetes directory. In Windows this is not done. For a Windows developer, we’ll need to have a script copying all the base/* folders into */. 

3. It probably will have to be run in a certain directory, likely the root of the repo or scripts. It needs to be documented well where it is supposed to be run though.

4. I’ll prefer to be a bat script. Although I don’t develop this repo in Windows, I do use Anaconda and python environments variables are only available under the Anaconda Prompt (cmd). 

Correct me if you have other thoughts. /cc @roycaihw

**Comment by Sai-Adarsh** [comment]
> /priority backlog

Hello @micw523 Gave a PR that solves the issue.

Added shell script to check python environment, prints the python version, copy files from /kubernetes/base to /kubernetes/ and finally runs python setup.py install.
