### ISSUE TITLE
Kubernetes REST API call

### ISSUE THREAD

**Issue by ori-n** [kubernetes-client/python#680]
I'm looking for a way to find a pod by name, and run REST call using python - I couldn't find such example in the docs. By kubectl I'm doing it using port forwarding and cURL.
Can I get any help? Thanks

**Comment by micw523** [comment]
Checkout https://github.com/kubernetes-client/python/blob/master/examples/exec.py

**Comment by ori-n** [comment]
I saw it before, and perhaps it is my misunderstanding - I don't want to run a command inside a container, but open port forwarding and do http rest call.I would like to catch the input if possible.

**Comment by micw523** [comment]
I don’t think opening port forward is supported. See #166
