### ISSUE TITLE
Key names don't match up with API

### ISSUE THREAD

**Issue by Velyks** [kubernetes-client/python#683]
The keys that are generated by kubernetes-client, both in the YAML response and using to_dict(), differ from the ones provided by the kubernetes API and all the tools that use it. It looks to mostly replace camelcase with underscores.

As I'm trying to use kubernetes-client to create diffs between exported YAML and the manifests in kubernetes this is causing me a lot of problems. Can we please have an option to use standard kubernetes naming for keys?

Some examples:
* `api_version` instead of `apiVersion`
* `creation_timestamp` instead of `creationTimestamp`
* `self_link` instead of `selfLink`
* `node_port` instead of `port` in Services

**Comment by micw523** [comment]
In one way I feel like what you need is a simple snake_case to camelCase parser;

In another way I went to check the JAVA client and saw their status output is the YAML/Json format that we can directly use. https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/models/V1Status.java

@roycaihw what are your thoughts?

**Comment by tomplus** [comment]
Names are consistent with the Python naming convention.

@Velyks Could you give an example where `to_dict()` or raw YAML content don't work for you? Do you use `_preload_content=False` to get the raw response?

**Comment by micw523** [comment]
Ah. I didn't realize ```_preload_content``` exists.

**Comment by AlexB138** [comment]
Is `_preload_content` documented somewhere? I'm not able to find an explanation of what it does. It may solve the problem.

I'm struggling with this convention as well. I'm using the client to do some templating. Loading a running deployment with the client loads it in the snake_case format. Merging that content with a partial deployment loaded from a CRD, and therefore in the standard camelCase format, seems needlessly difficult.

**Comment by gree-gorey** [comment]
@tomplus here is an example when it does not work. I want to use client to generate templates (yaml or json) and then use `kubectl apply`. But using:
```python
service = client.V1Service().to_dict()
```
generates this:
```yaml
api_version: null
kind: null
metadata: null
spec: null
status: null
```
which is invalid for `kubectl` as it should be:
```yaml
apiVersion: null
kind: null
metadata: null
spec: null
status: null
```
and I cannot use `_preload_content=False` in this case.

@micw523 we actually don't need snake_case to camelCase parser; all the objects already have `attribute_map` like this from `v1_service.py`:
```python
attribute_map = {
        'api_version': 'apiVersion',
        'kind': 'kind',
        'metadata': 'metadata',
        'spec': 'spec',
        'status': 'status'
}
```

so we only need either change `to_dict()` method or introduce new method which would use this map to generate valid k8s json.
Generally, I could use extent this class in my code and just add this method for the `Service` class for example, but method `to_dict()` is called recursively for nested objects, meaning that I would need to extend all possible classes form this client which is not that I would want to do :)

**Comment by gree-gorey** [comment]
#390 provides a workaround, but still this is a workaround

**Comment by Skillshot** [comment]
> #390 provides a workaround, but still this is a workaround

Just want to support the speaker on introducing a proper way of handling this issue.
