### ISSUE TITLE
rest request should squash URL

### ISSUE THREAD

**Issue by glbyers** [kubernetes-client/python#688]
In later versions of k8s, a request to //version is invalid, whilst a request to /version responds as expected. This appears to be an upstream bug, but it can be handled gracefully enough by simply "squashing" the URL path. ie.

```
scheme, netloc, path, params, query, fragment = urlparse(url)
urlunparse((scheme, netloc, re.sub(r'path, /+', '/', path), params, query, fragment))
```
Can it be handled gracefully here?

**Comment by roycaihw** [comment]
@glbyers Could you take a look at https://github.com/kubernetes-client/python-base/pull/45 to see if it solves your problem? 

Besides the host url containing trailing slash in kubeconfig file, do you have any other specific cases that cause invalid url in this client package?

**Comment by glbyers** [comment]
Thanks @roycaihw, I will test this tomorrow. It certainly looks like it should work around the issue (FWIW, I'd already removed the trailing / from my kubeconfig to get around this initially.
