### ISSUE TITLE
Uplift to swagger-codegen version 3.3.3

### ISSUE THREAD

**Issue by seaneagan** [kubernetes-client/python#692]
swagger-codegen v3.3.3:

https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.3.3

added this fix:

https://github.com/OpenAPITools/openapi-generator/pull/1387

which should fix #411 at least in cases where no async calls are made.

this also would address #684.

/cc @007 @micw523

**Comment by micw523** [comment]
I would be very careful to make this switch. As you see, the repo you mentioned is not swagger-codegen, but is called OpenApi generator. The repo is maintained by the original codegen authors.

The original codegen repo is now owned by Smartbear and I don’t know if k8s clients have received support from them. It’s difficult to say whether we could make the switch or not. It would be a little more feasible if the original repo contains the bug fix.

**Comment by seaneagan** [comment]
I see, I guess that's this PR that is needed then: https://github.com/swagger-api/swagger-codegen/pull/8061
