### ISSUE TITLE
ValueError("Invalid value for `match_expressions`, must not be `None`") when calling kubernetes.client.CoreV1Api().list_namespaced_pod

### ISSUE THREAD

**Issue by liwandaniel** [kubernetes-client/python#696]
When I try using the `kubernetes.client.CoreV1Api().list_namespaced_pod` method, I get the error:

```
  File "xxx/lib/python3.6/site-packages/kubernetes/client/models/v1_node_selector_term.py", line 49, in __init__
    self.match_expressions = match_expressions
  File "xxx/lib/python3.6/site-packages/kubernetes/client/models/v1_node_selector_term.py", line 72, in match_expressions
    raise ValueError("Invalid value for `match_expressions`, must not be `None`")
ValueError: Invalid value for `match_expressions`, must not be `None`
```
the way of calling method:

```
kubernetes.client.CoreV1Api().list_namespaced_pod(namespace="kube-system")
```

I'm just trying to list all pods for `kube-system` namespaces

I'm using Python 3.6 with Kubernetes 1.12.2 and kubernetes-client v5.0.0，and I've tried kubernetes-client v6.1.0

**Comment by micw523** [comment]
Please check the compatibility matrix - I suggest using v7 or higher for k8s 1.12.2

**Comment by liwandaniel** [comment]
ok,  I will try v7 or higher version, thx

**Comment by liwandaniel** [comment]
problem sovled by using version v8.0.0, thx! @micw523

**Comment by blazehu** [comment]
when i try using the  `kubernetes.client.CoreV1Api().list_pod_for_all_namespaces(watch=False)` method I get the error too:
```
ValueError: Invalid value for `match_expressions`, must not be `None`
```
I'm just trying to list all pods 

I'm using Python 2.7.5 with Kubernetes 1.13.2-2 and kubernetes-client v9.0.0
