### ISSUE TITLE
CoreV1Api().delete_namespaced_service() doesn't free node port immediately

### ISSUE THREAD

**Issue by aparamon** [kubernetes-client/python#703]
In my tests, I deploy a Kubernetes service on a pre-defined node port 30000, execute the test, and clean up via `CoreV1Api().delete_namespaced_service()` call. Apparently, the node port is not released immediately upon `CoreV1Api().delete_namespaced_service()`: the next test often fails to start with error on `CoreV1Api().create_namespaced_service()` call: *"Invalid value: 30000: provided port is already allocated"*.

`CoreV1Api().delete_namespaced_service()` should block until service is deleted and node port is de-allocated.

**Comment by tomplus** [comment]
This library provides very simple calls to interact with apiserver. It's full asynchronous and declarative approach. If you want to be sure that the service has been deleted by the controller, you'll have to try to read the service within a loop till you will get an error ~"object not found".

**Comment by aparamon** [comment]
I tried to use `watch.Watch().stream(CoreV1Api().list_namespaced_service, ...)` to catch `DELETED` event after `CoreV1Api().delete_namespaced_service()` call, but apparently the port is not always deallocated even by the time of `DELETED` event. Should that be considered a but in `kubeapi-server`?

**Comment by aparamon** [comment]
Reported upstream: https://github.com/kubernetes/kubernetes/issues/73140

**Comment by attlee-wang** [comment]
@aparamon  About this issuse，do you have any further conclusions?
