### ISSUE TITLE
Cannot create V1NetworkPolicy using create_from_yaml

### ISSUE THREAD

**Issue by trobert2** [kubernetes-client/python#704]
This error appears when trying to create a network policy from an existing configuration file.
Contents
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: ci
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress
```

Steps
```
>>> kubernetes.config.load_kube_config(config_file='/Users/trobert2/.kube/myconfing.yaml')
>>> k8s_client = client.api_client.ApiClient()
>>> api = utils.create_from_yaml(k8s_client, yaml_file='/Users/trobert2/extra/ci/0-default-deny-ingress.yaml', verbose=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/trobert2/extra/ci/venv/lib/python3.7/site-packages/kubernetes/utils/create_from_yaml.py", line 72, in create_from_yaml
    print("{0} created. status='{1}'".format(kind, str(resp.status)))
AttributeError: 'V1NetworkPolicy' object has no attribute 'status'
```

**Comment by micw523** [comment]
This is in fact not a problem on the YAML creater.

What you’ve run into is kubernetes-client/gen#52. If you don’t need to create many of these problem resources as seen in the other issue, you may comment out the empty array check as a temporary workaround.

**Comment by micw523** [comment]
On a separate look, it looks like that the response does not include a ```status``` field. Let me take an additional look on this. In the meantime, the network policy seems to be created. Calling ```verbose=False``` may help getting around the error.
/assign
