### ISSUE TITLE
Docs use incorrect python syntax in examples

### ISSUE THREAD

**Issue by melinath** [kubernetes-client/python#705]
See https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/BatchV1Api.md#create_namespaced_job

Example contains the line:
```
include_uninitialized = true
```

This is not python. Correct would be:
```
include_uninitialized = True
```

**Comment by micw523** [comment]
There are many of these - see the (incorrect) way of fixing it #640.

**Comment by govindKAG** [comment]
some indentation is broken too, I am pretty sure these have been autogenerated from the spec.

**Comment by roycaihw** [comment]
I think it's fixed in openapi-generator according to https://github.com/kubernetes-client/python/pull/738/files#diff-e11ea04965d89d48b1fde9336cdcfb8fR48
