### ISSUE TITLE
Service Must Include Port

### ISSUE THREAD

**Issue by JRascagneres** [kubernetes-client/python#709]
When creating a service spec it enforces you to define the port. This is not required when using either a yaml file or building from the command line as if not specified it will auto-generate one however the python client forces you to define one. Is there a workaround to ensure it is auto-generated?

**Comment by tomplus** [comment]
Could you provide the yaml definition of your service? As we can see here https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1ServiceSpec.md the attribute `ports` is optional.

**Comment by yadavsachin0995** [comment]
If you have a look at the model https://github.com/kubernetes-client/python/blob/ed18ea8d70846e273bdbeaf4d33676538d6aeabb/kubernetes/client/models/v1_service_spec.py#L77

you will find that the constructor defaults the ports to None. There probably is some issue with your implementation, can you share more details about how are you creating the spec object?
