### ISSUE TITLE
read_namespaced_pod_log with follow=True would hang if the pod has not log to yield yet

### ISSUE THREAD

**Issue by zq-david-wang** [kubernetes-client/python#716]
I am using following code to get pod logs
```
log = apiV1.read_namespaced_pod_log(
    name="default-http-backend-68f657df97-j2ncr",
    namespace="ingress-nginx",
    _preload_content=False,
    follow=True,
    #_request_timeout=1,
)
```
But when the pod has no log yet, the client would hang there forever without the request timeout.
The client need at least one byte to return an interactive object, but when there is no log yet, it would block the process. (request timeout would break the connection, not a valid solution.)

I tried adding a dummy byte before sending any logs in kubelet code, it could make the client return back a HTTPResponse object immediately. But kubenetes guys do think it is not a good idea. To be honest, it is not a good idea in my opinion either.
https://github.com/kubernetes/kubernetes/issues/72397
#72397

So is there any solution from client side?

**Comment by tomplus** [comment]
Thanks for reporting this. It'll be resolved by fix in the apiserver: https://github.com/kubernetes/kubernetes/pull/72575

**Comment by zq-david-wang** [comment]
close it since this is a apiserver issue.
