### ISSUE TITLE
`list_kube_config_contexts` cannot handle a KUBECONFIG env var with multiple config paths

### ISSUE THREAD

**Issue by dennis-tra** [kubernetes-client/python#723]
Hey there :)

When running
```python
from kubernetes import config

config.list_kube_config_contexts()
```
I get an error because my `KUBECONFIG` environment variable is configured with a **list** of paths to configuration files. E.g. `/path/one:/path/two`. This configuration is also covered in the documentation here:
https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable

I would have expected to get a list of contexts across all config files.

Cheers,
Dennis

**Comment by tomplus** [comment]
This feature has to be added to python-base repo, ref issue: kubernetes-client/python-base#62

**Comment by varac** [comment]
As far as I can judge, this feature has just been merged into  kubernetes-client/python-base: https://github.com/kubernetes-client/python-base/pull/94

**Comment by varac** [comment]
Works with https://github.com/kubernetes-client/python/releases/tag/v10.0.0a1
