### ISSUE TITLE
Configuring proxy_headers for rest authentication.

### ISSUE THREAD

**Issue by yadavsachin0995** [kubernetes-client/python#735]
I'm using Configuration object to be passed to the RESTClientObject class which, in it's constructor calls the proxy manager. The ProxyManager accepts the proxy_header attribute(defaults to None). Now the thing is that the Configuration object accepts the proxy_url attribute but misses out on proxy_headers due to which I'm not able to create a proxy configuration for authentication.

Here's the configuration file https://github.com/kubernetes-client/python/blob/ed18ea8d70846e273bdbeaf4d33676538d6aeabb/kubernetes/client/configuration.py#L48

And here goes the rest client https://github.com/kubernetes-client/python/blob/ed18ea8d70846e273bdbeaf4d33676538d6aeabb/kubernetes/client/rest.py#L91

**Comment by smileisak** [comment]
Same issue +1
