### ISSUE TITLE
models do not set kind or apiversion

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes-client/python#744]
The models do not set the `kind` and `apiVersion` when created:

```
In [12]: k8s.client.models.v1_service.V1Service()
Out[12]: 
{'api_version': None,
 'kind': None,
 'metadata': None,
 'spec': None,
 'status': None}
```

Both the kind and api version are known to the model so they should set it.

**Comment by splattner** [comment]
I see the same behaviour.

**Comment by micw523** [comment]
I would question if we could fix these. The constructors for such model objects are fairly dumb and are generated by a generator.

**Comment by splattner** [comment]
I think the PodList in the Response from the API Server does not include the `kind` & apiVersion fields in the items

GET https://kubernetes/api/v1/pods

```
{
    "kind": "PodList",
    "apiVersion": "v1",
    "metadata": {
        "selfLink": "/api/v1/pods",
        "resourceVersion": "127396924"
    },
    "items": [
        {
            "metadata": {   ...   },
            "spec": {   ...   },
            "status": {   ...   },
         }
   ]
  (...)
}
```

and therefore kind & apiVersion are none
So this is not a Problem with the Python Client.

But now the question, why is `kind` and `apiVersion` not included in the Response?

**Comment by juliantaylor** [comment]
This issue is about the models in the client and may indeed be a bit tricky to fix.
The consequences for api calls is issue https://github.com/kubernetes-client/python/issues/745
