### ISSUE TITLE
Cannot deserialize node object when one of its images has a null names list

### ISSUE THREAD

**Issue by PaulFurtado** [kubernetes-client/python#747]
When trying to call `client.read_node('ip-172-18-32-7.ec2.internal')`, a  ValueError is thrown:
```
ValueError: Invalid value for `names`, must not be `None`
```
it turns out this node had an image in its images list like:
```json
            {
                "names": null,
                "sizeBytes": 393898239
            }
```
which breaks this check: https://github.com/kubernetes-client/python/blob/cd411d2/kubernetes/client/models/v1_container_image.py#L76-L77

**Comment by inesusvet** [comment]
/remove-lifecycle stale

The issue is still present.
As a workaround, `_preload_content=False` param may be used but then the luxury of traversing the models objects from response should be restored by some `AttrDict`-like wrapper

**Comment by mgasner** [comment]
@inesusvet, can you expand on the work-around?

**Comment by inesusvet** [comment]
@mgasner as we are talking about [CoreV1API.list_node](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_node) method, it is possible to pass additional keyword argument `_preload_content=False` to it. In that case, the return value will be a dictionary version of the API's response, so additional wrapper as [AttrDict](https://github.com/bcj/AttrDict) may be helpful to keep the object-like interface of k8s API responses.
