### ISSUE TITLE
Quantity object

### ISSUE THREAD

**Issue by rmb938** [kubernetes-client/python#756]
Implement https://github.com/kubernetes/apimachinery/blob/master/pkg/api/resource/quantity.go

I would like the ability to parse resources into quantity objects and do actions on them (get their value, compare them, ect...)

**Comment by zou000** [comment]
We would like to have this feature too.

**Comment by igor47** [comment]
as recommended in [this medium article](https://medium.com/programming-kubernetes/building-stuff-with-the-kubernetes-api-part-3-using-python-aea5ab16f627) i found that i can get around this by using [Pint](https://pint.readthedocs.io/en/0.9/). you do have to add a `B` character to the unit description to make it parseable by pint:

```python
Q_ = pint.UnitRegistry().Quantity
HIGHMEM_THRESHOLD = Q_('13GB')
HIGHMEM_TOLERATION = {'key': 'highmem', 'effect': 'NoSchedule', 'operator': 'Exists'}

def get_tolerations(memory_request = '500Mi'):
    tolerations = []
    if Q_(memory_request + 'B') > HIGHMEM_THRESHOLD:
        tolerations.append(HIGHMEM_TOLERATION)
    return tolerations
```

**Comment by svenstucki** [comment]
For anyone else coming here via search - the API package now comes with a function to parse quantity information into regular Python `Decimal`s:
https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/quantity.py

```
>>> from kubernetes import utils
>>> utils.parse_quantity('15864Ki')
Decimal('16244736')
```

**Comment by jwenz723** [comment]
> For anyone else coming here via search - the API package now comes with a function to parse quantity information into regular Python `Decimal`s: https://github.com/kubernetes-client/python/blob/master/kubernetes/utils/quantity.py
> 
> ```
> >>> from kubernetes import utils
> >>> utils.parse_quantity('15864Ki')
> Decimal('16244736')
> ```

Thanks for this solution. One thing to note is that this solution is returning a decimal representation. With the go client it is common to retrieve the value by calling the [MilliValue()](https://github.com/kubernetes/apimachinery/blob/4524748494bf84fe99da72ca9a20e2666413ae49/pkg/api/resource/quantity.go#L788) function. To get the equivalent `MilliValue` value from the python `parse_quantity()` function you must multiply the returned value by 1000. So for example:


```bash
>>> from kubernetes import utils
>>> round(utils.parse_quantity('0.1')*1000)
100
>>> round(utils.parse_quantity('1')*1000)
1000
>>> round(utils.parse_quantity('1M')*1000)
1000000000
>>> round(utils.parse_quantity('1Mi')*1000)
1048576000
>>> round(utils.parse_quantity('1Gi')*1000)
1073741824000
>>> round(utils.parse_quantity('1m')*1000)
1
```
