### ISSUE TITLE
Get restart count value

### ISSUE THREAD

**Issue by redsox10** [kubernetes-client/python#758]
Hello!

Is there a way to get the restart count value of a pod? The RESTARTS column value of a specific pod (for example from `kubectl get pods` command)

Thank you.

**Comment by redsox10** [comment]
list_pod_for_all_namespaces() returns the restarts value per container.

**Comment by cy-lee** [comment]
Hi @redsox10 , could you share which attribute contain restart count, thank you.

**Comment by cy-lee** [comment]
I found it. it located on 
`pod.status.container_statuses[0].restart_count`
