### ISSUE TITLE
Changing the namespace for a .kube context programmatically

### ISSUE THREAD

**Issue by hmonteiro** [kubernetes-client/python#761]
I'm trying to change the configuration file from the API and I am struggling to mimic this simple kubectl command using the python API.
``kubectl config set-context $(kubectl config current-context) --namespace=<insert-namespace-name-here>``

**Comment by 1032231418** [comment]
@hmonteiro  [https://github.com/kubernetes-client/python/blob/master/kubernetes/doc](url)

https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/AppsV1beta2Api.md
[](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md)
Here you can find the interface document

**Comment by micw523** [comment]
I think you're trying to change the namespace you're in. I'm not sure we can do this directly, but you can set a variable of your namespace like 
```curr_namespace = 'this-namespace'```
and then call
```xxx_namespaced_yyy(namespace=curr_namespace)```
