### ISSUE TITLE
How to create and monitor a custom resource (SparkApplication)?

### ISSUE THREAD

**Issue by anselms** [kubernetes-client/python#763]
I'd like to submit and control a SparkApplication to a Kubernetes cluster programmatically.

A job definition job.yaml like this

apiVersion: sparkoperator.k8s.io/v1beta1
kind: SparkApplication
metadata:
  name: my-test
  namespace: default
spec:
  sparkVersion: "2.4.0"
  type: Python
...
runs without problems using kubectl apply -f job.yaml, but I cannot figure out whether and how I can use the kubernetes-client to start this job programmatically.

Does anyone know how to do this and could drop me a hint?

**Comment by micw523** [comment]
Try [this](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/ApiextensionsV1beta1Api.md#create_custom_resource_definition).


Although, if you're using k8s v1.10 or above, you may see an exception thrown. Generally you can ignore this error.

**Comment by anselms** [comment]
Thanks. I tried it, but 
```
body = kubernetes.client.V1beta1CustomResourceDefinition()
```
just throws with 
```
ValueError: Invalid value for `spec`, must not be `None`
```

for versions 8.0.1 and also for 9.0 beta1.

**Comment by micw523** [comment]
I know that will happen. However, if you use kubectl to see if you have created the CRD it should show that you have successfully created it.

**Comment by anselms** [comment]
Ahh, that is what you meant - thanks, will give it a go.

**Comment by anselms** [comment]
Got this working, the API I needed but had overlooked was `create_cluster_custom_object`.

Thanks!

**Comment by Teo920127** [comment]
I have the same problem, but my apiversion is  sparkoperator.k8s.io/v1beta2 . How can I solve this problem？

**Comment by MoShitrit** [comment]
@Teo920127 take a look at [that example](https://github.com/kubernetes-client/python/issues/1162#issuecomment-625857707) for listing custom resources.
And the documentation for managing and interacting with custom objects exists [here](https://github.com/kubernetes-client/python/blob/529bae376019d61806d0173e2d28722b995c894d/kubernetes/docs/CustomObjectsApi.md).
So for example, if you wish to create your custom resource at the cluster level, you can look at [this doc](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#create_cluster_custom_object), or alternatively, if you need it scoped to a namespace- [this one.](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#create_namespaced_custom_object).

In your case, the `apiVersion`, `group` and `plural` _should_ work in this form:
```python
(group="k8s.io", version="v1beta2", plural="sparkoperators")
```

**Comment by Teo920127** [comment]
I was very glad to receive your reply. And I solved the problem according to your guidance. Thank you very much !~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubernetes-client/python"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月23日(星期二) 晚上10:37
收件人:&nbsp;"kubernetes-client/python"<python@noreply.github.com&gt;;
抄送:&nbsp;"　　 ｎ．"<296554690@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [kubernetes-client/python] How to create and monitor a custom resource (SparkApplication)? (#763)





 
@Teo920127 take a look at that example for listing custom resources.
 And the documentation for managing and interacting with custom objects exists here.
 So for example, if you wish to create your custom resource at the cluster level, you can look at this doc, or alternatively, if you need it scoped to a namespace- this one..
 
In your case, the apiVersion, group and plural should work in this form:
 (group="k8s.io", version="v1beta2", plural="sparkoperators")
