### ISSUE TITLE
k8s config tmp files cleared by centos

### ISSUE THREAD

**Issue by xxxxczxc** [kubernetes-client/python#765]
k8s-client created some temp file in directory /tmp when process start, but centos will clear files that created over 10 days ago in this directory. After the temp files cleared, if my process was disconnected from k8s somehow, it will return 'No such file or directory' when call k8s interface.

> MaxRetryError: HTTPSConnectionPool(host='xxx.xxx.xxx.xxx', port=xxxx): Max retries exceeded with url: /api/v1/namespaces/canary/resourcequotas/canary-compute-resources (Caused by SSLError(IOError(2, 'No such file or directory'),))

It seems like that kubernetes-client will read the temp file when try to reconnect to k8s.  
So I call load_kube_config() when catched the Exception above, try to create temp again to recover, but return error.

>   File "/var/deploy/venv/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 334, in _load_cluster_info
    file_base_path=self._config_base_path).as_file()
  File "/var/deploy/venv/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 104, in as_file
    raise ConfigException("File does not exists: %s" % self._file)
ConfigException: File does not exists: /tmp/tmpux9Zef

Dose kubernetes-client has an interface to recreate temp files or refresh temp files periodically?
Or is there any other way to solve this problem?

**Comment by pigletfly** [comment]
there is a discussion https://github.com/kubernetes-client/python-base/pull/38
