### ISSUE TITLE
Question before implementing PR regarding keep-alive connections

### ISSUE THREAD

**Issue by lalo** [kubernetes-client/python#768]
I'm interested in adding a config to enable keep-alive on the connections with urllib3 connection pools. I see that this dependency is brought by the swagger-codegen -> https://github.com/kubernetes-client/python/blob/master/kubernetes/client/configuration.py#L43

If I contribute this to the swagger-codegen project, this project actively moves the dependency to the latest right? Also, is this the right approach or am I missing something else?

Thanks

**Comment by tomplus** [comment]
Hi. We are moving from swagger-codegen to openapi-generator. You can track it here: https://github.com/kubernetes-client/gen/issues/93. It'd be better to add this feature to [openapi-generator](https://github.com/OpenAPITools/openapi-generator).

**Comment by wing328** [comment]
@lalo May I know if you've time to submit a PR for OpenAPI Generator to enable keep-alive in the Python client?

**Comment by lalo** [comment]
If it's urgent you should go ahead and implement it, if not I have some personal time constraints and can't prioritize this high enough (maybe in a week or 2).

**Comment by wing328** [comment]
Please take your time and let us know if you need help with the PR. Thanks for your contribution in advance.

**Comment by lalo** [comment]
After taking a second look, it seems that there is no need to modify OpenApi generator, since the request method already has a way to modify the headers. https://github.com/kubernetes-client/python/blob/6d4587e18064288d031ed9bbf5ab5b8245460b3c/kubernetes/client/rest.py#L118

My take is that we should/could be able to set it to ```'connection': 'keep-alive'```, thoughts?

**Comment by wing328** [comment]
@lalo Sure, we can use this method for the time being.
