### ISSUE TITLE
apiserver http tls handshake error from :eof caused by urllib3

### ISSUE THREAD

**Issue by larryck** [kubernetes-client/python#772]
I used the kubernetes client to interact with my kuberentes cluster (v1.13.1, installed with kubeadm) and got **"MaxRetryError,  HTTPSConnectonPool Max retries exceeded with url, Caused by ProtocoError(Connection aborted, error(0, Error)))"**.  I checked apiserver log and found "http: TLS handshake error from : EOF"

The operating system I use is CentOS Linux release 7.3.1611 (Core), and the kubernetes client is installed with "pip install kubernetes" which is Version: 8.0.1.  Urllib3 is urllib3-1.24.1.

python command "from kubernetes import client, config" cause "'NoneType' object is not callable" in <function _removeHandlerRef at" error.

I downgraded urllib3 to 1.15.1 and both error disappered.

**Comment by 1032231418** [comment]
[root@192 test_script]# pip list  |grep urllib3 
urllib3 (1.23)

example：

    configuration = client.Configuration()
    setattr(configuration, 'verify_ssl', False)
    client.Configuration.set_default(configuration)
    configuration.host = ApiHost
    configuration.verify_ssl = False
    configuration.debug = True
    configuration.api_key = {"authorization": "Bearer " + ApiToken}
    client.Configuration.set_default(configuration)
