### ISSUE TITLE
patch_namespaced_pod not allowing pod label update. 

### ISSUE THREAD

**Issue by vsoutherner** [kubernetes-client/python#774]
When patching with the kubectl binary the patch is applied using this command;
kubectl patch po -n kube-system kube-keepalived-vip-mn9lp -p '{"metadata":{"labels":{"vip-holder":"true"}}}'

When patching using the python using this command;
client.CoreV1Api().patch_namespaced_pod('kube-keepalived-vip-mn9lp', 'kube-system', {"metadata":{"labels":{"vip-holder":"false"}}}, async_req=False)

I receive the following error. 
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 07 Mar 2019 20:56:14 GMT', 'Content-Length': '657', 'Content-Type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"kube-keepalived-vip-mn9lp\" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[0]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used spec.containers[1].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]","reason":"Forbidden","details":{"name":"kube-keepalived-vip-mn9lp","kind":"pods"},"code":403}

If I first try to pull the object using read_namespaced_pod and then modifying the labels I get the same error. The service account running the code has a cluster role binding to a cluster role that would allow patching or updating pods.

**Comment by 1032231418** [comment]
Is the interface not authorized

example:


kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io

**Comment by 1032231418** [comment]
You can find the answer from here.         [ https://github.com/kubernetes-client/python/blob/master/examples/in_cluster_config.py](url)

**Comment by vsoutherner** [comment]
It has permission 
- apiGroups:
 - ""
resources:
- pods
verbs:
- get
- list
- patch
- update
