### ISSUE TITLE
configuration.api_key['Authorization'] = 'xxx' takes no effects.

### ISSUE THREAD

**Issue by adolli** [kubernetes-client/python#775]
The configuration for authorization by bearer token is a little bit confused when the key of `configuration.api_key` is not all letter in lower cases.

I've try the following code to access my k8s API outside the cluster, but always got 403 as a system:anonymous user. I am very sure my token have such privileges because I can use it via `curl`.
```py
configuration.api_key['Authorization'] = 'Bearer ...'
```

After I diving into the code of `class Configuration` I found that it accept only the lowercases `'key': 'authorization'`.
https://github.com/kubernetes-client/python/blob/fcda6fe96beb21cd05522c17f7f08c5a7c0e3dc3/kubernetes/client/configuration.py#L216-L231

Why I use `Authorization` without checking out the examples or docs is that in usual cases the HTTP headers are capitalized its first letter. In addition, HTTP request headers are case insensitive in the standard. I think this should trasnform the case in this lib.

Thx!

**Comment by 1032231418** [comment]
ApiToken = "xxxxx"								#ApiToken
configuration = client.Configuration()
setattr(configuration, 'verify_ssl', False)
client.Configuration.set_default(configuration)
configuration.host = "https://xxxx:6443"			#ApiHost
configuration.verify_ssl = False
configuration.debug = True
configuration.api_key = {"authorization": "Bearer " + ApiToken}
client.Configuration.set_default(configuration)

**Comment by adolli** [comment]
@1032231418 thank u for your example. I can understand the reason. I just suggest that the key for the `configuration.api_key` should be case insensitive.
