### ISSUE TITLE
swagger codegen error message is not easy to read

### ISSUE THREAD

**Issue by jsollom** [kubernetes-client/python#778]
When using the swagger codegen to generate code from an OpenAPI spec, it produces an error message when a regular expression has been used to limit which characters can be used for a value.

The error reads "must be a follow pattern or equal to <insert your regular expression here>".  I am objecting to the wording of 'follow pattern'.  What is a 'follow pattern'?  My guess is that this was supposed to say, 'must follow a pattern or be equal to <...>'.  But that is only a guess.

The code is here.
https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/petstore_api/models/format_test.py#L273

**Comment by micw523** [comment]
Ummmm... I think it’s probably better if you open the issue in the swagger-codegen repo?

**Comment by jsollom** [comment]
Yes, my bad.  I should have filed it under swagger-codegen. Refiled here: https://github.com/swagger-api/swagger-codegen/issues/9256

Closing this issue.
