### ISSUE TITLE
yaml.load warning while running the config.load_kube_config()

### ISSUE THREAD

**Issue by prafull01** [kubernetes-client/python#787]
I have been getting following error whenever I am running config.load_kube_config()

`/usr/lib/python3.6/site-packages/kubernetes/config/kube_config.py:480:` YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict=yaml.load(f),
/usr/lib/python3.6/site-packages/kubernetes/config/kube_config.py:480: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict=yaml.load(f),`

**Comment by micw523** [comment]
I believe that this has been fixed in the current master branch via
#719 and
python-base/#111
