### ISSUE TITLE
api.list_namespaced_pod crashes gunicorn worker.  

### ISSUE THREAD

**Issue by njfix6** [kubernetes-client/python#794]
**What happened**:
When I use api.list_namespaced_pod in kubernetes, it crashes my gunicorn worker when I made the request. I'd say about 80% of the time it would crash it and then 20% of the time it would make the request ok. 

**What you expected to happen**:
The request should return properly every time. When I use list list_namespaced_pod_with_http_info it work perfect everytime:
```
api = client.CoreV1Api()
resp = api.list_namespaced_pod_with_http_info(namespace)
```

**How to reproduce it (as minimally and precisely as possible)**:
Running a gunicorn app with an endpoint that pings kubernetes with:
```
api = client.CoreV1Api()
resp = api.list_namespaced_pod(namespace)
```
Gunicorn run statement:
pipenv run gunicorn -b unix:/sock/gunicorn.sock -w 2 --threads=16 --worker-class=gevent --worker-connections=1000 --chdir ./sandbox_admin --access-logfile - --error-logfile - runweb:app --log-level=DEBUG

**Anything else we need to know?**:

**Environment**:
- Cloud provider or hardware configuration:
AWS
- OS (e.g: `cat /etc/os-release`):
kubernetes version: 1.10.11
Base image: python:3.6-alpine
- Install tools:
python kubernetes cli: 8.0.0
gunicorn: 19.9.0
- Others:

**Comment by tomplus** [comment]
I think this library may have a problem with working with gevent. Could you check how it works with different `--worker-class`?

**Comment by njfix6** [comment]
@tomplus  Would you recommend any? I will try "sync" otherwise.

**Comment by njfix6** [comment]
I just tested it and it seems to be working with "sync". I guess it only is broken for gevent? Very weird.
