### ISSUE TITLE
Body in delete methods required but marked as optional in documentation

### ISSUE THREAD

**Issue by maxbischoff** [kubernetes-client/python#798]
## What happened

In the [API documentation of the python client for delete_namespaced_pod](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#delete_namespaced_pod) the body parameter is marked as optional. Not setting the body parameter currently results in `TypeError: delete_namespaced_pod() missing 1 required positional argument: 'body'`.

The same behaviour can be observed for other delete methods, I tested `apps_v1_api.delete_namespaced_deployment`, `core_v1_api.delete_namespaced_secret`, and `core_v1_api.delete_namespaced_service`.

## What you expected to happen

As `kubectl delete` also does not require anything besides namespace and name, I would expect the body argument to be optional, as documented. Either way, I'd expect the documentation to match the implementation.

## How to reproduce it (as minimally and precisely as possible)

Try to call `delete_namespaced_pod` without body argument:

```python
from kubernetes import client, config
config.load_kube_config()
core_v1_api = client.CoreV1Api()
core_v1_api.delete_namespaced_pod(name="xyz", namespace="default")
```

Observe `TypeError: delete_namespaced_pod() missing 1 required positional argument: 'body'`.

Now call it with body argument:

```python
from kubernetes import client, config
config.load_kube_config()
core_v1_api = client.CoreV1Api()
core_v1_api.delete_namespaced_pod(name="xyz", namespace="default", body=client.V1DeleteOptions())
```

Observe, that pod is deleted (or API exception raised, if pod doesn't exist).

## Environment

```bash
$ python --version
Python 3.6.7
```

```bash
$ pip list | grep kubernetes
kubernetes        8.0.1
```

**Comment by tomplus** [comment]
This parameter is optional since Kubernetes v1.13, please upgrade your library to v 9.0.0.

**Comment by maxbischoff** [comment]
Upgrading fixed my issue, thank you
