### ISSUE TITLE
Kubernetes stream getting stuck/loosing events after some time

### ISSUE THREAD

**Issue by Ashutosh-Tripathy** [kubernetes-client/python#801]
I have written a service to look for pod events. Initially It is working fine and successfully detecting pod disruption and scheduling, but after sometime stream is loosing the pod and getting stuck in case of pod disruption(voluntary or involuntary).

```
while True:
    try:
        w = watch.Watch()

        for evt in w.stream(api.list_namespaced_pod,
                            namespace=mon_svc_namespace,
                            label_selector=labels,
                            timeout_seconds=60):

            obj = evt['object']
            if (evt['type'] in ('ADDED', 'MODIFIED')):
                ........
                ........
                ........

    except ApiException:
        logger.error("Got ApiException during watch. Retrying.")
        time.sleep(3)

```

I just want to discard current watch and create new one after fixed amount of time (even when steam is stuck and not returning any event).  Any suggestion?

python client version=7.0.0
kubernetes version= 1.12

**Comment by QqqRy** [comment]
any update?
