### ISSUE TITLE
List pods for a set of namespaces.

### ISSUE THREAD

**Issue by amitection** [kubernetes-client/python#802]
The API doc mentions two methods 

```
list_namespaced_pod
list_pod_for_all_namespaces
```
Is there a way to get pods for a set of namespaces?

I am trying to create a `Watch()` for pods in a set of namespaces
```
import kubernetes as k8s

core_api = k8s.client.CoreV1Api()
watcher = k8s.watch.Watch()
stream = watcher.stream(core_api.list_namespaced_pod, namespace=some_ns, timeout_seconds=5,  resource_version=rv, watch=True)
```

**Comment by johscheuer** [comment]
Probably the easiest way is to use a `field-selector`, e.g.: `kubectl get pods --all-namespaces --field-selector=metadata.namespace==kube-system` the same parameter is available in the Python client: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_namespaced_pod to use multiple `field-selector` just concat them with a `,`.
