### ISSUE TITLE
V1beta1Ingress is missing in 10.0.0a1 and break backward compatibility

### ISSUE THREAD

**Issue by zq-david-wang** [kubernetes-client/python#808]
There are now two new kind of ingress object in 10.0.0a1, NetworkingV1beta1Ingress(NetworkingV1beta1Api). ExtensionsV1beta1Ingress(ExtensionsV1beta1Api, which is deprecated).

but V1beta1Ingress does not exist.

**Comment by sayarg** [comment]
Hi all, we have just hit this issue when upgrading to 10.0.1. We had no way of introducing 10.0.1 without breaking our platform, so had to add logic to use different objects based on the version.

I know there's a lot of work and thought that goes into the project and the team is working hard to keep up with changes in kubernetes itself and you phase changes in/out, however here it's a pity that the feedback was missed. There's a clear break in the rename of the old objects, see:

https://github.com/kubernetes-client/python/blob/release-9.0/kubernetes/client/__init__.py#L444

vs

https://github.com/kubernetes-client/python/blob/release-10.0/kubernetes/client/__init__.py#L50

It's all done for us, so all good here. I was going to raise an issue as a feedback item mostly, then saw this issue already open and thought I'd add my thoughts too.
