### ISSUE TITLE
How to create docker-registry type secret using python client

### ISSUE THREAD

**Issue by adityabyreddy74** [kubernetes-client/python#810]
The example at https://github.com/kubernetes-client/python/blob/master/examples/notebooks/create_secret.ipynb shows how to create generic secrets...

How to create a docker-registry type secret?

**Comment by tomplus** [comment]
This type of secret is a secret with one field named `.dockerconfigjson` and value `{"auths":{"yourprivateregistry.com":{"username": "janedoe","password": "xxxxxxxxxxx","email":  "jdoe@example.com","auth": "c3R...zE2"}}}`. `auth` is base64 encoded and the whole value is encoded too.
More information: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#inspecting-the-secret-regcred

**Comment by adityabyreddy74** [comment]
@tomplus Thanks. That works :)

I was wondering if there is any straight way to create docker-registry type secret through python client.

**Comment by gotpist1** [comment]
I am also struggling with this. Would be a shame if i have to use subprocess instead.

**Comment by a-atalla** [comment]
This is my approach of doing it 
https://gist.github.com/a-atalla/fc3b7b14a54109374a5c89c72047bb2a
[create_regcred.py](https://gist.github.com/a-atalla/fc3b7b14a54109374a5c89c72047bb2a)
