### ISSUE TITLE
read_namespaced_pod_log reformats the output

### ISSUE THREAD

**Issue by urandom** [kubernetes-client/python#811]
With 8.0.1 (and tested with 9.0.0) read_namespaced_pod_log reformats the log so that each double quite is changed to a single quote, so that the following:
```
{"key":"value"}
```
changes to:
```
{'key':'value'}
```
which is a real problem when trying to parse that output as json.

For reference, `kubectl logs` returns the correct string without any reformatting.

Just in case, the k8s version is:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"archive", BuildDate:"2019-01-2
9T23:14:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T
16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by frederik-b** [comment]
I got a related problem with
```python
stream(
    v1.connect_get_namespaced_pod_exec,
    my_name,
    'default',
    command=['/bin/sh', '-c', 'echo $MY_VAR'],
    stderr=True,
    stdin=False,
    stdout=True,
    tty=False,
)
```
returning false json with wrong quotes
while the content of myvar equals {"foo":"bar"}
it returns {'foo':'bar'}

it does behave differenlty if the json contains quotes inside string values however

**Comment by shurikk** [comment]
the issue is here https://github.com/kubernetes-client/python/blob/master/kubernetes/client/api_client.py#L245 trying `json.loads()` without consulting `response_type`

**Comment by shurikk** [comment]
a workaround for this issue is to pass `_preload_content=False` to `read_namespaced_pod_log` like:

```python
client.CoreV1Api().read_namespaced_pod_log(
    name="pod-name",
    namespace="namespace-name",
    container="container-name",
    _preload_content=False,
) 
.data
```

**Comment by chaudum** [comment]
> I got a related problem with
> 
> ```python
> stream(
>     v1.connect_get_namespaced_pod_exec,
>     my_name,
>     'default',
>     command=['/bin/sh', '-c', 'echo $MY_VAR'],
>     stderr=True,
>     stdin=False,
>     stdout=True,
>     tty=False,
> )
> ```
> 
> returning false json with wrong quotes
> while the content of myvar equals {"foo":"bar"}
> it returns {'foo':'bar'}
> 
> it does behave differenlty if the json contains quotes inside string values however

@frederik-b We had the same problem with a `curl` command that outputs a JSON string. We solved it by adding a random character sequence at the end, so it is not JSON serializable any more, and removed it after receiving the response.
In your case, the `command` argument would be `["echo", "${MY_VAR}<EOF>" ]`, which returns `{"foo":"bar"}<EOF>`. Since you know the terminating character sequence, you can strip it thereafter.

I know, it's somehow a bad workaround ...

**Comment by mschmidt1208** [comment]
I ran into the same problem and found a solution:

1. add the parameter `_preload_content=False,` to the stream call -> you receive a WSClient object
2. call `run_forever(timeout=10)` on it 
3. Then you get the correct and unformatted string with `.read_stdout()`

For example:
`wsclient_obj = stream(v1.connect_get_namespaced_pod_exec, m
                        y_name,
                        'default',
                        command=['/bin/sh', '-c', 'echo $MY_VAR'],
                        stderr=True,
                        stdin=False,
                        stdout=True,
                        tty=False,
                        _preload_content=False
                    )
wsclient_obj.run_forever(timeout=10)
response_str = wsclient_obj.read_stdout()
`

**Comment by mschmidt1208** [comment]
I ran into the same problem and found a solution:

1. add the parameter _preload_content=False, to the stream call -> you receive a WSClient object
2. call run_forever(timeout=10) on it
3. Then you get the correct and unformatted string with .read_stdout()
For example:
```python
wsclient_obj = stream(v1.connect_get_namespaced_pod_exec, m
                        y_name,
                        'default',
                        command=['/bin/sh', '-c', 'echo $MY_VAR'],
                        stderr=True,
                        stdin=False,
                        stdout=True,
                        tty=False,
                        _preload_content=False
                    )
wsclient_obj.run_forever(timeout=10)
response_str = wsclient_obj.read_stdout()
```
