### ISSUE TITLE
How do you get exit code connect_get_namespaced_pod_exec ?

### ISSUE THREAD

**Issue by oz123** [kubernetes-client/python#812]
Currently I have to simply do this:

```
        response = stream(self.api.connect_get_namespaced_pod_exec,
                          podname, 'kube-system',
                          command=exec_command,
                          stderr=False, stdin=False,
                          stdout=True, tty=False)

        if not response:
            do_something__()
```

However, I can't get the error code, or the stderror.
Looking at the source code I don't see an easy way.

**Comment by tomplus** [comment]
@oz123 The error code arrives in the channel number 3 (error-channel) but it is not exposed by the stream() method.

As a workaround you can use:
```
client = stream(api.connect_get_namespaced_pod_exec,
                "myapp-78898448f4-pgnfl",
                "default",
                command=["false"],                  # <<< "false" returns with exit code = 1
                stderr=True, stdin=False,
                stdout=True, tty=False,
                _preload_content=False)

client.run_forever(timeout=60)
err = client.read_channel(ERROR_CHANNEL)

pprint(yaml.load(err))
```

and you should get
```
{'details': {'causes': [{'message': '1', 'reason': 'ExitCode'}]},
 'message': 'command terminated with non-zero exit code: Error executing in '
            'Docker Container: 1',
 'metadata': {},
 'reason': 'NonZeroExitCode',
 'status': 'Failure'}
```

I'm going to add a method to get it in more convenient way.

**Comment by phracek** [comment]
CC @TomasTomecek

**Comment by roycaihw** [comment]
fixed by https://github.com/kubernetes-client/python-base/pull/160

/close

**Comment by sunchill06** [comment]
@tomplus 

When I run this as

resp = stream(v1.connect_get_namespaced_pod_exec, podName, namespace, command=exec_command, stderr=True, stdin=False, stdout=True, tty=False, _preload_content=preloadContent)

resp.run_forever(timeout=5)
print(resp.readline_channel(1))

Response:
**None**

However, print(resp.read_channel(1)) gives me proper output.

Any pointers why?
