### ISSUE TITLE
create_namespaced_pod doesn't create a Pod with annotations.

### ISSUE THREAD

**Issue by Skazzino** [kubernetes-client/python#813]
Hi, I'm trying to create a simple pod with some annotations for it (I'm using library's latest version pulled with pip).
The code I'm using is this one:
```python
definition = {
            "apiVersion": "v1",
            "kind": "Pod",
            "metadata": {
                "annotations:": {
                    "key1": "value1",
                    "key2": "value2"
                },
                "name": self.name, # Defined in the class
            },
            "spec": {
                "containers": [{
                    "name": "container-test",
                    "image": "IMAGE_URL"
                    "tty": True,
                    "stdin": True,
                    "volumeMounts": [{
                        "name": "volume",
                        "mountPath": "/dir/files",
                        "subPath": "something"
                    }],
                    "imagePullPolicy": "IfNotPresent",
                }],
                "initContainers": [{
                    "name": "startup",
                    "image": "busybox",
                    "imagePullPolicy": "IfNotPresent",
                    "command": ["/bin/sh"],
                    "args": [], #SOME STUFF IN HERE
                }],
                "volumes": [{
                    "name": "volume",
                    "emptyDir": {}
                }]
            }
        }

# self.core_api is created in class constructor
# self.core_api = core_v1_api.CoreV1Api()
self.core_api.create_namespaced_pod(body=definition, namespace="default")
```

However, when the pod is Running, I cannot see any of the annotations that I've put in the pod definition as you can see here:
![immagine](https://user-images.githubusercontent.com/10586339/56083981-9dc4c080-5e2c-11e9-991a-757a46576265.png)

If I create the pod from a .yaml file using `kubectl create -f file.yaml`, annotations are properly added.

Is there any reason why this is happening? I tried every combination possibile, like moving the annotations before the name, or trying other annotation keys, but nothing.

Thanks in advance.

**Comment by tomplus** [comment]
`"annotations:"` < your key ends with the colon and it's silently ignored by the api-server...

**Comment by Skazzino** [comment]
Oh my God, didn't notice that typo for a week... Thanks a lot @tomplus. Now everything works!
