### ISSUE TITLE
list_namespaced_custom_object reruns builtin_function_or_method' object is not iterable

### ISSUE THREAD

**Issue by luisdavim** [kubernetes-client/python#818]
this is the code I'm using:

```python
#....
config.load_incluster_config()
crds = client.CustomObjectsApi()
#....
log.info('Looking for finished jobs')
try:
    jobs = crds.list_namespaced_custom_object(
        'test.example.com', 'v1', init.cfg['namespace'], 'daemonjobs', watch=False)
    log.debug(jobs)
    for job in jobs.items:
        log.debug(job)
        jobname = job.metadata.name
        jobstatus = job.status.conditions
        for condition in jobstatus:
            if condition.type.lower() == 'complete' and condition.status.lower() == 'true':
                log.info('Cleaning up Job: %s' % jobname)
                api_response = crds.delete_namespaced_custom_object(
                    'test.example.com', 'v1', init.cfg['namespace'], 'daemonjobs', jobname, job)
except ApiException as e:
    log.warn('Exception when calling kubernetes API: %s' % e)
#...
```
the `log.debug(jobs)` doesn't output anything. Am I doing anything wrong?

and I do have objects of that type in the namespace that I'm using and even if I didn't it should return an empty iterable object right?

**Comment by cometta** [comment]
I can't find method list_namespace_job . Does it exist?  @luisdavim , where did you get values for 'group' and 'plural' ? I can't find it in kubectl describe <job-name> .

**Comment by luisdavim** [comment]
The method I'm reporting on is `list_namespaced_custom_object`

**Comment by jcmcken** [comment]
I saw this issue by chance and wonder if it's related to one I submitted, #1140. 

In my testing, the only way to get DEBUG level logs to appear when using your own ``Configuration`` object is to set ``debug`` to ``True``, e.g. ``config = Configuration(); config.debug = True``.

You can always insert a ``import pdb; pdb,set_trace()`` right after you assign ``jobs`` to set a breakpoint and examine that variable to make sure it's not an empty list

**Comment by axelinux** [comment]
@luisdavim Hi, I had the same issue, it returns a tuple which contains dictionary, your code should be like this :

```
#....
config.load_incluster_config()
crds = client.CustomObjectsApi()
#....
log.info('Looking for finished jobs')
try:
    jobs = crds.list_namespaced_custom_object(
        'test.example.com', 'v1', init.cfg['namespace'], 'daemonjobs', watch=False)
    log.debug(jobs)
    for job in list(jobs.items())[1][1]:
        log.debug(job)
        jobname = job['metadata']['name']
        jobstatus = job['status']['conditions']
        for condition in jobstatus:
            if condition['type'].lower() == 'complete' and condition['status'].lower() == 'true':
                log.info('Cleaning up Job: %s' % jobname)
                api_response = crds.delete_namespaced_custom_object(
                    'test.example.com', 'v1', init.cfg['namespace'], 'daemonjobs', jobname, job)
except ApiException as e:
    log.warn('Exception when calling kubernetes API: %s' % e)
```

**Comment by erkanerol** [comment]
Note that root cause of this error is  to use `jobs.items` instead of `jobs.items()`

**Comment by tsunamishaun** [comment]
I ran into this trying to use `list_namespaced_custom_object()` and indeed the behavior is different compared to non-custom resource types. I was expecting the examples (at least iterating results) to be interchangeable between custom and non-custom resources.
