### ISSUE TITLE
V1PodSpec have to pass containers in init

### ISSUE THREAD

**Issue by oldani** [kubernetes-client/python#821]
When initalizing `client.V1PodSpec()` containers must be passed if not it raises:

`ValueError("Invalid value for containers, must not be None")`

This happends de to [this](https://github.com/kubernetes-client/python/blob/master/kubernetes/client/models/v1_pod_spec.py#L142) 

One should be able to to initialize the pod spec and add containers later

**Comment by tomplus** [comment]
Yes, swagger is very strict and doesn't allow to create object without mandatory fields.
