### ISSUE TITLE
connect_get_namespaced_pod_exec does not open interactive shell on pod

### ISSUE THREAD

**Issue by polanjir** [kubernetes-client/python#822]
Hi, I'm trying to open interactive shell to kubernetes pod in python code. Something like this in shell `kubectl exec -ti some-pod-name /bin/bash`. But it finish immediately and I dont know what is wrong. 
```
resp = stream(api.connect_get_namespaced_pod_exec, 'some-pod-name', 'default',
             command="/bin/bash",
             stderr=True, stdin=True,
             stdout=True, tty=True,
             container='container_name',
             _preload_content=False)
```

**Comment by futianshi1314** [comment]
if tty=True, resp is a websocket,you can see the code of kubernetes/stream/ws_client.py

**Comment by james-knott** [comment]
I could do this in bash but I would like to stick to python. Any idea how to keep the tty connection open? Having same problems as OP

**Comment by nettyxiong** [comment]
@futianshi1314
It seems that _preload_content=False means resp is a websocket, and  _preload_content=True means resp is a str after waiting timeout
```python
    try:
        client = WSClient(configuration, get_websocket_url(url), headers)
        if not _preload_content:
            return client
        client.run_forever(timeout=_request_timeout)
        return WSResponse('%s' % ''.join(client.read_all()))
    except (Exception, KeyboardInterrupt, SystemExit) as e:
        raise ApiException(status=0, reason=str(e))
```

**Comment by futianshi1314** [comment]
@nettyxiong 国人， 这个可以实现的 详细的可以加我Q358968104，我们第一版py的webshell已经下线了， 改用go了

**Comment by mohatb** [comment]
@nettyxiong @polanjir Have you been able to resolve this? I am also having the same issue and cannot figure it out in python.

**Comment by polanjir** [comment]
@mohatb unfortunately I gave it up. But workaround which I am using is
```
    def connect_exec(pod_name):
        subprocess.run(["kubectl", "exec", "-ti", pod_name, "/bin/bash"])
```

**Comment by mohatb** [comment]
Thanks @polanjir , yes seems the only way to get this working is by using pseudo-terminal if not with subprocess. I found the one below but as am still beginner to python am having hard time converting to python3.

https://github.com/xychu/python/blob/add-tty-example/examples/exec_tty.py
https://asciinema.org/a/fOznfIWkZcYdEslY1iJs4HeZc

if you were able to make it to work on python3 it would be great :P

**Comment by mohatb** [comment]
I got it to work here. Still having some issues after exiting the terminal.
https://github.com/mohatb/python/blob/master/examples/exec_tty
