### ISSUE TITLE
Unable to connect to K8s cluster with token

### ISSUE THREAD

**Issue by IamRajatBadjatya** [kubernetes-client/python#823]
![BookFlight (5)](https://user-images.githubusercontent.com/31719594/57064009-67f55800-6cc5-11e9-8beb-59da3363b468.png)

Please refer to the above image, I am trying to access Kubernetes Clusters Using the Kubernetes API and for that purpose as mentioned in [documents](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/) I am using Python Kuberentes Client, that needs a token to communicate with Kube API.

When I am trying to authenticate the user with the token added in Kube-config file by Kube login everything works fine, where token provided by Keycloak REST API results in an un-authorization error.

I would be glad if anyone could provide any insight on this issue

**Comment by hapstony** [comment]
Yes ! we have this issue. looking forward for a solution for this ...

**Comment by 1032231418** [comment]
1.Create roles
	# mkdir -p  role
	# cd  /role

	# vi CreateServiceAccount.yaml
	apiVersion: v1
	kind: ServiceAccount
	metadata:
	  name: admin-user
	  namespace: kube-system
  
  
2.Role authorization
	# vi RoleBinding.yaml
	apiVersion: rbac.authorization.k8s.io/v1beta1
	kind: ClusterRoleBinding
	metadata:
	  name: admin-user
	roleRef:
	  apiGroup: rbac.authorization.k8s.io
	  kind: ClusterRole
	  name: cluster-admin
	subjects:
	- kind: ServiceAccount
	  name: admin-user
	  namespace: kube-system

 # kubectl create -f CreateServiceAccount.yaml
 # kubectl create -f RoleBinding.yaml

3.Get token
	# Token=$(kubectl describe secret $(kubectl get secret -n kube-system | grep ^admin-user | awk '{print $1}') -n kube-system | grep -E '^token'| awk '{print $2}')
       echo $Token
