### ISSUE TITLE
v1binding() set value for target as `None`

### ISSUE THREAD

**Issue by greg9702** [kubernetes-client/python#825]
Got stuck in:
File "/usr/lib/python3.7/site-packages/kubernetes/client/models/v1_binding.py", line 64, in __init__
    self.target = target
  File "/usr/lib/python3.7/site-packages/kubernetes/client/models/v1_binding.py", line 156, in target
    raise ValueError("Invalid value for `target`, must not be `None`")
ValueError: Invalid value for `target`, must not be `None`

**Comment by tomplus** [comment]
Could you write more about your use case? The target attribute is mandatory in this model.

**Comment by greg9702** [comment]
I'm trying to create my own scheduler, started with random scheduler example found in net and edited it a bit.

```
#!/usr/bin/python

import time
import random
import json

from kubernetes import client, config, watch

config.load_kube_config()
v1 = client.CoreV1Api()
print ("v1", v1)

scheduler_name = "foobar"

def nodes_available():
    ready_nodes = []
    for n in v1.list_node().items:
            for status in n.status.conditions:
                if status.status == "True" and status.type == "Ready":
                    ready_nodes.append(n.metadata.name)
    # print ("NODES: \n",v1.list_node())
    return ready_nodes

def scheduler(name, node, namespace='default'):
	target = client.V1ObjectReference()
	target.kind = "Node"
	target.api_version = "v1"
	target.name = node
	print ("target", target)

	meta = client.V1ObjectMeta()
	meta.name = name
	
	body = client.V1Binding(target = target)
	# using V1Binding() works but spada z rowerka
    # body = client.V1ConfigMap() # dont work but nie spada z rowerka
    # body.target = target
	body.metadata = meta
	print ("BODY", body)

	return v1.create_namespaced_binding(namespace, body)

def main():
	print("Scheduler running... ")
	w = watch.Watch()
	for event in w.stream(v1.list_namespaced_pod, "default"):
		print("Event happened")
		print("Used scheduler: " + event['object'].spec.scheduler_name)
		print ("Scheduling pod: ", event['object'].metadata.name)
		if event['object'].status.phase == "Pending" and event['object'].spec.scheduler_name == scheduler_name:
			try:
				print ("Scheduling pod: ", event['object'].metadata.name)
				print ("nodes aval: ", nodes_available())
				print ("selected node: ",  random.choice(nodes_available()))
				res = scheduler(event['object'].metadata.name, random.choice(nodes_available()))
			except client.rest.ApiException as e:
				print (json.loads(e.body)['message'])

if __name__ == '__main__':
    main()
```
Here is my code, It looks like it tries to schedule pods which was already scheluded.
> body = client.V1Binding(target = target)
this line throws exception that target is null, while it isn't. (Printed this for debug purposes)
Before it throws this exception it sucesfully schelude one pod from queue and then crash.
When I comment line 156, in this file: 
"/usr/lib/python3.7/site-packages/kubernetes/client/models/v1_binding.py
It tries to schedule pods which was already scheluded and got message this pod is already on node xyz.
But do not crash in this case.

**Comment by fishercht1995** [comment]
I meet same issues. Did you figure it out?

**Comment by tammersaleh** [comment]
I think I've tracked this down.  The file is too large for GitHub to render, but the errant code is in `create_namespaced_pod_binding_with_http_info()` in `kubernetes/client/apis/core_v1_api.py`.  In that method, it creates the Binding via:

``` python
return self.api_client.call_api('/api/v1/namespaces/{namespace}/pods/{name}/binding', 'POST',
                                path_params,
                                query_params,
                                header_params,
                                body=body_params,
                                post_params=form_params,
                                files=local_var_files,
                                response_type='V1Binding',
                                auth_settings=auth_settings,
                                async_req=params.get('async_req'),
                                _return_http_data_only=params.get('_return_http_data_only'),
                                _preload_content=params.get('_preload_content', True),
                                _request_timeout=params.get('_request_timeout'),
                                collection_formats=collection_formats)

```

Note the `response_type='V1Binding'`:  That's incorrect.  The response from `/api/v1/namespaces/{namespace}/pods/{name}/binding` is `{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Success","code":201}`

While trying to marshal the Status object into a Binding object, it fails validation due to a missing `target` attribute.

Unfortunately, this issue still exists in `master`, and this file is auto-generated from the Swagger definition.  I have no idea where to attempt to PR this 😢

**Comment by tammersaleh** [comment]
I can see the incorrect swagger definition in `scripts/swagger.json` starting at line 22902 in current master (again, file's too big to link to):

``` json
"/api/v1/namespaces/{namespace}/pods/{name}/binding": {
  "parameters": [
    ... ],
  "post": {
    ...
    "responses": {
      "200": {
        "description": "OK",
        "schema": {
          "$ref": "#/definitions/v1.Binding"
        }
      },
```

That response schema should be a Status.

**Comment by tammersaleh** [comment]
For anyone looking for a quick workaround:

``` python
v1 = client.CoreV1Api()
v1.api_client.call_api(f"/api/v1/namespaces/default/pods/{pod_name}/binding",
                       'POST',
                       body=binding,
                       response_type='V1Status',
                       auth_settings=['BearerToken'])
```

**Comment by greg9702** [comment]
@tammersaleh my work around, we just skip this steps when this function is called unnecessary.
```
	try:
		v1.create_namespaced_binding(namespace, body)
		return True
	except:
		print ('exception')
		return False
```

**Comment by zichambers0** [comment]
I met the same issue.
Is there a plan to fix it?

**Comment by ishakhari** [comment]
i met the same problem here any solutions please ?

**Comment by torgeirl** [comment]
This looks to be the same issue as #547 (issue now closed, but problem was never resolved).

It has been present (at least) since Python client version 6.0. It seems to be caused by the Python client failing to deserialize the returned data. I have worked around the problem by ignoring the step of deserializing the returned data (suggested by @zhcf):

```Python3
v1.create_namespaced_binding(namespace, body, _preload_content=False)
```
