### ISSUE TITLE
Get current usage of PODs inside a particular namespace

### ISSUE THREAD

**Issue by VF-mbrauer** [kubernetes-client/python#826]
How can the current usage be printed with the Kubernetes Python client.
The command in parallel for the kubectl would be `kubectl top pods -n <namespace>`
or `kubectl top node -n <namespace>`

Thanks!

**Comment by scottilee** [comment]
@micw523 Is this something you can help with? I looked at the APIs with the word "metric" in them and couldn't get anything to work.

**Comment by darkdragn** [comment]
Have you tried using the CustomObjectsApi? This works for me.

```python
from kubernetes.config import load_kube_config                                  
from kubernetes.client import CustomObjectsApi                                  
load_kube_config()                                                              
cust = CustomObjectsApi()                                                       
cust.list_cluster_custom_object('metrics.k8s.io', 'v1beta1', 'nodes') # All node metrics
cust.list_cluster_custom_object('metrics.k8s.io', 'v1beta1', 'pods') # All Pod Metrics
cust.list_namespaced_custom_object('metrics.k8s.io', 'v1beta1', 'default', 'pods') # Just pod metrics for the default namespace

```

**Comment by micw523** [comment]
Yeah I think that’s probably the better way to do it.

The heapster is being phased out I believe, which is necessary for kubectl top.

**Comment by darkdragn** [comment]
@VF-mbrauer On a side node, pods are namespaced, but nodes are not. Just mentioning that, since you specified a namespace in your second command example. 

---
@micw523 Yepyep, I think, last I read, heapster's been fully retired as of 1.13 (https://github.com/kubernetes-retired/heapster/blob/master/docs/deprecation.md). Ever since ~1.10 kubectl top tries either the metrics endpoint or heapster endpoint, whichever is registered with component statuses.

**Comment by harshgarg1995** [comment]
> Have you tried using the CustomObjectsApi? This works for me.
> 
> ```python
> from kubernetes.config import load_kube_config                                  
> from kubernetes.client import CustomObjectsApi                                  
> load_kube_config()                                                              
> cust = CustomObjectsApi()                                                       
> cust.list_cluster_custom_object('metrics.k8s.io', 'v1beta1', 'nodes') # All node metrics
> cust.list_cluster_custom_object('metrics.k8s.io', 'v1beta1', 'pods') # All Pod Metrics
> cust.list_namespaced_custom_object('metrics.k8s.io', 'v1beta1', 'default', 'pods') # Just pod metrics for the default namespace
> ```

I am getting 403 forbidden error though I am loading kube config...any suggestions

**Comment by KeithTt** [comment]
> Have you tried using the CustomObjectsApi? This works for me.
> 
> ```python
> from kubernetes.config import load_kube_config                                  
> from kubernetes.client import CustomObjectsApi                                  
> load_kube_config()                                                              
> cust = CustomObjectsApi()                                                       
> cust.list_cluster_custom_object('metrics.k8s.io', 'v1beta1', 'nodes') # All node metrics
> cust.list_cluster_custom_object('metrics.k8s.io', 'v1beta1', 'pods') # All Pod Metrics
> cust.list_namespaced_custom_object('metrics.k8s.io', 'v1beta1', 'default', 'pods') # Just pod metrics for the default namespace
> ```

This API return too much info... Is there another one return info like `kubectl top pod`:

![image](https://user-images.githubusercontent.com/15189954/114484028-0b826d80-9c3c-11eb-89ca-526383707269.png)
