### ISSUE TITLE
Getting Started section causes traceback when setting API key

### ISSUE THREAD

**Issue by flyte** [kubernetes-client/python#827]
The 'Getting Started' example from https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md seems to be incorrect, as per the following traceback:

```python
>>> from __future__ import print_function
>>> import time
>>> import kubernetes.client
>>> from kubernetes.client.rest import ApiException
>>> from pprint import pprint
>>> 
>>> # Configure API key authorization: BearerToken
... kubernetes.client.configuration.api_key['authorization'] = 'YOUR_API_KEY'
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: module 'kubernetes.client.configuration' has no attribute 'api_key'
>>> 
```

I'm using `kubernetes==9.0.0`, but I've tried the example from the 9.0 release branch too, which is the same.

**Comment by scottilee** [comment]
@flyte the line should be:
`kubernetes.client.Configuration().api_key['authorization'] = 'YOUR_API_KEY'`

I believe it's auto-generated but there are fixes coming. Thanks for reporting!
