### ISSUE TITLE
list_pod_for_all_namespaces when accessing all namespaces isn't possible.

### ISSUE THREAD

**Issue by machine424** [kubernetes-client/python#837]
running `list_pod_for_all_namespaces` will raise an exception if the user doesn’t have permission to list or get resources in some or all namespaces, is it possible to bypass this and make the API return only pods in accessible namespaces?

**Comment by tomplus** [comment]
AFAIK it's not possible. If you have enough permissions you can list all namespaces and iterate over them to list pods.

**Comment by machine424** [comment]
Thank you for your response, I've already thought about that, but in case of many namespaces (if we can list them all) it will be slow, I was wondering if there is another method where the API uses its knowledge of the Roles of the client to list pods only in accessible namespaces. I think the API doesn't provide that for the moment.
