### ISSUE TITLE
Unable to exec in a pod using kubernetes-cli in Python even after using stream api

### ISSUE THREAD

**Issue by avisrivastava254084** [kubernetes-client/python#842]
I am following the [official documentation](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#connect_get_namespaced_pod_exec) and to my surprise, the request just won't work.

I tried reading multiple questions and answers but in vain. I had set `stream` api to use but the error did not go away.

My code is:
```
from __future__ import print_function
import time
import kubernetes.client
from kubernetes.client.rest import ApiException
from pprint import pprint
from kubernetes import client, config, stream
stream = stream.stream

# Configure API key authorization: BearerToken
configuration = kubernetes.client.Configuration()
configuration.host = "https://my_aws_server.amazonaws.com"
configuration.verify_ssl = False
configuration.api_key['authorization'] = "some_token"
# Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
configuration.api_key_prefix['authorization'] = 'Bearer'
configuration.debug = True

api_instance = kubernetes.client.CoreV1Api(
    kubernetes.client.ApiClient(configuration))
name = 'jupyter-ankita'  # str | name of the PodExecOptions
namespace = 'jhub'  # str | object name and auth scope, such as for teams and projects
# str | Command is the remote command to execute. argv array. Not executed within a shell. (optional)
command = 'echo "hail aviral"'
# bool | Redirect the standard error stream of the pod for this call. Defaults to true. (optional)
stderr = True
# bool | Redirect the standard input stream of the pod for this call. Defaults to false. (optional)
stdin = True
# bool | Redirect the standard output stream of the pod for this call. Defaults to true. (optional)
stdout = True
# bool | TTY if true indicates that a tty will be allocated for the exec call. Defaults to false. (optional)
tty = True

try:
    api_response = stream(api_instance.connect_post_namespaced_pod_exec(
        name, namespace, command=command, stderr=stderr, stdin=stdin, stdout=stdout)
    )
    pprint(api_response)
except ApiException as e:
    print("Exception when calling CoreV1Api->connect_post_namespaced_pod_exec: %s\n" % e)

```

I want the command to run but instead, I am facing an error:
```
Exception when calling CoreV1Api->connect_post_namespaced_pod_exec: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Audit-Id': '88df8863-61b1-4fe7-9d39-d0e6059ea993', 'Content-Type': 'application/json', 'Date': 'Tue, 28 May 2019 14:04:38 GMT', 'Content-Length': '139'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}
```

My SSL client is updated, I am using Python3.7 from the `brew` on a MacOS.

Also used on Ubuntu, same error.

**Comment by avisrivastava254084** [comment]
Any help @roycaihw @dims @micw523 @djkonro 
Sorry for direct tagging, need some urgent help. Would be grateful to you guys. 
Thanks!

**Comment by phracek** [comment]
Is there any chance to get RC of the command executed in POD?
I would like to check if the command was successful or not.
Like `$?` in bash.

**Comment by kareem-elsayed** [comment]
I have the same issue also

**Comment by phracek** [comment]
Adding to CC @TomasTomecek

**Comment by tomplus** [comment]
@avisrivastava254084 The official documentation is auto-generated from the spec and in many places are not helpful at all (ref: https://github.com/kubernetes-client/python/issues/601).

In your code I see that you try to pass output from the api_instance.connect_post_namespaced_pod_exec to the `stream()` instead of passing the function as an argument which the `stream()` will call for you.

```
api_response = stream(api_instance.connect_post_namespaced_pod_exec,
        name, namespace, command=command, stderr=stderr, stdin=stdin, stdout=stdout
    )
```
(I removed brackets only).

You can also check this example: https://github.com/kubernetes-client/python/blob/master/examples/exec.py 

@phracek I'am afraid getting the RC is currently not supported by this library. Could you create a separate issue for this.

**Comment by tomplus** [comment]
@phracek it's been already reported: https://github.com/kubernetes-client/python/issues/812

**Comment by EricCat** [comment]
@avisrivastava254084 Did you find the solution?

**Comment by avisrivastava254084** [comment]
@EricCat 
Yeah I did but as I have left my previous company, I am not able to recall the solution.

**Comment by roycaihw** [comment]
Please refer to this example for running exec https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py

Getting the RC is fixed in https://github.com/kubernetes-client/python/pull/956

/close

**Comment by kmmanto** [comment]
I'm getting the same error while following the examples. 
Using:
python3
kubernetes==10.0.1

`HTTP response body: unable to upgrade: missing upgrade headers in request`
