### ISSUE TITLE
Get deletion status information for pod

### ISSUE THREAD

**Issue by 1032231418** [kubernetes-client/python#849]
```
zbc-76b485bc86-rm7tl                                 0/1       ImagePullBackOff   0          9m
zbc-85ff8b568f-bwnw9                                 1/1       Terminating        0          9m
zbc-85ff8b568f-p2hmq                                 1/1       Running            0          2m

```
I have several container status information here.
I want to judge their status, but I can't judge Terminating status from interface.

**Comment by tomplus** [comment]
It's hidden in a metadata in the `deletion_timestamp` attribute: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1ObjectMeta.md

**Comment by 1032231418** [comment]
Thank you, but how do I get this information?

**Comment by tomplus** [comment]
Something like this:
```
pod = read_namespaced_pod(...)
print(pod.metadata.deletion_timestamp)
```
should work.

**Comment by 1032231418** [comment]
Thank you for your reply. I found it.
running  pod :
              'deletion_timestamp': None,
Terminating pod:
               'deletion_timestamp': datetime.datetime(2019, 6, 5, 8, 23, 4, tzinfo=tzutc()),
