### ISSUE TITLE
config is not a dir

### ISSUE THREAD

**Issue by Jonathan-7** [kubernetes-client/python#857]
I tried installing via pip and when importing `config `got this error:
`No name 'config' in module 'kubernetes'`

So I removed it and tried installing from source and got this error:
`error: supposed package directory 'kubernetes\config' exists, but is not a directory`

> PS C:\Users\username\Documents\res\git> git clone --recursive https://github.com/kubernetes-client/python.git
Cloning into 'python'...
remote: Enumerating objects: 42706, done.
remote: Total 42706 (delta 0), reused 0 (delta 0), pack-reused 42706
Receiving objects: 100% (42706/42706), 11.61 MiB | 4.88 MiB/s, done.
Resolving deltas: 100% (41250/41250), done.
Checking out files: 100% (2104/2104), done.
Submodule 'kubernetes/base' (https://github.com/kubernetes-client/python-base) registered for path 'kubernetes/base'
Cloning into 'C:/Users/username/Documents/res/git/python/kubernetes/base'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 440 (delta 0), reused 1 (delta 0), pack-reused 437
Receiving objects: 100% (440/440), 178.75 KiB | 1.22 MiB/s, done.
Resolving deltas: 100% (253/253), done.
Submodule path 'kubernetes/base': checked out '1d5231cee6d0674b958ad429b60dda39363a4dc1'
PS C:\Users\username\Documents\res\git> cd python
PS C:\Users\username\Documents\res\git\python> python setup.py install
C:\Users\username\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\dist.py:484: UserWarning: The version specified ('10.0.0-snapshot') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
creating kubernetes.egg-info
writing kubernetes.egg-info\PKG-INFO
writing dependency_links to kubernetes.egg-info\dependency_links.txt
writing requirements to kubernetes.egg-info\requires.txt
writing top-level names to kubernetes.egg-info\top_level.txt
writing manifest file 'kubernetes.egg-info\SOURCES.txt'
error: supposed package directory 'kubernetes\config' exists, but is not a directory

**Comment by micw523** [comment]
This is documented by #676. You should use the workaround provided by #766 on Windows systems when you clone from the source.
@roycaihw, I think it's safe to close this.
