### ISSUE TITLE
patch_namespaced_custom_object only accepts `merge-patch+json` patch type

### ISSUE THREAD

**Issue by rodrigovalin** [kubernetes-client/python#862]
The `patch_namespaced_custom_object` function will only accept patches of type `merge-patch+json` as can be seen in here:

https://github.com/kubernetes-client/python/blob/master/kubernetes/client/apis/custom_objects_api.py#L2038

It should also be possible to specify a `json-patch+json` object, that is what `kubectl patch` uses.

**Comment by tomplus** [comment]
It's already fixed here: https://github.com/kubernetes-client/gen/pull/119 and it should be generated in the next release of the library.
