### ISSUE TITLE
Add logic to wait for conditions to be true

### ISSUE THREAD

**Issue by yashbhutwala** [kubernetes-client/python#863]
Functionality similar to [`kubectl wait --for-condition=ready pod -l=labels`](https://github.com/kubernetes/kubernetes/issues/1899)

Function here in kubernetes e2e test framework is good for reference as well: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/pod/wait.go#L111

**Comment by y-spreen** [comment]
Is there any way to achieve this functionality with the current version? Or is it just not possible right now?

**Comment by prathameshd9** [comment]
Interested in the wait-for-pod condition. Using 1.10 version..

**Comment by underyx** [comment]
/reopen

This is still a valid feature request.
