### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by abigbigbird** [kubernetes-client/python#867]
python: 2.7.5

code
`from kubernetes import client, config, watch

def main():
    config.load_kube_config()

    v1 = client.CoreV1Api()
    print("Listing pods with their IPs:")
    w = watch.Watch()
    for event in w.stream(v1.list_pod_for_all_namespaces):
        print("Event: %s %s %s" % (event['type'],event['object'].kind, event['object'].metadata.name))
`
Traceback (most recent call last):
  File "examples/example.py", line 46, in <module>
    main()
  File "examples/example.py", line 34, in main
    for event in w.stream(v1.list_pod_for_all_namespaces):
  File "/usr/lib/python2.7/site-packages/kubernetes/watch/watch.py", line 144, in stream
    for line in iter_resp_lines(resp):
  File "/usr/lib/python2.7/site-packages/kubernetes/watch/watch.py", line 48, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/usr/lib/python2.7/site-packages/urllib3/response.py", line 732, in read_chunked
    self._original_response.close()
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/urllib3/response.py", line 415, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))

**Comment by Vince-Cercury** [comment]
What was the solution? I'm facing the same issue with Airflow 2.0.0. Although if I execute a small python script on the executor, I don't get any error

```
import os
from kubernetes import client, config, watch

config.load_incluster_config()

v1 = client.CoreV1Api()

stream = watch.Watch().stream(v1.list_namespaced_pod, "my-namespace")
for event in stream:
    print("Event: %s %s" % (event['type'], event['object'].metadata.name))
```

**Comment by newhardwarefound** [comment]
Me 2. Is it a problem on the AKS side?

**Comment by chekolyn** [comment]
This is very normal in K8s watch streams and it depends in multiple factors (apiserver node maintenance, how fast the client can consume the stream, firewalls between the server and client with TTL in TCP connections, etc). The key takeaway here is that you need to account for this type of failure and not expect a stream connection that will persist forever. 

One way I have solved this in the past is by creating a python service that will create multiple streams; I used to create a thread per stream and put it in the background. If the connection terminates you catch the exception then the thread should return. After that you can do some logic to reconnect if that is what you desire.
