### ISSUE TITLE
kubernetes.config.new_client_from_config() is not possible to pass serialized or deserialized yaml objects.

### ISSUE THREAD

**Issue by rfum** [kubernetes-client/python#870]
Hi There,
If I want to pass a yaml object which is serialized to a python dictionary,string or python object, I cannot achieve with the current implementation of `new_client_from_config()` I need to write down every kubeconfig data (which is a secret data) into a file and than need to give it's path in order to get a client instance. This is increasing the complexity and hardware dependencies of my code. Does any other way exists to get a client from yaml objects without using filesystem?

kubernetes-client/python version is 8.0.0

Thanks,
Furkan.

**Comment by roycaihw** [comment]
cc @yliaog

**Comment by yliaog** [comment]
depending on what is your particular use case, you may pass around the object through RPC if it crosses processes, alternative to using file system.

**Comment by rfum** [comment]
No, I only want to pass string or python dictionary instead of file path and interprocess communication is not my aim. There will be only one process in the picture.
I simply looking for a replacement of `kubernetes.config.new_client_from_config(config_path)` to `kubernetes.config.new_client_from_config(string_or_dict_config)`

**Comment by yliaog** [comment]
in that case, could you do it in two steps 1) deserialize the string 2) create a client from the result (of the deserialization)

**Comment by rfum** [comment]
Is it possible with the current API? If so would you please share an example snippet?

**Comment by 245967906** [comment]
@rfum 
I referred to the source code for the kubernetes.config.new_client_from_config method.
Your requirements can be implemented in the following code.

``` python
import kubernetes
from ruamel import yaml

configuration = kubernetes.client.Configuration()
kubeconfig = yaml.safe_load()
loader = kubernetes.config.kube_config.KubeConfigLoader(kubeconfig)
loader.load_and_set(configuration)
api_client=kubernetes.client.ApiClient(configuration)
api_instance = kubernetes.client.CoreV1Api(api_client)
api_instance.list_pod_for_all_namespaces()
```
