### ISSUE TITLE
error in create_namespaced_job 'property'  - object has no attribute 'swagger_types'

### ISSUE THREAD

**Issue by simondh** [kubernetes-client/python#872]
error in create_namespaced_job
'property' object has no attribute 'swagger_types'

I have traced this to an error in /kubernetes/client/api_client.py, sanitize_for_serialization, where the recursion calls this function to 'sanitize' a single entity of type Property. This falls through to the obj_dict comprehension, where it bombs as the object has no .swagger_type attibute.
I have fixed it locally with this change (2 lines in bold). The code that triggers the issue is attached
[k8-python-error.txt](https://github.com/kubernetes-client/python/files/3386411/k8-python-error.txt). I can submit a pull request if desired. 

        if isinstance(obj, dict):
            obj_dict = obj
        **elif isinstance(obj, property):
            return None**
        else:
            # Convert model obj to dict except
            # attributes `swagger_types`, `attribute_map`
            # and attributes which value is not None.
            # Convert attribute name to json key in
            # model definition for request.
            obj_dict = {obj.attribute_map[attr]: getattr(obj, attr)
                        for attr, _ in iteritems(obj.swagger_types)
                        if getattr(obj, attr) is not None}

**Comment by roycaihw** [comment]
thanks for the report!

I looked at `k8-python-error.txt` and I'm not sure if it's a bug in `api_client.py`

I pulled together a small example mimicking the [k8s doc](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#running-an-example-job) and it worked for me:
```
from kubernetes import client, config

def main():
    config.load_kube_config()
    container = client.V1Container(name="pi", image="perl",
        command=["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"])
    template = client.V1PodTemplateSpec(spec=client.V1PodSpec(containers=[container], restart_policy="Never"))
    job = client.V1Job(api_version="batch/v1", kind="Job",
        metadata=client.V1ObjectMeta(name="test-job"),
        spec=client.V1JobSpec(template=template, backoff_limit=4))
    batch_v1 = client.BatchV1Api()
    api_response = batch_v1.create_namespaced_job(body=job, namespace="default")
    print("Job creation status='%s'" % str(api_response.status))

if __name__ == '__main__':
    main()
```

```
Job creation status='{'active': None,
 'completion_time': None,
 'conditions': None,
 'failed': None,
 'start_time': None,
 'succeeded': None}'

$ kubectl get jobs
NAME       COMPLETIONS   DURATION   AGE
test-job   1/1           8s         10s
```

**Comment by roycaihw** [comment]
perhaps we could add some examples like ^ given job creation with the python client is painful

ref https://github.com/kubernetes-client/python/issues/589
https://blog.pythian.com/how-to-create-kubernetes-jobs-with-python/

cc @scottilee

**Comment by scottilee** [comment]
@roycaihw Added it to my list of examples to add and clean up. You can close this if you want.
