### ISSUE TITLE
Deleting CRD

### ISSUE THREAD

**Issue by MiyKh** [kubernetes-client/python#874]
Hello,

When I try to delete a CRD definition with delete_cluster_custom_object, it keeps ask me for namespace:

```
api.delete_cluster_custom_object(group="velero.io", version="v1", plural=crd_plural, name=crd_object, body=body)
```
```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Namespace parameter required.","reason":"BadRequest","code":400}
```

Do I miss something?

**Comment by roycaihw** [comment]
@MiyKh Are you trying to delete a CRD or a CR? CRDs are cluster-scoped, meaning they don't have namespaces. The delete_cluster_custom_object api is used for deleting a CR object.

**Comment by MiyKh** [comment]
I try to delete a CRD and not a CR.
The delete_cluster_custom_object api is designed for CR object but which one is for CRD?

**Comment by roycaihw** [comment]
You are looking for [`delete_custom_resource_definition`](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/ApiextensionsV1beta1Api.md#delete_custom_resource_definition)

**Comment by MiyKh** [comment]
Thanks a lot for your help
