### ISSUE TITLE
Suggestion: Raise default connection pool size from 1 to 10

### ISSUE THREAD

**Issue by dharmab** [kubernetes-client/python#875]
The default maximum connection pool size in urllib3 is a very low value of 1: https://urllib3.readthedocs.io/en/1.4/pools.html#api

Many popular libraries use a saner default. For example, `requests` uses a default of 10.

Connection pooling enhances performance on both the client and server, so using a sane default is a responsible choice. While the user can override the connection pool size in the config, most users are likely not doing this unless they are using high levels of concurrency.

Setting a sane default should reduce load on k8s apiservers everywhere :)

If this idea seems reasonable, I'm happy to contribute it.

**Comment by roycaihw** [comment]
May I ask are these [parameters](https://github.com/kubernetes-client/python/blob/da8c843bda7ebf03f53cdc95409e5543d2b2abd3/kubernetes/client/rest.py#L103-L104) what you're referring to? It seems that we are already using a PoolManager with num_pools and maxsize set to 4 by default, and the parameters are configurable. Also this code is auto-generated by code generator. So if it's a wide standard to increase the default to 10, it's better to make the change upstream.
