### ISSUE TITLE
Correct Kubernetes incubator information in README

### ISSUE THREAD

**Issue by krichter722** [kubernetes-client/python#877]
[The README states that this project is an Kubernetes incubator project](https://github.com/kubernetes-client/python#kubernetes-incubator), however [the Kubernetes incubator README states that the incubator project is deprecated](https://github.com/kubernetes/community/blob/master/incubator.md).

**Comment by scottilee** [comment]
I'll fix this. I'll have a pull request later tonight. Thanks for the catch @krichter722.

**Comment by scottilee** [comment]
Pull request: https://github.com/kubernetes-client/python/pull/883.

**Comment by scottilee** [comment]
Pull request was merged.

/close

**Comment by roycaihw** [comment]
@scottilee Thanks for fixing this.

/close
