### ISSUE TITLE
connect_get_namespaced_pod_exec

### ISSUE THREAD

**Issue by 1032231418** [kubernetes-client/python#878]
hi:

Return data, terminal size, with parameters to set?
My terminal can't fill the entire page

**Comment by 1032231418** [comment]
```             k8s_api_obj = client.CoreV1Api()
                container_stream = stream(k8s_api_obj.connect_get_namespaced_pod_exec,
                       name=pod_name,
                       namespace=namespace,
                       command=command,
                       stderr=True, stdin=True,
                       stdout=True, tty=True,
                       _preload_content=False)
```

**Comment by roycaihw** [comment]
Could you try configuring your terminal rendering size, or redirect the python client output to a file? I don't see it's a problem in the stream client itself.

**Comment by 1032231418** [comment]
The official client web terminal also has this problem，The terminal can only use half
![terminal](https://user-images.githubusercontent.com/5716348/61384461-3a42a700-a8e3-11e9-97e8-9950ee5c2498.png)

**Comment by roycaihw** [comment]
I tried changing [this example](https://github.com/kubernetes-client/python/blob/4a204fa4cd1ae6f8bfe2e1eea15145ba72532456/examples/exec.py#L60) to echo long messages and the responses got well-rendered. Could you try running the example and see if it works for you?
