### ISSUE TITLE
get all yamls based on a label selector

### ISSUE THREAD

**Issue by mathnitin** [kubernetes-client/python#879]
I am looking for the equivalent apis in python kubernetes client. Can anyone please provide any pointers. 

1. kubectl get all --all-namespaces --selector name=foo -o yaml --export > foo.yaml
2. kubectl delete -f foo.yaml
... (Modify the yaml file)
3. kubectl create -f foo.yaml. <-- For this i did find utils.create_from_yaml

**Comment by roycaihw** [comment]
cc @yliaog

**Comment by yliaog** [comment]
below are the steps taken by kubectl:
1. Read the file
2. Split it into 1 or more objects
3. For each object, decode it, look at its apiVersion and kind to determine the resource URL to submit it to 
4. Post the content for that object to that resource URL

below are some pointers to cli-runtime and client-go, you may switch to use python client library, or implement the equivalent function in python.

The code kubectl uses for #1 and #2 is called "resource builder" and lives in https://github.com/kubernetes/cli-runtime/tree/master/pkg/genericclioptions/resource (the way `kubectl create` makes use of it is at https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/cmd/create/create.go#L232-L247)

#3 based on discovery info from the server lives at https://github.com/kubernetes/client-go/blob/master/restmapper/discovery.go#L186-L193 and would be called at https://github.com/kubernetes/client-go/blob/master/restmapper/discovery.go#L254-L256

#4 you may use REST client

**Comment by mathnitin** [comment]
@yliaog Thanks for the explanation. How do i perform "kubectl get all --all-namespaces --selector name=foo -o yaml --export" command. 

Your explanation covers the part where I create objects from a yaml file.

**Comment by yliaog** [comment]
https://github.com/kubernetes-client/python/tree/master/examples
has some examples for using the api to retrieve resources, like pods. which particular aspect of the command "kubectl get all --all-namespaces --selector name=foo -o yaml --export" are you interested in?

**Comment by mathnitin** [comment]
Yeah i found the example of the pod retrieval. https://github.com/kubernetes-client/python/blob/master/examples/example1.py#L26.

My problem statement is that I don't know the type of resource, I just know the label. I need to get yaml of all the resources (service, deamonset, deployment, replicaset), if any, in export format. I looked at the go client as well couldn't find a generic call for this.

**Comment by yliaog** [comment]
https://stackoverflow.com/questions/47691479/listing-all-resources-in-a-namespace

so for that the first step is to list all the resources, the above discussion might be helpful. it is not python client specific though.
