### ISSUE TITLE
Deleting Deployments - Inconsistent behavior between CLI and Python API

### ISSUE THREAD

**Issue by michael-burt** [kubernetes-client/python#880]
In `kubectl`, I can delete a deployment using `kubectl delete deployments/some_deployment`

In the Python client, I can also delete a deployment, using something like [this](https://github.com/kubernetes-client/python/blob/master/examples/deployment_examples.py).

In the `kubectl` CLI, when I delete a deployment, it removes the associated pods and ReplicaSet. In the Python client, it only deletes the Deployment resource, the pods and ReplicaSet stick around.

Is there a specific reason that this behavior occurs?

Thanks!

**Comment by roycaihw** [comment]
Removing the associated resources happens in server side. It's done by the garbage collector who looks at the owner reference and the propagation_policy. I checked `kubectl delete deployments/some_deployment  --v=8` and it used `propagationPolicy: Background`, but I think `propagation_policy='Foreground'` used by the example should also trigger deletion of the pods and RSs. 

ref https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#controlling-how-the-garbage-collector-deletes-dependents
