### ISSUE TITLE
Test flake due to CPU requested in Travis CI

### ISSUE THREAD

**Issue by micw523** [kubernetes-client/python#890]
See my personal build [here](https://travis-ci.org/micw523/python/jobs/562374061).

It seems that the default config requests 2 CPUs but sometimes Travis CI only provides 1. This behavior causes Minikube to crash and the py*-functional test would fail. We should request 1 CPU from minikube instead.

**Comment by roycaihw** [comment]
minikube cpu usage is configurable using the [command line flag](https://github.com/kubernetes/minikube/blob/165c1afd331765aaa94d8db684b0045fb0713cc9/cmd/minikube/cmd/start.go#L130). I haven't tested if it can work with 1 cpu

Before that, 2 cpus doesn't sound like a huge value and I'm surprised that travis ci cannot guarantee that. My assumption is that workers running in parallel can share the cpus, and most of the time we only have one job running. I wonder if we can configure the worker pool to ensure the cpus assigned to each job: https://docs.travis-ci.com/user/enterprise/worker-configuration/#configuring-the-number-of-concurrent-jobs

/assign @micw523

**Comment by micw523** [comment]
Sounds good. I'll do some investigations when I have time. Also let me check some of our earlier builds to see what our configurations were.

**Comment by micw523** [comment]
Our previous builds were all configured for using 2 CPUs. I wonder if Travis CI had put some quota system in place.

**Comment by micw523** [comment]
See #906 - failure attributed to upstream Travis CI
