### ISSUE TITLE
Kubernetes-client python to find resource utilization of pods/ containers

### ISSUE THREAD

**Issue by akshay-r-1996** [kubernetes-client/python#892]
Hi,

I wanted to know how can we find resource utilization metrics for pods/ containers running in pods using the Kubernetes-client- Python.

**Comment by roycaihw** [comment]
cc @yliaog

**Comment by yliaog** [comment]
From core k8s API, only the requests and limits can be retrieved. for cpu / memory etc utilization, heapster was used before for that, then metrics API was defined, and metrics server or prometheus could be used.

https://brancz.com/2018/01/05/prometheus-vs-heapster-vs-kubernetes-metrics-apis/ has some more info about the topic.

**Comment by akshay-r-1996** [comment]
Okay. But what is this: 
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V2beta1ResourceMetricSource.md

And can this be used?

**Comment by yliaog** [comment]
https://github.com/kubernetes/api/blob/739c7f7721ed643459cb2d240f43811e0647ba79/autoscaling/v2beta1/types.go#L159

please see the comments in the above file for descriptions. in short, it is for auto scaling, it does not work for your use case

**Comment by akshay-r-1996** [comment]
Okay. Thank you.
