### ISSUE TITLE
list_node: v1_container_image: ValueError: Invalid value for `names`, must not be `None`

### ISSUE THREAD

**Issue by sebastian-philipp** [kubernetes-client/python#895]
Hey all,

I'm getting this when calling `list_node()`:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13437, in list_node
    (data) = self.list_node_with_http_info(**kwargs)  # `kwargs` is empty.
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 13534, in list_node_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 236, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 620, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 254, in __deserialize
    for sub_data in data]
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 620, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 620, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 254, in __deserialize
    for sub_data in data]
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 276, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 622, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/models/v1_container_image.py", line 52, in __init__
    self.names = names
  File "/usr/lib/python2.7/site-packages/kubernetes/client/models/v1_container_image.py", line 77, in names
    raise ValueError("Invalid value for `names`, must not be `None`")
ValueError: Invalid value for `names`, must not be `None`
```

Installed versions in the client (CentOS 7): 
```
[root@kubic-2 /]# python
Python 2.7.5 (default, Jun 20 2019, 20:27:34) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> urllib3.__version__
'1.10.2'
>>> kubernetes.__version__
'8.0.1'
>>> yaml.__version__
'3.10'
>>> requests.__version__
'2.6.0'
```

kubernetes:
```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

Found in https://github.com/ceph/ceph/pull/29131

Is there any chance of getting `list_node` to work?

**Comment by sebastian-philipp** [comment]
My workaround is a monkey-patch:

```python
    from kubernetes.client.models.v1_container_image import V1ContainerImage
    def names(self, names):
        self._names = names
    V1ContainerImage.names = V1ContainerImage.names.setter(names)
```

**Comment by roycaihw** [comment]
`names` is a required field in `containerImage` by k8s [Go type definition](https://github.com/kubernetes/kubernetes/blob/269183a7a83aa48d3a1da43d57e3f9e94e459bd6/staging/src/k8s.io/api/core/v1/types.go#L4425-L4427) and by the [generated openapi spec](https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json). Therefore the generated python client expects the field to not be `None` when deserializes the `containerImage` response from apiserver. 

The problem is either in k8s or in the image being used, where kubelet could report `null` image names if no repo tag or digest exist for the image. Ref https://github.com/kubernetes/kubernetes/pull/79018

Please either file an issue in k8s to follow up on https://github.com/kubernetes/kubernetes/pull/79018, or provide repo tag / digest for the image

/close

**Comment by sebastian-philipp** [comment]
After talking with @saschagrunert this seems to be related to how cri-o reports images to k8s. And there was a backport to a later patch release of 1.14.

**Comment by doubleyewdee** [comment]
Just ran into an issue with an Azure Kubernetes Service (AKS) 1.19.5 cluster where the above 'monkey patch' worked for me. We are migrating from 1.18.x to 1.19.x and found that a service using this API was broken.

The issue reproduces trivially on both the release (12.0.1) and alpha (17.14.0a1) packages. Should this issue really be closed?

**Comment by doubleyewdee** [comment]
Ok, this is a [still open k8s bug](https://github.com/containerd/containerd/issues/4771), so yeah the issue I guess can be closed although as more users shuffle to containerd-backed clusters they may be surprised. :)

**Comment by RobertDiPaolo** [comment]
We've just run into this issue, I'm surprised this is closed. I appreciate the spec says it's required but it seems quite tight to reject the entire server response on a null field! Whatever happened to the Robustness Principal, i.e. be liberal in what you accept. We'll try the monkey patch for now.

**Comment by doronmak** [comment]
just get the same issue

**Comment by alphaWizard** [comment]
I ran into the same issue as well.

**Comment by olix0r** [comment]
There's some more discussion related to this issue here https://github.com/kubernetes/kubernetes/issues/100802

**Comment by roycaihw** [comment]
/reopen

Please see more details in https://github.com/kubernetes/kubernetes/issues/100802#issuecomment-844561253

Until an agreement for some API change in SIG Node is made, we need to patch this client to treat `None` as `[]`

/help

The fix can be made directly to https://github.com/kubernetes-client/python/blob/821618feb3456674ea586047b972b3ae7559fa42/kubernetes/client/models/v1_container_image.py#L79-L80

After the fix is merged, the commit should be added to [apply-hotfixes.sh](https://github.com/kubernetes-client/python/blob/master/scripts/apply-hotfixes.sh) as a cherrypick command, so that we can carry this fix when we re-generate this client.

**Comment by roycaihw** [comment]
update: the `names` field will be optional in k8s 1.22: https://github.com/kubernetes/kubernetes/pull/102159. Before then, we still need to patch this client as mentioned in https://github.com/kubernetes-client/python/issues/895#issuecomment-844567240. I will send a patch next week if no one picks this up before me :)

**Comment by lixd** [comment]
get the same issue,when node in k8s has some image's name are `none`,like this:
```bash
$ circtl images
IMAGE                                                                      TAG                                 IMAGE ID            SIZE
<none>                                                                     <none>                              b24daf1f40e32       1.88GB
```
and when i remove this image,it works.

```bash
crictl rmi b24daf1f40e32
```
