### ISSUE TITLE
how to cordon(unschedule) a node

### ISSUE THREAD

**Issue by magiclamp2** [kubernetes-client/python#899]
Hello, I want to use the python client to achieve the following functions.
`-kubectl drain`
`-kubectl cordon`
`-kubectl uncordon`

Currently, I am able to evict all pods on a node using `create_namespaced_pod_eviction`. But I don't know how to make a node schedulable(`cordon`) or unschedulable(`uncordon`)? Is there existing api implemented or any workarounds?

**Comment by roycaihw** [comment]
cc @fabianvf

**Comment by fabianvf** [comment]
@magiclamp2 `cordon` and `uncordon` basically just set the `spec.unschedulable` field in the Node's resource definition. `cordon` sets `spec.unschedulable` to `true`, and uncordon sets `spec.unschedulable` to `false`. You should be able to use the existing core_v1 `patch_node` method to replicate that functionality.

**Comment by stevep-arm** [comment]
Just in case someone in the future is looking for how to do this. This is what I have for cordoning.

```python
    v1 = client.CoreV1Api()

    body = {
        "spec": {
            "unschedulable": True,
        },
    }
    v1.patch_node(node_name, body)
```

**Comment by MageshSrinivasulu** [comment]
Node js version for the same

```
        const headers = { 'content-type': 'application/strategic-merge-patch+json' }
        let body = { spec: { unschedulable: true } };
        let res = await k8sApi.patchNode(nodeName, body, undefined, undefined, undefined, undefined, { headers });
```

**Comment by MageshSrinivasulu** [comment]
> create_namespaced_pod_eviction

@magiclamp2  @stevep-arm How to get all the pods in the nodes ? What function do you use for it?

**Comment by MageshSrinivasulu** [comment]
The logic for getting the pods running in a node

```
   **// Get all namespace**

    let namespaces = await k8sApi.listNamespace();
    for (let item of namespaces.body.items) {
        let namespace = item.metadata.name;
        const fieldSelector = `spec.nodeName=${nodeName}`;

        ****// Filtering pod running in the namespace by node
       
        let resNamespacedPod = await k8sApi.listNamespacedPod(namespace, null, null, null, fieldSelector);
        for (let pod of resNamespacedPod.body.items) {
            console.log(namespace + " " + pod.metadata.name);
        }
    }
```

**Comment by MageshSrinivasulu** [comment]
@magiclamp2 @stevep-arm I am not able to figure out the syntax for **_createNamespacedPodEviction_** function getting an HTTP error. Can you share some examples if possible?
