### ISSUE TITLE
Add Installation Instructions for Windows Users

### ISSUE THREAD

**Issue by micw523** [kubernetes-client/python#910]
This issue originally appeared in #676. We provided a utility script for Windows developers to work around the symbolic link in #766. However, the script is not documented anywhere and we just got a new question on #857. I think we should add information to Readme for potential Windows developers.

We'll have to tell Windows developers about the symbolic links and our workaround - and that they'll face difficulty when trying to commit changes (should remove the copied folders, clone the base repo only if they want to change the code in the base repo, etc).

I have two ideas to document this:

1. Add some information under the "Installation" section and tell Windows users that installing from PyPi is preferred. Otherwise they'll need to run the batch script.
2. Add a new section in front of the Mac/Python issue on Readme to document the same kind of actions that they need to take.

**Comment by roycaihw** [comment]
I'm fine with adding a paragraph or two to Installation and Troubleshooting. If it will be longer we can have a separate doc and link to it

**Comment by micw523** [comment]
/lifecycle frozen
/assign
Will tie this to #266
