### ISSUE TITLE
documentation missing how to mount a volume to a job

### ISSUE THREAD

**Issue by thebeancounter** [kubernetes-client/python#917]
Hi 

I am using minicube with python-kubernetes and trying to mount a directory to a job (input data) and then keep the data only if the job finished. 

Something like [empty dir](https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/) defined here, I can't seem to find an example to that anywhere, not for how to mount a directory to a job and not for how to keep the data

**Comment by roycaihw** [comment]
There is a WIP example at https://github.com/kubernetes-client/python/pull/898/files#diff-5e0ba41a462031ce04f33c1a7e1b2bb8. You could refer to the sample examples we have in https://github.com/kubernetes-client/python/tree/master/examples to learn how to construct an API object. If you have further questions, please ask in the #kubernetes-client [slack channel](https://github.com/kubernetes/community/blob/master/sig-cli/CONTRIBUTING.md#meet-the-community) and stackoverflow so more experienced python client users can help

/close
