### ISSUE TITLE
minikube 1.3.0 is failing in test

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-client/python#919]
e.g. 

https://travis-ci.org/kubernetes-client/python/jobs/567654355
https://travis-ci.org/kubernetes-client/python-base/jobs/563196332

1.3.0 release note: https://github.com/kubernetes/minikube/blob/master/CHANGELOG.md#version-130---2019-08-05

switching back to 1.2.0 fixes the failure https://github.com/kubernetes-client/python/pull/918

/kind failing-test
/assign @micw523

**Comment by micw523** [comment]
I'm investigating this.

**Comment by micw523** [comment]
Somehow the Kubernetes config fails to find a NodeIP. See https://travis-ci.org/kubernetes-client/python/jobs/567654355#L356
Still investigating

**Comment by yliaog** [comment]
fixed
/close
