### ISSUE TITLE
documentation: remove old client version from the support matrix

### ISSUE THREAD

**Issue by oz123** [kubernetes-client/python#921]
Currently, the README contains a huge list of version of this clients with support for k8s clusters.
I find it odd that no one bothers to clean up... If there is no objection I would like to remove the versions from 1.5 to 1.10. 
I seriously hope no one is still using k8s in these versions. 
A nice side effect of this would be that the table will be completely visible in a 13" screen (not everyone has large HD screens).
Also I would like to clean the table containing support stati for the client. Again, I intend to remove versions 1.0 to 6.0.

@roycaihw @yliaog @micw523 what do you think?

**Comment by roycaihw** [comment]
removing versions <= Kubernetes 1.10 sounds good to me. Officially we support 3 stable major releases in this client, corresponding to 3 minor releases in Kubernetes

**Comment by micw523** [comment]
I’m not sure if some people are still using 1.10 on GKE (which was a thing when we were changing the CI from localkube to  minikube last November). Removing 1.9 or lower sgtm.
