### ISSUE TITLE
retrive master ip from within pod

### ISSUE THREAD

**Issue by Formartha** [kubernetes-client/python#925]
Hi, 
I have a usecase which I need to have access to one of the masters within a cluster. the client runs on one of the pods in the cluster. 

I actually need it's external IP address in order to do it,
how can I do that?

**Comment by oz123** [comment]
Here is how one can do it:
```python
     nodes = api.list_node(pretty=True)
     nodes = [node for node in nodes.items if
                    'node-role.kubernetes.io/master' in node.metadata.labels]
     # get all addresses of the master
     addresses = nodes[0].status.addresses

    [i.address for i in addresses if i.type == "InternalIP"][0] 
```

**Comment by yliaog** [comment]
the code above assumes 1) master's node is listed in the nodes list 2) master's node has the label 'node-role.kubernetes.io/master'

the assumptions may not hold true for some k8s cluster setups

**Comment by oz123** [comment]
@yliaog correct. This assumes that the cluster was installed with kubeadm.
Nevertheless, if you can retrieve the master with some labels, you can later get the IP.
