### ISSUE TITLE
multiple instance of client.Configuration do not work due to shadow copy of authorization information

### ISSUE THREAD

**Issue by zq-david-wang** [kubernetes-client/python#932]
**What happened (please include outputs or screenshots)**:
When trying to create multiple instances of client.Configuration to connect multiple cluster via bearer token, I have to reset token every time before I change cluster. And still cause race issue when connecting apiserver in an async manner, resulting in random 401 reponse from apiserver
**What you expected to happen**:
Each configuration should have its own authorization information, not shared.
**How to reproduce it (as minimally and precisely as possible)**:
create two configuration, each with different api asderss and token
```
            conf = client.Configuration()
            conf.api_key['authorization'] = token
            conf.api_key_prefix["authorization"] = "Bearer"
            conf.host = api
            new_client = client.ApiClient(conf)
```
try connect each cluster, the client with the first configuration would got 401 response
**Anything else we need to know?**:

The class client.Configuration use shadow copy.copy to share some information, but authorization should be use deepcopy.

Client could reset api_key for each configuration to workaround this, via something like
```
 conf.api_key = {'authorization': token}
```

**Environment**:
- Kubernetes version (`kubectl version`):
- OS (e.g., MacOS 10.13.6):
- Python version (`python --version`)
- Python client version (`pip list | grep kubernetes`)

**Comment by yliaog** [comment]
seems to be a problem, would you mind to create a pr to fix this?

**Comment by zq-david-wang** [comment]
@yliaog  I made a PR for this issue https://github.com/kubernetes-client/python/pull/939 
Please help give it a review.
Thx~!
