### ISSUE TITLE
Investigate moving tests from TravisCI to Prow and Testgrid

### ISSUE THREAD

**Issue by scottilee** [kubernetes-client/python#934]
**What is the feature and why do you need it**:
Move away from TravisCI and look into using Kubernetes infrastructure tools. This could provide better visibility and alerts on test failures and could potentially be easier to maintain.

**Describe the solution you'd like to see**:
Instead of using TravisCI and Minikube use Prow, Testgrid, and KIND for CI/CD.

Curious if there is any objection to this and if the pros outweigh the cons. Could also help the other kubernetes clients if they are interested in making a change to their test infrastructure.

**Comment by scottilee** [comment]
These two issues are related:
https://github.com/kubernetes-client/python-base/issues/117
https://github.com/kubernetes-client/python-base/issues/118

**Comment by micw523** [comment]
To use the test-infra tools, we will need dedicated servers to run our tests. Travis CI provides the resources we need at zero cost with relatively simple configuration and reliable up time most of the time.

Also, I don't even know if we could run Python-based jobs on Prow. The server will have to be seriously configured to run the test platform. KIND might be used in place of minikube, but I don't really see the benefit for now.

**Comment by scottilee** [comment]
So that there's no misunderstanding, we do not need "dedicated servers". Kubernetes Test Infra provides everything to run tests.

Additionally, Python-based jobs can run on Prow.

**Comment by scottilee** [comment]
I talked to some people from different Kubneretes client orgs and staying on TravisCI seems to be favored.
