### ISSUE TITLE
[question] why is _from in V1NetworkPolicyIngressRule protected?

### ISSUE THREAD

**Issue by hacker-h** [kubernetes-client/python#936]
Why is the _from field in V1NetworkPolicyIngressRule protected?
What is the correct way to fetch the list of pods affected by a policy without accessing this protected field?
Same question for _except in V1IPBlock

**Comment by roycaihw** [comment]
I think the leading underscore is done by the code generator because the field names conflict with Python builtin functions. The underscore doesn't mean `internal` and doesn't affect the behavior. Feel free to access these fields. 

/close
