### ISSUE TITLE
How to simulate "kubectl apply -f filename.json" using Kubernetes python client

### ISSUE THREAD

**Issue by akshay-r-1996** [kubernetes-client/python#942]
Is there a way to simulate "kubectl apply -f filename.json" using Kubernetes python client, assuming there are multiple objects in json file ( Pods, Deployments, Services, etc. )?

Please help me out with this.

**Comment by akshay-r-1996** [comment]
Okay. 
Is yaml supported?  "kubectl create/apply -f filename.yaml" ( Assuming yaml file has multiple objects )
For JSON also is "kubectl create -f filename.json" is supported?

**Comment by akshay-r-1996** [comment]
How to do it? 1 & 2? In Kubernetes-client Python

**Comment by micw523** [comment]
Check out this file - https://github.com/kubernetes-client/python/blob/master/kubernetes/e2e_test/test_utils.py
You'll need Python client v10 or later. We're currently reworking some examples related to the json/yaml utility.

**Comment by akshay-r-1996** [comment]
Okay, Thank you.
