### ISSUE TITLE
V1Status.status returned by BatchV1Api.delete_namespaced_job is not what's expected

### ISSUE THREAD

**Issue by Heldroe** [kubernetes-client/python#944]
**What happened (please include outputs or screenshots)**:
When deleting a job through `BatchV1Api.delete_namespaced_job`, the `status` property of the returned result ([V1Status](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Status.md#properties)) is a string representing a Python dictionary.

**What you expected to happen**:
I expected the `status` property of the result to be either:
* Following the [`V1Status` documentation](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Status.md#properties): a `str` being either `Success` or `Failure`
* Since the API seems to return more information than just `Success` or `Failure`: a Python dictionary with the data returned by the API
* Since the client likes to deal more with objects than dictionaries: an object representing the status

**How to reproduce it (as minimally and precisely as possible)**:
* Run the job example: https://github.com/kubernetes-client/python/blob/master/examples/job_examples.py
* If you see `Job deleted. status='{u'active': 1, u'startTime': u'2019-08-29T08:54:49Z'}'`, you reproduced (status is a string representing a Python object).

**Environment**:
- OS (e.g., MacOS 10.13.6): `MacOS 10.14.5`
- Python version (`python --version`): `Python 2.7.10`
- Python client version (`pip list | grep kubernetes`): `kubernetes (9.0.0)`
- Kubernetes version (`kubectl version`):
    Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by chowmean** [comment]
I want to take this up. Please suggest what is the expected result from the 3 options that are mentioned.

**Comment by jgoeres** [comment]
/reopen
I ran into this today (using Java, not Pytrhon), Minikube with K8s 1.25.10.
I delete a job with
```BatchV1Api.deleteNamespacedJob```

And this is the resulting V1Status:
```V1Status {
    apiVersion: batch/v1
    code: null
    details: null
    kind: Job
    message: null
    metadata: class V1ListMeta {
        _continue: null
        remainingItemCount: null
        resourceVersion: 125372
        selfLink: null
    }
    reason: null
    status: null
}```
