### ISSUE TITLE
 HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with ur

### ISSUE THREAD

**Issue by 1032231418** [kubernetes-client/python#945]
hi：
   HTTP connections exceed the maximum limit

 HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /api/v1/nodes/xxxx (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),))

**Comment by 1032231418** [comment]
Always prompt for this error by manipulating the label through the interface

**Comment by 1032231418** [comment]
WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /api/v1/nodes/xxx

**Comment by 1032231418** [comment]
Interface version

kubernetes-10.0.1 
urllib3-1.25.3

**Comment by eightlimbed** [comment]
@1032231418 did you ever resolve this? I am getting the same error.
