### ISSUE TITLE
how to query deployments by namespace

### ISSUE THREAD

**Issue by woshiyjs123** [kubernetes-client/python#946]
**Link to the issue (please include a link to the specific documentation or example)**:

**Description of the issue (please include outputs or screenshots if possible)**:
sorry to disturb, i have many deployments running on k8s cluster. i want to get all the deployments info(name, pods etc.). But i check the examples, only find the way to create deployment, no way to query. what should i do to query deployments by namespace.
or how to know which deployment the pod belong to?

**Comment by leavest** [comment]
```
# get deployment by namespace
from kubernetes import client
apis_api = client.AppsV1Api()
resp = apis_api.list_namespaced_deployment(namespace=namespace)
for i in resp.items:
    print(i)
```
```
# the pod owner
from kubernetes import client
core_api = client.CoreV1Api()
apis_api = client.AppsV1Api()
pod = core_api.read_namespaced_pod(name=name, namespace=namespace)
owner_references = pod.metadata.owner_references
if isinstance(owner_references, list):
    owner_name = owner_references[0].name
    owner_kind = owner_references[0].kind
    # owner  StatefulSet
    if owner_kind == 'ReplicaSet':
        replica_set = apis_api.read_namespaced_replica_set(name=owner_name, namespace=namespace)
        owner_references2 = replica_set.metadata.owner_references
        if isinstance(owner_references2, list):
            print(owner_references2[0].name)
        else:
            print(owner_name)
    # owner Deployment
    else:
        print(owner_name)
print(name)
```

**Comment by yliaog** [comment]
@leavest has provided the example, resolving the issue.
/close

**Comment by woshiyjs123** [comment]
> ```
> # get deployment by namespace
> from kubernetes import client
> apis_api = client.AppsV1Api()
> resp = apis_api.list_namespaced_deployment(namespace=namespace)
> for i in resp.items:
>     print(i)
> ```
> 
> ```
> # the pod owner
> from kubernetes import client
> core_api = client.CoreV1Api()
> apis_api = client.AppsV1Api()
> pod = core_api.read_namespaced_pod(name=name, namespace=namespace)
> owner_references = pod.metadata.owner_references
> if isinstance(owner_references, list):
>     owner_name = owner_references[0].name
>     owner_kind = owner_references[0].kind
>     # owner  StatefulSet
>     if owner_kind == 'ReplicaSet':
>         replica_set = apis_api.read_namespaced_replica_set(name=owner_name, namespace=namespace)
>         owner_references2 = replica_set.metadata.owner_references
>         if isinstance(owner_references2, list):
>             print(owner_references2[0].name)
>         else:
>             print(owner_name)
>     # owner Deployment
>     else:
>         print(owner_name)
> print(name)
> ```

thank you very much。
