### ISSUE TITLE
Kubectl apply -k feature

### ISSUE THREAD

**Issue by dosa9876** [kubernetes-client/python#947]
**What is the feature and why do you need it**:
Looking for a kubernetes client python api to achieve 
kubectl apply -k ./

I have a set of manifests which are customized by overlays kustomization.yaml. 

Apologies if it is already supported
**Describe the solution you'd like to see**:
Any API which would accept directory where kustomization.yaml exists and does kubectl apply -k  on it is what am looking for.

**Comment by micw523** [comment]
See this comment: https://github.com/kubernetes-client/python/issues/942#issuecomment-525538966

You probably need to wait for another two major release to see this.

**Comment by yliaog** [comment]
server side apply goes to beta in 1.16. please watch for its progress on main k/k repo
