### ISSUE TITLE
conditional logging in kubernetes/client/rest.py  

### ISSUE THREAD

**Issue by saurabhsinghmaurya** [kubernetes-client/python#949]
**What is the feature and why do you need it**:
kubernetes/client/rest.py  is dumping the rest API response in logs and we do not have any way to disable it. 
kubernetes/client/rest.py line number:219
**Describe the solution you'd like to see**:
Add a method to set logger or log level or remove it.

**Comment by roycaihw** [comment]
Did you enable the debug setting by accident? https://github.com/kubernetes-client/python/blob/a5cb3d788977bcecf43f9be4d4602e7b5bf1e56c/kubernetes/client/configuration.py#L79-L80 

see https://github.com/kubernetes-client/python/blob/a5cb3d788977bcecf43f9be4d4602e7b5bf1e56c/kubernetes/client/configuration.py#L153-L173

**Comment by saurabhsinghmaurya** [comment]
added this fix 

```
from kubernetes import config
client.rest.logger.setLevel(logging.WARNING)
```
