### ISSUE TITLE
[question] How to obtain information about memory/cpu consumption by pod?

### ISSUE THREAD

**Issue by stanhordiyenko** [kubernetes-client/python#950]
Hi,

Could not find how can I obtain information about memory consumption on kubernetes node with kubernetes-client library in Python. I know how to obtain this information with kubectl command. Metrics are collected by Heapster in my kubernetes cluster.

Could you provide me with a piece of code how can I do this via this library?

Thank you.

**Comment by roycaihw** [comment]
Do you mean getting the resource consumption using`kubectl describe node`? IIRU kubectl does some intelligent [calculation](https://github.com/kubernetes/kubernetes/blob/1888745c3db2432a613b2649686ee6bf5c9d2fa1/staging/src/k8s.io/kubectl/pkg/describe/versioned/describe.go#L2993-L3116) based on the information from getting pods and nodes. You can check what API requests kubectl made using the verbose level (e.g. `v=9`), and then try making the same requests using this library

**Comment by 1032231418** [comment]
With the same requirements, access, memory, and CPU usage are good

**Comment by stanhordiyenko** [comment]
@roycaihw thank you for your response, it helped me to identify URLs that `kubectl` is using to obtain metrics from kubernetes cluster. Still I haven't got how to match these URLs to library API? Please advise, thank you.

**Comment by roycaihw** [comment]
tried `kubectl describe node` in a single-node cluster
```
GET https://localhost:6443/api/v1/nodes
GET https://localhost:6443/api/v1/nodes/127.0.0.1
GET https://localhost:6443/api/v1/pods?fieldSelector=spec.nodeName%3D127.0.0.1%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded
GET https://localhost:6443/api/v1/events?fieldSelector=involvedObject.name%3D127.0.0.1%2CinvolvedObject.namespace%3D%2CinvolvedObject.kind%3DNode%2CinvolvedObject.uid%3D127.0.0.1
```

you can check https://github.com/kubernetes-client/python/blob/master/kubernetes/README.md to see which library APIs it made. E.g. `GET /api/v1/nodes` corresponds to `CoreV1Api list_node`; `GET /api/v1/nodes/{name}` corresponds to `CoreV1Api read_node`
