### ISSUE TITLE
Add e2e test for strategic merge patch

### ISSUE THREAD

**Issue by roycaihw** [kubernetes-client/python#951]
Add a test sending (e.g. config map) patches through the same API using:
- JSON patch
- [Strategic merge patch](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md)

make sure the API client is able to set the content type properly according to the request body, and the patches are applied successfully.

ref: https://github.com/kubernetes-client/python/pull/931#discussion_r314435505

**Comment by palnabarun** [comment]
I want to give a shot at this. :)

/assign

**Comment by roycaihw** [comment]
Examples of using these patches:

strategic merge patch: https://github.com/kubernetes-client/python/issues/641#issuecomment-429473349
json patch: https://github.com/kubernetes-client/python/issues/641#issuecomment-468291235

We can have one test sending multiple kinds of patch and make sure nothing fails, or two tests doing the same thing but using different kinds of patch.

**Comment by controller-switch-assignment** [comment]
this issue is marked as good for beginners, but seems old. can I still help as my first issue?

**Comment by pmareke** [comment]
Hi everyone!

After reading the issue, the examples and the e2e tests I would like to give it a try.

As far as I understand I have a couple of e2e tests patching a config map with the 2 strategies right?

Thanks for your time!

**Comment by pmareke** [comment]
Sorry for the multiple pull requests, I made a typo naming the branch.
