### ISSUE TITLE
How to deal with an expired continue token dring list_namespaced_job and silimar calls is not documented

### ISSUE THREAD

**Issue by adamnovak** [kubernetes-client/python#953]
**Link to the issue (please include a link to the specific documentation or example)**:

See [the documentation for list_namespaced_job](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/BatchV1Api.md#list_namespaced_job), and specifically the section on _continue, and specifically the section on dealign with expired tokens:

> If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the kubernetes.client needs a consistent list, it must restart their list without the continue field. Otherwise, the kubernetes.client may send another list request with the token received with the 410 error, ...

**Description of the issue (please include outputs or screenshots if possible)**:

How an expired token manifests at the Python level is not specified. Does the 410 error response from the server result in an ApiError being raised [when the response is received by the RESTClient](https://github.com/kubernetes-client/python/blob/c4883541465fe6a276365bb3e3dfee34c4e0c296/kubernetes/client/rest.py#L221-L222)? If so, then to get the token you would have to:

* Catch the ApiError
* Check its `status` for 410 and its `reason` for `'ResourceExpired'`.
* Look at its `data` field, which contains the body of the error response.
* Somehow extract the new continuation token from the response body.

The documentation does not specify how the token is sent "together with" the error. Is it the entire response body? Is it contained within some field of a serialized object?  If so, what type is it and is there a way to get the Kubernetes Python API to deserialize it for me?

The underlying problem may go back to the actual REST API docs at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#list-job-v1-batch where there is a possible 410 response code documented in the description of the `continue` parameter, but no documentation for it or its body in the table of possible response codes.

I think the answers may be in https://github.com/kubernetes/community/blob/79748734e6225769eb5186d0496adeb9f64789cf/contributors/design-proposals/api-machinery/api-chunking.md#handling-expired-resource-versions which gives an example in which a JSON response body appears to be returned. Is it safe to rely on the response body for this error type always being JSON? If not, is there a class I can use to deserailize it with [`deserialize()`](https://github.com/kubernetes-client/python/blob/c4883541465fe6a276365bb3e3dfee34c4e0c296/kubernetes/client/api_client.py#L228)?

I think @smarterclayton originally wrote up the whole system, and so may have some insight at least on the REST end of things.

**Comment by smarterclayton** [comment]
The continue token is part of all `*List` objects returned by Kubernetes.
Anyone getting a list gets continue tokens

**Comment by adamnovak** [comment]
How do I tell a list returned by `list_namespaced_job` describing a successful next page from a list that represents a 410 error caused by my having submitted an expired continue token?

**Comment by roycaihw** [comment]
iiuc the question is "how to read the `continue` token using the python client in a 410 response from the apiserver"

from a high level, apiserver always [return a response body of `Status` kind when an error occurs](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#response-status-kind), so the client should deserialize the response body into a `Status` object (python [model](https://github.com/kubernetes-client/python/blob/master/kubernetes/client/models/v1_status.py), golang [type](https://github.com/kubernetes/kubernetes/blob/ae99e2d412516fc5bd3d2e600ce7db36cd672319/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L585)) and read the `.metadata.continue` field

you're right that using this client you can catch the ApiError and deserialize the `data` field

it would be better if the client deserializes the Status for you when it sees the http status code >= 300 or < 200. This requires more plumbing:
- verify if the upstream [code generator](https://github.com/OpenAPITools/openapi-generator) supports different response schema based on http status code
- if so, fix kubernetes openapi to specify response schema when a non-2xx code is returned: https://github.com/kubernetes/kubernetes/issues/69014
- regenerate this client library

**Comment by roycaihw** [comment]
@scottilee An example using paging list and showing how to deal with expired continue token may be useful

**Comment by adamnovak** [comment]
Has anyone decided to actually do this? Or should we just close it as being a component of https://github.com/kubernetes/kubernetes/issues/69014 ?

**Comment by adamnovak** [comment]
I don't believe that this has yet been documented/implemented; it is still an open problem.

/remove-lifecycle rotten

**Comment by roycaihw** [comment]
I agree this is still a problem. I'm trying to convert this into a good first issue / help wanted issue, so I'm writing down what I think is needed here. 

I think we first need an example that does the following: 
- send a list request with a expired token that will trigger a 410 (either by sleeping 15 minutes or using a fake token)
- catch the ApiError 
- read the `data` field, either as a dict, or [deserializing](https://github.com/kubernetes-client/python/issues/977#issuecomment-592030030) it into [V1Status](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Status.md)
- read the [`_continue`](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1ListMeta.md) token out of the [metadata](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Status.md)
- send a list request with the continue token to retrieve a inconsistent list.

**Comment by adamnovak** [comment]
I don't think this has yet been addressed.

/remove-lifecycle stale

**Comment by adamnovak** [comment]
/remove-lifecycle stale

This is still outstanding I think
