### ISSUE TITLE
Loading configuration file fails when insecure-skip-tls-verify is false

### ISSUE THREAD

**Issue by ganchurin** [kubernetes-client/python#954]
**What happened**:
Loading configuration file with `config.load_kube_config()` failed with the following error:
```
Traceback (most recent call last):
  File "TestK8Client.py", line 4, in <module>
    config.load_kube_config()
  File "/usr/local/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 649, in load_kube_config
    loader.load_and_set(config)
  File "/usr/local/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 462, in load_and_set
    self._load_cluster_info()
  File "/usr/local/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 433, in _load_cluster_info
    self.verify_ssl = not self._cluster['insecure-skip-tls-verify']
  File "/usr/local/lib/python2.7/site-packages/kubernetes/config/kube_config.py", line 499, in __getitem__
    % (key, self.name))
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected key insecure-skip-tls-verify in [EDITED]/.kube/config/{'cluster': {'insecure-skip-tls-verify': False, 'certificate-authority-data': [EDITED], 'server': [EDITED]}, 'name': [EDITED]}/cluster
```

**How to reproduce it**:
The configuration file must include the following lines:
```
clusters:
- cluster:
    insecure-skip-tls-verify: false
```

**Anything else we need to know?**:
Java-client works fine with the same configuration file.

**Environment**:
- Kubernetes version: v1.11.8
- OS: MacOS 10.14.6
- Python version: 2.7.13
- Python client version: 10.0.1

**Comment by roycaihw** [comment]
I can reproduce this issue with v10.0.1. Interestingly having `insecure-skip-tls-verify: true` works fine. I think there is something wrong in the [getter](https://github.com/kubernetes-client/python-base/blob/4c1ab55553fa7d0479bd5b270c2b303cb056dd4b/config/kube_config.py#L495-L509) 

/good-first-issue

**Comment by ganchurin** [comment]
@roycaihw If there are no objections, I will work on this.

**Comment by micw523** [comment]
Go for it - enjoy!

**Comment by ganchurin** [comment]
@roycaihw The corresponding PR was merged. Do I correctly understand that now I should propagate changes from `python-base` into `python` repository? Thanks!

**Comment by roycaihw** [comment]
Yes, please open a PR to update the python-base submodule, e.g. https://github.com/kubernetes-client/python/pull/911

**Comment by ganchurin** [comment]
Already done in https://github.com/kubernetes-client/python/pull/969

**Comment by micw523** [comment]
/close
Thanks!
