### ISSUE TITLE
read_namespaced_deployment response as json

### ISSUE THREAD

**Issue by tdigangi** [kubernetes-client/python#955]
Is there a method to get a json response from the client `AppsV1Api` _read_namespaced_deployment_ api call. This would be for any GET deployment command.

I would expect there is a way to leverage `-o` similar to the command below.
` kubectl get deploy istio-telemetry -n istio-system -o json`

Please advise if this method exists or is missing,

**Environment**:
- Kubernetes version: 1.13
- OS, MacOS 10.14.6
- Python version: 3.7.3
- Python client version: 10.0.1

**Comment by PortingCode** [comment]
Same problem.

**Comment by roycaihw** [comment]
setting [`_preload_content`](https://github.com/kubernetes-client/python/blob/f4634711ec2decf273e915d42e43824b64a15b87/kubernetes/client/api_client.py#L318-L319) to false gives you the raw json undecoded

**Comment by PortingCode** [comment]
> setting [`_preload_content`](https://github.com/kubernetes-client/python/blob/f4634711ec2decf273e915d42e43824b64a15b87/kubernetes/client/api_client.py#L318-L319) to false gives you the raw json undecoded

Thanks a lot!!! It works well. I could get my custom resources directly.

**Comment by tdigangi** [comment]
@PortingCode would you be able to share an example?

**Comment by tdigangi** [comment]
Example:
`api_response = v1.read_namespaced_deployment(name, namespace, _preload_content=False).read()
`
