### ISSUE TITLE
Chunks functionality for custom objects

### ISSUE THREAD

**Issue by filippomc** [kubernetes-client/python#965]
**What is the feature and why do you need it**:
I'm using the client to retrieve [custom objects](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#list_cluster_custom_object) generated by [Argo workflows](https://argoproj.github.io/argo/). 

The functionality to [get results in chunks](https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks) is missing from the Python api, while is working correctly making the rest calls.

It's important to have the chunks pagination since the system based on argo is generating a fairly big amount of workflows.

**Describe the solution you'd like to see**:
Add the parameters `limit` and `continue_token` to the listing methods like the following:

```python
from __future__ import print_function
import time
import kubernetes.client
from kubernetes.client.rest import ApiException
from pprint import pprint

# Configure API key authorization: BearerToken
configuration = kubernetes.client.Configuration()
configuration.api_key['authorization'] = 'YOUR_API_KEY'
# Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
# configuration.api_key_prefix['authorization'] = 'Bearer'

# create an instance of the API class
api_instance = kubernetes.client.CustomObjectsApi(kubernetes.client.ApiClient(configuration))
group = 'group_example' # str | The custom resource's group name
version = 'version_example' # str | The custom resource's version
plural = 'plural_example' # str | The custom resource's plural name. For TPRs this would be lowercase plural kind.

limit = 10
try:
    api_response_page_1 = api_instance.list_cluster_custom_object(group, version, plural, limit=limit)
    continue_token = api_response_page_1['metadata']['continue']
    api_response_page_2 = api_instance.list_cluster_custom_object(group, version, plural, limit=limit, continue_token=continue_token)
except ApiException as e:
    print("Exception when calling CustomObjectsApi->list_cluster_custom_object: %s\n" % e)
```

Thanks in advance

**Comment by roycaihw** [comment]
The [openapi spec](https://github.com/kubernetes-client/gen/blob/master/openapi/custom_objects_spec.json) that we use to generate the APIs for custom objects needs to be fixed. 

It should have the same `continue` and `limit` parameters for LIST and DELETECOLLECTION paths as the [openapi spec for native types](https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json)

once the openapi spec is fixed, we can regenerate the client so the custom object APIs also have `_continue` and `limit` parameters as the native types (e.g. [here](https://github.com/kubernetes-client/python/blob/a05c3315f00dfff9385f60bc4cad4d856b8e23e9/kubernetes/client/apis/apps_v1_api.py#L2013-L2016))

/assign @scottilee
