### ISSUE TITLE
Examples use deprecated API since k8s v1.16

### ISSUE THREAD

**Issue by micw523** [kubernetes-client/python#967]
**Link to the issue (please include a link to the specific documentation or example)**:
This is the non-critical part of #963 

**Description of the issue (please include outputs or screenshots if possible)**:
In k8s v1.16, a few old APIs got deprecated. See #966 and kubernetes/kubernetes#70672. Also see https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
Need update:
- [ ] In examples/notebooks, the notebook ```create_deployment.ipynb``` uses apps/v1beta1 API.
- [ ] In examples/notebooks, the notebook ```intro_notebook.ipynb``` uses apps/v1beta1 API.

Could use an update:
- [ ] The example ```ingress_create.py``` uses networking/v1beta1 API. This could be upgraded to networking/v1 API.

/assign

**Comment by rajibmitra** [comment]
I would like to take this if no one is working on it actively ?

**Comment by scottilee** [comment]
@rajibmitra hey just checking in to see if you were able to make any progress on this?

**Comment by raunaqness** [comment]
Can I take this up? @scottilee

**Comment by rajibmitra** [comment]
@scottilee  I didn't get time to fix this , unassigned myself. 
@raunaqness or @scottilee  please feel free to work on this.

**Comment by MoShitrit** [comment]
Hey @micw523! 
is anyone working on this issue?
If not- I'd love to help!

**Comment by DivyaNayaka** [comment]
i would like to help
