### ISSUE TITLE
patch_namespaced_config_map merge-patch

### ISSUE THREAD

**Issue by jicowan** [kubernetes-client/python#968]
**Description of the issue (please include outputs or screenshots if possible)**:
I am trying to patch a configmap that has two elements: roles and users.  

```
roles: |
   - some values
users: |
   - some values
```

I want to remove the element users from the configmap when the value is null.  The default patch strategy appears to be a strategic merge, but I want to do a regular merge patch. How do you specify the merge strategy when you call the patch_namespaced_config_map() API?  Do you have to use patch_namespaced_config_map_with_http_info?  And if so, how do you pass the merge strategy to it?

**Comment by roycaihw** [comment]
This is a known issue. There is a PR proposing a fix: https://github.com/kubernetes-client/python/pull/959

**Comment by roycaihw** [comment]
Closing this issue as a dup. Tracking the fix in https://github.com/kubernetes-client/python/pull/959

/close
