### ISSUE TITLE
Incompatibility with K8s v1.16

### ISSUE THREAD

**Issue by avarf** [kubernetes-client/python#973]
**What happened (please include outputs or screenshots)**:
We were using the python client in our components but after trying to install our components on a K8s cluster which is running k8s 1.16 the client fails.
 
**What you expected to happen**:
I expect that it works with the new version of K8s.

**How to reproduce it (as minimally and precisely as possible)**:
Just run some of the functions such as `read_namespaced_stateful_set_scale` on a new K8s.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):
1.16
- OS (e.g., MacOS 10.13.6):
Ubuntu 18.04
- Python version (`python --version`)
3.7.4
- Python client version (`pip list | grep kubernetes`)
kubernetes        10.0.1

**Comment by micw523** [comment]
Please check out the [Readme](https://github.com/kubernetes-client/python/blob/master/README.md).

We are currently working on the client version v11.0, which is compatible with server version v1.15. v1.16 compatibility should come with client version v12.0.

**Comment by roycaihw** [comment]
Yes we haven't generated the client against kubernetes 1.16 yet. Before doing that, I want to send a survey to the community about opinion with major breaking changes caused by the upstream code generator

**Comment by yliaog** [comment]
please wait for python client for 1.16 k8s
/close
