### ISSUE TITLE
Switch Python Testing Package to Pytest

### ISSUE THREAD

**Issue by micw523** [kubernetes-client/python#976]
**What is the feature and why do you need it**:
Currently we are using pytest to test our clients and nose to generate coverage reports for the base repo. The reports can instead be generated with pytest as shown in [here](https://github.com/codecov/example-python).
**Describe the solution you'd like to see**:
Use pytest instead of nose to generate code coverage reports.
/good-first-issue
/help

**Comment by vladdoster** [comment]
Going to take a try at this!

**Comment by palnabarun** [comment]
@vladdoster I am on it already :)
