### ISSUE TITLE
Failed to get a log stream when log line is json type

### ISSUE THREAD

**Issue by mikai21** [kubernetes-client/python#982]
**What happened (please include outputs or screenshots)**:

When I got log like blow (use stream)

```
{"level": "error", "message": "error on app"}
10.216.68.8 - - [12/Oct/2019 12:57:26] "GET /error HTTP/1.1" 200 -
{"level": "error", "message": "error on app"}
10.216.68.9 - - [12/Oct/2019 12:57:26] "GET /error HTTP/1.1" 200 -
10.216.91.1 - - [12/Oct/2019 12:57:30] "GET /readiness HTTP/1.1" 200 -
```

Error occured like below

```
Traceback (most recent call last):
  File "/Users/hoyongpark/Documents/work/dference/groot/.venv/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 149, in stream
    yield self.unmarshal_event(line, return_type)
  File "/Users/hoyongpark/Documents/work/dference/groot/.venv/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 97, in unmarshal_event
    js['raw_object'] = js['object']
KeyError: 'object'
```

**What you expected to happen**:

Get a logs without error

**How to reproduce it (as minimally and precisely as possible)**:

Try to get json type log like this

```
{"level": "error", "message": "error on app"}
```

**Anything else we need to know?**:

```
    def unmarshal_event(self, data, return_type):
        # data => {"level": "error", "message": "error on app"}
        try:
            js = json.loads(data) # OMG data parsed!. js => {'level': "error", 'message': "error on app"}
        except ValueError:
            return data
        js['raw_object'] = js['object'] # js doesn't have 'object'
        if return_type:
            obj = SimpleNamespace(data=json.dumps(js['raw_object']))
            js['object'] = self._api_client.deserialize(obj, return_type)
            if hasattr(js['object'], 'metadata'):
                self.resource_version = js['object'].metadata.resource_version
            # For custom objects that we don't have model defined, json
            # deserialization results in dictionary
            elif (isinstance(js['object'], dict) and 'metadata' in js['object']
                  and 'resourceVersion' in js['object']['metadata']):
                self.resource_version = js['object']['metadata'][
                    'resourceVersion']
        return js
```

**Environment**:
- Kubernetes version (`kubectl version`): 1.15
- OS (e.g., MacOS 10.13.6): MacOS Mojave 10.14.6
- Python version (`python --version`) : Python 3.7.3
- Python client version (`pip list | grep kubernetes`) : 10.0.1

**Comment by mikai21** [comment]
I checked fix like below. But this is a bad solution.
If a log has the 'object' key, then It goes to problem...
```
        except ValueError:
            return data
        if 'object' not in js: # <- insert 2 lines
            return data
        js['raw_object'] = js['object']
```

**Comment by mikai21** [comment]
@Ark-kun 
Thank you for fix this problem.
But, I have some concern about unintentionally action if log is json type string and it has "object" key.
Still failed if log like blow.

```
{"level": "error", "message": "...", "object": 123}
```

I think https://github.com/Ark-kun/python-base/commit/f11587d0e3cedf645ba12fe4dfd7971ee7162c9d is not a fundamental solution.

**Comment by Ark-kun** [comment]
> I think [Ark-kun/python-base@f11587d](https://github.com/Ark-kun/python-base/commit/f11587d0e3cedf645ba12fe4dfd7971ee7162c9d) is not a fundamental solution.

Unfortunately, the fundamental solution might not exist. dictionaries duck typed by design. You cannot type-check them. The code in question decided to do some transformation of the `data['object']`. This design decision might not be easy to undo.

**Comment by Ark-kun** [comment]
Maybe we should just disable unmarshalling for logs.

**Comment by jiahuif** [comment]
That is good enough to give me a ping. Let me recall the context.
