### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

### ISSUE THREAD

**Issue by vmarkovtsev** [kubernetes-client/python#988]
**What happened (please include outputs or screenshots)**:

I am running the first example code from the README and get

```
MaxRetryError: HTTPSConnectionPool(host='...', port=443): Max retries exceeded with url: /api/v1/pods?watch=False (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

**Environment**:
- Kubernetes version (`kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:40:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"
```
- OS (e.g., MacOS 10.13.6): Ubuntu 18.04
- Python version (`python --version`): 3.6
- Python client version (`pip list | grep kubernetes`) today's master

Tested with urllib3 1.24.3 and 1.25.6.

**Comment by micw523** [comment]
Could you take a look at the SSL Error for MacOS in the readme file and see if it applies?

**Comment by vmarkovtsev** [comment]
`OpenSSL 1.1.1  11 Sep 2018`

**Comment by roycaihw** [comment]
I couldn't reproduce the issue from HEAD in a Debian 4.19.67-2 box. I ran the example against a GKE cluster and it worked.

```
$ python --version
Python 3.7.5rc1

$ pip freeze
cachetools==3.1.1
certifi==2019.9.11
chardet==3.0.4
google-auth==1.7.0
idna==2.8
oauthlib==3.1.0
pkg-resources==0.0.0
pyasn1==0.4.7
pyasn1-modules==0.2.7
python-dateutil==2.8.1
PyYAML==5.1.2
requests==2.22.0
requests-oauthlib==1.2.0
rsa==4.0
six==1.13.0
urllib3==1.25.6
websocket-client==0.56.0
```

**Comment by vmarkovtsev** [comment]
I am no longer active on this issue - I fell back to calling `kubectl` with `subprocess`. From what I see in the old issues, this is a recurring problem and a pain in the ass to reproduce. I think that the proper reproduction requires offering docker containers both for the client and the server. No idea how to package a k8s server running in one's org though.
