### ISSUE TITLE
Create a Job from existing Cronjob

### ISSUE THREAD

**Issue by pilosus** [kubernetes-client/python#991]
When working with `kubectl` I can easily create a `Job` from existing `Cronjob` like this:

```
kubectl create job --from=cronjob/<existing-cronjob-name> <your-job-name>
```

How can I do the same using `kubernetes-client`?

**Comment by fabianvf** [comment]
The `kubectl create job --from=cronjob/*` command simply pulls down the cronjob, pulls the `jobTemplate` out of its spec, and then creates the `Job` object using that template. The below code should do the same thing:

```python
from kubernetes import client, config


job_name = 'from-cron-job'
cron_job_name = 'example'
namespace = 'default'

config.load_kube_config()
batch_v1 = client.BatchV1Api()
batch_v1beta1 = client.BatchV1beta1Api()

cron_job = batch_v1beta1.read_namespaced_cron_job(cron_job_name, namespace)

job = client.V1Job(
    api_version='batch/v1',
    kind='Job',
    metadata=client.models.V1ObjectMeta(
        name=job_name,
        # This annotation is added by kubectl, probably best to add it ourselves as well
        annotations={"cronjob.kubernetes.io/instantiate": "manual"}
    ),
    spec=cron_job.spec.job_template.spec
)

result = batch_v1.create_namespaced_job(namespace, job)
print(result)
```

**Comment by pilosus** [comment]
@fabianvf great, thank you!

I've seen the source code for `kubectl create job --from=cronjob/*`. It doesn't translate directly to kubernetes API, just as you have shown here. But wouldn't it be nice to have a shortcut in `kubernetes-client`, an analogue for `--from=cronjob/*` in `client.V1Job`? It could be an optional argument.

**Comment by fabianvf** [comment]
I'll defer to @roycaihw , but my impression is that this sort of higher-level functionality isn't necessarily in scope, this client occupies a space closer to client-go than to kubectl. It would be nice to have a place for these sorts of helpful functions though, I'm not sure if there is one at the moment.

**Comment by roycaihw** [comment]
https://github.com/kubernetes-client/python/tree/master/kubernetes/utils is where we put some helpful high-level functions.

**Comment by yamikarajput546** [comment]
For creating a fresh new cronjob on GKE cluster using bearer token  for authentication you can refer to this:  https://techhub.go1percent.com/dashboard/projects/devops/62a1e1d8f20000af4db0c0cd

**Comment by Razihmad** [comment]
how can i add th

> The `kubectl create job --from=cronjob/*` command simply pulls down the cronjob, pulls the `jobTemplate` out of its spec, and then creates the `Job` object using that template. The below code should do the same thing:
> 
> ```python
> from kubernetes import client, config
> 
> 
> job_name = 'from-cron-job'
> cron_job_name = 'example'
> namespace = 'default'
> 
> config.load_kube_config()
> batch_v1 = client.BatchV1Api()
> batch_v1beta1 = client.BatchV1beta1Api()
> 
> cron_job = batch_v1beta1.read_namespaced_cron_job(cron_job_name, namespace)
> 
> job = client.V1Job(
>     api_version='batch/v1',
>     kind='Job',
>     metadata=client.models.V1ObjectMeta(
>         name=job_name,
>         # This annotation is added by kubectl, probably best to add it ourselves as well
>         annotations={"cronjob.kubernetes.io/instantiate": "manual"}
>     ),
>     spec=cron_job.spec.job_template.spec
> )
> 
> result = batch_v1.create_namespaced_job(namespace, job)
> print(result)
> ```

how can i add time to live for this job created. after this job is finished. it should not be listed in job let say after 1 min

**Comment by gaeljw** [comment]
For the record, I believe setting the `ownerReferences` in the `metadata` is important to get the proper relationship between the `Job` and its parent `CronJob`.

```python
job = V1Job(
 ...
 metadata=V1ObjectMeta(
  ...
  owner_references=[
    V1OwnerReference(
      api_version=cronjob.api_version,
      kind=cronjob.kind,
      name=cronjob_name,
      uid=cronjob.metadata.uid,
    )],
  ),
  ...
)
```
