### ISSUE TITLE
delete_namespaced_job does not document that the 'Foreground' deletion policy does not block

### ISSUE THREAD

**Issue by adamnovak** [kubernetes-client/python#994]
**Link to the issue (please include a link to the specific documentation or example)**:

https://github.com/kubernetes-client/python/blob/7fb3a25176395da26007aec7b4c843aa03514c21/kubernetes/docs/BatchV1Api.md#delete_namespaced_job

**Description of the issue (please include outputs or screenshots if possible)**:

Maybe this is obvious to people who already know things about Kubernetes, but I expected that setting `propagation_policy='Foreground'` in a `delete_namespaced_job()` call would cause the method to block until the job was no longer visible to my application. That is not the meaning of 'Foreground', as documented in the main Kubernetes docs at https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion

I think that the documentation for the method (and likely other deletion methods) should mention that `'Foreground'` deletion is still non-blocking. I want to add that note to the documentation.

Is the right way to make a PR for this to edit the Markdown file(s)? Or is it to edit the Python docstring(s) and then run something to regenerate the Markdown? Or is it to edit some other API definition file?

**Comment by palnabarun** [comment]
@adamnovak The documentation and client code is automatically generated from the OpenAPI specifications of kubernetes api-server. So, editing the Markdown file or Python docstrings would be temporary changes that will eventually be reverted by future client updates.

The correct way to approach this is to update the OpenAPI specifications.

**Comment by adamnovak** [comment]
My PR to fix this at https://github.com/kubernetes/kubernetes/pull/84810 still has not been reviewed, and the documentation at https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/BatchV1Api.md#parameters-2 still does not ref;ect the non-blocvking behavior.

/remove-lifecycle stale

**Comment by palnabarun** [comment]
@adamnovak The PR has had some reviews since then. Can you please resolve those?

> and the documentation at https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/BatchV1Api.md#parameters-2 still does not reflect the non-blocking behavior.

The documentation would be updated whenever a client release is made with the changes you made.

**Comment by adamnovak** [comment]
The PR at https://github.com/kubernetes/kubernetes/pull/84810 is still open and ready for API review, I think.

/remove-lifecycle stale

**Comment by adamnovak** [comment]
/remove-lifecycle stale

I've rebased https://github.com/kubernetes/kubernetes/pull/84810 again in hopes of eliminating the merge conflicts.
