### ISSUE TITLE
AttributeError: 'module' object has no attribute 'select_header_accept'

### ISSUE THREAD

**Issue by hmtai** [kubernetes-client/python#997]
**What happened (please include outputs or screenshots)**:
When I use python SDK to create create a customer resource ,it can not create successfully because `AttributeError`:
```
Traceback (most recent call last):
  File "experiment.py", line 174, in <module>
    create_study_job(k8s_client,spec,version="v1alpha3")
  File "experiment.py", line 100, in create_study_job
    EXPERIMENT_JOB_GROUP, version, namespace, EXPERIMENT_JOB_PLURAL, spec, async_req=True)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 176, in create_namespaced_custom_object
    return self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kubernetes/client/apis/custom_objects_api.py", line 258, in create_namespaced_custom_object_with_http_info
    header_params['Accept'] = self.api_client.\
AttributeError: 'module' object has no attribute 'select_header_accept'
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (`kubectl version`):v1.13.9
- OS (e.g., MacOS 10.13.6):amd ubuntu 16.04.6
- Python version (`python --version`)  Python 2.7.12
- Python client version (`pip list | grep kubernetes`)  kubernetes (10.0.1)

**Comment by roycaihw** [comment]
We have an example of how to create and use custom objects https://github.com/kubernetes-client/python/blob/master/examples/custom_object.py. Could you try it out and see if it works for you?

**Comment by roycaihw** [comment]
Closing based on the inactivity. Please reopen if you have more information

/close

**Comment by AtosGuru** [comment]
When I implement smtp mail sending code using Brevo Server, I met this issue too.
How can I handle this?
