### ISSUE TITLE
I want to get the information without None objects

### ISSUE THREAD

**Issue by zhaoguangqiang** [kubernetes-client/python#999]
**What happened (please include outputs or screenshots)**:
I want to use list_namespaced_replica_set to get the replicaset information, i did it. 
But the result object had many None objects
like that 

.......
 {'annotations': None,
                                               'cluster_name': None,
                                               'creation_timestamp': None,
                                               'deletion_grace_period_seconds': None,
                                               'deletion_timestamp': None,
                                               'finalizers': None,
                                               'generate_name': None,
                                               'generation': None,
                                               'initializers': None,
                                               'labels': {u'app': 'junction-view-server',
                                                          u'pod-template-hash': '5764957b7f'},
                                               'managed_fields': None,
.......

**What you expected to happen**:

I want the result object had no None objects

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

When i use debug log, i found the response objects without None objects

like that

response body: {"kind":"ReplicaSetList","apiVersion":"apps/v1","metadata":{"selfLink":"/apis/apps/v1/namespaces/default/replicasets","resourceVersion":"7964132"},"items":[{"metadata":{"name":"junction-view-server-5764957b7f","namespace":"default","selfLink":"/apis/apps/v1/namespaces/default/replicasets/junction-view-server-5764957b7f","uid":"7ffd3eda-8be9-4511-9dd2-c07aa2705b99","resourceVersion":"7914046","generation":6,"creationTimestamp":"2019-11-03T03:13:54Z","labels":{"app":"junction-view-server","pod-template-hash":"5764957b7f"},"annotations":{"deployment.kubernetes.io/desired-replicas":"1","deployment.kubernetes.io/max-replicas":"2","deployment.kubernetes.io/revision":"7","deployment.kubernetes.io/revision-history":"3,5"},"ownerReferenc.....

I don't know why, i want professional guidance.

Thanks a lot!

**Comment by roycaihw** [comment]
May I ask why do you want to omit the fields with None value? Is it for pretty printing? Or do you want to actually change the object?

**Comment by zhaoguangqiang** [comment]
> May I ask why do you want to omit the fields with None value? Is it for pretty printing? Or do you want to actually change the object?

i read info from list_namespaced_replica_set, then patch_namespaced_deployment it by op:replace resources. I found it report some errors like these:

HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Stdin: ReadBool: expect t or f, but found \", error found in #10 byte of ...|,\"stdin\":\"None\",\"nam|..., bigger context ...|ntainers\":[{\"image_pull_policy\":\"Always\",\"stdin\":\"None\",\"name\":\"junction-view-server\",\"env\":[{\"value|...","code":500}

So i didn't get the None objects from response~

**Comment by roycaihw** [comment]
> i read info from list_namespaced_replica_set, then patch_namespaced_deployment it by op:replace resources

Replicaset and deployment are different APIs. Could you try this example out for reading and patching deployments? https://github.com/kubernetes-client/python/blob/5181d2389eacd92fa0f72237da87286ed0d45a3e/examples/deployment_crud.py#L59-L64
